import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {resolve} from 'node:path';import {core,oracle,memory,string,report,root,enableNativeMath} from './helpers.mjs';import {resourceLoader,nativePool,nativeInstances,prepareBank,compareAnm} from './anm-oracle.mjs';
const ranges=[[0,0x28],[0x28,12],[0x34,0x500],[0x54c,0x28],[0x5c0,4],[0x5ec,12]];
const pointerFields=[0x574,0x578,0x57c,0x580,0x584,0x588,0x58c,0x590,0x594,0x598,0x59c,0x5a0,0x5a4,0x5a8,0x5ac,0x5b0,0x5b4,0x5b8,0x5bc,0x5c4];
test('TH15 complete original animation checkpoint trees import, preserve ordering, restore and reject truncated owners',async()=>{
 const c=await core(),m=await oracle(),manager=c.anm_manager_create(),source=c.anm_checkpoint_create(),imported=c.anm_checkpoint_create(),file=c.anm_tree_file_create(),nm=nativePool(m),loader=resourceLoader(m),out=m.allocate(4),used=m.allocate(4),nativeFile=m.allocate(1024*1024),bytes=readFileSync(resolve(root,'reference/assets/front.anm')),input=c.allocate(Math.max(bytes.length,1024*1024));enableNativeMath(m);let trees=0,nodes=0,checks=0;
 const children=p=>{const result=[];for(let node=m.u32(p+0x598);node;node=m.u32(node+4))result.push(m.u32(m.u32(node)+0x544));return result;};
 const comparePool=(pool,label)=>{const list=[];for(let node=m.u32(nm+0xc3fad8);node;node=m.u32(node+4))list.push(m.u32(node));assert.equal(c.anm_checkpoint_count(pool),list.length,label+' count');for(let i=0;i<list.length;i++){const np=list[i],h=m.u32(np+0x544),vm=c.anm_checkpoint_find(pool,h);assert.equal(c.anm_checkpoint_order(pool,i)>>>0,h,label+' order');assert.ok(vm,label+' handle');compareAnm(c,m,vm,np,label+' vm '+i);assert.deepEqual(Array.from({length:children(np).length},(_,k)=>c.anm_checkpoint_child(pool,h,k)>>>0),children(np),label+' child list');checks+=4;}return list.length;};
 const compareLive=label=>{for(let side=0;side<2;side++){const list=nativeInstances(m,nm,side);assert.equal(c.anm_manager_count(manager,side),list.length);for(let i=0;i<list.length;i++){const np=list[i],h=m.u32(np+0x544);assert.equal(c.anm_manager_order(manager,side,i)>>>0,h,label+' order');compareAnm(c,m,c.anm_manager_find(manager,h),np,label+' live vm '+i);checks+=2;}}};
 const clearLive=()=>{for(let side=0;side<2;side++)while(c.anm_manager_count(manager,side)){const h=c.anm_manager_order(manager,side,0),p=c.anm_manager_find(manager,h),np=m.call(0x488510,{ecx:nm,args:[h]});assert.equal(c.anm_manager_destroy_tree(manager,p),1);m.call(0x488820,{ecx:nm,args:[np],limit:100000000});}};
 try{
  memory(c,input,bytes.length).set(bytes);assert.equal(c.anm_manager_load(manager,3,input,bytes.length),1);const bank=prepareBank(m,loader,'front.anm',bytes,nm,3);m.u32(0x4ca620,0x4e73e8);m.f32(0x4e73e8,1);
  for(const script of [221,241,243,52,56,57])for(let sample=0;sample<4;sample++){
   c.anm_checkpoint_clear(source);m.call(0x489590,{limit:100000000});m.u32(nm+0xc3fad0,new DataView(c.memory.buffer).getUint32(c.anm_checkpoint_generation(source),true));
   const h=c.anm_manager_spawn(manager,3,script,24,2);m.call(0x433020,{ecx:bank,args:[out,script,24,0]});assert.equal(h>>>0,m.u32(out));const vm=c.anm_manager_find(manager,h),np=m.call(0x488510,{ecx:nm,args:[h]});
   new DataView(c.memory.buffer).setInt32(c.anm_vm_timer(vm)+4,37+sample,true);new DataView(c.memory.buffer).setFloat32(c.anm_vm_timer(vm)+8,37.375+sample,true);m.i32(np+0x550,37+sample);m.f32(np+0x554,37.375+sample);
   const saved=c.anm_checkpoint_capture(source,manager,h)>>>0;m.call(0x489740,{ecx:nm,args:[out,np,0,0],limit:100000000});assert.equal(saved,m.u32(out));nodes+=comparePool(source,'capture '+script+'/'+sample);
   assert.equal(c.anm_tree_file_write(file,source,saved,manager),1,string(c,c.anm_checkpoint_error(source)));const encoded=Buffer.from(memory(c,c.anm_tree_file_bytes(file),c.anm_tree_file_size(file))),nativeVm=m.call(0x4885b0,{ecx:nm,args:[saved]});m.u32(used,0);m.call(0x4899f0,{ecx:nm,args:[nativeFile,nativeVm,used],limit:100000000});const original=Buffer.from(m.bytes(nativeFile,m.u32(used)));assert.equal(encoded.length,original.length);
   // Each record has no geometry in this set. Ignore actual self/list pointers
   // while comparing every logical property in every child node.
   assert.equal(encoded.length%0x608,0);for(let at=0;at<encoded.length;at+=0x608){for(const [off,n]of ranges){assert.deepEqual(encoded.subarray(at+off,at+off+n),original.subarray(at+off,at+off+n),'record '+script+'/'+sample+'/'+at+'/'+off.toString(16));checks++;}for(const off of [0x588,0x598]){assert.equal(!!encoded.readUInt32LE(at+off),!!original.readUInt32LE(at+off),'tree link '+script+'/'+sample+'/'+at.toString(16)+'/'+off.toString(16)+' '+encoded.readUInt32LE(at+off).toString(16)+'/'+original.readUInt32LE(at+off).toString(16));checks++;}}
   c.anm_checkpoint_clear(imported);new DataView(c.memory.buffer).setUint32(c.anm_checkpoint_generation(imported),0,true);m.call(0x489590,{limit:100000000});m.u32(nm+0xc3fad0,0);memory(c,input,original.length).set(original);
   const restored=c.anm_tree_file_read(file,imported,input,original.length,manager)>>>0;assert.ok(restored,string(c,c.anm_checkpoint_error(imported)));m.u32(used,0);m.call(0x489bd0,{ecx:nm,args:[out,nativeFile,0,used],limit:100000000});assert.equal(restored,m.u32(out));assert.equal(c.anm_tree_file_consumed(file),original.length);assert.equal(m.u32(used),original.length);nodes+=comparePool(imported,'import '+script+'/'+sample);
   const beforeCount=c.anm_checkpoint_count(imported),beforeGeneration=new DataView(c.memory.buffer).getUint32(c.anm_checkpoint_generation(imported),true);assert.equal(c.anm_tree_file_read(file,imported,input,original.length-1,manager),0);assert.equal(c.anm_checkpoint_count(imported),beforeCount);assert.equal(new DataView(c.memory.buffer).getUint32(c.anm_checkpoint_generation(imported),true),beforeGeneration);checks+=3;
   const live=c.anm_checkpoint_restore(imported,manager,restored)>>>0;m.call(0x489820,{args:[out,restored],limit:100000000});assert.equal(live,m.u32(out));compareLive('restore '+script+'/'+sample);clearLive();trees++;
  }
  report('anm-tree-file',{passed:true,trees,nodes,checks,scope:'Original full recursive 4899f0 and 489bd0 records from actual front.anm child trees; byte comparison excludes host self/list pointers; native imported checkpoint pool order, generated identifiers, child hierarchy and subsequent live restoration queues; truncated input rolls back allocation and generation. Variable geometry tails and gathering particle trees are verified separately.'});
 }finally{c.anm_tree_file_delete(file);c.anm_checkpoint_delete(source);c.anm_checkpoint_delete(imported);c.anm_manager_delete(manager);c.release(input);m.close();}
});
