import test from 'node:test';import assert from 'node:assert/strict';import {core,oracle,memory,report,enableNativeMath} from './helpers.mjs';import {nativeGraphics} from './rendering-oracle.mjs';
function matrix(sample,kind){const b=Buffer.alloc(64);for(let k=0;k<16;k++)b.writeFloatLE(k%5===0?1+(sample%7+kind)*.03125:(sample%13-6+k%5-kind)*.015625,k*4);return b;}
test('TH15 camera projection matches original vector library with perspective and viewport transforms',async()=>{
 const c=await core(),m=await oracle(),camera=c.anm_camera_create(),world=c.allocate(64),pos=c.allocate(12),out=c.allocate(12),viewport=c.allocate(24),np=m.allocate(12),nw=m.allocate(64),nv=m.allocate(64),npr=m.allocate(64),nvp=m.allocate(24),no=m.allocate(12);enableNativeMath(m);const gfx=nativeGraphics(m);let cases=0;
 try{for(let sample=0;sample<4096;sample++){for(const[kind,cp,native]of [[0,world,nw],[1,c.anm_camera_matrix(camera,0),nv],[2,c.anm_camera_matrix(camera,1),npr]]){const data=matrix(sample,kind);memory(c,cp,64).set(data);m.write(native,data);}const position=Buffer.alloc(12);for(let k=0;k<3;k++)position.writeFloatLE((sample%47-23+k*5)*.0625,k*4);memory(c,pos,12).set(position);m.write(np,position);const vp=Buffer.alloc(24);vp.writeUInt32LE(sample%17);vp.writeUInt32LE(sample%13,4);vp.writeUInt32LE(320+sample%769,8);vp.writeUInt32LE(240+sample%541,12);vp.writeFloatLE((sample%7)*.0625,16);vp.writeFloatLE(1-(sample%5)*.0625,20);memory(c,viewport,24).set(vp);m.write(nvp,vp);m.call(gfx.library.exports.get('D3DXVec3Project'),{args:[no,np,nvp,npr,nv,nw]});c.anm_camera_project(camera,pos,world,viewport,out);assert.deepEqual(Buffer.from(memory(c,out,12)),Buffer.from(m.bytes(no,12)),'projection '+sample);cases++;}
 report('anm-camera-projection',{passed:true,cases,originalFunctions:['D3DXVec3Project'],scope:'Exact CPU projection including perspective division, row-vector matrix multiplication and viewport/depth conversion. The original vector library is loaded only into the test oracle.'});
 }finally{c.anm_camera_delete(camera);for(const p of [world,pos,out,viewport])c.release(p);m.close();}
});
test('TH15 camera-facing projected animation quads match original depth culling and geometry',async()=>{
 const c=await core(),m=await oracle(),camera=c.anm_camera_create(),vm=c.anm_vm_create(),parent=c.anm_vm_create(),native=m.allocate(0x608),np=m.allocate(0x608),viewport=c.allocate(24),out=c.allocate(48);enableNativeMath(m);const gfx=nativeGraphics(m);let cases=0,clipped=0;
 try{for(let sample=0;sample<4096;sample++){m.view(native,0x608).fill(0);m.view(np,0x608).fill(0);const vp=c.anm_vm_visual(vm),vars=c.anm_vm_variables(vm),pvars=c.anm_vm_variables(parent),dv=new DataView(c.memory.buffer);const flags=3|(4<<25)|((sample%3)<<21)|(((sample>>4)%3)<<23),rf=0x8000|(sample&32?0x10000:0);dv.setUint32(vp,flags,true);dv.setUint32(vp+4,rf,true);m.u32(native+0x18,flags);m.u32(native+0x1c,rf);for(const[co,no,count]of [[16,0x4ec,3],[40,0x5c,2],[48,0x64,2],[136,0x7c,2]])for(let k=0;k<count;k++){const value=co===40||co===48?.75+(sample%7+k*2)*.125:co===136?8+(sample%13+k*3)*.25:(sample%7-3+k*2)*.0625;dv.setFloat32(vp+co+k*4,value,true);m.f32(native+no+k*4,value);}for(let k=0;k<3;k++){const pos=(sample%31-15+k*7)*.0625,rot=(sample%61-31+k*7)*.0625;dv.setFloat32(vars+64+k*4,pos,true);dv.setFloat32(vars+76+k*4,rot,true);dv.setFloat32(c.anm_vm_translation(vm)+k*4,pos*.5,true);dv.setFloat32(pvars+76+k*4,rot*.75,true);m.f32(native+0x38+k*4,pos);m.f32(native+0x44+k*4,rot);m.f32(native+0x5ec+k*4,pos*.5);m.f32(np+0x44+k*4,rot*.75);const ref=[.0078125,.01171875,.015625][k];dv.setFloat32(c.anm_camera_reference(camera)+k*4,ref,true);m.f32(gfx.view+0x30+k*4,ref);}c.anm_vm_parent(vm,sample&1?parent:0);m.u32(native+0x5b8,sample&1?np:0);for(const[kind,offset]of [[0,0x60],[1,0xa0]]){const data=matrix(sample,kind);memory(c,c.anm_camera_matrix(camera,kind),64).set(data);m.write(gfx.view+offset,data);}const vpBytes=Buffer.alloc(24);vpBytes.writeUInt32LE(640,8);vpBytes.writeUInt32LE(480,12);vpBytes.writeFloatLE(1,20);memory(c,viewport,24).set(vpBytes);m.write(gfx.view+0xe0,vpBytes);const expected=m.call(0x47f0f0,{args:[native]})|0,actual=c.anm_camera_quad(camera,vm,viewport,out);assert.equal(actual,expected,'quad result '+sample);if(!actual){for(let k=0;k<4;k++)assert.deepEqual(Buffer.from(memory(c,out+k*12,12)),Buffer.from(m.bytes(0x5213c0+k*28,12)),'quad '+sample+'/'+k);}else clipped++;cases++;}
 report('anm-projected-quad',{passed:true,cases,clipped,originalFunctions:['0x47f0f0','0x47d6c0','D3DXVec3Project'],scope:'Camera-facing projected sprite size, rotation inheritance, three anchor choices and depth clipping. Does not validate fog colour, final drawing or GPU rasterization.'});
 }finally{c.anm_camera_delete(camera);c.anm_vm_delete(vm);c.anm_vm_delete(parent);c.release(out);c.release(viewport);m.close();}
});
