import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync,readdirSync} from 'node:fs';import {resolve} from 'node:path';
import {core,oracle,memory,root,report} from './helpers.mjs';
test('TH15 sprite binding reproduces original UVs and all three sprite matrices',async()=>{
 const c=await core(),m=await oracle(),bank=m.allocate(0x13c),native=m.allocate(0x608),nameBuffer=m.allocate(256),vtable=m.allocate(0x60),texture=m.allocate(16),vm=c.anm_vm_create();m.u32(texture,vtable);const heap=m.heap;let source,width,height,sprites=0,checks=0;
 m.replace(0x490cf2,'fixture format path',()=>0);m.replace(0x402db0,'read ANM fixture',()=>{const p=m.allocate(source.length);m.write(p,source);if(m.reg('EDX'))m.u32(m.reg('EDX'),source.length);return p;},1);
 const desc=m.registerImport({dll:'fixture',name:'texture description',argc:3,handler:()=>{const p=m.u32(m.reg('ESP')+12);m.view(p,32).fill(0);m.u32(p+24,width);m.u32(p+28,height);return 0;}});m.u32(vtable+0x44,desc);
 for(const address of [0x485a60,0x485c30,0x485c80,0x485820])m.replace(address,'dimension preserving texture allocation',()=>{m.u32(m.u32(m.reg('ESP')+4),texture);return 0;});m.replace(0x403560,'original diagnostic',()=>{throw Error('Original ANM diagnostic');});m.f32(0x51bc04,2);m.u32(0x51bbfc,640);m.u32(0x51bc00,480);
 try{for(const name of readdirSync(resolve(root,'reference/assets')).filter(n=>n.endsWith('.anm')).sort()){
 m.heap=heap;m.view(bank,0x13c).fill(0);source=readFileSync(resolve(root,'reference/assets',name));m.write(nameBuffer,Buffer.from(name+'\0'));m.call(0x485d20,{ecx:bank,args:[nameBuffer]});const a=c.anm_create(),p=c.allocate(source.length);memory(c,p,source.length).set(source);assert.equal(c.anm_open(a,p,source.length),1,name);c.anm_vm_resource(vm,a);let at=0,chunk=0,ns=0,nc=0;
 do{width=source.readUInt16LE(at+10);height=source.readUInt16LE(at+12);const count=source.readUInt16LE(at+4),scripts=source.readUInt16LE(at+6),base=m.u32(bank+0x108);m.call(0x486300,{args:[bank,chunk,ns,nc,base+at]});for(let i=0;i<count;i++){
 const index=ns+i;assert.equal(c.anm_vm_select_sprite(vm,index),1,name+' '+index);m.view(native,0x608).fill(0);assert.equal(m.call(0x477160,{ecx:bank,args:[native,index]})|0,0);const values=c.anm_vm_sprite_values(vm),expected=Buffer.concat([Buffer.from(m.bytes(native+0x3b4,32)),Buffer.from(m.bytes(native+0x7c,8)),Buffer.from(m.bytes(native+0x3dc,64)),Buffer.from(m.bytes(native+0x41c,64)),Buffer.from(m.bytes(native+0x45c,64))]);assert.deepEqual(Buffer.from(memory(c,values,expected.length)),expected,name+' sprite '+index);checks++;sprites++;
 }ns+=count;nc+=scripts;chunk++;const next=source.readUInt32LE(at+36);if(!next)break;at+=next;}while(at<source.length);c.anm_delete(a);c.release(p);
 }report('anm-sprite',{passed:true,checks,sprites,files:48,originalFunction:'0x477160',scope:'Sprite binding UV and matrix construction; low-resolution texture scaling is a later renderer integration check.'});}finally{c.anm_vm_delete(vm);m.close();}
});
