import test from 'node:test';import assert from 'node:assert/strict';import {core,oracle,memory,string,report} from './helpers.mjs';
const instruction=Buffer.from([166,1,8,0,0,0,0,0,3,0,8,0,1,0,0,0,255,255,8,0,0,0,0,0]);
test('TH15 reused animations preserve world translation and distinguish it from child anchors',async()=>{
 const c=await core(),m=await oracle(),vm=c.anm_vm_create(),rng=c.rng_create(),native=m.allocate(0x608),bank=m.allocate(0x13c),table=m.allocate(4),manager=m.allocate(0x187f600),source=m.allocate(instruction.length),p=c.allocate(instruction.length);memory(c,p,instruction.length).set(instruction);m.write(source,instruction);const resource=c.anm_fixture_create(p,instruction.length);m.u32(0x503c18,manager);m.u32(manager+0x187f4d8,bank);m.u32(bank+0x120,table);m.u32(table,source);m.u32(0x4ca620,0x4e73e8);let checks=0;
 try{for(let sample=0;sample<4096;sample++){
  const translation=Buffer.alloc(12),anchor=Buffer.alloc(12);for(let i=0;i<3;i++){translation.writeFloatLE((sample-2093+i*79)*.125,i*4);anchor.writeFloatLE((sample-2027-i*13)*.375,i*4);}m.view(native,0x608).fill(0);m.write(native+0x5ec,translation);m.u32(native+0x24,sample%44);memory(c,c.anm_vm_translation(vm),12).set(translation);new DataView(c.memory.buffer,c.anm_vm_visual(vm)+8,4).setInt32(0,sample%44,true);m.call(0x4773e0,{ecx:bank,args:[native,0]});assert.equal(c.anm_vm_bind(vm,resource,0),1);assert.deepEqual(Buffer.from(memory(c,c.anm_vm_translation(vm),12)),Buffer.from(m.bytes(native+0x5ec,12)));assert.deepEqual(Buffer.from(memory(c,c.anm_vm_visual(vm)+8,4)),Buffer.from(m.bytes(native+0x24,4)));
  m.write(native+0x4ec,anchor);memory(c,c.anm_vm_visual(vm)+16,12).set(anchor);const rate=[.5,1,1.5][sample%3];m.f32(0x4e73e8,rate);assert.equal(c.anm_vm_tick(vm,rng,rate),0,string(c,c.anm_vm_error(vm)));assert.equal(m.call(0x477e10,{ecx:native})|0,0);for(const [cp,at,n]of [[c.anm_vm_translation(vm),0x5ec,12],[c.anm_vm_visual(vm)+16,0x4ec,12],[c.anm_vm_variables(vm)+64,0x38,12],[c.anm_vm_timer(vm),0x54c,20]])assert.deepEqual(Buffer.from(memory(c,cp,n)),Buffer.from(m.bytes(native+at,n)),JSON.stringify({sample,field:at.toString(16)}));checks+=6;
 }report('anm-rebind-translation',{passed:true,cases:4096,checks,originalFunctions:['0x40d680','0x4773e0','0x477e10'],coveredOpcodes:[422],scope:'Layer/world-translation retention on resource binding and nonzero child-anchor distinction during translation-to-position transfer.'});}
 finally{c.anm_vm_delete(vm);c.rng_delete(rng);c.anm_delete(resource);c.release(p);m.close();}
});

