import test from "node:test";import assert from "node:assert/strict";import {readFileSync,readdirSync} from "node:fs";import {resolve} from "node:path";
import {core,oracle,memory,string,root,report,enableNativeMath} from "./helpers.mjs";
import {resource as eclResource,ins as eclIns,bits} from "./ecl-fixtures.mjs";
function resourceLoader(m){const bank=m.allocate(0x13c),path=m.allocate(256),vtable=m.allocate(0x60),texture=m.allocate(16);let source,width,height;m.u32(texture,vtable);
 m.replace(0x490cf2,"fixture format path",()=>0);m.replace(0x402db0,"read ANM fixture",()=>{const p=m.allocate(source.length);m.write(p,source);if(m.reg("EDX"))m.u32(m.reg("EDX"),source.length);return p;},1);
 const desc=m.registerImport({dll:"fixture",name:"texture description",argc:3,handler:()=>{const p=m.u32(m.reg("ESP")+12);m.view(p,32).fill(0);m.u32(p+24,width);m.u32(p+28,height);return 0;}});m.u32(vtable+0x44,desc);
 for(const address of [0x485a60,0x485c30,0x485c80,0x485820])m.replace(address,"dimension preserving texture allocation",()=>{m.u32(m.u32(m.reg("ESP")+4),texture);return 0;});m.replace(0x403560,"original diagnostic",()=>{throw Error("Original ANM diagnostic");});m.f32(0x51bc04,2);m.u32(0x51bbfc,640);m.u32(0x51bc00,480);
 return{bank,load(name,bytes){source=bytes;m.view(bank,0x13c).fill(0);m.write(path,Buffer.from(name+"\0"));m.call(0x485d20,{ecx:bank,args:[path]});let at=0,chunk=0,ns=0,nc=0;do{width=source.readUInt16LE(at+10);height=source.readUInt16LE(at+12);m.call(0x486300,{args:[bank,chunk,ns,nc,m.u32(bank+0x108)+at]});ns+=source.readUInt16LE(at+4);nc+=source.readUInt16LE(at+6);chunk++;const next=source.readUInt32LE(at+36);if(!next)break;at+=next;}while(at<source.length);}};
}
const fields=[[0,0x18,8],[8,0x24,4],[16,0x4ec,12],[28,0x50,12],[40,0x5c,8],[48,0x64,8],[56,0x6c,8],[64,0x74,8],[72,0x84,8],[80,0x3d4,8],[88,0x8c,8],[96,0x538,8],[104,0x3b4,32],[136,0x7c,8],[144,0x3dc,192]];
function compare(c,m,vm,native,label){const vp=c.anm_vm_visual(vm),vars=c.anm_vm_variables(vm);for(const [co,no,n]of fields)assert.deepEqual(Buffer.from(memory(c,vp+co,n)),Buffer.from(m.bytes(native+no,n)),label+" visual "+no.toString(16));for(const [co,no,n]of [[0,0x4ac,32],[64,0x38,12],[76,0x44,12]])assert.deepEqual(Buffer.from(memory(c,vars+co,n)),Buffer.from(m.bytes(native+no,n)),label+" variable "+no.toString(16));assert.equal(c.anm_vm_offset(vm),m.i32(native+0x34),label+" cursor");assert.deepEqual(Buffer.from(memory(c,c.anm_vm_timer(vm),20)),Buffer.from(m.bytes(native+0x54c,20)),label+" timer");}
test("All TH15 animation resource templates and instance binding match original negative-time initialization",async()=>{
 const c=await core(),m=await oracle(),manager=c.anm_manager_create(),nativeManager=m.allocate(0x187f600),loader=resourceLoader(m),native=m.allocate(0x608),vm=c.anm_vm_create();enableNativeMath(m);m.u32(0x503c18,nativeManager);m.u32(0x4ca620,0x4e73e8);m.f32(0x4e73e8,1);const fontBank=m.allocate(0x13c),textManager=m.allocate(0x19270);loader.load("ascii.anm",readFileSync(resolve(root,"reference/assets/ascii.anm")));m.write(fontBank,m.bytes(loader.bank,0x13c));m.u32(0x4e9a58,textManager);m.u32(textManager+0x19258,fontBank);const heap=m.heap;let files=0,templates=0,bindings=0;
 try{for(const name of readdirSync(resolve(root,"reference/assets")).filter(n=>n.endsWith(".anm")).sort()){const bytes=readFileSync(resolve(root,"reference/assets",name)),p=c.allocate(bytes.length);memory(c,p,bytes.length).set(bytes);assert.equal(c.anm_manager_load(manager,files,p,bytes.length),1,name+": "+string(c,c.anm_manager_error(manager)));c.release(p);if(!files)assert.equal(c.anm_manager_fallback(manager,0),1);m.heap=heap;loader.load(name,bytes);m.u32(nativeManager+0x187f4d8,loader.bank);
  const count=m.u32(loader.bank+0x114),base=m.u32(loader.bank+0x10c);for(let i=0;i<count;i++){const np=base+i*0x608;m.call(0x4773e0,{ecx:loader.bank,args:[np,i]});for(const off of [0x54c,0x560]){m.i32(np+off,-2);m.i32(np+off+4,-1);m.f32(np+off+8,-1);}m.call(0x477e10,{ecx:np});const template=c.anm_manager_template(manager,files,i);compare(c,m,template,np,name+" template "+i);templates++;
   for(let k=0;k<3;k++){m.f32(native+0x5ec+k*4,i*3.25-k*7);new DataView(c.memory.buffer).setFloat32(c.anm_vm_translation(vm)+k*4,i*3.25-k*7,true);}m.call(0x40b880,{ecx:loader.bank,args:[native,i]});assert.equal(c.anm_manager_bind(manager,vm,files,i),1);compare(c,m,vm,native,name+" binding "+i);assert.deepEqual(Buffer.from(memory(c,c.anm_vm_translation(vm),12)),Buffer.from(m.bytes(native+0x5ec,12)));bindings++;
  }files++;}
 report("anm-manager-templates",{passed:true,files,templates,bindings,originalFunctions:["0x486110","0x4773e0","0x477e10","0x40b880"],scope:"All original ANM resources initialize negative-time instructions and copy prepared templates into reused live instances. Original GPU texture allocation is replaced by dimension-preserving texture fixtures; this test does not validate drawing."});
 }finally{c.anm_vm_delete(vm);c.anm_manager_delete(manager);m.close();}
});
function ins(op,args=[],time=0,mask=0){const b=Buffer.alloc(8+args.length*4);b.writeInt16LE(op);b.writeUInt16LE(b.length,2);b.writeInt16LE(time,4);b.writeUInt16LE(mask,6);args.forEach((a,i)=>typeof a==="object"?b.writeFloatLE(a.f,8+i*4):b.writeInt32LE(a,8+i*4));return b;}
function fixture(scripts){scripts=scripts.map(s=>Buffer.concat([s,ins(-1)]));const head=Buffer.alloc(124+scripts.length*8),entries=64+4,name=entries+scripts.length*8,sprite=name+4;head.writeUInt32LE(8);head.writeUInt16LE(1,4);head.writeUInt16LE(scripts.length,6);head.writeUInt16LE(16,10);head.writeUInt16LE(16,12);head.writeUInt16LE(1,14);head.writeUInt32LE(name,16);head.writeUInt32LE(sprite,64);head.write("@T",name);head.writeFloatLE(16,sprite+12);head.writeFloatLE(16,sprite+16);let off=head.length;for(let i=0;i<scripts.length;i++){head.writeInt32LE(i,entries+i*8);head.writeUInt32LE(off,entries+i*8+4);off+=scripts[i].length;}return Buffer.concat([head,...scripts]);}
function nativePool(m){const manager=m.allocate(0x1caf980),sentinel=manager+0x187f4c4;m.u32(0x503c18,manager);m.u32(sentinel+4,manager+0xec+0x608);for(let i=0;i<0x1fff;i++){const vm=manager+0xec+i*0x620,node=vm+0x608;m.u32(node,vm);m.u32(node+4,i+1<0x1fff?node+0x620:0);m.u32(node+8,i?node-0x620:sentinel);m.u32(vm+0x61c,i);m.u32(vm+0x34,0xffffffff);}return manager;}
function nativeInstances(m,manager,alternate){const result=[];for(let node=m.u32(manager+(alternate?0xe4:0xdc));node;node=m.u32(node+4))result.push(m.u32(node));return result;}
test("TH15 enemy ECL, movement and animation manager preserve native allocation and draw-queue progression",async()=>{
 const animations=Array.from({length:6},(_,i)=>Buffer.concat([ins(300,[0],-1),ins(304,[7+i],-1),ins(400,[{f:i*.75},{f:i*1.25},{f:0}],-1),...(i<5?[ins(500,[5])]:[]),ins(0,[],1000),ins(1)])),bytes=fixture(animations),script=eclResource({main:Buffer.concat([eclIns(302,[0]),eclIns(306,[0,0]),eclIns(404,[bits(0),bits(.5)]),eclIns(404,[bits(Math.PI),bits(.75)],0,10),eclIns(404,[bits(0),bits(0)],0,20),eclIns(329,[0,bits(1.25),bits(.875)],0,25),eclIns(317,[0,1],0,30),eclIns(10,[],0,1000)])}),c=await core(),m=await oracle(),manager=c.anm_manager_create(),nativeManager=nativePool(m),loader=resourceLoader(m),ap=c.allocate(bytes.length),ep=c.allocate(script.bytes.length),np=m.allocate(script.bytes.length),program=c.program_create(),nativeProgram=m.allocate(0x90),definitions=m.allocate(8),owner=m.allocate(0x574c),name=m.allocate(8),cn=c.allocate(8),request=c.allocate(84),enemyManager=m.allocate(0x200),spell=m.allocate(0x1c8),game=m.allocate(0x28),player=m.allocate(0x16224),runtime=c.enemy_runtime_create(program),projection=c.enemy_runtime_projection(runtime);let frames=0,checks=0;enableNativeMath(m);
 try{memory(c,ap,bytes.length).set(bytes);assert.equal(c.anm_manager_load(manager,0,ap,bytes.length),1,string(c,c.anm_manager_error(manager)));loader.load("enemy-fixture.anm",bytes);m.u32(nativeManager+0x187f4d8,loader.bank);for(let i=0;i<animations.length;i++){const vm=m.u32(loader.bank+0x10c)+i*0x608;m.call(0x4773e0,{ecx:loader.bank,args:[vm,i]});for(const off of [0x54c,0x560]){m.i32(vm+off,-2);m.i32(vm+off+4,-1);m.f32(vm+off+8,-1);}m.call(0x477e10,{ecx:vm});}
  memory(c,ep,script.bytes.length).set(script.bytes);m.write(np,script.bytes);assert.equal(c.program_attach(program,ep,script.bytes.length),0);m.u32(nativeProgram+8,1);m.u32(nativeProgram+0x8c,definitions);m.write(name,Buffer.from("main\0"));memory(c,cn,5).set(Buffer.from("main\0"));m.u32(definitions,name);m.u32(definitions+4,np+script.bytes.readUInt32LE(36));m.u32(enemyManager+0x17c,nativeProgram);m.u32(enemyManager+0x164,loader.bank);m.u32(0x4e9a80,enemyManager);m.u32(0x4e9a70,spell);m.u32(0x4e9a8c,spell);m.u32(0x4e9a68,game);m.u32(0x4e9bb8,player);m.u32(0x521e34,1);m.u32(0x4ca620,0x4e73e8);m.f32(0x4e73e8,1);
  m.replace(0x4594e0,"no player shots in isolated scene",()=>0,7);m.replace(0x455d00,"distant player contact",()=>0,2);m.replace(0x455e10,"distant rectangular player contact",()=>0,3);m.replace(0x476400,"audio output",()=>0,1);m.replace(0x428220,"distortion lookup boundary",()=>0);
  c.enemy_runtime_animation_manager(runtime,manager);const data=Buffer.alloc(84);data.writeInt32LE(1000,20);memory(c,request,84).set(data);assert.equal(c.enemy_runtime_start(runtime,cn,request,117),1);m.call(0x426c60,{ecx:owner,args:[name]});m.u32(owner+0x11f8,nativeProgram);m.view(owner+0x1030,1)[0]=15;m.i32(owner+0x5180,1000);m.i32(owner+0x5184,1000);m.u32(owner+0x5740,117);m.u32(owner+0x526c,0x80008c);new DataView(c.memory.buffer).setUint32(c.enemy_fixture_field(projection,0,9,2),0x80008c,true);for(const[kind,at]of [[9,0x14c8],[10,0x5204],[11,0x5218]])m.write(owner+at,Buffer.from(memory(c,c.enemy_attribute_field(projection,kind),20)));for(const[index,at]of [[0,0x14dc],[1,0x5254]])m.write(owner+at,Buffer.from(memory(c,c.enemy_additional_timer(projection,index),20)));m.u32(player+0x16220,1);
  for(let frame=0;frame<96;frame++){m.u32(owner+0x526c,m.u32(owner+0x526c)&~0x40000);const expected=m.call(0x428830,{ecx:owner})|0,actual=c.enemy_runtime_step(runtime,1,0,0,0,1);assert.equal(actual,expected,"frame "+frame+": "+string(c,c.enemy_runtime_error(runtime)));assert.equal(actual,0);assert.deepEqual(Buffer.from(memory(c,c.enemy_attribute_field(projection,4),64)),Buffer.from(m.bytes(owner+0x1330,64)),"handles "+frame);assert.deepEqual(Buffer.from(memory(c,c.enemy_sprite_size(projection),8)),Buffer.from(m.bytes(owner+0x5164,8)),"enemy size "+frame);assert.deepEqual(Buffer.from(memory(c,c.enemy_motion(projection,0),68)),Buffer.from(m.bytes(owner+0x1250,68)),"motion "+frame);
   for(let alternate=0;alternate<2;alternate++){assert.equal(c.anm_manager_update(manager,alternate,1),1,string(c,c.anm_manager_error(manager)));m.call(alternate?0x487890:0x487740,{ecx:nativeManager});const instances=nativeInstances(m,nativeManager,alternate);assert.equal(c.anm_manager_count(manager,alternate),instances.length,"count "+frame);for(let i=0;i<instances.length;i++){const handle=m.u32(instances[i]+0x544);assert.equal(c.anm_manager_order(manager,alternate,i),handle,"frame "+frame+" group "+alternate+" index "+i+" native "+instances.map(v=>m.u32(v+0x544))+" cpp "+Array.from({length:instances.length},(_,j)=>c.anm_manager_order(manager,alternate,j)));compare(c,m,c.anm_manager_find(manager,handle),instances[i],"frame "+frame+" vm "+handle);assert.deepEqual(Buffer.from(memory(c,c.anm_vm_translation(c.anm_manager_find(manager,handle)),12)),Buffer.from(m.bytes(instances[i]+0x5ec,12)));checks++;}}frames++;
  }report("enemy-animation-manager",{passed:true,frames,checks,originalFunctions:["0x428830","0x4291e0","0x48ca80","0x433020","0x4882e0","0x487740"],scope:"Actual enemy ECL animation creation, directional replacement, scaling, interrupts, movement and animation queue updates. Player collision, audio and distortion are isolated service boundaries; test scripts isolate integration and do not constitute a full stage."});
 }finally{c.enemy_runtime_delete(runtime);c.program_delete(program);c.anm_manager_delete(manager);c.release(ap);c.release(ep);c.release(cn);c.release(request);m.close();}
});
test("TH15 animation manager executes child scripts, detached instances and replacement through original lifecycle",async()=>{
 const scripts=[
 Buffer.concat([ins(300,[0],-1),ins(304,[7],-1),ins(100,[10000,87],-1,1),ins(401,[{f:.125},{f:.25},{f:.375}],-1),ins(500,[1]),ins(505,[2,{f:12},{f:-18}]),ins(504,[3]),ins(0,[],20),ins(1)]),
 Buffer.concat([ins(300,[0],-1),ins(304,[12],-1),ins(509),ins(503,[4]),ins(415,[{f:0},{f:0},{f:.0625}]),ins(0,[],14),ins(1)]),
 Buffer.concat([ins(300,[0],-1),ins(304,[28],-1),ins(509),ins(407,[12,0,{f:24},{f:36},{f:0}]),ins(0,[],18),ins(1)]),
 Buffer.concat([ins(300,[0],-1),ins(304,[35],-1),ins(400,[{f:2},{f:3},{f:4}]),ins(0,[],8),ins(1)]),
 Buffer.concat([ins(300,[0],-1),ins(304,[35],-1),ins(509),ins(100,[10001,159],0,1),ins(0,[],5),ins(1)])
 ],bytes=fixture(scripts),c=await core(),m=await oracle(),manager=c.anm_manager_create(),nativeManager=nativePool(m),loader=resourceLoader(m),out=m.allocate(4),p=c.allocate(bytes.length);m.u32(0x4ca620,0x4e73e8);m.f32(0x4e73e8,1);enableNativeMath(m);let checks=0,frames=0;
 try{memory(c,p,bytes.length).set(bytes);assert.equal(c.anm_manager_load(manager,0,p,bytes.length),1,string(c,c.anm_manager_error(manager)));loader.load("fixture.anm",bytes);m.u32(nativeManager+0x187f4d8,loader.bank);const base=m.u32(loader.bank+0x10c);for(let i=0;i<scripts.length;i++){const np=base+i*0x608;m.call(0x4773e0,{ecx:loader.bank,args:[np,i]});for(const off of [0x54c,0x560]){m.i32(np+off,-2);m.i32(np+off+4,-1);m.f32(np+off+8,-1);}m.call(0x477e10,{ecx:np});}
 const compareAll=label=>{for(let alternate=0;alternate<2;alternate++){const instances=nativeInstances(m,nativeManager,alternate);assert.equal(c.anm_manager_count(manager,alternate),instances.length,label+" count "+alternate);for(let i=0;i<instances.length;i++){const handle=m.u32(instances[i]+0x544);assert.equal(c.anm_manager_order(manager,alternate,i),handle,label+" order "+i);const vm=c.anm_manager_find(manager,handle);assert.ok(vm);compare(c,m,vm,instances[i],label+" vm "+handle);assert.deepEqual(Buffer.from(memory(c,c.anm_vm_translation(vm),12)),Buffer.from(m.bytes(instances[i]+0x5ec,12)),label+" translation");checks++;}}};
 for(let sample=0;sample<32;sample++){const handle=c.anm_manager_spawn(manager,0,0,7,2);assert.ok(handle,string(c,c.anm_manager_error(manager)));m.call(0x433020,{ecx:loader.bank,args:[out,0,7]});assert.equal(handle,m.u32(out));compareAll("spawn "+sample);if(sample%2){const replacement=c.anm_manager_rebind(manager,handle,0);assert.ok(replacement,string(c,c.anm_manager_error(manager)));m.u32(out,handle);m.call(0x488fb0,{ecx:out,args:[0]});assert.equal(replacement,m.u32(out));compareAll("rebind "+sample);}
  for(let frame=0;frame<24;frame++){const rate=sample%3?.5:1;m.f32(0x4e73e8,rate);for(let alternate=0;alternate<2;alternate++){assert.equal(c.anm_manager_update(manager,alternate,rate),1,string(c,c.anm_manager_error(manager)));m.call(alternate?0x487890:0x487740,{ecx:nativeManager});}compareAll("sample "+sample+" frame "+frame);frames++;}
 }report("anm-manager-lifecycle",{passed:true,checks,frames,originalFunctions:["0x433020","0x4882e0","0x488420","0x488fb0","0x477e10","0x487740","0x487890"],scope:"Real child and detached allocation, inherited variables/rotation/translation, four queue orders, script progression, replacement and deferred parent/child destruction. Synthetic ANM scripts isolate lifecycle; actual drawing and full game scenarios remain separate."});
 }finally{c.release(p);c.anm_manager_delete(manager);m.close();}
});

test("TH15 embedded animation roots own pooled children without entering the draw queue",async()=>{
 const scripts=[Buffer.concat([ins(300,[0],-1),ins(304,[7],-1),ins(401,[{f:.125},{f:.25},{f:0}],-1),ins(500,[1]),ins(504,[2]),ins(0,[],1000)]),Buffer.concat([ins(300,[0],-1),ins(304,[12],-1),ins(509),ins(503,[2]),ins(415,[{f:0},{f:0},{f:.0625}]),ins(0,[],1000)]),Buffer.concat([ins(300,[0],-1),ins(304,[35],-1),ins(509),ins(407,[24,0,{f:24},{f:36},{f:0}]),ins(0,[],1000)])],bytes=fixture(scripts),c=await core(),m=await oracle(),manager=c.anm_manager_create(),nativeManager=nativePool(m),loader=resourceLoader(m),p=c.allocate(bytes.length),rootVm=c.anm_vm_create(),nativeRoot=m.allocate(0x608);enableNativeMath(m);m.u32(0x4ca620,0x4e73e8);m.f32(0x4e73e8,1);let checks=0,frames=0;
 try{memory(c,p,bytes.length).set(bytes);assert.equal(c.anm_manager_load(manager,0,p,bytes.length),1);loader.load("embedded.anm",bytes);m.u32(nativeManager+0x187f4d8,loader.bank);for(let i=0;i<scripts.length;i++){const np=m.u32(loader.bank+0x10c)+i*0x608;m.call(0x4773e0,{ecx:loader.bank,args:[np,i]});for(const off of [0x54c,0x560]){m.i32(np+off,-2);m.i32(np+off+4,-1);m.f32(np+off+8,-1);}m.call(0x477e10,{ecx:np});}
 for(let sample=0;sample<32;sample++){m.view(nativeRoot,0x608).fill(0);assert.equal(c.anm_manager_bind(manager,rootVm,0,0),1);m.call(0x40b880,{ecx:loader.bank,args:[nativeRoot,0]});for(let k=0;k<3;k++){const value=sample*.75+k*7;new DataView(c.memory.buffer).setFloat32(c.anm_vm_translation(rootVm)+k*4,value,true);m.f32(nativeRoot+0x5ec+k*4,value);}
  for(let frame=0;frame<32;frame++){assert.equal(c.anm_vm_tick(rootVm,c.anm_manager_random(manager),1),0,string(c,c.anm_vm_error(rootVm)));assert.equal(m.call(0x477e10,{ecx:nativeRoot})|0,0);compare(c,m,rootVm,nativeRoot,"embedded root "+sample+"/"+frame);for(let alternate=0;alternate<2;alternate++){assert.equal(c.anm_manager_update(manager,alternate,1),1,string(c,c.anm_manager_error(manager)));m.call(alternate?0x487890:0x487740,{ecx:nativeManager});const list=nativeInstances(m,nativeManager,alternate);assert.equal(c.anm_manager_count(manager,alternate),list.length);for(let i=0;i<list.length;i++){const h=m.u32(list[i]+0x544);assert.equal(c.anm_manager_order(manager,alternate,i),h);compare(c,m,c.anm_manager_find(manager,h),list[i],"embedded child "+sample+"/"+frame+"/"+i);checks++;}}frames++;}
  assert.equal(c.anm_manager_destroy_tree(manager,rootVm),1);while(m.u32(nativeRoot+0x598))m.call(0x488820,{ecx:nativeManager,args:[m.u32(m.u32(nativeRoot+0x598))]});for(let alternate=0;alternate<2;alternate++){const remaining=nativeInstances(m,nativeManager,alternate);assert.equal(c.anm_manager_count(manager,alternate),remaining.length);for(const np of remaining){const h=m.u32(np+0x544);assert.equal(c.anm_manager_destroy_tree(manager,c.anm_manager_find(manager,h)),1);m.call(0x488820,{ecx:nativeManager,args:[np]});}}assert.equal(c.anm_manager_count(manager,2),0);
 }
 report("anm-manager-embedded-roots",{passed:true,frames,checks,originalFunctions:["0x40b880","0x477e10","0x4882e0","0x487740","0x487890","0x488820"],scope:"Embedded player/bullet-style root animations create real nested pool children and remain outside global draw queues; recursive cleanup preserves root ownership and native slot reuse."});
 }finally{c.anm_vm_delete(rootVm);c.anm_manager_delete(manager);c.release(p);m.close();}
});
