import test from 'node:test';import assert from 'node:assert/strict';import {core,oracle,memory,string,report} from './helpers.mjs';
function nativePool(m){const manager=m.allocate(0x1caf980),sentinel=manager+0x187f4c4;m.u32(0x503c18,manager);m.u32(sentinel+4,manager+0xec+0x608);for(let i=0;i<0x1fff;i++){const vm=manager+0xec+i*0x620,node=vm+0x608;m.u32(node,vm);m.u32(node+4,i+1<0x1fff?node+0x620:0);m.u32(node+8,i?node-0x620:sentinel);m.u32(vm+0x61c,i);m.u32(vm+0x34,0xffffffff);}return manager;}
function order(m,manager,alternate){const result=[];for(let node=m.u32(manager+(alternate?0xe4:0xdc));node;node=m.u32(node+4))result.push(m.u32(m.u32(node)+0x544));return result;}
function nativeAttach(m,child,parent){const old=m.u32(parent+0x598),node=child+0x584;m.u32(node,child);m.u32(node+4,old);m.u32(node+8,parent+0x594);if(old)m.u32(old+8,node);m.u32(parent+0x598,node);m.u32(child+0x5b8,m.u32(parent+0x5b8)||parent);m.u32(child+0x5bc,parent);}
test('TH15 animation registry matches original pool slots, handle generations, overflow, queue ordering and reuse',async()=>{
 const c=await core(),m=await oracle(),registry=c.anm_registry_create(),manager=nativePool(m),out=m.allocate(4),instances=[];let checks=0,allocations=0;
 const allocate=(ordering,i)=>{if(i===128){new DataView(c.memory.buffer).setUint32(c.anm_registry_generation(registry),0x7ffff,true);m.u32(manager+0x1caf970,0x7ffff);}const native=m.call(0x489460)>>>0,vm=c.anm_registry_allocate(registry);assert.equal(c.anm_registry_slot(registry,vm),m.u32(native+0x548),'pool slot '+i);m.u32(native+0x34,0xffffffff);const handle=c.anm_registry_submit(registry,vm,ordering);m.call([0x487bd0,0x487c90,0x487d40,0x487e00][(ordering&4?2:0)+(ordering&2?1:0)],{args:[out,native]});assert.equal(handle,m.u32(out),'generation '+i);assert.equal(c.anm_registry_find(registry,handle),vm);assert.equal(m.call(0x488510,{ecx:manager,args:[handle]}),native);allocations++;checks+=4;return{native,vm,handle};};
 try{for(let i=0;i<8194;i++)instances.push(allocate((i%4)*2,i));for(let alternate=0;alternate<2;alternate++){const expected=order(m,manager,alternate);assert.equal(c.anm_registry_count(registry,alternate),expected.length);assert.deepEqual(Array.from({length:expected.length},(_,i)=>c.anm_registry_order(registry,alternate,i)),expected);checks+=2;}
  const released=[];for(let i=0;i<instances.length;i++)if(i%37===0||i>=8191){const instance=instances[i];assert.equal(c.anm_registry_release(registry,instance.vm,0),1);m.call(0x487eb0,{ecx:manager,args:[instance.native]});assert.equal(c.anm_registry_find(registry,instance.handle),0,'stale C++ handle');assert.equal(m.call(0x488510,{ecx:manager,args:[instance.handle]}),0,'stale native handle');released.push(instance);checks+=3;}
  for(let i=0;i<released.length+3;i++)allocate(i%2?2:4,8194+i);for(let alternate=0;alternate<2;alternate++){const expected=order(m,manager,alternate);assert.equal(c.anm_registry_count(registry,alternate),expected.length);assert.deepEqual(Array.from({length:expected.length},(_,i)=>c.anm_registry_order(registry,alternate,i)),expected);checks+=2;}assert.equal(string(c,c.anm_registry_error(registry)),'');report('anm-registry-pool',{passed:true,allocations,checks,poolCapacity:8191,originalFunctions:['0x489460','0x487bd0','0x487c90','0x487d40','0x487e00','0x488510','0x487eb0'],scope:'Primary animation pool allocation, four registration orders, generation wrap, heap overflow, stale-handle rejection and free-slot reuse. Script binding/execution and GPU drawing are separate integration requirements.'});}
 finally{c.anm_registry_delete(registry);m.close();}
});
test('TH15 animation registry matches original parent/child pause, interrupts, deferred deletion and layer queues',async()=>{
 const c=await core(),m=await oracle(),registry=c.anm_registry_create(),manager=nativePool(m),out=m.allocate(4),instances=[];m.u32(0x4ca620,0x4e73e8);m.f32(0x4e73e8,1);let checks=0;
 const compareOrder=()=>{for(let alternate=0;alternate<2;alternate++){const expected=order(m,manager,alternate);assert.equal(c.anm_registry_count(registry,alternate),expected.length);assert.deepEqual(Array.from({length:expected.length},(_,i)=>c.anm_registry_order(registry,alternate,i)),expected);checks+=2;}};
 try{for(let i=0;i<96;i++){const native=m.call(0x489460)>>>0,vm=c.anm_registry_allocate(registry),ordering=(i%4)*2,visual=c.anm_vm_visual(vm),layer=[0,3,17,24,29,35,37,41][i%8];m.u32(native+0x34,0xffffffff);m.u32(native+0x18,0x70006);m.u32(native+0x1c,0x8000);m.u32(native+0x24,layer);const view=new DataView(c.memory.buffer);view.setUint32(visual,0x70006,true);view.setUint32(visual+4,0x8000,true);view.setInt32(visual+8,layer,true);const handle=c.anm_registry_submit(registry,vm,ordering);m.call([0x487bd0,0x487c90,0x487d40,0x487e00][i%4],{args:[out,native]});assert.equal(handle,m.u32(out));instances.push({native,vm,handle,visual});if(i%8&&i%8!==7){const parent=instances[i-(i%3?1:2)];assert.equal(c.anm_registry_attach(registry,vm,parent.vm),1);nativeAttach(m,native,parent.native);}}
  for(const root of [instances[0],instances[8],instances[16]])for(const paused of [1,0]){assert.equal(c.anm_registry_pause(registry,root.vm,paused),1);m.u32(out,root.handle);m.call(paused?0x488be0:0x488bb0,{ecx:out});for(const instance of instances)assert.equal(new DataView(c.memory.buffer).getUint32(instance.visual,true),m.u32(instance.native+0x18));checks+=instances.length;}
  for(const root of [instances[0],instances[8],instances[16]]){assert.equal(c.anm_registry_interrupt(registry,root.vm,37,0,1),1);m.call(0x488620,{args:[root.handle,37]});for(const instance of instances)assert.equal(c.anm_vm_pending_interrupt(instance.vm),m.i32(instance.native+0x49c));checks+=instances.length;}
  for(let alternate=0;alternate<2;alternate++){assert.equal(c.anm_registry_update(registry,alternate,1),1,string(c,c.anm_registry_error(registry)));m.call(alternate?0x487890:0x487740,{ecx:manager});const first=alternate?35:0,last=alternate?42:35;for(let layer=first;layer<last;layer++){const expected=[];for(let vm=m.u32(manager+0x1c9fc20+layer*0x608+0x5b4);vm;vm=m.u32(vm+0x5b4))expected.push(m.u32(vm+0x544));assert.equal(c.anm_registry_layer_count(registry,layer),expected.length,'layer count '+layer);assert.deepEqual(Array.from({length:expected.length},(_,i)=>c.anm_registry_layer_handle(registry,layer,i)),expected,'layer order '+layer);checks+=2;}}
  for(const root of [instances[0],instances[32],instances[64]]){new DataView(c.memory.buffer).setUint32(root.visual+4,0x8020,true);m.u32(root.native+0x1c,0x8020);}for(let alternate=0;alternate<2;alternate++){assert.equal(c.anm_registry_update(registry,alternate,1),1,string(c,c.anm_registry_error(registry)));m.call(alternate?0x487890:0x487740,{ecx:manager});compareOrder();}
  assert.equal(c.anm_registry_release(registry,instances[8].vm,1),1);m.call(0x488820,{ecx:manager,args:[instances[8].native]});compareOrder();for(let i=0;i<24;i++){const native=m.call(0x489460)>>>0,vm=c.anm_registry_allocate(registry);assert.equal(c.anm_registry_slot(registry,vm),m.u32(native+0x548),'deletion reuse '+i);checks++;}report('anm-registry-lifecycle',{passed:true,checks,initialInstances:96,originalFunctions:['0x488bb0','0x488be0','0x488620','0x487740','0x487890','0x487a60','0x487eb0','0x488820'],scope:'Parent/child tree order, recursive visibility pause, immediate-child interrupt propagation, two update groups, layer remapping and queues, deferred vs direct recursive destruction and subsequent reuse. Instances intentionally have stopped script cursors; real ANM binding and child spawning need their own integration verification.'});}
 finally{c.anm_registry_delete(registry);m.close();}
});
