import test from 'node:test';import assert from 'node:assert/strict';import{readFileSync}from'node:fs';import{resolve}from'node:path';import{core,oracle,memory,string,root,report,enableNativeMath}from'./helpers.mjs';import{resourceLoader,nativePool,prepareBank,compareAnm}from'./anm-oracle.mjs';
test('TH15 chapter reward root draws its default material without selecting or resizing a sprite',async()=>{
 const c=await core(),m=await oracle(),manager=c.anm_manager_create(),renderer=c.anm_renderer_create(),bytes=readFileSync(resolve(root,'reference/assets/front.anm')),p=c.allocate(bytes.length);enableNativeMath(m);let captured=null,checks=0;
 try{memory(c,p,bytes.length).set(bytes);assert.equal(c.anm_manager_load(manager,3,p,bytes.length),1);const nm=nativePool(m),loader=resourceLoader(m),bank=prepareBank(m,loader,'front.anm',bytes,nm,3),native=m.u32(bank+0x10c)+241*0x608,vm=c.anm_manager_template(manager,3,241),device=m.allocate(4),vtable=m.allocate(0x170),view=m.allocate(0xf0),buffer=nm+0x187fc10;m.u32(device,vtable);m.u32(0x4e77d8,device);m.u32(0x4e7ec0,view);m.u32(view+0xe8,640);m.u32(view+0xec,480);
 for(const[off,argc,handler]of[[0xe4,3,()=>0],[0x10c,4,()=>0],[0x114,4,()=>0],[0x104,3,()=>0],[0x164,2,()=>0],[0x14c,5,()=>{const sp=m.reg('ESP'),count=m.u32(sp+12),data=m.u32(sp+16),stride=m.u32(sp+20);captured=Buffer.from(m.bytes(data,count*3*stride));return 0;}]] ){m.u32(vtable+off,m.registerImport({dll:'fixture',name:'default material device '+off,argc,handler}));}
 compareAnm(c,m,vm,native,'chapter root template');const visual=c.anm_vm_visual(vm);assert.equal(new DataView(c.memory.buffer).getInt32(visual+12,true),0);assert.deepEqual(Buffer.from(memory(c,visual+136,8)),Buffer.alloc(8));
 for(const offset of[0,128]){c.anm_renderer_reset(renderer);m.view(nm+0x187fba0,16).fill(255);m.u32(nm+0x187fc08,0);m.u32(nm+0x1bffc0c,buffer);m.u32(nm+0x1bffc10,buffer);m.view(0x5213c0,112).fill(0);for(let i=0;i<4;i++)m.f32(0x5213c0+i*28+12,1);captured=null;const dv=new DataView(c.memory.buffer);dv.setUint32(visual,dv.getUint32(visual,true)|1,true);m.u32(native+0x18,m.u32(native+0x18)|1);dv.setFloat32(c.anm_vm_variables(vm)+64,offset,true);m.f32(native+0x38,offset);dv.setFloat32(c.anm_vm_variables(vm)+68,128,true);m.f32(native+0x3c,128);
 const expected=m.call(0x4817d0,{ecx:nm,args:[native]})|0;m.call(0x47e3f0,{ecx:nm});assert.equal(c.anm_renderer_draw(renderer,vm,1),expected,string(c,c.anm_renderer_error(renderer)));if(captured)assert.deepEqual(Buffer.from(memory(c,c.anm_renderer_vertices(renderer),captured.length)),captured);else assert.equal(c.anm_renderer_count(renderer),0);if(offset===128)assert.ok(captured);compareAnm(c,m,vm,native,'chapter root after draw');checks++;}
 report('anm-default-sprite-material',{passed:true,checks,script:241,originalFunctions:['0x4817d0','0x47dba0'],scope:'Real front.anm chapter reward root before sprite selection: default bank sprite-index material and exact native degenerate vertices/UVs retained.'});
 }finally{c.anm_renderer_delete(renderer);c.anm_manager_delete(manager);c.release(p);m.close();}
});
