import test from 'node:test';import assert from 'node:assert/strict';import{readFileSync}from 'node:fs';import{resolve}from 'node:path';import{core,oracle,memory,string,root,report,enableNativeMath}from './helpers.mjs';import{resourceLoader,nativePool,prepareBank,nativeInstances,compareAnm}from './anm-oracle.mjs';
test('TH15 unloaded animation bank marks exactly the original instances before deferred pool cleanup',async()=>{
 const c=await core(),m=await oracle(),a=c.anm_manager_create(),native=nativePool(m),loader=resourceLoader(m),text=m.allocate(0x19270),out=m.allocate(4),banks=new Map();enableNativeMath(m);m.u32(0x4e9a58,text);m.u32(0x4ca620,0x4e73e8);m.f32(0x4e73e8,1);let checks=0,frames=0;
 const compare=label=>{for(let alt=0;alt<2;alt++){const list=nativeInstances(m,native,alt);assert.equal(c.anm_manager_count(a,alt),list.length,label+' count');for(let i=0;i<list.length;i++){const h=m.u32(list[i]+0x544);assert.equal(c.anm_manager_order(a,alt,i),h,label+' order');compareAnm(c,m,c.anm_manager_find(a,h),list[i],label+' animation '+i);checks++;}}};
 try{for(const[name,id]of[['ascii.anm',5],['front.anm',6],['title.anm',16]]){const bytes=readFileSync(resolve(root,'reference/assets',name)),p=c.allocate(bytes.length);memory(c,p,bytes.length).set(bytes);assert.equal(c.anm_manager_load(a,id,p,bytes.length),1,string(c,c.anm_manager_error(a)));c.release(p);const b=prepareBank(m,loader,name,bytes,native,id);banks.set(id,b);if(id===5){m.u32(text+0x19258,b);c.anm_manager_fallback(a,5);}}
  for(let i=0;i<12;i++){const id=i%2?16:6,script=i%2?89:0,h=c.anm_manager_spawn(a,id,script,7,2);m.call(0x433020,{ecx:banks.get(id),args:[out,script,7]});assert.equal(h,m.u32(out));}compare('created');
  for(let frame=0;frame<12;frame++){for(let alt=0;alt<2;alt++){assert.equal(c.anm_manager_update(a,alt,1),1);m.call(alt?0x487890:0x487740,{ecx:native});}compare('before retirement '+frame);frames++;}
  m.call(0x4889a0,{ecx:native,args:[banks.get(6)]});c.anm_manager_unload(a,6);assert.equal(c.anm_manager_resource_count(a),2);assert.ok(c.anm_manager_retired_resources(a)>0,'resource data retained until queued VMs are deleted');compare('retirement marked');
  for(let frame=0;frame<12;frame++){for(let alt=0;alt<2;alt++){assert.equal(c.anm_manager_update(a,alt,1),1,string(c,c.anm_manager_error(a)));m.call(alt?0x487890:0x487740,{ecx:native});}compare('after retirement '+frame);frames++;}
  assert.equal(c.anm_manager_retired_resources(a),0);m.call(0x4889a0,{ecx:native,args:[banks.get(16)]});c.anm_manager_unload(a,16);compare('second bank retired');for(let alt=0;alt<2;alt++){assert.equal(c.anm_manager_update(a,alt,1),1);m.call(alt?0x487890:0x487740,{ecx:native});}compare('cleaned');assert.equal(c.anm_manager_count(a,2),0);assert.equal(c.anm_manager_retired_resources(a),0);
  report('anm-resource-retirement',{passed:true,frames,checks,originalFunctions:['0x4889a0','0x487740','0x487890'],scope:'Actual front/title/ascii resources, exact native per-resource retirement flags and both deferred animation queues, other-bank survival and handle cleanup. Modern resource backing memory is retained safely until references disappear; GPU release callback and embedded scene owners are separate boundaries.'});
 }finally{c.anm_manager_delete(a);m.close();}
});
