import test from "node:test";import assert from "node:assert/strict";import {readFileSync,readdirSync} from "node:fs";import {resolve} from "node:path";
import {core,oracle,memory,root,report} from "./helpers.mjs";
test("All TH15 ANM v8 resources match original sprite UVs and script tables",async()=>{
 const c=await core(),m=await oracle(),manager=m.allocate(0x13c),path=m.allocate(256),vtable=m.allocate(0x60),texture=m.allocate(16);m.u32(texture,vtable);const heap=m.heap;let source,width,height;let sprites=0,scripts=0,chunks=0;const resources=[];
 m.replace(0x490cf2,"fixture format path",()=>0);
 m.replace(0x402db0,"read ANM fixture",()=>{const p=m.allocate(source.length);m.write(p,source);if(m.reg("EDX"))m.u32(m.reg("EDX"),source.length);return p;},1);
 const desc=m.registerImport({dll:"fixture",name:"texture description",argc:3,handler:()=>{const p=m.u32(m.reg("ESP")+12);m.view(p,32).fill(0);m.u32(p+24,width);m.u32(p+28,height);return 0;}});m.u32(vtable+0x44,desc);
 for(const address of [0x485a60,0x485c30,0x485c80,0x485820])m.replace(address,"dimension preserving texture allocation",()=>{m.u32(m.u32(m.reg("ESP")+4),texture);return 0;});
 m.replace(0x403560,"original diagnostic",()=>{throw Error("Original ANM diagnostic");});m.f32(0x51bc04,2);m.u32(0x51bbfc,640);m.u32(0x51bc00,480);
 try{for(const name of readdirSync(resolve(root,"reference/assets")).filter(n=>n.endsWith(".anm")).sort()){m.heap=heap;m.view(manager,0x13c).fill(0);source=readFileSync(resolve(root,"reference/assets",name));m.write(path,Buffer.from(name+"\0"));m.call(0x485d20,{ecx:manager,args:[path]});const a=c.anm_create(),p=c.allocate(source.length);memory(c,p,source.length).set(source);assert.equal(c.anm_open(a,p,source.length),1,name);assert.equal(c.anm_count(a,0),m.u32(manager+0x110),name+" textures");assert.equal(c.anm_count(a,1),m.u32(manager+0x118),name+" sprites");assert.equal(c.anm_count(a,2),m.u32(manager+0x114),name+" scripts");let at=0,chunk=0,ns=0,nc=0;do{width=source.readUInt16LE(at+10);height=source.readUInt16LE(at+12);const spriteCount=source.readUInt16LE(at+4),scriptCount=source.readUInt16LE(at+6),base=m.u32(manager+0x108);m.call(0x486300,{args:[manager,chunk,ns,nc,base+at]});
  for(let i=0;i<spriteCount;i++){const pointer=c.anm_sprite(a,ns+i),got=Buffer.from(memory(c,pointer,40)),original=Buffer.from(m.bytes(m.u32(manager+0x11c)+(ns+i)*0x44,0x44));assert.equal(got.readUInt32LE(4),chunk);for(const [cpp,native] of [[16,56],[20,52],[24,36],[28,40],[32,44],[36,48]])assert.equal(got.readUInt32LE(cpp),original.readUInt32LE(native),name+" sprite "+(ns+i)+" field "+cpp);sprites++;}
  for(let i=0;i<scriptCount;i++){const n=nc+i,length=c.anm_script_size(a,n),native=m.u32(m.u32(manager+0x120)+n*4);assert.deepEqual(Buffer.from(memory(c,c.anm_script(a,n),length)),Buffer.from(m.bytes(native,length)),name+" script "+n);scripts++;}
  ns+=spriteCount;nc+=scriptCount;chunk++;chunks++;const next=source.readUInt32LE(at+36);if(!next)break;at+=next;}while(at<source.length);resources.push({name,textures:chunk,sprites:ns,scripts:nc});c.anm_delete(a);c.release(p);}
 report("anm-resource",{passed:true,files:resources.length,chunks,sprites,scripts,originalFunctions:["0x485d20","0x486300","0x486870"],graphics:"GPU texture allocation replaced with dimension-preserving test doubles; original script table and UV computation executed.",resources});
 }finally{m.close();}
});
