import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {resolve} from 'node:path';import {core,oracle,memory,string,root,report,enableNativeMath,enableOriginalVectorMath} from './helpers.mjs';import {resourceLoader,nativePool,nativeInstances,prepareBank,compareAnm} from './anm-oracle.mjs';
test('TH15 animation gathering callbacks preserve original particle handles, random stream, curves and lifetime',async()=>{
 const scenarios=Number(process.env.TH15_GATHER_SCENARIOS||4);let frames=0,checks=0;
 for(let scenario=0;scenario<scenarios;scenario++){
 const c=await core(),m=await oracle();enableNativeMath(m);const lib=enableOriginalVectorMath(m);for(const entry of m.image.imports)if(entry.dll==='d3dx9_43.dll'&&entry.name==='D3DXVec3Normalize')m.u32(entry.address,lib.exports.get(entry.name));
 const am=c.anm_manager_create(),nm=nativePool(m),loader=resourceLoader(m),owner=m.allocate(0x1c),native=m.allocate(0x608),vm=c.anm_vm_create();let effects=0,effectBank=0;
 try{
 for(const[name,id]of [['ascii.anm',2],['effect.anm',8]]){const bytes=readFileSync(resolve(root,'reference/assets',name)),p=c.allocate(bytes.length);memory(c,p,bytes.length).set(bytes);assert.equal(c.anm_manager_load(am,id,p,bytes.length),1,string(c,c.anm_manager_error(am)));c.release(p);const bank=prepareBank(m,loader,name,bytes,nm,id);if(id===2){c.anm_manager_fallback(am,id);const text=m.allocate(0x19270);m.u32(0x4e9a58,text);m.u32(text+0x19258,bank);}else {m.u32(owner+0xc,bank);effectBank=bank;}}
 m.u32(0x4e9a78,owner);m.u32(0x4ca620,0x4e73e8);m.f32(0x4e73e8,1);m.call(0x40b880,{ecx:effectBank,args:[native,0]});m.i32(native+0x34,-1);m.u32(native+0x5d0,2);m.u32(native+0x5d8,2);m.u32(native+0x5dc,2);m.u32(native+0x5e0,1);m.u32(native+0x5e4,1);effects=c.anm_scene_effects_create(am,8);c.anm_vm_object_host(vm,0);assert.equal(c.anm_scene_effects_configure(effects,vm,1),1);m.call(0x407b80,{ecx:native});
 // Use the manager template's host on an otherwise scriptless parent VM.
 const template=c.anm_manager_template(am,8,0);c.anm_manager_bind(am,vm,8,0);assert.equal(c.anm_scene_effects_configure(effects,vm,1),1);m.i32(native+0x34,0);m.i32(native+0x28,8);m.i32(native+0x30,0);
 // Interrupt script 0 remains a stable parent; use direct update entry to isolate callback state.
 const gameSeed=Buffer.alloc(8),visualSeed=Buffer.alloc(8);gameSeed.writeUInt16LE(1997+scenario*7349);gameSeed.writeUInt32LE(13,4);visualSeed.writeUInt16LE(431+scenario*919);visualSeed.writeUInt32LE(71,4);memory(c,c.anm_manager_environment(am),8).set(gameSeed);memory(c,c.anm_manager_random(am),8).set(visualSeed);m.write(0x4e9a48,gameSeed);m.write(0x4e9a40,visualSeed);
 const vars=c.anm_vm_variables(vm),vp=c.anm_vm_visual(vm),duration=20+scenario*9,rate=[1,.5,1.25,.25][scenario%4];let dv=new DataView(c.memory.buffer);dv.setInt32(vars,duration,true);m.i32(native+0x4ac,duration);dv.setFloat32(vars+40,Math.fround(.125*scenario),true);m.f32(native+0x4d4,Math.fround(.125*scenario));dv.setFloat32(vars+84,Math.fround(.375+scenario*.125),true);m.f32(native+0x4c,Math.fround(.375+scenario*.125));dv.setUint32(vp+96,0xdecf592e,true);m.u32(native+0x538,0xdecf592e);for(let i=0;i<3;i++){const value=[17,96,0][i];dv.setFloat32(c.anm_vm_translation(vm)+i*4,value,true);m.f32(native+0x5ec+i*4,value);}
 c.anm_vm_slowdown(vm,scenario*.125);m.f32(native+0x5c0,scenario*.125);m.f32(0x4e73e8,rate);assert.equal(c.anm_manager_update(am,0,rate),1);
 for(let frame=0;frame<Math.ceil(260/rate);frame++){
 if(frame===30){assert.equal(c.anm_scene_effects_interrupt(effects,vm,1,rate),1);m.call(0x408820,{ecx:native,edx:1});}else if(frame===12){assert.equal(c.anm_scene_effects_interrupt(effects,vm,3,rate),1);m.call(0x408820,{ecx:native,edx:3});}
 const expected=m.call(0x407c10,{ecx:native}),actual=c.anm_scene_effects_update(effects,vm,rate);assert.equal(actual,expected===0?0:1,scenario+'/'+frame+' callback return');
 const gp=c.anm_vm_gather(vm),np=m.u32(native+0x5c4);assert.deepEqual(Buffer.from(memory(c,gp,0x193c)),Buffer.from(m.bytes(np,0x193c)),scenario+'/'+frame+' gathering state');assert.deepEqual(Buffer.from(memory(c,c.anm_manager_environment(am),8)),Buffer.from(m.bytes(0x4e9a48,8)),scenario+'/'+frame+' game RNG');assert.deepEqual(Buffer.from(memory(c,c.anm_manager_random(am),8)),Buffer.from(m.bytes(0x4e9a40,8)),scenario+'/'+frame+' visual RNG');checks+=4;frames++;if(expected)break;
 if(frame===19){
  const checkpoint=c.anm_checkpoint_create(),out=m.allocate(4),file=c.anm_tree_file_create(),fileInput=c.allocate(1024*1024),nativeFile=m.allocate(1024*1024),used=m.allocate(4);try{
   let saved=c.anm_checkpoint_capture_vm(checkpoint,am,vm)>>>0;m.call(0x489740,{ecx:nm,args:[out,native,0,0]});assert.equal(saved,m.u32(out),'gather snapshot root');
   const snapshots=[];for(let node=m.u32(nm+0xc3fad8);node;node=m.u32(node+4))snapshots.push(m.u32(node));assert.equal(c.anm_checkpoint_count(checkpoint),snapshots.length);
   snapshots.forEach((np,i)=>{const h=m.u32(np+0x544),savedVm=c.anm_checkpoint_find(checkpoint,h);assert.equal(c.anm_checkpoint_order(checkpoint,i)>>>0,h);compareAnm(c,m,savedVm,np,'gather snapshot '+i);assert.deepEqual(Buffer.from(memory(c,c.anm_vm_age(savedVm),20)),Buffer.from(m.bytes(np+0x560,20)));checks++;});
   const savedVm=c.anm_checkpoint_find(checkpoint,saved),savedNative=m.call(0x4885b0,{ecx:nm,args:[saved]});assert.deepEqual(Buffer.from(memory(c,c.anm_vm_gather(savedVm),0x193c)),Buffer.from(m.bytes(m.u32(savedNative+0x5c4),0x193c)),'gather saved independent handles');

   assert.equal(c.anm_tree_file_write(file,checkpoint,saved,am),1,string(c,c.anm_checkpoint_error(checkpoint)));m.u32(used,0);m.call(0x4899f0,{ecx:nm,args:[nativeFile,savedNative,used],limit:100000000});const original=Buffer.from(m.bytes(nativeFile,m.u32(used))),encoded=Buffer.from(memory(c,c.anm_tree_file_bytes(file),c.anm_tree_file_size(file)));assert.equal(encoded.length,original.length,'gather file length');assert.deepEqual(encoded.subarray(0x608,0x608+0x193c),original.subarray(0x608,0x608+0x193c),'gather file state and particle presence');for(const [off,n]of [[0,0x28],[0x28,12],[0x34,0x500],[0x54c,0x28],[0x5c0,4],[0x5c8,4],[0x5ec,12]])assert.deepEqual(encoded.subarray(off,off+n),original.subarray(off,off+n),'gather file parent '+off.toString(16));for(let at=0x608+0x193c;at<encoded.length;at+=0x608)for(const [off,n]of [[0,0x28],[0x28,12],[0x34,0x500],[0x54c,0x28],[0x5c0,4],[0x5ec,12]])assert.deepEqual(encoded.subarray(at+off,at+off+n),original.subarray(at+off,at+off+n),'gather file particle '+at+'/'+off);
   c.anm_checkpoint_clear(checkpoint);new DataView(c.memory.buffer).setUint32(c.anm_checkpoint_generation(checkpoint),0,true);m.call(0x489590,{limit:100000000});m.u32(nm+0xc3fad0,0);memory(c,fileInput,original.length).set(original);saved=c.anm_tree_file_read(file,checkpoint,fileInput,original.length,am)>>>0;assert.ok(saved,string(c,c.anm_checkpoint_error(checkpoint)));assert.equal(c.anm_tree_file_consumed(file),original.length);m.u32(used,0);m.call(0x489bd0,{ecx:nm,args:[out,nativeFile,0,used],limit:100000000});assert.equal(saved,m.u32(out));assert.equal(m.u32(used),original.length);const loadedNative=m.call(0x4885b0,{ecx:nm,args:[saved]}),loadedVm=c.anm_checkpoint_find(checkpoint,saved);compareAnm(c,m,loadedVm,loadedNative,'imported gathering');assert.deepEqual(Buffer.from(memory(c,c.anm_vm_gather(loadedVm),0x193c)),Buffer.from(m.bytes(m.u32(loadedNative+0x5c4),0x193c)),'imported gathering fresh particle handles');checks+=10;
   const restored=c.anm_checkpoint_restore(checkpoint,am,saved)>>>0;m.call(0x489820,{args:[out,saved]});assert.equal(restored,m.u32(out),'gather restore root');const rv=c.anm_manager_find(am,restored),rn=m.call(0x488510,{ecx:nm,args:[restored]});compareAnm(c,m,rv,rn,'gather restored root');assert.deepEqual(Buffer.from(memory(c,c.anm_vm_gather(rv),0x193c)),Buffer.from(m.bytes(m.u32(rn+0x5c4),0x193c)),'gather restored independent handles');
   assert.equal(c.anm_manager_destroy_tree(am,rv),1);m.call(0x488820,{ecx:nm,args:[rn]});checks+=4;
  }finally{c.anm_tree_file_delete(file);c.release(fileInput);c.anm_checkpoint_delete(checkpoint);}
 }
 assert.equal(c.anm_manager_update(am,0,rate),1,string(c,c.anm_manager_error(am)));m.call(0x487740,{ecx:nm});const list=nativeInstances(m,nm,0);assert.equal(c.anm_manager_count(am,0),list.length);list.forEach((n,i)=>{const h=m.u32(n+0x544);assert.equal(c.anm_manager_order(am,0,i)>>>0,h);const child=c.anm_manager_find(am,h);compareAnm(c,m,child,n,scenario+'/'+frame+' particle '+i);assert.deepEqual(Buffer.from(memory(c,c.anm_vm_age(child),20)),Buffer.from(m.bytes(n+0x560,20)),scenario+'/'+frame+' particle age '+i);checks++;});
 }
 }finally{if(effects)c.anm_scene_effects_delete(effects);c.anm_vm_delete(vm);c.anm_manager_delete(am);m.close();}
 }
 report('anm-gathering',{passed:true,scenarios,frames,checks,originalFunctions:['0x407b80','0x407c10','0x408d10','0x408ea0','0x408f80'],scope:'Actual effect ANM particle scripts: callback allocation, centers, 200 independent handles, phases, Hermite positions and tangents, game/visual RNG streams, colors, inherited slowdown, separate ANM lifetime and retirement. Includes native 4899f0/489bd0 file encoding/import, 408930 gathering payload and fresh particle identities, live particle snapshot capture/restore handles, pool ordering and effect destructor behavior and interrupt age advance. Overlay/trail effect variants remain separate.'});
});
