import test from'node:test';import assert from'node:assert/strict';import{readFileSync}from'node:fs';import{resolve}from'node:path';import{core,oracle,memory,string,report,root,enableNativeMath}from'./helpers.mjs';import{resourceLoader,nativePool,prepareBank,nativeInstances,compareAnm}from'./anm-oracle.mjs';
test('TH15 chapter animation snapshots match original separate pool, deep children, restore order and generation wrap',async()=>{
 const c=await core(),m=await oracle(),manager=c.anm_manager_create(),checkpoint=c.anm_checkpoint_create(),nm=nativePool(m),loader=resourceLoader(m),out=m.allocate(4),data=readFileSync(resolve(root,'reference/assets/front.anm')),p=c.allocate(data.length);enableNativeMath(m);let captures=0,restores=0,checks=0;
 try{memory(c,p,data.length).set(data);assert.equal(c.anm_manager_load(manager,3,p,data.length),1);const bank=prepareBank(m,loader,'front.anm',data,nm,3);m.u32(0x4ca620,0x4e73e8);m.f32(0x4e73e8,1);m.u32(nm+0xc3facc,0);m.u32(nm+0xc3fad0,0);m.u32(nm+0xc3fad8,0);m.u32(nm+0xc3fadc,0);
 const children=n=>{let result=[];for(let node=m.u32(n+0x598);node;node=m.u32(node+4))result.push(m.u32(m.u32(node)+0x544));return result;};
 const compareSnapshot=label=>{let native=[];for(let node=m.u32(nm+0xc3fad8);node;node=m.u32(node+4))native.push(m.u32(node));assert.equal(c.anm_checkpoint_count(checkpoint),native.length,label+' count');native.forEach((np,i)=>{const handle=m.u32(np+0x544);assert.equal(c.anm_checkpoint_order(checkpoint,i)>>>0,handle,label+' order');const vm=c.anm_checkpoint_find(checkpoint,handle);assert.ok(vm);compareAnm(c,m,vm,np,label+' snapshot '+i);assert.deepEqual(Array.from({length:children(np).length},(_,j)=>c.anm_checkpoint_child(checkpoint,handle,j)>>>0),children(np),label+' snapshot children');checks++;});};
 const compareLive=label=>{for(let alt=0;alt<2;++alt){const list=nativeInstances(m,nm,alt);assert.equal(c.anm_manager_count(manager,alt),list.length,label+' live count');list.forEach((np,i)=>{const handle=m.u32(np+0x544),vm=c.anm_manager_find(manager,handle);assert.equal(c.anm_manager_order(manager,alt,i)>>>0,handle,label+' live order');compareAnm(c,m,vm,np,label+' live '+i);assert.deepEqual(Array.from({length:children(np).length},(_,j)=>c.anm_registry_child_handle(c.anm_manager_registry(manager),vm,j)>>>0),children(np),label+' live children');checks++;});}};
 const handles=[];for(let sample=0;sample<12;++sample){const script=sample%3===0?241:sample%3===1?221:243,handle=c.anm_manager_spawn(manager,3,script,24,2);m.call(0x433020,{ecx:bank,args:[out,script,24,0],limit:10000000});assert.equal(handle,m.u32(out));handles.push(handle);}
 compareLive('initial');
 for(let sample=0;sample<5;++sample){if(sample===3){new DataView(c.memory.buffer).setUint32(c.anm_checkpoint_generation(checkpoint),0x3ffff,true);m.u32(nm+0xc3fad0,0x3ffff);}
  c.anm_checkpoint_clear(checkpoint);m.call(0x489590,{limit:100000000});
  for(let i=0;i<handles.length;++i){const handle=handles[i],vm=c.anm_manager_find(manager,handle);if(!vm)continue;const np=m.call(0x488510,{ecx:nm,args:[handle]})>>>0,ordering=(i%4)*2;new DataView(c.memory.buffer).setInt32(c.anm_vm_timer(vm)+4,37+i,true);new DataView(c.memory.buffer).setFloat32(c.anm_vm_timer(vm)+8,37.625+i,true);m.i32(np+0x550,37+i);m.f32(np+0x554,37.625+i);c.anm_vm_ordering(vm,ordering);m.u32(np+0x534,ordering);const saved=c.anm_checkpoint_capture(checkpoint,manager,handle)>>>0;m.call(0x489740,{ecx:nm,args:[out,np,0,0],limit:100000000});assert.equal(saved,m.u32(out));captures++;}
  compareSnapshot('capture '+sample);
  // Destroy the live world: saved trees must retain their own geometry/data.
  for(let alt=0;alt<2;++alt)while(c.anm_manager_count(manager,alt)){const h=c.anm_manager_order(manager,alt,0),vm=c.anm_manager_find(manager,h),np=m.call(0x488510,{ecx:nm,args:[h]})>>>0;assert.equal(c.anm_manager_destroy_tree(manager,vm),1);m.call(0x488820,{ecx:nm,args:[np],limit:100000000});}
  compareSnapshot('live destroyed '+sample);handles.length=0;
  const roots=[];for(let i=0;i<c.anm_checkpoint_count(checkpoint);++i){const h=c.anm_checkpoint_order(checkpoint,i)>>>0,np=m.call(0x4885b0,{ecx:nm,args:[h]})>>>0;if(!m.u32(np+0x5bc))roots.push(h);}
  for(const h of roots){const handle=c.anm_checkpoint_restore(checkpoint,manager,h);assert.ok(handle,string(c,c.anm_checkpoint_error(checkpoint)));m.call(0x489820,{args:[out,h],limit:100000000});assert.equal(handle>>>0,m.u32(out));handles.push(handle);restores++;}
  compareLive('restore '+sample);
 }
 report('anm-checkpoint',{passed:true,captures,restores,checks,scope:'Original 489590/489600/489740/489d70 checkpoint pool and 489820/4898a0 restore using real front.anm trees. Snapshot handle generations and wrap, fractional timer normalization, recursive child order, four restored queues, live-world destruction and isolated retained snapshot ownership. Complete player/bullet/enemy world snapshots remain separate.'});
 }finally{c.anm_checkpoint_delete(checkpoint);c.anm_manager_delete(manager);c.release(p);m.close();}
});
