import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {resolve} from 'node:path';import {core,oracle,memory,string,root,report,enableNativeMath} from './helpers.mjs';import {resourceLoader,nativePool,prepareBank,compareAnm} from './anm-oracle.mjs';import {nativeGraphics} from './rendering-oracle.mjs';
test('TH15 screen overlay preserves original embedded ANM state, interrupts, draw ordering and lifetime',async()=>{
 const c=await core(),m=await oracle();enableNativeMath(m);const am=c.anm_manager_create(),nm=nativePool(m),gfx=nativeGraphics(m,nm),loader=resourceLoader(m),owner=m.allocate(0x1c),native=m.allocate(0x608),vm=c.anm_vm_create(),renderer=c.anm_renderer_create();let effects=0,bank=0,checks=0,frames=0,draws=0;try{
 for(const[name,id]of [['ascii.anm',2],['effect.anm',8]]){const bytes=readFileSync(resolve(root,'reference/assets',name)),p=c.allocate(bytes.length);memory(c,p,bytes.length).set(bytes);assert.equal(c.anm_manager_load(am,id,p,bytes.length),1,string(c,c.anm_manager_error(am)));c.release(p);const nb=prepareBank(m,loader,name,bytes,nm,id);if(id===2){c.anm_manager_fallback(am,id);const text=m.allocate(0x19270);m.u32(0x4e9a58,text);m.u32(text+0x19258,nb);}else{bank=nb;m.u32(owner+0xc,bank);}}
 m.u32(0x4e9a78,owner);m.u32(0x4ca620,0x4e73e8);effects=c.anm_scene_effects_create(am,8);const env=c.anm_manager_environment(am);const addresses=[];m.replace(0x4817d0,'capture overlay embedded draw order',()=>{addresses.push(m.u32(m.reg('ESP')+4));return 0;},1);
 for(let sample=0;sample<24;sample++){
  const rate=[1,.5,1.25,.25][sample%4];m.f32(0x4e73e8,1);assert.equal(c.anm_manager_update(am,0,1),1);m.view(native,0x608).fill(0);m.call(0x40b880,{ecx:bank,args:[native,0]});assert.equal(c.anm_manager_bind(am,vm,8,0),1);const seed=Buffer.alloc(8);seed.writeUInt16LE((sample*997+39)&65535);seed.writeUInt32LE(113,4);memory(c,c.anm_manager_random(am),8).set(seed);m.write(0x4e9a40,seed);assert.equal(c.anm_scene_effects_configure(effects,vm,0),1,string(c,c.anm_manager_error(am)));m.call(0x40aec0,{ecx:native});const np=m.u32(native+0x5c4);const label='sample '+sample;assert.equal(c.anm_vm_geometry_bytes(vm),m.u32(native+0x5c8));compareAnm(c,m,vm,native,label+' parent init');checks++;
  for(let i=0;i<5;i++){const cv=c.anm_vm_overlay_panel(vm,i);compareAnm(c,m,cv,np+i*0x608,label+' panel init '+i);assert.deepEqual(Buffer.from(memory(c,c.anm_vm_translation(cv),12)),Buffer.from(m.bytes(np+i*0x608+0x5ec,12)));checks++;}
  m.f32(0x4e73e8,rate);assert.equal(c.anm_manager_update(am,0,rate),1);for(let frame=0;frame<Math.ceil(160/rate);frame++){
   if(frame===8){const interrupt=[7,8,9,10,2,6][sample%6];assert.equal(c.anm_scene_effects_interrupt(effects,vm,interrupt,rate),1);m.call(0x40b620,{ecx:native,edx:interrupt});}
   if(frame===Math.ceil(50/rate)){assert.equal(c.anm_scene_effects_interrupt(effects,vm,1,rate),1);m.call(0x40b620,{ecx:native,edx:1});}
   const expected=m.call(0x40b040,{ecx:native}),actual=c.anm_scene_effects_update(effects,vm,rate);assert.equal(actual,expected,label+'/'+frame+' update');compareAnm(c,m,vm,native,label+'/'+frame+' parent');checks+=2;
   for(let i=0;i<5;i++){const cv=c.anm_vm_overlay_panel(vm,i);compareAnm(c,m,cv,np+i*0x608,label+'/'+frame+' panel '+i);assert.deepEqual(Buffer.from(memory(c,c.anm_vm_age(cv),20)),Buffer.from(m.bytes(np+i*0x608+0x560,20)));assert.deepEqual(Buffer.from(memory(c,c.anm_vm_translation(cv),12)),Buffer.from(m.bytes(np+i*0x608+0x5ec,12)));checks+=3;}
   for(let i=0;i<2;i++)assert.equal(new DataView(c.memory.buffer).getInt32(c.anm_vm_overlay_field(vm,i),true),m.i32(np+0x1e28+i*4),label+'/'+frame+' field '+i);assert.deepEqual(Buffer.from(memory(c,c.anm_manager_random(am),8)),Buffer.from(m.bytes(0x4e9a40,8)));checks+=3;frames++;if(expected)break;
   if(frame%17===0){const continuing=(sample&1)!==0;c.anm_environment_continue_prompt(env,continuing);m.i32(0x4e78cc,continuing?21:1);addresses.length=0;gfx.reset();m.call(0x40b0b0,{ecx:native});const mode=m.i32(np+0x1e28),masking=mode===2||mode===0&&continuing;assert.deepEqual(addresses,Array.from({length:masking?5:4},(_,i)=>np+i*0x608));c.anm_renderer_reset(renderer);assert.equal(c.anm_renderer_draw(renderer,vm,1),0,string(c,c.anm_renderer_error(renderer)));if(masking){const original=gfx.draws();assert.equal(original.length,1);assert.deepEqual(Buffer.from(memory(c,c.anm_renderer_history(renderer,0),c.anm_renderer_history_size(renderer,0))),original[0].bytes);assert.deepEqual(Array.from(new Uint32Array(c.memory.buffer,c.anm_renderer_submission_alpha(renderer,0),4)),[1,1,0,0]);checks+=3;}draws++;checks++;
   }
  }
 }
 report('anm-screen-overlay',{passed:true,cases:24,frames,checks,draws,originalFunctions:['0x40aec0','0x40b040','0x40b620','0x40b0b0','0x477e10'],scope:'Five actual effect ANM scripts: embedded VM state, full clock/translation/RNG and interrupts, replacement/rebinding, lifetime and frame counter. Original embedded draw order is captured at ANM submission boundary; transparent rectangle bytes and semantic independent-alpha state are checked. GPU pixels and full scene composition remain separate.'});
 }finally{if(effects)c.anm_scene_effects_delete(effects);c.anm_renderer_delete(renderer);c.anm_vm_delete(vm);c.anm_manager_delete(am);m.close();}
});
