import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {resolve} from 'node:path';import {core,oracle,memory,string,root,report,enableNativeMath} from './helpers.mjs';import {resourceLoader,nativePool,prepareBank,compareAnm} from './anm-oracle.mjs';
// Compare the bytes actually consumed by the native animation engine. Native
// self/list addresses and allocator bookkeeping are deliberately not pointers
// in the portable game, and are not compared as equal host addresses.
const ranges=[[0,0x28],[0x28,12],[0x34,0x44],[0x7c,0x318],[0x3dc,0xc4],[0x4a0,4],[0x4a8,0x9c],[0x54c,0x28],[0x5c0,4],[0x5ec,12]];
test('TH15 fixed checkpoint ANM records preserve native logical state and resume original script execution',async()=>{
 const c=await core(),m=await oracle(),manager=c.anm_manager_create(),codec=c.anm_file_create(),next=c.anm_vm_create(),rng=c.anm_manager_random(manager),pool=nativePool(m),loader=resourceLoader(m),out=m.allocate(4),length=m.allocate(4),record=m.allocate(1024*1024),input=c.allocate(16*1024*1024);let cases=0,checks=0,frames=0;enableNativeMath(m);m.u32(0x4ca620,0x4e73e8);m.f32(0x4e73e8,1);m.u32(0x4e9a94,0);
 const load=(name,id)=>{const bytes=readFileSync(resolve(root,'reference/assets',name));memory(c,input,bytes.length).set(bytes);assert.equal(c.anm_manager_load(manager,id,input,bytes.length),1,string(c,c.anm_manager_error(manager)));return prepareBank(m,loader,name,bytes,pool,id);};
 try{
  const ascii=load('ascii.anm',2),text=m.allocate(0x19270);m.u32(0x4e9a58,text);m.u32(text+0x19258,ascii);assert.equal(c.anm_manager_fallback(manager,2),1);const bank=load('front.anm',3);load('effect.anm',8);
  for(const script of [0,1,2,3,4,5,11,14,24,52,56,57,62,79,80,81,82,86,120,137,158,171,221,241,243])for(const rate of [1,.5,1.25]){
   m.f32(0x4e73e8,1);const h=c.anm_manager_spawn(manager,3,script,24,2);m.call(0x433020,{ecx:bank,args:[out,script,24,0],limit:10000000});assert.equal(h>>>0,m.u32(out));const vm=c.anm_manager_find(manager,h),native=m.call(0x488510,{ecx:pool,args:[h]})>>>0;m.f32(0x4e73e8,rate);m.u32(native+0x534,2);
   for(let frame=0;frame<8;frame++){assert.ok(c.anm_vm_tick(vm,rng,rate)>=0,string(c,c.anm_vm_error(vm)));m.call(0x477e10,{ecx:native});}compareAnm(c,m,vm,native,'source '+script+'/'+rate);
   assert.equal(c.anm_file_write(codec,vm,manager),1,string(c,c.anm_file_error(codec)));const block=Buffer.from(memory(c,c.anm_file_block(codec),0x608));m.u32(length,0);m.call(0x4899f0,{ecx:pool,args:[record,native,length],limit:10000000});assert.ok(m.u32(length)>=0x608);const original=Buffer.from(m.bytes(record,0x608));
   for(const [at,n]of ranges){assert.deepEqual(block.subarray(at,at+n),original.subarray(at,at+n),'file '+script+'/'+rate+' region '+at.toString(16));checks++;}
   memory(c,input,0x608).set(original);assert.equal(c.anm_file_read(codec,input,0x608,next,manager),1,string(c,c.anm_file_error(codec)));compareAnm(c,m,next,native,'import '+script+'/'+rate);checks++;
   for(let frame=0;frame<20;frame++){if(frame===3||frame===9){c.anm_vm_interrupt(next,frame===3?1:3);m.u32(native+0x49c,frame===3?1:3);}assert.ok(c.anm_vm_tick(next,rng,rate)>=0,string(c,c.anm_vm_error(next)));m.call(0x477e10,{ecx:native});compareAnm(c,m,next,native,'resume '+script+'/'+rate+'/'+frame);frames++;checks++;}
   // Native resource addresses are irrelevant; bank/script/offset are checked.
   for(const [at,value]of [[0x28,255],[0x30,0x7fffffff],[0x34,0x7fffffff]]){const bad=Buffer.from(original);bad.writeInt32LE(value,at);memory(c,input,bad.length).set(bad);assert.equal(c.anm_file_read(codec,input,bad.length,next,manager),0);checks++;}
   assert.equal(c.anm_manager_destroy_tree(manager,vm),1);m.call(0x488820,{ecx:pool,args:[native]});cases++;
  }
  load('front.anm',9);const relocatedHandle=c.anm_manager_spawn(manager,9,0,24,2),relocatedVm=c.anm_manager_find(manager,relocatedHandle);assert.equal(c.anm_file_write(codec,relocatedVm,manager),1);const relocated=Buffer.from(memory(c,c.anm_file_block(codec),0x608));relocated.writeInt32LE(55,0x28);memory(c,input,relocated.length).set(relocated);assert.equal(c.anm_file_read(codec,input,relocated.length,next,manager),0);assert.equal(c.anm_file_read_mapped(codec,input,relocated.length,next,manager,55,9),1,string(c,c.anm_file_error(codec)));assert.equal(c.anm_file_write(codec,next,manager),1);assert.equal(new DataView(c.memory.buffer).getInt32(c.anm_file_block(codec)+0x28,true),9,'bank rebind resolves actual resource');assert.equal(c.anm_file_read(codec,input,relocated.length,next,manager),0,'mapping scope does not leak into later imports');checks+=5;
  report('anm-file',{passed:true,cases,checks,frames,scope:'Scoped portable saved-bank to current-bank rebinding and cleanup; native 4899f0 fixed 0x608 records: all logical visual/variable/interpolation/script/interrupt/private timer fields, real front.anm assets, import of original records and continued native script comparison. Host addresses and registry bookkeeping are excluded. Recursive children and variable geometry tails require separate checkpoint integration.'});
 }finally{c.anm_file_delete(codec);c.anm_vm_delete(next);c.release(input);c.anm_manager_delete(manager);m.close();}
});
