import test from 'node:test';import assert from 'node:assert/strict';
import {core,oracle,memory,string,report} from './helpers.mjs';
function ins(op,args=[],mask=0,time=0){const b=Buffer.alloc(8+args.length*4);b.writeInt16LE(op);b.writeUInt16LE(b.length,2);b.writeInt16LE(time,4);b.writeUInt16LE(mask,6);args.forEach((a,i)=>typeof a==='object'?b.writeFloatLE(a.f,8+i*4):b.writeInt32LE(a|0,8+i*4));return b;}
test('TH15 animation object commands preserve original creation order, arguments and parent variable copying',async()=>{
 const c=await core(),m=await oracle(),vm=c.anm_vm_create(),parent=c.anm_vm_create(),rng=c.rng_create(),host=c.anm_object_fixture_create(),native=m.allocate(0x608),originalParent=m.allocate(0x608),child=m.allocate(0x608),bank=m.allocate(0x13c),table=m.allocate(4),manager=m.allocate(0x187f600),source=m.allocate(1024),p=c.allocate(1024);let checks=0,cases=0,events=[];
 m.u32(0x503c18,manager);m.u32(manager+0x187f4d8,bank);m.u32(bank+0x120,table);m.u32(table,source);m.u32(0x4ca620,0x4e73e8);m.f32(0x4e73e8,1);c.anm_vm_object_host(vm,host);
 m.replace(0x4882e0,'capture original child allocation boundary',()=>{const sp=m.reg('ESP'),out=m.u32(sp+4);assert.equal(m.u32(sp+12),native);events.push(0,m.i32(sp+8),m.i32(sp+16),0);m.u32(out,1);return out;},4);
 m.replace(0x488420,'capture original detached allocation boundary',()=>{const sp=m.reg('ESP'),out=m.u32(sp+4);assert.equal(m.u32(sp+12),native);events.push(1,m.i32(sp+8),0,0);m.u32(out,1);return out;},4);
 m.replace(0x488a20,'resolve captured animation handle',()=>child);
 m.replace(0x422900,'capture original effect allocation boundary',()=>{const sp=m.reg('ESP'),out=m.u32(sp+4);assert.equal(m.u32(sp+12),native);assert.equal(m.u32(sp+16),native);events.push(2,m.i32(sp+8),0,0);m.u32(out,1);return out;},4);
 try{for(let op=500;op<=509;op++)for(let sample=0;sample<256;sample++){
  const x=(sample-135)*.125,y=(sample-77)*.375,script=sample*13-37,reference=sample&1,args=op===509?[]:op===505||op===506?[reference?10000:script,reference?{f:10004}:{f:x},reference?{f:10005}:{f:y}]:[reference?10000:script],mask=reference?(op===509?0:op===505||op===506?7:1):0;
  const bytes=Buffer.concat([ins(100,[10000,script],1),ins(101,[{f:10004},{f:x}],1),ins(101,[{f:10005},{f:y}],1),ins(op,args,mask),ins(3,[],0,1),ins(-1)]);memory(c,p,bytes.length).set(bytes);const resource=c.anm_fixture_create(p,bytes.length);assert.equal(c.anm_vm_bind(vm,resource,0),1);c.anm_object_fixture_reset(host);events=[];m.view(native,0x608).fill(0);m.view(child,0x608).fill(0);m.write(source,bytes);m.call(0x4773e0,{ecx:bank,args:[native,0]});
  const parentVars=Buffer.alloc(64);for(let i=0;i<16;i++)parentVars.writeInt32LE((sample+17)*571+i*197,i*4);memory(c,c.anm_vm_variables(parent),64).set(parentVars);m.write(originalParent+0x4ac,parentVars);if(sample&2){c.anm_vm_creation_parent(vm,parent);m.u32(native+0x5bc,originalParent);}
  assert.equal(c.anm_vm_tick(vm,rng,1),0,string(c,c.anm_vm_error(vm)));assert.equal(m.call(0x477e10,{ecx:native,limit:10000000})|0,0);const count=c.anm_object_fixture_count(host);assert.equal(count,events.length/4);assert.deepEqual(Buffer.from(memory(c,c.anm_object_fixture_events(host),count*16)),Buffer.from(new Int32Array(events).buffer),JSON.stringify({op,sample,events:true}));assert.deepEqual(Buffer.from(memory(c,c.anm_vm_visual(c.anm_object_fixture_child(host))+16,12)),Buffer.from(m.bytes(child+0x4ec,12)),JSON.stringify({op,sample,child:true}));assert.deepEqual(Buffer.from(memory(c,c.anm_vm_variables(vm),64)),Buffer.from(m.bytes(native+0x4ac,64)),JSON.stringify({op,sample,variables:true}));assert.deepEqual(Buffer.from(memory(c,c.anm_vm_visual(vm),8)),Buffer.from(m.bytes(native+0x18,8)),JSON.stringify({op,sample,flags:true}));assert.equal(c.anm_vm_offset(vm),m.i32(native+0x34));assert.deepEqual(Buffer.from(memory(c,c.anm_vm_timer(vm),20)),Buffer.from(m.bytes(native+0x54c,20)));checks+=7;cases++;c.anm_delete(resource);
 }report('anm-objects',{passed:true,checks,cases,coveredOpcodes:Array.from({length:10},(_,i)=>500+i),originalFunction:'0x477e10',scope:'Original script dispatch and arguments with allocation boundaries captured independently; allocator lifecycle, child ordering and drawing require separate integration tests.'});}
 finally{c.anm_vm_delete(vm);c.anm_vm_delete(parent);c.anm_object_fixture_delete(host);c.rng_delete(rng);c.release(p);m.close();}
});

