import test from 'node:test';import assert from 'node:assert/strict';
import {core,oracle,memory,string,report} from './helpers.mjs';
function instruction(op,args=[],mask=0,time=0){const b=Buffer.alloc(8+args.length*4);b.writeInt16LE(op,0);b.writeUInt16LE(b.length,2);b.writeInt16LE(time,4);b.writeUInt16LE(mask,6);for(let i=0;i<args.length;i++){if(typeof args[i]==='object')b.writeFloatLE(args[i].f,8+i*4);else b.writeInt32LE(args[i]|0,8+i*4);}return b;}
test('TH15 ANM arithmetic and random instructions execute identically to original',async()=>{
 const c=await core(),m=await oracle(),vm=c.anm_vm_create(),rng=c.rng_create(),native=m.allocate(0x608),bank=m.allocate(0x13c),table=m.allocate(4),manager=m.allocate(0x187f600),source=m.allocate(4096),cp=c.allocate(4096);let checks=0;
 m.u32(0x503c18,manager);m.u32(manager+0x187f4d8,bank);m.u32(bank+0x120,table);m.u32(table,source);m.u32(0x4ca620,0x4e73e8);m.f32(0x4e73e8,1);
 try{for(let sample=0;sample<256;sample++){
 const commands=[];for(const op of Array.from({length:24},(_,i)=>100+i)){const floating=op&1,three=op>=112,a=(sample-139)*37.125,b=(sample%17+1)*.125,args=floating?[{f:10004},{f:a}]:[10000,(sample-97)*577];if(three)args.push(floating?{f:b}:sample%23+1);else if(op>=108&&op<=111)args[1]=floating?{f:b}:sample%23+1;commands.push(instruction(op,args,1));}
 const bytes=Buffer.concat([...commands,instruction(1,[],0,3)]);memory(c,cp,bytes.length).set(bytes);const resource=c.anm_fixture_create(cp,bytes.length);assert.equal(c.anm_vm_bind(vm,resource,0),1);m.view(native,0x608).fill(0);m.write(source,bytes);m.call(0x4773e0,{ecx:bank,args:[native,0]});const seed=(sample*293+3)&65535;m.u32(0x4e9a40,seed);m.u32(0x4e9a44,0);new DataView(c.memory.buffer,rng,8).setUint32(0,seed,true);new DataView(c.memory.buffer,rng,8).setUint32(4,0,true);
 for(let frame=0;frame<5;frame++){const status=c.anm_vm_tick(vm,rng,1);assert.ok(status>=0,string(c,c.anm_vm_error(vm)));m.call(0x477e10,{ecx:native,limit:10000000});const vars=c.anm_vm_variables(vm);assert.deepEqual(Buffer.from(memory(c,vars,32)),Buffer.from(m.bytes(native+0x4ac,32)),'variables sample '+sample+' frame '+frame);assert.deepEqual(Buffer.from(memory(c,rng,8)),Buffer.from(m.bytes(0x4e9a40,8)));assert.equal(c.anm_vm_offset(vm),m.i32(native+0x34));assert.deepEqual(Buffer.from(memory(c,c.anm_vm_timer(vm),20)),Buffer.from(m.bytes(native+0x54c,20)),'timer sample '+sample+' frame '+frame);checks+=4;}c.anm_delete(resource);
 }report('anm-interpreter',{passed:true,checks,samples:256,frames:1280,coveredOpcodes:Array.from({length:24},(_,i)=>100+i),originalFunction:'0x477e10',scope:'Arithmetic/RNG execution and frame timing; graphics, interpolation and child commands remain integration work.'});
 }finally{c.anm_vm_delete(vm);c.rng_delete(rng);c.release(cp);m.close();}
});
test('Unknown animation instructions stop explicitly',async()=>{const c=await core(),vm=c.anm_vm_create(),rng=c.rng_create(),bytes=Buffer.concat([instruction(999),instruction(1)]),p=c.allocate(bytes.length);memory(c,p,bytes.length).set(bytes);const resource=c.anm_fixture_create(p,bytes.length);assert.equal(c.anm_vm_bind(vm,resource,0),1);assert.equal(c.anm_vm_tick(vm,rng,1),-1);assert.equal(string(c,c.anm_vm_error(vm)),'Unimplemented ANM opcode 999');c.anm_delete(resource);c.anm_vm_delete(vm);c.rng_delete(rng);c.release(p);});
