import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync}from'node:fs';import{resolve}from'node:path';import{core,oracle,memory,string,root,report,enableNativeMath}from'./helpers.mjs';import{nativePool}from'./anm-oracle.mjs';import{nativeGraphics}from'./rendering-oracle.mjs';
test('TH15 registered animation drawing preserves native layer order and camera switches',async()=>{
 const c=await core(),m=await oracle();enableNativeMath(m);const a=c.anm_manager_create(),r=c.anm_renderer_create(),f=c.anm_draw_schedule_create(a,r),nm=nativePool(m),gfx=nativeGraphics(m,nm),register=JSON.parse(readFileSync(resolve(root,'reference/native/animation-draw-registration.json'))),layers=[],events=[];let camera=2,checks=0;
 const observedRegistration=[];m.replace(0x490d92,'unused constructor array ownership',()=>0,5);m.replace(0x401390,'update callback registration',()=>0,2);m.replace(0x401440,'draw callback registration',()=>{const sp=m.reg('ESP'),node=m.u32(sp+4);observedRegistration.push({callback:'0x'+m.u32(node+8).toString(16),priority:m.i32(sp+8)});return 0;},2);const vt=m.u32(m.u32(0x4e77d8));m.u32(vt+0x170,m.registerImport({dll:'fixture',name:'constructor vertex binding',argc:2,handler:()=>0}));m.call(0x483100,{ecx:nm});assert.deepEqual(observedRegistration,register);
 const addressToCamera=new Map([[0x4e7a10,0],[0x4e7b3c,1],[0x4e7c68,2],[0x4e7d94,3]]);for(const [address,id]of addressToCamera){m.view(address,0x12c).fill(0);for(let i=0;i<4;i++){m.f32(address+0x60+i*20,1);m.f32(address+0xa0+i*20,1);}m.u32(address+0xe8,640);m.u32(address+0xec,480);m.f32(address+0xf4,1);m.f32(address+0xfc,id*7+3);m.f32(address+0x100,id*11+5);}
 m.replace(0x44df60,'camera recomputation (separately proven)',()=>{events.push(3,1);return 0;},1);
 m.replace(0x44def0,'semantic camera activation',()=>{const p=m.u32(m.reg('ESP')+4);camera=addressToCamera.get(p);if(camera!==3)events.push(camera,0);m.f32(nm+0xd0,m.f32(p+0xfc));m.f32(nm+0xd4,m.f32(p+0x100));return 0;},1);
 m.replace(0x487b60,'animation layer draw boundary',()=>{const layer=m.i32(m.reg('ESP')+4);layers.push({layer,camera,offset:[m.f32(nm+0xd0),m.f32(nm+0xd4)]});return 1;},1);
 try{for(let sample=0;sample<8;sample++){layers.length=events.length=0;camera=2;m.u32(0x4e81e4,sample&1);m.u32(0x4e81e8,sample&2);m.f32(nm+0xd0,sample+13);m.f32(nm+0xd4,sample+19);memory(c,c.anm_renderer_offset(r),8).set(new Uint8Array(new Float32Array([sample+13,sample+19]).buffer));c.anm_renderer_reset(r);assert.equal(c.anm_manager_update(a,0,1),1);assert.equal(c.anm_manager_update(a,1,1),1);for(const item of register.toSorted((a,b)=>a.priority-b.priority))assert.equal(m.call(parseInt(item.callback),{ecx:nm}),1);assert.equal(c.anm_draw_schedule_draw(f),1,string(c,c.anm_draw_schedule_error(f)));assert.deepEqual(Array.from(new Int32Array(c.memory.buffer,c.anm_draw_schedule_events(f),c.anm_draw_schedule_count(f))),events);assert.equal(c.anm_renderer_calls(r),layers.length);for(let i=0;i<layers.length;i++){const b=memory(c,c.anm_renderer_history(r,i),80),dv=new DataView(b.buffer,b.byteOffset,80);assert.equal(dv.getFloat32(0,true),layers[i].layer+9);assert.equal(dv.getFloat32(4,true),9);checks+=2;}
 assert.deepEqual(Array.from(new Float32Array(c.memory.buffer,c.anm_renderer_offset(r),2)),[17,27]);checks+=3;}
 report('anm-draw-schedule',{passed:true,samples:8,checks,layers:layers.map(v=>v.layer),registration:register,scope:'38 native animation draw callbacks execute in the original constructor priorities; camera selection/recomputation/restore and inherited/zeroed offsets match native wrappers. C++ shape draws prove actual layer order. Camera math and individual raster vertex/state submission have separate native tests; this is not whole-game rendering proof.'});
 }finally{c.anm_draw_schedule_delete(f);c.anm_renderer_delete(r);c.anm_manager_delete(a);m.close();}
});
