import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync,readdirSync} from 'node:fs';import {resolve} from 'node:path';import {core,memory,string,root,report} from './helpers.mjs';
test('TH15 application text and ASCII banks survive actual run destruction and repeated character/stage factories',async()=>{
 const c=await core(),a=c.stage_assets_create(),f=c.application_assets_create(a),name=c.allocate(256),owned=[];let scenes=0,frames=0;
 try{for(const file of readdirSync(resolve(root,'reference/assets')).filter(n=>/\.(anm|ecl|sht|std|msg)$/.test(n))){const b=readFileSync(resolve(root,'reference/assets',file)),p=c.allocate(b.length);owned.push(p);memory(c,p,b.length).set(b);memory(c,name,file.length+1).set(Buffer.from(file+'\0'));c.stage_assets_file(a,name,p,b.length);}
 assert.equal(c.application_assets_initialize(f),1,string(c,c.application_assets_error(f)));const identities=[0,2].map(n=>c.application_assets_common(f,n));assert.ok(identities.every(Boolean));
 for(let character=0;character<4;character++)for(const first of [1,7]){assert.equal(c.application_assets_begin(f,first,character),1,string(c,c.application_assets_error(f)));const r=c.application_assets_run(f);
 for(const stage of first===7?[7]:[1,2,3,4,5,6]){if(stage!==first){assert.equal(c.run_gameplay_close_spell(r),1);assert.equal(c.run_gameplay_next(r,stage),1,string(c,c.run_gameplay_error(r)));c.run_gameplay_release_previous(r);}assert.equal(c.application_assets_bank(f,0),0);assert.equal(c.application_assets_bank(f,1),2);assert.deepEqual([0,2].map(n=>c.application_assets_common(f,n)),identities);assert.equal(c.run_gameplay_begin(r),1,string(c,c.run_gameplay_error(r)));for(let t=0;t<120;t++){assert.equal(c.run_gameplay_step(r,1,0,t+1,t+1),1,string(c,c.run_gameplay_error(r)));frames++;}scenes++;}
 c.application_assets_clear(f);assert.deepEqual([0,2].map(n=>c.application_assets_common(f,n)),identities,'return to title preserves global GPU resource identity');}
 report('application-assets',{passed:true,scenes,frames,scope:'Actual scene factories, original ANM/ECL/STD/SHT/MSG and all four characters; global text/ASCII resource identity is retained across six-stage runs, Extra and complete run destruction/recreation. Controlled short gameplay verifies template fallback and callbacks; this is resource ownership integration, not whole-game or native replay parity.'});
 }finally{c.application_assets_delete(f);c.stage_assets_delete(a);for(const p of owned)c.release(p);c.release(name);}
});
