import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {resolve} from 'node:path';import {core,oracle,memory,string,root,report,enableNativeMath} from './helpers.mjs';import {resourceLoader,nativePool,prepareBank} from './anm-oracle.mjs';
test('TH15 ASCII text queue, six glyph families, punctuation spacing, alignment, scaling and shadows preserve original sprite vertices',async()=>{
 const c=await core(),m=await oracle();enableNativeMath(m);const loader=resourceLoader(m),nm=nativePool(m),owner=m.allocate(0x19270),nativeInput=m.allocate(12),nativeString=m.allocate(256),quad=c.allocate(48),banks=[];let expected=[],cases=0,glyphs=0,checks=0;
 try{m.f32(0x4e73e8,1);m.u32(0x4ca620,0x4e73e8);for(let i=0;i<3;i++){const name=['ascii.anm','ascii_960.anm','ascii_1280.anm'][i],b=readFileSync(resolve(root,'reference/assets',name));banks.push({name,bytes:b,bank:prepareBank(m,loader,name,b,nm,i+2)});}
 m.replace(0x47dba0,'observe original ASCII glyph submission boundary',()=>{const np=m.u32(m.reg('ESP')+4);expected.push({flags:Buffer.from(m.bytes(np+0x18,8)),sprite:m.i32(np+0x2c),position:Buffer.from(m.bytes(np+0x38,12)),scale:Buffer.from(m.bytes(np+0x5c,16)),size:Buffer.from(m.bytes(np+0x8c,8)),color:m.u32(np+0x538),uv:Buffer.from(m.bytes(np+0x3b4,32)),spriteSize:Buffer.from(m.bytes(np+0x7c,8)),quad:Buffer.concat(Array.from({length:4},(_,i)=>Buffer.from(m.bytes(0x5213c0+i*28,12))))});return 0;},2);
 for(let sample=0;sample<1296;sample++){
 const bankIndex=Math.floor(sample/432),source=banks[bankIndex],am=c.anm_manager_create(),f=c.ascii_text_create(am),bytes=source.bytes,p=c.allocate(bytes.length);try{memory(c,p,bytes.length).set(bytes);assert.equal(c.anm_manager_load(am,bankIndex+2,p,bytes.length),1,string(c,c.anm_manager_error(am)));c.release(p);assert.equal(c.ascii_text_initialize(f,bankIndex+2),1,string(c,c.ascii_text_error(f)));const environment=c.anm_manager_environment(am),dv=()=>new DataView(c.memory.buffer),resolution=[1,1.5,2][sample%3],sx=[1,.6,1.25,.875][Math.floor(sample/6)%4],sy=[1,.625,1.125][Math.floor(sample/24)%3],font=sample%6,alignment=Math.floor(sample/72)%3,vertical=Math.floor(sample/216)%3,shadow=Math.floor(sample/3)%2,space=sample%3,color=(0xbdabcdef^Math.imul(sample,19737))>>>0;
 dv().setFloat32(c.anm_environment_scale(environment),resolution,true);m.f32(0x51bc04,resolution);for(const[i,v]of[48,16,91,37].entries()){dv().setInt32(c.anm_environment_offsets(environment)+i*4,v,true);m.i32(0x51bc18+i*4,v);}const position=[Math.fround(303.25-sample%31*.125),Math.fround(128.5+sample%17*.375),Math.fround(sample%13*.0625)];for(let i=0;i<3;i++){dv().setFloat32(c.ascii_text_position(f)+i*4,position[i],true);m.f32(nativeInput+i*4,position[i]);}
 const s=c.ascii_text_style(f);dv().setUint32(s,color,true);dv().setFloat32(s+4,sx,true);dv().setFloat32(s+8,sy,true);for(const[off,v]of[[12,font],[16,space],[20,alignment],[24,vertical]])dv().setInt32(s+off,v,true);
 m.view(owner,0x19270).fill(0);m.u32(owner+0x19250,9);m.u32(owner+0x19224,color);m.f32(owner+0x19228,sx);m.f32(owner+0x1922c,sy);for(const[off,v]of[[0x1923c,font],[0x19240,space],[0x19248,alignment],[0x1924c,vertical],[0x19238,shadow],[0x19244,2]])m.i32(owner+off,v);m.call(0x40d680,{ecx:owner+0x10});m.u32(owner+0x38,bankIndex+2);m.call(0x477160,{ecx:source.bank,args:[owner+0x10,0]});
 const text=font>=4?`123,456.78/90s* 
 1,23`:`AbcXYZ 12.34/+:-*%$ 
 90`;m.write(nativeString,Buffer.from(text+String.fromCharCode(0)));const cp=c.allocate(256);memory(c,cp,256).fill(0);memory(c,cp,text.length).set(Buffer.from(text));assert.equal(c.ascii_text_enqueue(f,cp,2,shadow),1,string(c,c.ascii_text_error(f)));c.release(cp);m.call(0x40c410,{ecx:owner,args:[nativeInput,nativeString]});assert.deepEqual(Buffer.from(memory(c,c.ascii_text_entry_position(f,0),12)),Buffer.from(m.bytes(owner+0xd20,12)),sample+' enqueue scaled coordinates');assert.equal(string(c,c.ascii_text_entry_value(f,0)),m.string(owner+0xc20));assert.equal(c.ascii_text_count(f),m.u32(owner+0x19220));checks+=3;
 expected=[];assert.equal(c.ascii_text_draw(f,space),1,string(c,c.ascii_text_error(f)));m.view(0x5213c0,112).fill(0);m.call(0x40c960,{ecx:owner,args:[owner+0xc20]});assert.equal(c.ascii_text_glyph_count(f),expected.length,sample+' glyph count');for(let i=0;i<expected.length;i++){const np=expected[i],vm=c.ascii_text_glyph(f,i),v=c.anm_vm_visual(vm),vars=c.anm_vm_variables(vm);for(const[cp,n,data,label]of[[v,8,np.flags,'flags'],[vars+64,12,np.position,'position'],[v+40,16,np.scale,'scale'],[v+88,8,np.size,'size'],[v+104,32,np.uv,'UV'],[v+136,8,np.spriteSize,'dimensions']]){assert.deepEqual(Buffer.from(memory(c,cp,n)),data,sample+'/'+i+' '+label);checks++;}assert.equal(dv().getInt32(v+12,true),np.sprite,sample+'/'+i+' sprite');assert.equal(dv().getUint32(v+96,true),np.color,sample+'/'+i+' color');assert.equal(c.anm_quad_positions(vm,quad),1);assert.deepEqual(Buffer.from(memory(c,quad,48)),np.quad,sample+'/'+i+' original CPU corners');glyphs++;checks+=3;}
 for(let frame=0;frame<3;frame++){c.ascii_text_update(f);m.call(0x40d400,{ecx:owner});assert.equal(c.ascii_text_count(f),m.u32(owner+0x19220),sample+'/'+frame+' queue lifetime');if(c.ascii_text_count(f))assert.equal(c.ascii_text_entry_lifetime(f,0),m.i32(owner+0xd4c));checks++;}cases++;
 }finally{c.ascii_text_delete(f);c.anm_manager_delete(am);}}
 report('ascii-text-glyphs',{passed:true,cases,glyphs,checks,originalFunctions:['0x40c410','0x40c960','0x40d400','0x47e610'],scope:'All three original ASCII resolution resources; queue scaling/offset/lifetime and six glyph families with punctuation, newlines, horizontal/vertical alignment, noninteger scales and shadow glyphs. Original glyph properties and all four CPU corners compared at GPU submission boundary. Shared sprite backend rendering is separately verified.'});
 }finally{c.release(quad);m.close();}
});
