import test from 'node:test';import assert from 'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{resolve}from'node:path';import{core,oracle,memory,string,root,report,enableNativeMath}from'./helpers.mjs';import{resourceLoader,nativePool,prepareBank}from'./anm-oracle.mjs';import{nativeGraphics}from'./rendering-oracle.mjs';
test('TH15 caption frame callbacks preserve original three spaces, cameras and actual sprite submissions',async()=>{
 const c=await core(),m=await oracle();enableNativeMath(m);const loader=resourceLoader(m),nm=nativePool(m),gfx=nativeGraphics(m,nm),owner=m.allocate(0x19270),input=m.allocate(12),text=m.allocate(256),bytes=readFileSync(resolve(root,'reference/assets/ascii.anm')),bank=prepareBank(m,loader,'ascii.anm',bytes,nm,5),cameras=[];let cases=0,checks=0,vertices=0;
 const addresses=[0x4e7a10,0x4e7b3c,0x4e7c68,0x4e7d94],vt=m.u32(m.u32(0x4e77d8));m.u32(vt+0xbc,m.registerImport({dll:'fixture',name:'caption camera viewport',argc:2,handler:()=>{cameras.push(addresses.indexOf(m.u32(0x4e7ec0)));return 0;}}));
 try{for(let sample=0;sample<72;sample++){const a=c.anm_manager_create(),r=c.anm_renderer_create(),t=c.ascii_text_create(a),p=c.allocate(bytes.length);memory(c,p,bytes.length).set(bytes);assert.equal(c.anm_manager_load(a,5,p,bytes.length),1);c.release(p);assert.equal(c.ascii_text_initialize(t,5),1);const env=c.anm_manager_environment(a),dv=()=>new DataView(c.memory.buffer),scale=[1,1.5,2][sample%3],width=640*scale,height=480*scale;dv().setFloat32(c.anm_environment_scale(env),scale,true);dv().setUint32(c.anm_environment_dimensions(env),width,true);dv().setUint32(c.anm_environment_dimensions(env)+4,height,true);m.f32(0x51bc04,scale);m.u32(0x51bbfc,width);m.u32(0x51bc00,height);m.call(0x44e2f0,{ecx:0x4e77d0});for(let i=0;i<4;i++){const v=[width/2,16*scale,width/2,16*scale][i];dv().setInt32(c.anm_environment_offsets(env)+i*4,v,true);m.i32(0x51bc18+i*4,v);}const f=c.ascii_frame_create(t,r,a);
 try{m.view(owner,0x19270).fill(0);m.u32(owner+0x19250,9);m.call(0x40d680,{ecx:owner+0x10});m.u32(owner+0x38,5);m.call(0x477160,{ecx:bank,args:[owner+0x10,0]});for(let space=0;space<3;space++){const position=space===1?[-width/scale+sample,40+sample,0]:[space===2?32:210,35+space*80+sample,0],value=space===1?'12.5/:-':'Ab 90*';for(let i=0;i<3;i++){dv().setFloat32(c.ascii_text_position(t)+i*4,position[i],true);m.f32(input+i*4,position[i]);}const style=c.ascii_text_style(t),color=((0xef123456^sample*177)&(sample%9===0?0xffffff:0xffffffff))>>>0;dv().setUint32(style,color,true);for(const[off,v]of[[4,1],[8,1]])dv().setFloat32(style+off,v,true);for(const[off,v]of[[12,sample%6],[16,space],[20,1],[24,1]])dv().setInt32(style+off,v,true);m.u32(owner+0x19224,color);m.f32(owner+0x19228,1);m.f32(owner+0x1922c,1);for(const[off,v]of[[0x1923c,sample%6],[0x19240,space],[0x19248,1],[0x1924c,1],[0x19238,sample&1],[0x19244,2]])m.i32(owner+off,v);m.write(text,Buffer.from(value+'\0'));const s=c.allocate(256);memory(c,s,256).fill(0);memory(c,s,value.length).set(Buffer.from(value));assert.equal(c.ascii_text_enqueue(t,s,2,sample&1),1);c.release(s);m.call(0x40c410,{ecx:owner,args:[input,text]});assert.deepEqual(Buffer.from(memory(c,c.ascii_text_entry_position(t,space),12)),Buffer.from(m.bytes(owner+0xc20+space*0x138+0x100,12)));checks++;}
 for(let frame=0;frame<4;frame++){assert.equal(c.ascii_frame_update(f),1);assert.equal(m.call(0x40c340,{ecx:owner}),1);assert.equal(c.ascii_frame_frames(f),m.i32(owner+0x19254));assert.equal(c.ascii_text_count(t),m.u32(owner+0x19220));gfx.reset();c.anm_renderer_reset(r);cameras.length=0;const initial=sample%4;m.u32(0x4e7ec0,addresses[initial]);m.call(0x44def0,{args:[addresses[initial]]});c.ascii_frame_camera(f,initial);cameras.length=0;for(const address of[0x40c370,0x40c380,0x40c360])assert.equal(m.call(address,{ecx:owner}),1,address.toString(16));assert.equal(c.ascii_frame_draw(f),3,string(c,c.ascii_frame_error(f)));assert.deepEqual(Array.from(new Int32Array(c.memory.buffer,c.ascii_frame_cameras(f),c.ascii_frame_camera_count(f))),cameras,sample+'/'+frame+' camera order');const expected=Buffer.concat(gfx.draws().map(d=>{assert.equal(d.stride,28);return d.bytes;})),actual=Buffer.concat(Array.from({length:c.anm_renderer_calls(r)},(_,i)=>Buffer.from(memory(c,c.anm_renderer_history(r,i),c.anm_renderer_history_size(r,i)))));if(!actual.equals(expected))writeFileSync(resolve(root,'artifacts/cpp/verification/ascii-frame-observed.json'),JSON.stringify({sample,frame,cameras,cppCameras:Array.from(new Int32Array(c.memory.buffer,c.ascii_frame_cameras(f),c.ascii_frame_camera_count(f))),actual:Array.from({length:actual.length/168},(_,i)=>[actual.readFloatLE(i*168),actual.readFloatLE(i*168+4),actual.readUInt32LE(i*168+16)]),expected:Array.from({length:expected.length/168},(_,i)=>[expected.readFloatLE(i*168),expected.readFloatLE(i*168+4),expected.readUInt32LE(i*168+16)]),nativeFlags:m.u32(owner+0x2c),nativeCamera:m.u32(0x4e7ec0)},null,2));assert.deepEqual(actual,expected,sample+'/'+frame+' full glyph vertex stream');vertices+=expected.length/28;assert.equal(m.u32(owner+0x2c)&0xc0000,0);checks+=5;}cases++;
 }finally{c.ascii_frame_delete(f);c.ascii_text_delete(t);c.anm_renderer_delete(r);c.anm_manager_delete(a);}}
 report('ascii-frame',{passed:true,cases,checks,vertices,originalFunctions:['0x40c340','0x40c370','0x40c380','0x40c360','0x40d130','0x40c870','0x40c410'],scope:'Actual caption callback drawing with all three spaces, distinct origin offsets, six fonts, transparent glyphs, shadows, three resolutions, four inherited cameras and queue expiration; original GPU submissions compared byte-for-byte to the production CPU renderer. Hardware rasterization is a separate browser check.'});
 }finally{m.close();}
});
