import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {resolve} from 'node:path';import {core,memory,string,report,root} from './helpers.mjs';import {bits,ins,resource} from './ecl-fixtures.mjs';
test('TH15 integrated chapter checkpoints restore real battle, background, effects and four active bombs across repeated retries',async()=>{
 const c=await core();let frames=0,retries=0,checks=0;
 const {bytes}=resource({main:Buffer.concat([ins(40,[0]),ins(302,[2]),ins(303,[0,0]),ins(500,[bits(32),bits(32)]),ins(507,[0,2]),ins(600,[0]),ins(602,[0,5,3]),ins(604,[0,bits(0),bits(.0625)]),ins(605,[0,bits(1.25),bits(.25)]),ins(606,[0,3,2]),ins(608,[0,-1,-1]),...[0,15,30,45,60,75,90].map(t=>ins(601,[0],0,t)),ins(700,[0,bits(0),bits(160),bits(560),bits(12)]),ins(701,[0,12,16,180,16,0]),ins(703,[0,1234],0,24),ins(10,[],0,100000)])});
 for(let character=0;character<4;character++){
 const anm=c.anm_manager_create(),program=c.program_create(),pp=c.allocate(bytes.length),sht=c.sht_create(),name=c.allocate(5),request=c.allocate(84),backgroundResource=c.stage_resource_create();let battle=0,background=0,checkpoint=0;const file=c.player_checkpoint_file_create(),fileBuffer=c.allocate(16*1024*1024);const dv=()=>new DataView(c.memory.buffer);
 const load=(name,id)=>{const b=readFileSync(resolve(root,'reference/assets',name)),p=c.allocate(Math.max(b.length,name.length+1));memory(c,p,b.length).set(b);assert.equal(c.anm_manager_load(anm,id,p,b.length),1,name+' '+string(c,c.anm_manager_error(anm)));memory(c,p,name.length+1).set(Buffer.from(name+'\0'));assert.equal(c.anm_manager_name(anm,id,p),1);c.release(p);};
 try{
 load('ascii.anm',2);assert.equal(c.anm_manager_fallback(anm,2),1);for(const [n,id]of [['enemy.anm',1],['effect.anm',8],['bullet.anm',7],['pl0'+character+'.anm',9+character]])load(n,id);
 const sb=readFileSync(resolve(root,'reference/assets/pl0'+character+'.sht')),sp=c.allocate(sb.length);memory(c,sp,sb.length).set(sb);assert.equal(c.sht_open(sht,sp,sb.length),1);c.release(sp);const bg=readFileSync(resolve(root,'reference/assets/st01.std')),bp=c.allocate(bg.length);memory(c,bp,bg.length).set(bg);assert.equal(c.stage_resource_open(backgroundResource,bp,bg.length),1);c.release(bp);load(string(c,c.stage_resource_name(backgroundResource)),15);background=c.stage_scene_create(backgroundResource,anm,15);assert.equal(c.stage_scene_initialize(background,.6),1);
 memory(c,pp,bytes.length).set(bytes);assert.equal(c.program_attach(program,pp,bytes.length),0);battle=c.game_battle_create(anm,program,sht,character);assert.equal(c.game_battle_initialize(battle),1,string(c,c.game_battle_error(battle)));dv().setInt32(c.game_battle_field(battle,0),1,true);dv().setInt32(c.game_battle_field(battle,3)+28,400,true);assert.equal(c.game_battle_options(battle),1);c.timer_action(c.game_battle_field(battle,14),0,600,1,0);
 memory(c,name,5).set(Buffer.from('main\0'));const req=Buffer.alloc(84);req.writeFloatLE(0);req.writeFloatLE(144,4);req.writeInt32LE(1000000,20);memory(c,request,84).set(req);assert.equal(c.game_battle_spawn(battle,name,request),1,string(c,c.game_battle_error(battle)));
 checkpoint=c.battle_checkpoint_create(battle,background);const progress=c.battle_checkpoint_field(checkpoint,0);dv().setInt32(progress+16,character,true);
 const step=(held=1,pressed=0)=>{assert.equal(c.stage_scene_update(background,1,1,0),1,string(c,c.stage_scene_error(background)));assert.equal(c.game_battle_step(battle,held,pressed,0,1,1),1,string(c,c.game_battle_error(battle)));frames++;};
 for(let i=0;i<37;i++)step();assert.equal(c.game_battle_cancel_bullets(battle),1);assert.ok(Array.from(new Uint32Array(c.memory.buffer,c.game_battle_cancellation(battle),2000)).some(h=>h),'actual cancellation animations recorded');step(0,2);for(let i=0;i<12;i++)step();assert.equal(dv().getInt32(c.game_battle_field(battle,3)+20,true),1,'actual active character bomb');assert.ok(c.game_battle_item(battle,10));c.battle_checkpoint_popups(checkpoint,12345);
 dv().setInt32(progress+8,79,true);dv().setInt32(progress+12,91,true);dv().setInt32(progress+120,31,true);
 assert.equal(c.battle_checkpoint_capture(checkpoint,19),1,string(c,c.battle_checkpoint_error(checkpoint)));assert.ok(c.battle_checkpoint_count(checkpoint)>0,'real animation clones');
 const copy=(p,n)=>Buffer.from(memory(c,p,n)),position=copy(c.game_battle_field(battle,1),12),enemyMotion=copy(c.game_battle_enemy_field(battle,1,0),68),enemyAge=copy(c.game_battle_enemy_field(battle,1,1),20),enemyLife=c.game_battle_enemy_life(battle,1),bombPosition=copy(c.game_battle_bomb_common(battle,0),12),bombAge=dv().getInt32(c.game_battle_bomb_common(battle,2)+4,true),bgTimer=copy(c.stage_scene_state(background),20),popup=copy(c.battle_checkpoint_field(checkpoint,1),18*72),bullets=Array.from({length:2000},(_,i)=>copy(c.game_battle_bullet(battle,i),c.game_battle_bullet_size()));
 for(let retry=0;retry<6;retry++){
 for(let i=0;i<13;i++)step(1|0x80);dv().setInt32(progress+8,1987,true);dv().setInt32(progress+120,91,true);c.battle_checkpoint_popups(checkpoint,888);assert.equal(c.battle_checkpoint_restore(checkpoint),1,string(c,c.battle_checkpoint_error(checkpoint)));
 assert.deepEqual(copy(c.game_battle_field(battle,1),12),position);assert.deepEqual(copy(c.game_battle_enemy_field(battle,1,0),68),enemyMotion);assert.deepEqual(copy(c.game_battle_enemy_field(battle,1,1),20),enemyAge);assert.equal(c.game_battle_enemy_life(battle,1),enemyLife);assert.deepEqual(copy(c.game_battle_bomb_common(battle,0),12),bombPosition);assert.equal(dv().getInt32(c.game_battle_bomb_common(battle,2)+4,true),bombAge);assert.deepEqual(copy(c.stage_scene_state(background),20),bgTimer);assert.deepEqual(copy(c.battle_checkpoint_field(checkpoint,1),18*72),popup);assert.equal(dv().getInt32(progress+8,true),79);assert.equal(dv().getInt32(progress+120,true),31);assert.equal(dv().getInt32(c.game_battle_field(battle,3)+28,true),399-retry,'original cumulative retry power penalty');assert.equal(c.game_battle_laser_count(battle),0,'lasers retired during retry');for(let i=0;i<2000;i++)assert.deepEqual(copy(c.game_battle_bullet(battle,i),c.game_battle_bullet_size()),bullets[i],'bullet state restored '+i);checks+=2012;retries++;
 }
 assert.equal(c.battle_checkpoint_file_write(file,checkpoint,0),1,string(c,c.battle_checkpoint_error(checkpoint)));const imported=c.battle_checkpoint_create(battle,background);dv().setInt32(c.battle_checkpoint_field(imported,0)+16,character,true);const encoded=copy(c.player_checkpoint_file_bytes(file),c.player_checkpoint_file_size(file));memory(c,fileBuffer,encoded.length).set(encoded);assert.equal(c.battle_checkpoint_file_read(file,imported,fileBuffer,encoded.length-1,0),0);assert.equal(c.battle_checkpoint_file_read(file,imported,fileBuffer,encoded.length,0),1,string(c,c.battle_checkpoint_error(imported)));assert.equal(c.battle_checkpoint_restore(imported),1,string(c,c.battle_checkpoint_error(imported)));assert.deepEqual(copy(c.game_battle_field(battle,1),12),position,'file restored player');assert.deepEqual(copy(c.game_battle_enemy_field(battle,1,0),68),enemyMotion,'file restored enemy motion');assert.deepEqual(copy(c.game_battle_bomb_common(battle,0),12),bombPosition,'file restored bomb');assert.equal(dv().getInt32(c.game_battle_bomb_common(battle,2)+4,true),bombAge,'file restored bomb clock');for(let i=0;i<24;i++)step();c.battle_checkpoint_delete(imported);checks+=7;retries++;
 c.battle_checkpoint_available(checkpoint,0);assert.equal(c.battle_checkpoint_restore(checkpoint),0,'resource boundary failure propagates');assert.match(string(c,c.battle_checkpoint_error(checkpoint)),/resource/);checks+=2;
 }finally{c.player_checkpoint_file_delete(file);c.release(fileBuffer);if(checkpoint)c.battle_checkpoint_delete(checkpoint);if(battle)c.game_battle_delete(battle);if(background)c.stage_scene_delete(background);c.stage_resource_delete(backgroundResource);c.release(pp);c.release(name);c.release(request);c.sht_delete(sht);c.program_delete(program);c.anm_manager_delete(anm);}
 }
 report('battle-checkpoint-integration',{passed:true,characters:4,frames,retries,checks,scope:'Actual combined Player/Enemy/ECL/STD/Bullet/Item/Effect/Popup/Bomb snapshots share an owned animation checkpoint pool. Synthetic battle drives real player shots, lasers, cancellation animations and all four active bombs before saving and six repeated restores per character. Restored game objects continue executing, original power penalty and progress restoration apply, and integration errors propagate. All nine modules encode into the native compressed t15b/v6 container; a fresh checkpoint pool imports and restores each character then executes another 24 frames. GUI overlays/platform disk persistence are fixture boundaries. Full original stage/replay/GPU session is not covered.'});
});
