import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {resolve} from 'node:path';import {core,oracle,memory,string,root,report,enableNativeMath} from './helpers.mjs';import {resourceLoader,nativePool,nativeInstances,prepareBank,compareAnm} from './anm-oracle.mjs';
test('TH15 four character bomb checkpoints match original active/inactive transitions and owned animation trees',async()=>{
 const c=await core(),m=await oracle(),manager=c.anm_manager_create(),anm=c.anm_checkpoint_create(),nm=nativePool(m),loader=resourceLoader(m),native=m.allocate(0xbc),out=m.allocate(4);enableNativeMath(m);m.u32(0x4ca620,0x4e73e8);m.f32(0x4e73e8,1);
 let fixture=0,snapshot=0,checks=0,captures=0,restores=0;const file=c.player_checkpoint_file_create(),fileInput=c.allocate(2*1024*1024),nativeFile=m.allocate(2*1024*1024),used=m.allocate(4);
 const bytes=readFileSync(resolve(root,'reference/assets/front.anm')),p=c.allocate(bytes.length);memory(c,p,bytes.length).set(bytes);assert.equal(c.anm_manager_load(manager,3,p,bytes.length),1);const bank=prepareBank(m,loader,'front.anm',bytes,nm,3);c.release(p);for(let kind=0;kind<4;kind++){const b=readFileSync(resolve(root,'reference/assets','pl0'+kind+'.anm')),q=c.allocate(b.length);memory(c,q,b.length).set(b);assert.equal(c.anm_manager_load(manager,10+kind,q,b.length),1);c.release(q);}
 const writeAt=[0x417180,0x415850,0x417d80,0x4188f0],readAt=[0x4172a0,0x415930,0x417e60,0x4189d0];const names=['reimu','marisa','sanae','reisen'],captureAt=[0x416df0,0x4155f0,0x417c90,0x418800],restoreAt=[0x416ee0,0x415770,0x417d20,0x418890];
 const set32=(cp,np,v)=>{new DataView(c.memory.buffer).setUint32(cp,v>>>0,true);m.u32(np,v);},same=(cp,np,n,label)=>{assert.deepEqual(Buffer.from(memory(c,cp,n)),Buffer.from(m.bytes(np,n)),label);checks++;};
 const spawn=(index)=>{const script=[241,221,243][index%3],handle=c.anm_manager_spawn(manager,3,script,24,2);m.call(0x433020,{ecx:bank,args:[out,script,24,0],limit:10000000});assert.equal(handle>>>0,m.u32(out),'spawn script '+script+' index '+index+' queue '+nativeInstances(m,nm,0).length+' / '+c.anm_manager_count(manager,0));return handle;};
 const queues=label=>{for(let alt=0;alt<2;alt++){const list=nativeInstances(m,nm,alt);assert.equal(c.anm_manager_count(manager,alt),list.length,label+' count');for(let i=0;i<list.length;i++){const np=list[i],h=m.u32(np+0x544),vm=c.anm_manager_find(manager,h);assert.equal(c.anm_manager_order(manager,alt,i)>>>0,h,label+' order');compareAnm(c,m,vm,np,label+' VM '+h);checks++;}}};
 const clearLive=()=>{for(let alt=0;alt<2;alt++)while(nativeInstances(m,nm,alt).length){const np=nativeInstances(m,nm,alt)[0],h=m.u32(np+0x544);assert.equal(c.anm_manager_destroy_tree(manager,c.anm_manager_find(manager,h)),1);m.call(0x488820,{ecx:nm,args:[np]});}};
 try{for(let kind=0;kind<4;kind++){const name=names[kind],field=(i)=>c['bomb_'+name+'_field'](fixture,i);fixture=c['bomb_'+name+'_create'](manager,10+kind);snapshot=c.bomb_checkpoint_create(fixture,anm,kind);m.view(native,0xbc).fill(0);const orbNative=m.allocate(0x6c0);
 for(let sample=0;sample<8;sample++){
  clearLive();c.anm_checkpoint_clear(anm);m.call(0x489590,{limit:100000000});m.u32(native+0xb8,0);
    const active=sample&1,currentActive=sample>>1&1;
  const seed=(salt,isActive)=>{
   memory(c,field(0),12).set(new Uint8Array(new Float32Array([salt*1.25,271-salt,0]).buffer));m.write(native+0x14,Buffer.from(memory(c,field(0),12)));new DataView(c.memory.buffer).setFloat32(field(1),salt*.125,true);m.f32(native+0x20,salt*.125);set32(field(3)+20,native+0x24,isActive);
   for(let secondary=0;secondary<2;secondary++){const cp=secondary?c.bomb_controller_field(fixture,kind,0):field(2),np=native+(secondary?0x3c:0x28),timer=Buffer.alloc(20);timer.writeInt32LE(salt-1);timer.writeInt32LE(salt,4);timer.writeFloatLE(salt+.625,8);timer.writeUInt32LE(0,12);timer.writeUInt32LE(1,16);memory(c,cp,20).set(timer);m.write(np,timer);}
   new DataView(c.memory.buffer).setUint8(c.bomb_controller_field(fixture,kind,1),salt&1);m.u32(native+0x5c,salt&1);
   if(kind===3)set32(field(15),native+0x60,salt%4);
   if(kind){set32(field(13),native+0x50,sample===6?0:spawn(salt));}
   set32(field(14),native+0x58,sample===4?0:spawn(salt+1));
   if(!kind){m.u32(native+0x64,orbNative);c.bomb_reimu_orb_available(fixture,1);for(let i=0;i<8;i++){const np=orbNative+i*0xd8;set32(c.bomb_reimu_orb(fixture,i,0),np,i===5?0:spawn(salt+i+2));for(const [f,o,n]of [[1,4,68],[2,0xa0,4],[3,0xa4,20],[4,0xb8,12],[5,0xc4,4],[6,0xcc,4],[7,0xd0,4]]){const cp=c.bomb_reimu_orb(fixture,i,f),data=Buffer.alloc(n);for(let j=0;j<n/4;j++)data.writeUInt32LE((salt*197+i*31+j)>>>0,j*4);memory(c,cp,n).set(data);m.write(np+o,data);}m.u32(np+0xd4,0);}}
  };
  seed(31+sample,active);const outside=Buffer.from(memory(c,field(3),20));
  assert.equal(c.bomb_checkpoint_capture(snapshot),1,string(c,c.bomb_checkpoint_error(snapshot)));m.call(captureAt[kind],{ecx:native,limit:100000000});captures++;
  for(let secondary=0;secondary<2;secondary++)same(c.bomb_checkpoint_age(snapshot,secondary),native+(secondary?0x90:0x7c),20,'saved timer '+kind+'/'+sample);
  if(kind)assert.equal(c.bomb_checkpoint_handle(snapshot,0)>>>0,m.u32(native+0xa4));assert.equal(c.bomb_checkpoint_handle(snapshot,1)>>>0,m.u32(native+0xac));
  if(!kind&&active){const backup=m.u32(native+0xb8);assert.ok(backup);for(let i=0;i<8;i++){const orb=c.bomb_checkpoint_orb(snapshot,i);same(orb,backup+i*0xd8,4,'saved orb handle');}}
  queues('capture '+kind+'/'+sample);
  assert.equal(c.bomb_checkpoint_file_write(file,snapshot),1,string(c,c.bomb_checkpoint_error(snapshot)));m.u32(used,0);m.call(writeAt[kind],{ecx:native,args:[nativeFile,used],limit:100000000});const encoded=Buffer.from(memory(c,c.player_checkpoint_file_bytes(file),c.player_checkpoint_file_size(file))),original=Buffer.from(m.bytes(nativeFile,m.u32(used)));assert.equal(encoded.length,original.length,'bomb file size '+kind+'/'+sample);assert.deepEqual(encoded.subarray(0,0x50),original.subarray(0,0x50),'bomb common file state '+kind+'/'+sample);
  let at=0x54;if(!kind&&active){for(let i=0;i<8;i++)for(const [o,n]of [[0,72],[0xa0,4],[0xa4,20],[0xb8,16],[0xcc,12]])assert.deepEqual(encoded.subarray(at+i*0xd8+o,at+i*0xd8+o+n),original.subarray(at+i*0xd8+o,at+i*0xd8+o+n),'bomb file orb '+sample+'/'+i+'/'+o.toString(16));at+=0x6c0;}
  for(;at<original.length;at+=0x608)for(const [off,n]of [[0,0x28],[0x28,12],[0x34,0x500],[0x54c,0x28],[0x5c0,4],[0x5ec,12]])assert.deepEqual(encoded.subarray(at+off,at+off+n),original.subarray(at+off,at+off+n),'bomb file animation '+kind+'/'+sample+'/'+at.toString(16)+'/'+off.toString(16));
  memory(c,fileInput,original.length).set(original);const poolCount=c.anm_checkpoint_count(anm),generation=new DataView(c.memory.buffer).getUint32(c.anm_checkpoint_generation(anm),true);assert.equal(c.bomb_checkpoint_file_read(file,snapshot,fileInput,original.length-1),0);assert.equal(c.anm_checkpoint_count(anm),poolCount);assert.equal(new DataView(c.memory.buffer).getUint32(c.anm_checkpoint_generation(anm),true),generation);assert.equal(c.bomb_checkpoint_file_read(file,snapshot,fileInput,original.length),1,string(c,c.bomb_checkpoint_error(snapshot)));assert.equal(c.player_checkpoint_file_consumed(file),original.length);m.call(readAt[kind],{ecx:native,args:[nativeFile,original.length],limit:100000000});checks+=6;
  seed(71+sample,currentActive);
  assert.equal(c.bomb_checkpoint_restore(snapshot),1,string(c,c.bomb_checkpoint_error(snapshot)));m.call(restoreAt[kind],{ecx:native,limit:100000000});restores++;
  same(field(0),native+0x14,12,'restored position');same(field(1),native+0x20,4,'restored angle');same(field(3)+20,native+0x24,4,'restored state');same(field(2),native+0x28,20,'restored age');same(c.bomb_controller_field(fixture,kind,0),native+0x3c,20,'restored second age');assert.equal(new DataView(c.memory.buffer).getUint8(c.bomb_controller_field(fixture,kind,1)),m.u32(native+0x5c));assert.deepEqual(Buffer.from(memory(c,field(3),20)),outside,'external player session preserved');
  if(kind)same(field(13),native+0x50,4,'restored first');same(field(14),native+0x58,4,'restored aura');if(kind===3)same(field(15),native+0x60,4,'restored charges');
  if(!kind&&active){const live=m.u32(native+0x64);for(let i=0;i<8;i++){for(const [f,o,n]of [[0,0,4],[1,4,68],[2,0xa0,4],[3,0xa4,20],[4,0xb8,12],[5,0xc4,4],[6,0xcc,4],[7,0xd0,4]])same(c.bomb_reimu_orb(fixture,i,f),live+i*0xd8+o,n,'restored orb '+i+' field '+f);assert.equal(c.bomb_reimu_orb_archived(fixture,i),m.u32(live+i*0xd8+0xd4));}}
  queues('restore '+kind+'/'+sample);
 }
 c.bomb_checkpoint_delete(snapshot);snapshot=0;c['bomb_'+name+'_delete'](fixture);fixture=0;
 }
 report('bomb-checkpoint',{passed:true,characters:4,captures,restores,checks,originalFunctions:captureAt.concat(restoreAt).map(x=>'0x'+x.toString(16)),scope:'Native character-specific module file write/import, bounded truncation rollback, exact Reimu live/saved aura slot behavior; original common copied state and timer normalization, all active/inactive save/restore combinations, character-dependent retirement, Reimu eight independent orb states, deep animation child trees, clone handle generation and live queue order. Full world chapter integration remains separate.'});
 }finally{c.player_checkpoint_file_delete(file);c.release(fileInput);if(snapshot)c.bomb_checkpoint_delete(snapshot);if(fixture)c['bomb_'+names[0]+'_delete'](fixture);c.anm_checkpoint_delete(anm);c.anm_manager_delete(manager);m.close();}
});
