import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {resolve} from 'node:path';
import {core,oracle,memory,string,root,report,enableNativeMath} from './helpers.mjs';
test('TH15 bullet visual ownership integrates real animation, collision visuals and interrupt state like original',async()=>{
 const c=await core(),m=await oracle(),visual=c.bullet_visual_create(),vm=c.bullet_visual_vm(visual,0),rng=c.bullet_visual_rng(visual),bank=m.allocate(0x13c),native=m.allocate(0x608),bullet=m.allocate(0x1500),manager=m.allocate(0x187f600),source=m.allocate(1024),path=m.allocate(64),vtable=m.allocate(0x60),texture=m.allocate(16);let width,height,checks=0,frames=0;
 const data=readFileSync(resolve(root,'reference/assets/bullet.anm')),p=c.allocate(data.length),resource=c.anm_create();memory(c,p,data.length).set(data);assert.equal(c.anm_open(resource,p,data.length),1);m.u32(texture,vtable);enableNativeMath(m);
 m.replace(0x490cf2,'fixture format path',()=>0);m.replace(0x402db0,'original ANM resource bytes',()=>{const out=m.allocate(data.length);m.write(out,data);if(m.reg('EDX'))m.u32(m.reg('EDX'),data.length);return out;},1);
 const desc=m.registerImport({dll:'fixture',name:'texture dimensions',argc:3,handler:()=>{const out=m.u32(m.reg('ESP')+12);m.view(out,32).fill(0);m.u32(out+24,width);m.u32(out+28,height);return 0;}});m.u32(vtable+0x44,desc);
 for(const a of [0x485a60,0x485c30,0x485c80,0x485820])m.replace(a,'dimension preserving texture allocation',()=>{m.u32(m.u32(m.reg('ESP')+4),texture);return 0;});m.f32(0x51bc04,2);m.u32(0x51bbfc,640);m.u32(0x51bc00,480);m.write(path,Buffer.from('bullet.anm\0'));m.call(0x485d20,{ecx:bank,args:[path]});
 let at=0,chunk=0,ns=0,nc=0;do{width=data.readUInt16LE(at+10);height=data.readUInt16LE(at+12);m.call(0x486300,{args:[bank,chunk,ns,nc,m.u32(bank+0x108)+at]});ns+=data.readUInt16LE(at+4);nc+=data.readUInt16LE(at+6);chunk++;const next=data.readUInt32LE(at+36);if(!next)break;at+=next;}while(at<data.length);
 m.u32(0x503c18,manager);m.u32(manager+0x187f4d8,bank);m.u32(0x4ca620,0x4e73e8);m.f32(0x4e73e8,1);
 const presets=JSON.parse(readFileSync(resolve(root,'reference/bullet-appearance.json'),'utf8')).presets;const cases=[];
 const fields=[[0,0x18,8],[8,0x24,4],[16,0x4ec,12],[28,0x50,12],[40,0x5c,8],[48,0x64,8],[56,0x6c,8],[64,0x74,8],[72,0x84,8],[80,0x3d4,8],[88,0x8c,8],[96,0x538,8]];
 try{for(let type=0;type<44;type++)for(const color of [0,1])for(const interrupt of [0,1,2,7,8,9]){
  const spec=presets[type],index=spec.script,rate=interrupt&1?.5:1,seed=(type*327+color*197+3)&65535;m.f32(0x4e73e8,rate);new DataView(c.memory.buffer,c.anm_vm_visual(vm)+8,4).setInt32(0,0,true);m.view(native,0x608).fill(0);m.call(0x40d680,{ecx:native});m.u32(native+0x5e8,1);m.u32(native+0x5f8,bullet);m.u32(bullet+0x1490,type|(color<<16));new DataView(c.memory.buffer,rng,8).setUint32(0,seed,true);new DataView(c.memory.buffer,rng,8).setUint32(4,0,true);m.u32(0x4e9a40,seed);m.u32(0x4e9a44,0);m.call(0x477510,{ecx:bank,args:[native,index]});m.u32(native+0x1c,(m.u32(native+0x1c)&~0x80000)|0x40000);assert.equal(c.bullet_visual_bind(visual,resource,type,color,rate),1,string(c,c.bullet_visual_error(visual)));let length=0;

  for(let frame=0;frame<128;frame++){
   if(frame===3&&interrupt){c.bullet_visual_interrupt(visual,interrupt);m.u32(native+0x49c,interrupt);}
   if(frame===7){const flags=m.u32(native+0x18)|0x20000;new DataView(c.memory.buffer,c.bullet_visual_state_field(visual,0),4).setUint32(0,flags,true);m.u32(native+0x18,flags);const jitter=Buffer.alloc(12);jitter.writeFloatLE(.375);jitter.writeFloatLE(-.625,4);memory(c,c.bullet_visual_state_field(visual,1),12).set(jitter);m.write(native+0x38,jitter);new DataView(c.memory.buffer,c.bullet_visual_state_field(visual,2),4).setUint32(0,0xffffa080,true);m.u32(native+0x53c,0xffffa080);}const status=c.bullet_visual_tick(visual,0);assert.ok(status>=0,string(c,c.bullet_visual_error(visual)));const original=m.call(0x477e10,{ecx:native,limit:10000000})|0;assert.equal(status,original,JSON.stringify({type,color,interrupt,frame,status:true}));
   const vp=c.anm_vm_visual(vm),vars=c.anm_vm_variables(vm);const spriteExpected=Buffer.concat([Buffer.from(m.bytes(native+0x3b4,32)),Buffer.from(m.bytes(native+0x7c,8)),Buffer.from(m.bytes(native+0x3dc,192))]);assert.deepEqual(Buffer.from(memory(c,c.anm_vm_sprite_values(vm),232)),spriteExpected,JSON.stringify({type,color,interrupt,frame,sprite:true}));checks++;for(const [co,no,n]of fields){assert.deepEqual(Buffer.from(memory(c,vp+co,n)),Buffer.from(m.bytes(native+no,n)),JSON.stringify({type,color,interrupt,frame,field:no.toString(16)}));checks++;}
   for(const [co,no,n]of [[0,0x4ac,32],[64,0x38,12],[76,0x44,12]]){assert.deepEqual(Buffer.from(memory(c,vars+co,n)),Buffer.from(m.bytes(native+no,n)),JSON.stringify({type,color,interrupt,frame,variable:no.toString(16)}));checks++;}
   assert.equal(c.anm_vm_offset(vm),m.i32(native+0x34));assert.deepEqual(Buffer.from(memory(c,c.anm_vm_timer(vm),20)),Buffer.from(m.bytes(native+0x54c,20)),JSON.stringify({type,color,interrupt,frame,timer:true}));assert.deepEqual(Buffer.from(memory(c,rng,8)),Buffer.from(m.bytes(0x4e9a40,8)));for(const [field,offset,n]of [[0,0x18,4],[1,0x38,12],[2,0x53c,4],[3,0x49c,4]])assert.deepEqual(Buffer.from(memory(c,c.bullet_visual_state_field(visual,field),n)),Buffer.from(m.bytes(native+offset,n)),JSON.stringify({type,color,interrupt,frame,shared:field}));assert.equal(memory(c,c.bullet_visual_state_field(visual,4),1)[0],m.i32(native+0x4ac)?1:0);checks+=8;frames++;length++;if(status)break;
  }cases.push({type,color,interrupt,frames:length});
 }report('bullet-visual',{passed:true,checks,frames,types:44,interrupts:[0,1,2,7,8,9],originalFunctions:['0x40d680','0x477510','0x477e10','0x41efd0'],scope:'Production bullet visual binding and real script execution, live collision visual fields, pending interrupt consumption and spawn-completion feedback. Full pool host, GPU draw submission and collision geometry remain separate integration work.',cases});}
 finally{c.bullet_visual_delete(visual);c.anm_delete(resource);c.release(p);m.close();}
});



