import test from 'node:test';import assert from 'node:assert/strict';import {core,oracle,memory,report,enableNativeMath} from './helpers.mjs';import {bits} from './ecl-fixtures.mjs';
test('TH15 aimed, ring, random and sine-weighted bullet formations match original',async()=>{
 const c=await core(),m=await oracle(),fixture=c.enemy_variables_create(),out=c.bullet_initial_create(),p=c.allocate(896),native=m.allocate(0x1500),manager=m.allocate(0x141f0dc),shooter=m.allocate(896),player=m.allocate(0x620);enableNativeMath(m);m.u32(0x4e9a6c,manager);m.u32(0x4e9bb8,player);
 // The original formation and transform dispatcher execute normally. Only
 // resource binding, visual matrix updates and recycling are host boundaries.
 m.replace(0x477510,'animation_resource_binding_boundary',()=>0,2);m.replace(0x477e10,'animation_visual_update_boundary',()=>0);m.replace(0x419e10,'bullet_recycle_boundary',()=>0);let checks=0,cases=0;
 try{for(let pattern=0;pattern<16;pattern++)for(let sample=0;sample<48;sample++)for(let row=0;row<5;row++)for(let column=0;column<9;column++){
  const b=Buffer.alloc(896);b.writeFloatLE((sample-31)*.25,8);b.writeFloatLE((sample-19)*.375,12);b.writeFloatLE((sample-11)*.0625,16);b.writeFloatLE((sample-23)*.046875,20);b.writeFloatLE((sample-17)*.03125,24);b.writeFloatLE((sample-13)*.125,28);b.writeFloatLE((sample-7)*.0625,32);b.writeFloatLE(sample%3?(sample-19)*.25:0,36);b.writeInt16LE([1,2,3,5,8,11][sample%6],868);b.writeInt16LE([1,2,3,5,8,11][Math.floor(sample/6)%6],870);b.writeInt16LE(pattern,872);b.writeInt32LE(0x23,876);memory(c,p,896).set(b);c.enemy_shooter_read(fixture,0,p);m.write(shooter,b);
  const rng=Buffer.alloc(8);rng.writeUInt16LE((sample*997+row*737+column*373)&65535);rng.writeUInt32LE(sample*317,4);memory(c,c.enemy_variables_rng(fixture),8).set(rng);m.write(0x4e9a48,rng);const position=Buffer.alloc(12);position.writeFloatLE((sample-19)*.25,0);position.writeFloatLE((sample-13)*.375,4);memory(c,c.enemy_world_field(fixture,0,0),12).set(position);m.write(player+0x618,position.subarray(0,8));m.view(native,0x1500).fill(0);memory(c,out,32).fill(0);m.u32(manager+0x5c,native);m.view(manager+0x68,16).fill(0);const minimum=sample%4===0?4:0,aim=(sample-27)*.078125;m.f32(manager+0x44,minimum);
  const expected=m.call(0x41a600,{ecx:manager,args:[shooter,column,row,bits(aim)]})|0,actual=c.bullet_initial_form(fixture,out,0,column,row,aim,minimum),label=JSON.stringify({pattern,sample,column,row});assert.equal(actual,expected===0?1:0,label+' accepted');const motion=Buffer.concat([Buffer.from(m.bytes(native+0xc38,12)),Buffer.from(m.bytes(native+0xc44,12)),Buffer.from(m.bytes(native+0xc50,8))]);assert.deepEqual(Buffer.from(memory(c,out,32)),motion,label+' motion');assert.deepEqual(Buffer.from(memory(c,c.enemy_variables_rng(fixture),8)),Buffer.from(m.bytes(0x4e9a48,8)),label+' random consumption');checks+=3;cases++;
 }report('bullet-initial-formations',{passed:true,cases,checks,originalFunction:'0x41a600',patterns:13,scope:'Initial position, velocity, angle, speed, random consumption and minimum-distance rejection. Original transforms are empty; pool ownership, resource-derived hitboxes and subsequent bullet frames are separate modules.'});
 }finally{c.bullet_initial_delete(out);c.enemy_variables_delete(fixture);c.release(p);m.close();}
});
