import test from 'node:test';import assert from 'node:assert/strict';import {core,oracle,memory,string,report,enableNativeMath} from './helpers.mjs';
test('TH15 bullet object transforms preserve original enemy and moving/stationary laser requests',async()=>{
 const c=await core(),m=await oracle(),native=m.allocate(0x1500),player=m.allocate(0x620),enemyManager=m.allocate(0x200),laserManager=m.allocate(0x610),vtable=m.allocate(0x30),name=m.allocate(32),input=c.allocate(44),out=c.allocate(84),cn=c.allocate(32);memory(c,cn,16).set(Buffer.from('SpawnFromBullet\0'));enableNativeMath(m);m.u32(0x4e9bb8,player);m.u32(0x4e9a80,enemyManager);m.u32(0x4e9ba0,laserManager);m.u32(0x4ca620,0x4e73e8);m.f32(0x4e73e8,1);m.write(name,Buffer.from('SpawnFromBullet\0'));let requests=[],enemyNames=[],cancelled=0,currentKind=0,cases=0,checks=0;
 const sp=()=>m.reg('ESP');m.replace(0x426050,'capture actual bullet-spawned enemy request',()=>{enemyNames.push(m.string(m.u32(sp()+4)));requests.push(Buffer.from(m.bytes(m.u32(sp()+8),84)));return 1;},3);
 const ctor=(p,kind)=>{currentKind=kind;m.u32(p,vtable);return p;};m.replace(0x441300,'moving laser constructor boundary',()=>ctor(m.reg('ECX'),0));m.replace(0x441b20,'stationary laser constructor boundary',()=>ctor(m.reg('ECX'),1));m.u32(vtable+12,m.registerImport({dll:'fixture',name:'laser initializer request',argc:1,handler:()=>{requests.push(Buffer.from(m.bytes(m.u32(sp()+4),currentKind?0x378:0x358)));return 1;}}));m.replace(0x41e250,'laser conversion source bullet cancellation',()=>{cancelled++;return 0;},1);
 try{for(let kind=0;kind<3;kind++)for(let sample=0;sample<192;sample++){
  const f=c.bullet_state_create();try{requests=[];enemyNames=[];cancelled=0;m.view(native,0x1500).fill(0);m.view(laserManager,0x610).fill(0);m.u32(laserManager+0x5e0,laserManager+12);
  const position=Buffer.alloc(32);[-32+sample*.25,81+sample*.5,0,Math.fround(Math.cos(.75)*2),Math.fround(Math.sin(.75)*2),0,2,.75].forEach((v,i)=>position.writeFloatLE(v,i*4));memory(c,c.bullet_state_field(f,0,0),32).set(position);m.write(native+0xc38,position);const target=Buffer.alloc(12);target.writeFloatLE(sample%2?30:position.readFloatLE(0));target.writeFloatLE(sample%2?320:position.readFloatLE(4),4);memory(c,c.bullet_state_field(f,15,0),12).set(target);m.write(player+0x618,target.subarray(0,8));const index=sample%4;new DataView(c.memory.buffer).setInt32(c.bullet_state_field(f,16,0),index,true);m.i32(native+0xc9c,index);m.i32(native+0xc7c,-1);new DataView(c.memory.buffer).setInt32(c.bullet_state_field(f,33,0),-1,true);
  const primary=Buffer.alloc(44),secondary=Buffer.alloc(44),sentinel=[-999999,-999990,999990,999999,-1.25,6.5,1.125,0][sample%8];[sentinel,sample%3?2.5:-999990,64,256].forEach((v,i)=>primary.writeFloatLE(v,i*4));const packed=kind===1?sample%2:((sample%2)<<16)|((sample%17)<<8)|(sample%256);[kind===0?31:kind-1,kind===0?37:sample%12,kind===0?71:sample%8,kind===0?83:packed].forEach((v,i)=>primary.writeInt32LE(v,16+i*4));primary.writeUInt32LE(kind===0?0x1000000:0x8000000,32);primary.writeInt32LE(1,36);if(!kind)primary.writeUInt32LE(name,40);[96,12,16,sample].forEach((v,i)=>secondary.writeFloatLE(v,i*4));[30,31,5+sample%13,90].forEach((v,i)=>secondary.writeInt32LE(v,16+i*4));
  for(let i=0;i<18;i++){const b=i===index?primary:i===index+1&&kind?secondary:Buffer.alloc(44);memory(c,input,44).set(b);c.bullet_transform_read(f,i,input);m.write(native+0xca4+i*44,b);}if(!kind)c.bullet_object_payload(f,index,cn);
  m.call(0x41b180,{ecx:native});assert.equal(c.bullet_activate(f),1,string(c,c.bullet_activation_error(f)));assert.equal(requests.length,1);assert.equal(new DataView(c.memory.buffer).getInt32(c.bullet_state_field(f,16,0),true),m.i32(native+0xc9c),'index '+kind+'/'+sample);
  if(!kind){c.bullet_object_enemy(f,out);assert.deepEqual(Buffer.from(memory(c,out,84)),requests[0],'enemy '+sample);assert.equal(string(c,c.bullet_object_enemy_name(f)),enemyNames[0]);assert.equal(c.bullet_object_count(f,1),1);}
  else{assert.equal(c.bullet_object_laser_kind(f),kind-1);{const actual=Buffer.from(memory(c,c.bullet_object_laser(f),requests[0].length));const diffs=[];for(let at=0;at<actual.length;at+=4)if(actual.readUInt32LE(at)!==requests[0].readUInt32LE(at))diffs.push([at.toString(16),actual.readUInt32LE(at).toString(16),requests[0].readUInt32LE(at).toString(16)]);assert.deepEqual(diffs,[],'laser '+kind+'/'+sample);}assert.equal(c.bullet_collision_event(f,1),cancelled,'source cancellation '+kind+'/'+sample);assert.equal(c.bullet_object_count(f,0),1);}checks+=5;cases++;
  }finally{c.bullet_state_delete(f);}
 }
 report('bullet-object-transforms',{passed:true,cases,checks,originalFunctions:['0x41b180'],scope:'Unmodified native activation prepares every byte of enemy spawn and moving/stationary laser requests. Sentinel angles/speeds, packed flags, transform copying/index advancement, continuation payloads, source cancellation and argument ordering are compared. Actual enemy/laser update implementations have separate tests; full-stage GPU/replay remains separate.'});
 }finally{c.release(input);c.release(out);c.release(cn);m.close();}
});
