import test from 'node:test';import assert from 'node:assert/strict';import {core,oracle,memory,string,report} from './helpers.mjs';
const fields=[[0,0,0xc38,32],[24,0,0xc8a,2],[25,0,0x20,4],[31,0,0x1468,20],[33,0,0xc7c,4],[40,0,0x4c4,4]];
test('TH15 bullet cancellation motion, timing, spell-aware rewards and RNG match original',async()=>{
 const c=await core(),m=await oracle(),fixture=c.bullet_state_create(),native=m.allocate(0x1500),manager=m.allocate(0x141f0dc),spell=m.allocate(0x7c),callback=m.allocate(16);m.u32(0x4e9a6c,manager);m.u32(0x4e9a70,spell);m.u32(0x4cb4c8+4,callback);let hitCallbacks=0,overlayCallbacks=0,updates=0,sounds=0,lastSound=-1,items=0,angle=0,speed=0,itemPosition=Buffer.alloc(12),checks=0,frames=0;
 m.replace(callback,'cancel_hit_callback_boundary',()=>{assert.equal(m.reg('EDX'),1);if(m.reg('ECX')===native+0x630)overlayCallbacks++;else hitCallbacks++;return 0;});m.replace(0x477e10,'cancel_animation_boundary',()=>{updates++;return 0;});m.replace(0x476400,'cancel_sound_boundary',()=>{sounds++;lastSound=m.u32(m.reg('ESP')+4)|0;return 0;},1);m.replace(0x4408d0,'cancel_reward_item_boundary',()=>{items++;const sp=m.reg('ESP');assert.ok([1,10].includes(m.u32(sp+4)));itemPosition=Buffer.from(m.bytes(m.u32(sp+8),12));angle=m.f32(sp+16);speed=m.f32(sp+20);return 0;},6);
 try{for(let kind=0;kind<5;kind++)for(let sample=0;sample<256;sample++){
  const seed=Buffer.alloc(0x1500),rate=[.5,1,1.5][sample%3];[-240+sample%31*16,-48+sample%37*16,.1,(sample%17-8)*.125,(sample%19-9)*.25,(sample%13-6)*.0625,2,.5].forEach((v,i)=>seed.writeFloatLE(v,0xc38+i*4));seed.writeInt16LE(1,0xc8a);seed.writeUInt32LE(sample%7===0?512:0,0x20);seed.writeInt32LE(-1,0xc7c);seed.writeInt32LE(1,0x604);seed.writeInt32LE(1,0xc0c);seed.writeInt32LE(sample%2,0x648);seed.writeInt32LE(-1,0x1468);seed.writeInt32LE(17,0x146c);seed.writeFloatLE(17,0x1470);seed.writeUInt32LE(sample%2,0x1478);for(const [k,f,o,n]of fields)memory(c,c.bullet_state_field(fixture,k,f),n).set(seed.subarray(o,o+n));memory(c,c.bullet_state_field(fixture,35,0),1)[0]=sample%2;m.write(native,seed);new DataView(c.memory.buffer).setInt32(c.bullet_cancel_counter(fixture),sample%7-1,true);m.u32(manager+0x141f0c8,(sample%7-1)>>>0);c.bullet_cancel_spell(fixture,sample%2);m.u32(spell+0x78,sample%2);m.f32(0x4e73e8,rate);const rng=Buffer.alloc(8);rng.writeUInt16LE(sample*737&65535);memory(c,c.bullet_activation_rng(fixture),8).set(rng);m.write(0x4e9a48,rng);hitCallbacks=c.bullet_collision_event(fixture,1);overlayCallbacks=c.bullet_collision_event(fixture,2);updates=c.bullet_frame_event(fixture,1);sounds=c.bullet_sound_count(fixture);lastSound=c.bullet_sound_last(fixture);items=c.bullet_collision_event(fixture,5);itemPosition=Buffer.from(memory(c,c.bullet_state_field(fixture,45,0),12));angle=new DataView(c.memory.buffer).getFloat32(c.bullet_state_field(fixture,46,0),true);speed=new DataView(c.memory.buffer).getFloat32(c.bullet_state_field(fixture,47,0),true);
  for(let frame=0;frame<16;frame++){m.call(0x41e250,{ecx:native,args:[kind]});assert.equal(c.bullet_cancel(fixture,kind,rate),1,string(c,c.bullet_activation_error(fixture)));const label=JSON.stringify({kind,sample,frame,rate});for(const [k,f,o,n]of fields)assert.deepEqual(Buffer.from(memory(c,c.bullet_state_field(fixture,k,f),n)),Buffer.from(m.bytes(native+o,n)),label+' state '+o.toString(16));assert.equal(c.bullet_collision_event(fixture,1),hitCallbacks,label+' primary callback');assert.equal(c.bullet_collision_event(fixture,2),overlayCallbacks,label+' overlay callback');assert.equal(c.bullet_frame_event(fixture,1),updates,label+' animation tick');assert.equal(c.bullet_sound_count(fixture),sounds,label+' sounds');assert.equal(c.bullet_sound_last(fixture),lastSound,label+' sound ID');assert.equal(c.bullet_collision_event(fixture,5),items,label+' items');assert.equal(new DataView(c.memory.buffer).getInt32(c.bullet_cancel_counter(fixture),true),m.i32(manager+0x141f0c8),label+' item counter');assert.deepEqual(Buffer.from(memory(c,c.bullet_activation_rng(fixture),8)),Buffer.from(m.bytes(0x4e9a48,8)),label+' RNG');assert.deepEqual(Buffer.from(memory(c,c.bullet_state_field(fixture,45,0),12)),itemPosition,label+' item position');assert.equal(new DataView(c.memory.buffer).getFloat32(c.bullet_state_field(fixture,46,0),true),angle,label+' item angle');assert.equal(new DataView(c.memory.buffer).getFloat32(c.bullet_state_field(fixture,47,0),true),speed,label+' item speed');checks+=fields.length+12;frames++;}
 }report('bullet-cancellation',{passed:true,frames,checks,originalFunctions:['0x0041e250','0x0041e4b0'],scope:'Cancellation phase/motion/timer, primary and overlay notifications, freeze exclusion, sound, boundary checks, spell-aware item types/counts and random consumption. Cancellation visual effect allocation and item lifecycle remain separate integration.'});
 }finally{c.bullet_state_delete(fixture);m.close();}
});
