import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {resolve} from 'node:path';import {core,oracle,memory,string,root,report,enableNativeMath} from './helpers.mjs';import {resourceLoader,nativePool,nativeInstances,prepareBank,compareAnm} from './anm-oracle.mjs';import {bits} from './ecl-fixtures.mjs';
test('TH15 curve cancellation preserves original distinct clipping, effects, rewards and split requests',async()=>{
 const c=await core(),m=await oracle(),manager=c.anm_manager_create(),nm=nativePool(m),loader=resourceLoader(m),native=m.allocate(0x1580),samples=m.allocate(256*32),text=m.allocate(0x19270),spell=m.allocate(0x90),slots=m.allocate(24),tracking=m.allocate(0x1100),lasers=m.allocate(0x610),pos=m.allocate(12),size=m.allocate(12),cp=c.allocate(12),cs=c.allocate(8),origin=c.allocate(12);enableNativeMath(m);for(const [a,p]of [[0x4e9a58,text],[0x4e9a70,spell],[0x4e9a6c,slots-0x141f0c8],[0x4e9a78,tracking],[0x4e9ba0,lasers],[0x4ca620,0x4e73e8]])m.u32(a,p);let items=[],splits=[],cases=0,effects=0,checks=0,points=0;const sp=()=>m.reg('ESP');m.replace(0x4408d0,'observe cancellation reward items',()=>{const p=m.u32(sp()+8);items.push(m.u32(sp()+4),m.u32(p),m.u32(p+4),m.u32(p+8),m.u32(sp()+16),m.u32(sp()+20));return 0;},6);m.replace(0x447aa0,'capture split creation request',()=>{const request=m.u32(sp()+4);splits.push(m.i32(request+32),m.f32(request+0x354));assert.equal(m.i32(request+0x344),-1,'split sound suppression');assert.ok(m.u32(request+0x350),'split inherits actual path');return 0;},1);
 const load=(name,id)=>{const b=readFileSync(resolve(root,'reference/assets',name)),p=c.allocate(b.length);memory(c,p,b.length).set(b);assert.equal(c.anm_manager_load(manager,id,p,b.length),1,string(c,c.anm_manager_error(manager)));c.release(p);return prepareBank(m,loader,name,b,nm,id);},same=(cp,np,n,label)=>assert.deepEqual(Buffer.from(memory(c,cp,n)),Buffer.from(m.bytes(np,n)),label);
 try{m.f32(0x4e73e8,1);m.u32(text+0x19258,load('ascii.anm',2));assert.equal(c.anm_manager_fallback(manager,2),1);const bank=load('bullet.anm',9);m.u32(slots+16,bank);const heap=m.heap;
 for(let mode=0;mode<3;mode++)for(let sample=0;sample<1024;sample++){m.heap=heap;const f=c.curve_cancel_create(manager,9),motion=c.curve_cancel_motion(f),count=4+sample%124,label=mode+'/'+sample,rate=[1,.5,.995,1.25][sample%4],color=sample%16,protection=sample%5===0?7:0,honor=sample%3!==0,reward=sample%5;try{m.view(native,0x1580).fill(0);m.view(samples,256*32).fill(0);m.view(tracking,0x1100).fill(0);m.view(lasers,0x610).fill(0);m.u32(lasers+0x5e0,lasers+12);m.u32(lasers+0x604,bank);m.u32(native+0x153c,samples);m.i32(native+0x5f4,count);m.u32(native+12,1);m.i32(native+16,2);m.i32(native+0x5f0,color);m.i32(native+0x5c8,protection);m.i32(slots,sample%7);m.u32(spell+0x78,sample%2);m.f32(0x4e73e8,rate);memory(c,origin,12).fill(0);assert.equal(c.curve_motion_initialize(motion,origin,1.25,16,2,count,100),1);m.call(0x409040,{ecx:native+0x40,args:[100]});
 for(const [field,np,value]of [[0,native+12,1],[1,native+0x5f0,color],[2,native+0x5c8,protection],[3,native+16,2],[4,slots,sample%7]])new DataView(c.memory.buffer).setInt32(c.curve_cancel_field(f,field),value,true);memory(c,c.curve_cancel_field(f,7),1)[0]=sample%2;
 for(let j=0;j<count;j++){const data=Buffer.alloc(20),values=sample%4===0?[Math.fround((j-count/2)*4),100,0,1.25,2]:sample%4===1?[Math.fround(Math.sin(j*.125)*100),Math.fround(j*4),0,1.25,2]:sample%4===2?[Math.fround((j%16-8)*16),Math.fround(Math.floor(j/16)*24+64),Math.fround((j%7-3)*.25),1.25,2]:[Math.fround((j-count/2)*8),Math.fround(100+Math.sin(j*.25)*32),0,1.25,2];values.forEach((v,k)=>data.writeFloatLE(v,k*4));memory(c,c.curve_motion_sample(motion,j),20).set(data);m.write(samples+j*32,data.subarray(0,12));m.write(samples+j*32+24,data.subarray(12));}for(const [field,np]of [[5,0x4e9a48],[6,0x4e9a40]]){const rng=Buffer.alloc(8);rng.writeUInt16LE((sample*1933+mode*737)&65535);rng.writeUInt32LE(sample%13,4);memory(c,c.curve_cancel_field(f,field),8).set(rng);m.write(np,rng);}
 const center=[Math.fround((sample%7-3)*24),Math.fround(100+(sample%11-5)*16),0],radius=[0,16,32,64,96,192][sample%6],box=[Math.fround(radius*1.25),Math.fround(radius*.75)],angle=Math.fround([0,.7,1.5707963705062866,-.5][sample%4]);center.forEach((v,k)=>{new DataView(c.memory.buffer).setFloat32(cp+k*4,v,true);m.f32(pos+k*4,v);});box.forEach((v,k)=>{new DataView(c.memory.buffer).setFloat32(cs+k*4,v,true);m.f32(size+k*4,v);});items=[];splits=[];const expected=m.call(mode===0?0x44ae80:mode===1?0x44a330:0x44b1f0,{ecx:native,args:mode===0?[pos,bits(radius),reward,honor?1:0]:mode===1?[pos,size,bits(angle),reward,honor?1:0]:[reward,honor?1:0]})|0,actual=c.curve_cancel_apply(f,mode,cp,radius,cs,angle,reward,honor?1:0,rate);assert.ok(actual>=0,string(c,c.curve_cancel_error(f)));if(mode===0)assert.equal(actual,expected,label+' count');same(c.curve_cancel_field(f,0),native+12,4,label+' flags');same(c.curve_cancel_field(f,3),native+16,4,label+' state');same(c.curve_cancel_field(f,4),slots,4,label+' rewards');same(c.curve_cancel_field(f,5),0x4e9a48,8,label+' game RNG');same(c.curve_cancel_field(f,6),0x4e9a40,8,label+' visual RNG');same(c.curve_cancel_field(f,8),tracking+0x1c,4096,label+' tracking');same(c.curve_cancel_field(f,9),tracking+0x18,4,label+' cursor');same(c.curve_motion_timer(motion,0),native+0x40,20,label+' path timer');assert.equal(c.curve_motion_count(motion),m.u32(native+0x5f4),label+' point count');assert.deepEqual(Array.from(new Uint32Array(c.memory.buffer,c.curve_cancel_events(f),c.curve_cancel_event_count(f))),items,label+' item requests');assert.deepEqual(Array.from(new Float32Array(c.memory.buffer,c.curve_cancel_splits(f),c.curve_cancel_split_count(f)*2)),splits,label+' split time/count');
 for(let j=0;j<c.curve_motion_count(motion);j++){const data=Buffer.alloc(20);Buffer.from(m.bytes(samples+j*32,12)).copy(data);Buffer.from(m.bytes(samples+j*32+24,8)).copy(data,12);assert.deepEqual(Buffer.from(memory(c,c.curve_motion_sample(motion,j),20)),data,label+' surviving point '+j);points++;}
 for(let alt=0;alt<2;alt++){const list=nativeInstances(m,nm,alt);assert.equal(c.anm_manager_count(manager,alt),list.length,label+' queue');for(let i=0;i<list.length;i++){const np=list[i],h=m.u32(np+0x544);assert.equal(c.anm_manager_order(manager,alt,i),h,label+' order');compareAnm(c,m,c.anm_manager_find(manager,h),np,label+' effect '+i);effects++;}while(nativeInstances(m,nm,alt).length){const np=nativeInstances(m,nm,alt)[0],h=m.u32(np+0x544);assert.equal(c.anm_manager_destroy_tree(manager,c.anm_manager_find(manager,h)),1);m.call(0x488820,{ecx:nm,args:[np]});}}checks+=13;cases++;
 }finally{c.curve_cancel_delete(f);}}
 report('curve-cancellation',{passed:true,cases,points,effects,checks,originalFunctions:['0x44ae80','0x44a330','0x44b1f0','0x41e4b0','0x477e10'],scope:'Original circle/rectangle/full cancellation with real effect ANM queues and tracking, both RNG, reward item requests and exact surviving points. Preserves distinct circular buffer shifting without age change, rectangular age shift without point shifting, four-point threshold and inherited path split counts/times. Full cancellation creates effects without item rewards. Native rectangle/full void return registers are not asserted; future child lifecycles remain scene integration.'});
 }finally{c.anm_manager_delete(manager);c.release(cp);c.release(cs);c.release(origin);m.close();}
});
