import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {resolve} from 'node:path';import {core,oracle,memory,string,root,report,enableNativeMath} from './helpers.mjs';import {resourceLoader,nativePool,prepareBank,compareAnm} from './anm-oracle.mjs';
test('TH15 curved laser animations preserve native bindings, palette and full real ANM updates',async()=>{
 const c=await core(),m=await oracle(),manager=c.anm_manager_create(),nm=nativePool(m),loader=resourceLoader(m),native=m.allocate(0x1580),lasers=m.allocate(0x610),request=m.allocate(0x358),text=m.allocate(0x19270);enableNativeMath(m);m.u32(0x4e9ba0,lasers);m.u32(0x4e9a58,text);m.u32(0x4ca620,0x4e73e8);m.f32(0x4e73e8,1);m.replace(0x476400,'curve spawn audio boundary',()=>0,1);m.replace(0x4486c0,'curve contact checked separately',()=>0,1);let cases=0,frames=0,checks=0;
 const load=(name,id)=>{const bytes=readFileSync(resolve(root,'reference/assets',name)),p=c.allocate(bytes.length);memory(c,p,bytes.length).set(bytes);assert.equal(c.anm_manager_load(manager,id,p,bytes.length),1,string(c,c.anm_manager_error(manager)));c.release(p);return prepareBank(m,loader,name,bytes,nm,id);};
 try{m.u32(text+0x19258,load('ascii.anm',2));assert.equal(c.anm_manager_fallback(manager,2),1);m.u32(lasers+0x604,load('bullet.anm',9));const heap=m.heap;
 for(let type=0;type<44;type++)for(let color=0;color<16;color++){const f=c.laser_visual_create(manager,9),label=type+'/'+color;try{m.heap=heap;m.view(native,0x1580).fill(0);m.view(request,0x358).fill(0);m.call(0x441bb0,{ecx:native});m.f32(request,0);m.f32(request+4,100);m.f32(request+12,1.25);m.f32(request+16,16);m.f32(request+20,2);m.i32(request+24,type);m.i32(request+28,color);m.i32(request+32,32);m.i32(request+0x344,-1);m.f32(0x4e73e8,1);assert.equal(m.call(0x447aa0,{ecx:native,args:[request]}),0);assert.equal(c.laser_visual_initialize_curve(f,type,color),1,string(c,c.laser_visual_error(f)));for(let v=0;v<2;v++)compareAnm(c,m,c.laser_visual_vm(f,v),native+[0x92c,0xf34][v],label+' init '+v);
 const rate=[1,.5,.25,1.25][color%4];m.f32(0x4e73e8,rate);for(let frame=0;frame<32;frame++){assert.equal(m.call(0x448200,{ecx:native}),0);assert.equal(c.laser_visual_update_curve(f,rate),1,string(c,c.laser_visual_error(f)));for(let v=0;v<2;v++)compareAnm(c,m,c.laser_visual_vm(f,v),native+[0x92c,0xf34][v],label+'/'+frame+' VM '+v);frames++;checks+=2;}cases++;
 }finally{c.laser_visual_delete(f);}}
 report('curve-real-animations',{passed:true,cases,frames,checks,originalFunctions:['0x447aa0','0x448200','0x44b420','0x477e10'],scope:'Actual original curve initialization and unchanged complete update execute real bullet ANM for 44 styles and 16 colors. Special style 1, curve palette callback, body/head template binding, interrupt timing, semantic flags, UV, timer and later embedded animations. Audio/contact observed at boundaries; world and GPU remain unverified.'});
 }finally{c.anm_manager_delete(manager);m.close();}
});
