import test from 'node:test';import assert from 'node:assert/strict';
import {core,oracle,memory,string,report} from './helpers.mjs';
import {ins,call,resource} from './ecl-fixtures.mjs';
function spawn(op,name,values,refs=0,time=0){let b=call(name,values,refs);if(op===16){const start=20+b.readUInt32LE(16);b=Buffer.concat([b.subarray(0,start),b.subarray(start+4)]);b.writeUInt16LE(b.length,6);}b.writeUInt16LE(op,4);b.writeInt32LE(time);return b;}
test('TH15 ECL chapter snapshots preserve parallel script ordering, stacks and continuation',async()=>{
 const c=await core(),m=await oracle(),owner=m.allocate(0x1210),savedOwner=m.allocate(0x1210),native=owner+16,prNative=m.allocate(0x90),defs=m.allocate(4*8),rate=m.allocate(4),wrapper=m.allocate(32);m.u32(native+0x1018,owner);m.u32(owner+12,native);m.u32(owner+0x11f8,prNative);m.u32(prNative+8,4);m.u32(prNative+0x8c,defs);
 const wrapperCode=Buffer.from([0xf3,0x0f,0x10,0x0d,0,0,0,0,0xe8,0,0,0,0,0xc3]);wrapperCode.writeUInt32LE(rate,4);wrapperCode.writeInt32LE(0x48e690-wrapper-13,9);m.write(wrapper,wrapperCode);m.f32(rate,1);let frames=0,checks=0;const file=c.player_checkpoint_file_create(),fileInput=c.allocate(0x20000),nativeFile=m.allocate(0x20000),used=m.allocate(4);
 try{for(let sample=0;sample<32;sample++)for(const killAll of [0,1]){
  const scripts={alpha:Buffer.concat([ins(40,[16]),ins(42,[0],1),ins(42,[7]),ins(50),ins(43,[4],1),spawn(16,'beta',[['i','i',17],['i','i',9]]),ins(10,[],0,4)]),beta:Buffer.concat([ins(40,[8]),ins(42,[0],1),ins(42,[2]),ins(54),ins(43,[4],1),ins(10,[],0,3)]),gamma:Buffer.concat([ins(40,[8]),ins(42,[sample+17]),ins(43,[0],1),ins(91,[0,0,9,2,0x3f800000,0x40e00000],2),ins(10,[],0,6)]),main:Buffer.concat([ins(40,[16]),spawn(16,'alpha',[['i','i',7],['i','i',sample+3]]),spawn(15,'gamma',[]),ins(20,[7,6]),ins(18,[7]),ins(19,[7]),ins(killAll?21:17,killAll?[]:[-1],0,2),ins(10,[],0,10)])};
  const {bytes,names}=resource(scripts),pr=c.program_create(),p=c.allocate(bytes.length),nr=m.allocate(bytes.length),name=c.allocate(5);memory(c,p,bytes.length).set(bytes);memory(c,name,5).set(Buffer.from('main\0'));assert.equal(c.program_attach(pr,p,bytes.length),0);m.write(nr,bytes);names.forEach((name,i)=>{const text=m.allocate(name.length+1);m.write(text,Buffer.from(name+'\0'));m.u32(defs+i*8,text);m.u32(defs+i*8+4,nr+bytes.readUInt32LE(36+i*4));});
  m.view(native,0x11e8).fill(0);m.u32(native+0x1018,owner);m.u32(owner+12,native);m.u32(native+4,3);m.u32(native+8,0);m.view(native+0x1020,1)[0]=255;m.u32(owner+0x11fc,native);m.u32(owner+0x1200,0);m.u32(owner+0x1204,0);m.u32(owner+0x1208,0);
  const threads=c.ecl_threads_create(pr),saved=c.ecl_snapshot_create();assert.equal(c.ecl_threads_start(threads,name,255),1);
  for(let frame=0;frame<16;frame++){
   if(frame===1||frame===3){
    c.ecl_snapshot_capture(saved,threads);m.call(0x48f700,{ecx:owner,args:[savedOwner,prNative],limit:100000000});
    assert.equal(c.ecl_snapshot_file_write(file,saved),1);m.view(nativeFile,0x20000).fill(0);m.u32(used,0);m.call(0x48f820,{ecx:savedOwner,args:[nativeFile,nativeFile+0x1210,used],limit:100000000});const original=Buffer.from(m.bytes(nativeFile,0x1210+m.u32(used))),encoded=Buffer.from(memory(c,c.player_checkpoint_file_bytes(file),c.player_checkpoint_file_size(file)));assert.equal(encoded.length,original.length,'ECL file size '+sample+'/'+killAll+'/'+frame);const blocks=[16,...Array.from({length:(original.length-0x1210)/0x11f8},(_,i)=>0x1210+i*0x11f8)];for(const at of blocks){for(const [off,n]of [[0,0x1018],[0x101c,0x1cc]])assert.deepEqual(encoded.subarray(at+off,at+off+n),original.subarray(at+off,at+off+n),'ECL file context '+sample+'/'+killAll+'/'+frame+'/'+at.toString(16)+'/'+off.toString(16));}memory(c,fileInput,original.length).set(original);assert.equal(c.ecl_snapshot_file_read(file,saved,fileInput,original.length-1,pr),0);assert.equal(c.ecl_snapshot_file_read(file,saved,fileInput,original.length,pr),1);assert.equal(c.player_checkpoint_file_consumed(file),original.length);m.u32(used,0);m.call(0x48f980,{ecx:savedOwner,args:[nativeFile,nativeFile+0x1210,used],limit:100000000});checks+=blocks.length*2+4;
    for(let k=0;k<2;k++){assert.equal(c.ecl_threads_step(threads,1),m.call(wrapper,{ecx:owner})|0);}
    assert.equal(c.ecl_snapshot_restore(threads,saved),1);m.call(0x48f700,{ecx:savedOwner,args:[owner,prNative],limit:100000000});
   }
   const expected=m.call(wrapper,{ecx:owner})|0,actual=c.ecl_threads_step(threads,1),label=JSON.stringify({sample,killAll,frame});assert.equal(actual,expected,label+' return');const contexts=[];for(let node=owner+0x11fc;node;node=m.u32(node+4))contexts.push(m.u32(node));assert.equal(c.ecl_threads_count(threads),contexts.length,label+' count');
   contexts.forEach((np,index)=>{const ctx=c.ecl_threads_at(threads,index);assert.equal(string(c,c.ecl_context_error(ctx)),'',label+' error');assert.deepEqual(Buffer.from(memory(c,c.ecl_context_state(ctx),12)),Buffer.from(m.bytes(np,12)),label+' cursor/time '+index);assert.equal(c.ecl_context_field(ctx,0),m.i32(np+0x100c),label+' stack cursor '+index);assert.equal(c.ecl_context_field(ctx,1),m.i32(np+0x1010),label+' local base '+index);assert.deepEqual(Buffer.from(memory(c,c.ecl_context_stack(ctx),4096)),Buffer.from(m.bytes(np+12,4096)),label+' stack '+index);assert.equal(c.ecl_thread_field(ctx,0),m.i32(np+0x1014),label+' identifier '+index);assert.equal(c.ecl_thread_field(ctx,1),m.i32(np+0x101c),label+' state '+index);assert.equal(c.ecl_thread_field(ctx,2)>>>0,m.u32(np+0x11e4),label+' flags '+index);checks+=7;});frames++;if(actual===-1)break;
  }c.ecl_snapshot_delete(saved);c.ecl_threads_delete(threads);c.program_delete(pr);c.release(name);c.release(p);
 }report('ecl-checkpoint',{passed:true,checks,frames,originalFunctions:['0x48e690','0x48ef50','0x48f010','0x48f040'],scope:'Native 48f820/48f980 owner/child file records, routine-index interpolation destinations, active interpolation, bounded stack import, 48f700 deep context clone, saved and live child ordering, independently retained stacks, restoration and further native execution after two intervening updates per capture. Script list ordering, lifecycle and context state. Rendering and enemy world updates remain unverified.'});
 }finally{c.player_checkpoint_file_delete(file);c.release(fileInput);m.close();}
});
