import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {resolve} from 'node:path';import {core,oracle,memory,string,root,report,enableNativeMath} from './helpers.mjs';import {resourceLoader,nativePool,prepareBank,nativeInstances,compareAnm} from './anm-oracle.mjs';
const hash=s=>{let h=2166136261;for(const b of Buffer.from(s,'latin1'))h=Math.imul(h^b,16777619)>>>0;return h|0;};
test('TH15 actual ending scene and shared scheduler preserve native animation trees through staff transition',async()=>{
 const c=await core(),m=await oracle();enableNativeMath(m);const loader=resourceLoader(m),base=m.heap,defaults=readFileSync(resolve(root,'artifacts/cpp/analysis/score/original-saved-state.bin'));let events=[],texts=[],pending=null,currentBase=0,readyBank=0,readyName='',totalFrames=0,checks=0,animationChecks=0,loads=0;
 const str=p=>{const b=m.bytes(p,1024);return Buffer.from(b.subarray(0,b.indexOf(0))).toString('latin1');};
 const msgRead=()=>{const name=str(m.reg('ECX')),data=readFileSync(resolve(root,'reference/assets',name)),p=m.allocate(data.length);m.write(p,data);currentBase=p;events.push(1,hash(name));return p;};
 m.replace(0x476360,'ending sound output',()=>{events.push(7,m.i32(m.reg('ESP')+4));return 0;},2);
 m.replace(0x4869c0,'ending measured font upload boundary',()=>{const sp=m.reg('ESP'),h=m.u32(m.u32(sp+8)+0x544),color=m.u32(sp+12),value=str(m.u32(sp+32));events.push(2,h,color|0,hash(value));texts.push(value);return 0;});
 m.replace(0x44d360,'ending music preload boundary',()=>{events.push(4,hash(str(m.u32(m.reg('ESP')+8))));return 0;},2);
 m.replace(0x44d3e0,'ending music start/unlock boundary',()=>{const track=m.i32(m.reg('ESP')+8);events.push(5,track);m.view(m.u32(0x4e9bc8)+0x3374e+track,1)[0]=1;return 0;},2);
 m.replace(0x476f10,'ending fade output',()=>{const sp=m.reg('ESP');assert.equal(m.i32(sp+4),5);events.push(6,m.i32(sp+8));return 0;},3);
 m.replace(0x4751f0,'ending screen shake output',()=>{events.push(8,m.reg('ECX')|0,m.reg('EDX')|0);return 0;},4);
 m.replace(0x403fb0,'ending background resource request boundary',()=>{const p=m.u32(m.reg('ESP')+8),bank=m.i32(p+0xec)+20,name=str(m.u32(p+0x70));pending={bank,name};events.push(3,bank,hash(name));return 0;},2);
 m.replace(0x485f70,'ending prepared ANM transfer boundary',()=>{const sp=m.reg('ESP');assert.equal(m.i32(sp+4),readyBank);assert.equal(str(m.u32(sp+8)),readyName);return m.u32(m.u32(0x503c18)+0x187f4d8+readyBank*4);},2);
 const originalAnmReader=m.importMap.get((0x402db0+5+Buffer.from(m.bytes(0x402db0,5)).readInt32LE(1))>>>0).handler;
 const routes=[];
 try{for(const [character,continues,mode,seen]of[[0,0,0,0],[3,1,0,1],[1,0,0x100,1],[2,1,0,0]]){m.heap=base;m.replace(0x402db0,'ANM resource loader',originalAnmReader,1);m.view(m.heap,0x1caf980).fill(0);const a=c.anm_manager_create(),native=nativePool(m),owner=m.allocate(0x24),ascii=m.allocate(0x19270),record=m.allocate(0x33b54),scheduler=m.allocate(0x58);m.view(owner,0x24).fill(0);m.view(ascii,0x19270).fill(0);m.u32(0x4e9a58,ascii);m.u32(0x4e9a7c,owner);m.u32(0x4e9bc8,record);m.u32(0x4e9a54,scheduler);m.view(0x503d78,16).fill(0);m.u32(0x4e9a40,0);m.u32(0x4e9a44,0);m.u32(0x4ca620,0x4e73e8);m.f32(0x4e73e8,1);m.u32(0x4e7f08,0);m.call(0x401310,{ecx:scheduler});const blocks=Buffer.from(defaults);blocks.fill(seen,5*0xa4a0+0x16,5*0xa4a0+0x1f);m.write(record+8,blocks);m.i32(0x4e7404,character);m.i32(0x4e7408,0);m.i32(0x4e7410,2);m.i32(0x4e742c,continues);m.u32(0x4e7794,mode);
 const load=(name,id)=>{const bytes=readFileSync(resolve(root,'reference/assets',name)),p=c.allocate(bytes.length);memory(c,p,bytes.length).set(bytes);assert.equal(c.anm_manager_load(a,id,p,bytes.length),1,string(c,c.anm_manager_error(a)));c.release(p);return prepareBank(m,loader,name,bytes,native,id);};load('ascii.anm',5);m.u32(ascii+0x19258,m.u32(native+0x187f4d8+5*4));assert.equal(c.anm_manager_fallback(a,5),1);load('text.anm',0);m.u32(0x4e7f00,m.u32(native+0x187f4d8));const textureTable=m.u32(m.u32(m.u32(loader.bank+0x124)));m.u32(textureTable+8,m.registerImport({dll:'fixture',name:'texture COM release boundary',argc:1,handler:()=>0}));
 // Actual original ANM callback wrappers on the actual original scheduler.
 for(const[callback,priority]of[[0x487b40,9],[0x487b10,34]]){const node=m.allocate(0x28);m.view(node,0x28).fill(0);m.u32(node+4,2);m.u32(node+8,callback);m.u32(node+0x14,node);m.u32(node+0x24,native);m.call(0x401390,{args:[node,priority]});}
 const f=c.ending_scene_create(a);for(const name of['e01.msg','e02.msg','e03.msg','e04.msg','e05.msg','e06.msg','e07.msg','e08.msg','staff1.msg','staff2.msg','staff3.msg','staff4.msg','staff5.msg','staff6.msg']){const bytes=readFileSync(resolve(root,'reference/assets',name)),p=c.allocate(bytes.length),n=c.allocate(32);memory(c,p,bytes.length).set(bytes);memory(c,n,name.length+1).set(Buffer.from(name+'\0'));c.ending_scene_message(f,n,p,bytes.length);c.release(n);c.release(p);}c.ending_scene_seen(f,seen,seen);pending=null;m.replace(0x402db0,'ending message assets',msgRead,1);events=[];texts=[];
 try{assert.equal(m.call(0x423310,{ecx:owner}),0);assert.equal(c.ending_scene_initialize(f,character,2,continues,mode),1,string(c,c.ending_scene_error(f)));const vmState=m.u32(owner+0x14);const compare=label=>{assert.deepEqual(Array.from({length:4},(_,i)=>c.ending_scene_field(f,i)),[m.u32(vmState+0x54)-currentBase,m.u32(vmState+0x74),m.i32(vmState+0x78),m.i32(vmState+0x7c)],label+' control');for(const[kind,offset]of[[0,4],[1,0x18],[2,0x2c]])assert.deepEqual(Buffer.from(memory(c,c.ending_scene_timer(f,kind),20)),Buffer.from(m.bytes(vmState+offset,20)),label+' timer '+kind);for(const[kind,offset,n]of[[0,0x40,5],[1,0x90,16]])assert.deepEqual(Buffer.from(memory(c,c.ending_scene_handles(f,kind),n*4)),Buffer.from(m.bytes(vmState+offset,n*4)),label+' handles '+kind);assert.equal(c.ending_scene_field(f,4),m.i32(owner+0x20));assert.equal(c.ending_scene_field(f,6),m.i32(owner+0x1c));assert.deepEqual(Array.from(new Int32Array(c.memory.buffer,c.ending_scene_events(f),c.ending_scene_event_count(f))),events,label+' outputs');assert.equal(c.ending_scene_text_count(f),texts.length);for(let i=0;i<texts.length;i++){const p=c.ending_scene_text_bytes(f,i),b=memory(c,p,1024);assert.deepEqual(Buffer.from(b.subarray(0,b.indexOf(0))),Buffer.from(texts[i],'latin1'));}for(let alt=0;alt<2;alt++){const list=nativeInstances(m,native,alt);assert.equal(c.anm_manager_count(a,alt),list.length,label+' animation count '+alt);for(let i=0;i<list.length;i++){const h=m.u32(list[i]+0x544),vm=c.anm_manager_find(a,h);assert.equal(c.anm_manager_order(a,alt,i),h,label+' animation order');assert.ok(vm);compareAnm(c,m,vm,list[i],label+' animation '+h);assert.equal(c.anm_vm_pending_interrupt(vm),m.i32(list[i]+0x49c));assert.deepEqual(Buffer.from(memory(c,c.anm_vm_translation(vm),12)),Buffer.from(m.bytes(list[i]+0x5ec,12)));animationChecks++;}}assert.deepEqual(Buffer.from(memory(c,c.ending_scene_music(f),20)),Buffer.from(m.bytes(record+0x3374e,20)));checks+=10;};compare('initial '+character);let frames=0;
 for(;frames<15000;frames++){if(pending){const {bank,name}=pending;assert.equal(c.ending_scene_pending_bank(f),bank);assert.equal(string(c,c.ending_scene_pending_name(f)),name);pending=null;readyBank=bank;readyName=name;m.replace(0x402db0,'ANM resource loader',originalAnmReader,1);const bytes=readFileSync(resolve(root,'reference/assets',name));prepareBank(m,loader,name,bytes,native,bank);m.replace(0x402db0,'ending message assets',msgRead,1);m.call(0x424540);const p=c.allocate(bytes.length);memory(c,p,bytes.length).set(bytes);assert.equal(c.ending_scene_ready(f,p,bytes.length),1,string(c,c.ending_scene_error(f)));c.release(p);loads++;}
 const held=frames%37<29?0x200:1,pressed=frames%47===0?1:0,holdAge=frames%40,system=frames%2?0x2000:0;m.u32(0x4e6d10,held);m.u32(0x4e6d1c,pressed);m.u32(0x4e6e24,holdAge);m.u32(0x4e7f08,system);m.i32(0x4e7ecc,-1);events=[];texts=[];m.call(0x4014f0,{ecx:scheduler});assert.equal(c.ending_scene_step(f,held,pressed,holdAge,1,system),1,string(c,c.ending_scene_error(f)));compare(character+'/'+frames);assert.equal(c.ending_scene_field(f,5),m.i32(0x4e7ecc));totalFrames++;if(m.i32(0x4e7ecc)>=0)break;}
 assert.ok(frames<15000);routes.push({character,continues,mode,seen,frames:frames+1});
 }finally{c.ending_scene_delete(f);c.anm_manager_delete(a);}
 }
 report('ending-scene',{passed:true,routes,totalFrames,checks,animationChecks,loads,originalFunctions:['0x423310','0x4237c0','0x423b80','0x4238d0','0x424540','0x4014f0','0x487b10','0x487b40'],scope:'Actual original ending scene constructor, real ANM templates/trees, native frame scheduler including restarts, CP932 text requests, 4 characters/good-bad/Point/seen paths, staff change and resource completions against production EndingScene. File-worker transfer, GPU allocation, text raster and physical audio remain explicit platform boundaries. Browser whole ending composition remains pending.'});
 }finally{m.close();}
});
