import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {resolve} from 'node:path';import {core,oracle,memory,string,root,report} from './helpers.mjs';
const hash=s=>{let h=2166136261;for(const x of Buffer.from(s,'latin1'))h=Math.imul(h^x,16777619)>>>0;return h|0;};
const filename=run=>(run.mode&0x300)?'staff1.msg':run.continues?'staff2.msg':run.difficulty===1?'staff4.msg':run.difficulty===2?'staff5.msg':run.difficulty===3?'staff6.msg':'staff3.msg';
test('TH15 original ending frame callback matches whole-interpreter timing, return actions and skip restarts',async()=>{
 const c=await core(),m=await oracle(),base=m.heap,owner=m.allocate(0x24),state=m.allocate(0xf0),textbank=m.allocate(0x13c);m.u32(0x4e9a7c,owner);m.u32(owner+0x14,state);m.u32(0x4e7f00,textbank);m.u32(0x4ca620,0x4e73e8);m.view(0x503d78,16).fill(0);let next=100,events=[],texts=[],pending=null,currentBase=0,loading=0,totalFrames=0,checks=0,textChecks=0;const fakeVms=new Map(),bankIds=new Map();for(let i=0;i<4;i++){const p=m.allocate(0x13c);m.u32(p,20+i);bankIds.set(p,20+i);}const permanentHeap=m.heap;
 const str=p=>{const b=m.bytes(p,1024),n=b.indexOf(0);return Buffer.from(b.subarray(0,n<0?b.length:n)).toString('latin1');};
 const submit=()=>{const h=next++,vm=m.allocate(0x608);m.view(vm,0x608).fill(0);m.u32(vm+0x544,h);fakeVms.set(h,vm);return {h,vm};};
 m.replace(0x408f00,'initial ending text animation service',()=>{const sp=m.reg('ESP'),out=m.u32(sp+4),script=m.i32(sp+8),{h}=submit();m.u32(out,h);events.push(1,script,h);return out;},4);
 m.replace(0x488510,'ending animation lookup service',()=>fakeVms.get(m.u32(m.reg('ESP')+4))||0,1);
 m.replace(0x4869c0,'ending text raster service',()=>{const sp=m.reg('ESP'),vm=m.u32(sp+8),h=m.u32(vm+0x544),color=m.u32(sp+12),value=str(m.u32(sp+32));assert.deepEqual(m.readWords(sp+16,4),[0,0,0,0]);events.push(2,h,color|0,hash(value));texts.push(value);return 0;});
 m.replace(0x488620,'ending animation interrupt service',()=>{const sp=m.reg('ESP');events.push(3,m.u32(sp+4),m.i32(sp+8));return 0;},2);
 m.replace(0x488d30,'ending animation retirement service',()=>{const p=m.reg('ECX');events.push(4,m.u32(p));m.u32(p,0);return 0;});
 m.replace(0x424670,'ending loading overlay service',()=>{events.push(7);return 0;});
 m.replace(0x4866c0,'ending bank release service',()=>0,1);
 m.replace(0x403fb0,'ending asynchronous file service',()=>{const bank=m.i32(state+0xec),name=str(m.u32(state+0x70));pending={bank,name};events.push(5,bank+20,hash(name));return 0;},2);
 let createVm=0,createBank=0,createScript=0;
 m.replace(0x489460,'ending sprite allocation service',()=>{createVm=m.allocate(0x608);m.view(createVm,0x608).fill(0);return createVm;});
 m.replace(0x40b880,'ending sprite binding service',()=>{createBank=bankIds.get(m.reg('ECX'));createScript=m.i32(m.reg('ESP')+8);assert.notEqual(createBank,undefined);return 0;},2);
 m.replace(0x477e10,'initial sprite ANM tick service',()=>0);
 m.replace(0x487bd0,'ending sprite registration service',()=>{const sp=m.reg('ESP'),out=m.u32(sp+4),vm=m.u32(sp+8),h=next++;assert.equal(vm,createVm);fakeVms.set(h,vm);m.u32(vm+0x544,h);m.u32(out,h);events.push(6,createBank,createScript,h);return out;},2);
 m.replace(0x44d360,'ending music preparation service',()=>{events.push(10,hash(str(m.u32(m.reg('ESP')+8))));return 0;},2);
 m.replace(0x44d3e0,'ending music start service',()=>{events.push(11,m.i32(m.reg('ESP')+8));return 0;},2);
 m.replace(0x476f10,'ending music command service',()=>{const sp=m.reg('ESP');assert.equal(m.i32(sp+4),5);events.push(12,m.i32(sp+8));return 0;},3);
 m.replace(0x476360,'ending page sound service',()=>{events.push(13,m.i32(m.reg('ESP')+4));return 0;},2);
 m.replace(0x4751f0,'ending screen shake service',()=>{assert.deepEqual(m.readWords(m.reg('ESP')+4,4),[0,0,0,81]);events.push(14,m.reg('ECX')|0,m.reg('EDX')|0);return 0;},4);
 m.replace(0x4231f0,'ending staff file service',()=>{const name=str(m.u32(m.reg('ESP')+4));events.push(9,hash(name));const data=readFileSync(resolve(root,'reference/assets',name)),p=m.allocate(data.length);m.write(p,data);currentBase=p;return p;},1);
 const routes=[];
 try{const scenarios=[];for(let index=1;index<=8;index++)scenarios.push({name:'e'+String(index).padStart(2,'0')+'.msg',difficulty:index%4,continues:index%2,mode:index%3===0?0x100:0,first:index%4,rate:1});for(const [rate,first]of[[.5,0],[.875,1],[1.5,3],[2,2]])scenarios.push({name:'e01.msg',difficulty:2,continues:0,mode:0,first,rate});for(let index=1;index<=6;index++)scenarios.push({name:'staff'+index+'.msg',difficulty:1,continues:0,mode:0,first:0,rate:[1,.5,1.25][index%3]});
 for(const run of scenarios){m.heap=permanentHeap;next=100;fakeVms.clear();m.view(state,0xf0).fill(0);m.view(owner,0x24).fill(0);m.u32(owner+0x14,state);m.u32(owner+0x1c,run.first);m.u32(0x4e7794,run.mode);m.i32(0x4e742c,run.continues);m.i32(0x4e7410,run.difficulty);m.f32(0x4e73e8,run.rate);const data=readFileSync(resolve(root,'reference/assets',run.name)),p=m.allocate(data.length);m.write(p,data);currentBase=p;const f=c.ending_script_create(),frame=c.ending_frame_create(f),cp=c.allocate(data.length),staff=readFileSync(resolve(root,'reference/assets',filename(run))),sp=c.allocate(staff.length);memory(c,cp,data.length).set(data);memory(c,sp,staff.length).set(staff);c.ending_script_staff(f,sp,staff.length);c.ending_script_configure(f,run.difficulty,run.continues,run.mode,run.first);pending=null;events=[];texts=[];
 try{m.call(0x4238d0,{ecx:state,args:[p+data.readUInt32LE(4)]});assert.equal(c.ending_script_initialize(f,cp,data.length),1,string(c,c.ending_script_error(f)));assert.deepEqual(Array.from(new Int32Array(c.memory.buffer,c.ending_script_events(f),c.ending_script_event_count(f))),events,'initialize '+run.name);
 const compare=label=>{const fields=Array.from(new Int32Array(c.memory.buffer,c.ending_script_fields(f),29));const expected=[m.u32(state+0x54)-currentBase,m.u32(state+0x74),m.i32(state+0x78),m.i32(state+0x7c),...Array.from({length:5},(_,i)=>m.i32(state+0x40+i*4)),...Array.from({length:4},(_,i)=>bankIds.get(m.u32(state+0x80+i*4))??-1),...Array.from({length:16},(_,i)=>m.i32(state+0x90+i*4))];assert.deepEqual(fields,expected,label+' ending fields');for(const[kind,offset]of[[0,4],[1,0x18],[2,0x2c]])assert.deepEqual(Buffer.from(memory(c,c.ending_script_timer(f,kind),20)),Buffer.from(m.bytes(state+offset,20)),label+' timer '+kind);assert.deepEqual(Array.from(new Int32Array(c.memory.buffer,c.ending_script_events(f),c.ending_script_event_count(f))),events,label+' services');assert.equal(c.ending_script_text_count(f),texts.length,label+' text count');for(let i=0;i<texts.length;i++){const at=c.ending_script_text_bytes(f,i),raw=memory(c,at,1024),n=raw.indexOf(0);assert.deepEqual(Buffer.from(raw.subarray(0,n)),Buffer.from(texts[i],'latin1'),label+' text '+i);textChecks++;}checks+=5;};compare(run.name+'/initialize');let frames=0;
 for(;frames<60000;frames++){if(pending){const {bank}=pending;pending=null;const ptr=[...bankIds].find(v=>v[1]===bank+20)[0];m.u32(state+0x80+bank*4,ptr);m.u32(state+0x74,m.u32(state+0x74)&~4);assert.equal(c.ending_script_ready(f,bank),1);assert.deepEqual(Array.from(new Int32Array(c.memory.buffer,c.ending_script_events(f),c.ending_script_event_count(f))),[8]);loading++;}
 const held=frames%43<31?0x200:1,pressed=frames%53===0?1:0,held_frames=frames%40;m.u32(0x4e6d10,held);m.u32(0x4e6d1c,pressed);m.u32(0x4e6e24,held_frames);m.u32(0x503c10,7);events=[];texts=[];const system=frames%2?0x2000:0;m.u32(0x4e7f08,system);m.i32(0x4e7ecc,-1);const result=m.call(0x4237c0,{ecx:owner})|0; assert.equal(c.ending_frame_update(frame,held,pressed,held_frames,run.rate,system),result,string(c,c.ending_frame_error(frame))+' '+run.name+'/'+frames);assert.equal(c.ending_frame_fields(frame,0),m.i32(owner+0x20),'ending frame clock');assert.equal(c.ending_frame_fields(frame,1),m.i32(0x4e7ecc),'ending destination');const nativeEvents=events;const actual=Array.from(new Int32Array(c.memory.buffer,c.ending_script_events(f),c.ending_script_event_count(f))); // reset_caption_state is a named memory write boundary
 let ai=0,normalized=[],resets=0;const widths={1:3,2:4,3:3,4:2,5:3,6:4,7:1,8:1,9:2,10:2,11:2,12:2,13:2,14:3,15:1};while(ai<actual.length){const code=actual[ai],n=widths[code];assert.ok(n,'Unknown fixture event '+code);if(code!==15)normalized.push(...actual.slice(ai,ai+n));else resets++;ai+=n;}assert.deepEqual(normalized,nativeEvents,run.name+'/'+frames+' platform sequence');assert.equal(resets>0,m.u32(0x503c10)===0,'caption reset '+run.name+'/'+frames);events=actual;compare(run.name+'/'+frames);assert.equal(c.ending_script_finished(f),m.i32(0x4e7ecc)>=0?1:0);totalFrames++;if(m.i32(0x4e7ecc)>=0)break;
 }
 assert.ok(frames<60000,'Ending completes '+run.name);routes.push({...run,frames:frames+1});
 }finally{c.ending_frame_delete(frame);c.ending_script_delete(f);c.release(cp);c.release(sp);}
 }
 report('ending-frame',{passed:true,routes,totalFrames,checks,textChecks,loadingRequests:loading,originalFunctions:['0x4237c0','0x4238d0','0x423b80','0x439c60','0x409040','0x4126c0'],scope:'Actual original ending frame callback plus eight ending and six staff scripts, original text decoder, exact age/clock/wait and frame count, native return actions including restart=6, ending title destinations and all platform request sequences across held/pressed/unseen gates and multiple rates. Font raster, ANM execution, async file worker and hardware audio are explicit isolated services; final full-scene composition remains pending.'});
 }finally{m.close();}
});
