import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {resolve} from 'node:path';import {core,oracle,memory,string,root,report} from './helpers.mjs';
test('TH15 ending constructor branch and persisted first-view flags match original records exactly',async()=>{
 const c=await core(),m=await oracle(),record=m.allocate(0x33b54),owner=m.allocate(0x24),data=c.allocate(0x33b4c),first=c.allocate(4),defaults=readFileSync(resolve(root,'artifacts/cpp/analysis/score/original-saved-state.bin'));let loaded='',cases=0,checks=0;const base=m.heap;
 const str=p=>{const b=m.bytes(p,256);return Buffer.from(b.subarray(0,b.indexOf(0))).toString('latin1');};
 m.replace(0x4017e0,'ending callback allocation boundary',()=>{const p=m.allocate(0x28);m.view(p,0x28).fill(0);return p;},1);m.replace(0x401390,'ending update registration boundary',()=>0,2);m.replace(0x401440,'ending draw registration boundary',()=>0,2);m.replace(0x424670,'ending loading presentation boundary',()=>0);
 m.replace(0x402db0,'ending message file boundary',()=>{loaded=str(m.reg('ECX'));return m.allocate(16);},1);m.replace(0x4238d0,'ending script construction boundary (separately proven)',()=>{const p=m.reg('ECX');m.view(p,0xf0).fill(0);return p;},1);
 try{for(let sample=0;sample<1024;sample++){m.heap=base;const f=c.records_create();try{const bytes=Buffer.from(defaults),character=sample%4,subcharacter=0,difficulty=(sample>>2)%5,mode=[0,0x100,0x200,0x300][(sample>>5)%4],continues=(sample>>7)%3;for(let i=0;i<16;i++)bytes[5*0xa4a0+0x16+i]=sample%3===0?0:(sample*17+i*31)&255;memory(c,data,bytes.length).set(bytes);assert.equal(c.records_import_blocks(f,data),1);m.write(record+8,bytes);m.view(owner,0x24).fill(0);m.u32(0x4e9bc8,record);m.i32(0x4e7404,character);m.i32(0x4e7408,subcharacter);m.i32(0x4e7410,difficulty);m.u32(0x4e7794,mode);m.i32(0x4e742c,continues);m.call(0x423310,{ecx:owner});const index=c.ending_index(character,subcharacter,mode,continues);assert.equal(index,m.i32(owner+0x18),'ending branch '+sample);assert.equal(loaded,'e'+String(index+1).padStart(2,'0')+'.msg');new DataView(c.memory.buffer).setUint32(first,0,true);assert.equal(c.records_begin_ending(f,index,difficulty,first),1,string(c,c.records_error(f)));assert.equal(new DataView(c.memory.buffer).getUint32(first,true),m.u32(owner+0x1c),'first-view flags '+sample);const out=Buffer.concat([Buffer.from(memory(c,c.records_blocks(f,0),5*0xa4a0)),Buffer.from(memory(c,c.records_blocks(f,1),0x42c))]);assert.deepEqual(out,Buffer.from(m.bytes(record+8,0x33b4c)),'all stored bytes '+sample);assert.equal(c.records_save(f),1);const reloaded=c.records_create();try{assert.equal(c.records_open(reloaded,c.records_data(f),c.records_size(f)),1);assert.deepEqual(Buffer.from(memory(c,c.records_blocks(reloaded,1),0x42c)),Buffer.from(memory(c,c.records_blocks(f,1),0x42c)),'saved ending flags '+sample);}finally{c.records_delete(reloaded);}cases++;checks+=6;}finally{c.records_delete(f);}}
 report('ending-selection',{passed:true,cases,checks,originalFunctions:['0x423310'],scope:'Real original ending constructor chooses eight branches from character/mode/continues; first-ending and first-staff flags, all rank bits and complete persisted score bytes match named records. Full score encode/decode round trip preserves the changes. Animation/script construction is an explicit boundary independently checked by ending-script and ANM tests.'});
 }finally{c.release(data);c.release(first);m.close();}
});
