import test from 'node:test';import assert from 'node:assert/strict';import {core,oracle,memory,report,enableNativeMath} from './helpers.mjs';
test('TH15 animated enemy damage regions preserve original sequential damage queries, pool deduplication and score',async()=>{
 const c=await core(),m=await oracle(),f=c.enemy_combat_create(),enemy=c.enemy_variables_create(),vm=c.anm_vm_create(),pool=c.enemy_combat_damage(f),data=c.damage_sources_data(pool),timer=c.enemy_combat_timer(f),player=m.allocate(0x2c100),bomb=m.allocate(64),sht=m.allocate(0xe0),vt=m.allocate(16),bombCallback=m.allocate(16),entity=m.allocate(0x4530),world=m.allocate(0x5780),animation=m.allocate(0x608),out=c.allocate(4);enableNativeMath(m);m.u32(0x4e9bb8,player);m.u32(0x4e9a68,bomb);m.u32(player+0x2c008,sht);m.u32(bomb,vt);m.u32(vt+12,bombCallback);m.u32(bomb+0x24,1);m.u32(entity+0x44b8,world);let bombValue=0,nativeBombCalls=0,available=true,cases=0,queries=0,checks=0;
 m.replace(bombCallback,'bomb damage service boundary',()=>{nativeBombCalls++;return bombValue;},2);m.replace(0x488510,'lookup only animation for multi-region damage fixture',()=>available?animation:0,1);
 const dv=()=>new DataView(c.memory.buffer),set=(cp,np,v,float=false)=>{if(float){dv().setFloat32(cp,v,true);m.f32(np,v);}else{dv().setInt32(cp,v|0,true);m.i32(np,v);}};
 try{for(let sample=0;sample<4096;sample++){
  const native=player+0xcd8c;memory(c,data,256*148).fill(0);m.view(native,256*148).fill(0);const max=sample%127+1;set(c.damage_sources_maximum(pool),sht+0x28,max);set(c.damage_sources_score(pool),0x4e740c,sample*11);const changed=sample%17!==0;set(timer,player+0x62c,0);set(timer+4,player+0x630,changed?1:0);
  const point=[Math.fround((sample%19-9)*13.375),Math.fround((sample%23-11)*7.625),Math.fround(sample%5*.125)],scale=[Math.fround((sample%9-2)*.125),Math.fround((sample%13-3)*.25)],angle=Math.fround((sample%15-7)*.34906584),target=sample%13?sample%7+1:0;for(let i=0;i<3;i++)set(c.enemy_fixture_field(enemy,0,0,0)+i*4,entity+0x44+i*4,point[i],true);for(let i=0;i<2;i++)set(c.anm_vm_visual(vm)+40+i*4,animation+0x5c+i*4,scale[i],true);set(c.anm_vm_variables(vm)+84,animation+0x4c,angle,true);set(c.enemy_fixture_field(enemy,0,9,6),world+0x5740,target);set(c.enemy_attribute_field(enemy,4),entity+0x128,37);
  for(let i=0;i<18;i++){const o=i*148,write=(off,v,float=false)=>set(data+o+off,native+o+off,v,float);write(0,1|((sample+i)%2?2:0)|((sample+i)%3?0:4));write(4,(sample%9+i)*2.5,true);write(12,Math.fround((sample%13-6)*.2617994),true);write(20,((sample+i)%31)*2.5,true);write(24,((sample+i)%29)*3.75,true);write(28,Math.fround(point[0]+(i-8)*7.375),true);write(32,Math.fround(point[1]+(i-4)*7.625),true);write(36,i*.125,true);write(96,8);write(100,9+(sample+i)%4);write(104,12,true);write(112,1);write(116,i-2);write(120,sample%3);write(124,(sample+i)%4?9999999:4);write(128,1+(sample+i)%3);write(132,sample%7?0:target);}
  bombValue=[0,7,-3,129][sample%4];nativeBombCalls=0;c.enemy_combat_configure(f,bombValue,1);available=sample%31!==0;const incoming=[0,1,-7,0x7fffffff,-2147483600,sample*337][sample%6];
  for(let iteration=0;iteration<3;iteration++){const expected=m.call(0x431a50,{ecx:entity,edx:incoming})|0;assert.equal(c.enemy_combat_regions(f,enemy,available?vm:0,incoming,out),1);assert.equal(dv().getInt32(out,true),expected,sample+'/'+iteration+' damage');assert.deepEqual(Buffer.from(memory(c,data,256*148)),Buffer.from(m.bytes(native,256*148)),sample+'/'+iteration+' source pool');assert.equal(dv().getInt32(c.damage_sources_score(pool),true),m.i32(0x4e740c));assert.equal(c.enemy_combat_bomb_calls(f),nativeBombCalls);assert.equal(dv().getInt32(c.enemy_attribute_field(enemy,4),true),m.i32(entity+0x128));queries++;checks+=6;}cases++;
 }
 c.enemy_combat_configure(f,0,0);dv().setInt32(timer,0,true);dv().setInt32(timer+4,1,true);assert.equal(c.enemy_combat_regions(f,enemy,vm,5,out),0);c.enemy_combat_configure(f,0,0);dv().setInt32(timer+4,0,true);assert.equal(c.enemy_combat_regions(f,enemy,vm,5,out),1);assert.equal(c.enemy_combat_bomb_calls(f),0);
 report('enemy-animation-region-damage',{passed:true,cases,queries,checks,originalFunctions:['0x431a50','0x4594e0'],scope:'Original animated-region callback and full damage pool queries: scaled/rotated rectangle followed by offset circle, per-target deduplication, frame gate, repeated calls, score/limit/accumulated mutations, missing animation retirement, wrapped incoming damage and bomb-service calls. Shot-specific callbacks and original full-stage replay validation remain separate.'});
 }finally{c.release(out);c.anm_vm_delete(vm);c.enemy_variables_delete(enemy);c.enemy_combat_delete(f);m.close();}
});
