import test from 'node:test';import assert from 'node:assert/strict';import {core,oracle,memory,string,report,enableNativeMath} from './helpers.mjs';import {bits,ins} from './ecl-fixtures.mjs';
test('TH15 enemy cancellation ECL commands preserve original request order, rewards, protection and animation rotation',async()=>{
 const c=await core(),m=await oracle(),f=c.enemy_variables_create(),ctx=c.ecl_context_create(),owner=m.allocate(0x5780),entity=owner+0x120c,native=m.allocate(0x11e8),program=m.allocate(0x90),table=m.allocate(8),source=m.allocate(256),p=c.allocate(256),rate=m.allocate(4),wrapper=m.allocate(32),vm=m.allocate(0x608);enableNativeMath(m);c.enemy_context(f,ctx);c.enemy_visual_enable(f);m.u32(0x521e34,1);m.u32(owner,0x4cc2e8);m.u32(entity+0x44b8,owner);m.u32(owner+12,native);m.u32(native+0x1018,owner);m.u32(owner+0x11f8,program);m.u32(program+0x8c,table);m.u32(table+4,source);m.view(native+0x1020,1)[0]=255;let events=[],cases=0,checks=0;
 const code=Buffer.from([0xf3,0x0f,0x10,0x0d,0,0,0,0,0xe8,0,0,0,0,0xc3]);code.writeUInt32LE(rate,4);code.writeInt32LE(0x48ca80-wrapper-13,9);m.write(wrapper,code);m.f32(rate,1);const sp=()=>m.reg('ESP');
 const observe=(address,register,argc,handler)=>{const scalar=m.allocate(4);m.replace(address,'capture typed cancellation service',()=>handler(scalar),argc);const entry=Buffer.from(m.bytes(address,5)),stub=address+5+entry.readInt32LE(1),cave=m.allocate(32),jump=Buffer.from([0xf3,0x0f,0x11,0x05|(register<<3),0,0,0,0,0xe9,0,0,0,0]);jump.writeUInt32LE(scalar,4);jump.writeInt32LE(stub-cave-jump.length,9);m.write(cave,jump);const transfer=Buffer.alloc(5);transfer[0]=0xe9;transfer.writeInt32LE(cave-address-5,1);m.write(address,transfer);};
 observe(0x41e650,2,2,scalar=>{const q=m.u32(sp()+4);events.push(1,m.u32(q),m.u32(q+4),m.u32(q+8),m.u32(scalar),m.u32(sp()+8),0);return 0;});observe(0x441db0,2,3,scalar=>{const q=m.u32(sp()+4);events.push(2,m.u32(q),m.u32(q+4),m.u32(q+8),m.u32(scalar),m.u32(sp()+8),m.u32(sp()+12));return 0;});observe(0x41e850,3,3,scalar=>{const q=m.u32(sp()+4),size=m.u32(sp()+8);events.push(3,m.u32(q),m.u32(q+4),m.u32(q+8),m.u32(size),m.u32(size+4),m.u32(scalar),m.u32(sp()+12));return 0;});m.replace(0x488a20,'resolve first enemy ANM for rectangle rotation',()=>{assert.equal(m.u32(m.reg('ECX')),1);return vm;});
 try{for(const op of [615,616,712,901,902])for(let sample=0;sample<128;sample++){const pos=[Math.fround((sample%13-6)*17.25),Math.fround((sample%17-4)*21.5),Math.fround(sample%3*.125)],angle=Math.fround((sample%21-10)*.125);for(let k=0;k<3;k++){new DataView(c.memory.buffer).setFloat32(c.enemy_motion(f,0)+k*4,pos[k],true);m.f32(entity+0x44+k*4,pos[k]);}new DataView(c.memory.buffer).setUint32(c.enemy_attribute_field(f,4),1,true);m.u32(entity+0x124,1);new DataView(c.memory.buffer).setFloat32(c.anm_vm_variables(c.enemy_visual_vm(f,0))+84,angle,true);m.f32(vm+0x4c,angle);const args=op===712?[bits(sample*.625),bits(sample*.875)]:[bits(sample*.75)];const bytes=Buffer.concat([ins(op,args),ins(0,[],0,10000)]);memory(c,p,bytes.length).set(bytes);m.write(source+16,bytes);c.ecl_context_code(ctx,p,bytes.length,255,0);c.ecl_context_bind(ctx,p,0,0);for(let offset of [0,4,8,0x100c,0x1010])m.u32(native+offset,0);events=[];c.enemy_area_clear(f);const expected=m.call(wrapper,{ecx:native})|0,actual=c.ecl_context_step(ctx,1);assert.equal(actual,expected,op+'/'+sample+' '+string(c,c.ecl_context_error(ctx)));assert.deepEqual(Array.from(new Uint32Array(c.memory.buffer,c.enemy_area_events(f),c.enemy_area_event_count(f))),events,op+'/'+sample+' requests');assert.deepEqual(Buffer.from(memory(c,c.ecl_context_state(ctx),12)),Buffer.from(m.bytes(native,12)),op+'/'+sample+' script');cases++;checks+=3;}
 report('enemy-area-commands',{passed:true,cases,checks,opcodes:[615,616,712,901,902],originalFunctions:['0x4291e0','0x48ca80'],scope:'Actual ECL execution, world cancellation requests and order, original differing reward/protection gates, enemy coordinates and first ANM rotation. Area geometry, bullet animation and laser lifetimes have independent original comparisons. Target opcodes 901 and 902 explicitly jump to dispatch epilogue without state changes.'});
 }finally{c.release(p);c.ecl_context_delete(ctx);c.enemy_variables_delete(f);m.close();}
});
