import test from 'node:test';import assert from 'node:assert/strict';import {core,oracle,memory,string,report,enableNativeMath} from './helpers.mjs';import {bits,ins,resource} from './ecl-fixtures.mjs';
function spawn(name,x,y,life,time=0){const text=Buffer.from(name+'\0'),n=(text.length+3)&~3,b=Buffer.alloc(20+n+20);b.writeInt32LE(time);b.writeUInt16LE(300,4);b.writeUInt16LE(b.length,6);b[10]=255;b[11]=6;b.writeUInt32LE(n,16);text.copy(b,20);[bits(x),bits(y),life,100,0].forEach((v,i)=>b.writeInt32LE(v,20+n+i*4));return b;}
test('TH15 enemy manager preserves original initial updates, nested spawn traversal and deletion order',async()=>{
 const c=await core(),m=await oracle();enableNativeMath(m);m.u32(0x521e34,1);m.u32(0x4ca620,0x4e73e8);const{bytes,names}=resource({child:Buffer.concat([ins(40,[0]),spawn('leaf',7,13,31),ins(404,[bits(.25),bits(.5)]),ins(502,[12]),spawn('leaf',-13,17,71,17),ins(10,[],0,71)]),exitSoon:Buffer.concat([ins(40,[0]),ins(502,[0x2000000],0,11),ins(10,[],0,23)]),leaf:Buffer.concat([ins(40,[0]),ins(404,[bits(1.5),bits(1.25)]),ins(502,[12]),ins(10,[],0,37)]),main:Buffer.concat([ins(40,[0]),ins(400,[bits(-17.5),bits(64)]),ins(502,[12]),spawn('child',11,23,100),spawn('child',-23,41,151,19),spawn('exitSoon',-7,33,71,31),ins(10,[],0,83)])}),program=c.program_create(),p=c.allocate(bytes.length),np=m.allocate(bytes.length),nativeProgram=m.allocate(0x90),definitions=m.allocate(names.length*8),manager=m.allocate(0x200),request=m.allocate(84),cpReq=c.allocate(84),cppName=c.allocate(32),nativeNames={},owners=new Set();memory(c,p,bytes.length).set(bytes);m.write(np,bytes);assert.equal(c.program_attach(program,p,bytes.length),0);m.u32(nativeProgram+8,names.length);m.u32(nativeProgram+0x8c,definitions);names.forEach((text,i)=>{const ptr=m.allocate(text.length+1);m.write(ptr,Buffer.from(text+'\0'));nativeNames[text]=ptr;m.u32(definitions+i*8,ptr);m.u32(definitions+i*8+4,np+bytes.readUInt32LE(36+i*4));});m.u32(0x4e9a80,manager);m.replace(0x488510,'no animations in this manager integration sample',()=>0,1);m.replace(0x427a10,'damage integration boundary',()=>0);m.replace(0x428220,'distortion integration boundary',()=>0);m.replace(0x49039f,'original entity and thread allocation',()=>{const n=m.u32(m.reg('ESP')+4),out=m.allocate(n);if(n===0x574c)owners.add(out);return out;});let deleted=[];m.replace(0x4903f0,'capture original entity deletion',()=>{const ptr=m.u32(m.reg('ESP')+4);if(owners.has(ptr)){deleted.push(m.u32(ptr+0x5740));owners.delete(ptr);}return 0;});let checks=0,frames=0,cases=0;
 const spawnBoth=(fixture,name,position,rate)=>{const data=Buffer.alloc(84);data.writeFloatLE(position[0]);data.writeFloatLE(position[1],4);data.writeInt32LE(100,20);m.write(request,data);memory(c,cpReq,84).set(data);memory(c,cppName,name.length+1).set(Buffer.from(name+'\0'));m.f32(0x4e73e8,rate);assert.ok(m.call(0x426050,{ecx:manager,args:[nativeNames[name],request,0]}));assert.equal(c.enemy_manager_spawn(fixture,cppName,cpReq),1,string(c,c.enemy_manager_error(fixture)));};
 const compare=(fixture,label)=>{const active=[];for(let node=m.u32(manager+0x180);node;node=m.u32(node+4))active.push(m.u32(node));assert.equal(c.enemy_manager_count(fixture),active.length,label+' count');assert.equal(new DataView(c.memory.buffer).getInt32(c.enemy_manager_world_counts(fixture,0),true),m.i32(manager+0x18c),label+' active total');assert.equal(new DataView(c.memory.buffer).getUint32(c.enemy_manager_world_counts(fixture,1),true),m.u32(manager+0x94),label+' last ID');assert.equal(new DataView(c.memory.buffer).getUint32(c.enemy_manager_next_id(fixture),true),m.u32(manager+0x90),label+' next ID');assert.deepEqual(Buffer.from(memory(c,c.enemy_manager_timer(fixture),20)),Buffer.from(m.bytes(manager+0x98,20)),label+' manager time');assert.deepEqual(Buffer.from(memory(c,c.enemy_manager_destroyed(fixture),c.enemy_manager_destroyed_count(fixture)*4)),Buffer.from(Uint32Array.from(deleted).buffer),label+' destruction order');
  active.forEach((owner,index)=>{const state=c.enemy_manager_projection(fixture,index),entity=owner+0x120c;for(const[kind,at]of [[0,0x44],[1,0x88],[2,0xcc],[3,0]])assert.deepEqual(Buffer.from(memory(c,c.enemy_motion(state,kind),68)),Buffer.from(m.bytes(entity+at,68)),label+' motion '+index+'/'+at.toString(16));for(const[kind,at,n]of [[5,0x3f74,16],[9,0x2bc,20],[10,0x3ff8,20],[11,0x400c,20]])assert.deepEqual(Buffer.from(memory(c,c.enemy_attribute_field(state,kind),n)),Buffer.from(m.bytes(entity+at,n)),label+' life/time '+index);assert.equal(new DataView(c.memory.buffer).getUint32(c.enemy_fixture_field(state,0,9,2),true),m.u32(entity+0x4060),label+' flags '+index);assert.equal(new DataView(c.memory.buffer).getUint32(c.enemy_fixture_field(state,0,9,6),true),m.u32(owner+0x5740),label+' ID '+index);assert.equal(new DataView(c.memory.buffer).getUint32(c.enemy_fixture_field(state,0,9,7),true),m.u32(owner+0x5744),label+' parent '+index);const ctx=c.enemy_manager_context(fixture,index,0);assert.deepEqual(Buffer.from(memory(c,c.ecl_context_state(ctx),12)),Buffer.from(m.bytes(owner+0x10,12)),label+' script '+index);checks+=12;});checks+=6;
 };
 try{for(let sample=0;sample<64;sample++){
  const fixture=c.enemy_manager_create(program),id=sample%3===0?0xfffffffd:sample%3===1?1:737,rate=[.5,.995,1,1.25,1.5][sample%5];new DataView(c.memory.buffer).setUint32(c.enemy_manager_next_id(fixture),id,true);new DataView(c.memory.buffer).setFloat32(c.enemy_manager_rate(fixture),rate,true);m.view(manager,0x200).fill(0);m.u32(manager+0x17c,nativeProgram);m.u32(manager+0x8c,1000);m.u32(manager+0x90,id);m.call(0x409040,{ecx:manager+0x98,args:[0]});m.u32(0x4e73f8,0);m.u32(0x4e7410,0);deleted=[];spawnBoth(fixture,'main',[0,0],rate);compare(fixture,'initial '+sample);
  for(let frame=0;frame<320;frame++){
   if(frame===12)spawnBoth(fixture,'exitSoon',[17,79],rate);const native=[];for(let node=m.u32(manager+0x180);node;node=m.u32(node+4))native.push(m.u32(node));native.forEach((owner,index)=>{const amount=frame<29&&sample&1?[0,.25,.5,1][(index+frame%3)%4]:0;m.f32(owner+0x14f0,amount);new DataView(c.memory.buffer).setFloat32(c.enemy_manager_slowdown(fixture,index),amount,true);});m.f32(0x4e73e8,rate);assert.equal(m.call(0x426ad0,{ecx:manager}),1);assert.equal(c.enemy_manager_step(fixture,rate),1,string(c,c.enemy_manager_error(fixture)));compare(fixture,JSON.stringify({sample,frame}));frames++;
  }assert.equal(c.enemy_manager_count(fixture),0,'all scripts ended');c.enemy_manager_delete(fixture);cases++;
 }report('enemy-manager-integration',{passed:true,cases,frames,checks,originalFunctions:['0x426050','0x426c60','0x426ad0','0x4263b0','0x428830','0x428930'],scope:'Real native enemy construction, movement and script execution across nested births, pre-insertion child creation, cached-next traversal, initial update guards, removal flags/script ends, ID wrapping, inherited slowdown and manager timers. Damage, animation and distortion services are boundaries; this is not full-game replay verification.'});}
 finally{c.program_delete(program);c.release(p);c.release(cpReq);c.release(cppName);m.close();}
});
