import test from 'node:test';import assert from 'node:assert/strict';import {core,oracle,memory,report,enableNativeMath} from './helpers.mjs';
test('TH15 enemy combat queries real player damage sources with native preview, hit position and frame gates',async()=>{
 const c=await core(),m=await oracle(),f=c.enemy_combat_create(),enemy=c.enemy_variables_create(),pool=c.enemy_combat_damage(f),data=c.damage_sources_data(pool),timer=c.enemy_combat_timer(f),player=m.allocate(0x2c100),bomb=m.allocate(64),sht=m.allocate(0xe0),vt=m.allocate(16),bombCallback=m.allocate(16),position=m.allocate(12),size=m.allocate(8),direct=m.allocate(4),output=m.allocate(12),values=m.allocate(4),call=m.allocate(16),out=c.allocate(20);enableNativeMath(m);m.u32(0x4e9bb8,player);m.u32(0x4e9a68,bomb);m.u32(player+0x2c008,sht);m.u32(bomb,vt);m.u32(vt+12,bombCallback);m.u32(bomb+0x24,1);let bombValue=0,nativeBombCalls=0,cases=0,queries=0,checks=0;
 m.replace(bombCallback,'bomb damage game-service boundary',()=>{nativeBombCalls++;return bombValue;},2);const code=Buffer.from([0xf3,0x0f,0x10,0x1d,0,0,0,0,0xe9,0,0,0,0]);code.writeUInt32LE(values,4);code.writeInt32LE(0x4594e0-call-code.length,9);m.write(call,code);
 const dv=()=>new DataView(c.memory.buffer),set=(cp,np,v,float=false)=>{if(float){dv().setFloat32(cp,v,true);m.f32(np,v);}else{dv().setInt32(cp,v|0,true);m.i32(np,v);}},bits=v=>{const b=Buffer.alloc(4);b.writeFloatLE(v);return b.readUInt32LE();};
 try{for(let sample=0;sample<2048;sample++){const native=player+0xcd8c;memory(c,data,256*148).fill(0);m.view(native,256*148).fill(0);const max=sample%127+1;set(c.damage_sources_maximum(pool),sht+0x28,max);set(c.damage_sources_score(pool),0x4e740c,sample*11);const changed=sample%17!==0;set(timer,player+0x62c,0);set(timer+4,player+0x630,changed?1:0);const px=Math.fround((sample%19-9)*1.375),py=Math.fround((sample%23-11)*.625),z=Math.fround(sample%5*.125),width=Math.fround(.125+sample%11*.5),height=Math.fround(.5+sample%13*.75),angle=Math.fround((sample%15-7)*.34906584),rectangle=sample&1,target=sample%13?sample%7+1:0;for(let i=0;i<3;i++)set(c.enemy_fixture_field(enemy,0,0,0)+i*4,position+i*4,[px,py,z][i],true);set(c.enemy_attribute_field(enemy,0),size,width,true);set(c.enemy_attribute_field(enemy,0)+4,size+4,height,true);set(c.enemy_attribute_field(enemy,2),values,angle,true);dv().setUint32(c.enemy_fixture_field(enemy,0,9,2),rectangle?0x1000:0,true);dv().setInt32(c.enemy_fixture_field(enemy,0,9,6),target,true);for(let i=0;i<3;i++)dv().setFloat32(c.enemy_damage_field(enemy,6)+i*4,[17,23,31][i],true);
  for(let i=0;i<12;i++){const o=i*148,write=(off,v,float=false)=>set(data+o+off,native+o+off,v,float);write(0,1|((sample+i)%2?2:0)|((sample+i)%3?0:4));write(4,(sample%9+i)*.5,true);write(12,Math.fround((sample%13-6)*.2617994),true);write(20,((sample+i)%31)*.5,true);write(24,((sample+i)%29)*.75,true);write(28,Math.fround((i-5)*1.375),true);write(32,Math.fround((i-6)*.625),true);write(36,i*.125,true);write(96,8);write(100,9+(sample+i)%4);write(104,12,true);write(112,1);write(116,i-2);write(120,sample%3);write(124,(sample+i)%4?9999999:4);write(128,1+(sample+i)%3);write(132,sample%7?0:target);}
  bombValue=[0,7,-3,129][sample%4];nativeBombCalls=0;c.enemy_combat_configure(f,bombValue,1);
  for(let iteration=0;iteration<4;iteration++){const preview=iteration===0||iteration===2;m.u32(direct,0);[17,23,31].forEach((v,i)=>m.f32(output+i*4,v));const expected=m.call(call,{args:[position,rectangle?size:0,bits(width*.5),direct,output,preview?1:0,target]})|0;assert.equal(c.enemy_combat_shot(f,enemy,preview?1:0,out),1);const result=Buffer.alloc(20);result.writeInt32LE(expected);result.writeUInt32LE(m.u32(direct),4);Buffer.from(m.bytes(output,12)).copy(result,8);assert.deepEqual(Buffer.from(memory(c,out,20)),result,sample+'/'+iteration+' hit');assert.deepEqual(Buffer.from(memory(c,data,256*148)),Buffer.from(m.bytes(native,256*148)),sample+'/'+iteration+' actual pool');assert.equal(dv().getInt32(c.damage_sources_score(pool),true),m.i32(0x4e740c));assert.equal(c.enemy_combat_bomb_calls(f),nativeBombCalls);queries++;checks+=4;}cases++;}
  // A failed world service is propagated; an unchanged player frame never invokes it.
  c.enemy_combat_configure(f,0,0);dv().setInt32(timer,0,true);dv().setInt32(timer+4,1,true);assert.equal(c.enemy_combat_shot(f,enemy,0,out),0);c.enemy_combat_configure(f,0,0);dv().setInt32(timer+4,0,true);assert.equal(c.enemy_combat_shot(f,enemy,0,out),1);assert.equal(c.enemy_combat_bomb_calls(f),0);
  report('enemy-combat-damage',{passed:true,cases,queries,checks,originalFunction:'0x4594e0',scope:'EnemyCombat builds typed enemy shape/ID queries and directly invokes the real 256-source DamageSources pool. Native original player damage query compares repeated preview/normal hits, caps, budgets, last-target mutation, hit positions, scoring and bomb calls after frame-change gating. Bomb damage itself remains a game-service boundary; actual PlayerShots callbacks verified separately, full battle not yet verified.'});
 }finally{c.release(out);c.enemy_variables_delete(enemy);c.enemy_combat_delete(f);m.close();}
});
