import test from 'node:test';import assert from 'node:assert/strict';import {core,oracle,memory,string,report} from './helpers.mjs';import {bits,ins,resource,call} from './ecl-fixtures.mjs';
const replaceRoutine=(id,name,time)=>{const text=Buffer.from(name+'\0'),n=(text.length+3)&~3,b=Buffer.alloc(24+n);b.writeInt32LE(time);b.writeUInt16LE(800,4);b.writeUInt16LE(b.length,6);b[10]=255;b[11]=2;b.writeInt32LE(id,16);b.writeUInt32LE(n,20);text.copy(b,24);return b;};
const fork=name=>{const b=call(name,[]);b.writeUInt16LE(15,4);return b;};
test('TH15 script frame-rate writes preserve same-frame ECL interpolation, subsequent enemies and slowdown restoration',async()=>{
 const c=await core(),m=await oracle(),manager=m.allocate(0x200),request=m.allocate(84),cpReq=c.allocate(84),text=c.allocate(64),nativeProgram=m.allocate(0x90);m.u32(0x521e34,1);m.u32(0x4ca620,0x4e73e8);m.u32(0x4e9a80,manager);m.replace(0x488510,'no animations in routine-replacement fixture',()=>0,1);m.replace(0x427a10,'independent damage boundary',()=>0);m.replace(0x428220,'independent distortion boundary',()=>0);let cases=0,checks=0,frames=0;
 try{for(let sample=0;sample<64;sample++){const changed=[0,.25,.5,.75,1,1.25,2][sample%7],curve=ins(91,[0,bits(-9981),47,0,bits(-3),bits(17)],2),scripts={controller:Buffer.concat([ins(40,[16]),curve,ins(547,[bits(changed)],0,5),ins(547,[bits(1)],0,20),ins(0,[],0,10000)]),worker:Buffer.concat([ins(40,[16]),curve,fork('child'),ins(404,[bits(.125),bits(.25)]),ins(0,[],0,10000)]),child:Buffer.concat([ins(40,[8]),curve,ins(0,[],0,10000)])};const {bytes,names}=resource(scripts),program=c.program_create(),at=c.allocate(bytes.length),np=m.allocate(bytes.length),defs=m.allocate(names.length*8),namesNative={};memory(c,at,bytes.length).set(bytes);m.write(np,bytes);assert.equal(c.program_attach(program,at,bytes.length),0);m.u32(nativeProgram+8,names.length);m.u32(nativeProgram+0x8c,defs);names.forEach((name,i)=>{const p=m.allocate(name.length+1);m.write(p,Buffer.from(name+'\0'));namesNative[name]=p;m.u32(defs+i*8,p);m.u32(defs+i*8+4,np+bytes.readUInt32LE(36+i*4));});m.view(manager,0x200).fill(0);m.u32(manager+0x17c,nativeProgram);m.u32(manager+0x8c,1000);m.u32(manager+0x90,1);m.call(0x409040,{ecx:manager+0x98,args:[0]});m.u32(0x4e73f8,0);m.u32(0x4e7410,0);m.f32(0x4e73e8,1);const f=c.enemy_manager_create(program);try{for(const [i,name]of ['controller','worker','worker'].entries()){const req=Buffer.alloc(84);req.writeFloatLE(i*7);req.writeFloatLE(80+i*13,4);req.writeInt32LE(100,20);m.write(request,req);memory(c,cpReq,84).set(req);memory(c,text,name.length+1).set(Buffer.from(name+'\0'));assert.ok(m.call(0x426050,{ecx:manager,args:[namesNative[name],request,0]}));assert.equal(c.enemy_manager_spawn(f,text,cpReq),1,string(c,c.enemy_manager_error(f)));}
 for(let frame=0;frame<48;frame++){const base=[.5,1,1.25,1.5][sample%4],slowdown=sample&4?((frame%3)+1)*.125:0;let first=m.u32(m.u32(manager+0x180));m.f32(first+0x14f0,slowdown);new DataView(c.memory.buffer).setFloat32(c.enemy_manager_slowdown(f,0),slowdown,true);m.f32(0x4e73e8,base);assert.equal(m.call(0x426ad0,{ecx:manager}),1);assert.equal(c.enemy_manager_step(f,base),1,string(c,c.enemy_manager_error(f)));assert.equal(new DataView(c.memory.buffer).getFloat32(c.enemy_manager_rate(f),true),m.f32(0x4e73e8),'shared frame clock');assert.deepEqual(Buffer.from(memory(c,c.enemy_manager_timer(f),20)),Buffer.from(m.bytes(manager+0x98,20)),'manager frame clock');const owners=[];for(let node=m.u32(manager+0x180);node;node=m.u32(node+4))owners.push(m.u32(node));assert.equal(c.enemy_manager_count(f),owners.length);owners.forEach((owner,index)=>{const contexts=[];for(let node=owner+0x11fc;node;node=m.u32(node+4))contexts.push(m.u32(node));contexts.forEach((nctx,k)=>{const ctx=c.enemy_manager_context(f,index,k);assert.ok(ctx);assert.deepEqual(Buffer.from(memory(c,c.ecl_context_state(ctx),12)),Buffer.from(m.bytes(nctx,12)),sample+'/'+frame+'/'+index+'/'+k+' cursor/time');assert.equal(c.ecl_context_field(ctx,0),m.i32(nctx+0x100c));assert.equal(c.ecl_context_field(ctx,1),m.i32(nctx+0x1010));assert.deepEqual(Buffer.from(memory(c,c.ecl_context_stack(ctx),4096)),Buffer.from(m.bytes(nctx+12,4096)));checks+=4;});const projection=c.enemy_manager_projection(f,index);assert.deepEqual(Buffer.from(memory(c,c.enemy_fixture_field(projection,0,7,0),4)),Buffer.from(m.bytes(owner+0x120c+0x29c,4)),sample+'/'+frame+'/'+index+' interpolated float');checks++;assert.equal(c.enemy_manager_context(f,index,contexts.length),0);const state=c.enemy_manager_projection(f,index);for(const [kind,offset]of [[0,0x44],[1,0x88],[2,0xcc]])assert.deepEqual(Buffer.from(memory(c,c.enemy_motion(state,kind),68)),Buffer.from(m.bytes(owner+0x120c+offset,68)));checks+=4;});frames++;}cases++;
 }finally{c.enemy_manager_delete(f);c.program_delete(program);c.release(at);}}
 report('enemy-frame-clock',{passed:true,cases,checks,frames,originalFunctions:['0x426050','0x426ad0','0x428830','0x428930','0x48e690','0x48ca80','0x4291e0','0x41f010'],scope:'Original ECL 547, main/concurrent elapsed snapshots versus live interpolation clock, subsequent enemy movement, shared manager timer, callback-local slowdown restoration and cursor/stack state. Same-frame rate changes compared; complete game scheduler/platform remains unfinished.'});
 }finally{c.release(cpReq);c.release(text);m.close();}
});
