import test from 'node:test';import assert from 'node:assert/strict';import {core,oracle,memory,string,report,enableNativeMath} from './helpers.mjs';import {ins,resource} from './ecl-fixtures.mjs';
test('TH15 enemy life damage preserves original signed wraparound and scaled life budget',async()=>{
 const c=await core(),m=await oracle(),fixture=c.enemy_variables_create(),state=m.allocate(28);let checks=0;
 try{for(let sample=0;sample<8192;sample++){
  const seed=Buffer.alloc(28);for(let i=0;i<6;i++)seed.writeInt32LE((Math.imul(sample+1,(i+1)*73799731)^Math.imul(i+1,33773131))|0,i*4);seed.writeUInt32LE(sample&7,24);memory(c,c.enemy_attribute_field(fixture,5),16).set(seed.subarray(0,16));new DataView(c.memory.buffer).setInt32(c.enemy_life_threshold(fixture),seed.readInt32LE(16),true);new DataView(c.memory.buffer).setInt32(c.enemy_damage_field(fixture,1),seed.readInt32LE(20),true);new DataView(c.memory.buffer).setUint32(c.enemy_attribute_field(fixture,13),seed.readUInt32LE(24),true);m.write(state,seed);const amount=Math.imul(sample+3,397317313)|0;m.call(0x424dc0,{ecx:state,args:[amount]});c.enemy_apply_damage(fixture,amount);assert.deepEqual(Buffer.from(memory(c,c.enemy_attribute_field(fixture,5),16)),Buffer.from(m.bytes(state,16)),JSON.stringify({sample,amount})+' life');assert.equal(new DataView(c.memory.buffer).getInt32(c.enemy_damage_field(fixture,1),true),m.i32(state+20));checks+=5;
 }report('enemy-life-damage',{passed:true,cases:8192,checks,originalFunction:'0x424dc0',scope:'Life subtraction, cumulative damage, scaled life budget, signed 32-bit overflow and truncating division.'});}
 finally{c.enemy_variables_delete(fixture);m.close();}
});
test('TH15 enemy damage update matches original damage gates, death boundaries, contact, sounds and animation flashing',async()=>{
 const c=await core(),m=await oracle();enableNativeMath(m);m.u32(0x521e34,1);m.u32(0x4ca620,0x4e73e8);const{bytes,names}=resource({main:Buffer.concat([ins(40,[0]),ins(10,[],0,100000)])}),program=c.program_create(),p=c.allocate(bytes.length),np=m.allocate(bytes.length),nativeProgram=m.allocate(0x90),definitions=m.allocate(8),owner=m.allocate(0x574c),entity=owner+0x120c,nativeName=m.allocate(8),name=c.allocate(8),request=c.allocate(84),callback=m.allocate(16),vm=m.allocate(0x608),manager=m.allocate(0x200),spell=m.allocate(0x1c8),game=m.allocate(0x28),player=m.allocate(0x16224),runtime=c.enemy_runtime_create(program),fixture=c.enemy_runtime_projection(runtime);memory(c,p,bytes.length).set(bytes);m.write(np,bytes);assert.equal(c.program_attach(program,p,bytes.length),0);m.u32(nativeProgram+8,1);m.u32(nativeProgram+0x8c,definitions);m.write(nativeName,Buffer.from('main\0'));memory(c,name,5).set(Buffer.from('main\0'));m.u32(definitions,nativeName);m.u32(definitions+4,np+bytes.readUInt32LE(36));m.u32(0x4e9a80,manager);m.u32(manager+0x17c,nativeProgram);m.u32(0x4e9a70,spell);m.u32(0x4e9a8c,spell);m.u32(0x4e9a68,game);m.u32(0x4e9bb8,player);m.call(0x426c60,{ecx:owner,args:[nativeName]});const pristine=Buffer.from(m.bytes(owner,0x574c));let nativeEvents=[],nativeVisualEvents=[],configuration=[0,0,0,1,0];
 m.replace(0x4594e0,'player shot collision boundary',()=>{const sp=m.reg('ESP'),special=m.u32(sp+24);nativeEvents.push(4,special);m.u32(m.u32(sp+16),configuration[1]?1:0);return configuration[0];},7);
 m.replace(callback,'registered additional damage callback',()=>{nativeEvents.push(5,m.reg('EDX'));return configuration[2];});m.replace(0x428b70,'enemy death services boundary',()=>{nativeEvents.push(6,0);return configuration[3];});
 m.replace(0x455d00,'circular player contact boundary',()=>{nativeEvents.push(7,0);return configuration[4];},2);m.replace(0x455e10,'rectangular player contact boundary',()=>{nativeEvents.push(7,0);return configuration[4];},3);m.replace(0x4573a0,'player graze boundary',()=>{nativeEvents.push(8,0);return 0;},1);m.replace(0x476400,'positional audio boundary',()=>{nativeEvents.push(9,m.u32(m.reg('ESP')+4));return 0;},1);
 m.replace(0x488510,'primary animation lookup',()=>m.u32(m.reg('ESP')+4)?vm:0,1);m.replace(0x488a20,'primary animation handle lookup',()=>m.u32(m.reg('ECX'))?vm:0);m.replace(0x488fb0,'primary animation rebind boundary',()=>{nativeVisualEvents.push(5,m.u32(m.reg('ECX')),m.u32(m.reg('ESP')+4),0,0);return 0;},1);
 const write=(pointer,address,value,float=false)=>{const view=new DataView(c.memory.buffer);if(float){view.setFloat32(pointer,value,true);m.f32(address,value);}else{view.setInt32(pointer,value|0,true);m.i32(address,value|0);}};
 const states=[[5,0x3f74,16],[9,0x2bc,20],[10,0x3ff8,20],[11,0x400c,20],[13,0x3f8c,4]],damageStates=[[0,0x3fdc,4],[1,0x3f88,4],[2,0x3fec,4],[3,0x4068,4],[4,0x406c,4],[5,0x402c,20],[6,0x280,12],[7,0x3f84,4]],worldStates=[[0,player+0x16220],[1,spell+0x1b8],[2,manager+0xac],[3,manager+0xb0]];let frames=0,checks=0;
 try{for(let sample=0;sample<1024;sample++){
  const data=Buffer.alloc(84);data.writeInt32LE(100+sample%1200,20);memory(c,request,84).set(data);assert.equal(c.enemy_runtime_start(runtime,name,request,113),1);m.write(owner,pristine);m.u32(owner+0x5180,100+sample%1200);m.u32(owner+0x5184,100+sample%1200);m.u32(owner+0x5740,113);m.u32(entity+0x4520,callback);const flags=[0,16,32,1,128,0x800,0x1000,0x200,0x2000,0x4000000,0x80000000,0x40800000,0x10000000,0x20000001,0x30000001,0x40000000][sample%16]|(sample&16?0x200000:0);write(c.enemy_fixture_field(fixture,0,9,2),entity+0x4060,flags);write(c.enemy_attribute_field(fixture,0),entity+0x110,sample%5===0?-1:24,true);write(c.enemy_attribute_field(fixture,0)+4,entity+0x114,17,true);write(c.enemy_attribute_field(fixture,1),entity+0x118,24,true);write(c.enemy_attribute_field(fixture,1)+4,entity+0x11c,36,true);write(c.enemy_attribute_field(fixture,2),entity+0x120,.5,true);write(c.enemy_attribute_field(fixture,3),entity+0x4040,[-.5,0,.125,.5,1,2][Math.floor(sample/16)%6],true);write(c.enemy_attribute_field(fixture,4),entity+0x124,sample%17===0?0:1);write(c.enemy_metadata(fixture,2),entity+0x3ff4,sample%13===0?19:-1);write(c.enemy_attribute_field(fixture,13),entity+0x3f8c,sample%23===0?2:sample%7===0?1:0);write(c.enemy_damage_field(fixture,0),entity+0x3fdc,sample%9-3);write(c.enemy_damage_field(fixture,1),entity+0x3f88,sample*7);write(c.enemy_damage_field(fixture,2),entity+0x3fec,sample%7);write(c.enemy_damage_field(fixture,3),entity+0x4068,31);write(c.enemy_damage_field(fixture,4),entity+0x406c,13);write(c.enemy_life_threshold(fixture),entity+0x3f84,sample%31);write(c.enemy_attribute_field(fixture,5)+12,entity+0x3f80,5000);write(c.enemy_phase_world(fixture,5),game+0x24,Math.floor(sample/32)%3);write(c.enemy_world_field(fixture,1,2),0x4e7404,sample%5);write(c.enemy_chapter_field(fixture,5),spell+0x78,[0,1,9,33,41][Math.floor(sample/64)%5]);for(const[kind,address]of worldStates)write(c.enemy_damage_world(fixture,kind),address,kind===0?Math.floor(sample/17)%4:kind===1?+(sample%29===0):sample*17);
  for(const[kind,offset,n]of states)if(kind===9||kind===10||kind===11)m.write(entity+offset,Buffer.from(memory(c,c.enemy_attribute_field(fixture,kind),n)));
  const instance=c.enemy_visual_vm(fixture,0),visual=c.anm_vm_visual(instance);memory(c,visual,352).fill(0);m.view(vm,0x608).fill(0);write(visual,vm+0x18,0x70000|6);write(visual+100,vm+0x53c,0x12345678);write(c.anm_vm_variables(instance)+84,vm+0x4c,.25,true);const rate=[.5,.995,1,1.5,2][sample%5];
  for(let frame=0;frame<24;frame++){
   const age=frame+sample%7-3;write(c.enemy_attribute_field(fixture,9)+4,entity+0x2c0,age);write(c.enemy_attribute_field(fixture,10)+4,entity+0x3ffc,frame<2?2-frame:0);write(c.enemy_attribute_field(fixture,11)+4,entity+0x4010,frame<4?4-frame:0);configuration=[frame%5===0?0:sample%997-17,+(sample%3!==0),sample%7-2,+(sample%5!==0),sample%3];memory(c,c.enemy_damage_configuration(runtime),20).set(Buffer.from(Int32Array.from(configuration).buffer));nativeEvents=[];nativeVisualEvents=[];m.f32(0x4e73e8,rate);const expected=m.call(0x427a10,{ecx:entity})|0,actual=c.enemy_damage_step(runtime,rate),label=JSON.stringify({sample,frame});assert.equal(string(c,c.enemy_runtime_error(runtime)),'',label+' error');assert.equal(actual,expected,label+' result');assert.deepEqual(Buffer.from(memory(c,c.enemy_runtime_events(runtime),c.enemy_runtime_event_count(runtime)*8)),Buffer.from(Uint32Array.from(nativeEvents).buffer),label+' event order');assert.deepEqual(Buffer.from(memory(c,c.enemy_visual_events(fixture),c.enemy_visual_count(fixture)*20)),Buffer.from(Uint32Array.from(nativeVisualEvents).buffer),label+' animation rebind');c.enemy_visual_reset(fixture,0);
   for(const[kind,offset,n]of states)assert.deepEqual(Buffer.from(memory(c,c.enemy_attribute_field(fixture,kind),n)),Buffer.from(m.bytes(entity+offset,n)),label+' state '+offset.toString(16));for(const[kind,offset,n]of damageStates)assert.deepEqual(Buffer.from(memory(c,c.enemy_damage_field(fixture,kind),n)),Buffer.from(m.bytes(entity+offset,n)),label+' damage '+offset.toString(16));for(const[kind,address]of worldStates)assert.equal(new DataView(c.memory.buffer).getInt32(c.enemy_damage_world(fixture,kind),true),m.i32(address),label+' world '+kind);assert.equal(new DataView(c.memory.buffer).getUint32(c.enemy_fixture_field(fixture,0,9,2),true),m.u32(entity+0x4060),label+' flags');assert.equal(new DataView(c.memory.buffer).getInt32(c.enemy_animation_field(fixture,3),true),m.i32(entity+0x270),label+' animation base');assert.equal(new DataView(c.memory.buffer).getUint32(visual,true),m.u32(vm+0x18),label+' animation flags');assert.equal(new DataView(c.memory.buffer).getUint32(visual+100,true),m.u32(vm+0x53c),label+' secondary colour');frames++;checks+=26;if(actual)break;
  }
 }report('enemy-damage-update',{passed:true,cases:1024,frames,checks,originalFunctions:['0x427a10','0x424dc0','0x430050'],scope:'Real damage gates, cumulative/overkill damage, invulnerability, spell reduction, life and death flags, normal/inactive animation changes, contact/graze gating, timed colour flashes and hit sound selection. Shot/contact/death/audio/animation allocation remain explicitly captured service boundaries; full player and world replay verification remains incomplete.'});}
 finally{c.enemy_runtime_delete(runtime);c.program_delete(program);c.release(p);c.release(name);c.release(request);m.close();}
});
