import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {resolve} from 'node:path';import {core,oracle,memory,string,root,report} from './helpers.mjs';
test('TH15 laser-origin callback preserves all four concrete laser kinds, zero identifiers and single-precision addition',async()=>{
 const c=await core(),m=await oracle(),a=c.anm_manager_create(),p=c.player_collision_create(),native=m.allocate(0x610),enemy=m.allocate(0x4530),records=Array.from({length:4},()=>m.allocate(0x100));m.u32(0x4e9ba0,native);let checks=0;
 const load=(name,id)=>{const bytes=readFileSync(resolve(root,'reference/assets',name)),at=c.allocate(bytes.length);memory(c,at,bytes.length).set(bytes);assert.equal(c.anm_manager_load(a,id,at,bytes.length),1,string(c,c.anm_manager_error(a)));c.release(at);};load('ascii.anm',2);c.anm_manager_fallback(a,2);load('bullet.anm',9);const f=c.laser_scene_create(a,p,9);
 try{const put=(at,value)=>new DataView(c.memory.buffer).setFloat32(at,value,true);put(c.laser_scene_request(f,2),128);put(c.laser_scene_request(f,3),64);put(c.laser_scene_request(f,5),16);put(c.laser_scene_stationary_request(f,4),128);put(c.laser_scene_stationary_request(f,5),64);put(c.laser_scene_stationary_request(f,6),16);new DataView(c.memory.buffer).setUint32(c.laser_scene_curve_request(f,6),32,true);put(c.laser_scene_curve_request(f,2),16);put(c.laser_scene_segmented_request(f,2),64);assert.ok(c.laser_scene_emit(f));assert.ok(c.laser_scene_stationary_emit(f));assert.ok(c.laser_scene_curve_emit(f));assert.ok(c.laser_scene_segmented_emit(f));assert.equal(c.laser_scene_count(f),4);m.u32(native+0x14,records[0]);records.forEach((r,i)=>m.u32(r+8,i<3?records[i+1]:0));
 for(let sample=0;sample<8192;sample++){const first=Math.fround((sample%31-15)*.125),second=Math.fround((sample%23-11)*.3);m.f32(enemy+0x29c,first);m.f32(enemy+0x2a0,second);for(let i=0;i<4;i++){const id=(sample+i)%3?65536+i:0,origin=[Math.fround(i*1.3),Math.fround((sample%177-88)*3.7),-2.5];c.laser_scene_set_identifier(f,i,id);m.u32(records[i]+0x80,id);for(let k=0;k<3;k++){put(c.laser_scene_origin(f,i)+4*k,origin[k]);m.f32(records[i]+0x54+4*k,origin[k]);}}
 assert.equal(m.call(0x431840,{ecx:enemy}),0);c.laser_scene_offset_origins(f,first,second);for(let i=0;i<4;i++){assert.deepEqual(Buffer.from(memory(c,c.laser_scene_origin(f,i),12)),Buffer.from(m.bytes(records[i]+0x54,12)),sample+'/'+i);checks++;}}
 report('enemy-laser-callback',{passed:true,cases:8192,checks,originalFunctions:['0x431840'],scope:'Original list callback compared with four concrete C++ laser objects, common origin and untouched X/Z, identifier-dependent Y shift including zero identifiers and exact float addition. Laser creation/update separately compared; full game world remains unfinished.'});
 }finally{c.laser_scene_delete(f);c.player_collision_delete(p);c.anm_manager_delete(a);m.close();}
});
