import test from 'node:test';import assert from 'node:assert/strict';import {core,oracle,memory,string,report,enableOriginalVectorMath,enableNativeMath} from './helpers.mjs';import {enemyInterpreter} from './enemy-native-context.mjs';import {bits} from './ecl-fixtures.mjs';
test('TH15 Boss radial distortion reproduces original screen grid vertices, UV clipping, growth, wave phases and interleaved strips',async()=>{
 const c=await core(),m=await oracle(),f=c.screen_grid_create(),entity=m.allocate(0x4530),grid=m.allocate(0x1c),vertices=m.allocate(17*17*28),samples=m.allocate(17*17*12),instances=m.allocate(17*4),vms=Array.from({length:16},()=>m.allocate(0x600)),strips=Array.from({length:16},()=>m.allocate(34*28));enableNativeMath(m);const lib=enableOriginalVectorMath(m);for(const entry of m.image.imports)if(entry.dll==='d3dx9_43.dll'&&entry.name==='D3DXVec3Normalize')m.u32(entry.address,lib.exports.get(entry.name));m.u32(entity+0x44bc,grid);m.u32(grid,17);m.u32(grid+4,17);m.u32(grid+0x14,vertices);m.u32(grid+0x18,samples);m.u32(grid+0x10,instances);for(let i=0;i<16;i++){m.u32(instances+i*4,vms[i]);m.u32(vms[i]+0x5c4,strips[i]);}let frames=0,checks=0;
 try{for(let scenario=0;scenario<96;scenario++){const view=[640,480,320,16,128],target=[0,16,17,64,128,160,300,8][scenario%8],color=(scenario*31573)^0x003f9fbf,rate=[.25,.5,1,1.25,2][scenario%5];view.forEach((v,i)=>new DataView(c.memory.buffer).setInt32(c.screen_grid_field(f,1)+i*4,v,true));for(const [address,value]of [[0x51bbfc,view[0]],[0x51bc00,view[1]],[0x51bc20,view[2]],[0x51bc24,view[3]],[0x51bc08,view[4]]])m.i32(address,value);const state=Buffer.alloc(20);state.writeFloatLE(target);state.writeFloatLE(16,4);state.writeUInt32LE(color>>>0,8);memory(c,c.screen_grid_field(f,0),20).set(state);m.write(entity+0x44c4,state);
 for(let frame=0;frame<32;frame++){const position=[Math.fround((scenario%11-5)*24+(frame%7-3)*1.75),Math.fround((scenario%13)*39+(frame%5-2)*.375),[0,-2.5,4][scenario%3]];position.forEach((v,i)=>{new DataView(c.memory.buffer).setFloat32(c.screen_grid_field(f,2)+i*4,v,true);m.f32(entity+0x44+i*4,v);});m.f32(0x4e73e8,rate);m.call(0x428220,{ecx:entity});assert.equal(c.screen_grid_update(f,rate),1);const label=scenario+'/'+frame;assert.deepEqual(Buffer.from(memory(c,c.screen_grid_field(f,0),20)),Buffer.from(m.bytes(entity+0x44c4,20)),label+' state');assert.deepEqual(Buffer.from(memory(c,c.screen_grid_field(f,3),17*17*28)),Buffer.from(m.bytes(vertices,17*17*28)),label+' CPU vertices');assert.deepEqual(Buffer.from(memory(c,c.screen_grid_field(f,4),17*17*12)),Buffer.from(m.bytes(samples,17*17*12)),label+' sample positions');checks+=3;if(frame%11===0){m.call(0x422f20,{ecx:grid});for(let col=0;col<16;col++){assert.equal(c.screen_grid_strip(f,col),1);assert.deepEqual(Buffer.from(memory(c,c.screen_grid_field(f,5),34*28)),Buffer.from(m.bytes(strips[col],34*28)),label+' strip '+col);checks++;}}frames++;}}
 report('enemy-distortion-grid',{passed:true,scenarios:96,frames,checks,originalFunctions:['0x428220','0x422d30','0x422f20','D3DXVec3Normalize'],scope:'Unchanged original geometry functions and independently loaded original normalization routine; radius growth uses previous frame radius, packed color channel arithmetic, sine phase order, all CPU vertices/sampling coordinates/UV clipping, exact strip order. Animation allocation, screen capture and GPU pixels remain separate unfinished work.'});
 }finally{c.screen_grid_delete(f);m.close();}
});
test('TH15 ECL radial distortion replacement preserves old-object retirement, getter order and exact state reset',async()=>{
 const c=await core(),m=await oracle(),f=c.enemy_variables_create();let events=[],cases=0,checks=0;m.replace(0x40e5b0,'observe old distortion retirement',()=>{events.push(1);return 0;},1);m.replace(0x422bf0,'observe distortion mesh factory boundary',()=>{assert.equal(m.u32(m.reg('ESP')+8),17);events.push(2);return m.reg('ECX');},3);
 try{for(let sample=0;sample<1024;sample++){const radius=[-1,0,16,128,160,300][sample%6],color=(sample*7753)^0x3f8fff,old=sample&1,it=enemyInterpreter(c,m,f,629,[bits(radius),color]),entity=m.u32(it.native+0x1018)+0x120c;try{m.u32(entity+0x44bc,old?m.allocate(0x1c):0);c.enemy_distortion_active(f,old);events=[];const [actual,expected]=it.run();assert.equal(actual,expected,string(c,c.ecl_context_error(it.ctx)));assert.deepEqual(Buffer.from(memory(c,c.enemy_distortion_field(f),20)),Buffer.from(m.bytes(entity+0x44c4,20)));assert.deepEqual(Array.from(new Uint32Array(c.memory.buffer,c.enemy_distortion_events(f),c.enemy_distortion_event_count(f))),events);assert.deepEqual(Buffer.from(memory(c,c.ecl_context_state(it.ctx),12)),Buffer.from(m.bytes(it.native,12)));cases++;checks+=4;}finally{it.dispose();}}
 report('enemy-distortion-command',{passed:true,cases,checks,originalFunctions:['0x48ca80','0x4291e0'],scope:'Full original ECL dispatcher: old-object cleanup before argument retrieval, reset radius/color/phase, creation predicate and 17-row request observed at factory boundary. GPU mesh allocation remains separate.'});
 }finally{c.enemy_variables_delete(f);m.close();}
});
