import test from 'node:test';import assert from 'node:assert/strict';import {core,oracle,memory,string,report} from './helpers.mjs';
test('TH15 enemy life/time interrupt choice, Boss timer and spell timeout state match original',async()=>{
 const c=await core(),m=await oracle(),fixture=c.enemy_variables_create(),owner=m.allocate(0x5780),spell=m.allocate(0x1c8),manager=m.allocate(0x200),game=m.allocate(0x28),p=c.allocate(128);m.u32(0x4e9a70,spell);m.u32(0x4e9a8c,spell);m.u32(0x4e9a80,manager);m.u32(0x4e9a68,game);let checks=0,cases=0;
 const fields=[[5,owner+0x5180,16],[9,owner+0x14c8,20],[12,owner+0x5734,8]],worldFields=[[0,0x4e73f8],[1,0x4e7484],[2,0x4e7488],[5,spell+0x78]],phaseFields=[[1,spell+0x1c0],[2,spell+0x1c4],[3,spell+0x24],[4,spell+0x7c],[5,game+0x24],[6,manager+0x44]];
 const write=(ptr,address,value)=>{new DataView(c.memory.buffer).setInt32(ptr,value|0,true);m.i32(address,value|0);};
 try{for(let sample=0;sample<8192;sample++){
  m.view(owner,0x5780).fill(0);for(const [kind,address,n]of fields){const seed=Buffer.alloc(n);if(kind===5){[sample%151-17,31,37,43].forEach((v,i)=>seed.writeInt32LE(v,i*4));}else if(kind===9){seed.writeInt32LE(-1);seed.writeInt32LE(sample%7200,4);seed.writeFloatLE(sample%7200,8);seed.writeUInt32LE(17,12);seed.writeUInt32LE(sample%2,16);}else{seed.writeInt32LE(sample%7);seed.writeInt32LE(sample%5-1,4);}memory(c,c.enemy_attribute_field(fixture,kind),n).set(seed);m.write(address,seed);}write(c.enemy_life_threshold(fixture),owner+0x5190,19);write(c.enemy_fixture_field(fixture,0,9,2),owner+0x526c,(sample%2?0x800000:0)|(sample%3?0x1000000:0)|0x1234);for(const [kind,address]of worldFields)write(c.enemy_chapter_field(fixture,kind),address,kind===0?sample%11:kind===5?sample%256:sample*7-11);for(const [kind,address]of phaseFields)write(c.enemy_phase_world(fixture,kind),address,kind===3?sample%90:kind===5?sample%3:sample%151-17);
  for(let slot=0;slot<8;slot++){const state=Buffer.alloc(8);state.writeInt32LE((sample*737+slot*997)%13<5?-1:(sample*373+slot*317)%150);state.writeInt32LE((sample*997+slot*317)%17<4?-1:(sample*337+slot*137)%7300,4);memory(c,c.enemy_interrupt_fields(fixture,slot),8).set(state);m.write(owner+0x5284+slot*136,state);const first=Buffer.from('life_'+slot+'_'+sample+'\0'),second=Buffer.from('timeout_'+slot+'_'+sample+'\0');memory(c,p,128).fill(0);memory(c,p,first.length).set(first);memory(c,p+64,second.length).set(second);c.enemy_interrupt_names(fixture,slot,p,p+64);m.write(owner+0x528c+slot*136,first);m.write(owner+0x52cc+slot*136,second);}
  const expected=m.call(0x430050,{ecx:owner})>>>0,actual=c.enemy_interrupt_check(fixture)>>>0,label=JSON.stringify({sample});assert.equal(Boolean(actual),Boolean(expected),label+' interrupt');if(actual)assert.equal(string(c,actual),m.string(expected),label+' script');for(const [kind,address,n]of fields)assert.deepEqual(Buffer.from(memory(c,c.enemy_attribute_field(fixture,kind),n)),Buffer.from(m.bytes(address,n)),label+' state '+address.toString(16));assert.equal(new DataView(c.memory.buffer).getInt32(c.enemy_life_threshold(fixture),true),m.i32(owner+0x5190),label+' life threshold');assert.equal(new DataView(c.memory.buffer).getUint32(c.enemy_fixture_field(fixture,0,9,2),true),m.u32(owner+0x526c),label+' flags');for(const [kind,address]of worldFields)assert.equal(new DataView(c.memory.buffer).getInt32(c.enemy_chapter_field(fixture,kind),true),m.i32(address),label+' chapter/spell '+kind);for(const [kind,address]of phaseFields)assert.equal(new DataView(c.memory.buffer).getInt32(c.enemy_phase_world(fixture,kind),true),m.i32(address),label+' phase '+kind);for(let slot=0;slot<8;slot++)assert.deepEqual(Buffer.from(memory(c,c.enemy_interrupt_fields(fixture,slot),8)),Buffer.from(m.bytes(owner+0x5284+slot*136,8)),label+' interrupt '+slot);checks+=26;cases++;
 }report('enemy-life-time-interrupts',{passed:true,cases,checks,originalFunction:'0x00430050',scope:'Eight interrupt priorities, life thresholds, timeout routine choice, timer resets, Boss seconds/hundredths, chapter contribution accounting, spell timeout flags/bonus and damage-gate state. Starting the returned ECL routine and downstream stage/GUI state remain manager integration.'});
 }finally{c.enemy_variables_delete(fixture);c.release(p);m.close();}
});
