import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync,readdirSync} from 'node:fs';import {resolve} from 'node:path';import {core,oracle,memory,string,root,report,enableNativeMath} from './helpers.mjs';import {resourceLoader,nativePool,prepareBank,nativeInstances,compareAnm} from './anm-oracle.mjs';
test('TH15 world graze binds original score, point value, actual effect, popup, player flash and item slowdown',async()=>{
 const c=await core(),m=await oracle(),a=c.stage_assets_create(),r=c.run_gameplay_create(a),name=c.allocate(256),position=c.allocate(12),owned=[];let cases=0,checks=0;enableNativeMath(m);
 try {for(const file of readdirSync(resolve(root,'reference/assets')).filter(n=>/\.(anm|ecl|sht|std|msg)$/.test(n))){const bytes=readFileSync(resolve(root,'reference/assets',file)),p=c.allocate(bytes.length);owned.push(p);memory(c,p,bytes.length).set(bytes);memory(c,name,file.length+1).set(Buffer.from(file+'\0'));c.stage_assets_file(a,name,p,bytes.length);}assert.equal(c.run_gameplay_load(r,1,0),1,string(c,c.run_gameplay_error(r)));
 const nm=nativePool(m),loader=resourceLoader(m),ascii=prepareBank(m,loader,'ascii.anm',readFileSync(resolve(root,'reference/assets/ascii.anm')),nm,5),textOwner=m.allocate(0x19270),captionBank=(m.u32(0x4e9a58,textOwner),m.u32(textOwner+0x19258,ascii)),bank=prepareBank(m,loader,'effect.anm',readFileSync(resolve(root,'reference/assets/effect.anm')),nm,8),effect=m.allocate(16),player=m.allocate(0x2c0a0),popups=m.allocate(0x1040),np=m.allocate(12),score=c.run_gameplay_field(r,2),cppPosition=c.run_gameplay_field(r,3);m.u32(0x4e9bb8,player);m.u32(0x4e9a78,effect);m.u32(effect+12,bank);m.u32(0x4e9bd0,popups);m.u32(0x4e79cc,4);m.u32(0x4ca620,0x4e73e8);m.f32(0x4e73e8,1);m.f32(0x51bc04,1);let sounds=[];m.replace(0x476400,'graze positioned audio',()=>{sounds.push(m.i32(m.reg('ESP')+4));return 0;},1);
 for(let i=0;i<128;i++){const dv=()=>new DataView(c.memory.buffer),total=[0,73,99999998,99999999][i%4],chapter=[0,8,99999998,99999999][i%4],max=50000000,value=[1000000,max-50,max,max+200][i%4];for(const [at,native,v] of [[48,0x4e741c,total],[52,0x4e7420,chapter],[4,0x4e7434,value],[8,0x4e743c,max]]){dv().setInt32(score+at,v,true);m.i32(native,v);}for(let k=0;k<3;k++){const p=(i%17-7+k*13)*7.125,v=(i%13-5+k*7)*13.25;dv().setFloat32(position+k*4,p,true);m.f32(np+k*4,p);dv().setFloat32(cppPosition+k*4,v,true);m.f32(player+0x618+k*4,v);}const seed=Buffer.alloc(8);seed.writeUInt16LE(i*977&65535);memory(c,c.run_gameplay_visual_rng(r),8).set(seed);m.write(0x4e9a40,seed);const count=nativeInstances(m,nm,false).length,soundCount=sounds.length;m.call(0x4573a0,{args:[np]});assert.equal(c.run_gameplay_graze(r,position),1,string(c,c.run_gameplay_error(r)));for(const [at,native] of [[48,0x4e741c],[52,0x4e7420],[4,0x4e7434]])assert.equal(dv().getInt32(score+at,true),m.i32(native),'score '+i+'/'+at);const nativeVm=nativeInstances(m,nm,false).at(-1),cppVm=c.run_gameplay_graze_animation(r);assert.equal(nativeInstances(m,nm,false).length,count+1);assert.ok(cppVm);compareAnm(c,m,cppVm,nativeVm,'effect '+i);assert.deepEqual(Buffer.from(memory(c,c.run_gameplay_visual_rng(r),8)),Buffer.from(m.bytes(0x4e9a40,8)),'visual RNG '+i);assert.deepEqual(Buffer.from(memory(c,c.run_gameplay_field(r,6),18*72)),Buffer.from(m.bytes(popups+0x620,18*72)),'popup '+i);assert.equal(sounds.length,soundCount+1);assert.equal(sounds.at(-1),42);
 const timer=Buffer.alloc(20);timer.writeInt32LE(i-2);timer.writeInt32LE(i,4);timer.writeFloatLE(i+.25,8);timer.writeUInt32LE(i%3,12);timer.writeUInt32LE(i%4,16);memory(c,c.run_gameplay_graze_timer(r),20).set(timer);m.write(player+0x1622c,timer);m.call(0x4581d0);c.run_gameplay_graze_flash(r);assert.deepEqual(Buffer.from(memory(c,c.run_gameplay_graze_timer(r),20)),Buffer.from(m.bytes(player+0x1622c,20)),'flash '+i);c.run_gameplay_graze_resonance(r,.3);assert.equal(dv().getFloat32(c.run_gameplay_graze_scale(r),true),Math.fround(.3));cases++;checks+=25;}
 report('gameplay-graze',{passed:true,cases,checks,originalFunctions:['0x4573a0','0x4581d0','0x45ef60'],scope:'Actual named stage/run owners: graze total/chapter saturation, capped point value, effect.anm script 24 full animation state and RNG, floating number ring and sound 42, all original flash timer initialization flags/rate indices, item motion-scale binding. Original audio mixing and item/frame motion separately covered.'});
 }finally{c.run_gameplay_delete(r);c.stage_assets_delete(a);for(const p of owned)c.release(p);c.release(name);c.release(position);m.close();}
});
