import test from 'node:test';import assert from 'node:assert/strict';import{readFileSync}from'node:fs';import{resolve}from'node:path';import{core,oracle,memory,string,root,report,enableNativeMath}from'./helpers.mjs';import{resourceLoader,nativePool,prepareBank,nativeInstances,compareAnm}from'./anm-oracle.mjs';
test('TH15 real front HUD entry, stock fragments, mode labels and stage notices match original ANM trees',async()=>{
 const c=await core(),m=await oracle();enableNativeMath(m);const loader=resourceLoader(m),base=m.heap;let scenarios=0,checks=0,frames=0;
 try{for(let sample=0;sample<48;sample++){m.heap=base;m.view(m.heap,0x1caf980).fill(0);const a=c.anm_manager_create(),native=nativePool(m),owner=m.allocate(0x2d4),scene=m.allocate(0xc0),text=m.allocate(0x19270),f=c.game_hud_create(a,5,2,6);try{
 m.view(owner,0x2d4).fill(0);m.view(scene,0xc0).fill(0);m.u32(0x4e9a8c,owner);m.u32(0x4e9a94,scene);m.u32(0x4e9a58,text);m.u32(0x4e9a40,0);m.u32(0x4e9a44,0);m.u32(0x4ca620,0x4e73e8);m.f32(0x4e73e8,1);m.view(0x4e73f0,0x400).fill(0);
 for(const[name,id]of[['ascii.anm',2],['front.anm',5],['st01logo.anm',6]]){const b=readFileSync(resolve(root,'reference/assets',name)),p=c.allocate(b.length);memory(c,p,b.length).set(b);assert.equal(c.anm_manager_load(a,id,p,b.length),1,name+' '+string(c,c.anm_manager_error(a)));c.release(p);const bank=prepareBank(m,loader,name,b,native,id);if(id===2){m.u32(text+0x19258,bank);assert.equal(c.anm_manager_fallback(a,2),1);}else m.u32(owner+(id===5?0x2c8:0x168),bank);}
 const s=c.game_hud_field(f,0),p=c.game_hud_field(f,1),score=c.game_hud_field(f,2),difficulty=sample%5,character=Math.floor(sample/5)%4,mode=[0,0x100,0x200,0x20,0x40,0x140][Math.floor(sample/8)%6],destination=sample%3?7:8;let dv=new DataView(c.memory.buffer);for(const[offset,at,value]of[[0,0x4e73f0,sample%2?1:2],[16,0x4e7404,character],[24,0x4e7410,difficulty],[28,0x4e7414,sample%3?0:1],[100,scene+0xb4,sample%4?0:1]]){dv.setInt32(s+offset,value,true);m.i32(at,value);}dv.setUint8(s+108,sample%7!==0?1:0);m.u32(0x4e7ed8,sample%7!==0?1:0);dv.setUint32(p+24,mode,true);m.u32(0x4e7794,mode);dv.setInt32(p,sample%9,true);m.i32(0x4e7450,sample%9);dv.setInt32(p+4,sample%3,true);m.i32(0x4e7454,sample%3);dv.setInt32(p+36,(sample+3)%9,true);m.i32(0x4e745c,(sample+3)%9);dv.setInt32(p+40,sample%5,true);m.i32(0x4e7460,sample%5);dv.setInt32(score+40,sample%6,true);m.i32(0x4e7458,sample%6);m.i32(0x4e7ecc,destination);
 const compare=label=>{for(const[index,at,count]of[[3,0xc,8],[4,0x2c,8],[5,0x4c,2],[6,0x140,1],[7,0x9c,1],[8,0x10c,1],[9,0x104,1],[10,0x108,1]])assert.deepEqual(Buffer.from(memory(c,c.game_hud_field(f,index),count*4)),Buffer.from(m.bytes(owner+at,count*4)),label+' handles '+index);for(let alt=0;alt<2;alt++){const list=nativeInstances(m,native,alt);assert.equal(c.anm_manager_count(a,alt),list.length,label+' count');for(let i=0;i<list.length;i++){const h=m.u32(list[i]+0x544);assert.equal(c.anm_manager_order(a,alt,i),h,label+' queue');const vm=c.anm_manager_find(a,h);compareAnm(c,m,vm,list[i],label+' ANM '+h);assert.equal(c.anm_vm_pending_interrupt(vm),m.i32(list[i]+0x49c),label+' interrupt');assert.deepEqual(Buffer.from(memory(c,c.anm_vm_translation(vm),12)),Buffer.from(m.bytes(list[i]+0x5ec,12)));checks++;}}assert.deepEqual(Buffer.from(memory(c,c.anm_manager_random(a),8)),Buffer.from(m.bytes(0x4e9a40,8)),label+' visual RNG');};
 m.call(0x4340d0,{limit:10000000});assert.equal(c.game_hud_initialize(f,destination),1,string(c,c.game_hud_error(f)));compare(sample+' entry');
 for(let frame=0;frame<24;frame++){if(frame%4===0){const life=frame===8?-1:frame===16?-7:(sample+frame)%9,lp=frame%3,bomb=(sample+frame+1)%9,bp=frame%5;assert.equal(c.game_hud_stock(f,0,life,lp),1,string(c,c.game_hud_error(f)));m.call(0x43a850,{ecx:owner,args:[life,lp]});assert.equal(c.game_hud_stock(f,1,bomb,bp),1);m.call(0x43a960,{ecx:owner,args:[bomb,bp]});compare(sample+'/'+frame+' stock');}for(let alt=0;alt<2;alt++){assert.equal(c.anm_manager_update(a,alt,1),1,string(c,c.anm_manager_error(a)));m.call(alt?0x487890:0x487740,{ecx:native});}compare(sample+'/'+frame);frames++;}
 scenarios++;
 }finally{c.game_hud_delete(f);c.anm_manager_delete(a);}}
 report('game-hud-entry',{passed:true,scenarios,frames,animationChecks:checks,originalFunctions:['0x4340d0','0x43a850','0x43a960'],scope:'Unmodified original HUD entry and stock updates using actual front/ascii/st01logo scripts. Both animation queues, handle ownership, partial life and bomb pieces including Extra tiers, chapter mode label, demo/logo suppression, stage tutorial placement and difficulty notices checked before/after real updates. HUD frame/draw controller and full scene remain separate requirements.'});
 }finally{m.close();}
});
