import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {resolve} from 'node:path';import {core,memory,string,report,root} from './helpers.mjs';import {bits,ins,resource} from './ecl-fixtures.mjs';
test('TH15 real battle scene connects four players, scripted enemies, projectiles, damage, drops, collection and bombs',async()=>{
 const c=await core();let frames=0,damageCases=0,deathCases=0,bombCases=0,checks=0;
 const {bytes}=resource({main:Buffer.concat([ins(40,[0]),ins(302,[2]),ins(303,[0,0]),ins(500,[bits(32),bits(32)]),ins(507,[0,2]),ins(600,[0]),ins(602,[0,5,3]),ins(604,[0,bits(0),bits(.0625)]),ins(605,[0,bits(1.25),bits(.25)]),ins(606,[0,3,2]),ins(608,[0,-1,-1]),ins(601,[0]),ins(700,[0,bits(0),bits(160),bits(560),bits(12)]),ins(701,[0,12,16,180,16,0]),ins(703,[0,1234],0,24),ins(601,[0],0,40),ins(601,[0],0,80),ins(10,[],0,100000)])});
 for(let character=0;character<4;character++){const anm=c.anm_manager_create(),program=c.program_create(),pp=c.allocate(bytes.length),sht=c.sht_create(),name=c.allocate(5),request=c.allocate(84),pos=c.allocate(12);let battle=0;const dv=()=>new DataView(c.memory.buffer);
  const load=(name,id)=>{const b=readFileSync(resolve(root,'reference/assets',name)),p=c.allocate(b.length);memory(c,p,b.length).set(b);assert.equal(c.anm_manager_load(anm,id,p,b.length),1,string(c,c.anm_manager_error(anm)));c.release(p);};
  try{load('ascii.anm',2);assert.equal(c.anm_manager_fallback(anm,2),1);load('enemy.anm',1);load('effect.anm',8);load('bullet.anm',7);load('pl0'+character+'.anm',9+character);const sb=readFileSync(resolve(root,'reference/assets/pl0'+character+'.sht')),sp=c.allocate(sb.length);memory(c,sp,sb.length).set(sb);assert.equal(c.sht_open(sht,sp,sb.length),1);c.release(sp);memory(c,pp,bytes.length).set(bytes);assert.equal(c.program_attach(program,pp,bytes.length),0);battle=c.game_battle_create(anm,program,sht,character);assert.equal(c.game_battle_initialize(battle),1,string(c,c.game_battle_error(battle)));dv().setInt32(c.game_battle_field(battle,0),1,true);dv().setInt32(c.game_battle_field(battle,5)+4,10000,true);dv().setInt32(c.game_battle_field(battle,5)+8,10000,true);memory(c,name,5).set(Buffer.from('main\0'));const r=Buffer.alloc(84);r.writeFloatLE(0);r.writeFloatLE(144,4);r.writeInt32LE(10000,20);memory(c,request,84).set(r);assert.equal(c.game_battle_spawn(battle,name,request),1,string(c,c.game_battle_error(battle)));assert.equal(c.game_battle_enemy_count(battle),1);let bulletsSeen=false,lasersSeen=false,itemsSeen=false;
   const step=(held=1,pressed=0,flags=0,rate=1,frameFlags=1)=>{assert.equal(c.game_battle_step(battle,held,pressed,flags,rate,frameFlags),1,string(c,c.game_battle_error(battle)));assert.equal(string(c,c.game_battle_error(battle)),'');bulletsSeen||=c.game_battle_bullet_count(battle)>0;lasersSeen||=c.game_battle_laser_count(battle)>0;itemsSeen||=c.game_battle_item_count(battle)>0;frames++;};
   for(let frame=0;frame<120;frame++)step();assert.ok(bulletsSeen,'ECL creates actual bullet objects');assert.ok(lasersSeen,'ECL creates actual warning and active laser objects');assert.ok(c.game_battle_enemy_life(battle,1)<10000,'real PlayerShots damage reaches enemy life');damageCases++;
   // Real pause wrapper skips enemy logic while the player callback is disabled.
   const life=c.game_battle_enemy_life(battle,1),timer=Buffer.from(memory(c,c.game_battle_field(battle,6),20));for(let i=0;i<4;i++)step(0,0,7,1,1|8|16|32|64);assert.equal(c.game_battle_enemy_life(battle,1),life);assert.deepEqual(Buffer.from(memory(c,c.game_battle_field(battle,6),20)),timer);
   // A real expanding damage source kills the target over later frames.
   dv().setFloat32(pos,0,true);dv().setFloat32(pos+4,144,true);dv().setFloat32(pos+8,0,true);const damage=c.game_battle_damage(battle);assert.ok(c.damage_sources_circle(damage,pos,64,0,400,1000)>0);for(let i=0;i<250&&c.game_battle_enemy_count(battle);i++)step();assert.equal(c.game_battle_enemy_count(battle),0,'enemy manager removes the dead enemy');deathCases++;dv().setInt32(c.game_battle_field(battle,0),1,true);c.timer_action(c.game_battle_field(battle,14),0,600,1,0);for(let i=0;i<240;i++)step(0x10);assert.ok(itemsSeen,'death creates real collectible items');assert.equal(c.game_battle_item_count(battle),0,'item collection or original offscreen retirement completes');
   // Start each actual character bomb through the player input and callback order.
   // The original bomb gate requires a live enemy manager entry.
   assert.equal(c.game_battle_spawn(battle,name,request),1,string(c,c.game_battle_error(battle)));
   dv().setInt32(c.game_battle_field(battle,0),1,true);const before=dv().getInt32(c.game_battle_field(battle,3)+36,true);step(0,2);assert.equal(dv().getInt32(c.game_battle_field(battle,3)+20,true),1,'bomb session active');assert.equal(dv().getInt32(c.game_battle_field(battle,3)+36,true),before-1,'bomb stock used');for(let i=0;i<48;i++)step(0);assert.ok(dv().getInt32(c.game_battle_field(battle,9)+4,true)>0,'bomb frame advances');bombCases++;checks+=12;
   // World presentation failures must stop the frame and stay visible.
   c.game_battle_audio_available(battle,0);assert.equal(c.game_battle_step(battle,0,0,0,1,0),0);assert.match(string(c,c.game_battle_error(battle)),/audio/i);assert.equal(c.game_battle_step(battle,0,0,0,1,0),0);checks+=3;
  }finally{if(battle)c.game_battle_delete(battle);c.release(pp);c.release(name);c.release(request);c.release(pos);c.sht_delete(sht);c.program_delete(program);c.anm_manager_delete(anm);}
 }
 report('game-battle-integration',{passed:true,characters:4,frames,damageCases,deathCases,bombCases,checks,scope:'Headless integration of real Player, all BombControllers, EnemyManager/EnemyDamage/EnemyDeath, BulletScene, LaserScene, ItemManager/ItemCollection and both ANM queues. Synthetic ECL drives real projectiles; real player shots change life, lethal damage creates actual drops, and input starts bombs. Service failures propagate. Individual modules and scheduler have native comparisons; this test is not an original full stage/replay or GPU visual comparison. Presentation, stage/session and special enemy services are explicit fixture boundaries.'});
});
