import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {resolve} from 'node:path';import {core,oracle,memory,string,root,report,enableNativeMath} from './helpers.mjs';import {resourceLoader,nativePool,prepareBank,nativeInstances,compareAnm} from './anm-oracle.mjs';
test('TH15 spell capture/failure and item notices preserve original animation trees, leading zeros, comma digits and repeated replacement',async()=>{
 const c=await core(),m=await oracle();enableNativeMath(m);const loader=resourceLoader(m),base=m.heap;let calls=0,frames=0,checks=0;
 try{for(let sample=0;sample<16;sample++){
 m.heap=base;m.view(m.heap,0x1caf980).fill(0);const am=c.anm_manager_create(),nm=nativePool(m),owner=m.allocate(0x2d4),text=m.allocate(0x19270),f=c.game_hud_create(am,5,2,6);try{
 m.view(owner,0x2d4).fill(0);m.view(text,0x19270).fill(0);m.u32(0x4e9a8c,owner);m.u32(0x4e9a58,text);m.u32(0x4ca620,0x4e73e8);m.f32(0x4e73e8,1);m.u32(0x4e9a40,0);m.u32(0x4e9a44,0);
 for(const[name,id]of[['ascii.anm',2],['front.anm',5]]){const b=readFileSync(resolve(root,'reference/assets',name)),p=c.allocate(b.length);memory(c,p,b.length).set(b);assert.equal(c.anm_manager_load(am,id,p,b.length),1,string(c,c.anm_manager_error(am)));c.release(p);const bank=prepareBank(m,loader,name,b,nm,id);if(id===2){c.anm_manager_fallback(am,id);m.u32(text+0x19258,bank);}else m.u32(owner+0x2c8,bank);}
 const compare=label=>{for(const[cp,np,n,what]of[[c.game_hud_lifecycle_field(f,0),owner+0xa0,40,'digits'],[c.game_hud_lifecycle_field(f,1),owner+0xc8,8,'banners'],[c.game_hud_frame_field(f,8),owner+0x118,4,'time notice'],[c.game_hud_frame_field(f,9),owner+0x13c,4,'time state']]){assert.deepEqual(Buffer.from(memory(c,cp,n)),Buffer.from(m.bytes(np,n)),label+' '+what);checks++;}for(let alt=0;alt<2;alt++){const list=nativeInstances(m,nm,alt);assert.equal(c.anm_manager_count(am,alt),list.length,label+' queue');for(let i=0;i<list.length;i++){const h=m.u32(list[i]+0x544);assert.equal(c.anm_manager_order(am,alt,i),h,label+' order');const vm=c.anm_manager_find(am,h);compareAnm(c,m,vm,list[i],label+' VM '+i);assert.deepEqual(Buffer.from(memory(c,c.anm_vm_translation(vm),12)),Buffer.from(m.bytes(list[i]+0x5ec,12)),label+' translation');assert.equal(c.anm_vm_pending_interrupt(vm),m.i32(list[i]+0x49c),label+' interrupt');checks++;}}assert.deepEqual(Buffer.from(memory(c,c.anm_manager_random(am),8)),Buffer.from(m.bytes(0x4e9a40,8)),label+' RNG');};
 const values=[0,10,990,1000,999990,1000000,12345678,99999999],rate=[1,.5,1.25,.25][sample%4];assert.equal(c.anm_manager_update(am,0,rate),1);m.f32(0x4e73e8,rate);
 for(let frame=0;frame<128;frame++){if(frame%4===0){const kind=(frame/4+sample)%7,value=values[Math.floor(frame/4+sample)%values.length];assert.equal(c.game_hud_notification(f,value,kind),1,sample+'/'+frame+' '+string(c,c.game_hud_error(f)));m.call(0x439d60,{ecx:owner,args:[value,kind]});compare(sample+'/'+frame+' notice');calls++;}for(let alt=0;alt<2;alt++){assert.equal(c.anm_manager_update(am,alt,rate),1,string(c,c.anm_manager_error(am)));m.call(alt?0x487890:0x487740,{ecx:nm});}compare(sample+'/'+frame+' animation');frames++;}
 }finally{c.game_hud_delete(f);c.anm_manager_delete(am);}}
 report('game-hud-notifications',{passed:true,calls,frames,checks,originalFunction:'0x439d60',scope:'All seven original notification kinds, including the no-op slot, with real front/ascii ANM. Capture/failure overlays, eight score digits, leading-zero visibility, comma thresholds, time notice, item notices, replacement ordering, inherited rate and both animation queues checked. Full session and browser pixels remain separate.'});
 }finally{m.close();}
});
