import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {resolve} from 'node:path';import {core,oracle,memory,string,root,report,enableNativeMath} from './helpers.mjs';import {resourceLoader,nativePool,nativeInstances,prepareBank,compareAnm} from './anm-oracle.mjs';
test('TH15 original item pools preserve allocation, reuse, delays, piece cycling and real animation binding',async()=>{
 const c=await core(),m=await oracle(),manager=c.anm_manager_create(),nativeManager=nativePool(m),loader=resourceLoader(m),native=m.allocate(0x1cbbde8),bulletBankSlot=m.allocate(4),bullet=bulletBankSlot-0x141f0d8,effects=m.allocate(0x1100),text=m.allocate(0x19270),position=m.allocate(12);enableNativeMath(m);m.u32(0x4e9a9c,native);m.u32(0x4e9a6c,bullet);m.u32(0x4e9a78,effects);m.u32(0x4e9a58,text);m.u32(0x4ca620,0x4e73e8);m.f32(0x4e73e8,1);let fixture,sounds=[],requests=0,reuses=0,falling=0,checks=0;
 m.replace(0x476360,'item piece audio request',()=>{sounds.push(m.i32(m.reg('ESP')+4));return 0;},2);const bits=f=>{const b=Buffer.alloc(4);b.writeFloatLE(f);return b.readUInt32LE();},nativeItem=id=>native+16+(id-1)*0xc88,idOf=p=>p?(p-native-16)/0xc88+1:0,equal=(a,b,label)=>{if(!a.equals(b)){let i=0;while(i<a.length&&a[i]===b[i])i++;assert.fail(label+' byte '+i.toString(16)+' actual='+a.subarray(Math.max(0,i-4),i+12).toString('hex')+' original='+b.subarray(Math.max(0,i-4),i+12).toString('hex'));}};
 const load=(name,id)=>{const bytes=readFileSync(resolve(root,'reference/assets',name)),p=c.allocate(bytes.length);memory(c,p,bytes.length).set(bytes);assert.equal(c.anm_manager_load(manager,id,p,bytes.length),1,string(c,c.anm_manager_error(manager)));c.release(p);return prepareBank(m,loader,name,bytes,nativeManager,id);};const check=label=>{const dv=new DataView(c.memory.buffer);for(const [field,no]of [[0,0x1cbbddc],[1,0x1cbbde0],[2,0x1cbbde4],[4,0x1cbbdd8]])assert.equal(dv.getInt32(c.item_manager_field(fixture,field),true),m.i32(native+no),label+' counter '+field);assert.equal(dv.getInt32(c.item_manager_field(fixture,3),true),m.i32(0x4e7480));for(let cancel=0;cancel<2;cancel++)assert.equal(c.item_manager_free(fixture,cancel),idOf(m.u32(native+(cancel?0xe5dee4:0xe5ded4))),label+' free '+cancel);for(const [field,at]of [[6,0x4e9a48],[7,0x4e9a40]])equal(Buffer.from(memory(c,c.item_manager_field(fixture,field),8)),Buffer.from(m.bytes(at,8)),label+' RNG');assert.deepEqual(Array.from(new Int32Array(c.memory.buffer,c.item_manager_sounds(fixture),c.item_manager_sound_count(fixture))),sounds,label+' sounds');checks+=10;};
 const spawn=(kind,sample)=>{const pos=[Math.fround((sample%43-21)*17.25),Math.fround((sample%17)*24.125),Math.fround((sample%3-1)*.0625)],angle=Math.fround((sample%33-16)*.125),speed=Math.fround((sample%13)*.25),density=[0,255,256,511,512,1023,1024,4096][sample%8];let dv=new DataView(c.memory.buffer);dv.setInt32(c.item_manager_field(fixture,1),density,true);dv.setInt32(c.item_manager_field(fixture,2),sample,true);m.i32(native+0x1cbbde0,density);m.i32(native+0x1cbbde4,sample);for(let i=0;i<3;i++)m.f32(position+i*4,pos[i]);const expected=idOf(m.call(0x4408d0,{args:[kind,position,0,bits(angle),bits(speed),0]})),actual=c.item_manager_spawn(fixture,kind,...pos,angle,speed);assert.equal(actual,expected,'spawn '+kind+'/'+sample+' '+string(c,c.item_manager_error(fixture)));assert.equal(string(c,c.item_manager_error(fixture)),'');if(actual){const item=nativeItem(actual);equal(Buffer.from(memory(c,c.item_manager_state(fixture,actual),104)),Buffer.from(m.bytes(item+0xc20,104)),'item '+kind+'/'+sample);if(![9,10,11,13].includes(kind)){compareAnm(c,m,c.item_manager_vm(fixture,actual,0),item+16,'body '+kind+'/'+sample);compareAnm(c,m,c.item_manager_vm(fixture,actual,1),item+0x618,'arrow '+kind+'/'+sample);}}check('spawn '+sample);requests++;return actual;};
 try{const ascii=load('ascii.anm',2);assert.equal(c.anm_manager_fallback(manager,2),1);m.u32(text+0x19258,ascii);m.u32(effects+12,load('effect.anm',8));m.u32(bullet+0x141f0d8,load('bullet.anm',0));fixture=c.item_manager_create(manager,0);m.call(0x421230,{ecx:native});m.i32(0x4e7480,0);for(const [field,at]of [[6,0x4e9a48],[7,0x4e9a40]]){const b=Buffer.alloc(8);b.writeUInt16LE(2717+field*137);m.write(at,b);memory(c,c.item_manager_field(fixture,field),8).set(b);}check('reset');
 const ordinary=[];for(let i=0;i<600;i++)ordinary.push(spawn([1,2,3,4,5,6,7,8,12][i%9],i));assert.equal(spawn(1,600),0);for(let i=0;i<64;i++){const id=ordinary[i];m.call(0x440dc0,{ecx:nativeItem(id)});assert.equal(c.item_manager_release(fixture,id),1);check('release '+i);assert.equal(spawn(i%2?12:3,601+i),id);reuses++;}
 const cancelled=[];for(let i=0;i<4096;i++)cancelled.push(spawn([9,10,11,13][i%4],1000+i));assert.equal(spawn(9,6000),0);for(let i=0;i<32;i++){const id=cancelled[i];m.call(0x440bf0,{ecx:nativeItem(id)});assert.equal(c.item_manager_falling(fixture,id),1,string(c,c.item_manager_error(fixture)));equal(Buffer.from(memory(c,c.item_manager_state(fixture,id),104)),Buffer.from(m.bytes(nativeItem(id)+0xc20,104)),'falling '+i);compareAnm(c,m,c.item_manager_vm(fixture,id,0),nativeItem(id)+16,'falling body '+i);falling++;m.call(0x440dc0,{ecx:nativeItem(id)});assert.equal(c.item_manager_release(fixture,id),1);check('cancel recycle '+i);assert.equal(spawn([9,10,11,13][i%4],7000+i),id);reuses++;}
 for(let alt=0;alt<2;alt++){const list=nativeInstances(m,nativeManager,alt);assert.equal(c.anm_manager_count(manager,alt),list.length);for(let i=0;i<list.length;i++){const h=m.u32(list[i]+0x544);assert.equal(c.anm_manager_order(manager,alt,i),h);compareAnm(c,m,c.anm_manager_find(manager,h),list[i],'piece effect '+h);checks++;}}

 let resets=0;for(let cycle=0;cycle<3;cycle++){
  const dv=new DataView(c.memory.buffer);dv.setInt32(c.item_manager_field(fixture,1),321+cycle,true);m.i32(native+0x1cbbde0,321+cycle);dv.setInt32(c.item_manager_field(fixture,4),111+cycle,true);m.i32(native+0x1cbbdd8,111+cycle);dv.setFloat32(c.item_manager_field(fixture,5),2.5+cycle,true);m.f32(native+0xe5def0,2.5+cycle);
  m.call(0x421230,{ecx:native});assert.equal(c.item_manager_reset(fixture),1,string(c,c.item_manager_error(fixture)));check('scene reset '+cycle);assert.equal(new DataView(c.memory.buffer).getFloat32(c.item_manager_field(fixture,5),true),m.f32(native+0xe5def0));
  for(let id=1;id<=4696;id++){equal(Buffer.from(memory(c,c.item_manager_state(fixture,id),104)),Buffer.from(m.bytes(nativeItem(id)+0xc20,104)),'reset item '+cycle+'/'+id);assert.equal(c.item_manager_vm(fixture,id,0),0);assert.equal(c.item_manager_vm(fixture,id,1),0);checks++;}
  for(let i=0;i<24;i++)spawn([1,2,3,4,6,12,9,10,11,13][i%10],cycle*100+i);resets++;
 }
 report('item-pool-generation',{passed:true,ordinarySlots:600,cancelSlots:4096,requests,reuses,falling,resets,checks,originalFunctions:['0x421230','0x4408d0','0x440dc0','0x440bf0','0x440c60','0x440f30'],scope:'Actual fixed ordinary/cancellation pools, full-pool rejection, original free-slot order/reuse, delays/density, alternating life/bomb pieces, spawn motion and original bullet/effect ANM binding. Repeated scene-entry resets also compare every item state, counter retention, motion scale and rebuilt allocation order. Item frame movement, collection/scoring and chapter snapshots remain separate integration.'});}finally{if(fixture)c.item_manager_delete(fixture);c.anm_manager_delete(manager);m.close();}
});
