import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {resolve} from 'node:path';import {core,oracle,memory,string,root,report,enableNativeMath} from './helpers.mjs';import {resourceLoader,nativePool,nativeInstances,prepareBank,compareAnm} from './anm-oracle.mjs';
test('TH15 item chapter snapshots match original full pools, rebuilt free order, embedded VM timers and outside counters',async()=>{
 const c=await core(),m=await oracle(),manager=c.anm_manager_create(),nativeManager=nativePool(m),loader=resourceLoader(m),native=m.allocate(0x1cbbde8),bulletBankSlot=m.allocate(4),bullet=bulletBankSlot-0x141f0d8,effects=m.allocate(0x1100),text=m.allocate(0x19270),position=m.allocate(12),file=c.player_checkpoint_file_create(),fileInput=c.allocate(16*1024*1024),nativeFile=m.allocate(16*1024*1024),used=m.allocate(4);enableNativeMath(m);m.u32(0x4e9a9c,native);m.u32(0x4e9a6c,bullet);m.u32(0x4e9a78,effects);m.u32(0x4e9a58,text);m.u32(0x4ca620,0x4e73e8);m.f32(0x4e73e8,1);let fixture,saved=0,sounds=[],requests=0,reuses=0,falling=0,checks=0;
 m.replace(0x476360,'item piece audio request',()=>{sounds.push(m.i32(m.reg('ESP')+4));return 0;},2);const bits=f=>{const b=Buffer.alloc(4);b.writeFloatLE(f);return b.readUInt32LE();},nativeItem=id=>native+16+(id-1)*0xc88,idOf=p=>p?(p-native-16)/0xc88+1:0,equal=(a,b,label)=>{if(!a.equals(b)){let i=0;while(i<a.length&&a[i]===b[i])i++;assert.fail(label+' byte '+i.toString(16)+' actual='+a.subarray(Math.max(0,i-4),i+12).toString('hex')+' original='+b.subarray(Math.max(0,i-4),i+12).toString('hex'));}};
 const load=(name,id)=>{const bytes=readFileSync(resolve(root,'reference/assets',name)),p=c.allocate(bytes.length);memory(c,p,bytes.length).set(bytes);assert.equal(c.anm_manager_load(manager,id,p,bytes.length),1,string(c,c.anm_manager_error(manager)));c.release(p);return prepareBank(m,loader,name,bytes,nativeManager,id);};const check=label=>{const dv=new DataView(c.memory.buffer);for(const [field,no]of [[0,0x1cbbddc],[1,0x1cbbde0],[2,0x1cbbde4],[4,0x1cbbdd8]])assert.equal(dv.getInt32(c.item_manager_field(fixture,field),true),m.i32(native+no),label+' counter '+field);assert.equal(dv.getInt32(c.item_manager_field(fixture,3),true),m.i32(0x4e7480));for(let cancel=0;cancel<2;cancel++)assert.equal(c.item_manager_free(fixture,cancel),idOf(m.u32(native+(cancel?0xe5dee4:0xe5ded4))),label+' free '+cancel);for(const [field,at]of [[6,0x4e9a48],[7,0x4e9a40]])equal(Buffer.from(memory(c,c.item_manager_field(fixture,field),8)),Buffer.from(m.bytes(at,8)),label+' RNG');assert.deepEqual(Array.from(new Int32Array(c.memory.buffer,c.item_manager_sounds(fixture),c.item_manager_sound_count(fixture))),sounds,label+' sounds');checks+=10;};
 const spawn=(kind,sample)=>{const pos=[Math.fround((sample%43-21)*17.25),Math.fround((sample%17)*24.125),Math.fround((sample%3-1)*.0625)],angle=Math.fround((sample%33-16)*.125),speed=Math.fround((sample%13)*.25),density=[0,255,256,511,512,1023,1024,4096][sample%8];let dv=new DataView(c.memory.buffer);dv.setInt32(c.item_manager_field(fixture,1),density,true);dv.setInt32(c.item_manager_field(fixture,2),sample,true);m.i32(native+0x1cbbde0,density);m.i32(native+0x1cbbde4,sample);for(let i=0;i<3;i++)m.f32(position+i*4,pos[i]);const expected=idOf(m.call(0x4408d0,{args:[kind,position,0,bits(angle),bits(speed),0]})),actual=c.item_manager_spawn(fixture,kind,...pos,angle,speed);assert.equal(actual,expected,'spawn '+kind+'/'+sample+' '+string(c,c.item_manager_error(fixture)));assert.equal(string(c,c.item_manager_error(fixture)),'');if(actual){const item=nativeItem(actual);equal(Buffer.from(memory(c,c.item_manager_state(fixture,actual),104)),Buffer.from(m.bytes(item+0xc20,104)),'item '+kind+'/'+sample);if(![9,10,11,13].includes(kind)){compareAnm(c,m,c.item_manager_vm(fixture,actual,0),item+16,'body '+kind+'/'+sample);compareAnm(c,m,c.item_manager_vm(fixture,actual,1),item+0x618,'arrow '+kind+'/'+sample);}}check('spawn '+sample);requests++;return actual;};
 try{const ascii=load('ascii.anm',2);assert.equal(c.anm_manager_fallback(manager,2),1);m.u32(text+0x19258,ascii);m.u32(effects+12,load('effect.anm',8));m.u32(bullet+0x141f0d8,load('bullet.anm',0));fixture=c.item_manager_create(manager,0);saved=c.item_checkpoint_create(fixture);m.call(0x421230,{ecx:native});m.i32(0x4e7480,0);for(const [field,at]of [[6,0x4e9a48],[7,0x4e9a40]]){const b=Buffer.alloc(8);b.writeUInt16LE(2717+field*137);m.write(at,b);memory(c,c.item_manager_field(fixture,field),8).set(b);}check('reset');
 const ordinary=[];for(let i=0;i<600;i++)ordinary.push(spawn([1,2,3,4,5,6,7,8,12][i%9],i));assert.equal(spawn(1,600),0);for(let i=0;i<64;i++){const id=ordinary[i];m.call(0x440dc0,{ecx:nativeItem(id)});assert.equal(c.item_manager_release(fixture,id),1);check('release '+i);assert.equal(spawn(i%2?12:3,601+i),id);reuses++;}
 const cancelled=[];for(let i=0;i<4096;i++)cancelled.push(spawn([9,10,11,13][i%4],1000+i));assert.equal(spawn(9,6000),0);for(let i=0;i<32;i++){const id=cancelled[i];m.call(0x440bf0,{ecx:nativeItem(id)});assert.equal(c.item_manager_falling(fixture,id),1,string(c,c.item_manager_error(fixture)));equal(Buffer.from(memory(c,c.item_manager_state(fixture,id),104)),Buffer.from(m.bytes(nativeItem(id)+0xc20,104)),'falling '+i);compareAnm(c,m,c.item_manager_vm(fixture,id,0),nativeItem(id)+16,'falling body '+i);falling++;m.call(0x440dc0,{ecx:nativeItem(id)});assert.equal(c.item_manager_release(fixture,id),1);check('cancel recycle '+i);assert.equal(spawn([9,10,11,13][i%4],7000+i),id);reuses++;}
 for(let cycle=0;cycle<6;++cycle){
  m.f32(native+0xe5def0,.375+cycle*.0625);new DataView(c.memory.buffer).setFloat32(c.item_manager_field(fixture,5),.375+cycle*.0625,true);
  for(let i=0;i<32;i++){const id=ordinary[i],vm=c.item_manager_vm(fixture,id,0);new DataView(c.memory.buffer).setFloat32(c.anm_vm_timer(vm)+8,41.625+i,true);new DataView(c.memory.buffer).setInt32(c.anm_vm_timer(vm)+4,41+i,true);m.f32(nativeItem(id)+16+0x554,41.625+i);m.i32(nativeItem(id)+16+0x550,41+i);}
  assert.equal(c.item_checkpoint_capture(saved),1,string(c,c.item_checkpoint_error(saved)));m.call(0x492870,{args:[native+0xe5def4,native+16,0xe5dee4]});
  for(let id=1;id<=4696;id++){equal(Buffer.from(memory(c,c.item_checkpoint_state(saved,id),104)),Buffer.from(m.bytes(nativeItem(id)+0xc20+0xe5dee4,104)),'saved '+cycle+'/'+id);for(let arrow=0;arrow<2;arrow++){const vm=c.item_checkpoint_vm(saved,id,arrow);if(vm)compareAnm(c,m,vm,nativeItem(id)+(arrow?0x618:16)+0xe5dee4,'saved animation '+cycle+'/'+id+'/'+arrow);}}
  if([0,3,5].includes(cycle)){
   assert.equal(c.item_checkpoint_file_write(file,saved,manager),1,string(c,c.item_checkpoint_error(saved)));m.u32(used,0);m.call(0x412e70,{args:[nativeFile,used],limit:100000000});const original=Buffer.from(m.bytes(nativeFile,m.u32(used))),encoded=Buffer.from(memory(c,c.player_checkpoint_file_bytes(file),c.player_checkpoint_file_size(file)));assert.equal(encoded.length,original.length);let at=0;for(let group=0;group<2;group++){const count=original.readUInt32LE(at);assert.equal(encoded.readUInt32LE(at),count);at+=4;for(let n=0;n<count;n++){equal(encoded.subarray(at+0xc20,at+0xc88),original.subarray(at+0xc20,at+0xc88),'item file state '+cycle+'/'+group+'/'+n);for(const base of [0x10,0x618])for(const [off,len]of [[0,0x28],[0x28,12],[0x34,0x500],[0x54c,0x28],[0x5c0,4],[0x5c8,4],[0x5ec,12]])equal(encoded.subarray(at+base+off,at+base+off+len),original.subarray(at+base+off,at+base+off+len),'item file animation '+cycle+'/'+group+'/'+n+'/'+base+'/'+off);at+=0xc88;}}assert.equal(at,encoded.length);
   memory(c,fileInput,original.length).set(original);assert.equal(c.item_checkpoint_file_read(file,saved,fileInput,original.length-1,manager),0);assert.equal(c.player_checkpoint_file_consumed(file),0);assert.equal(c.item_checkpoint_file_read(file,saved,fileInput,original.length,manager),1,string(c,c.item_checkpoint_error(saved)));assert.equal(c.player_checkpoint_file_consumed(file),original.length);m.u32(used,0);m.call(0x413010,{args:[nativeFile,used],limit:100000000});assert.equal(m.u32(used),original.length);checks+=7;
  }
  for(let i=0;i<32;i++){const id=ordinary[i];m.call(0x440dc0,{ecx:nativeItem(id)});assert.equal(c.item_manager_release(fixture,id),1);spawn(i%2?12:3,9100+cycle*100+i);}
  for(const [field,at]of [[0,0x1cbbddc],[1,0x1cbbde0],[2,0x1cbbde4],[4,0x1cbbdd8]]){const value=cycle*211+field+93;new DataView(c.memory.buffer).setInt32(c.item_manager_field(fixture,field),value,true);m.i32(native+at,value);}m.f32(native+0xe5def0,9);new DataView(c.memory.buffer).setFloat32(c.item_manager_field(fixture,5),9,true);
  assert.equal(c.item_checkpoint_restore(saved),1,string(c,c.item_checkpoint_error(saved)));m.call(0x43baa0,{limit:100000000});check('restore '+cycle);assert.equal(new DataView(c.memory.buffer).getFloat32(c.item_manager_field(fixture,5),true),m.f32(native+0xe5def0));
  for(let id=1;id<=4696;id++){equal(Buffer.from(memory(c,c.item_manager_state(fixture,id),104)),Buffer.from(m.bytes(nativeItem(id)+0xc20,104)),'restored '+cycle+'/'+id);for(let arrow=0;arrow<2;arrow++){const vm=c.item_manager_vm(fixture,id,arrow);if(vm)compareAnm(c,m,vm,nativeItem(id)+(arrow?0x618:16),'restored animation '+cycle+'/'+id+'/'+arrow);}checks++;}
 }
 for(let alt=0;alt<2;alt++){const list=nativeInstances(m,nativeManager,alt);assert.equal(c.anm_manager_count(manager,alt),list.length);for(let i=0;i<list.length;i++){const h=m.u32(list[i]+0x544);assert.equal(c.anm_manager_order(manager,alt,i),h);compareAnm(c,m,c.anm_manager_find(manager,h),list[i],'piece effect '+h);checks++;}}
 report('item-checkpoint',{passed:true,ordinarySlots:600,cancelSlots:4096,requests,reuses,falling,checks,originalFunctions:['0x421230','0x4408d0','0x440dc0','0x440bf0','0x440c60','0x440f30'],cycles:6,scope:'Original 412e70/413010 file encoding/import of all 4696 slots, animation records and truncation guards at three cycles; raw copied item block and 43baa0 restore, six full-pool save/modify/restore cycles including fractional VM timers, preserved pool-external request/density/stamp counters and free-list reconstruction. Actual fixed ordinary/cancellation pools, full-pool rejection, original free-slot order/reuse, delays/density, alternating life/bomb pieces, spawn motion and original bullet/effect ANM binding. Item frame movement, collection/scoring and chapter snapshots remain separate integration.'});}finally{c.player_checkpoint_file_delete(file);c.release(fileInput);if(saved)c.item_checkpoint_delete(saved);if(fixture)c.item_manager_delete(fixture);c.anm_manager_delete(manager);m.close();}
});
