import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {resolve} from 'node:path';import {core,oracle,memory,string,root,report,enableNativeMath} from './helpers.mjs';import {resourceLoader,nativePool,prepareBank,compareAnm} from './anm-oracle.mjs';
test('TH15 moving and stationary laser animations preserve original bindings, colors and real frame updates',async()=>{
 const c=await core(),m=await oracle(),manager=c.anm_manager_create(),nm=nativePool(m),loader=resourceLoader(m),native=m.allocate(0x1b44),lasers=m.allocate(0x610),request=m.allocate(0x378),text=m.allocate(0x19270);enableNativeMath(m);m.u32(0x4e9ba0,lasers);m.u32(0x4e9a58,text);m.u32(0x4ca620,0x4e73e8);m.f32(0x4e73e8,1);m.replace(0x476400,'observe laser spawn audio boundary',()=>0,1);m.replace(0x443640,'observe moving-laser collision boundary',()=>0,1);m.replace(0x445b50,'observe stationary-laser collision boundary',()=>0,1);let cases=0,frames=0,checks=0;
 const load=(name,id)=>{const bytes=readFileSync(resolve(root,'reference/assets',name)),p=c.allocate(bytes.length);memory(c,p,bytes.length).set(bytes);assert.equal(c.anm_manager_load(manager,id,p,bytes.length),1,string(c,c.anm_manager_error(manager)));c.release(p);return prepareBank(m,loader,name,bytes,nm,id);};
 const same=(cp,np,n,label)=>assert.deepEqual(Buffer.from(memory(c,cp,n)),Buffer.from(m.bytes(np,n)),label);
 try{m.u32(text+0x19258,load('ascii.anm',2));assert.equal(c.anm_manager_fallback(manager,2),1);m.u32(lasers+0x604,load('bullet.anm',9));
 for(let moving=0;moving<2;moving++)for(let type=0;type<44;type++)for(let color=0;color<16;color++){const f=c.laser_visual_create(manager,9),motion=moving?c.laser_motion_create():c.laser_stationary_create(),field=(index)=>(moving?c.laser_motion_field:c.laser_stationary_field)(motion,index),set=(index,value)=>new DataView(c.memory.buffer).setFloat32(field(index),value,true),label=moving+'/'+type+'/'+color;try{
 m.view(native,0x1b44).fill(0);m.view(request,0x378).fill(0);m.call(moving?0x441300:0x441b20,{ecx:native});m.i32(request+(moving?0x24:0x54),type);m.i32(request+(moving?0x28:0x58),color);m.i32(request+(moving?0x350:0x40),-1);m.f32(request+0xc,moving?.7:0);m.f32(request+(moving?0x10:0x20),128);m.f32(request+(moving?0x14:0x24),36);m.f32(request+(moving?0x20:0x2c),2);if(!moving){m.f32(request+0x18,.7);m.f32(request+0x28,16);for(const [o,n]of [[0x30,5],[0x34,15],[0x38,30],[0x3c,10]])m.i32(request+o,n);}else m.f32(request+0x1c,16);
 m.f32(0x4e73e8,1);assert.equal(m.call(moving?0x441ed0:0x445590,{ecx:native,args:[request]}),0);assert.equal(c.laser_visual_initialize(f,moving,type,color),1,string(c,c.laser_visual_error(f)));for(let i=0;i<(moving?3:2);i++)compareAnm(c,m,c.laser_visual_vm(f,i),native+(moving?[0x92c,0xf34,0x153c]:[0x950,0xf58])[i],label+' initialize '+i);
 set(2,.7);set(3,36);set(4,moving?16:2);set(5,2);set(7,128);if(moving){c.laser_motion_velocity(motion);for(const [index,o,n]of [[9,0x5a0,9999],[10,0x5b4,3],[11,0x40,0]]){const timer=Buffer.alloc(20);timer.writeInt32LE(n-1);timer.writeInt32LE(n,4);timer.writeFloatLE(n,8);timer.writeUInt32LE(1,16);memory(c,field(index),20).set(timer);m.write(native+o,timer);}}else{set(8,16);for(const [i,n]of [[11,5],[12,15],[13,30],[14,10]])new DataView(c.memory.buffer).setInt32(field(i),n,true);m.u32(lasers+0x14,native);m.u32(lasers+0x5e0,native);m.u32(lasers+0x5e4,1);m.u32(native+4,lasers+12);}
 const rate=[1,.5,.25,1.25][color%4];m.f32(0x4e73e8,rate);for(let frame=0;frame<32;frame++){const ended=moving?c.laser_motion_update(motion,rate):c.laser_stationary_update(motion,rate,0);assert.equal(ended,0,label+' motion');const dv=new DataView(c.memory.buffer),width=dv.getFloat32(field(4),true),length=dv.getFloat32(field(3),true),traveled=moving?dv.getFloat32(field(6),true):0;assert.equal(c.laser_visual_update(f,width,length,traveled,moving,rate),1,string(c,c.laser_visual_error(f)));assert.equal(m.call(moving?0x4430e0:0x4417e0,{ecx:moving?native:lasers}),moving?0:1,label+' native frame');same(field(0),native+0x54,12,label+' motion position');same(field(3),native+0x70,4,label+' motion length');same(field(4),native+0x74,4,label+' motion width');for(let i=0;i<(moving?3:2);i++){const np=native+(moving?[0x92c,0xf34,0x153c]:[0x950,0xf58])[i];compareAnm(c,m,c.laser_visual_vm(f,i),np,label+'/'+frame+' VM '+i);assert.equal(c.anm_vm_pending_interrupt(c.laser_visual_vm(f,i)),m.i32(np+0x49c),label+' interrupt');}frames++;checks+=6;}cases++;
 }finally{c.laser_visual_delete(f);if(moving)c.laser_motion_delete(motion);else c.laser_stationary_delete(motion);}}
 report('laser-real-animations',{passed:true,cases,frames,checks,originalFunctions:['0x441ed0','0x445590','0x4430e0','0x445830','0x4417e0','0x442330','0x477e10'],scope:'All 44 sprite kinds and 16 colors for moving and stationary lasers: unchanged original initialization/frame functions, actual bullet ANM scripts and templates, color source, body/head/tip lifecycles, blend/draw flags and scaling integrated with verified laser motion at four rates. Audio/collision observed at boundaries; advanced transforms, actual GPU drawing and complete world remain separate.'});
 }finally{c.anm_manager_delete(manager);m.close();}
});
