import test from 'node:test';import assert from 'node:assert/strict';import{readFileSync}from'node:fs';import{resolve}from'node:path';import{core,oracle,memory,string,root,report,enableNativeMath}from'./helpers.mjs';import{resourceLoader,nativePool,prepareBank,nativeInstances,compareAnm}from'./anm-oracle.mjs';
const load=(c,manager,name,id)=>{const data=readFileSync(resolve(root,'reference/assets',name)),p=c.allocate(data.length);memory(c,p,data.length).set(data);assert.equal(c.anm_manager_load(manager,id,p,data.length),1,name+': '+string(c,c.anm_manager_error(manager)));c.release(p);return data;};
const compareQueue=(c,m,manager,native,label)=>{for(let alt=0;alt<2;++alt){const list=nativeInstances(m,native,alt);assert.equal(c.anm_manager_count(manager,alt),list.length,label+' ANM count');for(let i=0;i<list.length;++i){const handle=m.u32(list[i]+0x544);assert.equal(c.anm_manager_order(manager,alt,i),handle,label+' order');const vm=c.anm_manager_find(manager,handle);assert.ok(vm);compareAnm(c,m,vm,list[i],label+' VM '+handle);assert.deepEqual(Buffer.from(memory(c,c.anm_vm_translation(vm),12)),Buffer.from(m.bytes(list[i]+0x5ec,12)),label+' translation');}}};
test('TH15 original scene music requests preserve reset order, practice skip, unlock flags and actual logo animations',async()=>{
 const c=await core(),m=await oracle();enableNativeMath(m);const loader=resourceLoader(m),base=m.heap;let cases=0,checks=0,events=[];m.replace(0x476f10,'original queued music control',()=>{const sp=m.reg('ESP');events.push(1,m.u32(sp+4),m.u32(sp+8));return 0;},3);m.replace(0x43d890,'original stage complete request',()=>{events.push(3);return 0;});m.replace(0x451100,'original ending request',()=>{events.push(4);return 0;});
 try{for(let stage=0;stage<8;++stage){m.heap=base;m.view(m.heap,0x1caf980).fill(0);const manager=c.anm_manager_create(),native=nativePool(m),gui=m.allocate(0x400),game=m.allocate(0x100),spell=m.allocate(0x100),scores=m.allocate(0x34000),text=m.allocate(0x19270),f=c.message_bridge_create(manager,stage),wave=c.allocate(256);try{
 m.u32(0x4ca620,0x4e73e8);m.f32(0x4e73e8,1);m.i32(0x4e73f4,stage);m.call(0x44f6c0);const definition=m.u32(0x4e9bd8),name=m.string(m.u32(definition+36)),ascii=load(c,manager,'ascii.anm',5),font=prepareBank(m,loader,'ascii.anm',ascii,native,5);assert.equal(c.anm_manager_fallback(manager,5),1);m.u32(0x4e9a58,text);m.u32(text+0x19258,font);const logo=load(c,manager,name,2),bank=prepareBank(m,loader,name,logo,native,2);m.u32(gui+0x168,bank);m.u32(0x4e9a8c,gui);m.u32(0x4e9a94,game);m.u32(0x4e9a70,spell);m.u32(0x4e9bc8,scores);
 for(let sample=0;sample<96;++sample){const id=[-1,-3,-2][sample%3],boss=id===-1,track=m.string(m.u32(definition+(boss?16:12))),flags=[0,0x20,0x30,0x10,0x60][Math.floor(sample/3)%5],transition=sample>>4&1,restart=sample&8,spellFlags=sample&4?0x80:0,current=sample&1?track+'.wav':track+'-different.wav';events=[];m.u32(0x4e7794,flags);m.u32(game+0xb4,transition);m.u32(spell+0x78,spellFlags);m.u32(0x4e79cc,restart?0x10:0);m.write(0x51dfa4,Buffer.from(current+'\0'));memory(c,wave,256).fill(0);memory(c,wave,current.length+1).set(Buffer.from(current+'\0'));c.message_bridge_configuration(f,flags,spellFlags,transition,restart,wave);m.call(0x437be0,{ecx:gui,args:[id]});if(events.includes(2)&&id!==-2){const unlock=m.i32(definition+(boss?44:40));assert.equal(m.bytes(scores+0x3374e+unlock,1)[0],1);events.push(2,unlock);}assert.equal(c.message_bridge_request(f,id),1,string(c,c.message_bridge_error(f)));assert.deepEqual(Array.from(new Uint32Array(c.memory.buffer,c.message_bridge_events(f),c.message_bridge_event_count(f))),events,'stage '+stage+' sample '+sample);compareQueue(c,m,manager,native,'stage '+stage+' sample '+sample);cases++;checks+=3;}
 }finally{c.message_bridge_delete(f);c.anm_manager_delete(manager);c.release(wave);}}
 report('message-music-bridge',{passed:true,cases,checks,originalFunctions:['0x437be0','0x44f6c0','0x477e10','0x487bd0'],scope:'Full original message-controller negative requests: stage/boss music reset and queue order, music unlock writes, spell-practice same-track skip, ending/stage transitions and real ANM logo trees and order. Audio hardware and complete game transitions remain separate.'});
 }finally{m.close();}
});
test('TH15 real dialogue balloon children, widths and text following match original geometry',async()=>{
 const c=await core(),m=await oracle(),manager=c.anm_manager_create(),native=nativePool(m),loader=resourceLoader(m),gui=m.allocate(0x400),dialogue=m.allocate(0x1b8),future=m.allocate(8),text=m.allocate(0x19270),f=c.message_bridge_create(manager,1),args=m.allocate(16);enableNativeMath(m);m.u32(0x4ca620,0x4e73e8);m.f32(0x4e73e8,1);m.u32(0x4e9a8c,gui);m.u32(0x4e9a58,text);m.write(future,Buffer.from([255,255,0,0,0,0,0,0]));for(const address of[0x41ebf0,0x441e30,0x428e30])m.replace(address,'dialogue constructor field clear',()=>0,address===0x41ebf0?1:address===0x441e30?2:0);let cases=0,checks=0;
 const invoke=(address,registers,argv)=>{const code=Buffer.alloc(29);code.set([0xf3,0x0f,0x10,0x0d],0);code.writeUInt32LE(args,4);code.set([0xf3,0x0f,0x10,0x15],8);code.writeUInt32LE(args+4,12);code.set([0xf3,0x0f,0x10,0x1d],16);code.writeUInt32LE(args+8,20);code[24]=0xe9;const cave=m.allocate(code.length);code.writeInt32LE(address-cave-code.length,25);m.write(cave,code);return m.call(cave,{ecx:registers,args:argv});};
 try{for(const[name,id]of[['ascii.anm',5],['text.anm',0],['front.anm',3]]){const bytes=load(c,manager,name,id),bank=prepareBank(m,loader,name,bytes,native,id);if(id===5){m.u32(text+0x19258,bank);assert.equal(c.anm_manager_fallback(manager,5),1);}if(id===0)m.u32(0x4e7f00,bank);if(id===3)m.u32(gui+0x2c8,bank);}new DataView(c.memory.buffer).setFloat32(c.anm_environment_scale(c.anm_manager_environment(manager)),2,true);
 assert.equal(c.message_bridge_request(f,0),1,string(c,c.message_bridge_error(f)));m.call(0x437520,{ecx:dialogue,args:[future]});compareQueue(c,m,manager,native,'initial dialogue');const state=c.message_bridge_dialogue(f),dv=()=>new DataView(c.memory.buffer);const handles=Array.from(new Uint32Array(c.memory.buffer,state+64,12)).slice(6,10);for(let sample=0;sample<120;++sample){const style=sample%16,x=(sample%19-9)*8.125,y=(sample%17-8)*7.5,width=(sample%23)*8.25;m.f32(args,x);m.f32(args+4,y);m.f32(args+8,Math.fround(width+16));invoke(0x439a40,dialogue,[style]);assert.equal(c.dialogue_bridge_balloon(f,style,x,y,width),1,string(c,c.message_bridge_error(f)));assert.equal(c.dialogue_bridge_balloon_handle(f),m.u32(dialogue+0x6c));compareQueue(c,m,manager,native,'balloon '+sample);for(let variant=0;variant<16;++variant){const value=(variant-2)*13.75;m.f32(args,value);invoke(0x439bb0,dialogue,[style]);assert.equal(c.dialogue_bridge_width(f,value),1);const child=c.dialogue_bridge_child(f,style+173),np=m.call(0x489250,{ecx:m.call(0x488510,{ecx:native,args:[m.u32(dialogue+0x6c)]}),args:[style+173,0]});assert.ok(child&&np);const scale=[.125,.75,1,1.125][variant%4],speaker=variant%3;dv().setFloat32(c.anm_vm_visual(child)+40,scale,true);m.f32(np+0x5c,scale);for(let k=0;k<3;++k){const p=(sample%7-3+k*11)*1.375,offset=(variant-5+k*3)*.25;dv().setFloat32(c.anm_vm_variables(child)+64+k*4,p,true);m.f32(np+0x38+k*4,p);dv().setFloat32(c.anm_vm_translation(child)+k*4,offset,true);m.f32(np+0x5ec+k*4,offset);}m.i32(dialogue+0x190,speaker);assert.equal(m.call(0x437ef0,{ecx:dialogue})|0,0);assert.equal(c.dialogue_bridge_follow(f,speaker,...handles),1);for(let k=0;k<4;++k){const vm=c.anm_manager_find(manager,handles[k]),nv=m.call(0x488510,{ecx:native,args:[m.u32(dialogue+0x58+k*4)]});assert.deepEqual(Buffer.from(memory(c,c.anm_vm_translation(vm),12)),Buffer.from(m.bytes(nv+0x5ec,12)),'sample '+sample+' variant '+variant+' text '+k);}compareQueue(c,m,manager,native,'width/follow '+sample+'/'+variant);cases++;checks+=6;}
 // Let deferred retirement run before reusing the next balloon style.
 assert.equal(c.anm_manager_update(manager,0,1),1,string(c,c.anm_manager_error(manager)));m.call(0x487740,{ecx:native});}
 report('dialogue-anm-bridge',{passed:true,cases,checks,originalFunctions:['0x437520','0x439a40','0x439bb0','0x437ef0','0x409630'],scope:'Original text and all 16 balloon template families, real child creation order, width changes, speaker-dependent text anchoring and deferred retirement compared. Raster font pixels and full scene rendering remain separate.'});
 }finally{c.message_bridge_delete(f);c.anm_manager_delete(manager);m.close();}
});
