import test from 'node:test';import assert from 'node:assert/strict';import{readFileSync}from 'node:fs';import{resolve}from 'node:path';import{core,oracle,memory,string,root,report}from './helpers.mjs';
test('TH15 music layout preserves original WAV index fallback, exact PCM loops and SSE quadratic volume',async()=>{
 const c=await core(),m=await oracle(),f=c.music_layout_create(),bytes=readFileSync(resolve(root,'reference/assets/thbgm.fmt')),p=c.allocate(bytes.length),name=c.allocate(200),native=m.allocate(0x2000),table=m.allocate(bytes.length),text=m.allocate(200),stream=m.allocate(0x100),vtable=m.allocate(0x50),buffer=m.allocate(16),ptr=m.allocate(4);let checks=0,volumes=0,actualDb=0;
 memory(c,p,bytes.length).set(bytes);assert.equal(c.music_layout_open(f,p,bytes.length),1,string(c,c.music_layout_error(f)));assert.equal(c.music_layout_count(f),18);m.view(native,0x2000).fill(0);m.write(table,bytes);m.u32(native+0x1980,table);m.view(stream,0x100).fill(0);m.view(vtable,0x50).fill(0);m.u32(stream+4,ptr);m.u32(ptr,buffer);m.u32(buffer,vtable);m.u32(vtable+0x3c,m.registerImport({dll:'fixture',name:'music volume device',argc:2,handler:()=>{actualDb=m.i32(m.reg('ESP')+8);return 0;}}));
 try{
 for(let index=0;index<18;index++){const offset=index*52,filename=bytes.subarray(offset,offset+16).toString('latin1').split('\0')[0],values=[...Array.from({length:4},(_,i)=>bytes.readUInt32LE(offset+16+i*4)),bytes.readUInt32LE(offset+36),bytes.readUInt16LE(offset+34),bytes.readUInt16LE(offset+44),bytes.readUInt16LE(offset+46),bytes.readUInt32LE(offset+28)/bytes.readUInt16LE(offset+44),bytes.readUInt32LE(offset+24)/bytes.readUInt16LE(offset+44)];assert.equal(string(c,c.music_layout_name(f,index)),filename);assert.deepEqual(Array.from(new Uint32Array(c.memory.buffer,c.music_layout_fields(f,index),10)),values);checks+=2;
 for(const prefix of['','music/','E:\\game\\music\\','a/b/','a\\b/','a/b\\']){const path=prefix+filename;memory(c,name,path.length+1).set(Buffer.from(path+'\0'));m.write(text,Buffer.from(path+'\0'));assert.equal(c.music_layout_index(f,name),m.call(0x475ba0,{ecx:native,args:[text]}),path+' original basename selection');checks++;}}
 for(const value of['unknown.wav','TH15_01.wav','th15_01.ogg','th15_01','/','\\']){memory(c,name,value.length+1).set(Buffer.from(value+'\0'));m.write(text,Buffer.from(value+'\0'));assert.equal(c.music_layout_index(f,name),m.call(0x475ba0,{ecx:native,args:[text]}));checks++;}
 for(const base of[0,-1,-100,-500,-1500,-3000,-4999,-5000,-6000])for(let master=0;master<=100;master++){m.i32(0x521350,master);m.call(0x48b950,{ecx:stream,args:[base]});assert.equal(c.music_adjusted_volume(base,master),actualDb,'native quadratic volume '+base+'/'+master);volumes++;checks++;}
 report('music-layout',{passed:true,tracks:18,checks,volumes,originalFunctions:['0x475ba0','0x48b950'],scope:'Original music filename lookup including slash precedence, case-sensitive exact matching and unknown-name fallback, all original PCM table fields and exact loop/source frame positions; actual original SSE music volume across 101 settings and nine attenuation levels. OGG PCM count, audio mixing and application scheduling remain separate.'});
 }finally{c.music_layout_delete(f);c.release(p);c.release(name);m.close();}
});
