import test from 'node:test';import assert from 'node:assert/strict';import{readFileSync}from 'node:fs';import{resolve}from 'node:path';import{core,oracle,memory,string,root,report,enableNativeMath}from './helpers.mjs';import{resourceLoader,nativePool,prepareBank,nativeInstances,compareAnm}from './anm-oracle.mjs';
const load=(c,a,name,id)=>{const bytes=readFileSync(resolve(root,'reference/assets',name)),p=c.allocate(bytes.length);memory(c,p,bytes.length).set(bytes);assert.equal(c.anm_manager_load(a,id,p,bytes.length),1,string(c,c.anm_manager_error(a)));c.release(p);return bytes;};
test('TH15 actual pause-menu ANM trees match original delayed prompts, disabled navigation, replay names, results and options return',async()=>{
 const c=await core(),m=await oracle();enableNativeMath(m);const loader=resourceLoader(m),base=m.heap;let sounds=[],reads=0,preparations=0,opened=0,closed=0,frames=0,checks=0,options=0;
 m.replace(0x476360,'fixture pause sound',()=>{sounds.push(m.i32(m.reg('ESP')+4));return 0;},2);m.replace(0x490cf2,'fixture numbered catalog filename',()=>0);m.replace(0x45bf50,'fixture replay slot read',()=>{reads++;return 0;});m.replace(0x45c020,'fixture replay metadata release',()=>0);m.replace(0x45c460,'fixture named replay file write',()=>1,4);m.replace(0x45c410,'fixture completed replay footer',()=>{preparations++;return 0;},1);m.replace(0x490eda,'fixture replay/result timestamp',()=>{const out=m.u32(m.reg('ESP')+4);m.view(out,8).fill(0);preparations++;return 0;});
 m.replace(0x43ed30,'fixture in-game options creation',()=>{opened++;m.u32(0x4e9a98,options);m.i32(options+0x124,0);return options;});m.replace(0x43eda0,'fixture in-game options destruction',()=>{closed++;m.u32(0x4e9a98,0);return 0;});
 const scenarios=[];for(const mode of[0,0x100])for(const item of[0,1,2,3,4])scenarios.push({phase:0,screen:1,mode,item});for(const item of[1,4])scenarios.push({phase:1,screen:1,mode:0x100,item});for(const item of[0,1,2,4])scenarios.push({phase:2,screen:2,mode:0,item});for(const mode of[0,0x100])for(const item of[1,2,4])scenarios.push({phase:3,screen:3,mode,item});scenarios.push({phase:0,screen:1,mode:0,item:1,replay:true},{phase:2,screen:2,mode:0,item:1,budget:0},{phase:0,screen:1,mode:0,item:4,continues:1},{phase:2,screen:2,mode:0,item:2,points:2000000});
 try{for(let index=0;index<scenarios.length;index++){
  const scene=scenarios[index];m.heap=base;m.view(base,0x1caf980).fill(0);const a=c.anm_manager_create(),pool=nativePool(m),native=m.allocate(0x400),run=m.allocate(0x100),hud=m.allocate(0x300),text=m.allocate(0x19270),records=m.allocate(0x40000),graphics=m.allocate(0x100),replay=m.allocate(0x100),file=m.allocate(0x100),out=m.allocate(4),f=c.pause_menu_create(a);options=m.allocate(0x140);
  try{
   m.u32(0x4e9a40,0);m.u32(0x4e9a44,0);m.u32(0x4ca620,0x4e73e8);m.f32(0x4e73e8,1);m.view(0x4e73f0,0x450).fill(0);m.view(run,0x100).fill(0);m.i32(run+0xb4,scene.replay?1:0);m.u32(0x4e9a94,run);m.u32(0x4e9a8c,hud);m.u32(0x4e9a58,text);m.u32(0x4e9bc8,records);m.u32(0x4e9a88,graphics);m.view(graphics,0x100).fill(0);const dbl=Buffer.alloc(8);dbl.writeDoubleLE(1);m.write(graphics+0x28,dbl);m.u32(0x4e9bc4,replay);m.u32(replay+0x18,file);m.u32(0x4e9a98,0);m.u32(0x4e7794,scene.mode);m.i32(0x4e7414,scene.continues||0);m.i32(0x4e7404,0);m.i32(0x4e7408,0);m.i32(0x4e7410,0);m.i32(0x4e73f0,1);m.i32(0x4e740c,scene.points||0);m.i32(0x4e75bc,0);m.i32(0x4e7594,0);m.i32(0x4e77a4,scene.budget??5);
   let front;for(const[name,id]of[['ascii.anm',5],['front.anm',101]]){const bytes=load(c,a,name,id),bank=prepareBank(m,loader,name,bytes,pool,id);if(id===5){m.u32(text+0x19258,bank);assert.equal(c.anm_manager_fallback(a,5),1);}else front=bank;}
   const script=scene.phase===1?152:scene.replay?151:scene.mode?150:149;assert.equal(c.pause_menu_configure(f,scene.phase,0,scene.screen,0,scene.mode,scene.continues||0,!!scene.replay,scene.phase===3?4:0,scene.budget??5,script),1,string(c,c.pause_menu_error(f)));c.pause_menu_points(f,scene.points||0);m.view(native,0x400).fill(0);m.write(native,Buffer.from(memory(c,c.pause_menu_state(f),0x3f4)));m.u32(native+0x3f0,front);m.call(0x423020,{ecx:front,args:[out,script]});assert.equal(m.u32(out),m.u32(native+0x1e4));m.write(records+8,Buffer.concat([Buffer.from(memory(c,c.pause_name_blocks(f,0),5*0xa4a0)),Buffer.from(memory(c,c.pause_name_blocks(f,1),0x42c))]));reads=preparations=opened=closed=0;
   const queue=label=>{for(let alt=0;alt<2;alt++){const list=nativeInstances(m,pool,alt);assert.equal(c.anm_manager_count(a,alt),list.length,label+' queue size');for(let i=0;i<list.length;i++){const handle=m.u32(list[i]+0x544);assert.equal(c.anm_manager_order(a,alt,i),handle,label+' handle order');compareAnm(c,m,c.anm_manager_find(a,handle),list[i],label+' script '+(m.u32(list[i]+0x4a8)&65535));checks++;}}};
   const step=(pressed=0,repeated=0)=>{const label=index+'/'+frames;m.u32(0x4e6d1c,pressed);m.u32(0x4e6d18,repeated);sounds=[];m.call(0x451740,{ecx:native,limit:1000000});assert.equal(c.pause_menu_update(f,pressed,repeated),1,string(c,c.pause_menu_error(f)));const expected=Buffer.from(m.bytes(native,0x3f4)),actual=Buffer.from(memory(c,c.pause_menu_state(f),0x3f4));for(const[at,n]of[[0xc,40],[0x34,0x1d8],[0x2d4,16],[0x3ec,4]])assert.deepEqual(actual.subarray(at,at+n),expected.subarray(at,at+n),label+' pause state '+at.toString(16));assert.deepEqual(Array.from(new Int32Array(c.memory.buffer,c.pause_name_sounds(f),c.pause_name_sound_count(f))),sounds,label+' sound order');assert.equal(c.pause_menu_count(f,0),reads,label+' catalog reads');assert.equal(c.pause_menu_count(f,2),opened);assert.equal(c.pause_menu_count(f,3),closed);checks+=8;queue(label+' before');
    for(const at of[0xc,0x20]){m.i32(native+at,m.i32(native+at+4));m.i32(native+at+4,m.i32(native+at+4)+1);m.f32(native+at+8,Math.fround(m.f32(native+at+8)+1));m.u32(native+at+12,0);}c.pause_menu_tick(f,1);for(let alt=0;alt<2;alt++){assert.equal(c.anm_manager_update(a,alt,1),1,string(c,c.anm_manager_error(a)));m.call(alt?0x487890:0x487740,{ecx:pool});}queue(label+' after');assert.deepEqual(Buffer.from(memory(c,c.anm_manager_random(a),8)),Buffer.from(m.bytes(0x4e9a40,8)),label+' RNG');frames++;return m.i32(native+0x1f4);};
   for(let k=0;k<12;k++)step();if(m.i32(native+0x1f4)===15){c.pause_menu_name_choose(f,90);m.call(0x422280,{ecx:native+0x10c,args:[90]});for(let k=0;k<10;k++)step();assert.equal(step(1),6);}
   const disabled=()=>Array.from({length:m.i32(native+0x108)},(_,i)=>m.i32(native+0xc4+i*4));let desired=scene.item;if(disabled().includes(desired))desired=1;for(let k=0;m.i32(native+0x34)!==desired&&k<8;k++)step(32,k%2?32:0);assert.equal(m.i32(native+0x34),desired);let phase=step(1);
   if(phase===7||phase===9){for(let k=0;k<31;k++)step();if(index%2===0){step(16);phase=step(1);}else phase=step(0x102);for(let k=0;k<21&&phase!==6&&phase!==11&&phase!==16;k++)phase=step();}
   if(phase===11){for(let k=0;k<11;k++)step();phase=step(1);assert.equal(phase,12);for(let k=0;k<11;k++)step();c.pause_menu_name_choose(f,90);m.call(0x422280,{ecx:native+0x10c,args:[90]});phase=step(1);assert.equal(phase,11);for(let k=0;k<11;k++)step();phase=step(0x102);}
   if(phase===14){for(let k=0;k<21;k++)step();assert.equal(opened,1);m.i32(options+0x124,1);c.pause_menu_options_done(f,1);assert.equal(step(),6);assert.equal(closed,1);}
  }finally{c.pause_menu_delete(f);c.anm_manager_delete(a);}
 }
 report('pause-menu',{passed:true,scenarios:scenarios.length,frames,animationChecks:checks,originalFunctions:['0x451740','0x423020','0x487740','0x487890'],scope:'Original pause controller versus actual portable ANM manager, original front/ascii resources, animation instances/order/VM fields/RNG before and after every frame, menu histories/disabled entries, delayed confirmation, replay slot/name/cancel, result score name and options overlay return. Audio/filesystem/options device and final phase-16 actions are isolated; final gameplay action integration is separately verified.'});
 }finally{m.close();}
});
