import test from 'node:test';import assert from 'node:assert/strict';import{core,oracle,memory,string,report}from './helpers.mjs';
test('TH15 original replay and high-score name grid preserves movement, eight-byte edits, empty cancellation and both save paths',async()=>{
 const c=await core(),m=await oracle(),f=c.pause_name_create(),native=m.allocate(0x400),records=m.allocate(0x40000),text=c.allocate(9);let cases=0,checks=0,sounds=[],written=null,refreshed=0;
 m.u32(0x4e9bc8,records);m.i32(0x4e7404,1);m.i32(0x4e7408,0);m.i32(0x4e7410,2);m.i32(0x4e7414,0);m.i32(0x4e77a4,5);const sp=()=>m.reg('ESP');
 m.replace(0x476360,'fixture name sound',()=>{sounds.push(m.i32(sp()+4));return 0;},2);
 m.replace(0x490cf2,'fixture numbered replay filename formatting',()=>{const out=m.u32(sp()+4),format=m.string(m.u32(sp()+8)),slot=m.i32(sp()+12);assert.equal(format,'th15_%.2d.rpy');const value='th15_'+String(slot).padStart(2,'0')+'.rpy';m.write(out,Buffer.from(value+String.fromCharCode(0)));return value.length;});
 m.replace(0x45c020,'fixture previous replay catalog metadata release',()=>0);
 m.replace(0x45c460,'fixture completed named replay file write',()=>{const name=m.string(m.u32(sp()+4)),bytes=Buffer.from(m.bytes(m.u32(sp()+8),9));assert.equal(m.u32(sp()+16),1);written={name,bytes};return 1;},4);
 m.replace(0x45bf50,'fixture saved replay catalog refresh',()=>{refreshed++;return 0x1234;});
 m.replace(0x423020,'fixture result-menu visual creation',()=>{const out=m.u32(sp()+4);m.u32(out,0x3333);return out;},3);m.replace(0x4886a0,'fixture result-menu delayed interrupt',()=>0,2);m.replace(0x488620,'fixture result-menu selection interrupt',()=>0,2);
 const patterns=[0,1,2,0x100,0x80000,0x10,0x20,0x40,0x80,0x41,0x91,0x102,0x31,0xc1],repeat=[0,0x10,0x20,0x40,0x80,0x30],recordBytes=()=>Buffer.concat([Buffer.from(memory(c,c.pause_name_blocks(f,0),5*0xa4a0)),Buffer.from(memory(c,c.pause_name_blocks(f,1),0x42c))]);
 try{for(const phase of[12,15])for(let length=0;length<=8;length++)for(let cursor=0;cursor<91;cursor++)for(let variant=0;variant<2;variant++){
  const value=Buffer.alloc(9,32);for(let k=0;k<length;k++)value[k]=65+k;value[8]=0;memory(c,text,9).set(value);const age=variant?10:cursor%2?9:10,slot=cases%10,mode=cases%3?0:0x100,pressed=cursor===90?1:patterns[(cursor+length+variant)%patterns.length],repeated=repeat[(cursor+length+variant)%repeat.length];
  assert.equal(c.pause_name_configure(f,phase,cursor,length,age,slot,mode,text),1);m.view(native,0x400).fill(0);m.write(native,Buffer.from(memory(c,c.pause_activation_state(f),0x3f4)));m.write(native+0x10c,Buffer.from(memory(c,c.pause_name_grid(f),0xd8)));m.i32(native+0x1f8,length);m.write(native+0x2d4,value);m.i32(native+0x34,slot);m.i32(native+0x3c,25);m.i32(native+0x104,1);m.u32(0x4e7794,mode);m.u32(0x4e6d1c,pressed);m.u32(0x4e6d18,repeated);m.write(records+8,recordBytes());sounds=[];written=null;refreshed=0;
  m.call(0x451740,{ecx:native,limit:100000});assert.equal(c.pause_name_update(f,pressed,repeated),1,string(c,c.pause_name_error(f)));const label=phase+'/'+length+'/'+cursor+'/'+variant;
  assert.deepEqual(Buffer.from(memory(c,c.pause_name_grid(f),0xd8)),Buffer.from(m.bytes(native+0x10c,0xd8)),label+' original name cursor/history/disabled grid');assert.deepEqual(Buffer.from(memory(c,c.pause_name_text(f),9)),Buffer.from(m.bytes(native+0x2d4,9)),label+' exact padded text');assert.equal(c.pause_name_length(f),m.i32(native+0x1f8),label+' edit length');assert.equal(c.pause_name_phase(f),m.i32(native+0x1f4),label+' phase');assert.deepEqual(Array.from(new Int32Array(c.memory.buffer,c.pause_name_sounds(f),c.pause_name_sound_count(f))),sounds,label+' sounds');assert.deepEqual(recordBytes(),Buffer.from(m.bytes(records+8,0x33b4c)),label+' complete recorded score/settings');assert.deepEqual(Buffer.from(memory(c,c.pause_activation_state(f)+0xc,20)),Buffer.from(m.bytes(native+0xc,20)),label+' reset age');assert.equal(new DataView(c.memory.buffer).getUint32(c.pause_activation_state(f)+0x3ec,true),m.u32(native+0x3ec),label+' name-save flags');checks+=8;
  if(written){assert.equal(written.name,'th15_'+String(slot+1).padStart(2,'0')+'.rpy');assert.equal(c.pause_name_written_slot(f),slot);assert.deepEqual(Buffer.from(memory(c,c.pause_name_written(f),9)),written.bytes);assert.equal(refreshed,1);checks+=4;}else{assert.equal(c.pause_name_written_slot(f),-1);checks++;}
  cases++;
 }
 report('pause-name-editor',{passed:true,cases,checks,originalFunctions:['0x451740','0x422240','0x403ba0','0x422280'],scope:'Original phase-12/15 name editor runs all 91 cursor cells and lengths 0..8, repeat/multiple-direction input, waiting age, append/full-name replacement, space/delete/empty cancel, named numbered replay write and refresh, registered score and stored name bytes, flags and phase clocks. Result-menu drawing is an isolated service and main menu rebuild is excluded; actual file I/O and full pause/score preparation remain separate.'});
 }finally{c.pause_name_delete(f);c.release(text);m.close();}
});
