import test from 'node:test';import assert from 'node:assert/strict';import{readFileSync}from 'node:fs';import{resolve}from 'node:path';import{core,oracle,memory,string,root,report}from './helpers.mjs';
test('TH15 result score registration matches original practice/Extra qualification, record bytes and both prepared name menus',async()=>{
 const c=await core(),m=await oracle(),f=c.pause_score_create(),pause=m.allocate(0x400),records=m.allocate(0x40000),graphics=m.allocate(0x100),data=c.allocate(0x33b4c),baseline=readFileSync(resolve(root,'artifacts/cpp/analysis/score/original-saved-state.bin'));let cases=0,checks=0,dates=0;
 const bytes=()=>Buffer.concat([Buffer.from(memory(c,c.pause_name_blocks(f,0),5*0xa4a0)),Buffer.from(memory(c,c.pause_name_blocks(f,1),0x42c))]);const double=(at,v)=>{const b=Buffer.alloc(8);b.writeDoubleLE(v);m.write(at,b);};
 m.u32(0x4e9bc8,records);m.u32(0x4e9a88,graphics);m.replace(0x490eda,'fixture qualifying result timestamp',()=>{const out=m.u32(m.reg('ESP')+4);m.u32(out,0x12345678);m.u32(out+4,0x9abcdef0);dates++;return 0;});
 try{for(let character=0;character<5;character++)for(let difficulty=0;difficulty<5;difficulty++)for(const mode of[0,0x10,0x20,0x30,0x100])for(const stage of[1,6,7])for(const result of[0,1])for(let variant=0;variant<4;variant++){
  const input=Buffer.from(baseline),name=['        ','ABCDEFGH','HI      ','X'+String.fromCharCode(0)+'      '][variant];input.set(Buffer.from(name+String.fromCharCode(0)),5*0xa4a0+12);const points=[0,1000000,950000,0xffffffff][variant],continues=cases%10,deaths=cases%71,delivered=cases%53,requested=60;
  memory(c,data,input.length).set(input);assert.equal(c.pause_score_configure(f,data,character,difficulty,stage,continues,deaths,mode,points,result,delivered,requested),1);
  m.view(pause,0x400).fill(0);m.write(pause,Buffer.from(memory(c,c.pause_activation_state(f),0x3f4)));m.write(pause+0x34,Buffer.from(memory(c,c.pause_score_menu(f),0xd8)));m.write(pause+0x10c,Buffer.from(memory(c,c.pause_name_grid(f),0xd8)));m.write(pause+0x2d4,Buffer.from(memory(c,c.pause_name_text(f),9)));m.i32(pause+0x1f8,c.pause_name_length(f));m.i32(pause+0x200,0);m.write(records+8,input);
  for(const[at,v]of[[0x4e7404,character],[0x4e7408,0],[0x4e7410,difficulty],[0x4e7794,mode],[0x4e73f0,stage],[0x4e740c,points],[0x4e7414,continues],[0x4e7594,deaths]])m.u32(at,v);double(graphics+0x20,delivered);double(graphics+0x28,requested);dates=0;
  m.call(0x4515a0,{ecx:pause,limit:1000000});assert.equal(c.pause_score_register(f),1,string(c,c.pause_score_error(f)));const label=[character,difficulty,mode,stage,result,variant].join('/');
  assert.deepEqual(bytes(),Buffer.from(m.bytes(records+8,0x33b4c)),label+' complete records');assert.equal(c.pause_score_name_not_required(f),m.i32(pause+0x200),label+' name qualification');assert.deepEqual(Buffer.from(memory(c,c.pause_score_menu(f),0xd8)),Buffer.from(m.bytes(pause+0x34,0xd8)),label+' score-row cursor');assert.deepEqual(Buffer.from(memory(c,c.pause_name_grid(f),0xd8)),Buffer.from(m.bytes(pause+0x10c,0xd8)),label+' name grid');assert.deepEqual(Buffer.from(memory(c,c.pause_name_text(f),9)),Buffer.from(m.bytes(pause+0x2d4,9)),label+' padded/short name');assert.equal(c.pause_name_length(f),m.i32(pause+0x1f8),label+' trimmed spaces');assert.equal(c.pause_name_phase(f),m.i32(pause+0x1f4),label+' phase unchanged');assert.equal(c.pause_score_stage(f),m.i32(0x4e73f0),label+' Extra live stage preserved');assert.equal(c.pause_score_captures(f),dates,label+' timestamp only after qualification');checks+=9;cases++;
 }
 report('pause-score-registration',{passed:true,cases,checks,originalFunctions:['0x4515a0','0x44fdc0','0x422280','0x403ba0'],scope:'Unmodified original result registration versus named C++ controller: five character banks, five difficulties, normal/practice/spell modes, Pointdevice bank, stages 1/6/Extra, completed Extra row marker, unsigned qualification, every score/settings byte, exact menu grids, prepared padded and short names, live-stage preservation and qualifying timestamp boundary. Pause transitions and actual platform clock remain separate.'});
 }finally{c.pause_score_delete(f);c.release(data);m.close();}
});
