import test from 'node:test';import assert from 'node:assert/strict';import{readFileSync}from 'node:fs';import{resolve}from 'node:path';import{core,oracle,memory,string,root,report}from './helpers.mjs';
test('TH15 pause draw matches original replay slots, animated naming grid, score ranking, credits and captured-background tint',async()=>{
 const c=await core(),m=await oracle(),a=c.anm_manager_create(),f=c.pause_draw_create(a),owner=m.allocate(0x400),text=m.allocate(0x19270),records=m.allocate(0x40000),tm=m.allocate(36),replayOwner=m.allocate(0x31c),live=m.allocate(0xa4),rootVm=m.allocate(0x610),child=m.allocate(0x610),captured=m.allocate(0x610),baseline=readFileSync(resolve(root,'artifacts/cpp/analysis/score/original-saved-state.bin')),data=c.allocate(baseline.length),description=c.pause_draw_live(f);let draws=[],times=[],date=[2024,9,17,12,43],snapshotKind=0,cases=0,checks=0;
 m.view(owner,0x400).fill(0);m.view(text,0x19270).fill(0);m.view(records,0x40000).fill(0);m.view(rootVm,0x610).fill(0);m.view(child,0x610).fill(0);m.view(captured,0x610).fill(0);m.u32(0x4e9a58,text);m.u32(0x4e9bc8,records);m.u32(0x4e9bc4,replayOwner);m.u32(replayOwner+0x18,live);m.u32(0x4e7994,captured);
 m.replace(0x488510,'fixture captured ANM handle lookup',()=>snapshotKind>=2?rootVm:0,1);
 m.replace(0x4915bf,'fixture pause calendar',()=>{const at=m.u32(m.reg('ESP')+4);times.push(Buffer.from(m.bytes(at,8)).readBigInt64LE());m.i32(tm+16,date[1]-1);m.i32(tm+20,date[0]-1900);m.i32(tm+12,date[2]);return tm;});
 m.replace(0x40c570,'fixture formatted ASCII request',()=>{const sp=m.reg('ESP'),font=m.u32(sp+4),pos=m.u32(sp+8),format=m.string(m.u32(sp+12));let arg=sp+16;
 const rendered=format.replace(/%%|%(?:[0-9]+)?(?:\.[0-9]+)?l?[sdc]/g,token=>{if(token==='%%')return '%';const kind=token.at(-1),width=Number(token.slice(1).match(/^\d+/)?.[0]||0),precision=token.match(/\.(\d+)/)?.[1];let value;
 if(kind==='s'){value=m.string(m.u32(arg));arg+=4;}else if(kind==='c'){value=String.fromCharCode(m.u32(arg)&255);arg+=4;}else{value=String(m.i32(arg));arg+=4;if(precision)value=value.padStart(Number(precision),'0');}return value.padStart(width,' ');});draws.push({text:Buffer.from(rendered,'latin1'),color:m.u32(font+0x19224),font:m.i32(font+0x1923c),position:[m.f32(pos),m.f32(pos+4),m.f32(pos+8)]});return 0;});
 const makeFile=slot=>{const r=c.recording_create(),h=c.allocate(0x238),n=c.allocate(9),meta=c.recording_metadata(r);try{memory(c,h,0x238).fill(0);new DataView(c.memory.buffer).setUint16(h,1,true);assert.equal(c.recording_begin(r,h,0x238),1);c.recording_activate(r);c.recording_tick(r,0,0,0,60,0);const d=new DataView(c.memory.buffer);d.setBigInt64(meta+0xc,1700000000n+BigInt(slot),true);d.setUint32(meta+0x8c,slot%4,true);d.setUint32(meta+0x94,slot%5,true);d.setUint32(meta+0x98,slot%10,true);d.setInt32(meta+0xa0,slot*4-1,true);memory(c,meta+10,1)[0]=slot%3===0?2:0;memory(c,n,9).set(Buffer.from('TEST'+String(slot).padStart(4,'0')+'\0'));assert.equal(c.recording_write(r,n,1),1);return Buffer.from(memory(c,c.recording_data(r),c.recording_size(r)));}finally{c.recording_delete(r);c.release(h);c.release(n);}};
 try{
 for(const slot of[0,2,4,7,12,20,24]){const bytes=makeFile(slot),p=c.allocate(bytes.length),file=c.replay_create();memory(c,p,bytes.length).set(bytes);assert.equal(c.pause_draw_file(f,slot,p,bytes.length),1);assert.equal(c.replay_open(file,p,bytes.length),1);const nativeReplay=m.allocate(0x31c),meta=m.allocate(0xa4);m.view(nativeReplay,0x31c).fill(0);m.write(meta,Buffer.from(memory(c,c.replay_data(file),0xa4)));m.u32(nativeReplay+0x18,meta);m.u32(owner+0x20c+slot*4,nativeReplay);if(slot===24){memory(c,description,0xa4).set(memory(c,c.replay_data(file),0xa4));m.write(live,Buffer.from(memory(c,description,0xa4)));}c.replay_delete(file);c.release(p);}
 for(const screen of[0,1,2,3,4])for(const phase of[0,14,15])for(const flags of[0,1,2,3])for(const mode of[0,0x100,0x300])for(const selected of[0,7,24])for(const age of[0,9,10,30]){
 const character=cases%5,rank=cases%6,required=cases%2===0,cursor=cases%91,length=cases%9,credit=cases%11-1,name=Buffer.from(cases%2?'ABCDEFGH\0':'AB      \0');snapshotKind=cases%5;const tint=(0x00765432^(cases*0x10101))>>>0;c.pause_draw_configure(f,screen,phase,flags,mode,selected,cursor,length,age,required,character,rank,credit);c.pause_draw_snapshot(f,snapshotKind,tint);memory(c,c.pause_name_text(f),9).set(name);date=[1901+cases%200,1+cases%12,1+cases%28,0,0];memory(c,c.pause_draw_date(f),20).set(new Uint8Array(new Int32Array(date).buffer));
 const bytes=Buffer.from(baseline),base=character*0xa4a0+(mode&0x300?0:0x5188)+0x10+rank*320;for(let row=0;row<10;row++){const at=base+row*32;bytes.writeInt32LE(row%2?-12345-row:987654+row,at);bytes[at+4]=row;bytes.writeInt8(row-1,at+5);bytes.set(Buffer.from('SCORE'+String(row).padStart(3,'0')+'\0'),at+6);bytes.writeBigInt64LE(row%3?1700000000n+BigInt(row):0n,at+16);}memory(c,data,bytes.length).set(bytes);assert.equal(c.pause_draw_records(f,data),1);m.write(records+8,bytes);
 m.i32(owner+0x1ec,screen);m.i32(owner+0x1f4,phase);m.u32(owner+0x3ec,flags);m.i32(owner+0x34,selected);m.i32(owner+0x10c,cursor);m.i32(owner+0x1f8,length);m.i32(owner+0x10,age);m.i32(owner+0x200,required?1:0);m.write(owner+0x2d4,name);m.u32(owner+0x1e8,snapshotKind?0x12345678:0);m.u32(0x4e7794,mode);m.i32(0x4e7404,character);m.i32(0x4e7408,0);m.i32(0x4e7410,rank);m.i32(0x4e77a4,credit);m.u32(text+0x19224,0xffffffff);m.u32(text+0x19238,0);m.u32(captured+0x538,0x11223344);m.u32(rootVm+0x594,snapshotKind>=3?child:0);m.u32(rootVm+0x598,0);m.u32(child+0x4a8,snapshotKind===3?57:56);m.u32(child+0x538,tint);
 draws=[];times=[];assert.equal(m.call(0x450a40,{ecx:owner,limit:1000000}),1);assert.equal(c.pause_draw_run(f),1,cases+' '+string(c,c.pause_draw_error(f)));assert.equal(c.pause_draw_count(f),draws.length,cases+' count');for(let i=0;i<draws.length;i++){const p=c.pause_draw_text(f,i),raw=memory(c,p,Math.min(256,c.memory.buffer.byteLength-p)),end=raw.indexOf(0),style=c.pause_draw_style(f,i),v=new DataView(c.memory.buffer);assert.deepEqual(Buffer.from(raw.subarray(0,end)),draws[i].text,cases+' text '+i);assert.equal(v.getUint32(style,true),draws[i].color,cases+' color '+i);assert.equal(v.getInt32(style+12,true),draws[i].font,cases+' glyph set');assert.equal(v.getInt32(style+16,true),0,cases+' screen coordinate space');assert.deepEqual(Array.from(new Float32Array(c.memory.buffer,c.pause_draw_position(f,i),3)),draws[i].position,cases+' position '+i);checks+=5;}
 assert.deepEqual(Array.from(new BigInt64Array(c.memory.buffer,c.pause_draw_times(f),c.pause_draw_time_count(f))),times,cases+' calendar calls');assert.deepEqual(Buffer.from(memory(c,description,0xa4)),Buffer.from(m.bytes(live,0xa4)),cases+' live caption name reset');assert.equal(c.pause_draw_snapshot_handle(f)!==0,m.u32(owner+0x1e8)!==0,cases+' stale snapshot handle');assert.equal(c.pause_draw_snapshot_color(f)>>>0,m.u32(captured+0x538),cases+' snapshot primary tint');assert.equal(m.u32(text+0x19238),0);checks+=5;cases++;
 }
 report('pause-draw',{passed:true,cases,checks,originalFunctions:['0x4503d0','0x450560','0x450630','0x4507b0','0x450870','0x450a40'],scope:'Actual original pause drawing and formatted text requests against named C++: every caption byte, position, small ASCII glyph set, screen coordinates, 91-cell name grid, cursor including full names, age-0/9/10 naming interpolation, empty/normal/spell replay slots, record banks and signed scores/continue suffix, date inputs, credit gates, overlay order, invalid/correct/wrong-script capture tint and live replay name mutation. CRT formatting/calendar and native ANM owner lookup are isolated boundaries; GPU capture pixels and full browser presentation remain separate.'});
 }finally{c.pause_draw_delete(f);c.anm_manager_delete(a);c.release(data);m.close();}
});
