import test from 'node:test';import assert from 'node:assert/strict';import{core,oracle,memory,string,report}from './helpers.mjs';
test('TH15 closing pause/result presentation restores original rate, frame skip, elapsed-time gate and overlay freeze order',async()=>{
 const c=await core(),m=await oracle(),f=c.pause_activation_create(),native=m.allocate(0x400),game=m.allocate(0x400),gui=m.allocate(0x400),notice=m.allocate(0x610),dialogue=m.allocate(0x100);let cases=0,checks=0,events=[];
 m.u32(0x4e9a94,game);m.u32(0x4e9a8c,gui);m.view(gui,0x400).fill(0);m.u32(gui+0x1b8,dialogue);m.u32(gui+0x11c,88);
 const sp=()=>m.reg('ESP'),push=(...e)=>{events.push(...e);return 0;};m.replace(0x472c90,'fixture resume wall-clock origin',()=>push(1));m.replace(0x439840,'fixture dialogue resume',()=>push(2));m.replace(0x488510,'fixture chapter-notice animation lookup',()=>{assert.equal(m.u32(sp()+4),88);push(3);return notice;},1);m.replace(0x488620,'fixture closing animation interrupt',()=>push(4,m.u32(sp()+4),m.i32(sp()+8)),2);
 try{for(const screen of[1,2,3])for(const replay of[0,1])for(const rate of[.125,.75,1,1.125])for(const flags of[0x10,0x90,0x4090,0x8010]){
  c.pause_activation_configure(f,0,43,replay,rate,screen,5);const p=c.pause_activation_field(f,0);new DataView(c.memory.buffer).setUint32(p+96,flags,true);m.view(native,0x400).fill(0);m.write(native,Buffer.from(memory(c,c.pause_activation_state(f),0x3f4)));m.view(game,0x400).fill(0);m.u32(game+0x90,flags);m.u32(game+0xb4,replay);m.f32(0x4e73e8,rate);m.i32(0x51bc60,7);m.view(notice,0x610).fill(0);events=[];m.call([0,0x451460,0x451500,0x451550][screen],{ecx:native});assert.equal(c.pause_restoration_run(f),1,string(c,c.pause_restoration_error(f)));const dv=new DataView(c.memory.buffer),label=screen+'/'+replay+'/'+rate+'/'+flags;
  assert.equal(dv.getUint32(p+96,true),m.u32(game+0x90),label+' flags');assert.equal(dv.getFloat32(p+92,true),m.f32(0x4e73e8),label+' speed');assert.equal(dv.getInt32(c.pause_activation_field(f,2),true),m.i32(0x51bc60),label+' frame skip');assert.deepEqual(Array.from(new Int32Array(c.memory.buffer,c.pause_activation_events(f),c.pause_activation_event_count(f))),events,label+' original ordering');assert.deepEqual(Buffer.from(memory(c,c.pause_activation_state(f),0x3f4)),Buffer.from(m.bytes(native,0x3f4)),label+' menu state remains available to selected action');cases++;checks+=5;
 }
 report('pause-restoration',{passed:true,cases,checks,originalFunctions:['0x451460','0x451500','0x451550'],scope:'Original three close-presentation functions; live/replay elapsed-time restart gate, scene flags, stored rate/frame skip, dialogue/chapter notice resume and both visual interrupt ordering. This is the close step preceding actual continue/retry/title routing; device animation and wall time are explicit services.'});
 }finally{c.pause_activation_delete(f);m.close();}
});
