import test from 'node:test';import assert from 'node:assert/strict';import {core,oracle,memory,report} from './helpers.mjs';
test('TH15 player hit and graze predicates match original boundaries and immunity states',async()=>{
 const c=await core(),m=await oracle(),fixture=c.player_collision_create(),player=m.allocate(0x2c048),bomb=m.allocate(0x1bc),radius=m.allocate(8),position=m.allocate(8),size=m.allocate(8),bulletRadius=m.allocate(4),wrapper=m.allocate(32);m.u32(0x4e9bb8,player);m.u32(player+0x2c008,radius);const code=Buffer.from([0xf3,0x0f,0x10,0x15,0,0,0,0,0xe9,0,0,0,0]);code.writeUInt32LE(bulletRadius,4);code.writeInt32LE(0x455d00-wrapper-code.length,9);m.write(wrapper,code);let hits=0,checks=0,cases=0;m.replace(0x456540,'player_death_request_boundary',()=>{hits++;return 0;});
 const write=(field,values,offset)=>{const b=Buffer.alloc(values.length*4);values.forEach((v,i)=>b.writeFloatLE(v,i*4));memory(c,c.player_collision_field(fixture,field),b.length).set(b);m.write(offset,b);};
 try{for(let circle=0;circle<2;circle++)for(let sample=0;sample<256;sample++){
  const px=(sample-127)*.125,py=(sample-113)*.25,rad=[0,.1,1,2,4,8,16,64][sample%8],multiplier=[.5,1,1.5,2][sample%4],state=sample%6,immune=sample%3-1,enlarged=sample%2,bombActive=sample%7===0;write(0,[px,py],player+0x618);write(1,[px-3,py-4],player+0x2bfb0);write(2,[px+3,py+4],player+0x2bfbc);write(3,[rad],radius+4);write(4,[multiplier],player+0x2c044);new DataView(c.memory.buffer).setInt32(c.player_collision_field(fixture,5),state,true);new DataView(c.memory.buffer).setInt32(c.player_collision_field(fixture,6),immune,true);m.u32(player+0x16220,state);m.u32(player+0x16284,immune>>>0);m.u32(player+0x16294,enlarged?16:0);m.u32(0x4e9a8c,sample%3?bomb:0);m.u32(bomb+0x1b8,bombActive?1:0);c.player_collision_options(fixture,enlarged,sample%3?bombActive:0);
  for(let point=0;point<96;point++)for(let graze=0;graze<2;graze++){
   const delta=[-100,-64,-41,-40,-25,-24,-8,-4,-3,-1,-.125,0,.125,1,3,4,8,24,25,40,41,64,100],x=Math.fround(px+delta[point%delta.length]),y=Math.fround(py+delta[Math.floor(point/delta.length)*5+(sample%3)]),a=[0,.1,1,4,8,16,64,128][point%8],b=[0,.1,1,4,8,16,64,128][sample%8];m.f32(position,x);m.f32(position+4,y);m.f32(size,a);m.f32(size+4,b);m.f32(bulletRadius,a);hits=c.player_collision_hits(fixture);const expected=m.call(circle?wrapper:0x455be0,{args:circle?[position,graze]:[position,size,graze]})|0,actual=c.player_collision_check(fixture,circle,x,y,a,b,graze),label=JSON.stringify({circle,sample,point,graze,state,immune,enlarged,a,b});assert.equal(actual,expected,label+' contact');assert.equal(c.player_collision_hits(fixture),hits,label+' death request');checks+=2;cases++;
  }
 }report('player-collision-predicates',{passed:true,cases,checks,originalFunctions:['0x455be0','0x455d00'],scope:'Rectangle/circle contacts, boundary rounding, graze-only checks, enlarged hit radius, bomb immunity, player state and death requests. Full player death/retry/bomb lifecycle is separate work.'});
 }finally{c.player_collision_delete(fixture);m.close();}
});
