import test from 'node:test';import assert from 'node:assert/strict';import {core,oracle,memory,report} from './helpers.mjs';
test('TH15 firing timers preserve original press, release, fractional-rate and wrap sequencing',async()=>{
 const c=await core(),m=await oracle(),owner=m.allocate(0x2c020);let frames=0,checks=0,events=[];m.replace(0x458c90,'observe_fire',()=>{const sp=m.reg('ESP');events.push(m.i32(sp+4),m.i32(sp+8));return 0;},2);m.u32(0x4ca620,0x4e73e8);
 try{for(let scenario=0;scenario<24;scenario++){const fixture=c.player_shooting_create();events=[];m.view(owner,0x2c020).fill(0);for(let i=0;i<2;i++)m.write(owner+0x16244+i*20,Buffer.from(memory(c,c.player_shooting_timer(fixture,i),20)));
  for(let frame=0;frame<2400;frame++){const held=scenario%4===0?true:scenario%4===1?frame%201<120:scenario%4===2?frame%7<2:frame%199>150,state=frame%251<5?frame%5:1,rate=[1,.5,.25,1.25,.995,1.005][scenario%6];m.f32(0x4e73e8,rate);m.u32(0x4e6f28,held?1:0);m.i32(owner+0x16220,state);m.i32(owner+0x2c00c,19);m.view(owner+0x2c010,1)[0]=1;c.player_shooting_aux(fixture,19,1);
   assert.equal(c.player_shooting_step(fixture,state,held,rate),1);m.call(0x458de0,{ecx:owner});for(let i=0;i<2;i++)assert.deepEqual(Buffer.from(memory(c,c.player_shooting_timer(fixture,i),20)),Buffer.from(m.bytes(owner+0x16244+i*20,20)),scenario+'/'+frame+' timer '+i);assert.equal(c.player_shooting_aux_value(fixture,0),m.i32(owner+0x2c00c));assert.equal(c.player_shooting_aux_value(fixture,1),m.bytes(owner+0x2c010,1)[0]);assert.equal(c.player_shooting_count(fixture)*2,events.length);if(events.length){const actual=new Int32Array(c.memory.buffer,c.player_shooting_events(fixture),events.length);assert.equal(actual[events.length-2],events[events.length-2]);assert.equal(actual[events.length-1],events[events.length-1]);}frames++;checks+=7;
  }assert.deepEqual(Array.from(new Int32Array(c.memory.buffer,c.player_shooting_events(fixture),events.length)),events);c.player_shooting_delete(fixture);
 }report('player-shooting-timers',{passed:true,frames,checks,originalFunctions:['0x458de0','0x452e80','0x409040','0x408ba0','0x44b870'],scope:'Original shooting state, press/release continuation, 14/119-frame timer wrapping and fractional-rate sequencing. Shot generation requests are observed at the original 0x458c90 boundary; actual SHT generation has separate original-resource tests.'});}finally{m.close();}
});
