import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {resolve} from 'node:path';import {core,oracle,memory,string,root,report,enableNativeMath} from './helpers.mjs';import {resourceLoader,nativePool,nativeInstances,prepareBank,compareAnm} from './anm-oracle.mjs';
const fields=[[0,0x624,8],[1,0x618,12],[2,0x2bff8,8],[3,0x162c0,8],[4,0x162a8,12],[5,0x162b4,12],[6,0x16298,16],[7,0x2c000,4],[8,0x16240,4],[9,0x644,4],[10,0x162c8,4],[11,0x162cc,4],[12,0x1626c,4],[13,0x16294,4],[14,0x2c044,4],[15,0x162d0,4],[16,0x162d4,12],[17,0x1622c,20]],optionFields=[[0,0x668,4],[1,0x6bc,8],[2,0x6c4,8],[3,0x6cc,8],[4,0x6d4,8],[5,0x73c,4]];
test('TH15 all four characters preserve original movement and actual animation manager progression',async()=>{
 const c=await core(),m=await oracle(),manager=c.anm_manager_create(),nativeManager=nativePool(m),loader=resourceLoader(m),enemyManager=m.allocate(0x200),effects=m.allocate(0x2020),textManager=m.allocate(0x19270),owner=m.allocate(0x2c0a0),out=m.allocate(4);enableNativeMath(m);m.u32(0x4e9a80,enemyManager);m.u32(0x4e9a78,effects);m.u32(0x4e9a58,textManager);m.u32(0x4ca620,0x4e73e8);m.f32(0x4e73e8,1);let frames=0,checks=0;
 const load=(name,id)=>{const bytes=readFileSync(resolve(root,'reference/assets',name)),p=c.allocate(bytes.length);memory(c,p,bytes.length).set(bytes);assert.equal(c.anm_manager_load(manager,id,p,bytes.length),1,name+': '+string(c,c.anm_manager_error(manager)));c.release(p);return prepareBank(m,loader,name,bytes,nativeManager,id);};
 try{const ascii=load('ascii.anm',2);assert.equal(c.anm_manager_fallback(manager,2),1);m.u32(textManager+0x19258,ascii);const effectBank=load('effect.anm',8);m.u32(effects+12,effectBank);
 for(let character=0;character<4;character++){const name='pl0'+character,playerBank=load(name+'.anm',9+character),shot=readFileSync(resolve(root,'reference/assets',name+'.sht')),header=c.allocate(0xe0);memory(c,header,0xe0).set(shot.subarray(0,0xe0));
  for(let scenario=0;scenario<8;scenario++){m.view(owner,0x2c0a0).fill(0);m.u32(owner+12,playerBank);const fixture=c.player_motion_create(manager,9+character,8),vm=c.player_motion_root(fixture);m.call(0x40b880,{ecx:playerBank,args:[owner+16,0]});m.call(0x477e10,{ecx:owner+16});c.player_motion_configure(fixture,header);for(const[field,no,n]of fields){if(field===6)m.write(owner+no,Buffer.from(memory(c,c.player_motion_field(fixture,field),n)));else if(field===17)m.write(owner+no,Buffer.from(memory(c,c.player_motion_field(fixture,field),n)));else{const data=Buffer.alloc(n);if(field===0){data.writeInt32LE((scenario-3)*7000);data.writeInt32LE(40000-scenario*7000,4);}if(field===10)data.writeInt32LE([10,30,50,100,125,200,0,-30][scenario]);if(field===12)data.writeInt32LE(8);if(field===14||field===15)data.writeFloatLE(1);if(field===4)data.writeFloatLE(.75,8);memory(c,c.player_motion_field(fixture,field),n).set(data);m.write(owner+no,data);}}
   for(let i=0;i<8;i++){for(const[field,no,n]of optionFields){const data=Buffer.alloc(n);if(field===0)data.writeInt32LE(1);if(field===5)data.writeInt32LE(i%2);if(field===1||field===2){data.writeInt32LE((i-3)*4500);data.writeInt32LE((i+2)*1700,4);}if(field===3||field===4){data.writeInt32LE((i-3)*(field===3?3200:800));data.writeInt32LE((i+1)*(field===3?-2700:-1300),4);}memory(c,c.player_motion_option(fixture,i,field),n).set(data);m.write(owner+no+i*0xe4,data);}for(let k=0;k<2;k++){const handle=c.anm_manager_spawn(manager,8,26+k,14,2);assert.ok(handle);m.call(0x433020,{ecx:effectBank,args:[out,26+k,14]});assert.equal(handle,m.u32(out));new DataView(c.memory.buffer).setUint32(c.player_motion_handles(fixture,2)+(i*2+k)*4,handle,true);m.u32(owner+0x718+i*0xe4+k*4,handle);}}
   for(let frame=0;frame<240;frame++){let dv=new DataView(c.memory.buffer);const input=((frame*37+scenario*19)&255)|((frame%11)?8:0),allowed=frame%41>3,rate=[1,.5,.25,1.25][(frame>>4)%4],flags=(frame>=80&&frame<115?2:0)|(frame%17>7?16:0),enlarge=1+(frame%13)*.0625,scale=1+(frame%5-2)*.125;dv.setInt32(c.player_motion_field(fixture,9),frame,true);m.i32(owner+0x644,frame);dv.setUint32(c.player_motion_field(fixture,13),flags,true);m.u32(owner+0x16294,flags);dv.setFloat32(c.player_motion_field(fixture,14),enlarge,true);m.f32(owner+0x2c044,enlarge);dv.setFloat32(c.player_motion_field(fixture,15),scale,true);m.f32(owner+0x162d0,scale);for(let k=0;k<3;k++){const value=(frame%13-6+k*3)*.015625;dv.setFloat32(c.player_motion_field(fixture,16)+k*4,value,true);m.f32(owner+0x162d4+k*4,value);}if(frame===50||frame===137){const timer=Buffer.alloc(20);timer.writeInt32LE(6);timer.writeInt32LE(7,4);timer.writeFloatLE(7,8);timer.writeUInt32LE(1,16);memory(c,c.player_motion_field(fixture,17),20).set(timer);m.write(owner+0x1622c,timer);}m.u32(0x4e6f28,input);m.u32(enemyManager+0x18c,allowed?1:0);m.f32(0x4e73e8,rate);assert.equal(c.player_motion_step(fixture,input,allowed,rate),1,string(c,c.player_motion_error(fixture)));assert.equal(m.call(0x4540e0,{ecx:owner})|0,0);const label=name+'/'+scenario+'/'+frame;for(const[field,no,n]of fields)assert.deepEqual(Buffer.from(memory(c,c.player_motion_field(fixture,field),n)),Buffer.from(m.bytes(owner+no,n)),label+' field '+field);for(let i=0;i<8;i++)for(const[field,no,n]of optionFields)assert.deepEqual(Buffer.from(memory(c,c.player_motion_option(fixture,i,field),n)),Buffer.from(m.bytes(owner+no+i*0xe4,n)),label+' option '+i+' field '+field);assert.equal(new DataView(c.memory.buffer).getUint32(c.player_motion_handles(fixture,0),true),m.u32(owner+0x16224),label+' focus handle');assert.equal(new DataView(c.memory.buffer).getUint32(c.player_motion_handles(fixture,1),true),m.u32(owner+0x16228),label+' barrier handle');compareAnm(c,m,vm,owner+16,label+' root');
    for(let alternate=0;alternate<2;alternate++){assert.equal(c.anm_manager_update(manager,alternate,rate),1,string(c,c.anm_manager_error(manager)));m.call(alternate?0x487890:0x487740,{ecx:nativeManager});const list=nativeInstances(m,nativeManager,alternate);assert.equal(c.anm_manager_count(manager,alternate),list.length,label+' queue '+alternate);for(let i=0;i<list.length;i++){const h=m.u32(list[i]+0x544);assert.equal(c.anm_manager_order(manager,alternate,i),h,label+' order '+i);compareAnm(c,m,c.anm_manager_find(manager,h),list[i],label+' queued '+h);assert.deepEqual(Buffer.from(memory(c,c.anm_vm_translation(c.anm_manager_find(manager,h)),12)),Buffer.from(m.bytes(list[i]+0x5ec,12)),label+' translation '+h);checks++;}}frames++;checks+=68;
   }c.player_motion_delete(fixture);for(let alternate=0;alternate<2;alternate++)while(nativeInstances(m,nativeManager,alternate).length){const original=nativeInstances(m,nativeManager,alternate)[0],h=m.u32(original+0x544);assert.equal(c.anm_manager_destroy_tree(manager,c.anm_manager_find(manager,h)),1);m.call(0x488820,{ecx:nativeManager,args:[original]});}
  }c.release(header);
 }report('player-motion-animation',{passed:true,characters:4,frames,checks,originalFunctions:['0x4540e0','0x40b880','0x477e10','0x488620','0x487740'],scope:'Actual motion of all four characters with original SHT speeds and ANM resources, digital-input precedence, fixed positions/bounds, frame-rate scaling, focus indicator, animation poses, eight option positions/collapse and barrier timer/visuals. Option-specific callbacks and the full player death/shot/bomb session remain separate.'});
 }finally{c.anm_manager_delete(manager);m.close();}
});
