import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {resolve} from 'node:path';import {core,oracle,memory,string,root,report,enableNativeMath} from './helpers.mjs';import {resourceLoader,nativePool,nativeInstances,prepareBank,compareAnm} from './anm-oracle.mjs';
test('TH15 hit, deathbomb cancellation and death preserve original state and real animation effects',async()=>{
 const c=await core(),m=await oracle(),manager=c.anm_manager_create(),nativeManager=nativePool(m),loader=resourceLoader(m),owner=m.allocate(0x2c0a0),effects=m.allocate(0x1100),spell=m.allocate(0x90),bomb=m.allocate(0x40),enemies=m.allocate(0x200),text=m.allocate(0x19270),hud=m.allocate(0x200),out=m.allocate(4);enableNativeMath(m);m.u32(0x4e9a78,effects);m.u32(0x4e9a70,spell);m.u32(0x4e9a68,bomb);m.u32(0x4e9a80,enemies);m.u32(0x4e9a58,text);m.u32(0x4e9a8c,hud);m.u32(0x4ca620,0x4e73e8);m.f32(0x4e73e8,1);let events=[],transitions=0,frames=0,checks=0;
 m.replace(0x476360,'hit sound request',()=>{events.push(1,m.i32(m.reg('ESP')+4),0);return 0;},2);m.replace(0x43a850,'remaining life display',()=>{events.push(2,m.i32(m.reg('ESP')+4),m.i32(m.reg('ESP')+8));return 0;},2);
 const load=(name,id)=>{const bytes=readFileSync(resolve(root,'reference/assets',name)),p=c.allocate(bytes.length);memory(c,p,bytes.length).set(bytes);assert.equal(c.anm_manager_load(manager,id,p,bytes.length),1,name+': '+string(c,c.anm_manager_error(manager)));c.release(p);return prepareBank(m,loader,name,bytes,nativeManager,id);};
 const put=(p,bytes)=>memory(c,p,bytes.length).set(bytes),sessionOffsets=[0x4e7450,0x4e7454,0x4e742c,enemies+0x3c,enemies+0x44,bomb+0x24,0x4e7794];
 try{const ascii=load('ascii.anm',2);assert.equal(c.anm_manager_fallback(manager,2),1);m.u32(text+0x19258,ascii);const effectBank=load('effect.anm',8);m.u32(effects+12,effectBank);
 for(let character=0;character<4;character++){const bank=load('pl0'+character+'.anm',9+character);for(let scenario=0;scenario<16;scenario++){m.view(owner,0x2c0a0).fill(0);m.view(effects+0x18,0x1004).fill(0);m.u32(owner+12,bank);m.call(0x40b880,{ecx:bank,args:[owner+16,0]});m.call(0x477e10,{ecx:owner+16});const fixture=c.player_life_create(manager,9+character),vm=c.player_life_root(fixture);events=[];for(let field=1;field<=2;field++)m.write(owner+(field===1?0x62c:0x16280),Buffer.from(memory(c,c.player_life_field(fixture,field),20)));let dv=new DataView(c.memory.buffer);const values=[[2,0,8,-1][scenario%4],scenario*17,scenario%2?999999:19,scenario+2,17,scenario%2,([0,0x100,0x200,0x300][scenario%4])];for(let i=0;i<7;i++){dv.setInt32(c.player_life_field(fixture,3)+i*4,values[i],true);m.i32(sessionOffsets[i],values[i]);}const spellValues=[scenario%3?0x23:0,([0,59,60,99][scenario%4]),123456];for(let i=0;i<3;i++){dv.setInt32(c.player_life_field(fixture,4)+i*4,spellValues[i],true);m.i32(spell+[0x78,0x24,0x7c][i],spellValues[i]);}dv.setUint32(c.player_life_field(fixture,5),scenario%2?8:0,true);m.u32(owner+0x16294,scenario%2?8:0);for(let i=0;i<3;i++){dv.setFloat32(c.player_life_field(fixture,6)+i*4,(i-1)*73.25,true);m.f32(owner+0x618+i*4,(i-1)*73.25);}dv.setInt32(c.player_life_field(fixture,9),8,true);m.i32(owner+0x1626c,8);
 for(let i=0;i<8;i++){dv=new DataView(c.memory.buffer);dv.setInt32(c.player_life_option_active(fixture,i),2,true);m.i32(owner+0x668+i*0xe4,2);for(let k=0;k<2;k++){const h=c.anm_manager_spawn(manager,8,26+k,14,2);m.call(0x433020,{ecx:effectBank,args:[out,26+k,14]});assert.equal(h,m.u32(out),'option '+character+'/'+scenario+'/'+i+'/'+k);new DataView(c.memory.buffer).setUint32(c.player_life_option_handles(fixture)+(i*2+k)*4,h,true);m.u32(owner+0x718+i*0xe4+k*4,h);}}
 for(const kind of [0,2,0,1]){assert.equal(c.player_life_transition(fixture,kind),1,string(c,c.player_life_error(fixture)));m.call([0x456540,0x456370,0x456740][kind],{ecx:owner});assert.equal(new DataView(c.memory.buffer).getInt32(c.player_life_field(fixture,0),true),m.i32(owner+0x16220));for(let field=1;field<=2;field++)assert.deepEqual(Buffer.from(memory(c,c.player_life_field(fixture,field),20)),Buffer.from(m.bytes(owner+(field===1?0x62c:0x16280),20)));dv=new DataView(c.memory.buffer);for(let i=0;i<7;i++)assert.equal(dv.getInt32(c.player_life_field(fixture,3)+i*4,true),m.i32(sessionOffsets[i]));for(let i=0;i<3;i++)assert.equal(dv.getInt32(c.player_life_field(fixture,4)+i*4,true),m.i32(spell+[0x78,0x24,0x7c][i]));assert.equal(dv.getInt32(c.player_life_field(fixture,9),true),m.i32(owner+0x1626c));for(let i=0;i<8;i++)assert.equal(dv.getInt32(c.player_life_option_active(fixture,i),true),m.i32(owner+0x668+i*0xe4));assert.deepEqual(Array.from(new Int32Array(c.memory.buffer,c.player_life_events(fixture),c.player_life_count(fixture)*3)),events);assert.deepEqual(Buffer.from(memory(c,c.player_life_field(fixture,7),4096)),Buffer.from(m.bytes(effects+0x1c,4096)));assert.equal(dv.getInt32(c.player_life_field(fixture,8),true),m.i32(effects+0x18));compareAnm(c,m,vm,owner+16,'root '+character+'/'+scenario+'/'+kind);for(let alternate=0;alternate<2;alternate++){const list=nativeInstances(m,nativeManager,alternate);assert.equal(c.anm_manager_count(manager,alternate),list.length);for(let i=0;i<list.length;i++){const h=m.u32(list[i]+0x544);assert.equal(c.anm_manager_order(manager,alternate,i),h);compareAnm(c,m,c.anm_manager_find(manager,h),list[i],'effect '+h);}}transitions++;checks+=30;
 }
 for(let frame=0;frame<60;frame++){const rate=([1,.5,.25,1.25][scenario%4]);m.f32(0x4e73e8,rate);for(let alternate=0;alternate<2;alternate++){assert.equal(c.anm_manager_update(manager,alternate,rate),1,string(c,c.anm_manager_error(manager)));m.call(alternate?0x487890:0x487740,{ecx:nativeManager});const list=nativeInstances(m,nativeManager,alternate);assert.equal(c.anm_manager_count(manager,alternate),list.length);for(let i=0;i<list.length;i++){const h=m.u32(list[i]+0x544);assert.equal(c.anm_manager_order(manager,alternate,i),h);compareAnm(c,m,c.anm_manager_find(manager,h),list[i],'tick '+character+'/'+scenario+'/'+frame+'/'+h);checks++;}}frames++;}
 c.player_life_delete(fixture);for(let alternate=0;alternate<2;alternate++)while(nativeInstances(m,nativeManager,alternate).length){const p=nativeInstances(m,nativeManager,alternate)[0],h=m.u32(p+0x544);assert.equal(c.anm_manager_destroy_tree(manager,c.anm_manager_find(manager,h)),1);m.call(0x488820,{ecx:nativeManager,args:[p]});}m.f32(0x4e73e8,1);assert.equal(c.anm_manager_update(manager,0,1),1);
 }}report('player-life-transitions',{passed:true,characters:4,transitions,frames,checks,originalFunctions:['0x456540','0x456370','0x456740','0x4530c0','0x417f70'],scope:'Real player/effect ANM hit, deathbomb cancellation and death transitions, remaining lives, spell failure, Legacy death counter, option interruption, effect tracking and subsequent animation lifecycles. Audio/HUD requests are observed at service boundaries; full player frame/session/bombs remain separate.'});}finally{c.anm_manager_delete(manager);m.close();}
});
