import test from "node:test";import assert from "node:assert/strict";import {readFileSync} from "node:fs";import {resolve} from "node:path";
import {core,oracle,memory,string,root,report} from "./helpers.mjs";
test("All original TH15 demo files decode and replay every input tick identically",async()=>{
 const c=await core(),m=await oracle(),manager=m.allocate(0x400),world=m.allocate(0x200),path=m.allocate(256),heap=m.heap;let source,checks=0;const demos=[];
 m.replace(0x490cf2,"fixture format path",()=>0);m.replace(0x490f2b,"fixture directory change",()=>0);m.replace(0x450fa0,"fixture replay end",()=>0);
 m.replace(0x402db0,"read replay fixture",()=>{const out=m.allocate(source.length);m.write(out,source);if(m.reg("EDX"))m.u32(m.reg("EDX"),source.length);return out;},1);m.u32(0x4e7794,0x40);m.u32(0x4e9a94,world);
 try{for(const name of ["demo0.rpy","demo1.rpy","demo2.rpy"]){source=readFileSync(resolve(root,"reference/assets",name));m.heap=heap;m.view(manager,0x400).fill(0);m.write(path,Buffer.from(name+"\0"));m.call(0x45cc80,{ecx:manager,args:[path],limit:100000000});const replay=c.replay_create(),p=c.allocate(source.length);memory(c,p,source.length).set(source);assert.equal(c.replay_open(replay,p,source.length),1,name+" "+string(c,c.replay_error(replay)));const unpacked=source.readUInt32LE(32),nativeData=m.u32(manager+0x204);assert.equal(c.replay_size(replay),unpacked);assert.deepEqual(Buffer.from(memory(c,c.replay_data(replay),unpacked)),Buffer.from(m.bytes(nativeData,unpacked)));const decoded=m.bytes(nativeData,unpacked),number=decoded[0xa4]|decoded[0xa5]<<8,frames=decoded.readUInt32LE?decoded.readUInt32LE(0xa8):new DataView(decoded.buffer).getUint32(0xa8,true);assert.equal(c.replay_select(replay,number),1);m.u32(manager+0x214,number);m.u32(manager+0xd8+number*0x28,0);m.u32(manager+200+number*0x28,m.u32(manager+0xc4+number*0x28));m.u32(manager+0xd0+number*0x28,m.u32(manager+0xcc+number*0x28));m.u32(manager+0x20c,0);
 for(let frame=0;frame<frames+3;frame++){const before=c.replay_frame(replay),inactive=Buffer.from(memory(c,c.replay_tick(replay,0),8));assert.equal(c.replay_frame(replay),before);m.call(0x45cea0,{ecx:manager});const got=Buffer.from(memory(c,c.replay_tick(replay,1),8));assert.equal(got.readUInt16LE(0),m.u32(0x4e6f28),name+" held "+frame);assert.equal(got.readUInt16LE(2),m.u32(0x4e6f34),name+" pressed "+frame);assert.equal(got.readUInt16LE(4),m.u32(0x4e6f38),name+" released "+frame);assert.equal(got[6],m.bytes(manager+0x208,1)[0],name+" fps "+frame);checks+=4;}demos.push({name,stage:number,frames,character:c.replay_field(replay,1),difficulty:c.replay_field(replay,2)});c.replay_delete(replay);c.release(p);}report("replay-input",{passed:true,checks,totalFrames:demos.reduce((s,d)=>s+d.frames,0),demos,scope:"Decoding and input playback only; world simulation equivalence remains to be implemented and verified."});
 }finally{m.close();}
});
