import test from 'node:test';import assert from 'node:assert/strict';import {core,oracle,memory,string,report} from './helpers.mjs';
const rawString=(m,p)=>{const b=Buffer.from(m.bytes(p,4096)),end=b.indexOf(0);return b.subarray(0,end<0?b.length:end).toString('latin1');};
test('TH15 recording and complete exported replay bytes match original across FPS rounding, 900-frame chunks, stages, sentinels and repeat exports',async()=>{
 const c=await core(),m=await oracle();let writes=[],timestamp=1700000000n;const world=m.allocate(0x200),timing=m.allocate(0x100),tm=m.allocate(36),filename=m.allocate(64),name=m.allocate(32),base=m.heap;let ticks=0,totalBytes=0;
 m.u32(0x4e9a94,world);m.u32(0x4e9a88,timing);m.write(filename,Buffer.from('th15_01.rpy'+String.fromCharCode(0)));m.replace(0x422160,'platform input edges already computed',()=>0);
 m.replace(0x490cf2,'CRT sprintf formatting boundary',()=>{const sp=m.reg('ESP'),dest=m.u32(sp+4),format=rawString(m,m.u32(sp+8));let arg=sp+12;const text=format.replace(/%(?:s|d|\.2d|2\.2f)/g,spec=>{if(spec==='%s'){const s=rawString(m,m.u32(arg));arg+=4;return s;}if(spec.includes('f')){const b=Buffer.from(m.bytes(arg,8)),v=b.readDoubleLE();arg+=8;return v.toFixed(2);}const v=m.i32(arg);arg+=4;return spec==='%.2d'?String(v).padStart(2,'0'):String(v);});const data=Buffer.from(text,'latin1');m.write(dest,Buffer.concat([data,Buffer.from([0])]));return data.length;});
 m.replace(0x490f2b,'working directory boundary',()=>0);m.replace(0x403130,'replay file creation boundary',()=>{m.u32(0x4e0ef0,777);return 0;});m.replace(0x4915bf,'local calendar conversion boundary',()=>tm);m.replace(0x490eda,'current replay completion timestamp boundary',()=>{const b=Buffer.alloc(8);b.writeBigInt64LE(timestamp);m.write(m.u32(m.reg('ESP')+4),b);return Number(timestamp&0xffffffffn);});
 const writeAddress=m.u32(0x4be09c),writeEntry=m.importMap.get(writeAddress);m.importMap.set(writeAddress,{...writeEntry,argc:5,handler:()=>{const sp=m.reg('ESP'),size=m.u32(sp+12);assert.equal(m.u32(sp+4),777);writes.push(Buffer.from(m.bytes(m.u32(sp+8),size)));m.u32(m.u32(sp+16),size);return 1;}});const closeAddress=m.u32(0x4be088),closeEntry=m.importMap.get(closeAddress);m.importMap.set(closeAddress,{...closeEntry,argc:1,handler:()=>1});
 try{for(let scenario=0;scenario<12;scenario++){
  m.heap=base;const manager=m.allocate(0x220),header=m.allocate(0x24),meta=m.allocate(0xa4),record=c.recording_create(),snapshot=c.allocate(0x238),namePtr=c.allocate(16);m.view(manager,0x220).fill(0);m.view(header,0x24).fill(0);m.u32(0x4e9bc4,manager);m.u32(manager+0x14,header);m.u32(manager+0x18,meta);m.u32(header,0x72353174);m.write(header+4,Buffer.from([3,0]));m.u32(header+0x10,0x100);
  try{
   const description=Buffer.from(Array.from({length:0xa4},(_,i)=>(i*31+scenario*7)&255));description.fill(0,0,9);description.writeUInt32LE(scenario%4,0x8c);description.writeUInt32LE(0,0x90);description.writeUInt32LE(scenario%5,0x94);memory(c,c.recording_metadata(record),description.length).set(description);m.write(meta,description);
   const details=c.recording_details(record),score=1234567+scenario*91,elapsed=503.5+scenario*0.07,total=520.1+scenario*0.003;new DataView(c.memory.buffer).setInt32(details,score,true);new DataView(c.memory.buffer).setFloat64(details+8,elapsed,true);new DataView(c.memory.buffer).setFloat64(details+16,total,true);for(const[o,v]of[[24,2026],[28,10],[32,1+scenario],[36,7+scenario],[40,11+scenario]])new DataView(c.memory.buffer).setInt32(details+o,v,true);m.u32(0x4e740c,score);m.write(timing+0x20,Buffer.from(memory(c,details+8,16)));m.view(tm,36).fill(0);m.i32(tm+4,11+scenario);m.i32(tm+8,7+scenario);m.i32(tm+12,1+scenario);m.i32(tm+16,9);m.i32(tm+20,126);
   const numbers=scenario>=9?[1,3,6]:scenario===8?[7]:[1+(scenario%6)],counts=[0,1,29,30,31,899,900,901,1801,901,1801,1801];let last=0;
   for(const number of numbers){last=number;const h=Buffer.from(Array.from({length:0x238},(_,i)=>(i*71+number*11+scenario)&255));h.writeUInt16LE(number);h.writeUInt16LE(1234+scenario,2);h.fill(0,4,12);memory(c,snapshot,h.length).set(h);assert.equal(c.recording_begin(record,snapshot,h.length),1,string(c,c.recording_error(record)));const nativeHeader=m.allocate(h.length);m.write(nativeHeader,h);m.u32(manager+0x1c+number*4,nativeHeader);const node=m.call(0x45d4f0,{ecx:manager,args:[number]});m.u32(manager+0xbc,node);m.u32(manager+0x214,number);m.i32(manager+0x20c,-1);m.u32(0x4e7794,0);assert.equal(m.call(0x45c040,{ecx:manager}),1);assert.equal(c.recording_tick(record,0,0,0,60,0),1);assert.equal(c.recording_clock(record),-1);c.recording_activate(record);m.i32(manager+0x20c,0);
    for(let frame=0;frame<counts[scenario];frame++){
     const held=(frame*17+scenario*27)&65535,pressed=(frame*19+number)&65535,released=(frame*23+scenario)&65535,fps=[60,59.49,59.5,255.4,255.5,256,300,-1.7,-0.6,30.2][Math.floor(frame/30)%10],paused=scenario===11&&frame%20===7;
     m.u32(0x4e6d10,held);m.u32(0x4e6f34,pressed);m.u32(0x4e6f38,released);m.f32(timing+0x30,fps);m.u32(0x4e7794,paused?[0x100,0x200,0x300][Math.floor(frame/20)%3]:0);assert.equal(m.call(0x45c040,{ecx:manager}),1);assert.equal(c.recording_tick(record,held,pressed,released,fps,paused),1,string(c,c.recording_error(record)));assert.equal(c.recording_clock(record),m.i32(manager+0x20c));ticks++;
    }
   }
   const cleared=scenario%3===0;m.u32(0x4e73f0,last);timestamp=1700000000n+BigInt(scenario*12345);m.call(0x45c410,{args:[cleared?1:0]});c.recording_finish(record,timestamp,last,cleared);assert.deepEqual(Buffer.from(memory(c,c.recording_metadata(record)+0xc,8)),Buffer.from(m.bytes(meta+0xc,8)));assert.equal(new DataView(memory(c,c.recording_metadata(record),0xa4).buffer,memory(c,c.recording_metadata(record),0xa4).byteOffset,0xa4).getUint32(0x98,true),cleared?8:last);
   for(let exported=0;exported<2;exported++){
    const playerName=exported?'ABCDEFGH':scenario%2?'TEST':'',b=Buffer.from(playerName+String.fromCharCode(0));m.write(name,b);memory(c,namePtr,b.length).set(b);writes=[];const terminate=scenario!==1;m.call(0x45c460,{args:[filename,name,0,terminate],limit:1000000000});assert.equal(writes.length,4);assert.equal(c.recording_write(record,namePtr,terminate),1,string(c,c.recording_error(record)));const original=Buffer.concat(writes),actual=Buffer.from(memory(c,c.recording_data(record),c.recording_size(record)));assert.deepEqual(actual,original,'complete exported replay scenario '+scenario+' export '+exported);totalBytes+=actual.length;
    if(scenario!==11){const replay=c.replay_create();assert.equal(c.replay_open(replay,c.recording_data(record),actual.length),1,string(c,c.replay_error(replay)));assert.equal(c.replay_field(replay,0),numbers.length);c.replay_delete(replay);}
   }
   const savedOutput=Buffer.from(memory(c,c.recording_data(record),c.recording_size(record)));
    m.u32(0x4e6d10,0x80);m.u32(0x4e6f34,0x80);m.u32(0x4e6f38,0);m.f32(timing+0x30,17);m.u32(0x4e7794,0);const sealedClock=m.i32(manager+0x20c),nativeResult=m.call(0x45c040,{ecx:manager});
    assert.equal(nativeResult,1,'native sealed recording tick succeeds');assert.equal(m.i32(manager+0x20c),sealedClock+1,'native post-export clock advances');assert.equal(c.recording_tick(record,0x80,0x80,0,17,0),nativeResult,string(c,c.recording_error(record)));assert.equal(c.recording_clock(record),sealedClock+1);assert.deepEqual(Buffer.from(memory(c,c.recording_data(record),c.recording_size(record))),savedOutput,'post-export input does not change saved bytes');
  }finally{c.release(snapshot);c.release(namePtr);c.recording_delete(record);}
 }
 report('replay-recording',{passed:true,scenarios:12,ticks,exports:24,comparedBytes:totalBytes,originalFunctions:['0x45c040','0x45d4f0','0x45c410','0x45c460','0x46d1b0','0x402ca0'],scope:'Recording clock, independent held/pressed/released inputs, native FPS rounding and suspended ticks, original 900-frame linked chunks, stage snapshot retention, termination sentinel, repeat-export idempotence, compression/encryption, both complete USER blocks and decoder reopen. Input edge calculation, file I/O and CRT calendar/text formatting are isolated platform boundaries; gameplay replay equivalence remains separate.'});
 }finally{m.close();}
});
