import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {resolve} from 'node:path';import {core,oracle,memory,string,root,report} from './helpers.mjs';
test('TH15 original replay gameplay recalculates redundant input edges and preserves hold clocks, final FPS, inactive waits and sentinels',async()=>{
 const c=await core(),m=await oracle(),manager=m.allocate(0x220),world=m.allocate(0x200),path=m.allocate(32),base=m.heap;let source,frames=0,checks=0,ended=0;const results=[];
 m.replace(0x490cf2,'replay path formatting boundary',()=>0);m.replace(0x490f2b,'replay directory boundary',()=>0);m.replace(0x450fa0,'replay ending destination boundary',()=>{ended++;return 0;});m.replace(0x402db0,'test replay file read',()=>{const p=m.allocate(source.length);m.write(p,source);if(m.reg('EDX'))m.u32(m.reg('EDX'),source.length);return p;},1);m.u32(0x4e9a94,world);m.u32(0x4e7794,0x40);
 try{for(let scenario=0;scenario<6;scenario++){
  const original=readFileSync(resolve(root,'reference/assets','demo'+(scenario%3)+'.rpy')),file=c.replay_create(),p=c.allocate(original.length);memory(c,p,original.length).set(original);assert.equal(c.replay_open(file,p,original.length),1);source=original;
  if(scenario>=3){const bytes=Buffer.from(memory(c,c.replay_data(file),c.replay_size(file))),n=bytes.readUInt32LE(0xa8);for(let i=0;i<n;i++){const at=0xa4+0x238+i*6;bytes.writeUInt16LE((i*31+999)&65535,at+2);bytes.writeUInt16LE((i*71+27)&65535,at+4);}bytes.fill(255,0xa4+0x238+(n-2)*6,0xa4+0x238+(n-1)*6);
   const codec=c.codec_create(),input=c.allocate(bytes.length),packed=c.allocate(bytes.length*2+1024),a=c.allocate(bytes.length*2+1024),b=c.allocate(bytes.length*2+1024);try{memory(c,input,bytes.length).set(bytes);const size=c.codec_encode(codec,input,bytes.length,packed,bytes.length*2+1024);assert.ok(size>0);assert.equal(c.crypt(packed,a,size,0x7d,0x3a,0x100,size,1),1);assert.equal(c.crypt(a,b,size,0x5c,0xe1,0x400,size,1),1);source=Buffer.concat([original.subarray(0,0x24),Buffer.from(memory(c,b,size))]);source.writeUInt32LE(0x24+size,0xc);source.writeUInt32LE(size,0x1c);assert.equal(c.replay_open(file,b,1),0);const rewritten=c.allocate(source.length);memory(c,rewritten,source.length).set(source);assert.equal(c.replay_open(file,rewritten,source.length),1,string(c,c.replay_error(file)));c.release(rewritten);}finally{c.codec_delete(codec);for(const ptr of[input,packed,a,b])c.release(ptr);}}
  m.heap=base;m.view(manager,0x220).fill(0);m.call(0x45cc80,{ecx:manager,args:[path],limit:100000000});const decoded=Buffer.from(memory(c,c.replay_data(file),c.replay_size(file))),number=decoded.readUInt16LE(0xa4),count=decoded.readUInt32LE(0xa8),play=c.replay_playback_create(file);assert.equal(c.replay_playback_select(play,number),1);m.call(0x45d1a0);m.u32(manager+0x214,number);m.i32(manager+0xd8+number*0x28,-1);m.u32(manager+0xc8+number*0x28,m.u32(manager+0xc4+number*0x28));m.u32(manager+0xd0+number*0x28,m.u32(manager+0xcc+number*0x28));m.u32(manager+0x20c,0);m.u32(manager+0x208,0);ended=0;
  const compare=label=>{const ip=c.replay_playback_input(play),v=Array.from(new Uint32Array(c.memory.buffer,ip,70));for(const[i,at]of[[0,0x4e6f28],[1,0x4e6f2c],[2,0x4e6f30],[3,0x4e6f34],[4,0x4e6f38],[5,0x4e6f40]])assert.equal(v[i],m.u32(at),label+' input '+i);for(let i=0;i<32;i++){assert.equal(v[i+6],m.u32(0x4e6da4+i*4),label+' repeat '+i);assert.equal(v[i+38],m.u32(0x4e6ea4+i*4),label+' duration '+i);}assert.equal(c.replay_playback_fps(play),m.bytes(manager+0x208,1)[0],label+' fps');assert.equal(c.replay_playback_finished(play),ended?1:0,label+' ending');checks+=72;};
  try{for(let i=0;i<3;i++){m.call(0x45c150,{ecx:manager});assert.equal(c.replay_playback_tick(play,1),1);compare(scenario+'/waiting');}m.i32(manager+0xd8+number*0x28,0);m.u32(manager+0x20c,0);c.replay_playback_activate(play);
   for(let frame=0;frame<count+3;frame++){const clock=c.replay_playback_clock(play),snapshot=Buffer.from(memory(c,c.replay_playback_input(play),280));assert.equal(c.replay_playback_tick(play,0),1);assert.equal(c.replay_playback_clock(play),clock);assert.deepEqual(Buffer.from(memory(c,c.replay_playback_input(play),280)),snapshot);m.call(0x45c150,{ecx:manager});assert.equal(c.replay_playback_tick(play,1),1,string(c,c.replay_playback_error(play)));compare(scenario+'/'+frame);assert.equal(c.replay_playback_clock(play),m.i32(manager+0x20c));frames++;}
   results.push({scenario,stage:number,frames:count,mutatedRedundantEdges:scenario>=3,endingRequests:ended});
  }finally{c.replay_playback_delete(play);c.replay_delete(file);c.release(p);}
 }
 report('replay-gameplay-input',{passed:true,frames,checks,results,originalFunctions:['0x45cc80','0x45c150','0x45d1a0','0x422160'],scope:'Original demo replay inputs and mutated redundant edges, all 32 held clocks, stage pre-activation wait, inactive callback, EOF/FPS boundary, sentinel and subsequent frames. No world simulation or native complete-stage parity claim.'});
 }finally{m.close();}
});
