import test from 'node:test';import assert from 'node:assert/strict';import{readFileSync}from'node:fs';import{resolve}from'node:path';import{core,oracle,memory,string,root,report}from'./helpers.mjs';import{preloadStage}from'./stage-assets-fixture.mjs';
test('Original Z/Ctrl replay acceleration repeats updates to the next eight-frame boundary',{timeout:90000},async()=>{
 const c=await core(),m=await oracle(),bytes=readFileSync(resolve(root,'../[th15] 东方绀珠传 (汉化版+日文版)/replay/th15_ud0186.rpy')),p=c.allocate(bytes.length),file=c.replay_create();memory(c,p,bytes.length).set(bytes);assert.equal(c.replay_open(file,p,bytes.length),1,string(c,c.replay_error(file)));const asset=preloadStage(c,1,1),stage=c.stage_gameplay_create(asset.fixture);let playback=0,session=0,checks=0;const observations=[];const nativeOwner=m.allocate(0x100),nativeReplay=m.allocate(0x220);m.u32(0x4e9a94,nativeOwner);
 const expected=(held,clock,flags=0,phase=1)=>{m.u32(nativeOwner+0x90,flags);m.u32(nativeReplay+0xc,phase);m.i32(nativeReplay+0x20c,clock);m.u32(0x4e6d10,held);return m.call(0x45ceb0,{ecx:nativeReplay});};
 try{assert.equal(c.stage_gameplay_prepare(stage),1);assert.equal(c.stage_gameplay_begin(stage),1);playback=c.replay_playback_create(file);assert.equal(c.replay_playback_select(playback,1),1);c.replay_playback_activate(playback);session=c.session_gameplay_create(stage,0,playback);
 for(const held of [0,1,0x200,0x201,0xa00,2,8,0x100])for(let phase=0;phase<8;phase++){
  for(let align=0;c.replay_playback_clock(playback)%8!==phase;align++){assert.ok(align<8,'single-step clock must advance');assert.equal(c.session_gameplay_step(session,0,0,60),1,string(c,c.session_gameplay_error(session)));}
  const before=c.replay_playback_clock(playback);let want=1;while(expected(held,before+want)===6){assert.ok(want<8,'native update boundary');want++;}assert.ok(want<=8);
  assert.equal(c.session_gameplay_step(session,held,0,60),1,string(c,c.session_gameplay_error(session)));const after=c.replay_playback_clock(playback);assert.equal(after-before,want,'held '+held+' clock '+before);observations.push({held,before,after,want});checks++;
 }
 const progress=c.stage_gameplay_field(stage,0),d=new DataView(c.memory.buffer);d.setUint32(progress+96,4,true);const before=c.replay_playback_clock(playback);assert.equal(expected(0x201,before+1,4),1);assert.equal(c.session_gameplay_step(session,0x201,0,60),1);assert.equal(c.replay_playback_clock(playback),before+1,'pause cannot accelerate');d.setUint32(progress+96,0,true);checks++;
 const released=c.replay_playback_clock(playback);assert.equal(c.session_gameplay_step(session,0,0,60),1);assert.equal(c.replay_playback_clock(playback),released+1,'released keys resume single updates');checks++;
 // Individual stages in this multi-stage file have no EOF marker. Inject the
 // original six-byte terminal marker to exercise that separate completion path.
 const terminal=c.replay_playback_clock(playback);memory(c,c.replay_data(file)+0xa4+0x238+terminal*6,6).fill(255);assert.equal(c.replay_playback_tick(playback,1),1);assert.equal(c.replay_playback_finished(playback),1);const eof=c.replay_playback_clock(playback);assert.equal(c.session_gameplay_step(session,0x201,0,60),1);assert.equal(c.replay_playback_clock(playback),eof+1,'EOF does not restart indefinitely');checks++;
 report('replay-acceleration',{passed:true,checks,observations,originalFunctions:['0x45ceb0','0x45b630'],scope:'Actual recorded stage-one stream and scheduled C++ world, Z/Ctrl/combined/C/non-accelerating controls at all eight clock phases; original unmodified 45ceb0 determines each expected update count. Pause/release guards and an injected original-format terminal marker. Browser routing and actual pixels verified separately.'});
 }finally{if(session)c.session_gameplay_delete(session);if(playback)c.replay_playback_delete(playback);c.stage_gameplay_delete(stage);asset.close();c.replay_delete(file);c.release(p);m.close();}
});
