import test from 'node:test';import assert from 'node:assert/strict';import{readFileSync,readdirSync}from 'node:fs';import{resolve}from 'node:path';import{core,memory,string,root,report}from './helpers.mjs';
test('TH15 actual run scheduler freezes gameplay/recording, resumes pause, saves a named replay and routes real player death through continue/chapter restore',async()=>{
 const c=await core(),name=c.allocate(256),files=[];let frames=0,checks=0;const results=[];
 try{
  for(const n of readdirSync(resolve(root,'reference/assets')).filter(n=>/\.(anm|ecl|sht|std|msg)$/.test(n))){const bytes=readFileSync(resolve(root,'reference/assets',n)),p=c.allocate(bytes.length);memory(c,p,bytes.length).set(bytes);files.push({name:n,p,size:bytes.length});}
  for(let character=0;character<4;character++)for(const scenario of[0,1,2]){const mode=scenario===1?0x100:0;
   const a=c.stage_assets_create(),r=c.run_pause_create(a);try{
    for(const f of files){memory(c,name,f.name.length+1).set(Buffer.from(f.name+String.fromCharCode(0)));c.stage_assets_file(a,name,f.p,f.size);}
    assert.equal(c.run_construction_load(r,1,character,mode,1,0,0),1,string(c,c.run_construction_error(r)));assert.equal(c.run_pause_attach(r),1,string(c,c.run_pause_error(r)));const view=()=>new DataView(c.memory.buffer),int=p=>view().getInt32(p,true),state=k=>c.run_pause_state(r,k),progress=c.run_gameplay_field(r,0),player=c.run_gameplay_field(r,1),step=(held=0,pressed=0,repeated=0)=>{assert.equal(c.run_pause_step(r,held,pressed,repeated,0),1,string(c,c.run_pause_error(r)));frames++;};
    for(let k=0;k<400;k++)step();assert.equal(state(0),0);const stageFrame=int(progress+8),clock=c.run_pause_record_clock(r),position=Buffer.from(memory(c,c.run_gameplay_field(r,3),12));step(0,0x100);assert.equal(state(0),1);assert.equal(view().getUint32(progress+96,true)&0x10,0x10);const random=Buffer.from(memory(c,c.run_pause_random(r),8));
    for(let k=0;k<150;k++){step();assert.equal(int(progress+8),stageFrame);assert.equal(c.run_pause_record_clock(r),clock);assert.deepEqual(Buffer.from(memory(c,c.run_gameplay_field(r,3),12)),position);assert.deepEqual(Buffer.from(memory(c,c.run_pause_random(r),8)),random);checks+=4;}
    assert.equal(state(1),6);step(0,0x100);for(let k=0;k<13;k++)step();assert.equal(state(0),0);assert.equal(view().getUint32(progress+96,true)&0x10,0);assert.ok(int(progress+8)>stageFrame);checks+=5;
    // Save from a real paused run through the original delayed replay/name menus.
    if(scenario===0){step(0,0x100);for(let k=0;k<12;k++)step();c.run_pause_choose(r,2);step(0,1);assert.equal(state(1),9);for(let k=0;k<31;k++)step();step(0,0x10);step(0,1);for(let k=0;k<21;k++)step();assert.equal(state(1),11);for(let k=0;k<11;k++)step();c.run_pause_choose(r,3);step(0,1);assert.equal(state(1),12);for(let k=0;k<11;k++)step();c.run_pause_name_choose(r,0);step(0,1);c.run_pause_name_choose(r,90);step(0,1);assert.equal(state(1),11);assert.equal(state(7),3);assert.equal(string(c,c.run_pause_name(r)),'A       ');const n=c.run_pause_replay_size(r,3);assert.ok(n>0xa4);const replay=c.replay_create();try{assert.equal(c.replay_open(replay,c.run_pause_replay_data(r,3),n),1);assert.equal(c.replay_field(replay,1),character);}finally{c.replay_delete(replay);}checks+=6;
     // Saving seals this fixture's recorder; a fresh run exercises the death route below.
     results.push({character,mode,replayBytes:n});continue;
    }
    assert.equal(c.run_gameplay_capture(r,2),1,string(c,c.run_pause_error(r)));const savedStageFrame=int(progress+8);assert.equal(c.run_pause_die(r),1);for(let k=0;k<50&&state(0)===0;k++)step();assert.equal(state(0),2,'actual PlayerLife -> GameBattle -> RunPause Game Over');for(let k=0;k<12;k++)step();assert.equal(state(1),6);assert.equal(state(3),0);step(0,1);for(let k=0;k<13;k++)step();assert.equal(state(0),0);assert.equal(view().getUint32(progress+96,true)&0x10,0);if(mode){assert.equal(view().getUint32(progress+96,true)&0x10000,0x10000);assert.equal(int(progress+8),savedStageFrame+1,'snapshot restored; original retry entrance permits its first update');assert.equal(view().getUint32(player+24,true)&0x400,0x400);}else{assert.equal(int(player),2);assert.equal(int(player+36),3,'original first respawn update replenishes three bombs after the menu sets two');assert.equal(int(player+28),400);assert.equal(int(progress+28),1);assert.equal(int(c.run_gameplay_field(r,2)),0);}checks+=7;results.push({character,mode,chapterRestored:!!mode,legacyContinued:!mode});
   }finally{c.run_pause_delete(r);c.stage_assets_delete(a);}
  }
  report('run-pause',{passed:true,frames,checks,results,scope:'Actual original assets, run initialization, priority-10 pause callback in the same scheduler as session/battle, state/RNG/record-clock/position freeze and resume, real replay recorder file and decoded name, actual PlayerLife death reaches pause menu and real chapter snapshot restores on continue. Captures/audio/options/date use explicit fixture services. Legacy continued stock/power routing has separate native proof; independent whole-world/browser/mobile remains outstanding.'});
 }finally{for(const f of files)c.release(f.p);c.release(name);}
});
