import test from 'node:test';import assert from 'node:assert/strict';import{readFileSync}from 'node:fs';import{resolve}from 'node:path';import{core,oracle,memory,string,root,report}from './helpers.mjs';
test('TH15 original run time accounting matches mode/global unsigned centisecond counters, paused/replay gates and clock rebasing',async()=>{
 const c=await core(),m=await oracle(),f=c.run_time_create(),native=m.allocate(0x40000),scene=m.allocate(0x100),data=c.allocate(0x33b4c),baseline=readFileSync(resolve(root,'artifacts/cpp/analysis/score/original-saved-state.bin'));let values=[],reads=0,cases=0,checks=0;const f64=(at,value)=>{const b=Buffer.alloc(8);b.writeDoubleLE(value);m.write(at,b);};m.u32(0x4e9bc8,native);m.u32(0x4e9a94,scene);m.replace(0x472c90,'fixture monotonic run clock',()=>{const b=new Uint8Array(16);new DataView(b.buffer).setFloat64(0,values[reads++&1],true);m.cpu.reg_write(m.uc.X86_REG_XMM0,b);return 0;});
 const state=()=>Buffer.concat([Buffer.from(memory(c,c.run_time_blocks(f,0),5*0xa4a0)),Buffer.from(memory(c,c.run_time_blocks(f,1),0x42c))]);
 try{for(let character=0;character<5;character++)for(const mode of[0,0x100,0x200,0x10])for(const replay of[false,true])for(const destination of[-1,3,0,2,4,10,12])for(const delta of[-3,0,.009,.011,2.345,40,100000000]){
  const input=Buffer.from(baseline),base=character*0xa4a0+(mode&0x300?0:0x5188);input.writeBigUInt64LE(cases%3===0?0xfffffffffffffff0n:cases%2===0?0x00000000fffffffen:12345n,base+0x5158);input.writeBigUInt64LE(cases%2===0?0xfffffffffffffff0n:0x00000000fffffffen,5*0xa4a0+0x48);const origin=15.125,first=origin+delta,second=first+.0001;values=[first,second];reads=0;memory(c,data,input.length).set(input);assert.equal(c.run_time_configure(f,data,character,mode,replay,origin,first,second),1);m.write(native+8,input);m.i32(scene+0xb4,replay?1:0);m.i32(0x4e7ecc,destination);m.i32(0x4e7404,character);m.i32(0x4e7408,0);m.u32(0x4e7794,mode);f64(0x4e77a8,origin);m.call(0x43d2c0,{limit:1000000});assert.equal(c.run_time_account(f,destination),1,string(c,c.run_time_error(f)));const label=[character,mode,replay,destination,delta].join('/');assert.deepEqual(state(),Buffer.from(m.bytes(native+8,0x33b4c)),label+' complete saved records');assert.equal(c.run_time_origin(f),new DataView(m.bytes(0x4e77a8,8).buffer).getFloat64(0,true),label+' clock origin');assert.equal(c.run_time_reads(f),reads,label+' two separate wall clock calls');cases++;checks+=3;
 }
 report('run-play-time',{passed:true,cases,checks,originalFunctions:['0x43d2c0','0x4ba0ce'],scope:'Original elapsed-time function and unsigned conversion versus named records, five character banks, ordinary/Pointdevice modes, replay and destination gates, negative/sub-centisecond/large intervals, exact global and per-mode counters including low-word carry/full 64-bit wrap, rebasing and every preserved score/settings byte. Clock samples are deterministic platform inputs; whole application persistence remains separate.'});
 }finally{c.run_time_delete(f);c.release(data);m.close();}
});
