import test from 'node:test';import assert from 'node:assert/strict';import{readFileSync,readdirSync}from 'node:fs';import{resolve}from 'node:path';import{core,memory,string,root,report}from './helpers.mjs';
test('TH15 actual run construction uses original initial stocks and retained records, then scene completion queues the next stage after the callback',async()=>{
 const c=await core(),name=c.allocate(256),out=c.allocate(48),files=[];let frames=0,checks=0;const results=[];
 try{
  for(const n of readdirSync(resolve(root,'reference/assets')).filter(n=>/\.(anm|ecl|sht|std|msg)$/.test(n))){const bytes=readFileSync(resolve(root,'reference/assets',n)),p=c.allocate(bytes.length);memory(c,p,bytes.length).set(bytes);files.push({name:n,p,size:bytes.length});}
  const make=()=>{const a=c.stage_assets_create();for(const file of files){memory(c,name,file.name.length+1).set(Buffer.from(file.name+String.fromCharCode(0)));c.stage_assets_file(a,name,file.p,file.size);}return {a,r:c.run_construction_create(a)};};
  // Native 45b630 invokes 45d370 to clear stage-practice mode during ordinary playback.
  const view=()=>new DataView(c.memory.buffer),int=p=>view().getInt32(p,true),snapshot=r=>{const player=Buffer.from(memory(c,c.run_gameplay_field(r,1),48));player.fill(0,44,48);player.writeUInt32LE(player.readUInt32LE(24)&~0x30,24);return Buffer.concat([Buffer.from(memory(c,c.run_gameplay_field(r,3),12)),player,Buffer.from(memory(c,c.run_gameplay_field(r,2),60)),Buffer.from(memory(c,c.run_session_controls(r),280)),Buffer.from(memory(c,c.run_session_age(r),20))]);};
  for(let character=0;character<4;character++)for(let scenario=0;scenario<4;scenario++){
   const stage=scenario===2?2:scenario===3?7:1,flags=scenario===1?0x100:scenario===2?0x10:0,difficulty=stage===7?4:1,mode=flags&0x300?0:1,live=make(),played=make(),trajectory=[[],[]];let bytes;
   try{
    assert.equal(c.run_construction_load(live.r,stage,character,flags,difficulty,0,0),1,string(c,c.run_construction_error(live.r)));const stock=c.run_gameplay_field(live.r,1);assert.equal(int(stock),2);assert.equal(int(stock+28),stage>1?400:100,'original starting power');assert.equal(int(stock+36),3);assert.equal(int(stock+44),0,'recording owner mode');assert.equal(int(c.run_construction_record_field(live.r,character,mode,difficulty,stage,0)),1);assert.equal(memory(c,c.run_construction_record_field(live.r,character,mode,difficulty,stage,1)+5,1)[0],1);assert.equal(c.run_construction_queue(live.r,2),stage);checks+=7;
    const ids=Array.from({length:7},(_,i)=>c.run_gameplay_identity(live.r,i));
    for(let frame=0;frame<420;frame++){const held=1|(frame%93<31?0x40:frame%93<62?0x80:0);assert.equal(c.run_session_step(live.r,held,0,60,0),1,string(c,c.run_construction_error(live.r)));trajectory[0].push(snapshot(live.r));frames++;}
    let next=false;
    if(scenario<2){assert.equal(c.run_construction_complete(live.r),1,string(c,c.run_construction_error(live.r)));assert.equal(c.run_construction_queue(live.r,0),1);assert.equal(c.run_construction_queue(live.r,1),2);assert.equal(int(c.run_gameplay_field(live.r,0)),2);assert.equal(memory(c,c.run_construction_record_field(live.r,character,mode,difficulty,1,1)+4,1)[0],1,'normal clear written to shared record');assert.equal(c.run_construction_next(live.r),1,string(c,c.run_construction_error(live.r)));assert.deepEqual(Array.from({length:c.run_construction_exit_event_count(live.r)},(_,i)=>int(c.run_construction_exit_events(live.r)+i*4)),[1,2,3,4,5,6],'original retained-mode exit suppresses music command');assert.ok(c.run_construction_saved_size(live.r)>24,'actual saved score-file output');assert.equal(int(c.run_construction_exit_presentation(live.r)),1);assert.equal(view().getUint32(c.run_construction_exit_presentation(live.r)+4,true),0xff000000);checks+=4;assert.deepEqual(Array.from({length:7},(_,i)=>c.run_gameplay_identity(live.r,i)),ids);assert.equal(int(c.run_construction_record_field(live.r,character,mode,difficulty,2,0)),1,'next scene does not increment run count');checks+=6;next=true;
     for(let frame=0;frame<420;frame++){assert.equal(c.run_session_step(live.r,1|0x40,0,60,frame>=151),1,string(c,c.run_construction_error(live.r)));if(frame<150)assert.equal(c.run_session_input_active(live.r),0);else assert.equal(c.run_session_input_active(live.r),1);trajectory[1].push(frame>=150?snapshot(live.r):null);frames++;checks++;}
    }
    // Native 45c040 advances the clock but suppresses input sampling in Pointdevice mode (flags & 0x300).
    if(scenario===1){assert.equal(c.run_session_sample_count(live.r,1),0);assert.equal(c.run_session_sample_count(live.r,2),0);results.push({character,stage,flags,next,originalSampling:"suppressed in Pointdevice"});continue;}
    memory(c,name,12).set(Buffer.from('FACTORY'+character+String.fromCharCode(0)));assert.equal(c.run_session_export(live.r,name),1,string(c,c.run_construction_error(live.r)));bytes=Buffer.from(memory(c,c.run_session_data(live.r),c.run_session_size(live.r)));const p=c.allocate(bytes.length);memory(c,p,bytes.length).set(bytes);
    try{
     assert.equal(c.run_construction_load(played.r,stage,character,flags,difficulty,p,bytes.length),1,string(c,c.run_construction_error(played.r)));assert.equal(int(c.run_gameplay_field(played.r,1)+24)&0x30,0,'native ordinary replay mode');assert.equal(int(c.run_gameplay_field(played.r,1)+44),1,'playback owner mode prevents history writes');assert.equal(int(c.run_construction_record_field(played.r,character,mode,difficulty,stage,0)),0,'replay does not count as a play');assert.equal(memory(c,c.run_construction_record_field(played.r,character,mode,difficulty,stage,1)+5,1)[0],0,'replay does not unlock visited stage');checks+=3;
     for(let frame=0;frame<420;frame++){assert.equal(c.run_session_step(played.r,0,0,60,0),1,string(c,c.run_construction_error(played.r)));assert.deepEqual(snapshot(played.r),trajectory[0][frame],character+'/'+scenario+'/'+frame);frames++;checks++;}
     if(next){assert.equal(c.run_construction_complete(played.r),1);assert.equal(memory(c,c.run_construction_record_field(played.r,character,mode,difficulty,1,1)+4,1)[0],0,'replay clear does not alter records');assert.equal(c.run_construction_next(played.r),1,string(c,c.run_construction_error(played.r)));for(let frame=0;frame<420;frame++){assert.equal(c.run_session_step(played.r,0,0,60,frame>=151),1,string(c,c.run_construction_error(played.r)));if(trajectory[1][frame])assert.deepEqual(snapshot(played.r),trajectory[1][frame],'retained scene '+character+'/'+scenario+'/'+frame);frames++;checks++;}}
    }finally{c.release(p);}
    results.push({character,stage,flags,next,replayBytes:bytes.length});
   }finally{c.run_construction_delete(live.r);c.run_construction_delete(played.r);c.stage_assets_delete(live.a);c.stage_assets_delete(played.a);}
  }
  report('run-construction',{passed:true,frames,checks,results,scope:'Actual initialization controller, stocks/power/records, real resource owners and scheduler, imported recording restores owner mode and prevents record writes. Actual message completion reaches real HUD bonus and player-option finish before queuing next scene; retained managers run original 120+30 entrance and replay both scenes. Audio/capture/checkpoint storage are explicit fixture boundaries, invulnerability and forced clear retained; independent whole-game native parity/application remains outstanding.'});
 }finally{for(const f of files)c.release(f.p);c.release(name);c.release(out);}
});
