import test from'node:test';import assert from'node:assert/strict';import{readFileSync,readdirSync}from'node:fs';import{resolve}from'node:path';import{core,memory,string,root,report}from'./helpers.mjs';
test('TH15 actual stage scheduler combines background, objects, captions, pause and original screen targets',async()=>{
 const c=await core(),name=c.allocate(256),files=[];let frames=0,checks=0;const results=[];
 try{for(const n of readdirSync(resolve(root,'reference/assets')).filter(n=>/\.(anm|ecl|sht|std|msg)$/.test(n))){const bytes=readFileSync(resolve(root,'reference/assets',n)),p=c.allocate(bytes.length);memory(c,p,bytes.length).set(bytes);files.push({name:n,p,size:bytes.length});}
 for(let character=0;character<4;character++)for(const stage of[1,2,3,4,5,6,7]){const a=c.stage_assets_create(),d=c.run_draw_create(a),r=c.run_draw_run(d);try{for(const f of files){memory(c,name,f.name.length+1).set(Buffer.from(f.name+'\0'));c.stage_assets_file(a,name,f.p,f.size);}assert.equal(c.run_construction_load(r,stage,character,0,stage===7?4:1,0,0),1,string(c,c.run_construction_error(r)));assert.equal(c.run_draw_attach(d),1,string(c,c.run_draw_error(d)));const dv=()=>new DataView(c.memory.buffer),progress=c.run_gameplay_field(r,0),step=(held=0,pressed=0,repeated=0)=>{assert.equal(c.run_draw_step(d,held,pressed,repeated),1,stage+'/'+character+'/'+frames+' '+string(c,c.run_draw_error(d)));frames++;};
 for(let frame=0;frame<900;frame++)step(frame<180?0:1|(frame%90<30?0x10:frame%90<60?0x20:0)|4);const before=dv().getInt32(progress+8,true),position=Buffer.from(memory(c,c.run_gameplay_field(r,3),12)),clock=c.run_pause_record_clock(r);step(0,0x100);for(let frame=0;frame<40;frame++){step();assert.equal(dv().getInt32(progress+8,true),before);assert.deepEqual(Buffer.from(memory(c,c.run_gameplay_field(r,3),12)),position);assert.equal(c.run_pause_record_clock(r),clock);checks+=3;}step(0,0x100);for(let frame=0;frame<24;frame++)step(1);assert.equal(c.run_pause_state(r,0),0);assert.ok(dv().getInt32(progress+8,true)>before);const stats=Array.from(new Uint32Array(c.memory.buffer,c.run_draw_statistics(d),5));assert.ok(stats[1]>100);assert.ok(stats[2]>100000);assert.ok(stats[3]>=stats[0]*11);assert.ok(stats[4]<320);checks+=6;results.push({character,stage,frames:stats[0],batches:stats[1],vertexBytes:stats[2],targetCommands:stats[3],queuedCaptions:stats[4]});}finally{c.run_draw_delete(d);c.stage_assets_delete(a);}}
 report('run-draw',{passed:true,frames,checks,results,scope:'Controlled actual C++ stage/gameplay/pause scheduler with all four characters and seven original stage asset sets. Real object drawing, 38 ANM layers, three caption spaces, ten original compositor passes, text.anm target factory and paused scene drawn and resumed while gameplay/record clock/position freeze. Geometry submission is captured by semantic graphics fixture; audio/fonts/file I/O/captured pause image remain fixture services. This is integration coverage, not independent original whole-world or complete SDL/browser game proof.'});
 }finally{for(const f of files)c.release(f.p);c.release(name);}
});
