import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {resolve} from 'node:path';import {core,oracle,memory,string,root,report,enableNativeMath} from './helpers.mjs';import {resourceLoader,nativePool,prepareBank,compareAnm} from './anm-oracle.mjs';import {nativeGraphics} from './rendering-oracle.mjs';
test('TH15 pause and result captures preserve original rectangle arithmetic and deferred frame timing',async()=>{
 const c=await core(),m=await oracle();enableNativeMath(m);const a=c.anm_manager_create(),nm=nativePool(m),gfx=nativeGraphics(m,nm),loader=resourceLoader(m),bytes=readFileSync(resolve(root,'reference/assets/text.anm')),p=c.allocate(bytes.length);memory(c,p,bytes.length).set(bytes);assert.equal(c.anm_manager_load(a,0,p,bytes.length),1);c.release(p);const bank=prepareBank(m,loader,'text.anm',bytes,nm,0),f=c.scene_capture_create(a,0),handle=c.allocate(4),pause=m.allocate(0x400);let nativeCalls=[],cases=0,checks=0;
 const texture=m.u32(m.u32(bank+0x124)),vt=m.u32(texture),surface=m.allocate(4),svt=m.allocate(0x60);m.u32(surface,svt);m.u32(vt+0x48,m.registerImport({dll:'fixture',name:'capture destination surface',argc:3,handler:()=>{m.u32(m.u32(m.reg('ESP')+12),surface);return 0;}}));for(const off of [8,0x54])m.u32((off===8?svt:vt)+off,m.registerImport({dll:'fixture',name:'surface ownership '+off,argc:off===8?1:2,handler:()=>0}));
 m.u32(0x4be2bc,m.registerImport({dll:'fixture',name:'capture native GPU resample request',argc:8,handler:()=>{const sp=m.reg('ESP'),dst=m.u32(sp+12),src=m.u32(sp+24);assert.equal(m.u32(sp+28),2);nativeCalls.push(m.u32(sp+16)===0x20?3:-1,m.u32(m.u32(bank+0x11c)+m.u32(nm+0xec+(m.u32(pause+0x1e8)&0x1fff)*0x620+0x2c)*0x44+4),...Array.from({length:4},(_,i)=>m.i32(src+i*4)),...Array.from({length:4},(_,i)=>m.i32(dst+i*4)));return 0;}}));
 m.u32(0x4e7f00,bank);m.u32(0x4e7980,0x20);m.u32(0x4e7984,0x30);m.u32(pause+0x1e8,0);new Uint32Array(c.memory.buffer,handle,1)[0]=0;
 const calls=()=>Array.from(new Int32Array(c.memory.buffer,c.scene_capture_calls(f),c.scene_capture_count(f)));
 try{for(let i=0;i<48;i++){const scale=[1,1.5,2,.75][i%4],x=320+(i%7)*13,y=16+(i%9)*3;c.scene_capture_reset(f);nativeCalls=[];c.scene_capture_configure(f,scale,x,y);m.f32(0x51bc04,scale);m.u32(0x51bc18,x);m.u32(0x51bc1c,y);
 assert.equal(c.scene_capture_run(f,handle,0),1,string(c,c.scene_capture_error(f)));m.call(0x450bf0,{ecx:pause});assert.deepEqual(calls(),nativeCalls,'pause rect '+i);compareAnm(c,m,c.anm_manager_find(a,new Uint32Array(c.memory.buffer,handle,1)[0]),m.call(0x488510,{ecx:nm,args:[m.u32(pause+0x1e8)]}),i+' screenshot animation');checks+=2;cases++;
 c.scene_capture_reset(f);nativeCalls=[];for(let j=0;j<4;j++)m.i32(nm+0x20+j*0x28,-1);
 const nh=m.u32(pause+0x1e8),ch=new Uint32Array(c.memory.buffer,handle,1)[0];for(let j=0;j<6;j++){const rect=[Math.trunc(32*scale)+j,Math.trunc(16*scale)-j,Math.trunc(384*scale),Math.trunc(448*scale)];assert.equal(c.scene_capture_queue(f,ch,...rect),1);m.call(0x452c20,{args:[nh,...rect]});}assert.equal(c.scene_capture_pending(f),4);assert.deepEqual(calls(),[]);assert.equal(c.scene_capture_finish(f),1);m.call(0x471130);assert.deepEqual(calls(),nativeCalls,'queued screenshot '+i);assert.equal(c.scene_capture_pending(f),0);assert.equal(c.scene_capture_finish(f),1);assert.equal(calls().length,40);checks+=6;cases++;
 }
 report('scene-capture',{passed:true,cases,checks,originalFunctions:['0x450bf0','0x452c20','0x452bb0','0x471130'],scope:'Actual original text.anm script52 and complete ANM state; immediate pause rectangle arithmetic at four scales and varying viewport offsets; six queued requests retain the original four-slot limit, order and frame-end consumption. Captured native surface calls are compared at the graphics boundary; GPU pixels are verified separately.'});
 }finally{c.release(handle);c.scene_capture_delete(f);c.anm_manager_delete(a);m.close();}
});
