import test from 'node:test';import assert from 'node:assert/strict';import{readFileSync}from 'node:fs';import{resolve}from 'node:path';import{core,oracle,memory,string,root,report}from './helpers.mjs';
test('TH15 named high-score registration matches original full-row shifting, unsigned ties, date/slowdown details and preserved spare bytes',async()=>{
 const c=await core(),m=await oracle(),f=c.records_create(),native=m.allocate(0x40000),graphics=m.allocate(0x100),data=c.allocate(0x33b4c),name=c.allocate(9),baseline=readFileSync(resolve(root,'artifacts/cpp/analysis/score/original-saved-state.bin'));let cases=0,checks=0,dateCalls=0;
 const state=()=>Buffer.concat([Buffer.from(memory(c,c.records_blocks(f,0),5*0xa4a0)),Buffer.from(memory(c,c.records_blocks(f,1),0x42c))]),f64=(at,value)=>{const b=Buffer.alloc(8);b.writeDoubleLE(value);m.write(at,b);};m.u32(0x4e9bc8,native);m.u32(0x4e9a88,graphics);m.replace(0x490eda,'fixture score timestamp',()=>{const out=m.u32(m.reg('ESP')+4);m.u32(out,0x12345678);m.u32(out+4,0x9abcdef0);dateCalls++;return 0;});
 try{for(let character=0;character<5;character++)for(const legacy of[false,true])for(let rank=0;rank<6;rank++)for(const score of[1500000,1000000,950000,650000,100000,99999,0,0xffffffff]){
  const bytes=Buffer.from(baseline),base=character*0xa4a0+(legacy?0x5188:0)+0x10+rank*320;
  for(let row=0;row<10;row++){for(let b=0;b<32;b++)bytes[base+row*32+b]=(row*31+b*17+cases)&255;bytes.writeUInt32LE(1000000-row*100000,base+row*32);}
  memory(c,data,bytes.length).set(bytes);assert.equal(c.records_import_blocks(f,data),1);m.write(native+8,bytes);const stage=[1,4,7,9,255][cases%5],continues=[0,3,9,255,257,-1][cases%6],delivered=[0,1,7.25,299,1200,-5][cases%6],requested=[1,3,11,300,1000,3][cases%6],deaths=cases%2?-cases:cases;
  m.u32(0x4e7794,legacy?0:0x100);m.i32(0x4e7410,rank);m.u32(0x4e740c,score);m.i32(0x4e7414,continues);m.i32(0x4e73f0,stage);m.i32(0x4e7594,deaths);f64(graphics+0x20,delivered);f64(graphics+0x28,requested);dateCalls=0;const expected=m.call(0x44fdc0,{ecx:native+character*0xa4a0+8})|0,actual=c.records_insert_score(f,character,legacy,rank,score|0,stage,continues,delivered,requested,deaths);
  assert.equal(actual,expected,'rank '+cases+' '+string(c,c.records_error(f)));assert.equal(dateCalls,actual<0?0:1,'date only sampled after qualifying');assert.deepEqual(state(),Buffer.from(m.bytes(native+8,0x33b4c)),cases+' complete records and spare-byte movement');checks+=3;
  if(actual>=0){const value=Buffer.alloc(9,32);if(cases%3===0){value.set(Buffer.from('SHORT'));value[5]=0;}else value.set(Buffer.from('NAME'+String(cases).padStart(4,'0')));value[8]=0;memory(c,name,9).set(value);assert.equal(c.records_score_name(f,character,legacy,rank,actual,name),1);const end=value.indexOf(0)+1;m.write(native+8+base+actual*32+6,value.subarray(0,end));m.write(native+0x33734,value.subarray(0,end));assert.deepEqual(state(),Buffer.from(m.bytes(native+8,0x33b4c)),cases+' score-name suffix preservation');checks++;}
  cases++;
 }
 report('score-registration',{passed:true,cases,checks,originalFunctions:['0x44fdc0'],scope:'Actual original insertion and metadata writes, every byte of five score blocks plus settings; five character banks, both modes, six ranks, unsigned/tied/no-place scores, 32-byte shifts including preserved byte 15, stage/continue truncation, timestamp and original SSE slowdown arithmetic. Name copy checks use directly observed original C-string rules; full name-entry controller/application remains separate.'});
 }finally{c.records_delete(f);c.release(data);c.release(name);m.close();}
});
