import test from'node:test';import assert from'node:assert/strict';import{readFileSync}from'node:fs';import{resolve}from'node:path';import{core,oracle,memory,string,root,report,enableNativeMath}from'./helpers.mjs';import{resourceLoader,nativePool,prepareBank,compareAnm}from'./anm-oracle.mjs';import{nativeGraphics}from'./rendering-oracle.mjs';
test('TH15 screen targets use original text.anm captures and resolution-dependent factory',async()=>{
 const c=await core(),m=await oracle();enableNativeMath(m);const a=c.anm_manager_create(),nm=nativePool(m),gfx=nativeGraphics(m,nm),loader=resourceLoader(m),r=c.anm_renderer_create(),data=readFileSync(resolve(root,'reference/assets/text.anm')),p=c.allocate(data.length);memory(c,p,data.length).set(data);assert.equal(c.anm_manager_load(a,5,p,data.length),1);c.release(p);const bank=prepareBank(m,loader,'text.anm',data,nm,5),f=c.screen_compositor_create(a,r),native=Array.from({length:4},()=>m.allocate(0x608)),texture=m.u32(m.u32(bank+0x124)+0x30),vt=m.u32(texture);let checks=0,cases=0,t=0,requests=[];
 m.u32(vt+0x48,m.registerImport({dll:'fixture',name:'original render target surface ownership',argc:3,handler:()=>{const sp=m.reg('ESP'),out=m.u32(sp+12);requests.push(out);m.u32(out,out===0x4e797c?0x10:0x20);return 0;}}));
 try{for(let sample=0;sample<24;sample++){const width=[640,960,1280][sample%3],scale=width/640,height=480*scale;requests=[];gfx.reset();c.anm_renderer_reset(r);c.screen_compositor_configure(f,0,0xff000000,width,height,scale);t=c.screen_targets_create(a,f,5);m.u32(0x4e797c,0);m.u32(0x4e7980,0);m.u32(0x4e7984,0x30);m.u32(0x4e7f00,bank);m.u32(0x51bbfc,width);m.u32(0x51bc00,height);m.f32(0x51bc04,scale);m.call(0x44e2f0,{ecx:0x4e77d0});for(let i=0;i<4;i++){m.call(0x40db10,{ecx:native[i]});m.u32(0x4e798c+i*4,native[i]);}
 assert.equal(c.screen_targets_prepare(t),1,string(c,c.screen_targets_error(t)));m.call(0x44f300,{ecx:0x4e77d0});assert.deepEqual(requests,[0x4e797c,0x4e7980]);for(let i=0;i<4;i++)compareAnm(c,m,c.screen_targets_capture(t,i),native[i],sample+' original capture '+i);checks+=5;
 const before=requests.length;assert.equal(c.screen_targets_prepare(t),1);m.call(0x44f300,{ecx:0x4e77d0});assert.equal(requests.length,before);for(let i=0;i<4;i++)compareAnm(c,m,c.screen_targets_capture(t,i),native[i],sample+' retained capture '+i);checks+=5;
 c.screen_targets_deactivate(t);m.u32(0x4e797c,0);m.u32(0x4e7980,0);assert.equal(c.screen_targets_prepare(t),1);m.call(0x44f300,{ecx:0x4e77d0});assert.equal(requests.length,before+2);for(let i=0;i<4;i++)compareAnm(c,m,c.screen_targets_capture(t,i),native[i],sample+' reactivated capture '+i);checks+=5;c.screen_targets_delete(t);t=0;cases++;}
 report('screen-targets',{passed:true,cases,checks,originalFunctions:['0x44f300','0x40b880','0x477e10'],scope:'Actual original offscreen factory and text.anm scripts at 640/960/1280 widths; all four capture animations, timer/UV/transform/flag bytes, 960-wide nearest-filter exception, two actual surface lookup indices, active camera refresh and reuse after deactivation. Surface creation is captured at the graphics ownership boundary; full GPU composite rasterization remains separate.'});
 }finally{if(t)c.screen_targets_delete(t);c.screen_compositor_delete(f);c.anm_renderer_delete(r);c.anm_manager_delete(a);m.close();}
});
