import test from'node:test';import assert from'node:assert/strict';import{readFileSync}from'node:fs';import{resolve}from'node:path';import{core,oracle,memory,string,root,report,enableNativeMath}from'./helpers.mjs';import{resourceLoader,nativePool,prepareBank,compareAnm}from'./anm-oracle.mjs';import{nativeGraphics}from'./rendering-oracle.mjs';
test('TH15 screen compositor preserves original ten target/camera passes and capture submissions',async()=>{
 const c=await core(),m=await oracle();enableNativeMath(m);const a=c.anm_manager_create(),nm=nativePool(m),gfx=nativeGraphics(m,nm),loader=resourceLoader(m),r=c.anm_renderer_create(),data=readFileSync(resolve(root,'reference/assets/ascii.anm')),p=c.allocate(data.length);memory(c,p,data.length).set(data);assert.equal(c.anm_manager_load(a,5,p,data.length),1);c.release(p);const bank=prepareBank(m,loader,'ascii.anm',data,nm,5),f=c.screen_compositor_create(a,r),vms=Array.from({length:4},()=>c.anm_vm_create()),native=Array.from({length:4},()=>m.allocate(0x608)),device=m.u32(0x4e77d8),vt=m.u32(device);let target=0,events=[],cases=0,checks=0,vertices=0;
 const capture=(kind,color,rect)=>events.push(kind,target,color>>>0,rect?1:0,...(rect?[m.u32(rect),m.u32(rect+4),m.u32(rect+8)-m.u32(rect),m.u32(rect+12)-m.u32(rect+4)]:[0,0,0,0]));
 m.u32(vt+0x94,m.registerImport({dll:'fixture',name:'observe original compositor render target',argc:3,handler:()=>{const handle=m.u32(m.reg('ESP')+12);target=handle===0x10?1:handle===0x20?2:0;capture(0,0,0);return 0;}}));
 m.u32(vt+0xac,m.registerImport({dll:'fixture',name:'observe original compositor color/depth clear',argc:7,handler:()=>{const sp=m.reg('ESP'),flags=m.u32(sp+16);capture(flags===2?2:1,flags===2?0:m.u32(sp+20),m.u32(sp+12));return 0;}}));
 const custom=[m.registerImport({dll:'fixture',name:'native background replacement',argc:0,handler:()=>{capture(3,0,0);return 0;}}),m.registerImport({dll:'fixture',name:'native playfield replacement',argc:0,handler:()=>{capture(3,1,0);return 0;}})];
 const addresses=[0x44e8d0,0x44eb90,0x44ea80,0x44ed30,0x44ec30,0x44ee80,0x44edd0,0x44efb0,0x44ef50,0x44f000];
 try{for(let sample=0;sample<96;sample++){const scale=[1,1.5,2][sample%3],width=640*scale,height=480*scale,active=sample%7!==0,color=(0xff012345^sample*877)>>>0;gfx.reset();c.anm_renderer_reset(r);events=[];target=0;c.screen_compositor_configure(f,active,color,width,height,scale);m.f32(0x51bc04,scale);m.u32(0x51bbfc,width);m.u32(0x51bc00,height);m.call(0x44e2f0,{ecx:0x4e77d0});m.u32(0x4e797c,active?0x10:0);m.u32(0x4e7980,0x20);m.u32(0x4e7984,0x30);m.u32(0x4e8214,color);for(let i=0;i<4;i++){c.screen_compositor_capture(f,i,vms[i]);assert.equal(c.anm_manager_bind(a,vms[i],5,i),1);m.call(0x40db10,{ecx:native[i]});m.call(0x40b880,{ecx:bank,args:[native[i],i]});m.u32(0x4e798c+i*4,native[i]);const dv=new DataView(c.memory.buffer),visual=c.anm_vm_visual(vms[i]),vars=c.anm_vm_variables(vms[i]),rgba=((sample*19+i*37)<<24|0xaabbcc)>>>0;dv.setUint32(visual+96,rgba,true);m.u32(native[i]+0x538,rgba);for(let k=0;k<3;k++){const value=[220+i*23,160+i*19,0][k];dv.setFloat32(vars+64+k*4,value,true);m.f32(native[i]+0x38+k*4,value);}const offsets=[width/2,16*scale,width/2,16*scale];for(let k=0;k<4;k++){dv.setInt32(c.anm_environment_offsets(c.anm_manager_environment(a))+k*4,offsets[k],true);m.i32(0x51bc18+k*4,offsets[k]);}}
 for(let view=0;view<4;view++){const x=sample%5-2,y=(sample*3)%7-3;c.screen_compositor_offset(f,view,x,y);const at=[0x4e7a10,0x4e7b3c,0x4e7c68,0x4e7d94][view]+0xfc;m.f32(at,x);m.f32(at+4,y);}
 for(let i=0;i<2;i++){const replace=!!(sample&(8<<i));m.u32(i?0x4e9ba8:0x4e9bac,replace?custom[i]:0);c.screen_compositor_replacement(f,i,replace);}
 for(let pass=0;pass<addresses.length;pass++){assert.equal(m.call(addresses[pass],{ecx:0x4e77d0}),1);assert.equal(c.screen_compositor_pass(f,pass),1,sample+'/'+pass+' '+string(c,c.screen_compositor_error(f)));assert.deepEqual(Array.from(new Uint32Array(c.memory.buffer,c.screen_compositor_events(f),c.screen_compositor_event_count(f))),events,sample+'/'+pass+' original target and clear order');for(let i=0;i<4;i++)compareAnm(c,m,vms[i],native[i],sample+'/'+pass+' capture animation '+i);const expected=Buffer.concat(gfx.draws().map(d=>d.bytes)),actual=Buffer.concat(Array.from({length:c.anm_renderer_calls(r)},(_,i)=>Buffer.from(memory(c,c.anm_renderer_history(r,i),c.anm_renderer_history_size(r,i)))));assert.deepEqual(actual,expected,sample+'/'+pass+' complete capture vertices');const env=c.anm_manager_environment(a),dv=new DataView(c.memory.buffer);for(let k=0;k<4;k++)assert.equal(dv.getInt32(c.anm_environment_offsets(env)+k*4,true),m.i32(0x51bc18+k*4),sample+'/'+pass+' origin '+k);if(active&&pass>=0){const size=Array.from(new Float32Array(c.memory.buffer,c.screen_compositor_size(f),2));assert.deepEqual(size,[m.i32(0x51bc14),m.i32(0x51bc10)],sample+'/'+pass+' playfield size');}for(let view=0;view<4;view++){const at=[0x4e7a10,0x4e7b3c,0x4e7c68,0x4e7d94][view]+0xfc;assert.deepEqual(Buffer.from(memory(c,c.screen_compositor_view_offset(f,view),8)),Buffer.from(m.bytes(at,8)),sample+'/'+pass+' camera offset '+view);}checks+=15;}vertices+=gfx.draws().reduce((n,d)=>n+d.bytes.length/d.stride,0);cases++;}
 report('screen-compositor',{passed:true,cases,checks,vertices,originalFunctions:addresses.map(a=>'0x'+a.toString(16)),scope:'Actual original ten compositor callbacks: frame clear, alternating targets, color-preserving depth clears, original callback priority inputs, all four real ANM capture submissions, original replacement callbacks, screen/playfield origin and size transitions, three resolutions and missing offscreen-target path. GPU target commands and complete CPU vertex streams are captured byte-for-byte; actual captured-scene rasterization and native offscreen-resource factory remain separate.'});
 }finally{c.screen_compositor_delete(f);for(const v of vms)c.anm_vm_delete(v);c.anm_renderer_delete(r);c.anm_manager_delete(a);m.close();}
});
