import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {resolve} from 'node:path';import {core,oracle,memory,string,root,report,enableNativeMath,enableOriginalVectorMath} from './helpers.mjs';import {ins,resource} from './ecl-fixtures.mjs';import {resourceLoader,nativePool,nativeInstances,prepareBank,compareAnm} from './anm-oracle.mjs';
test('TH15 screen distortion owns original capture/strip animation order, real geometry and retirement',async()=>{
 const c=await core(),m=await oracle();enableNativeMath(m);const lib=enableOriginalVectorMath(m);for(const entry of m.image.imports)if(entry.dll==='d3dx9_43.dll'&&entry.name==='D3DXVec3Normalize')m.u32(entry.address,lib.exports.get(entry.name));const anm=c.anm_manager_create(),nm=nativePool(m),loader=resourceLoader(m),text=m.allocate(0x19270),owner=m.allocate(0x1c),enemy=m.allocate(0x4530);const program=c.program_create(),wait=resource({wait:Buffer.concat([ins(40,[0]),ins(0,[],0,1000000)])}).bytes,pp=c.allocate(wait.length),request=c.allocate(84),name=c.allocate(8),savedPool=c.anm_checkpoint_create(),file=c.player_checkpoint_file_create(),fileBuffer=c.allocate(4*1024*1024),nativeSaved=m.allocate(0x1c),nativeSavedStrips=m.allocate(64),nativeOut=m.allocate(4*1024*1024),nativeUsed=m.allocate(4),nativeRestored=m.allocate(0x1c),nativeTemp=m.allocate(4),liveOut=m.allocate(4);memory(c,pp,wait.length).set(wait);assert.equal(c.program_attach(program,pp,wait.length),0);const enemies=c.enemy_manager_create(program),saved=c.enemy_checkpoint_create(enemies,anm,savedPool);memory(c,name,5).set(Buffer.from('wait\0'));memory(c,request,84).fill(0);assert.equal(c.enemy_manager_spawn(enemies,name,request),1);let object=0,frames=0,checks=0,fileCases=0;
 try{m.u32(0x4e9a58,text);m.u32(0x4ca620,0x4e73e8);m.f32(0x4e73e8,1);m.u32(0x4e797c,1);
 for(const[name,id]of [['ascii.anm',2],['text.anm',6]]){const b=readFileSync(resolve(root,'reference/assets',name)),p=c.allocate(b.length);memory(c,p,b.length).set(b);assert.equal(c.anm_manager_load(anm,id,p,b.length),1,string(c,c.anm_manager_error(anm)));c.release(p);const bank=prepareBank(m,loader,name,b,nm,id);if(id===2){assert.equal(c.anm_manager_fallback(anm,2),1);m.u32(text+0x19258,bank);}else m.u32(0x4e7f00,bank);}
 object=c.screen_grid_object_create(anm);assert.equal(c.screen_grid_object_initialize(object,6),1);m.call(0x422bf0,{ecx:owner,args:[0,17,0]});m.u32(enemy+0x44bc,owner);for(const[address,value]of [[0x51bbfc,640],[0x51bc00,480],[0x51bc20,320],[0x51bc24,16],[0x51bc08,128]])m.i32(address,value);
 const compare=label=>{const list=nativeInstances(m,nm,0);assert.equal(c.anm_manager_count(anm,0),list.length,label+' queue size');list.forEach((np,i)=>{const h=m.u32(np+0x544);assert.equal(c.anm_manager_order(anm,0,i)>>>0,h);compareAnm(c,m,c.anm_manager_find(anm,h),np,label+' vm '+i);checks++;});};compare('create');assert.equal(c.screen_grid_object_handle(object,0)>>>0,m.u32(owner+8));for(let i=0;i<16;i++)assert.equal(c.screen_grid_object_handle(object,i+1)>>>0,m.u32(m.u32(owner+0xc)+i*4));
 const state=Buffer.alloc(24);state.writeFloatLE(160);state.writeFloatLE(16,4);state.writeUInt32LE(0xff7f9fff,8);state[20]=1;memory(c,c.screen_grid_object_field(object,0),24).set(state);m.write(enemy+0x44c4,state.subarray(0,20));
 for(let frame=0;frame<96;frame++){const rate=[.5,1,1.25][frame%3],position=[Math.fround(frame*.5-24),Math.fround(64+frame*.375),0];const dv=()=>new DataView(c.memory.buffer);position.forEach((v,i)=>{dv().setFloat32(c.screen_grid_object_field(object,2)+i*4,v,true);m.f32(enemy+0x44+i*4,v);});m.f32(0x4e73e8,rate);m.call(0x428220,{ecx:enemy});m.call(0x422f20,{ecx:owner});assert.equal(c.screen_grid_object_update(object,rate),1);assert.deepEqual(Buffer.from(memory(c,c.screen_grid_object_field(object,0),20)),Buffer.from(m.bytes(enemy+0x44c4,20)),frame+' state');assert.deepEqual(Buffer.from(memory(c,c.screen_grid_object_field(object,3),17*17*28)),Buffer.from(m.bytes(m.u32(owner+0x14),17*17*28)),frame+' grid');for(let i=0;i<16;i++){const vm=c.anm_manager_find(anm,c.screen_grid_object_handle(object,i+1)),np=m.u32(m.u32(owner+0x10)+i*4);assert.deepEqual(Buffer.from(memory(c,c.anm_vm_screen_vertices(vm),17*2*28)),Buffer.from(m.bytes(m.u32(np+0x5c4),17*2*28)),frame+' strip '+i);}checks+=18;for(let alt=0;alt<2;alt++){assert.equal(c.anm_manager_update(anm,alt,rate),1,string(c,c.anm_manager_error(anm)));m.call(alt?0x487890:0x487740,{ecx:nm});}if([19,49,95].includes(frame)){
 c.anm_checkpoint_clear(savedPool);m.call(0x489590,{limit:100000000});assert.equal(c.enemy_manager_attach_grid(enemies,0,object),1);assert.equal(c.enemy_checkpoint_capture(saved),1,string(c,c.enemy_checkpoint_error(saved)));m.write(nativeSaved,m.bytes(owner,0x1c));m.u32(nativeSaved+0xc,nativeSavedStrips);
 for(let i=0;i<17;i++){const handle=i?m.u32(m.u32(owner+0xc)+(i-1)*4):m.u32(owner+8),vm=m.call(0x488510,{ecx:nm,args:[handle]})>>>0;m.call(0x489740,{ecx:nm,args:[nativeTemp,vm,0,0],limit:100000000});m.u32(i?nativeSavedStrips+(i-1)*4:nativeSaved+8,m.u32(nativeTemp));}
 assert.equal(c.enemy_checkpoint_file_write(file,saved),1,string(c,c.enemy_checkpoint_error(saved)));const bytes=Buffer.from(memory(c,c.player_checkpoint_file_bytes(file),c.player_checkpoint_file_size(file))),offset=0xa8+0x574c;m.u32(nativeUsed,0);m.view(nativeOut,4*1024*1024).fill(0);m.call(0x425a60,{ecx:nativeSaved,args:[nativeOut,nativeUsed],limit:100000000});const nb=Buffer.from(m.bytes(nativeOut,m.u32(nativeUsed)));assert.equal(bytes.length-offset,nb.length,'grid file length');for(const[at,length]of [[0,8],[0x1c,64],[0x1c+128,17*17*40]])assert.deepEqual(bytes.subarray(offset+at,offset+at+length),nb.subarray(at,at+length),frame+' grid file region '+at.toString(16));
 // Each native tree carries saved pool addresses and geometry pointers. Their
 // logical animation/geometry bytes are checked after both readers run.
 memory(c,fileBuffer,bytes.length).set(bytes);assert.equal(c.enemy_checkpoint_file_read(file,saved,fileBuffer,bytes.length-1),0);assert.equal(c.enemy_checkpoint_file_read(file,saved,fileBuffer,bytes.length),1,string(c,c.enemy_checkpoint_error(saved)));assert.equal(c.player_checkpoint_file_consumed(file),bytes.length);m.u32(nativeUsed,0);m.call(0x425be0,{ecx:nativeRestored,args:[nativeOut,nativeUsed],limit:100000000});assert.equal(c.enemy_checkpoint_restore(saved),1,string(c,c.enemy_checkpoint_error(saved)));for(const[kind,at,length]of [[1,0x14,17*17*28],[2,0x18,17*17*12]])assert.deepEqual(Buffer.from(memory(c,c.enemy_manager_grid_field(enemies,0,kind),length)),Buffer.from(m.bytes(m.u32(nativeRestored+at),length)),frame+' restored grid '+kind);
 const restored=[];for(let i=0;i<17;i++){const sh=i?m.u32(m.u32(nativeRestored+0xc)+(i-1)*4):m.u32(nativeRestored+8);m.call(0x489820,{args:[liveOut,sh],limit:100000000});const handle=c.enemy_manager_grid_handle(enemies,0,i)>>>0;assert.equal(handle,m.u32(liveOut));const vm=c.anm_manager_find(anm,handle),np=m.call(0x488510,{ecx:nm,args:[handle]})>>>0;compareAnm(c,m,vm,np,frame+' restored grid VM '+i);if(i)assert.deepEqual(Buffer.from(memory(c,c.anm_vm_screen_vertices(vm),17*2*28)),Buffer.from(m.bytes(m.u32(np+0x5c4),17*2*28)),frame+' restored strip '+i);restored.push([vm,np]);}for(const[vm,np]of restored){assert.equal(c.anm_manager_destroy_tree(anm,vm),1);m.call(0x488820,{ecx:nm,args:[np],limit:100000000});}fileCases++;checks+=42;
 }if(frame%16===0)compare('frame '+frame);frames++;}
 assert.equal(c.screen_grid_object_retire(object),1);m.call(0x40dd40,{ecx:owner});compare('retire');assert.equal(c.anm_manager_update(anm,0,1),1);m.call(0x487740,{ecx:nm});compare('retired update');assert.equal(c.anm_manager_count(anm,0),0);report('screen-grid-object',{passed:true,frames,checks,fileCases,originalFunctions:['0x422bf0','0x44f040','0x428220','0x422f20','0x40dd40'],scope:'Three enemy checkpoint file roundtrips compare native 425a60/425be0 screen-grid records, CPU vertices/sampling, fresh saved-pool imports and restored strip geometry. Original capture/16 strip ANM creation, handles, queue order, flags, script states, all CPU grid/strip vertices and retirement against actual text ANM. Screen read/copy trigger and captured GPU pixels remain renderer integration work; no pixel capture claim.'});
 }finally{c.enemy_checkpoint_delete(saved);c.enemy_manager_delete(enemies);c.player_checkpoint_file_delete(file);c.anm_checkpoint_delete(savedPool);c.program_delete(program);c.release(pp);c.release(request);c.release(name);c.release(fileBuffer);if(object)c.screen_grid_object_delete(object);c.anm_manager_delete(anm);m.close();}
});
