import test from 'node:test';import assert from 'node:assert/strict';import {core,memory,string,report} from './helpers.mjs';import {preloadStage} from './stage-assets-fixture.mjs';
test('TH15 actual stage session owns clocks, captures requested chapters and round-trips a recorded input stream through the same scheduled world',async()=>{
 const c=await core(),out=c.allocate(96),limit=3600;let frames=0,checks=0,recordedBytes=0;const results=[];
 const capture=(stage,session)=>{c.stage_gameplay_counts(stage,out);c.stage_gameplay_enemy_trace(stage,out+48);const counts=Buffer.from(memory(c,out,48)),trace=Buffer.from(memory(c,out+48,48));trace.fill(0,24,28);return Buffer.concat([counts,trace,Buffer.from(memory(c,c.stage_gameplay_field(stage,3),12)),Buffer.from(memory(c,c.stage_gameplay_field(stage,1),44)),Buffer.from(memory(c,c.stage_gameplay_field(stage,2),52)),Buffer.from(memory(c,c.session_gameplay_field(session,0),20)),Buffer.from(memory(c,c.session_gameplay_field(session,2),280)),Buffer.from(memory(c,c.session_gameplay_field(session,3),4)),Buffer.from(memory(c,c.session_gameplay_field(session,4),8)),Buffer.from(memory(c,c.session_gameplay_field(session,5),8))]);};
 try{for(let character=0;character<2;character++){
  const recording=c.recording_create(),header=c.allocate(0x238),name=c.allocate(16),metadata=c.recording_metadata(recording);memory(c,header,0x238).fill(0);new DataView(c.memory.buffer).setUint16(header,1,true);new DataView(c.memory.buffer).setUint32(metadata+0x8c,character,true);new DataView(c.memory.buffer).setUint32(metadata+0x94,1,true);assert.equal(c.recording_begin(recording,header,0x238),1);c.recording_activate(recording);const fingerprints=[];let source;
  try{{const asset=preloadStage(c,1,character),stage=c.stage_gameplay_create(asset.fixture);let session=0;try{
   assert.equal(c.stage_gameplay_prepare(stage),1,string(c,c.stage_gameplay_error(stage)));assert.equal(c.stage_gameplay_begin(stage),1,string(c,c.stage_gameplay_error(stage)));session=c.session_gameplay_create(stage,recording,0);const progress=c.stage_gameplay_field(stage,0);
   for(let frame=0;frame<limit;frame++){const held=1|0x200|(frame%120<60?0x40:0x80)|(frame%200>=100?8:0);assert.equal(c.session_gameplay_step(session,held,0,60),1,'live '+character+'/'+frame+' '+string(c,c.session_gameplay_error(session)));fingerprints.push(capture(stage,session));assert.equal(c.recording_clock(recording),frame+1);assert.ok(new DataView(c.memory.buffer).getInt32(progress+8,true)>0);frames++;checks+=2;}
   c.stage_gameplay_counts(stage,out);assert.equal(new Uint32Array(c.memory.buffer,out,12)[9],limit);assert.equal(new Uint32Array(c.memory.buffer,out,12)[11],1,'real ECL chapter requests must capture the owned scene');assert.ok(new DataView(c.memory.buffer).getInt32(progress+4,true)>0,'chapter must advance through the session callback');
   // The original session stop result must prevent input/background/gameplay callbacks.
   const input=Buffer.from(memory(c,c.session_gameplay_field(session,2),280)),position=Buffer.from(memory(c,c.stage_gameplay_field(stage,3),12)),clock=c.recording_clock(recording);new DataView(c.memory.buffer).setUint32(progress+96,0x10,true);assert.equal(c.session_gameplay_step(session,0x10,0,60),1);assert.deepEqual(Buffer.from(memory(c,c.session_gameplay_field(session,2),280)),input);assert.deepEqual(Buffer.from(memory(c,c.stage_gameplay_field(stage,3),12)),position);assert.equal(c.recording_clock(recording),clock);c.stage_gameplay_counts(stage,out);assert.equal(new Uint32Array(c.memory.buffer,out,12)[9],limit);
   memory(c,name,5).set(Buffer.from([84,69,83,84,0]));assert.equal(c.recording_write(recording,name,1),1,string(c,c.recording_error(recording)));source=Buffer.from(memory(c,c.recording_data(recording),c.recording_size(recording)));recordedBytes+=source.length;
  }finally{if(session)c.session_gameplay_delete(session);c.stage_gameplay_delete(stage);asset.close();}}
  const replay=c.replay_create(),bytes=c.allocate(source.length);memory(c,bytes,source.length).set(source);assert.equal(c.replay_open(replay,bytes,source.length),1,string(c,c.replay_error(replay)));const playback=c.replay_playback_create(replay);assert.equal(c.replay_playback_select(playback,1),1);c.replay_playback_activate(playback);const asset=preloadStage(c,1,character),stage=c.stage_gameplay_create(asset.fixture);let session=0;
  try{assert.equal(c.stage_gameplay_prepare(stage),1);assert.equal(c.stage_gameplay_begin(stage),1);session=c.session_gameplay_create(stage,0,playback);for(let frame=0;frame<limit;frame++){assert.equal(c.session_gameplay_step(session,0,0,60),1,'replay '+character+'/'+frame+' '+string(c,c.session_gameplay_error(session)));assert.deepEqual(capture(stage,session),fingerprints[frame],'actual scheduled state replay '+character+'/'+frame);checks++;frames++;}assert.equal(c.session_gameplay_step(session,0,0,60),1);assert.equal(c.replay_playback_finished(playback),1);const events=Array.from(new Int32Array(c.memory.buffer,c.session_gameplay_events(session),c.session_gameplay_event_count(session)));assert.ok(events.includes(2),'sentinel must request replay completion');results.push({character,stage:1,liveFrames:limit,replayFrames:limit,checkpointCaptured:true,recordingBytes:source.length});
  }finally{if(session)c.session_gameplay_delete(session);c.stage_gameplay_delete(stage);asset.close();c.replay_playback_delete(playback);c.replay_delete(replay);c.release(bytes);}
  }finally{c.recording_delete(recording);c.release(header);c.release(name);}
 }
 report('session-gameplay-integration',{passed:true,frames,checks,recordedBytes,results,scope:'Actual stage-one ECL/STD/ANM/SHT/MSG, real chapter reward/capture and shared 15/16/17/21/23..34 scheduler; session-owned clocks without fixture-written stage clocks; recorded-input C++ world round trip compares player, score, counts, main enemy execution, input timers, rank and both RNGs on every frame. Controlled full power, invulnerability and held dialogue skip; native whole-world parity, stage factories/activation, persisted snapshots, GPU/audio/browser remain separate.'});
 }finally{c.release(out);}
});
