import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {resolve} from 'node:path';import {core,oracle,memory,string,report,root} from './helpers.mjs';import {bits,ins,resource} from './ecl-fixtures.mjs';
test('TH15 battle shares real session progress, chapter requests and same-frame ECL clocks',async()=>{
 const c=await core(),m=await oracle(),enemy=m.allocate(0x5780),manager=m.allocate(0x200),scene=m.allocate(0x100),player=m.allocate(0x800);let checks=0,frames=0;
 try{m.view(enemy,0x5780).fill(0);m.view(manager,0x200).fill(0);m.view(scene,0x100).fill(0);m.view(player,0x800).fill(0);m.u32(0x4e9a80,manager);m.u32(0x4e9a94,scene);m.u32(0x4e9bb8,player);
 const {bytes}=resource({main:Buffer.concat([ins(524,[19]),ins(547,[bits(.5)]),ins(547,[bits(.25)],0,6),ins(524,[22],0,8),ins(0,[],0,100000)])});
 for(let character=0;character<4;character++){const anm=c.anm_manager_create(),program=c.program_create(),sht=c.sht_create(),data=c.allocate(bytes.length),state=c.allocate(128),requestOwner=c.allocate(4),name=c.allocate(5),request=c.allocate(84);let battle=0;const dv=()=>new DataView(c.memory.buffer);
 const load=(name,id)=>{const b=readFileSync(resolve(root,'reference/assets',name)),p=c.allocate(b.length);memory(c,p,b.length).set(b);assert.equal(c.anm_manager_load(anm,id,p,b.length),1,string(c,c.anm_manager_error(anm)));c.release(p);};
 try{load('ascii.anm',2);assert.equal(c.anm_manager_fallback(anm,2),1);load('effect.anm',8);load('bullet.anm',7);load('pl0'+character+'.anm',9+character);const sb=readFileSync(resolve(root,'reference/assets/pl0'+character+'.sht')),sp=c.allocate(sb.length);memory(c,sp,sb.length).set(sb);assert.equal(c.sht_open(sht,sp,sb.length),1);c.release(sp);memory(c,data,bytes.length).set(bytes);assert.equal(c.program_attach(program,data,bytes.length),0);battle=c.game_battle_create(anm,program,sht,character);assert.equal(c.game_battle_initialize(battle),1,string(c,c.game_battle_error(battle)));memory(c,state,128).fill(0);for(const [offset,value]of [[0,2],[4,7],[16,character],[20,2],[24,3],[32,71],[100,0]])dv().setInt32(state+offset,value,true);dv().setFloat32(state+92,1,true);dv().setUint8(state+108,1);dv().setInt32(requestOwner,-1,true);c.game_battle_bind_progress(battle,state,requestOwner);memory(c,name,5).set(Buffer.from('main\0'));memory(c,request,84).fill(0);dv().setFloat32(request+4,128,true);dv().setInt32(request+20,10000,true);assert.equal(c.game_battle_spawn(battle,name,request),1,string(c,c.game_battle_error(battle)));assert.equal(dv().getUint32(state+96,true),0x8000);assert.equal(dv().getInt32(requestOwner,true),19);assert.equal(dv().getFloat32(state+92,true),.5);checks+=3;
 for(let frame=0;frame<64;frame++){
  // Clearing the consumed request must not be undone by stale world flags.
  dv().setUint32(state+96,frame%9===0?8:0,true);const transition=frame%2,run=frame%3!==0;dv().setInt32(state+100,transition,true);dv().setUint8(state+108,run?1:0);dv().setInt32(state+4,frame%48,true);const stock=c.game_battle_field(battle,3);dv().setInt32(stock+8,frame*3,true);dv().setInt32(stock+28,100+frame,true);dv().setUint32(stock+24,(frame%3)<<8,true);assert.equal(c.game_battle_step(battle,0,0,0,3,1),1,string(c,c.game_battle_error(battle)));frames++;
  for(const [variable,address,value]of [[-9960,0x4e7418,0],[-9959,0x4e7410,3],[-9945,0x4e7404,character],[-9930,0x4e7440,dv().getInt32(stock+28,true)],[-9927,scene+0xb4,transition],[-9907,0x4e7424,71],[-9905,0x4e73f8,frame%48],[-9904,0x4e742c,dv().getInt32(stock+8,true)]]){m.i32(address,value);m.i32(0x4e7408,2);m.i32(0x4e7ed8,run?1:0);assert.equal(c.game_battle_variable(battle,1,variable),m.call(0x42e910,{ecx:enemy,args:[variable]})|0,'native session binding '+variable);checks++;}
  assert.equal(dv().getFloat32(c.game_battle_clock(battle),true),dv().getFloat32(state+92,true),'later callbacks use shared ECL rate');checks++;
 }
 assert.equal(dv().getInt32(requestOwner,true),22,'later chapter request reaches runtime owner');assert.equal(dv().getFloat32(state+92,true),.25,'script clock retained across later frames');checks+=2;
 }finally{if(battle)c.game_battle_delete(battle);for(const p of [data,state,requestOwner,name,request])c.release(p);c.sht_delete(sht);c.program_delete(program);c.anm_manager_delete(anm);}
 }
 report('session-battle-binding',{passed:true,characters:4,frames,checks,scope:'Actual GameBattle and all four players, real ECL 524/547 and original 42e910 values from shared session globals. Chapter request persists to the session owner; consumed flags are not reintroduced; later battle callbacks use the rate written by ECL. Synthetic scenario and native variable checks; full stage and UI verification remain separate.'});
 }finally{m.close();}
});
