import test from 'node:test';import assert from 'node:assert/strict';import{core,memory,string,report}from './helpers.mjs';import{preloadStage}from './stage-assets-fixture.mjs';
test('TH15 actual stage session restores original-format snapshots/configuration before running imported recording input',async()=>{
 const c=await core(),out=c.allocate(96),name=c.allocate(8),limit=2400;memory(c,name,8).set(Buffer.from('SNAPSHOT'));let frames=0,checks=0,totalBytes=0;const results=[];
 const capture=(stage,session,autoFocus)=>{c.stage_gameplay_counts(stage,out);c.stage_gameplay_enemy_trace(stage,out+48);const trace=Buffer.from(memory(c,out+48,48));trace.fill(0,24,28);const controls=Buffer.from(memory(c,c.session_gameplay_field(session,2),280));if(autoFocus){for(const at of[8,12,16,20])controls.writeUInt32LE(controls.readUInt32LE(at)&~8,at);controls.fill(0,36,40);controls.fill(0,164,168);}return Buffer.concat([Buffer.from(memory(c,out,48)),trace,Buffer.from(memory(c,c.stage_gameplay_field(stage,3),12)),Buffer.from(memory(c,c.stage_gameplay_field(stage,1),44)),Buffer.from(memory(c,c.stage_gameplay_field(stage,2),52)),Buffer.from(memory(c,c.session_gameplay_field(session,0),20)),controls,Buffer.from(memory(c,c.session_gameplay_field(session,3),4)),Buffer.from(memory(c,c.session_gameplay_field(session,4),8)),Buffer.from(memory(c,c.session_gameplay_field(session,5),8))]);};
 const setup=(stage,character,live)=>{const dv=new DataView(c.memory.buffer),p=c.stage_gameplay_field(stage,1),v=c.stage_gameplay_field(stage,2),s=c.stage_gameplay_field(stage,0);dv.setInt32(p,live?character+2:8,true);dv.setInt32(p+28,live?400:100,true);dv.setInt32(v,live?character*13579:987654,true);dv.setInt32(s+40,0,true);};
 try{for(let character=0;character<4;character++){
  let bytes,header,config;const snapshots=[];{const asset=preloadStage(c,1,character),stage=c.stage_gameplay_create(asset.fixture);let run=0;try{assert.equal(c.stage_gameplay_prepare(stage),1,string(c,c.stage_gameplay_error(stage)));setup(stage,character,true);run=c.stage_session_replay_create(stage);memory(c,c.stage_session_replay_config(run)+0x24,1)[0]=character%2;assert.equal(c.stage_session_replay_enter(run,0,0),1,string(c,c.stage_session_replay_error(run)));header=Buffer.from(memory(c,c.stage_session_replay_header(run,1),0x238));config=Buffer.from(memory(c,c.stage_session_replay_config(run),0x6c));const session=c.stage_session_replay_session(run);
   for(let frame=0;frame<limit;frame++){const held=1|0x200|(frame%160<80?0x40:0x80)|(frame%217>=100?8:0);assert.equal(c.session_gameplay_step(session,held,0,60),1,'record '+character+'/'+frame+' '+string(c,c.session_gameplay_error(session)));snapshots.push(capture(stage,session,character%2));assert.equal(c.stage_session_replay_clock(run),frame+1);frames++;checks++;}
   const label=c.allocate(9);memory(c,label,9).set(Buffer.from('SNAPSHOT'+String.fromCharCode(0)));assert.equal(c.stage_session_replay_export(run,label),1);c.release(label);bytes=Buffer.from(memory(c,c.stage_session_replay_data(run),c.stage_session_replay_size(run)));totalBytes+=bytes.length;
  }finally{if(run)c.stage_session_replay_delete(run);c.stage_gameplay_delete(stage);asset.close();}}
  {const asset=preloadStage(c,1,character),stage=c.stage_gameplay_create(asset.fixture),file=c.allocate(bytes.length);let run=0;try{memory(c,file,bytes.length).set(bytes);assert.equal(c.stage_gameplay_prepare(stage),1);setup(stage,character,false);run=c.stage_session_replay_create(stage);memory(c,c.stage_session_replay_config(run),0x6c).fill(0xee);assert.equal(c.stage_session_replay_enter(run,file,bytes.length),1,string(c,c.stage_session_replay_error(run)));const restoredHeader=Buffer.from(memory(c,c.stage_session_replay_header(run,1),0x238));assert.equal(restoredHeader.readUInt32LE(4),limit+1);assert.equal(restoredHeader.readUInt32LE(8),(limit+1)*6+Math.ceil(limit/30));restoredHeader.fill(0,4,12);assert.deepEqual(restoredHeader,header);assert.deepEqual(Buffer.from(memory(c,c.stage_session_replay_config(run),0x6c)),config);const session=c.stage_session_replay_session(run);
   for(let frame=0;frame<limit;frame++){assert.equal(c.session_gameplay_step(session,0,0,60),1,'replay '+character+'/'+frame+' '+string(c,c.session_gameplay_error(session)));assert.deepEqual(capture(stage,session,character%2),snapshots[frame],'snapshot restored world '+character+'/'+frame);frames++;checks++;}
   assert.equal(c.session_gameplay_step(session,0,0,60),1);assert.equal(c.stage_session_replay_finished(run),1);results.push({character,frames:limit,bytes:bytes.length,autoFocus:character%2});
  }finally{if(run)c.stage_session_replay_delete(run);c.stage_gameplay_delete(stage);asset.close();c.release(file);}}
 }
 report('session-replay',{passed:true,frames,checks,totalBytes,results,scope:'Four real stage-one worlds, restored lives/power/score/config from original-format stage headers instead of coincidentally identical defaults, original stage-entry ordering around snapshot activation, recorded/replayed inputs and full named player/counts/main ECL/rank/timer/RNG trace. Controlled invulnerability/full power/held dialogue skip; independent native snapshot, recording and input tests separate. Auto-focus intentionally injects held focus after live edges, whereas playback recomputes those edges; only its independently native-verified focus edge/repeat/duration bookkeeping is excluded, with held/previous and world state compared. Complete original replay world, cross-stage app and hardware presentation remain unverified.'});
 }finally{c.release(name);c.release(out);}
});
