import test from 'node:test';import assert from 'node:assert/strict';import {core,oracle,memory,report,enableNativeMath} from './helpers.mjs';import {nativeGraphics} from './rendering-oracle.mjs';
test('TH15 16-point background box projection and distance clipping match original',async()=>{
 const c=await core(),m=await oracle();enableNativeMath(m);const gfx=nativeGraphics(m),o=m.allocate(28),instance=m.allocate(12),radius=m.allocate(4),wrapper=m.allocate(32),co=c.allocate(28),ci=c.allocate(12),camera=c.anm_camera_create(),vp=c.allocate(24),out=c.allocate(192);let checks=0,projected=0,visible=0,far=0,ptr=0;const ep=gfx.library.exports.get('D3DXVec3ProjectArray');m.hooks.push(m.cpu.hook_add(m.uc.HOOK_CODE,()=>{ptr=m.u32(m.reg('ESP')+4);},null,ep,ep));const code=Buffer.from([0xf3,0x0f,0x10,0x15,0,0,0,0,0xe9,0,0,0,0]);code.writeUInt32LE(radius,4);code.writeInt32LE(0x40f050-wrapper-code.length,9);m.write(wrapper,code);
 try{for(let sample=0;sample<4096;sample++){
  const object=Buffer.alloc(28),position=Buffer.alloc(12),view=Buffer.alloc(0x120);for(let k=0;k<3;k++){object.writeFloatLE((sample%31-15+k*3)*17.25,4+k*4);object.writeFloatLE((sample%37+k*5)*6.5,16+k*4);position.writeFloatLE((sample%73-36+k*7)*12.5,k*4);view.writeFloatLE((sample%23-11+k*2)*3.125,k*4);view.writeFloatLE((sample%13-6+k*3)*.1875,0x3c+k*4);view.writeFloatLE(k===2?1:(sample%7-3+k*2)*.025,0x24+k*4);view.writeFloatLE(k===1?1:(sample%17-8+k*2)*.00625,0x18+k*4);}view.writeFloatLE(.35+(sample%29)*.0125,0x54);view.writeUInt32LE(640,0xe8);view.writeUInt32LE(480,0xec);m.write(gfx.view,view);gfx.reset();m.call(0x44e120,{args:[gfx.view]});m.write(o,object);m.write(instance,position);memory(c,co,28).set(object);memory(c,ci,12).set(position);memory(c,c.anm_camera_matrix(camera,0),64).set(m.bytes(gfx.view+0x60,64));memory(c,c.anm_camera_matrix(camera,1),64).set(m.bytes(gfx.view+0xa0,64));let dv=new DataView(c.memory.buffer);for(let k=0;k<3;k++)dv.setFloat32(c.anm_camera_eye(camera)+4*k,Math.fround(m.f32(gfx.view+k*4)+m.f32(gfx.view+0x3c+k*4)),true);const vpData=Buffer.alloc(24);vpData.writeUInt32LE(640,8);vpData.writeUInt32LE(480,12);vpData.writeFloatLE(1,20);memory(c,vp,24).set(vpData);m.write(gfx.view+0xe0,vpData);const x=sample%11*3,y=sample%7*2,limit=[0,40000,100000,1000000,10000000][sample%5];m.u32(0x51bc08,x);m.u32(0x51bc0c,y);m.f32(radius,limit);ptr=0;const want=m.call(wrapper,{ecx:o,args:[instance,gfx.view]}),got=c.stage_visibility(co,ci,camera,vp,x,y,limit,out);assert.equal(got,want===0?1:0,'visibility '+sample);checks++;if(ptr){assert.deepEqual(Buffer.from(memory(c,out,192)),Buffer.from(m.bytes(ptr,192)),'projected points '+sample);checks++;projected++;}else far++;if(got)visible++;
 }
 report('stage-visibility',{passed:true,cases:4096,checks,projected,visible,distanceCulled:far,originalFunctions:['0x40f050','D3DXVec3ProjectArray'],scope:'Native 16-point bounding box projection, exact per-point screen/depth output, distance gate and logical playfield clipping with independent viewport and playfield origins. No GPU rasterization is claimed.'});
 }finally{for(const p of [co,ci,vp,out])c.release(p);c.anm_camera_delete(camera);m.close();}
});
