import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync,readdirSync} from 'node:fs';import {resolve} from 'node:path';import {core,oracle,memory,string,root,report,enableNativeMath,enableOriginalVectorMath} from './helpers.mjs';import {resourceLoader,nativePool,nativeInstances,prepareBank,compareAnm} from './anm-oracle.mjs';import {nativeGraphics} from './rendering-oracle.mjs';
test('TH15 seven original background draw callbacks preserve foreground, fog and transitions',async()=>{
 const c=await core();let frames=0,checks=0,slots=0,primitives=0,draws=0,renderedFrames=0;const summaries=[];
 for(const name of readdirSync(resolve(root,'reference/assets')).filter(n=>n.endsWith('.std')).sort()){
  const m=await oracle();enableNativeMath(m);const library=enableOriginalVectorMath(m);for(const entry of m.image.imports)if(entry.dll==='d3dx9_43.dll'&&library.exports.has(entry.name))m.u32(entry.address,library.exports.get(entry.name));const manager=c.anm_manager_create(),nm=nativePool(m),gfx=nativeGraphics(m,nm),renderer=c.anm_renderer_create(),viewport=c.allocate(24),stats=c.allocate(12),loader=resourceLoader(m),text=m.allocate(0x19270),owner=m.allocate(0x6788),callbacks=[m.allocate(40),m.allocate(40),m.allocate(40)],r=c.stage_resource_create();let scene=0,drawFrame=0;let clearEvents=[],fadeRegistrations=[];const vt=m.u32(m.u32(0x4e77d8));m.u32(vt+0xac,m.registerImport({dll:"fixture",name:"capture background color/depth clear",argc:7,handler:()=>{const sp=m.reg("ESP"),rect=m.u32(sp+12);clearEvents.push(1,0,m.u32(sp+20),rect?1:0,...(rect?[m.u32(rect),m.u32(rect+4),m.u32(rect+8)-m.u32(rect),m.u32(rect+12)-m.u32(rect+4)]:[0,0,0,0]));return 0;}}));m.replace(0x401390,"background fade update registration",()=>{const sp=m.reg("ESP"),node=m.u32(sp+4);fadeRegistrations.push([m.u32(node+0x24),m.i32(sp+8)]);return 0;},2);m.replace(0x401440,"background fade draw registration",()=>{const sp=m.reg("ESP"),node=m.u32(sp+4);fadeRegistrations.at(-1).push(m.i32(sp+8));return 0;},2);const data=readFileSync(resolve(root,'reference/assets',name)),cp=c.allocate(data.length);memory(c,cp,data.length).set(data);assert.equal(c.stage_resource_open(r,cp,data.length),1);
  m.u32(0x51bc08,32);m.u32(0x51bc0c,16);const vpBytes=Buffer.alloc(24);vpBytes.writeUInt32LE(640,8);vpBytes.writeUInt32LE(480,12);vpBytes.writeFloatLE(1,20);memory(c,viewport,24).set(vpBytes);m.write(owner+0x2cc,vpBytes);const load=(name,id)=>{const b=readFileSync(resolve(root,'reference/assets',name)),p=c.allocate(b.length);memory(c,p,b.length).set(b);assert.equal(c.anm_manager_load(manager,id,p,b.length),1,name+' '+string(c,c.anm_manager_error(manager)));c.release(p);return prepareBank(m,loader,name,b,nm,id);};
  try{m.u32(0x4ca620,0x4e73e8);m.f32(0x4e73e8,1);m.u32(0x4e9a58,text);m.u32(text+0x19258,load('ascii.anm',2));assert.equal(c.anm_manager_fallback(manager,2),1);const bank=load(string(c,c.stage_resource_name(r)),3);m.view(owner,0x6788).fill(0);m.write(owner+0x2cc,vpBytes);const input=m.allocate(data.length);m.write(input,data);m.u32(owner+0x677c,input);m.u32(owner+0x6780,data.length);m.replace(0x485f70,'loaded real background ANM bank boundary',()=>bank,2);assert.equal(m.call(0x40f4b0,{ecx:owner,args:[0]}),0);m.u32(0x4e9a60,owner);m.u32(owner+4,callbacks[0]);m.u32(owner+8,callbacks[1]);m.u32(owner+0x6784,callbacks[2]);m.u32(owner+0x318,owner);m.i32(owner+12,-1);m.u32(owner+0x1c,1);m.u32(owner+0x675c,1);m.f32(owner+0x1f4,-600);m.f32(owner+0x1fc,300);m.f32(owner+0x200,600);m.f32(owner+0x208,1);m.f32(owner+0x218,1);m.f32(owner+0x240,.6);m.f32(owner+0x337c,9999999);for(let i=0;i<8;i++)m.call(0x40db10,{ecx:owner+0x31c+i*0x608});m.call(0x40f640);scene=c.stage_scene_create(r,manager,3);assert.equal(c.stage_scene_initialize(scene,.6),1,string(c,c.stage_scene_error(scene)));drawFrame=c.stage_draw_frame_create(scene,manager,renderer);m.call(0x44e2f0,{ecx:0x4e77d0});const npr=c.stage_resource_count(r,1);primitives+=npr;
   const check=label=>{for(let i=0;i<npr;i++)compareAnm(c,m,c.stage_scene_vm(scene,i,0),m.u32(owner+0x6734)+i*0x608,name+'/'+label+' primitive '+i);for(let i=0;i<8;i++){const np=owner+0x31c+i*0x608;if(m.u32(np+0x28)===3){compareAnm(c,m,c.stage_scene_vm(scene,i,1),np,name+'/'+label+' slot '+i);slots++;}}for(let i=0;i<c.stage_resource_count(r,0);i++)assert.equal(c.stage_scene_object_flags(scene,i),m.bytes(m.u32(m.u32(owner+0x6740)+i*4)+3,1)[0]);checks+=npr+1;};check('initial');
   for(let frame=0;frame<3300;frame++){
    const rate=[1,.5,1.25,1][Math.floor(frame/900)],flags=frame%41===0?8:frame%43===0?4:0,age=[0,29,30,59,60][frame%5];m.u32(owner+0x675c,1|flags);m.i32(owner+0x6764,age);m.f32(0x4e73e8,rate);assert.equal(m.call(0x40e6b0,{ecx:owner}),1);assert.equal(c.stage_scene_update(scene,rate,1|flags,age),1,name+'/'+frame+' '+string(c,c.stage_scene_error(scene)));assert.deepEqual(Buffer.from(memory(c,c.stage_scene_direction(scene),12)),Buffer.from(m.bytes(owner+0x210,12)),name+'/'+frame+' prepared camera direction');assert.equal(c.stage_scene_color(scene)>>>0,m.u32(0x4e8214));if(frame<8||frame%32===0||frame===3599)check(frame);
    for(let alt=0;alt<2;alt++){assert.equal(c.anm_manager_update(manager,alt,rate),1,string(c,c.anm_manager_error(manager)));m.call(alt?0x487890:0x487740,{ecx:nm});const list=nativeInstances(m,nm,alt);assert.equal(c.anm_manager_count(manager,alt),list.length);for(let i=0;i<list.length;i++){const h=m.u32(list[i]+0x544);assert.equal(c.anm_manager_order(manager,alt,i),h);if(frame<8||frame%32===0)compareAnm(c,m,c.anm_manager_find(manager,h),list[i],name+'/'+frame+' pooled '+i);}}checks+=4;frames++;
    if([1,60,240,900,1800,3100,3299].includes(frame)){
     gfx.reset();c.anm_renderer_reset(renderer);clearEvents=[];fadeRegistrations=[];c.anm_renderer_clear_target_events(renderer);const transitionFlags=[1,5,7,1,9,0,5][[1,60,240,900,1800,3100,3299].indexOf(frame)],transitionAge=[0,29,60,1,0,0,30][[1,60,240,900,1800,3100,3299].indexOf(frame)],tint=frame===900?0x80aabbcc:0x00ffffff,ox=Math.fround((frame%11-5)*.25),oy=Math.fround((frame%9-4)*.5);m.u32(owner+0x675c,transitionFlags);m.u32(owner+0x339c,tint);const age=Buffer.alloc(20);age.writeInt32LE(transitionAge-1);age.writeInt32LE(transitionAge,4);age.writeFloatLE(transitionAge,8);age.writeUInt32LE(1,16);m.write(owner+0x6760,age);m.f32(0x4e7e90,ox);m.f32(0x4e7e94,oy);c.stage_draw_frame_configure(drawFrame,scene,viewport,transitionFlags,tint,transitionAge,rate,ox,oy);m.u32(owner+0x6750,0);m.u32(owner+0x6754,0);m.u32(owner+0x6758,0);c.stage_scene_draw_stats(scene,stats,1);
     for(let pass=0;pass<2;pass++){m.call(pass?0x40ec80:0x40e7f0,{ecx:owner});assert.equal(c.stage_draw_frame_pass(drawFrame,pass),1,name+'/'+frame+' pass '+pass+' '+string(c,c.stage_draw_frame_error(drawFrame)));const state=c.stage_draw_frame_state(drawFrame),dv=new DataView(c.memory.buffer);assert.equal(dv.getUint32(state,true),m.u32(owner+0x675c),name+'/'+frame+' background flags');assert.equal(dv.getUint32(state+4,true),m.u32(owner+0x339c),name+'/'+frame+' tint');assert.deepEqual(Buffer.from(memory(c,state+8,20)),Buffer.from(m.bytes(owner+0x6760,20)),name+'/'+frame+' transition timer');assert.deepEqual(Array.from(new Uint32Array(c.memory.buffer,c.anm_renderer_target_events(renderer),c.anm_renderer_target_event_count(renderer))),clearEvents,name+'/'+frame+' color/depth clears');const fades=fadeRegistrations.flatMap(([effect,update,draw])=>[m.i32(effect+24),update,draw]);assert.deepEqual(Array.from(new Int32Array(c.memory.buffer,c.stage_draw_frame_fades(drawFrame),c.stage_draw_frame_fade_count(drawFrame))),fades,name+'/'+frame+' fade creation');checks+=5;}
     m.call(0x47e3f0,{ecx:nm});const captured=gfx.draws();assert.equal(c.anm_renderer_calls(renderer),captured.length,name+'/'+frame+' batches');
     for(let draw=0;draw<captured.length;draw++){const v=captured[draw],bytes=Buffer.from(memory(c,c.anm_renderer_history(renderer,draw),c.anm_renderer_history_size(renderer,draw)));assert.deepEqual(bytes,v.bytes,name+'/'+frame+' draw '+draw+' vertex bytes');for(const[kind,key]of [[0,256],[1,2],[2,3],[3,16]])if((v.stride===20||v.stride===24)&&v.matrices.has(key))assert.deepEqual(Buffer.from(memory(c,c.anm_renderer_submission_matrix(renderer,draw,kind),64)),v.matrices.get(key),name+'/'+frame+' draw '+draw+' matrix '+kind);const state=Array.from(new Uint32Array(c.memory.buffer,c.anm_renderer_submission_states(renderer,draw),15));if(v.states.has(14))assert.equal(state[7],v.states.get(14),name+'/'+frame+' draw '+draw+' depth write');if(v.states.has(28))assert.equal(state[10],v.states.get(28),name+'/'+frame+' draw '+draw+' fog');draws++;checks+=6;}
     c.stage_scene_draw_stats(scene,stats,0);assert.deepEqual(Array.from(new Uint32Array(c.memory.buffer,stats,3)),[m.u32(owner+0x6750),m.u32(owner+0x6754),m.u32(owner+0x6758)],name+'/'+frame+' scene stats');check(frame+' rendered');renderedFrames++;
    }
   }summaries.push({name,frames:3300,primitives:npr});
  }finally{if(drawFrame)c.stage_draw_frame_delete(drawFrame);if(scene)c.stage_scene_delete(scene);c.anm_renderer_delete(renderer);c.release(viewport);c.release(stats);c.stage_resource_delete(r);c.release(cp);c.anm_manager_delete(manager);m.close();}
 }
 report('stage-draw-frame',{passed:true,files:7,frames,renderedFrames,draws,checks,primitives,embeddedChecks:slots,summaries,originalFunctions:['0x40f640','0x40f740','0x40e6b0','0x40fbc0','0x477e10','0x487740','0x487890'],scope:'Actual original 40e7f0/40ec80 full background callbacks on seven real STD/ANM banks, both background/foreground layer groups, transition gates and exact draw-time timers, fade construction priorities, color/depth clear rectangle, tint consumption, scene counters, complete GPU-boundary vertex bytes, depth/fog state and world matrices. Original ANM/STD update executes between draws; callback registration of the fade is captured at the scheduler boundary, its later animation and actual SDL scene rasterization remain separately verified. Previous background-layer scope: Real seven background ANM banks and original complete stage update callback, initial primitive binding, primitive/embedded/pool animation timing, object flags, camera preparation order, background script clear color and transition gates. Initial camera and inactive embedded VMs are prepared fixture state; the stage factory is not tested. Texture allocation is an ANM dimension boundary. Original full background layer draws are captured at the GPU boundary and compared with semantic C++ vertex bytes, world/view/projection/texture matrices for world vertex layouts (pretransformed screen vertices do not consume these matrices), depth/fog state and scene counters. Actual SDL/WebGL rasterization, stage transitions and deformation remain unverified.'});
});
