import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync,readdirSync} from 'node:fs';import {resolve} from 'node:path';import {core,oracle,memory,string,root,report,enableNativeMath,enableOriginalVectorMath} from './helpers.mjs';import {resourceLoader,nativePool,nativeInstances,prepareBank,compareAnm} from './anm-oracle.mjs';
test('TH15 background checkpoints restore original camera, primitive and embedded VM copies across seven stages',async()=>{
 const c=await core(),file=c.player_checkpoint_file_create(),fileInput=c.allocate(1024*1024);let frames=0,checks=0,slots=0,primitives=0;const summaries=[];
 for(const name of readdirSync(resolve(root,'reference/assets')).filter(n=>n.endsWith('.std')).sort()){
  const m=await oracle();enableNativeMath(m);const library=enableOriginalVectorMath(m);for(const entry of m.image.imports)if(entry.dll==='d3dx9_43.dll'&&library.exports.has(entry.name))m.u32(entry.address,library.exports.get(entry.name));const manager=c.anm_manager_create(),nm=nativePool(m),loader=resourceLoader(m),text=m.allocate(0x19270),owner=m.allocate(0x6788),callbacks=[m.allocate(40),m.allocate(40),m.allocate(40)],r=c.stage_resource_create(),nativeFile=m.allocate(1024*1024),used=m.allocate(4);let scene=0,saved=0;const data=readFileSync(resolve(root,'reference/assets',name)),cp=c.allocate(data.length);memory(c,cp,data.length).set(data);assert.equal(c.stage_resource_open(r,cp,data.length),1);
  const load=(name,id)=>{const b=readFileSync(resolve(root,'reference/assets',name)),p=c.allocate(b.length);memory(c,p,b.length).set(b);assert.equal(c.anm_manager_load(manager,id,p,b.length),1,name+' '+string(c,c.anm_manager_error(manager)));c.release(p);return prepareBank(m,loader,name,b,nm,id);};
  try{m.u32(0x4ca620,0x4e73e8);m.f32(0x4e73e8,1);m.u32(0x4e9a58,text);m.u32(text+0x19258,load('ascii.anm',2));assert.equal(c.anm_manager_fallback(manager,2),1);const bank=load(string(c,c.stage_resource_name(r)),3);m.view(owner,0x6788).fill(0);const input=m.allocate(data.length);m.write(input,data);m.u32(owner+0x677c,input);m.u32(owner+0x6780,data.length);m.replace(0x485f70,'loaded real background ANM bank boundary',()=>bank,2);assert.equal(m.call(0x40f4b0,{ecx:owner,args:[0]}),0);m.u32(0x4e9a60,owner);m.u32(owner+4,callbacks[0]);m.u32(owner+8,callbacks[1]);m.u32(owner+0x6784,callbacks[2]);m.u32(owner+0x318,owner);m.i32(owner+12,-1);m.u32(owner+0x1c,1);m.u32(owner+0x675c,1);m.f32(owner+0x1f4,-600);m.f32(owner+0x1fc,300);m.f32(owner+0x200,600);m.f32(owner+0x208,1);m.f32(owner+0x218,1);m.f32(owner+0x240,.6);m.f32(owner+0x337c,9999999);for(let i=0;i<8;i++)m.call(0x40db10,{ecx:owner+0x31c+i*0x608});m.call(0x40f640);scene=c.stage_scene_create(r,manager,3);assert.equal(c.stage_scene_initialize(scene,.6),1,string(c,c.stage_scene_error(scene)));saved=c.stage_checkpoint_create(scene);const npr=c.stage_resource_count(r,1);primitives+=npr;
   const check=label=>{for(let i=0;i<npr;i++)compareAnm(c,m,c.stage_scene_vm(scene,i,0),m.u32(owner+0x6734)+i*0x608,name+'/'+label+' primitive '+i);for(let i=0;i<8;i++){const np=owner+0x31c+i*0x608;if(m.u32(np+0x28)===3){compareAnm(c,m,c.stage_scene_vm(scene,i,1),np,name+'/'+label+' slot '+i);slots++;}}for(let i=0;i<c.stage_resource_count(r,0);i++)assert.equal(c.stage_scene_object_flags(scene,i),m.bytes(m.u32(m.u32(owner+0x6740)+i*4)+3,1)[0]);checks+=npr+1;};check('initial');
   for(let frame=0;frame<360;frame++){
    const rate=[1,.5,1.25,1][Math.floor(frame/90)],flags=frame%41===0?8:frame%43===0?4:0,age=[0,29,30,59,60][frame%5];m.u32(owner+0x675c,1|flags);m.i32(owner+0x6764,age);m.f32(0x4e73e8,rate);assert.equal(m.call(0x40e6b0,{ecx:owner}),1);assert.equal(c.stage_scene_update(scene,rate,1|flags,age),1,name+'/'+frame+' '+string(c,c.stage_scene_error(scene)));assert.deepEqual(Buffer.from(memory(c,c.stage_scene_direction(scene),12)),Buffer.from(m.bytes(owner+0x210,12)),name+'/'+frame+' prepared camera direction');assert.equal(c.stage_scene_color(scene)>>>0,m.u32(0x4e8214));if(frame<8||frame%32===0||frame===359)check(frame);
    if(frame===37||frame===123||frame===258){
      assert.equal(c.stage_checkpoint_capture(saved),1,string(c,c.stage_checkpoint_error(saved)));m.call(0x411580,{limit:100000000});
      for(let i=0;i<npr;i++)compareAnm(c,m,c.stage_checkpoint_vm(saved,i,0),m.u32(owner+0x6738)+i*0x608,name+'/'+frame+' saved primitive '+i);
      for(let i=0;i<8;i++){const np=owner+0x33a0+0x310+i*0x608;if(m.u32(np+0x28)===3)compareAnm(c,m,c.stage_checkpoint_vm(saved,i,1),np,name+'/'+frame+' saved embedded '+i);}
      assert.equal(c.stage_checkpoint_file_write(file,saved),1,string(c,c.stage_checkpoint_error(saved)));m.u32(used,0);m.call(0x411920,{args:[nativeFile,used],limit:100000000});const original=Buffer.from(m.bytes(nativeFile,m.u32(used))),encoded=Buffer.from(memory(c,c.player_checkpoint_file_bytes(file),c.player_checkpoint_file_size(file)));assert.equal(encoded.length,original.length,name+' background file length');for(const [a,b]of [[0,0x30],[0x30,0x1e0],[0x1e0,0x210],[0x21c,0x238],[0x2e4,0x30c],[0x3350,0x3374],[0x3378,0x3390]])assert.deepEqual(encoded.subarray(a,b),original.subarray(a,b),name+' saved file script '+a.toString(16));const ranges=[[0,0x28],[0x28,12],[0x34,0x500],[0x54c,0x28],[0x5c0,4],[0x5c8,4],[0x5ec,12]];for(let i=0;i<8;i++)for(const [off,n]of ranges){const at=0x310+i*0x608+off;assert.deepEqual(encoded.subarray(at,at+n),original.subarray(at,at+n),name+'/'+frame+' saved file embedded '+i+'/'+off.toString(16)+' bank='+original.readUInt32LE(0x310+i*0x608+0x28)+' native-before='+m.f32(owner+0x36b0+i*0x608+0x8c)+'/'+m.f32(owner+0x36b0+i*0x608+0x3d4)+' diffs='+Array.from({length:n},(_,k)=>k).filter(k=>encoded[at+k]!==original[at+k]).slice(0,32).map(k=>(off+k).toString(16)).join(','));}let at=0x3394;for(let i=0;i<npr;i++){const geometry=original.readUInt32LE(at+0x5c8);for(const [off,n]of ranges)assert.deepEqual(encoded.subarray(at+off,at+off+n),original.subarray(at+off,at+off+n),name+' saved file primitive '+i+'/'+off.toString(16));assert.deepEqual(encoded.subarray(at+0x608,at+0x608+geometry),original.subarray(at+0x608,at+0x608+geometry),name+' primitive geometry '+i);at+=0x608+geometry;}assert.equal(encoded.readUInt32LE(at),original.readUInt32LE(at));at+=4;for(let i=0;i<8;i++)if(original.readUInt32LE(0x310+i*0x608+0x5c8)){const geometry=original.readUInt32LE(at+0x5c8);for(const [off,n]of ranges)assert.deepEqual(encoded.subarray(at+off,at+off+n),original.subarray(at+off,at+off+n),name+' saved geometry record '+i+'/'+off.toString(16));assert.deepEqual(encoded.subarray(at+0x608,at+0x608+geometry),original.subarray(at+0x608,at+0x608+geometry),name+' saved embedded geometry '+i);at+=0x608+geometry;}assert.equal(at,encoded.length);
      memory(c,fileInput,original.length).set(original);assert.equal(c.stage_checkpoint_file_read(file,saved,fileInput,original.length-1),0);assert.equal(c.player_checkpoint_file_consumed(file),0);assert.equal(c.stage_checkpoint_file_read(file,saved,fileInput,original.length),1,string(c,c.stage_checkpoint_error(saved)));assert.equal(c.player_checkpoint_file_consumed(file),original.length);m.call(0x4116e0,{args:[nativeFile,original.length],limit:100000000});
      for(let k=0;k<13;k++){m.f32(0x4e73e8,.625);assert.equal(c.stage_scene_update(scene,.625,1,0),1);assert.equal(m.call(0x40e6b0,{ecx:owner}),1);}
      assert.equal(c.stage_checkpoint_restore(saved),1,string(c,c.stage_checkpoint_error(saved)));m.call(0x411630,{limit:100000000});check('restored '+frame);
      const out=c.allocate(0x3390);c.stage_scene_snapshot(scene,out);const got=Buffer.from(memory(c,out,0x3390));for(const [a,b]of [[0,0x30],[0x30,0x1e0],[0x1e0,0x204],[0x21c,0x238],[0x2e4,0x30c],[0x3350,0x3374],[0x3378,0x3390]])assert.deepEqual(got.subarray(a,b),Buffer.from(m.bytes(owner+12+a,b-a)),name+'/'+frame+' restored script '+a.toString(16));c.release(out);
      assert.deepEqual(Buffer.from(memory(c,c.stage_scene_direction(scene),12)),Buffer.from(m.bytes(owner+0x210,12)),name+'/'+frame+' restored view');m.f32(0x4e73e8,rate);
    }
    for(let alt=0;alt<2;alt++){assert.equal(c.anm_manager_update(manager,alt,rate),1,string(c,c.anm_manager_error(manager)));m.call(alt?0x487890:0x487740,{ecx:nm});const list=nativeInstances(m,nm,alt);assert.equal(c.anm_manager_count(manager,alt),list.length);for(let i=0;i<list.length;i++){const h=m.u32(list[i]+0x544);assert.equal(c.anm_manager_order(manager,alt,i),h);if(frame<8||frame%32===0)compareAnm(c,m,c.anm_manager_find(manager,h),list[i],name+'/'+frame+' pooled '+i);}}checks+=4;frames++;
   }summaries.push({name,frames:360,primitives:npr});
  }finally{if(saved)c.stage_checkpoint_delete(saved);if(scene)c.stage_scene_delete(scene);c.stage_resource_delete(r);c.release(cp);c.anm_manager_delete(manager);m.close();}
 }
 c.player_checkpoint_file_delete(file);c.release(fileInput);report('stage-checkpoint',{passed:true,files:7,frames,checks,primitives,embeddedChecks:slots,summaries,originalFunctions:['0x40f640','0x40f740','0x40e6b0','0x40fbc0','0x477e10','0x487740','0x487890'],scope:'Original 411920/4116e0 native file encoding/import plus 411580/411630 save/restore at three boundaries per stage, thirteen intervening frames and fractional ANM timer normalization. Real seven background ANM banks and original complete stage update callback, initial primitive binding, primitive/embedded/pool animation timing, object flags, camera preparation order, background script clear color and transition gates. Initial camera and inactive embedded VMs are prepared fixture state; the stage factory is not tested. Texture allocation is an ANM dimension boundary. Background GPU drawing, stage transitions and deformation are not claimed.'});
});
