import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync,readdirSync} from 'node:fs';import {resolve} from 'node:path';import {core,oracle,memory,string,root,report} from './helpers.mjs';
test('TH15 seven STD scene object tables, instances and animation indices match original loader',async()=>{
 const c=await core(),m=await oracle(),stage=m.allocate(0x6788),callbacks=[m.allocate(40),m.allocate(40),m.allocate(40)],bank=m.allocate(16),heap=m.heap,out=c.allocate(4096),r=c.stage_resource_create();let checks=0,loads=[],bindings=[],ticks=0;const summaries=[];
 m.replace(0x485f70,'scene animation resource boundary',()=>{const sp=m.reg('ESP');loads.push({id:m.u32(sp+4),name:m.string(m.u32(sp+8))});return bank;},2);
 m.replace(0x40b880,'scene primitive script binding boundary',()=>{const sp=m.reg('ESP');bindings.push({vm:m.u32(sp+4),script:m.i32(sp+8),bank:m.reg('ECX')});return 0;},2);
 m.replace(0x477e10,'scene primitive initial animation boundary',()=>{ticks++;return 0;});
 try{for(const name of readdirSync(resolve(root,'reference/assets')).filter(n=>n.endsWith('.std')).sort()){
  const src=readFileSync(resolve(root,'reference/assets',name)),p=c.allocate(src.length);memory(c,p,src.length).set(src);assert.equal(c.stage_resource_open(r,p,src.length),1,string(c,c.stage_resource_error(r)));m.heap=heap;m.view(stage,0x6788).fill(0);for(const cb of callbacks)m.view(cb,40).fill(0);const source=m.allocate(src.length);m.write(source,src);m.u32(stage+0x677c,source);m.u32(stage+0x6780,src.length);m.u32(stage+0x6774,summaries.length&1);loads=[];bindings=[];ticks=0;
  assert.equal(m.call(0x40f4b0,{ecx:stage,args:[0]}),0);const copied=m.u32(stage+0x673c),directory=m.u32(stage+0x6740),instances=m.u32(stage+0x6744),script=m.u32(stage+0x6748),count=src.readInt16LE(0),quads=src.readInt16LE(2);assert.deepEqual(loads,[{id:3+(summaries.length&1),name:string(c,c.stage_resource_name(r))}]);assert.equal(c.stage_resource_count(r,0),count);assert.equal(c.stage_resource_count(r,1),quads);assert.equal(directory,copied+0x90);checks+=5;
  for(let i=0;i<count;i++){c.stage_resource_object(r,i,out);assert.deepEqual(Buffer.from(memory(c,out,28)),Buffer.from(m.bytes(m.u32(directory+i*4),28)),name+' object '+i);checks++;}
  for(let i=0;i<c.stage_resource_count(r,2);i++){c.stage_resource_instance(r,i,out);assert.deepEqual(Buffer.from(memory(c,out,16)),Buffer.from(m.bytes(instances+i*16,16)));checks++;}
  for(let i=0;i<c.stage_resource_count(r,3);i++){const offset=c.stage_resource_instruction(r,i,out),length=new DataView(c.memory.buffer).getInt16(out+6,true);assert.deepEqual(Buffer.from(memory(c,out,length<0?8:length)),Buffer.from(m.bytes(script+offset,length<0?8:length)));checks++;}
  m.u32(stage+4,callbacks[0]);m.u32(stage+8,callbacks[1]);m.u32(stage+0x6784,callbacks[2]);m.u32(0x4e9a60,stage);m.call(0x40f640);let index=0;
  for(let i=0;i<count;i++){let native=m.u32(directory+i*4)+28;assert.equal(m.bytes(native-25,1)[0],1);for(let q=0;q<c.stage_resource_primitive_count(r,i);q++){c.stage_resource_primitive(r,i,q,out);assert.deepEqual(Buffer.from(memory(c,out,28)),Buffer.from(m.bytes(native,28)),name+' primitive '+index);assert.deepEqual(bindings[index],{vm:m.u32(stage+0x6734)+index*0x608,script:src.readInt16LE(src.readUInt32LE(0x90+i*4)+(native-(m.u32(directory+i*4)))+4),bank});native+=src.readInt16LE(src.readUInt32LE(0x90+i*4)+(native-m.u32(directory+i*4))+2);index++;checks+=2;}}
  assert.equal(ticks,quads);assert.equal(bindings.length,quads);for(const cb of callbacks)assert.equal(m.u32(cb+4),2);checks+=5;summaries.push({name,objects:count,primitives:quads,instances:c.stage_resource_count(r,2),instructions:c.stage_resource_count(r,3)});c.release(p);
 }
 // Malformed files are checked by the bounded C++ parser only; the original loader is unsafe on them.
 const base=readFileSync(resolve(root,'reference/assets/st01.std'));const mutations=[b=>b.writeInt16LE(-1,0),b=>b.writeInt16LE(999,2),b=>b.writeUInt32LE(b.length+1,4),b=>b.writeUInt32LE(b.length+1,8),b=>b.fill(65,16,144),b=>b.writeUInt32LE(0,144),b=>b.writeInt16LE(1,b.readUInt32LE(144)+30),b=>b.writeInt16LE(999,b.readUInt32LE(4)),b=>b.writeInt16LE(9,b.readUInt32LE(8)+6),b=>b.writeInt32LE(0,b.readUInt32LE(8)+1064)];let invalid=0;
 for(const mutate of mutations){const b=Buffer.from(base);mutate(b);const p=c.allocate(b.length);memory(c,p,b.length).set(b);assert.equal(c.stage_resource_open(r,p,b.length),0,'invalid input '+invalid);assert.notEqual(string(c,c.stage_resource_error(r)),'');invalid++;c.release(p);checks+=2;}
 for(const size of [0,1,64,143,base.readUInt32LE(8)+1071]){const p=c.allocate(base.length);memory(c,p,base.length).set(base);assert.equal(c.stage_resource_open(r,p,size),0);c.release(p);checks++;invalid++;}
 report('stage-resource',{passed:true,files:summaries.length,checks,invalidInputs:invalid,originalFunctions:['0x40f4b0','0x40f640'],summaries,scope:'Original STD loader copying/relocation and primitive animation binding order; animation bank loading and initial VM execution are explicit boundaries. Actual background script execution, GPU rendering and stage sessions are not covered.'});
 }finally{c.stage_resource_delete(r);c.release(out);m.close();}
});
