import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync,readdirSync} from 'node:fs';import {resolve} from 'node:path';import {core,oracle,memory,string,root,report,enableNativeMath,enableOriginalVectorMath} from './helpers.mjs';import {resourceLoader,nativePool,nativeInstances,prepareBank,compareAnm} from './anm-oracle.mjs';
test('TH15 backgrounds run original primitive and embedded animation lifecycles with real seven ANM resources',async()=>{
 const c=await core();let frames=0,checks=0,slots=0,primitives=0;const summaries=[];
 for(const name of readdirSync(resolve(root,'reference/assets')).filter(n=>n.endsWith('.std')).sort()){
  const m=await oracle();enableNativeMath(m);const library=enableOriginalVectorMath(m);for(const entry of m.image.imports)if(entry.dll==='d3dx9_43.dll'&&library.exports.has(entry.name))m.u32(entry.address,library.exports.get(entry.name));const manager=c.anm_manager_create(),nm=nativePool(m),loader=resourceLoader(m),text=m.allocate(0x19270),owner=m.allocate(0x6788),callbacks=[m.allocate(40),m.allocate(40),m.allocate(40)],r=c.stage_resource_create();let scene=0;const data=readFileSync(resolve(root,'reference/assets',name)),cp=c.allocate(data.length);memory(c,cp,data.length).set(data);assert.equal(c.stage_resource_open(r,cp,data.length),1);
  const load=(name,id)=>{const b=readFileSync(resolve(root,'reference/assets',name)),p=c.allocate(b.length);memory(c,p,b.length).set(b);assert.equal(c.anm_manager_load(manager,id,p,b.length),1,name+' '+string(c,c.anm_manager_error(manager)));c.release(p);return prepareBank(m,loader,name,b,nm,id);};
  try{m.u32(0x4ca620,0x4e73e8);m.f32(0x4e73e8,1);m.u32(0x4e9a58,text);m.u32(text+0x19258,load('ascii.anm',2));assert.equal(c.anm_manager_fallback(manager,2),1);const bank=load(string(c,c.stage_resource_name(r)),3);m.view(owner,0x6788).fill(0);const input=m.allocate(data.length);m.write(input,data);m.u32(owner+0x677c,input);m.u32(owner+0x6780,data.length);m.replace(0x485f70,'loaded real background ANM bank boundary',()=>bank,2);assert.equal(m.call(0x40f4b0,{ecx:owner,args:[0]}),0);m.u32(0x4e9a60,owner);m.u32(owner+4,callbacks[0]);m.u32(owner+8,callbacks[1]);m.u32(owner+0x6784,callbacks[2]);m.u32(owner+0x318,owner);m.i32(owner+12,-1);m.u32(owner+0x1c,1);m.u32(owner+0x675c,1);m.f32(owner+0x1f4,-600);m.f32(owner+0x1fc,300);m.f32(owner+0x200,600);m.f32(owner+0x208,1);m.f32(owner+0x218,1);m.f32(owner+0x240,.6);m.f32(owner+0x337c,9999999);for(let i=0;i<8;i++)m.call(0x40db10,{ecx:owner+0x31c+i*0x608});m.call(0x40f640);scene=c.stage_scene_create(r,manager,3);assert.equal(c.stage_scene_initialize(scene,.6),1,string(c,c.stage_scene_error(scene)));const npr=c.stage_resource_count(r,1);primitives+=npr;
   const check=label=>{for(let i=0;i<npr;i++)compareAnm(c,m,c.stage_scene_vm(scene,i,0),m.u32(owner+0x6734)+i*0x608,name+'/'+label+' primitive '+i);for(let i=0;i<8;i++){const np=owner+0x31c+i*0x608;if(m.u32(np+0x28)===3){compareAnm(c,m,c.stage_scene_vm(scene,i,1),np,name+'/'+label+' slot '+i);slots++;}}for(let i=0;i<c.stage_resource_count(r,0);i++)assert.equal(c.stage_scene_object_flags(scene,i),m.bytes(m.u32(m.u32(owner+0x6740)+i*4)+3,1)[0]);checks+=npr+1;};check('initial');
   for(let frame=0;frame<3600;frame++){
    const rate=[1,.5,1.25,1][Math.floor(frame/900)],flags=frame%41===0?8:frame%43===0?4:0,age=[0,29,30,59,60][frame%5];m.u32(owner+0x675c,1|flags);m.i32(owner+0x6764,age);m.f32(0x4e73e8,rate);assert.equal(m.call(0x40e6b0,{ecx:owner}),1);assert.equal(c.stage_scene_update(scene,rate,1|flags,age),1,name+'/'+frame+' '+string(c,c.stage_scene_error(scene)));assert.deepEqual(Buffer.from(memory(c,c.stage_scene_direction(scene),12)),Buffer.from(m.bytes(owner+0x210,12)),name+'/'+frame+' prepared camera direction');assert.equal(c.stage_scene_color(scene)>>>0,m.u32(0x4e8214));if(frame<8||frame%32===0||frame===3599)check(frame);
    for(let alt=0;alt<2;alt++){assert.equal(c.anm_manager_update(manager,alt,rate),1,string(c,c.anm_manager_error(manager)));m.call(alt?0x487890:0x487740,{ecx:nm});const list=nativeInstances(m,nm,alt);assert.equal(c.anm_manager_count(manager,alt),list.length);for(let i=0;i<list.length;i++){const h=m.u32(list[i]+0x544);assert.equal(c.anm_manager_order(manager,alt,i),h);if(frame<8||frame%32===0)compareAnm(c,m,c.anm_manager_find(manager,h),list[i],name+'/'+frame+' pooled '+i);}}checks+=4;frames++;
   }summaries.push({name,frames:3600,primitives:npr});
  }finally{if(scene)c.stage_scene_delete(scene);c.stage_resource_delete(r);c.release(cp);c.anm_manager_delete(manager);m.close();}
 }
 report('stage-scene',{passed:true,files:7,frames,checks,primitives,embeddedChecks:slots,summaries,originalFunctions:['0x40f640','0x40f740','0x40e6b0','0x40fbc0','0x477e10','0x487740','0x487890'],scope:'Real seven background ANM banks and original complete stage update callback, initial primitive binding, primitive/embedded/pool animation timing, object flags, camera preparation order, background script clear color and transition gates. Initial camera and inactive embedded VMs are prepared fixture state; the stage factory is not tested. Texture allocation is an ANM dimension boundary. Background GPU drawing, stage transitions and deformation are not claimed.'});
});
