import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync,readdirSync} from 'node:fs';import {resolve} from 'node:path';import {core,oracle,memory,string,root,report,enableNativeMath} from './helpers.mjs';
const sections=[[0,0x30],[0x30,0x1e0],[0x1e0,0x204],[0x21c,0x238],[0x2e4,0x30c],[0x3350,0x3374],[0x3378,0x3390],...Array.from({length:8},(_,i)=>[0x328+i*0x608,0x32c+i*0x608])];
const snapshot=(c,s,p)=>{c.stage_script_snapshot(s,p);return Buffer.from(memory(c,p,0x3390));};
function fixture(commands){const header=Buffer.alloc(0x94);header.writeUInt32LE(0x90,4);header.writeUInt32LE(0x94,8);header.write('fixture.anm',16);header.writeInt16LE(-1,0x90);const chunks=[];for(const {time=0,op,args=[]} of commands){const b=Buffer.alloc(8+args.length*4);b.writeInt32LE(time,0);b.writeInt16LE(op,4);b.writeInt16LE(b.length,6);args.forEach((v,i)=>b.writeUInt32LE(v>>>0,8+i*4));chunks.push(b);}const end=Buffer.alloc(8,255);return Buffer.concat([header,...chunks,end]);}
const float=x=>{const b=Buffer.alloc(4);b.writeFloatLE(x);return b.readUInt32LE();};
test('TH15 STD camera scripts match original across all seven backgrounds and camera effects',async()=>{
 const c=await core(),m=await oracle();enableNativeMath(m);const owner=m.allocate(0x6788),native=owner+12,out=c.allocate(0x3390),r=c.stage_resource_create(),rate=m.allocate(4),heap=m.heap;let checks=0,frames=0,events=[],bank=0x1234;const summaries=[];m.u32(0x4ca620,rate);m.u32(0x4e9a60,owner);
 m.replace(0x40b880,'embedded scene ANM binding boundary',()=>{const sp=m.reg('ESP'),vm=m.u32(sp+4);events.push(1,Math.trunc((vm-native-0x310)/0x608),m.u32(sp+8));m.u32(vm+0x18,1);return 0;},2);
 m.replace(0x477e10,'initial embedded scene ANM execution boundary',()=>0);
 m.replace(0x40dd40,'deformation resource teardown boundary',()=>0);
 m.replace(0x422bf0,'deformation resource construction boundary',()=>{events.push(2,m.u32(m.reg('ESP')+8));return m.reg('ECX');},3);
 m.replace(0x40fb50,'scene object animation interrupt boundary',()=>{events.push(3,m.u32(m.reg('ESP')+4));return 0;},1);
 const run=(name,source,count,speed=1,interrupts=[])=>{
  m.heap=heap;const input=m.allocate(source.length);m.write(input,source);m.view(owner,0x6788).fill(0);m.u32(owner+0x6748,input+source.readUInt32LE(8));m.u32(owner+0x674c,bank);m.f32(rate,speed);m.u32(0x4e8214,0);const p=c.allocate(source.length);memory(c,p,source.length).set(source);assert.equal(c.stage_resource_open(r,p,source.length),1,string(c,c.stage_resource_error(r)));const s=c.stage_script_create(r);m.write(native,snapshot(c,s,out));m.u32(native+0x30c,owner);events=[];
  try{for(let frame=0;frame<count;frame++){
   if(interrupts.some(x=>x[0]===frame)){for(const [f,id]of interrupts.filter(x=>x[0]===frame)){m.call(0x410930,{args:[id]});assert.equal(c.stage_script_interrupt(s,id),1,string(c,c.stage_script_error(s)));}}
   c.stage_script_event_reset(s);events=[];const oldColor=m.u32(0x4e8214);m.call(0x40fbc0,{ecx:native});assert.equal(c.stage_script_step(s,speed),1,name+' '+frame+' '+string(c,c.stage_script_error(s)));const got=snapshot(c,s,out);for(const [a,b]of sections){const want=Buffer.from(m.bytes(native+a,b-a));if(!got.subarray(a,b).equals(want)){let j=0;while(j<b-a&&got[a+j]===want[j])j++;assert.fail(name+' frame '+frame+' byte 0x'+(a+j).toString(16)+' C++='+got.subarray((a+j)&~3,((a+j)&~3)+4).toString('hex')+' original='+Buffer.from(m.bytes(native+((a+j)&~3),4)).toString('hex'));}checks++;}assert.equal(c.stage_script_clear(s)>>>0,m.u32(0x4e8214));
   const raw=Buffer.from(memory(c,c.stage_script_events(s),c.stage_script_event_count(s)*4)),all=Array.from({length:raw.length/4},(_,i)=>raw.readUInt32LE(i*4));let filtered=[];for(let i=0;i<all.length;){const op=all[i++];if(op===0){i++;continue;}const n=op===1?2:1;filtered.push(op,...all.slice(i,i+n));i+=n;}assert.deepEqual(filtered,events,name+' world requests frame '+frame);checks+=2;frames++;
  }summaries.push({name,frames:count,rate:speed});}finally{c.stage_script_delete(s);c.release(p);}
 };
 try{
 for(const name of readdirSync(resolve(root,'reference/assets')).filter(n=>n.endsWith('.std')).sort())run(name,readFileSync(resolve(root,'reference/assets',name)),8000);
 for(let kind=0;kind<12;kind++)run('camera-effect-'+kind,fixture([{op:6,args:[float(.1),float(1),float(.2)]},{op:12,args:[kind]},{op:0,time:0}]),3300,[1,.5,2][kind%3]);
 run('all-script-opcodes',fixture([{op:2,args:[float(10),float(-20),float(30)]},{op:4,args:[0,0,float(1)]},{op:6,args:[0,float(1),0]},{op:8,args:[0xaedcf3b1,float(30),float(800)]},{op:3,args:[120,2,float(40),float(60),float(80)]},{op:5,args:[90,3,float(.2),float(.3),float(.8)]},{op:18,args:[140,1,float(.1),float(.9),float(.1)]},{op:9,args:[80,0,0xff734ab0,float(100),float(1000)]},{op:13,args:[0xff0f1838]},{op:14,args:[3,4,2]},{op:17,args:[1]},{op:19,args:[123]},{op:20,args:[float(5000)]},{op:15},{op:16,args:[7]},{time:12,op:14,args:[3,0xffffffff,4]},{time:15,op:17,args:[2]},{time:30,op:10,args:[60,0,float(1),float(2),float(3),float(10),float(20),float(30),float(2),float(3),float(4)]},{time:30,op:11,args:[80,0,float(.1),float(.2),float(.3),float(.2),float(.4),float(.6),float(.2),float(.3),float(.4)]},{time:150,op:0}]),200,.5);
 run('interrupt-label-offset',fixture([{op:7,args:[float(.6)]},{op:0},{time:50,op:16,args:[42]},{time:51,op:2,args:[float(5),float(7),float(9)]},{time:60,op:0}]),120,1,[[10,42],[30,999]]);
 report('stage-script',{passed:true,frames,checks,files:7,summaries,originalFunctions:['0x40fbc0','0x410930'],scope:'Original STD interpretation, camera/fog interpolation, eight embedded animation slots, camera effects and world request order. Actual ANM/world effect execution and GPU output are boundaries; no full gameplay replay is claimed.'});
 }finally{c.stage_resource_delete(r);c.release(out);m.close();}
});
