import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {resolve} from 'node:path';import {core,memory,string,root,report} from './helpers.mjs';
function eclHeader(b){let p=36,limit=36+b.readUInt16LE(6);const out={animations:[],includes:[]};if(p===limit)return out;function names(){let count=b.readUInt32LE(p+4);p+=8;const list=[];while(count--){const end=b.indexOf(0,p);assert.ok(end>=p&&end<limit);list.push(b.toString('ascii',p,end));p=end+1;}p=(p+3)&~3;return list;}if(b.toString('ascii',p,p+4)==='ANIM')out.animations=names();if(p+8<=limit&&b.toString('ascii',p,p+4)==='ECLI')out.includes=names();return out;}
test('TH15 seven actual stage bundles preload four characters, original ECL dependencies and logical resource aliases',async()=>{
 const c=await core(),names=c.allocate(256),out=c.allocate(80);let cases=0,resources=0;const bytes=name=>readFileSync(resolve(root,'reference/assets',name));
 try{for(let stage=1;stage<=7;stage++)for(let character=0;character<4;character++){const f=c.stage_assets_create(),files=new Map(),ptrs=[],wanted=['ascii.anm','text.anm','front.anm','bullet.anm','effect.anm','pl0'+character+'.anm','pl0'+character+'.sht','st0'+stage+'.std','st0'+stage+'logo.anm','st0'+stage+String.fromCharCode(97+character)+'.msg'];let fileCount=0,definitions=0;const expectedAnimations=['ascii.anm','text.anm','front.anm','bullet.anm','effect.anm','pl0'+character+'.anm'];try{
 const std=bytes('st0'+stage+'.std'),end=std.indexOf(0,16),scenery=std.toString('ascii',16,end);wanted.push(scenery);expectedAnimations.push(scenery,'st0'+stage+'logo.anm');const aliases=['bullet.anm','effect.anm',null,null,null,null];function walk(name){const b=bytes(name);wanted.push(name);files.set(name,b);fileCount++;definitions+=b.readUInt16LE(16);const h=eclHeader(b);h.animations.forEach((n,i)=>{aliases[i+2]=n;wanted.push(n);if(!expectedAnimations.includes(n))expectedAnimations.push(n);});for(const child of h.includes)walk(child);}walk('st0'+stage+'.ecl');for(const name of wanted)if(!files.has(name))files.set(name,bytes(name));for(const [name,data]of files){const p=c.allocate(data.length);memory(c,p,data.length).set(data);ptrs.push(p);memory(c,names,name.length+1).set(Buffer.from(name+'\0'));c.stage_assets_file(f,names,p,data.length);}
 assert.equal(c.stage_assets_load(f,stage,character),1,stage+'/'+character+' '+string(c,c.stage_assets_error(f)));c.stage_assets_values(f,out);const values=Array.from(new Int32Array(c.memory.buffer,out,20)),loaded=Array.from({length:c.stage_assets_animation_count(f)},(_,i)=>string(c,c.stage_assets_animation_name(f,i)));assert.deepEqual(loaded,expectedAnimations,stage+'/'+character+' preload order');const bank=name=>loaded.indexOf(name)+1;assert.deepEqual(values.slice(0,8),['ascii.anm','text.anm','front.anm','bullet.anm','effect.anm','pl0'+character+'.anm','st0'+stage+'logo.anm',scenery].map(bank));assert.deepEqual(values.slice(8,14),aliases.map(n=>n===null?-1:bank(n)));assert.equal(values[14],files.get(wanted[9]).readUInt32LE(0));assert.equal(values[15],std.readInt16LE(0));assert.equal(values[17],files.get('pl0'+character+'.sht').readUInt16LE(2));assert.equal(values[18],fileCount);assert.equal(values[19],definitions);memory(c,names,5).set(Buffer.from('main\0'));assert.notEqual(c.program_find(c.stage_assets_program(f),names),0);assert.equal(c.stage_assets_load(f,stage,character),0,'reject repeated scene initialization');cases++;resources+=loaded.length;
 }finally{c.stage_assets_delete(f);for(const p of ptrs)c.release(p);}}
 const missing=c.stage_assets_create();try{assert.equal(c.stage_assets_load(missing,1,0),0);assert.match(string(c,c.stage_assets_error(missing)),/ascii\.anm/);}finally{c.stage_assets_delete(missing);}report('stage-assets',{passed:true,cases,resources,scope:'Headless scene asset integration for seven stages/four characters with real common/player/stage ANM templates, original STD/MSG/SHT and transitive ECL dependencies. Independent file directory/header expectations and alias mapping; asset templates/parsers separately compared with native. No complete stage simulation, native global initialization RNG, GPU, fonts or browser claim.'});
 }finally{c.release(names);c.release(out);}
});
