import test from 'node:test';import assert from 'node:assert/strict';import{readFileSync,readdirSync}from 'node:fs';import{resolve}from 'node:path';import{core,memory,string,root,report}from './helpers.mjs';
test('TH15 actual stage bundles coexist in one manager and retire their owned banks without erasing the next scene',async()=>{
 const c=await core(),f=c.shared_stage_assets_create(),name=c.allocate(256),owned=[];let scenes=0,checks=0,released=0,maxBanks=0;
 try{for(const file of readdirSync(resolve(root,'reference/assets')).filter(n=>/\.(anm|ecl|sht|std|msg)$/.test(n))){const bytes=readFileSync(resolve(root,'reference/assets',file)),p=c.allocate(bytes.length);owned.push(p);memory(c,p,bytes.length).set(bytes);memory(c,name,file.length+1).set(Buffer.from(file+String.fromCharCode(0)));c.shared_stage_assets_file(f,name,p,bytes.length);}
  for(let character=0;character<4;character++)for(let stage=1;stage<=7;stage++){
   assert.equal(c.shared_stage_assets_load(f,0,stage,character),1,string(c,c.shared_stage_assets_error(f,0)));const countA=c.shared_stage_assets_animation_count(f,0),idsA=Array.from({length:14},(_,i)=>c.shared_stage_assets_resource(f,0,i)).filter(n=>n>=0),h0=c.shared_stage_assets_spawn(f,0,0);assert.ok(h0);assert.equal(c.shared_stage_assets_update(f),1,string(c,c.shared_stage_assets_error(f,0)));
   assert.equal(c.shared_stage_assets_load(f,1,stage%7+1,character),1,string(c,c.shared_stage_assets_error(f,1)));const countB=c.shared_stage_assets_animation_count(f,1),idsB=Array.from({length:14},(_,i)=>c.shared_stage_assets_resource(f,1,i)).filter(n=>n>=0),h1=c.shared_stage_assets_spawn(f,1,0);assert.ok(h1);assert.equal(c.shared_stage_assets_value(f,0),countA+countB);assert.ok(idsA.every(n=>!idsB.includes(n)),'coexisting logical banks cannot collide');assert.equal(c.shared_stage_assets_update(f),1);maxBanks=Math.max(maxBanks,c.shared_stage_assets_value(f,0));
   c.shared_stage_assets_unload(f,0);assert.equal(c.shared_stage_assets_value(f,0),countB);assert.ok(c.shared_stage_assets_value(f,1)>0,'live retired animations retain backing resource');assert.ok(c.shared_stage_assets_find(f,h0));assert.ok(c.shared_stage_assets_find(f,h1));assert.equal(c.shared_stage_assets_update(f),1);assert.equal(c.shared_stage_assets_find(f,h0),0);assert.ok(c.shared_stage_assets_find(f,h1),'next scene remains active');assert.equal(c.shared_stage_assets_value(f,1),0);released+=countA;assert.equal(c.shared_stage_assets_value(f,2),released);
   c.shared_stage_assets_unload(f,1);assert.equal(c.shared_stage_assets_value(f,0),0);assert.equal(c.shared_stage_assets_update(f),1);assert.equal(c.shared_stage_assets_find(f,h1),0);assert.equal(c.shared_stage_assets_value(f,1),0);assert.equal(c.shared_stage_assets_value(f,3),0);released+=countB;assert.equal(c.shared_stage_assets_value(f,2),released);checks+=15;scenes+=2;
  }
  report('stage-resource-lifetime',{passed:true,scenes,checks,released,maxBanks,scope:'Seven stages/four characters, two actual bundles coexisting in one AnmManager, disjoint logical IDs, old scene animation retirement on the next tick, retained backing memory and resource-release callback until references disappear, next-scene survival and no retained banks/instances after cleanup. GPU texture release is a callback boundary; complete gameplay cross-stage factories and original timing remain separate.'});
 }finally{c.shared_stage_assets_delete(f);c.release(name);for(const p of owned)c.release(p);}
});
