import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {resolve} from 'node:path';import {core,oracle,memory,string,root,report,enableNativeMath,enableOriginalVectorMath} from './helpers.mjs';import {resourceLoader,nativePool,prepareBank,compareAnm,nativeInstances} from './anm-oracle.mjs';
test('TH15 STD wave and radial distortion reproduce original grids, phases, spell gate, RNG and animation ownership',async()=>{
 const c=await core(),m=await oracle();enableNativeMath(m);const lib=enableOriginalVectorMath(m);for(const entry of m.image.imports)if(entry.dll==='d3dx9_43.dll'&&entry.name==='D3DXVec3Normalize')m.u32(entry.address,lib.exports.get(entry.name));const am=c.anm_manager_create(),nm=nativePool(m),loader=resourceLoader(m),text=m.allocate(0x19270),native=m.allocate(0x3390),grid=m.allocate(0x1c),spell=m.allocate(0x80);let frames=0,checks=0,object=0;
 try{m.u32(0x4e9a58,text);m.u32(0x4ca620,0x4e73e8);m.f32(0x4e73e8,1);m.u32(0x4e797c,1);m.u32(0x4e9a70,spell);
 for(const[name,id]of [['ascii.anm',2],['text.anm',6]]){const b=readFileSync(resolve(root,'reference/assets',name)),p=c.allocate(b.length);memory(c,p,b.length).set(b);assert.equal(c.anm_manager_load(am,id,p,b.length),1,string(c,c.anm_manager_error(am)));c.release(p);const bank=prepareBank(m,loader,name,b,nm,id);if(id===2){assert.equal(c.anm_manager_fallback(am,2),1);m.u32(text+0x19258,bank);}else m.u32(0x4e7f00,bank);}
 for(const mode of [1,2])for(let sample=0;sample<24;sample++){
  object=c.stage_deformation_create(am,6);const seed=Buffer.alloc(8);seed.writeUInt16LE(37+sample*1997);seed.writeUInt32LE(53,4);memory(c,c.anm_manager_random(am),8).set(seed);m.write(0x4e9a40,seed);m.view(grid,0x1c).fill(0);m.view(native,0x3390).fill(0);assert.equal(c.stage_deformation_begin(object,mode),1,string(c,c.stage_deformation_error(object)));const rows=mode===1?7:17;m.call(0x422bf0,{ecx:grid,args:[0,rows,0]});m.u32(native+0x3374,grid);const state=Buffer.alloc(24);state.writeFloatLE(32+sample,0);state.writeFloatLE(192+sample*2,4);state.writeUInt32LE(0xffa37218,8);state.writeFloatLE(Math.fround((sample%5-2)*.375),12);state.writeFloatLE(Math.fround((sample%7-3)*.25),16);state.writeInt32LE(mode,20);memory(c,c.stage_deformation_field(object,0),24).set(state);m.write(native+0x3378,state);const viewport=[640+sample%3*320,480+sample%3*240,224+sample%4*32,16+sample%5*8,32+sample%4*32];viewport.forEach((v,i)=>{new DataView(c.memory.buffer).setInt32(c.stage_deformation_field(object,1)+i*4,v,true);m.i32([0x51bbfc,0x51bc00,0x51bc20,0x51bc24,0x51bc08][i],v);});
  for(let i=0;i<17;i++){const handle=c.stage_deformation_handle(object,i)>>>0,expected=i===0?m.u32(grid+8):m.u32(m.u32(grid+0xc)+(i-1)*4);assert.equal(handle,expected);compareAnm(c,m,c.anm_manager_find(am,handle),m.call(0x488510,{ecx:nm,args:[expected]}),mode+'/'+sample+' initial '+i);checks+=2;}
  for(let frame=0;frame<96;frame++){
   const active=frame>=20&&frame<28;const rate=[1,.5,.25,1.25][frame%4];m.u32(spell+0x78,active?1:0);m.f32(0x4e73e8,rate);m.call(0x410d90,{ecx:native});assert.equal(c.stage_deformation_update(object,active?1:0,0),1,string(c,c.stage_deformation_error(object)));const label=mode+'/'+sample+'/'+frame;assert.deepEqual(Buffer.from(memory(c,c.stage_deformation_field(object,0),24)),Buffer.from(m.bytes(native+0x3378,24)),label+' state');assert.deepEqual(Buffer.from(memory(c,c.stage_deformation_field(object,2),17*rows*28)),Buffer.from(m.bytes(m.u32(grid+0x14),17*rows*28)),label+' grid');assert.deepEqual(Buffer.from(memory(c,c.stage_deformation_field(object,3),17*rows*12)),Buffer.from(m.bytes(m.u32(grid+0x18),17*rows*12)),label+' sampling');assert.deepEqual(Buffer.from(memory(c,c.anm_manager_random(am),8)),Buffer.from(m.bytes(0x4e9a40,8)),label+' RNG');checks+=4;
   for(let i=0;i<16;i++){const cv=c.anm_manager_find(am,c.stage_deformation_handle(object,i+1)),np=m.u32(m.u32(grid+0x10)+i*4);assert.deepEqual(Buffer.from(memory(c,c.anm_vm_screen_vertices(cv),rows*2*28)),Buffer.from(m.bytes(m.u32(np+0x5c4),rows*2*28)),label+' pre-capture strip '+i);checks++;}
   frames++;
  }
  c.stage_deformation_delete(object);object=0;m.call(0x40dd40,{ecx:grid});assert.equal(c.anm_manager_update(am,0,1),1);m.call(0x487740,{ecx:nm});assert.equal(c.anm_manager_count(am,0),0);assert.equal(nativeInstances(m,nm,0).length,0);
 }
 report('stage-std-deformation',{passed:true,cases:48,frames,checks,originalFunctions:['0x422bf0','0x410d90','0x422d30','0x422f20','0x40dd40'],scope:'Actual text ANM capture/strip ownership and native background wave/radial callbacks: full CPU grid and sampling bytes, pre-capture strips, fixed phase/radius evolution, visual RNG and spell gate. Frame-rate parameter intentionally does not rescale original per-frame deformation. Captured GPU pixels and complete game compositions remain separate.'});
 }finally{if(object)c.stage_deformation_delete(object);c.anm_manager_delete(am);m.close();}
});
