import test from 'node:test';import assert from 'node:assert/strict';import {core,memory,string,report} from './helpers.mjs';import {preloadStage} from './stage-assets-fixture.mjs';
test('TH15 actual stage resources drive one shared background/battle/dialogue/HUD/checkpoint scene',async()=>{
 const c=await core(),out=c.allocate(48);let frames=0,checks=0;const summaries=[],selectedCharacter=Number(process.env.TH15_STAGE_GAMEPLAY_CHARACTER||0),limit=Number(process.env.TH15_STAGE_GAMEPLAY_FRAMES||3600),stages=process.env.TH15_STAGE_GAMEPLAY_STAGE?[Number(process.env.TH15_STAGE_GAMEPLAY_STAGE)]:[1,2,3,4,5,6,7];
 try{for(const stage of stages){const character=selectedCharacter,a=preloadStage(c,stage,character),scene=c.stage_gameplay_create(a.fixture);const dv=()=>new DataView(c.memory.buffer);let maximumEnemies=0,maximumBullets=0,maximumLasers=0,maximumItems=0;try{assert.ok(scene);assert.equal(c.stage_gameplay_prepare(scene),1,string(c,c.stage_gameplay_error(scene)));assert.equal(c.stage_gameplay_begin(scene),1,string(c,c.stage_gameplay_error(scene)));const progress=c.stage_gameplay_field(scene,0);
 for(let frame=0;frame<limit;frame++){dv().setInt32(progress+8,frame,true);dv().setInt32(progress+12,frame,true);assert.equal(c.stage_gameplay_step(scene,1|0x100,frame%12===0?1:0,frame+1,frame+1),1,'stage '+stage+' frame '+frame+' '+string(c,c.stage_gameplay_error(scene)));c.stage_gameplay_counts(scene,out);const counts=Array.from(new Uint32Array(c.memory.buffer,out,12));maximumEnemies=Math.max(maximumEnemies,counts[0]);maximumBullets=Math.max(maximumBullets,counts[1]);maximumLasers=Math.max(maximumLasers,counts[2]);maximumItems=Math.max(maximumItems,counts[3]);assert.equal(counts[9],frame+1,'background follows the same frame loop');if(counts[10]!==0xffffffff)dv().setInt32(progress+4,counts[10]|0,true);frames++;checks+=2;}
 c.stage_gameplay_counts(scene,out);const counts=Array.from(new Uint32Array(c.memory.buffer,out,12));assert.ok(maximumEnemies>1,"actual stage waves must spawn");assert.ok(maximumBullets>0,"actual stage waves must shoot");if(limit>=90000&&stage<7)assert.equal(counts[6],1,"normal stage must reach completion");summaries.push({stage,character,frames:limit,maximumEnemies,maximumBullets,maximumLasers,maximumItems,dialogueActive:counts[4],completions:counts[6],musicRequests:counts[7],textRequests:counts[8]});
 }finally{if(scene)c.stage_gameplay_delete(scene);a.close();}}
 report('stage-gameplay-integration-c'+selectedCharacter+'-f'+limit+'-'+stages.join('-'),{passed:true,frames,checks,summaries,scope:'Unmodified actual ECL/STD/ANM/SHT/MSG resources run through owned GameBattle/StageScene/GameHud/PopupManager/MessageController and one FrameScheduler. Controlled stage clock, full power, invulnerability and accelerated dialogue are fixture input; text pixels, sound, records, transition destinations and checkpoint persistence are explicit presentation boundaries. Native full-stage/replay, full HUD frame/draw and GPU/browser parity are not yet claimed.'});}finally{c.release(out);}
});
