import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {resolve} from 'node:path';import {core,oracle,memory,string,root,report,enableNativeMath} from './helpers.mjs';import {resourceLoader,nativePool,prepareBank,nativeInstances,compareAnm} from './anm-oracle.mjs';
const load=(c,a,name,id)=>{const data=readFileSync(resolve(root,'reference/assets',name)),p=c.allocate(data.length);memory(c,p,data.length).set(data);assert.equal(c.anm_manager_load(a,id,p,data.length),1,string(c,c.anm_manager_error(a)));c.release(p);return data;};
const cstring=(bytes)=>Buffer.from(bytes.subarray(0,bytes.indexOf(0)<0?bytes.length:bytes.indexOf(0)));
test('TH15 actual Music Room catalog, animations, text timing, locked confirmation, scroll and title BGM restoration match original',async()=>{
 const c=await core(),m=await oracle();enableNativeMath(m);const loader=resourceLoader(m),base=m.heap,raw=readFileSync(resolve(root,'reference/assets/musiccmt.txt'));let frames=0,checks=0,textChecks=0,events=[],texts=[];const anmReader=m.importMap.get((0x402db0+5+Buffer.from(m.bytes(0x402db0,5)).readInt32LE(1))>>>0).handler;
 const byte=(p,v)=>v===undefined?m.view(p,1)[0]:(m.view(p,1)[0]=v),nativeString=p=>cstring(m.bytes(p,1024));
 m.replace(0x476360,'menu sound output',()=>{events.push('sound:'+m.u32(m.reg('ESP')+4));return 0;},2);
 m.replace(0x476f10,'music command output',()=>{events.push('command:'+m.u32(m.reg('ESP')+4));return 0;},3);
 m.replace(0x44d360,'music loading output',()=>{events.push('music:'+nativeString(m.u32(m.reg('ESP')+8)).toString());return 0;},2);
 m.replace(0x44d3e0,'title music reset output',()=>{events.push('command:0');return 0;},2);
 m.replace(0x4869c0,'raster text output',()=>{const sp=m.reg('ESP'),vm=m.u32(sp+8);assert.deepEqual(m.readWords(sp+16,4),[0,0,0,0]);let text=nativeString(m.u32(sp+32));if(text.includes(Buffer.from('%2d')))text=Buffer.concat([Buffer.from('No.'+String(m.u32(sp+36)).padStart(2)+'  '),Buffer.from([0x81,0x48,0x81,0x48,0x81,0x48,0x81,0x48,0x81,0x48,0x81,0x48,0x81,0x48,0x81,0x48,0x81,0x48,0x81,0x48,0x81,0x48])]);texts.push({handle:m.u32(vm+0x544),color:m.u32(sp+12),bytes:text});return 0;});
 try{for(let scenario=0;scenario<8;scenario++){
  m.heap=base;m.replace(0x402db0,"animation asset boundary",anmReader,1);m.view(m.heap,0x1caf980).fill(0);const a=c.anm_manager_create(),native=nativePool(m),owner=m.allocate(0x5bb0),text=m.allocate(0x19270),record=m.allocate(0x33780),f=c.title_menu_create(a),music=c.title_music_create(f);
  try{
   m.u32(0x4e9a40,0);m.u32(0x4e9a44,0);m.view(owner,0x5bb0).fill(0);m.view(text,0x19270).fill(0);m.view(record,0x33780).fill(0);m.u32(0x4e9a58,text);m.u32(0x4e9bc8,record);m.u32(0x4ca620,0x4e73e8);m.f32(0x4e73e8,1);m.i32(owner+0x18,14);m.i32(owner+0x1c,1);m.i32(owner+0xf4,1);m.i32(owner+0x2c,9);m.i32(owner+0x24,5);m.call(0x403b10,{ecx:owner+0x24});c.title_menu_configure(f,5,1,0,0);c.title_menu_count(f,9);c.title_menu_push(f);
   const mask=scenario%3===0?0x1ffff:scenario%3===1?1:0x15555,alternate=scenario%2;for(let i=0;i<20;i++)byte(record+0x3374e+i,(mask>>i)&1);byte(0x4e79cc,alternate?16:0);
   const p=c.allocate(raw.length);memory(c,p,raw.length).set(raw);assert.equal(c.title_music_configure(music,p,raw.length,mask,alternate),1);c.release(p);const age=c.title_menu_field(f,2);m.write(owner+0x2b0,Buffer.from(memory(c,age,20)));
   for(const[name,id]of[['ascii.anm',5],['text.anm',2],['title.anm',16]]){const data=load(c,a,name,id),bank=prepareBank(m,loader,name,data,native,id);if(id===5){m.u32(text+0x19258,bank);assert.equal(c.anm_manager_fallback(a,5),1);}else if(id===2)m.u32(0x4e7f00,bank);else m.u32(owner+0x10,bank);}
   m.replace(0x402db0,'actual music catalog asset',()=>{const p=m.allocate(raw.length);m.write(p,raw);m.u32(m.reg('EDX'),raw.length);return p;},1);
   const compareQueue=label=>{for(let alt=0;alt<2;alt++){const list=nativeInstances(m,native,alt);assert.equal(c.anm_manager_count(a,alt),list.length,label+' count');for(let i=0;i<list.length;i++){const h=m.u32(list[i]+0x544);assert.equal(c.anm_manager_order(a,alt,i),h,label+' queue');const vm=c.anm_manager_find(a,h);compareAnm(c,m,vm,list[i],label+' script '+(m.u32(list[i]+0x4a8)&65535));assert.deepEqual(Buffer.from(memory(c,c.anm_vm_translation(vm),12)),Buffer.from(m.bytes(list[i]+0x5ec,12)));checks++;}}};
   const step=(pressed=0,repeated=0)=>{
    const label=scenario+'/'+frames;m.u32(0x4e6d1c,pressed);m.u32(0x4e6d18,repeated);events=[];texts=[];assert.equal(m.call(0x46b3a0,{ecx:owner}),0);assert.equal(c.title_music_update(music,pressed,repeated),1,label+': '+string(c,c.title_music_error(music)));
    assert.deepEqual(Array.from({length:c.title_music_event_count(music)},(_,i)=>string(c,c.title_music_event(music,i))),events,label+' audio');
    assert.equal(c.title_music_text_count(music),texts.length,label+' texts');for(let i=0;i<texts.length;i++){const p=c.title_music_text_bytes(music,i),data=memory(c,p,1024);assert.equal(c.title_music_text_value(music,i,0),texts[i].handle,label+' text handle');assert.equal(c.title_music_text_value(music,i,1),texts[i].color,label+' text color');assert.deepEqual(cstring(data),texts[i].bytes,label+' text '+i);textChecks++;}
    const st=Array.from(new Uint32Array(c.memory.buffer,c.title_menu_state(f),254));for(const[i,addr]of[[0,owner+0x18],[1,owner+0x1c],[2,owner+0x20],[3,owner+0xf4]])assert.equal(st[i],m.u32(addr),label+' state '+i);assert.deepEqual(Buffer.from(memory(c,c.title_menu_cursor(f),0xd8)),Buffer.from(m.bytes(owner+0x24,0xd8)),label+' menu');for(let i=0;i<248;i++)assert.equal(st[6+i],m.u32(owner+0x2c4+i*4),label+' handle '+i);
    for(const[i,offset]of[[0,0x58f8],[1,0x6ac],[2,0x6b0],[3,0x6b4],[4,0x6a8]])assert.equal(c.title_music_value(music,i),m.i32(owner+offset),label+' music field '+i);let savedMask=0;for(let i=0;i<20;i++)if(byte(record+0x3374e+i))savedMask|=1<<i;assert.equal(c.title_music_value(music,5),savedMask,label+' unlocked');
    assert.deepEqual(Buffer.from(memory(c,age,20)),Buffer.from(m.bytes(owner+0x2b0,20)),label+' timer');compareQueue(label+' pre-update');m.i32(owner+0x2b0,m.i32(owner+0x2b4));m.i32(owner+0x2b4,m.i32(owner+0x2b4)+1);m.f32(owner+0x2b8,Math.fround(m.f32(owner+0x2b8)+1));c.title_menu_tick(f,1);for(let alt=0;alt<2;alt++){assert.equal(c.anm_manager_update(a,alt,1),1,string(c,c.anm_manager_error(a)));m.call(alt?0x487890:0x487740,{ecx:native});}compareQueue(label+' post-update');frames++;return st[0];
   };
   step();assert.equal(c.title_music_value(music,4),17);for(let i=0;i<17;i++)for(let field=0;field<10;field++){const addr=field===0?owner+0x6b8+i*64:field===1?owner+0xeb8+i*66:owner+0x16f8+(i*8+field-2)*66;assert.deepEqual(cstring(memory(c,c.title_music_catalog(music,i,field),66)),nativeString(addr),scenario+' catalog '+i+'/'+field);}
   for(let i=0;i<29;i++)step();step(0x80001);for(let i=0;i<20;i++)step();step(32);step(0x80001);for(let i=0;i<20;i++)step();step(0x80001);for(let i=0;i<20;i++)step();
   for(let j=0;j<21;j++){step(j%2?0:32,j%2?32:0);step();}for(let j=0;j<20;j++)step(16);step(0x80001);step(32);step(0x80001);for(let i=0;i<20;i++)step();step(0x102);for(let i=0;i<14;i++)if(step()!==14)break;
  }finally{c.title_music_delete(music);c.title_menu_delete(f);c.anm_manager_delete(a);}
 }
 report('title-music-room',{passed:true,scenarios:8,frames,animationChecks:checks,textChecks,originalFunctions:['0x46b3a0','0x46c090','0x46c0d0'],scope:'Actual CP932 catalog and title/text/ascii animation trees, all text payloads and timing, confirmation/fade commands for locked music, scrolling/position interpolation, audio mode variants and title BGM restoration. Font raster and hardware audio are isolated services covered separately; no full application/browser claim.'});
 }finally{m.close();}
});
