import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {resolve} from 'node:path';import {core,oracle,memory,string,root,report,enableNativeMath} from './helpers.mjs';import {resourceLoader,nativePool,prepareBank,nativeInstances,compareAnm} from './anm-oracle.mjs';
const load=(c,a,name,id)=>{const data=readFileSync(resolve(root,'reference/assets',name)),p=c.allocate(data.length);memory(c,p,data.length).set(data);assert.equal(c.anm_manager_load(a,id,p,data.length),1,string(c,c.anm_manager_error(a)));c.release(p);return data;};
test('TH15 controller menu preserves original binding swaps, digit trees, first pressed button, restore/save and cancellation',async()=>{
 const c=await core(),m=await oracle();enableNativeMath(m);const loader=resourceLoader(m),buttons=m.allocate(32),base=m.heap;let frames=0,checks=0,sounds=[];
 m.replace(0x476360,'controller menu sound output',()=>{sounds.push(m.u32(m.reg('ESP')+4));return 0;},2);m.replace(0x401e20,'physical gamepad button boundary',()=>buttons);
 try{for(let scenario=0;scenario<12;scenario++){
  m.heap=base;m.view(m.heap,0x1caf980).fill(0);const a=c.anm_manager_create(),native=nativePool(m),owner=m.allocate(0x5bb0),text=m.allocate(0x19270),f=c.title_menu_create(a),controller=c.title_controller_create(f);try{
   m.u32(0x4e9a40,0);m.u32(0x4e9a44,0);m.view(owner,0x5bb0).fill(0);m.u32(0x4e9a58,text);m.u32(0x4ca620,0x4e73e8);m.f32(0x4e73e8,1);m.i32(owner+0x18,4);m.i32(owner+0x1c,3);m.i32(owner+0xf4,1);m.i32(owner+0x24,2);m.i32(owner+0x2c,5);m.call(0x403b10,{ecx:owner+0x24});c.title_menu_configure(f,2,3,0,0);c.title_menu_count(f,5);c.title_menu_push(f);
   const initial=Int16Array.from({length:10},(_,i)=>i<4?(scenario*5+i*3)%31:200+i),p=c.title_controller_field(controller,0),saved=c.title_controller_field(controller,2),pending=c.title_controller_field(controller,1),age=c.title_menu_field(f,2);memory(c,p,20).set(new Uint8Array(initial.buffer));m.write(0x4e6f44,Buffer.from(initial.buffer));memory(c,saved,20).fill(0xab);m.view(0x4e79a8,20).fill(0xab);m.write(owner+0x2b0,Buffer.from(memory(c,age,20)));
   for(const[name,id]of[['ascii.anm',5],['title.anm',16]]){const data=load(c,a,name,id),bank=prepareBank(m,loader,name,data,native,id);if(id===5){m.u32(text+0x19258,bank);assert.equal(c.anm_manager_fallback(a,5),1);}else m.u32(owner+0x10,bank);}
   const compareQueue=label=>{for(let alt=0;alt<2;alt++){const list=nativeInstances(m,native,alt);assert.equal(c.anm_manager_count(a,alt),list.length,label+' count');for(let i=0;i<list.length;i++){const h=m.u32(list[i]+0x544);assert.equal(c.anm_manager_order(a,alt,i),h,label+' queue');compareAnm(c,m,c.anm_manager_find(a,h),list[i],label+' script '+(m.u32(list[i]+0x4a8)&65535));checks++;}}};
   const step=(pressed=0,repeated=0,pad=0)=>{const label=scenario+'/'+frames;m.u32(0x4e6d1c,pressed);m.u32(0x4e6d18,repeated);m.view(buttons,32).fill(0);for(let i=0;i<32;i++)if((pad>>>i)&1)m.view(buttons+i,1)[0]=128;sounds=[];assert.equal(m.call(0x464950,{ecx:owner}),1);assert.equal(c.title_controller_update(controller,pressed,repeated,pad),1,label+': '+string(c,c.title_controller_error(controller)));
    assert.deepEqual(Array.from(new Int32Array(c.memory.buffer,c.title_menu_sounds(f),c.title_menu_sound_count(f))),sounds,label+' sounds');const st=Array.from(new Uint32Array(c.memory.buffer,c.title_menu_state(f),254));for(const[i,addr]of[[0,owner+0x18],[1,owner+0x1c],[2,owner+0x20],[3,owner+0xf4]])assert.equal(st[i],m.u32(addr),label+' state '+i);assert.deepEqual(Buffer.from(memory(c,c.title_menu_cursor(f),0xd8)),Buffer.from(m.bytes(owner+0x24,0xd8)),label+' menu');for(let i=0;i<248;i++)assert.equal(st[6+i],m.u32(owner+0x2c4+i*4),label+' handle '+i);
    assert.deepEqual(Buffer.from(memory(c,pending,12)),Buffer.from(m.bytes(owner+0x59ec,12)),label+' temporary bindings');assert.deepEqual(Buffer.from(memory(c,p,20)),Buffer.from(m.bytes(0x4e6f44,20)),label+' active settings');assert.deepEqual(Buffer.from(memory(c,saved,20)),Buffer.from(m.bytes(0x4e79a8,20)),label+' persisted settings');assert.deepEqual(Buffer.from(memory(c,age,20)),Buffer.from(m.bytes(owner+0x2b0,20)),label+' timer');compareQueue(label+' pre-update');m.i32(owner+0x2b0,m.i32(owner+0x2b4));m.i32(owner+0x2b4,m.i32(owner+0x2b4)+1);m.f32(owner+0x2b8,Math.fround(m.f32(owner+0x2b8)+1));c.title_menu_tick(f,1);for(let alt=0;alt<2;alt++){assert.equal(c.anm_manager_update(a,alt,1),1,string(c,c.anm_manager_error(a)));m.call(alt?0x487890:0x487740,{ecx:native});}compareQueue(label+' post-update');frames++;return st[0];};
   for(let i=0;i<12;i++)step();
   for(let i=0;i<4;i++){step(0,0,(1<<((scenario+i)%31))|(1<<((scenario+i+7)%31)));step(0,0,1<<((scenario+i)%31));step(32);}
   step(0x80001);step(16);step(0,0,1<<30);step(16);step(0,0,1<<9);step(0,32);step(0,32);step(0,0,0x80000000);step(0,32);
   step(scenario%3===0?0x102:0x80001);for(let i=0;i<14;i++)if(step()!==4)break;
  }finally{c.title_controller_delete(controller);c.title_menu_delete(f);c.anm_manager_delete(a);}
 }
 report('title-controller',{passed:true,scenarios:12,frames,animationChecks:checks,originalFunctions:['0x464950','0x464c30','0x4659d0','0x465ad0'],scope:'Original actual title digit/selection animation trees, physical button priority, no-op unchanged assignments, duplicate-binding swaps, temporary restoration, persisted settings and options-return timing. Platform gamepad polling and sound output are isolated boundaries.'});
 }finally{m.close();}
});
