import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {resolve} from 'node:path';import {core,oracle,memory,string,root,report,enableNativeMath} from './helpers.mjs';import {resourceLoader,nativePool,prepareBank,nativeInstances,compareAnm} from './anm-oracle.mjs';
test('TH15 original replay menu preserves three pages, async completion/cancel, actual title animations, disabled stages and normal/spell replay startup',async()=>{
 const c=await core(),m=await oracle();enableNativeMath(m);const loader=resourceLoader(m),scratch=m.allocate(8),base=m.heap;let owner=0,staged=new Map(),immediate=false,sounds=[],events=[],freed=false,frames=0,checks=0,textChecks=0,draws=[],calendarAt=0;
 let date=[2024,9,17,12,43];const tm=m.allocate(36);
 
 m.replace(0x4915bf,'replay calendar boundary',()=>{calendarAt=m.u32(m.reg('ESP')+4);m.i32(tm+16,date[1]-1);m.i32(tm+20,date[0]-1900);m.i32(tm+12,date[2]);m.i32(tm+8,date[3]);m.i32(tm+4,date[4]);return tm;});
 m.replace(0x40c570,'ASCII formatted queue boundary',()=>{const sp=m.reg('ESP'),font=m.u32(sp+4),pos=m.u32(sp+8),format=m.string(m.u32(sp+12));let arg=sp+16;
  const rendered=format.replace(/%%|%(?:[0-9]+)?(?:\.[0-9]+)?[sdf]/g,token=>{if(token==='%%')return '%';const kind=token.at(-1),width=Number(token.slice(1).match(/^\d+/)?.[0]||0),precision=token.match(/\.(\d+)/)?.[1];let value;
   if(kind==='s'){value=m.string(m.u32(arg));arg+=4;}
   else if(kind==='f'){value=Buffer.from(m.bytes(arg,8)).readDoubleLE(0);arg+=8;value=Number(value).toFixed(Number(precision||6));}
   else{value=String(m.i32(arg));arg+=4;if(precision)value=value.padStart(Number(precision),'0');}return String(value).padStart(width,' ');
  });draws.push({text:rendered,color:m.u32(font+0x19224),font:m.i32(font+0x1923c),position:[m.f32(pos),m.f32(pos+4),m.f32(pos+8)]});return 0;});
 m.replace(0x476360,'replay menu sound boundary',()=>{sounds.push(m.u32(m.reg('ESP')+4));return 0;},2);
 m.replace(0x403fb0,'replay catalog async boundary',()=>{events.push(1);for(const[slot,p]of staged)m.u32(owner+0x5a08+slot*4,p);if(immediate)m.u32(owner+0x5ba0,(m.u32(owner+0x5ba0)&~4)|8);return 0;},2);
 m.replace(0x45bb60,'catalog object destructor boundary',()=>{if(!freed){events.push(2);freed=true;}return 0;});
 m.replace(0x4229c0,'replay entrance transition object boundary',()=>{events.push(4);const out=m.u32(m.reg('ESP')+4);m.u32(out,0);return out;},1);
 const patchFloat=(at,count,id)=>{const stub=m.registerImport({dll:'fixture',name:'replay transition float boundary',argc:0,handler:()=>{events.push(id);if(count===1)events.push(m.u32(scratch));else events.push(m.u32(scratch+4),m.u32(scratch));return 0;}}),code=count===1?Buffer.from([0xf3,0x0f,0x11,0x0d,0,0,0,0,0xe9,0,0,0,0]):Buffer.from([0xf3,0x0f,0x11,0x0d,0,0,0,0,0xf3,0x0f,0x11,0x15,0,0,0,0,0xe9,0,0,0,0]),cave=m.allocate(code.length);code.writeUInt32LE(scratch,4);if(count===2)code.writeUInt32LE(scratch+4,12);code.writeInt32LE(stub-cave-code.length,code.length-4);m.write(cave,code);const jump=Buffer.alloc(5);jump[0]=0xe9;jump.writeInt32LE(cave-at-5,1);m.write(at,jump);};patchFloat(0x44d530,1,3);patchFloat(0x424670,2,5);const stableBase=m.heap;
 const start=m.cpu.hook_add(m.uc.HOOK_MEM_WRITE,(cpu,type,address,size,value)=>{assert.equal(Number(value),13);events.push(6);},null,0x4e7ecc,0x4e7ecf);m.hooks.push(start);
 const fileFor=(slot,spell)=>{const r=c.recording_create(),h=c.allocate(0x238),name=c.allocate(8),meta=c.recording_metadata(r);try{new DataView(c.memory.buffer).setUint32(meta+0x14,987654,true);new DataView(c.memory.buffer).setUint32(meta+0x9c,2,true);new DataView(c.memory.buffer).setUint32(meta+0x98,8,true);new DataView(c.memory.buffer).setBigInt64(meta+0xc,1700000000n+BigInt(slot),true);new DataView(c.memory.buffer).setUint32(meta+0x8c,slot%4,true);new DataView(c.memory.buffer).setUint32(meta+0x94,slot%5,true);new DataView(c.memory.buffer).setUint32(meta+0xa0,37+slot,true);memory(c,meta+10,1)[0]=spell?2:0;for(const number of slot%2?[2]:[1,3,7]){memory(c,h,0x238).fill(0);new DataView(c.memory.buffer).setUint16(h,number,true);new DataView(c.memory.buffer).setUint32(h+0x30,number*123456,true);new DataView(c.memory.buffer).setUint32(h+0x38,number%3,true);assert.equal(c.recording_begin(r,h,0x238),1);c.recording_activate(r);c.recording_tick(r,0,0,0,60,0);}memory(c,name,8).set(Buffer.from([65,66,67,68,69,70,71,0]));assert.equal(c.recording_write(r,name,1),1);return Buffer.from(memory(c,c.recording_data(r),c.recording_size(r)));}finally{c.recording_delete(r);c.release(h);c.release(name);}};
 try{for(let scenario=0;scenario<18;scenario++){
  m.heap=stableBase;m.view(m.heap,0x1caf980).fill(0);staged=new Map();immediate=scenario%2===0;const a=c.anm_manager_create(),native=nativePool(m),text=m.allocate(0x19270),f=c.title_menu_create(a),menu=c.title_replay_create(f),owned=[],target=scenario%3===0?74:scenario%3===1?24:25;owner=m.allocate(0x5bb0);
  try{m.view(owner,0x5bb0).fill(0);m.u32(0x4e9a40,0);m.u32(0x4e9a44,0);m.u32(0x4e9a58,text);m.u32(0x4ca620,0x4e73e8);m.f32(0x4e73e8,1);m.i32(owner+0x18,12);m.i32(owner+0x1c,1);m.i32(owner+0xf4,1);m.i32(owner+0x24,5);m.i32(owner+0x2c,10);m.call(0x403b10,{ecx:owner+0x24});m.view(0x4e73f0,0x450).fill(0);m.i32(0x4e73f0,1);m.i32(0x4e7424,-1);m.u32(0x4e7794,0x110);c.title_menu_configure(f,5,1,0,0x110);c.title_menu_count(f,10);c.title_menu_push(f);m.i32(0x4e9bf4,target);c.title_replay_configure(menu,target,immediate);const age=c.title_menu_field(f,2),progress=c.title_menu_field(f,0),player=c.title_menu_field(f,1);m.write(owner+0x2b0,Buffer.from(memory(c,age,20)));
   for(const[name,id]of[['ascii.anm',5],['title.anm',16]]){const data=readFileSync(resolve(root,'reference/assets',name)),p=c.allocate(data.length);memory(c,p,data.length).set(data);assert.equal(c.anm_manager_load(a,id,p,data.length),1);c.release(p);const bank=prepareBank(m,loader,name,data,native,id);if(id===5){m.u32(text+0x19258,bank);c.anm_manager_fallback(a,5);}else m.u32(owner+0x10,bank);}
   if(scenario!==17)for(const slot of[0,4,24,25,49,50,74]){const bytes=fileFor(slot,scenario%4===3),p=c.allocate(bytes.length),n=c.allocate(64),file=c.replay_create(),filename=slot<25?'th15_'+String(slot+1).padStart(2,'0')+'.rpy':'th15_ud'+String(slot).padStart(4,'0')+'.rpy';owned.push(p,n);memory(c,p,bytes.length).set(bytes);memory(c,n,filename.length+1).set(Buffer.from(filename+String.fromCharCode(0)));assert.equal(c.title_replay_file(menu,slot,n,p,bytes.length),1);assert.equal(c.replay_open(file,p,bytes.length),1);const object=m.allocate(0x31c),description=m.allocate(0xa4);m.view(object,0x31c).fill(0);m.write(description,Buffer.from(memory(c,c.replay_data(file),0xa4)));m.u32(object+0x18,description);m.write(object+0x21c,Buffer.from(filename+String.fromCharCode(0)));for(let s=1;s<=7;s++){const at=c.replay_stage(file,s);if(!at)continue;const offset=new DataView(c.memory.buffer).getUint32(at+4,true),h=m.allocate(0x238);m.write(h,Buffer.from(memory(c,c.replay_data(file)+offset,0x238)));m.u32(object+0xd4+s*0x28,h);}staged.set(slot,object);c.replay_delete(file);}
   const compareQueue=label=>{for(let alt=0;alt<2;alt++){const list=nativeInstances(m,native,alt);assert.equal(c.anm_manager_count(a,alt),list.length,label+' count');for(let i=0;i<list.length;i++){const h=m.u32(list[i]+0x544);assert.equal(c.anm_manager_order(a,alt,i),h,label+' queue');compareAnm(c,m,c.anm_manager_find(a,h),list[i],label+' script '+(m.u32(list[i]+0x4a8)&65535));checks++;}}};
   const step=(pressed=0,repeated=0)=>{const label=scenario+'/'+frames;m.u32(0x4e6d1c,pressed);m.u32(0x4e6d18,repeated);sounds=[];events=[];freed=false;assert.equal(m.call(0x467fd0,{ecx:owner}),1);assert.equal(c.title_replay_update(menu,pressed,repeated),1,label+' '+string(c,c.title_replay_error(menu)));assert.deepEqual(Array.from(new Int32Array(c.memory.buffer,c.title_menu_sounds(f),c.title_menu_sound_count(f))),sounds,label+' sounds');assert.deepEqual(Array.from(new Int32Array(c.memory.buffer,c.title_replay_events(menu),c.title_replay_event_count(menu))),events,label+' services');const state=Array.from(new Uint32Array(c.memory.buffer,c.title_menu_state(f),254));for(const[i,at]of[[0,owner+0x18],[1,owner+0x1c],[2,owner+0x20],[3,owner+0xf4],[4,owner+0x5ba0]])assert.equal(state[i],m.u32(at),label+' state '+i);for(let i=0;i<248;i++)assert.equal(state[i+6],m.u32(owner+0x2c4+i*4),label+' handle '+i);assert.deepEqual(Buffer.from(memory(c,c.title_menu_cursor(f),0xd8)),Buffer.from(m.bytes(owner+0x24,0xd8)),label+' primary cursor');assert.deepEqual(Buffer.from(memory(c,c.title_replay_pages(menu),0xd8)),Buffer.from(m.bytes(owner+0x1d4,0xd8)),label+' page cursor');assert.deepEqual(Buffer.from(memory(c,age,20)),Buffer.from(m.bytes(owner+0x2b0,20)),label+' timer');for(const[i,at]of[[1,owner+0x5a00],[2,owner+0x5a04],[3,0x4e9bf4]])assert.equal(c.title_replay_value(menu,i),m.i32(at),label+' selection '+i);let count=0;for(let i=0;i<100;i++)count+=m.u32(owner+0x5a08+i*4)!==0;assert.equal(c.title_replay_value(menu,4),count,label+' catalog');for(const[o,at]of[[0,0x4e73f0],[16,0x4e7404],[20,0x4e7408],[24,0x4e7410],[32,0x4e7424]])assert.equal(new DataView(c.memory.buffer).getInt32(progress+o,true),m.i32(at),label+' progress '+o);assert.equal(new DataView(c.memory.buffer).getUint32(player+24,true),m.u32(0x4e7794));if(state[0]===2)assert.equal(string(c,c.title_replay_filename(menu)),m.string(0x4e9aa0));
    draws=[];calendarAt=0;date=[2024+scenario,1+scenario%12,1+scenario%28,scenario%24,(scenario*7)%60];memory(c,c.title_replay_date(menu),20).set(new Uint8Array(new Int32Array(date).buffer));
    assert.equal(m.call(0x468630,{ecx:owner}),1);assert.equal(c.title_replay_draw(menu),1,label+' '+string(c,c.title_replay_error(menu)));assert.equal(c.title_replay_text_count(menu),draws.length,label+' draw count');
    for(let i=0;i<draws.length;i++){const style=c.title_replay_text_style(menu,i);assert.equal(string(c,c.title_replay_text(menu,i)),draws[i].text,label+' caption '+i);assert.equal(new DataView(c.memory.buffer).getUint32(style,true),draws[i].color,label+' caption color');assert.equal(new DataView(c.memory.buffer).getInt32(style+12,true),draws[i].font,label+' font');assert.deepEqual(Array.from(new Float32Array(c.memory.buffer,c.title_replay_text_position(menu,i),3)),draws[i].position,label+' caption position');textChecks++;}
    if(calendarAt)assert.equal(c.title_replay_timestamp(menu),Buffer.from(m.bytes(calendarAt,8)).readBigInt64LE(0),label+' timestamp');if(draws.length){assert.equal(m.u32(text+0x19224),0xffffffff);assert.equal(m.u32(text+0x19238),0);}
    compareQueue(label+' pre-update');m.i32(owner+0x2b0,m.i32(owner+0x2b4));m.i32(owner+0x2b4,m.i32(owner+0x2b4)+1);m.f32(owner+0x2b8,Math.fround(m.f32(owner+0x2b8)+1));c.title_menu_tick(f,1);for(let alt=0;alt<2;alt++){assert.equal(c.anm_manager_update(a,alt,1),1,string(c,c.anm_manager_error(a)));m.call(alt?0x487890:0x487740,{ecx:native});}compareQueue(label+' post-update');frames++;return state[0];};
   const ready=()=>{m.u32(owner+0x5ba0,(m.u32(owner+0x5ba0)&~4)|8);c.title_replay_ready(menu);};for(let i=0;i<12;i++)step();step(0xa0);step(0x50);step(16,128);step(32,64);
   if(scenario===17||scenario%6===0){step(0x102);for(let i=0;i<9;i++)step();if(!immediate)ready();for(let i=0;i<8;i++)if(step()!==12)break;}
   else{let guard=0;while(c.title_replay_value(menu,0)!==Math.floor(target/25)){assert.ok(guard++<10);step(128);}guard=0;while(new DataView(c.memory.buffer).getInt32(c.title_menu_cursor(f),true)!==target%25){assert.ok(guard++<30);step(32);}step(0x80001);if(m.i32(owner+0x20)===4){for(let i=0;i<16;i++)step(1);step(16);step(32);if(scenario%5===0){step(0x102);step(0x80001);for(let i=0;i<16;i++)step();}step(16);step(0x80001);}for(let i=0;i<38;i++)if(step()!==12)break;if(m.i32(owner+0x18)===12){ready();for(let i=0;i<8;i++)if(step()!==12)break;}assert.equal(m.i32(owner+0x18),2);}
  }finally{for(const p of owned)c.release(p);c.title_replay_delete(menu);c.title_menu_delete(f);c.anm_manager_delete(a);}
 }
 report('title-replay',{passed:true,scenarios:18,frames,animationChecks:checks,textChecks,originalFunctions:['0x467fd0','0x468630'],scope:'Actual title/ASCII animation queues, 25 rows/three pages, menu histories/disabled stages, loading-completion flags, delayed cancel, startup wait/fade/transition layout, normal and spell-practice metadata and selected filename. Exact list/stage text, color, font, date inputs, user filename tags, score source and animation timing. Catalog file I/O/worker, calendar/CRT formatting, text queue and transition GPU object are isolated boundaries; complete app destinations are separate.'});
 }finally{m.close();}
});
