import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {resolve} from 'node:path';import {core,oracle,memory,string,root,report,enableNativeMath} from './helpers.mjs';import {resourceLoader,nativePool,prepareBank,nativeInstances,compareAnm} from './anm-oracle.mjs';
const load=(c,a,name,id)=>{const data=readFileSync(resolve(root,'reference/assets',name)),p=c.allocate(data.length);memory(c,p,data.length).set(data);assert.equal(c.anm_manager_load(a,id,p,data.length),1,name+': '+string(c,c.anm_manager_error(a)));c.release(p);return data;};
test('TH15 actual title main-menu trees, disabled Extra, cursor navigation and outgoing selection match original frames',async()=>{
 const c=await core(),m=await oracle();enableNativeMath(m);const loader=resourceLoader(m),base=m.heap;let frames=0,checks=0,sounds=[],extra=true;
 m.replace(0x460160,'persisted Extra-unlock boundary',()=>extra?1:0);m.replace(0x476360,'menu sound output boundary',()=>{sounds.push(m.u32(m.reg('ESP')+4));return 0;},2);
 try{for(let scenario=0;scenario<18;scenario++){
  m.heap=base;m.view(m.heap,0x1caf980).fill(0);const a=c.anm_manager_create(),native=nativePool(m),owner=m.allocate(0x5bb0),text=m.allocate(0x19270),f=c.title_menu_create(a);try{
   m.u32(0x4e9a40,0);m.u32(0x4e9a44,0);m.view(owner,0x5bb0).fill(0);m.u32(0x4e9a58,text);m.u32(0x4ca620,0x4e73e8);m.f32(0x4e73e8,1);m.view(0x4e73f0,0x450).fill(0);m.i32(owner+0x18,1);m.i32(owner+0x1c,scenario%2?3:0);m.i32(owner+0xf4,1);const initialFlags=scenario<9?2:0,initialCursor=scenario%9,mode=scenario%3===0?0x310:0x100;extra=initialCursor!==1?scenario%4!==0:true;m.i32(owner+0x24,initialCursor);m.u32(owner+0x5ba0,initialFlags);m.u32(0x4e7794,mode);m.i32(0x4e7410,2);m.i32(0x4e7424,123);m.i32(0x4e9bec,scenario%2);m.i32(0x4e0ef4,scenario%4);c.title_menu_configure(f,initialCursor,scenario%2?3:0,initialFlags,mode);
   const pp=c.title_menu_field(f,0),lp=c.title_menu_field(f,1),age=c.title_menu_field(f,2),settings=c.title_menu_field(f,3);let dv=new DataView(c.memory.buffer);dv.setInt32(pp+24,2,true);dv.setInt32(pp+32,123,true);dv.setInt32(settings,scenario%2,true);dv.setInt32(settings+4,scenario%4,true);m.write(owner+0x2b0,Buffer.from(memory(c,age,20)));
   for(const[name,id]of[['ascii.anm',5],['title.anm',16],['title_v.anm',17]]){const data=load(c,a,name,id),bank=prepareBank(m,loader,name,data,native,id);if(id===5){m.u32(text+0x19258,bank);assert.equal(c.anm_manager_fallback(a,5),1);}else m.u32(owner+(id===16?0x10:0x14),bank);}
   const compareQueue=label=>{for(let alt=0;alt<2;alt++){const list=nativeInstances(m,native,alt);assert.equal(c.anm_manager_count(a,alt),list.length,label+' count');for(let i=0;i<list.length;i++){const h=m.u32(list[i]+0x544);assert.equal(c.anm_manager_order(a,alt,i),h,label+' queue');const vm=c.anm_manager_find(a,h);compareAnm(c,m,vm,list[i],label+' VM '+h+' script '+(m.u32(list[i]+0x4a8)&65535));assert.deepEqual(Buffer.from(memory(c,c.anm_vm_translation(vm),12)),Buffer.from(m.bytes(list[i]+0x5ec,12)));checks++;}}};
   const step=(pressed=0,repeated=0)=>{const label=scenario+'/'+frames;m.u32(0x4e6d1c,pressed);m.u32(0x4e6d18,repeated);sounds=[];assert.equal(m.call(0x461050,{ecx:owner}),1);assert.equal(c.title_menu_update(f,pressed,repeated,extra),1,string(c,c.title_menu_error(f)));assert.deepEqual(Array.from(new Int32Array(c.memory.buffer,c.title_menu_sounds(f),c.title_menu_sound_count(f))),sounds,label+' sounds');const st=Array.from(new Uint32Array(c.memory.buffer,c.title_menu_state(f),254));for(const[index,address]of[[0,owner+0x18],[1,owner+0x1c],[2,owner+0x20],[3,owner+0xf4],[4,owner+0x5ba0],[5,owner+0x6a4]])assert.equal(st[index],m.u32(address),label+' state '+index);assert.deepEqual(Buffer.from(memory(c,c.title_menu_cursor(f),0xd8)),Buffer.from(m.bytes(owner+0x24,0xd8)),label+' menu');for(let i=0;i<248;i++)assert.equal(st[6+i],m.u32(owner+0x2c4+i*4),label+' handle '+i);assert.deepEqual(Buffer.from(memory(c,age,20)),Buffer.from(m.bytes(owner+0x2b0,20)),label+' timer');dv=new DataView(c.memory.buffer);assert.equal(dv.getUint32(lp+24,true),m.u32(0x4e7794),label+' mode flags');assert.equal(dv.getInt32(pp+24,true),m.i32(0x4e7410),label+' difficulty');assert.equal(dv.getInt32(pp+32,true),m.i32(0x4e7424),label+' spell');assert.equal(dv.getInt32(settings+8,true),m.i32(owner+0x5910),label+' saved difficulty');compareQueue(label+' before queue update');m.u32(owner+0x2bc,0);m.i32(owner+0x2b0,m.i32(owner+0x2b4));m.i32(owner+0x2b4,m.i32(owner+0x2b4)+1);m.f32(owner+0x2b8,Math.fround(m.f32(owner+0x2b8)+1));c.title_menu_tick(f,1);for(let alt=0;alt<2;alt++){assert.equal(c.anm_manager_update(a,alt,1),1,string(c,c.anm_manager_error(a)));m.call(alt?0x487890:0x487740,{ecx:native});}compareQueue(label+' after queue update');assert.deepEqual(Buffer.from(memory(c,c.anm_manager_random(a),8)),Buffer.from(m.bytes(0x4e9a40,8)),label+' visual RNG');frames++;return st[0];};
   for(let i=0;i<(initialFlags?133:13);i++)assert.equal(step(),1);
   // Navigate with both pressed and repeated directions, then choose every entry.
   for(let i=0;i<6;i++){assert.equal(step(i%2?32:16,i%3?0:32),1);}
   let current=new DataView(c.memory.buffer).getInt32(c.title_menu_cursor(f),true),desired=scenario%9;while(current!==desired){assert.equal(step(32),1);current=new DataView(c.memory.buffer).getInt32(c.title_menu_cursor(f),true);if(!extra&&desired===1)desired=2;}
   if(desired===8&&scenario%2){assert.equal(step(0x102),1);}else assert.equal(step(0x80001),1);
   for(let i=0;i<22;i++){if(step()!==1)break;}
  }finally{c.title_menu_delete(f);c.anm_manager_delete(a);}
 }
 report('title-main-menu',{passed:true,scenarios:18,frames,animationChecks:checks,originalFunctions:['0x461050','0x45fcc0','0x45fd40','0x45fdb0','0x45ffa0','0x45ff20','0x487740','0x487890'],scope:'Actual title/title_v/ascii scripts and original animation trees are compared before and after every frame: introduction, immediate return, disabled Extra appearance, navigation/repeat, all nine exit branches, sound requests, mode/difficulty selection and timer/history. Persisted unlock predicate and audio device are isolated boundaries. Other title screens and GPU/browser remain separate.'});
 }finally{m.close();}
});
