import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {resolve} from 'node:path';import {core,oracle,memory,string,root,report,enableNativeMath} from './helpers.mjs';import {resourceLoader,nativePool,prepareBank,nativeInstances,compareAnm} from './anm-oracle.mjs';
test('TH15 title manual opens the original prompt/header and returns only after the manual close delay',async()=>{
 const c=await core(),m=await oracle();enableNativeMath(m);const loader=resourceLoader(m),base=m.heap;let frames=0,checks=0,manual=0,destructions=0;
 m.replace(0x43eb40,'manual scheduler registration boundary',()=>{manual=m.reg('ECX');m.u32(0x4e9a98,manual);return 0;});m.replace(0x43ec40,'manual scheduler teardown boundary',()=>{assert.equal(m.reg('ECX'),manual);destructions++;m.u32(0x4e9a98,0);return 0;});
 try{for(let scenario=0;scenario<4;scenario++){
  m.heap=base;m.view(m.heap,0x1caf980).fill(0);const a=c.anm_manager_create(),native=nativePool(m),owner=m.allocate(0x5bb0),text=m.allocate(0x19270),f=c.title_menu_create(a),panel=c.manual_create(a),wrapper=c.title_manual_create(f,panel);try{
   m.view(owner,0x5bb0).fill(0);m.u32(0x4e9a40,0);m.u32(0x4e9a44,0);m.u32(0x4e9a58,text);m.u32(0x4ca620,0x4e73e8);m.f32(0x4e73e8,1);m.i32(owner+0x18,17);m.i32(owner+0x1c,1);m.i32(owner+0xf4,1);m.i32(owner+0x24,8);m.i32(owner+0x2c,10);m.call(0x403b10,{ecx:owner+0x24});c.title_menu_configure(f,8,1,0,0);c.title_menu_count(f,10);c.title_menu_push(f);const age=c.title_menu_field(f,2);m.write(owner+0x2b0,Buffer.from(memory(c,age,20)));
   for(const[name,id]of[['ascii.anm',5],['title.anm',16]]){const data=readFileSync(resolve(root,'reference/assets',name)),p=c.allocate(data.length);memory(c,p,data.length).set(data);assert.equal(c.anm_manager_load(a,id,p,data.length),1);c.release(p);const bank=prepareBank(m,loader,name,data,native,id);if(id===5){m.u32(text+0x19258,bank);c.anm_manager_fallback(a,5);}else m.u32(owner+0x10,bank);}
   const step=()=>{const label=scenario+'/'+frames;assert.equal(m.call(0x46b190,{ecx:owner}),0);assert.equal(c.title_manual_update(wrapper),1,string(c,c.title_manual_error(wrapper)));const st=Array.from(new Uint32Array(c.memory.buffer,c.title_menu_state(f),254));for(const[i,addr]of[[0,owner+0x18],[1,owner+0x1c],[2,owner+0x20]])assert.equal(st[i],m.u32(addr),label+' state');for(let i=0;i<248;i++)assert.equal(st[6+i],m.u32(owner+0x2c4+i*4),label+' handle');assert.deepEqual(Buffer.from(memory(c,c.title_menu_cursor(f),0xd8)),Buffer.from(m.bytes(owner+0x24,0xd8)),label+' cursor');assert.deepEqual(Buffer.from(memory(c,age,20)),Buffer.from(m.bytes(owner+0x2b0,20)),label+' timer');
    for(let alt=0;alt<2;alt++){const list=nativeInstances(m,native,alt);assert.equal(c.anm_manager_count(a,alt),list.length);for(let i=0;i<list.length;i++){const h=m.u32(list[i]+0x544);assert.equal(c.anm_manager_order(a,alt,i),h);compareAnm(c,m,c.anm_manager_find(a,h),list[i],label);checks++;}assert.equal(c.anm_manager_update(a,alt,1),1);m.call(alt?0x487890:0x487740,{ecx:native});}m.i32(owner+0x2b0,m.i32(owner+0x2b4));m.i32(owner+0x2b4,m.i32(owner+0x2b4)+1);m.f32(owner+0x2b8,Math.fround(m.f32(owner+0x2b8)+1));c.title_menu_tick(f,1);frames++;};
   step();assert.equal(m.f32(manual+0x128),128);for(let i=0;i<30+scenario*7;i++)step();m.u32(manual+0x124,1);c.manual_finished(panel,1);step();assert.equal(destructions,scenario+1);
  }finally{c.title_manual_delete(wrapper);c.manual_delete(panel);c.title_menu_delete(f);c.anm_manager_delete(a);}
 }
 report('title-manual',{passed:true,scenarios:4,frames,animationChecks:checks,originalFunctions:['0x46b190'],scope:'Actual title/ASCII prompt and header animation queues, waiting for Manual completion, close labels, title screen transition and preserved menu stack. Manual body is verified separately; scheduler registration is isolated.'});
 }finally{m.close();}
});
