import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {resolve} from 'node:path';import {core,memory,string,root,report} from './helpers.mjs';
test('TH15 title scene composes actual menus on the shared callback scheduler',async()=>{
 const c=await core();let totalFrames=0,routes=[];
 const create=()=>{const a=c.anm_manager_create();for(const [name,id] of [['text.anm',0],['ascii.anm',5],['title.anm',16],['title_v.anm',17],['help.anm',19]]){const bytes=readFileSync(resolve(root,'reference/assets',name)),p=c.allocate(bytes.length);memory(c,p,bytes.length).set(bytes);assert.equal(c.anm_manager_load(a,id,p,bytes.length),1);c.release(p);}assert.equal(c.anm_manager_fallback(a,5),1);const comment=readFileSync(resolve(root,'reference/assets/musiccmt.txt')),p=c.allocate(comment.length);memory(c,p,comment.length).set(comment);const f=c.title_scene_create(a,p,comment.length);c.release(p);assert.equal(string(c,c.title_scene_error(f)),'');return {a,f};};
 const fields=f=>Array.from(new Int32Array(c.memory.buffer,c.title_scene_fields(f),14));
 const step=(v,pressed=0,repeated=0)=>{assert.equal(c.title_scene_step(v.f,pressed|repeated,pressed,repeated),1,string(c,c.title_scene_error(v.f)));for(let alt=0;alt<2;alt++)assert.equal(c.anm_manager_update(v.a,alt,1),1,string(c,c.anm_manager_error(v.a)));totalFrames++;return fields(v.f);};
 const wait=(v,predicate,limit=250)=>{for(let i=0;i<limit;i++){const s=step(v);if(predicate(s))return s;}assert.fail('title scene did not reach expected state: '+fields(v.f));};
 const ready=(v,screen)=>wait(v,s=>s[0]===screen&&s[1]===2);
 const choose=(v,index,screen)=>{c.title_scene_select(v.f,index);step(v,1);return ready(v,screen);};
 const dispose=v=>{c.title_scene_delete(v.f);c.anm_manager_delete(v.a);};
 for(let character=0;character<4;character++)for(let mode=0;mode<2;mode++){
 const v=create();try{ready(v,1);choose(v,0,5);choose(v,mode,6);choose(v,character%4,7);c.title_scene_select(v.f,character);step(v,1);const s=wait(v,s=>s[10]===13);assert.equal(s[6],character);assert.equal(s[7],character%4);assert.equal(s[8],1);assert.equal(s[9]&0x300,mode?0:0x100);routes.push({kind:'new-game',character,mode,stage:s[8]});}finally{dispose(v);}}
 for(const [index,screen] of [[3,12],[4,11],[5,14],[6,3],[7,17]]){
 const v=create();try{ready(v,1);c.title_scene_select(v.f,index);step(v,1);if(screen===17){wait(v,s=>s[0]===17);for(let i=0;i<25;i++)step(v);step(v,0x102);ready(v,1);c.title_scene_select(v.f,7);step(v,1);wait(v,s=>s[0]===17);for(let i=0;i<25;i++)step(v);step(v,1);for(let i=0;i<25;i++)step(v);step(v,0x102);for(let i=0;i<25;i++)step(v);step(v,0x102);ready(v,1);}else{ready(v,screen);step(v,0x102);if(screen===3)step(v,0x102);ready(v,1);}assert.equal(fields(v.f)[5],screen===17?2:0);routes.push({kind:'submenu-return',screen});}finally{dispose(v);}}
 const extra=create();try{assert.equal(c.title_scene_unlock(extra.f),1);ready(extra,1);choose(extra,1,6);choose(extra,0,7);c.title_scene_select(extra.f,3);step(extra,1);const s=wait(extra,s=>s[10]===13);assert.equal(s[8],7);assert.equal(s[7],4);routes.push({kind:'extra',stage:s[8]});}finally{dispose(extra);}
 const practice=create();try{assert.equal(c.title_scene_unlock(practice.f),1);ready(practice,1);choose(practice,2,6);choose(practice,1,7);c.title_scene_select(practice.f,2);step(practice,1);ready(practice,9);for(let i=0;i<11;i++)step(practice);assert.ok(c.title_scene_caption_count(practice.f)>=6);step(practice,0x102);ready(practice,7);step(practice,0x102);ready(practice,6);step(practice,0x102);ready(practice,1);routes.push({kind:'practice-return'});}finally{dispose(practice);}
 const quit=create();try{ready(quit,1);c.title_scene_select(quit.f,8);step(quit,1);const s=wait(quit,s=>s[10]>=0);assert.equal(s[10],3);routes.push({kind:'quit',destination:s[10]});}finally{dispose(quit);}
 report('title-scene',{routes,totalFrames,scope:'Actual ANM resources and named title menus on shared update/draw scheduler; platform audio, files, page uploads and scene destinations are recorded boundaries. Component native proofs cover menu behavior; this is composition coverage, not independent full-game replay proof.'});
});
