import test from'node:test';import assert from'node:assert/strict';import{core,oracle,memory,string,report}from'./helpers.mjs';
test('TH15 practice score captions and selected-row flash match the original text requests',async()=>{
 const c=await core(),m=await oracle(),a=c.anm_manager_create(),t=c.title_menu_create(a),f=c.title_frame_create(t),d=c.title_practice_draw_create(f),owner=m.allocate(0x5bb0),text=m.allocate(0x19270),records=m.allocate(0x33800);let draws=[],cases=0,checks=0;
 m.view(owner,0x5bb0).fill(0);m.view(text,0x19270).fill(0);m.view(records,0x33800).fill(0);m.u32(0x4e9a58,text);m.u32(0x4e9bc8,records);
 m.replace(0x40c570,'original ASCII formatting/draw boundary',()=>{const sp=m.reg('ESP'),at=m.u32(sp+8),format=m.string(m.u32(sp+12)),title=m.string(m.u32(sp+16));let line=title+'  ---------';if(format==='%s  %.8d0'){const score=m.i32(sp+20),digits=String(Math.abs(score)).padStart(8,'0');line=title+'  '+(score<0?'-':'')+digits+'0';}else assert.equal(format,'%s  ---------');draws.push({text:line,color:m.u32(text+0x19224),font:m.i32(text+0x1923c),position:[m.f32(at),m.f32(at+4),m.f32(at+8)]});return 0;});
 try{for(let character=0;character<4;character++)for(let rank=0;rank<5;rank++)for(const phase of[0,1,2,3,4])for(const age of[-3,0,1,2,3,6,9,10,11,12,13])for(let cursor=0;cursor<6;cursor++){
  const label=[character,rank,phase,age,cursor].join('/');m.i32(owner+0x20,phase);m.i32(owner+0x2b4,age);m.i32(owner+0x24,cursor);m.i32(0x4e7404,character);m.i32(0x4e7408,0);m.i32(0x4e7410,rank);c.title_practice_draw_configure(d,phase,age,cursor,character,rank);
  for(let row=1;row<=6;row++){const score=[0,17,-17,12345678,2147483647,-2147483648][row-1],visited=(row+cases)%3?1:0,at=records+0xa320+character*0xa4a0+(rank*8+row)*8;m.i32(at,score);m.view(at+5,1)[0]=visited;c.title_practice_draw_record(d,character,rank,row,score,visited);}
  draws=[];assert.equal(m.call(0x467c20,{ecx:owner}),1);assert.equal(c.title_practice_draw_run(d),1,string(c,c.title_practice_draw_error(d)));assert.equal(c.title_practice_draw_count(d),draws.length,label+' count');for(let i=0;i<draws.length;i++){const style=c.title_practice_draw_style(d,i),view=new DataView(c.memory.buffer);assert.equal(string(c,c.title_practice_draw_text(d,i)),draws[i].text,label+' line');assert.equal(view.getUint32(style,true),draws[i].color,label+' color');assert.equal(view.getInt32(style+12,true),draws[i].font,label+' font');assert.deepEqual(Array.from(new Float32Array(c.memory.buffer,c.title_practice_draw_position(d,i),3)),draws[i].position,label+' position');checks+=4;}cases++;
 }
 report('title-practice-draw',{passed:true,cases,checks,originalFunctions:['0x467c20'],scope:'Six actual practice records, original visited flag, signed eight-digit scores, locked placeholders, all four characters/five difficulties, six selections, entry/confirmation/exit phases and blinking timer including negative frames; compare every text, position, color and font against original requests.'});
 }finally{c.title_practice_draw_delete(d);c.title_frame_delete(f);c.title_menu_delete(t);c.anm_manager_delete(a);m.close();}
});
