import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {resolve} from 'node:path';import {core,oracle,memory,string,root,report,enableNativeMath} from './helpers.mjs';import {resourceLoader,nativePool,prepareBank,nativeInstances,compareAnm} from './anm-oracle.mjs';
const load=(c,a,name,id)=>{const data=readFileSync(resolve(root,'reference/assets',name)),p=c.allocate(data.length);memory(c,p,data.length).set(data);assert.equal(c.anm_manager_load(a,id,p,data.length),1,name+': '+string(c,c.anm_manager_error(a)));c.release(p);return data;};
test('TH15 actual mode and difficulty menu frames preserve original selection, markers, practice, Extra and cancellation',async()=>{
 const c=await core(),m=await oracle();enableNativeMath(m);const loader=resourceLoader(m),base=m.heap;let frames=0,checks=0,sounds=[];
 m.replace(0x460160,'persisted Extra unlock boundary',()=>1);m.replace(0x476360,'menu sound output boundary',()=>{sounds.push(m.u32(m.reg('ESP')+4));return 0;},2);
 try{for(let scenario=0;scenario<48;scenario++){
  m.heap=base;m.view(m.heap,0x1caf980).fill(0);const a=c.anm_manager_create(),native=nativePool(m),owner=m.allocate(0x5bb0),text=m.allocate(0x19270),scores=m.allocate(0x34000),f=c.title_menu_create(a),type=scenario%3,initialCursor=[0,2,1][type],clearMask=scenario%32,reason=scenario>=36?4:1;
  try{
   m.u32(0x4e9a40,0);m.u32(0x4e9a44,0);m.view(owner,0x5bb0).fill(0);m.view(scores,0x34000).fill(0);m.u32(0x4e9a58,text);m.u32(0x4e9bc8,scores);m.u32(0x4ca620,0x4e73e8);m.f32(0x4e73e8,1);m.view(0x4e73f0,0x450).fill(0);m.i32(owner+0x18,1);m.i32(owner+0xf4,1);m.i32(owner+0x24,initialCursor);m.u32(0x4e7794,0x100);m.i32(0x4e7410,2);m.i32(0x4e7424,123);m.i32(0x4e9bec,scenario%2);m.i32(0x4e0ef4,scenario%4);m.i32(0x4e9be8,scenario%4);m.i32(0x4e9bdc,reason);c.title_menu_configure(f,initialCursor,0,0,0x100);c.title_selection_return_reason(f,reason);
   const pp=c.title_menu_field(f,0),lp=c.title_menu_field(f,1),age=c.title_menu_field(f,2),settings=c.title_menu_field(f,3);let dv=new DataView(c.memory.buffer);dv.setInt32(pp+24,2,true);dv.setInt32(pp+32,123,true);dv.setInt32(settings,scenario%2,true);dv.setInt32(settings+4,scenario%4,true);dv.setInt32(settings+12,scenario%4,true);m.write(owner+0x2b0,Buffer.from(memory(c,age,20)));
   for(let character=0;character<4;character++)for(let variant=0;variant<2;variant++)for(let difficulty=0;difficulty<5;difficulty++)if(clearMask>>difficulty&1)m.i32(scores+0x5184+character*0xa4a0+variant*0x5188+difficulty*4,1);
   for(const[name,id]of[['ascii.anm',5],['title.anm',16],['title_v.anm',17]]){const data=load(c,a,name,id),bank=prepareBank(m,loader,name,data,native,id);if(id===5){m.u32(text+0x19258,bank);assert.equal(c.anm_manager_fallback(a,5),1);}else m.u32(owner+(id===16?0x10:0x14),bank);}
   const compareQueue=label=>{for(let alt=0;alt<2;alt++){const list=nativeInstances(m,native,alt);assert.equal(c.anm_manager_count(a,alt),list.length,label+' count');for(let i=0;i<list.length;i++){const h=m.u32(list[i]+0x544);assert.equal(c.anm_manager_order(a,alt,i),h,label+' queue');const vm=c.anm_manager_find(a,h);compareAnm(c,m,vm,list[i],label+' VM '+h+' script '+(m.u32(list[i]+0x4a8)&65535));assert.deepEqual(Buffer.from(memory(c,c.anm_vm_translation(vm),12)),Buffer.from(m.bytes(list[i]+0x5ec,12)));checks++;}}};
   const step=(pressed=0,repeated=0)=>{const label=scenario+'/'+frames;m.u32(0x4e6d1c,pressed);m.u32(0x4e6d18,repeated);sounds=[];const screen=m.i32(owner+0x18),address=screen===1?0x461050:screen===5?0x4660e0:screen===6?0x4664c0:0;assert.ok(address,'screen '+screen);assert.equal(m.call(address,{ecx:owner}),1);assert.equal(c.title_selection_update(f,pressed,repeated,1,clearMask),1,string(c,c.title_selection_error(f)));assert.deepEqual(Array.from(new Int32Array(c.memory.buffer,c.title_menu_sounds(f),c.title_menu_sound_count(f))),sounds,label+' sounds');const st=Array.from(new Uint32Array(c.memory.buffer,c.title_menu_state(f),254));for(const[index,address]of[[0,owner+0x18],[1,owner+0x1c],[2,owner+0x20],[3,owner+0xf4],[4,owner+0x5ba0],[5,owner+0x6a4]])assert.equal(st[index],m.u32(address),label+' state '+index);assert.deepEqual(Buffer.from(memory(c,c.title_menu_cursor(f),0xd8)),Buffer.from(m.bytes(owner+0x24,0xd8)),label+' menu');for(let i=0;i<248;i++)assert.equal(st[6+i],m.u32(owner+0x2c4+i*4),label+' handle '+i);assert.deepEqual(Buffer.from(memory(c,age,20)),Buffer.from(m.bytes(owner+0x2b0,20)),label+' timer');dv=new DataView(c.memory.buffer);assert.equal(dv.getUint32(lp+24,true),m.u32(0x4e7794),label+' mode flags');assert.equal(dv.getInt32(pp+24,true),m.i32(0x4e7410),label+' difficulty');assert.equal(dv.getInt32(pp+32,true),m.i32(0x4e7424),label+' spell');assert.equal(dv.getInt32(settings+8,true),m.i32(owner+0x5910),label+' saved difficulty');assert.equal(dv.getInt32(settings,true),m.i32(0x4e9bec),label+' preferred mode');assert.equal(dv.getInt32(settings+4,true),m.i32(0x4e0ef4),label+' configured difficulty');assert.equal(dv.getInt32(pp+16,true),m.i32(0x4e7404),label+' character');compareQueue(label+' before queue update');m.u32(owner+0x2bc,0);m.i32(owner+0x2b0,m.i32(owner+0x2b4));m.i32(owner+0x2b4,m.i32(owner+0x2b4)+1);m.f32(owner+0x2b8,Math.fround(m.f32(owner+0x2b8)+1));c.title_menu_tick(f,1);for(let alt=0;alt<2;alt++){assert.equal(c.anm_manager_update(a,alt,1),1,string(c,c.anm_manager_error(a)));m.call(alt?0x487890:0x487740,{ecx:native});}compareQueue(label+' after queue update');assert.deepEqual(Buffer.from(memory(c,c.anm_manager_random(a),8)),Buffer.from(m.bytes(0x4e9a40,8)),label+' visual RNG');frames++;return st[0];};

   const state=()=>Array.from(new Uint32Array(c.memory.buffer,c.title_menu_state(f),6)),ready=()=>{for(let i=0;state()[2]!==2&&i<150;i++)step();assert.equal(state()[2],2);},transition=()=>{const before=state()[0];for(let i=0;state()[0]===before&&i<30;i++)step();assert.notEqual(state()[0],before);};
   ready();step(1);transition();
   if(type===0){assert.equal(state()[0],5);ready();step(scenario%2?0x80:0x40);if(scenario<36&&(scenario>>2&1)){step(0x102);transition();assert.equal(state()[0],1);continue;}step(0x80000);transition();assert.equal(state()[0],6);}
   else assert.equal(state()[0],6);
   if(reason===4){step();assert.equal(state()[0],7);continue;}
   ready();step(scenario%2?0x20:0x40,scenario%3?0:0x80);
   if(scenario>>3&1){step(0x102);transition();assert.equal(state()[0],type===0?5:1);}
   else{step(1);transition();assert.equal(state()[0],7);}
  }finally{c.title_menu_delete(f);c.anm_manager_delete(a);}
 }
 report('title-selection-menu',{passed:true,scenarios:48,frames,animationChecks:checks,originalFunctions:['0x461050','0x4660e0','0x4664c0','0x45fcc0','0x45fd40','0x45fe70','0x460030','0x488be0','0x487740','0x487890'],scope:'Real title/title_v/ascii trees and unmodified original controllers are compared before/after every frame for Normal/Pointdevice mode, all difficulty choices, full-character completion markers, Practice, Extra, selection recovery, both cancellation routes, sound requests and persistent selections. Character/stage menus, actual save storage, GPU and browser remain separate.'});
 }finally{m.close();}
});
