import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {resolve} from 'node:path';import {core,oracle,memory,string,root,report,enableNativeMath} from './helpers.mjs';import {resourceLoader,nativePool,prepareBank,nativeInstances,compareAnm} from './anm-oracle.mjs';
const load=(c,a,name,id)=>{const data=readFileSync(resolve(root,'reference/assets',name)),p=c.allocate(data.length);memory(c,p,data.length).set(data);assert.equal(c.anm_manager_load(a,id,p,data.length),1,name+': '+string(c,c.anm_manager_error(a)));c.release(p);return data;};
test('TH15 four real character menu trees preserve Extra restrictions, completion emblems, chapter resume, practice and game-start branches',async()=>{
 const c=await core(),m=await oracle();enableNativeMath(m);const loader=resourceLoader(m),base=m.heap;let frames=0,checks=0,sounds=[],events=[],resumeMask=0;
 m.replace(0x476360,'menu sound output boundary',()=>{sounds.push(m.u32(m.reg('ESP')+4));return 0;},2);
 m.replace(0x43e180,'chapter checkpoint storage boundary',()=>{const sp=m.reg('ESP'),character=m.i32(sp+4),difficulty=m.i32(sp+8);events.push(1,character,difficulty);return resumeMask>>character&1;},2);
 m.replace(0x44d530,'game-start music device boundary',()=>{events.push(3);return 0;});m.replace(0x424670,'game-start overlay device boundary',()=>{events.push(4);return 0;});m.replace(0x4229c0,'game-start transition object boundary',()=>{const out=m.u32(m.reg('ESP')+4);m.u32(out,0);return out;},1);
 const resetHook=m.cpu.hook_add(m.uc.HOOK_MEM_WRITE,(cpu,type,address,size,value)=>events.push(2),null,0x4e9be4,0x4e9be4);m.hooks.push(resetHook);const startHook=m.cpu.hook_add(m.uc.HOOK_MEM_WRITE,(cpu,type,address,size,value)=>events.push(5,m.i32(0x4e73f4)),null,0x4e7ecc,0x4e7ecf);m.hooks.push(startHook);
 try{for(let scenario=0;scenario<64;scenario++){
  m.heap=base;m.view(m.heap,0x1caf980).fill(0);const a=c.anm_manager_create(),native=nativePool(m),owner=m.allocate(0x5bb0),text=m.allocate(0x19270),scores=m.allocate(0x34000),f=c.title_menu_create(a),cf=c.title_character_create(f),type=scenario%3,initialCursor=[0,2,1][type],reason=scenario>=48?4:1,allowed=scenario%15+1;resumeMask=scenario%16;c.title_character_configure(cf,resumeMask);
  try{
   m.u32(0x4e9a40,0);m.u32(0x4e9a44,0);m.view(owner,0x5bb0).fill(0);m.view(scores,0x34000).fill(0);m.u32(0x4e9a58,text);m.u32(0x4e9bc8,scores);m.u32(0x4ca620,0x4e73e8);m.f32(0x4e73e8,1);m.view(0x4e73f0,0x450).fill(0);m.i32(0x4e73f4,1);m.i32(owner+0x18,1);m.i32(owner+0xf4,1);m.i32(owner+0x24,initialCursor);m.u32(0x4e7794,0x100);m.i32(0x4e7410,2);m.i32(0x4e7424,123);m.i32(0x4e9bec,scenario%2);m.i32(0x4e0ef4,scenario%4);m.i32(0x4e9be8,scenario%4);m.i32(0x4e9bdc,reason);c.title_menu_configure(f,initialCursor,0,0,0x100);c.title_selection_return_reason(f,reason);
   const pp=c.title_menu_field(f,0),lp=c.title_menu_field(f,1),age=c.title_menu_field(f,2),settings=c.title_menu_field(f,3),records=c.title_character_records(cf);let dv=new DataView(c.memory.buffer);dv.setInt32(pp+24,2,true);dv.setInt32(pp+32,123,true);dv.setInt32(settings,scenario%2,true);dv.setInt32(settings+4,scenario%4,true);dv.setInt32(settings+12,scenario%4,true);m.write(owner+0x2b0,Buffer.from(memory(c,age,20)));
   for(let character=0;character<4;character++)for(let variant=0;variant<2;variant++)for(let difficulty=0;difficulty<5;difficulty++){const value=(allowed>>character&1)&&((scenario+character+variant)%4===difficulty||difficulty===4&&scenario%2)?scenario%5?1:-1:0;m.i32(scores+0x5184+character*0xa4a0+variant*0x5188+difficulty*4,value);dv.setInt32(records+((character*2+variant)*5+difficulty)*4,value,true);}assert.equal(c.title_character_extra(cf,-1),m.call(0x460160));for(let character=0;character<4;character++)assert.equal(c.title_character_extra(cf,character),m.call(0x460110,{ecx:scores,args:[character,0]})||m.call(0x460110,{ecx:scores,args:[character,1]}));
   for(const[name,id]of[['ascii.anm',5],['title.anm',16],['title_v.anm',17]]){const data=load(c,a,name,id),bank=prepareBank(m,loader,name,data,native,id);if(id===5){m.u32(text+0x19258,bank);assert.equal(c.anm_manager_fallback(a,5),1);}else m.u32(owner+(id===16?0x10:0x14),bank);}
   const compareQueue=label=>{for(let alt=0;alt<2;alt++){const list=nativeInstances(m,native,alt);assert.equal(c.anm_manager_count(a,alt),list.length,label+' count');for(let i=0;i<list.length;i++){const h=m.u32(list[i]+0x544);assert.equal(c.anm_manager_order(a,alt,i),h,label+' queue');const vm=c.anm_manager_find(a,h);compareAnm(c,m,vm,list[i],label+' VM '+h+' script '+(m.u32(list[i]+0x4a8)&65535));assert.deepEqual(Buffer.from(memory(c,c.anm_vm_translation(vm),12)),Buffer.from(m.bytes(list[i]+0x5ec,12)));checks++;}}};
   const step=(pressed=0,repeated=0)=>{const label=scenario+'/'+frames;m.u32(0x4e6d1c,pressed);m.u32(0x4e6d18,repeated);sounds=[];events=[];const screen=m.i32(owner+0x18),address=screen===1?0x461050:screen===5?0x4660e0:screen===6?0x4664c0:screen===7?0x466b70:0;assert.ok(address,'screen '+screen);assert.equal(m.call(address,{ecx:owner}),1);if(screen===7){assert.equal(c.title_character_update(cf,pressed,repeated),1,string(c,c.title_character_error(cf)));assert.deepEqual(Array.from(new Int32Array(c.memory.buffer,c.title_character_events(cf),c.title_character_event_count(cf))),events,label+' character services');}else{const flags=new DataView(c.memory.buffer).getUint32(lp+24,true);assert.equal(c.title_selection_update(f,pressed,repeated,c.title_character_extra(cf,-1),c.title_character_clear_mask(cf,flags)),1,string(c,c.title_selection_error(f)));}assert.deepEqual(Array.from(new Int32Array(c.memory.buffer,c.title_menu_sounds(f),c.title_menu_sound_count(f))),sounds,label+' sounds');const st=Array.from(new Uint32Array(c.memory.buffer,c.title_menu_state(f),254));for(const[index,address]of[[0,owner+0x18],[1,owner+0x1c],[2,owner+0x20],[3,owner+0xf4],[4,owner+0x5ba0],[5,owner+0x6a4]])assert.equal(st[index],m.u32(address),label+' state '+index);assert.deepEqual(Buffer.from(memory(c,c.title_menu_cursor(f),0xd8)),Buffer.from(m.bytes(owner+0x24,0xd8)),label+' menu');for(let i=0;i<248;i++)assert.equal(st[6+i],m.u32(owner+0x2c4+i*4),label+' handle '+i);assert.deepEqual(Buffer.from(memory(c,age,20)),Buffer.from(m.bytes(owner+0x2b0,20)),label+' timer');dv=new DataView(c.memory.buffer);assert.equal(dv.getUint32(lp+24,true),m.u32(0x4e7794),label+' mode flags');assert.equal(dv.getInt32(pp+24,true),m.i32(0x4e7410),label+' difficulty');assert.equal(dv.getInt32(pp+32,true),m.i32(0x4e7424),label+' spell');assert.equal(dv.getInt32(settings+8,true),m.i32(owner+0x5910),label+' saved difficulty');assert.equal(dv.getInt32(settings,true),m.i32(0x4e9bec),label+' preferred mode');assert.equal(dv.getInt32(settings+4,true),m.i32(0x4e0ef4),label+' configured difficulty');assert.equal(dv.getInt32(pp+16,true),m.i32(0x4e7404),label+' character');assert.equal(dv.getInt32(pp,true),m.i32(0x4e73f4),label+' stage');assert.equal(dv.getInt32(settings+12,true),m.i32(0x4e9be8),label+' preferred character');compareQueue(label+' before queue update');m.u32(owner+0x2bc,0);m.i32(owner+0x2b0,m.i32(owner+0x2b4));m.i32(owner+0x2b4,m.i32(owner+0x2b4)+1);m.f32(owner+0x2b8,Math.fround(m.f32(owner+0x2b8)+1));c.title_menu_tick(f,1);for(let alt=0;alt<2;alt++){assert.equal(c.anm_manager_update(a,alt,1),1,string(c,c.anm_manager_error(a)));m.call(alt?0x487890:0x487740,{ecx:native});}compareQueue(label+' after queue update');assert.deepEqual(Buffer.from(memory(c,c.anm_manager_random(a),8)),Buffer.from(m.bytes(0x4e9a40,8)),label+' visual RNG');frames++;return st[0];};


   const state=()=>Array.from(new Uint32Array(c.memory.buffer,c.title_menu_state(f),6)),ready=()=>{for(let i=0;state()[2]!==2&&i<150;i++)step();assert.equal(state()[2],2);},transition=()=>{const before=state()[0];for(let i=0;state()[0]===before&&i<50;i++)step();assert.notEqual(state()[0],before);};
   ready();step(1);transition();if(type===0){ready();step(scenario%2?0x80:0x40);step(1);transition();}assert.equal(state()[0],6);
   if(reason===4){step();assert.equal(state()[0],7);step();assert.equal(state()[0],9);continue;}
   ready();step(scenario%2?0x20:0x40);step(1);transition();assert.equal(state()[0],7);ready();
   for(let i=0;i<6;i++)step(i%2?0x80:0x40,i%3?0:0x80);
   if(scenario>>2&1){step(0x102);transition();assert.equal(state()[0],6);}
   else{step(0x80001);transition();assert.ok([2,9,21].includes(state()[0]),'destination '+state()[0]);}
  }finally{c.title_character_delete(cf);c.title_menu_delete(f);c.anm_manager_delete(a);}
 }
 report('title-character-menu',{passed:true,scenarios:64,frames,animationChecks:checks,originalFunctions:['0x460110','0x460160','0x466b70','0x461050','0x4660e0','0x4664c0','0x487740','0x487890'],scope:'Actual four character selection trees, recorded completion emblems, native Extra restrictions and every cursor/confirm/cancel/selection-recovery branch are compared per frame. Title completion predicates execute unmodified original code. Checkpoint file availability, game-start overlay objects, audio device and destination handling are observed boundaries; actual complete-session/browser integration remains separate.'});
 }finally{m.close();}
});
