import test from'node:test';import assert from'node:assert/strict';import{readFileSync}from'node:fs';import{resolve}from'node:path';import{core,oracle,memory,string,root,report,enableNativeMath}from'./helpers.mjs';import{resourceLoader,nativePool,prepareBank,nativeInstances,compareAnm}from'./anm-oracle.mjs';
const hash=text=>{let n=2166136261;for(const b of Buffer.from(text))n=Math.imul(n^b,16777619)>>>0;return n|0;};const cstring=(c,p)=>{const b=memory(c,p,Math.min(1024,c.memory.buffer.byteLength-p)),n=b.indexOf(0);return Buffer.from(b.subarray(0,n<0?b.length:n));};
test('TH15 Player Data matches native navigation, spell rows, records and animation queues',async()=>{
 const c=await core(),m=await oracle();enableNativeMath(m);const sprintfPrefix=Buffer.from(m.bytes(0x490cf2,5)),loader=resourceLoader(m),tm=m.allocate(36),performance=m.allocate(0x40),crtThread=m.allocate(0x3bc),formatOutput=m.allocate(4096);m.view(crtThread,0x3bc).fill(0);m.u32(crtThread+0x5c,0x4c5740);m.u32(crtThread+0x14,1);m.u32(crtThread+0x70,1);m.u32(crtThread+0x68,0x4dff60);m.u32(crtThread+0x6c,m.u32(0x4e03e4));m.replace(0x496fbd,'initialized CRT thread environment',()=>crtThread);for(const e of m.importMap.values())if(e.name==='DecodePointer'){e.handler=()=>m.u32(m.reg('ESP')+4);e.argc=1;}m.write(0x490cf2,sprintfPrefix);m.call(0x4937d7);const base=m.heap;let owner=0,scores=0,events=[],draws=[],times=[],prepared='',frames=0,checks=0,textChecks=0,bitmaps=[],bitmapChecks=0,date=[2026,10,2,20,36],stamp=1700000000n;
 m.replace(0x476360,'result menu sound',()=>{events.push(4,m.i32(m.reg('ESP')+4));return 0;},2);
 m.replace(0x44d360,'result music preparation',()=>{prepared=m.string(m.u32(m.reg('ESP')+8));return 0;},2);m.replace(0x44d3e0,'result music playback',()=>{const track=m.i32(m.reg('ESP')+8);events.push(1,hash(prepared),track);m.view(scores+0x3374e+track,1)[0]=1;return 0;},2);
 m.replace(0x490eda,'result wall-clock timestamp',()=>{events.push(2);const p=m.u32(m.reg('ESP')+4),b=Buffer.alloc(8);b.writeBigInt64LE(stamp);m.write(p,b);return Number(stamp&0xffffffffn);});m.replace(0x45bb60,'completed live replay release',()=>{events.push(3);return 0;});
 m.replace(0x4915bf,'score calendar',()=>{const p=m.u32(m.reg('ESP')+4);times.push(Buffer.from(m.bytes(p,8)).readBigInt64LE(0));m.i32(tm+16,date[1]-1);m.i32(tm+20,date[0]-1900);m.i32(tm+12,date[2]);m.i32(tm+8,date[3]);m.i32(tm+4,date[4]);return tm;});
 m.replace(0x402aa0,'physical keyboard boundary',()=>{m.view(m.reg('ECX'),256).fill(0);return 1;});
 m.replace(0x486da0,'bitmap text queue collection',()=>{const sp=m.reg('ESP'),format=m.u32(sp+28),args=Array.from({length:16},(_,i)=>m.u32(sp+32+i*4));const source=m.string(format);let arg=0;source.replace(/%%|%(?:[0-9]+)?(?:\.[0-9]+)?[sd]/g,token=>{if(token==='%%')return token;if(token.endsWith('s')){const bytes=m.bytes(args[arg],1024),end=bytes.indexOf(0),copy=m.allocate(end+1);m.write(copy,bytes.subarray(0,end+1));args[arg]=copy;}arg++;return token;});const vm=m.u32(sp+8);assert.ok(vm);bitmaps.push({format,args,handle:m.u32(vm+0x544),color:m.u32(sp+12)});return 0;});
 m.replace(0x40c570,'result text queue collection',()=>{const sp=m.reg('ESP'),font=m.u32(sp+4),pos=m.u32(sp+8);draws.push({format:m.u32(sp+12),args:Array.from({length:16},(_,i)=>m.u32(sp+16+i*4)),color:m.u32(font+0x19224),font:m.i32(font+0x1923c),position:[m.f32(pos),m.f32(pos+4),m.f32(pos+8)]});return 0;});
 try{for(let scenario=0;scenario<8;scenario++){
  m.heap=base;m.view(m.heap,0x1caf980).fill(0);const a=c.anm_manager_create(),native=nativePool(m),t=c.title_menu_create(a),f=c.title_frame_create(t),r=c.title_results_create(f),viewer=c.title_player_data_create(r);owner=m.allocate(0x5bb0);scores=m.allocate(0x34000);const text=m.allocate(0x19270),block=c.allocate(5*0xa4a0+0x42c),character=scenario%4,rank=scenario%5,mode=scenario%2?0x100:0,legacy=mode===0,slot=scenario%11,currentScore=slot<10?1000-slot*100:0,continues=scenario%3===0?0:scenario%3;
  try{m.u32(0x4e9a40,0);m.u32(0x4e9a44,0);m.view(owner,0x5bb0).fill(0);m.view(scores,0x34000).fill(0);m.u32(0x4e9a58,text);m.u32(0x4e9bc8,scores);m.u32(0x4e9a88,performance);m.write(performance+0x20,Buffer.from(new Float64Array([537,600]).buffer));m.i32(owner+0x18,11);m.i32(0x5218e4,0);m.i32(0x5218e0,0);m.view(0x521c20,512).fill(0);m.i32(owner+0x1c,0);m.u32(owner+0xf4,1);m.i32(owner+0x2c,10);m.i32(owner+0x24,0);m.call(0x403b10,{ecx:owner+0x24});c.title_menu_count(t,10);c.title_menu_push(t);c.title_results_configure(r,character,rank,mode,currentScore,continues,scenario+17);c.title_menu_configure(t,0,0,0,mode);c.title_frame_configure(f,11,1,0,0,0,0,false,rank,1);new DataView(c.memory.buffer).setInt32(c.title_player_data_keyboard(viewer),1,true);m.u32(0x4e7794,mode);m.i32(0x4e7404,character);m.i32(0x4e7408,0);m.i32(0x4e7410,rank);m.i32(0x4e740c,currentScore);m.i32(0x4e7414,continues);m.i32(0x4e7594,scenario+17);m.i32(0x4e73f0,6);m.i32(0x4e73f4,1);m.u32(0x4e9bc4,0x22334455);m.u32(0x4ca620,0x4e73e8);m.f32(0x4e73e8,1);m.write(owner+0x2b0,Buffer.from(memory(c,c.title_menu_field(t,2),20)));
   const data=Buffer.alloc(5*0xa4a0+0x42c);for(let i=0;i<10;i++){const at=character*0xa4a0+(legacy?0x5188:0)+0x10+rank*320+i*32;data.writeInt32LE(1000-i*100,at);data[at+4]=i%10;data[at+5]=i%4;Buffer.from(('Row'+i).padEnd(8,' ')+'\0').copy(data,at+6);data[at+15]=0x91+i;if(i%3){data.writeBigInt64LE(1600000000n+BigInt(i),at+16);data.writeFloatLE(i*.25,at+24);}data.writeInt32LE(i*17,at+28);}for(let ch=0;ch<5;ch++)for(let variant=0;variant<2;variant++){
 const base=ch*0xa4a0+variant*0x5188;data.writeInt32LE(12345+ch*31+variant,base+0x5154);data.writeBigUInt64LE(ch%2?183000000000n+BigInt(ch):123450000n+BigInt(ch),base+0x5158);for(let d=0;d<5;d++)data.writeInt32LE(ch*37+variant*13+d,base+0x5160+d*4);
 for(let card=0;card<119;card++){const at=base+0x8d0+card*0x9c;const label=Buffer.from(('Spell'+card).padEnd(card%3?22:42,' '));label.copy(data,at);data[at+label.length]=0;data.writeInt32LE((card+ch+variant)%3?card:0,at+0x80);data.writeInt32LE((card+ch+variant)%4?card+17:0,at+0x88);}
 }const stored=scenario%3?'PLAYER  ':'        ';Buffer.from(stored+'\0').copy(data,5*0xa4a0+12);memory(c,block,data.length).set(data);assert.equal(c.title_results_records(r,block),1);m.write(scores+8,data.subarray(0,5*0xa4a0));m.write(scores+0x33728,data.subarray(5*0xa4a0));const details=c.title_results_details(r),dv=new DataView(c.memory.buffer);dv.setBigInt64(details,stamp,true);dv.setFloat64(details+8,537,true);dv.setFloat64(details+16,600,true);memory(c,c.title_player_data_date(viewer),20).set(new Uint8Array(new Int32Array(date).buffer));
   for(const[name,id]of[['text.anm',0],['ascii.anm',5],['title.anm',16],['title_v.anm',17]]){const bytes=readFileSync(resolve(root,'reference/assets',name)),p=c.allocate(bytes.length);memory(c,p,bytes.length).set(bytes);assert.equal(c.anm_manager_load(a,id,p,bytes.length),1);c.release(p);const bank=prepareBank(m,loader,name,bytes,native,id);if(id===5){m.u32(text+0x19258,bank);assert.equal(c.anm_manager_fallback(a,5),1);}else if(id===0)m.u32(0x4e7f00,bank);else m.u32(owner+(id===16?0x10:0x14),bank);}
   const compareQueue=label=>{for(let alt=0;alt<2;alt++){const list=nativeInstances(m,native,alt);assert.equal(c.anm_manager_count(a,alt),list.length,label+' queue length');for(let i=0;i<list.length;i++){const handle=m.u32(list[i]+0x544);assert.equal(c.anm_manager_order(a,alt,i),handle);compareAnm(c,m,c.anm_manager_find(a,handle),list[i],label+' VM '+handle);checks++;}}};
   const step=(pressed=0,repeated=0)=>{const label=scenario+'/'+frames;m.u32(0x4e6d1c,pressed);m.u32(0x4e6d18,repeated);events=[];bitmaps=[];assert.equal(m.call(0x468be0,{ecx:owner}),1);assert.equal(c.title_player_data_update(viewer,pressed,repeated),1,string(c,c.title_player_data_error(viewer)));const sounds=Array.from(new Int32Array(c.memory.buffer,c.title_player_data_sounds(viewer),c.title_player_data_sound_count(viewer)));assert.deepEqual(sounds,events.filter((v,i)=>events[i-1]===4),label+' sounds');assert.deepEqual(Array.from(new Int32Array(c.memory.buffer,c.title_player_data_fields(viewer),3)),[m.i32(owner+0x2ac),m.i32(0x5218e4),m.i32(0x5218e0)],label+' display/cheat');for(let page=0;page<2;page++)assert.deepEqual(Buffer.from(memory(c,c.title_player_data_cursors(viewer,page),0xd8)),Buffer.from(m.bytes(owner+(page?0x1d4:0xfc),0xd8)),label+' secondary menu');assert.equal(c.title_player_data_bitmap_count(viewer),bitmaps.length,label+' bitmap requests');for(let i=0;i<bitmaps.length;i++){const b=bitmaps[i];m.call(0x490cf2,{args:[formatOutput,b.format,...b.args],limit:10000000});const bytes=m.bytes(formatOutput,4096),end=bytes.indexOf(0);assert.deepEqual(cstring(c,c.title_player_data_bitmap(viewer,i)),Buffer.from(bytes.subarray(0,end)),label+' bitmap string');assert.equal(c.title_player_data_bitmap_handle(viewer,i),b.handle,label+' bitmap handle');assert.equal(c.title_player_data_bitmap_color(viewer,i)>>>0,b.color,label+' bitmap color');bitmapChecks+=3;}const state=Array.from(new Uint32Array(c.memory.buffer,c.title_menu_state(t),254));for(const[i,at]of[[0,0x18],[1,0x1c],[2,0x20],[3,0xf4],[4,0x5ba0]])assert.equal(state[i],m.u32(owner+at),label+' state '+i);for(let i=0;i<248;i++)assert.equal(state[6+i],m.u32(owner+0x2c4+i*4),label+' animation handle '+i);assert.deepEqual(Buffer.from(memory(c,c.title_menu_cursor(t),0xd8)),Buffer.from(m.bytes(owner+0x24,0xd8)),label+' history');assert.deepEqual(Buffer.from(memory(c,c.title_menu_field(t,2),20)),Buffer.from(m.bytes(owner+0x2b0,20)),label+' timer');assert.deepEqual(Buffer.from(memory(c,c.title_results_blocks(r,0),5*0xa4a0)),Buffer.from(m.bytes(scores+8,5*0xa4a0)),label+' all score rows');assert.deepEqual(Buffer.from(memory(c,c.title_results_blocks(r,1),0x42c)),Buffer.from(m.bytes(scores+0x33728,0x42c)),label+' score settings');checks+=12;
    draws=[];times=[];assert.equal(m.call(0x4699a0,{ecx:owner}),1);assert.equal(c.title_player_data_draw(viewer),1,string(c,c.title_results_error(r)));assert.equal(c.title_player_data_text_count(viewer),draws.length,label+' captions');for(let i=0;i<draws.length;i++){m.call(0x490cf2,{args:[formatOutput,draws[i].format,...draws[i].args],limit:10000000});const rendered=m.bytes(formatOutput,4096),end=rendered.indexOf(0);draws[i].text=Buffer.from(rendered.subarray(0,end));const style=c.title_player_data_style(viewer,i),view=new DataView(c.memory.buffer);assert.deepEqual(cstring(c,c.title_player_data_text(viewer,i)),draws[i].text,label+' caption '+i);assert.equal(view.getUint32(style,true),draws[i].color,label+' text color');assert.equal(view.getInt32(style+12,true),draws[i].font,label+' text font');assert.deepEqual(Array.from(new Float32Array(c.memory.buffer,c.title_player_data_position(viewer,i),3)),draws[i].position,label+' text position');textChecks+=4;}assert.deepEqual(Array.from(new BigInt64Array(c.memory.buffer,c.title_player_data_timestamps(viewer),c.title_player_data_timestamp_count(viewer))),times,label+' calendar timestamps');compareQueue(label+' before animation update');m.u32(owner+0x2bc,0);m.i32(owner+0x2b0,m.i32(owner+0x2b4));m.i32(owner+0x2b4,m.i32(owner+0x2b4)+1);m.f32(owner+0x2b8,Math.fround(m.f32(owner+0x2b8)+1));c.title_menu_tick(t,1);for(let alt=0;alt<2;alt++){assert.equal(c.anm_manager_update(a,alt,1),1,string(c,c.anm_manager_error(a)));m.call(alt?0x487890:0x487740,{ecx:native});}compareQueue(label+' after animation update');frames++;return state[0];};
   for(let i=0;i<9;i++)step();for(let i=0;i<scenario;i++)step(128);for(let rank=0;rank<5;rank++){const count=new DataView(c.memory.buffer).getInt32(c.title_player_data_cursors(viewer,1)+8,true);for(let page=0;page<count;page++){step(1);step();}step(32);step(64);step(128);}step(0x102);for(let i=0;i<9;i++)if(step()===1)break;assert.equal(m.i32(owner+0x18),1);
  }finally{c.title_player_data_delete(viewer);c.release(block);c.title_results_delete(r);c.title_frame_delete(f);c.title_menu_delete(t);c.anm_manager_delete(a);}
 }
 report('title-player-data',{passed:true,scenarios:8,frames,checks,textChecks,bitmapChecks,originalFunctions:['0x468be0','0x4694e0','0x4699a0','0x41fa20'],scope:'Original Player Data menus and actual title/ascii/text animation trees: eight character/mode selections, five difficulty tabs, full page wrap and rank change, known/unknown spell names/fullwidth numbering/padding/counts/colors, score/date/gradient/plays/time/clear requests, complete stored records and title return. Original VC2012 formatting is executed, bitmap names copied before leaving native stack. Texture/font writes and physical keyboard remain explicit boundaries.'});
 }finally{m.close();}
});
