#include "AsciiText.hpp"
namespace th15 {
bool AsciiText::initialize(i32 bank){auto* resource=animations.resource(bank);if(!resource){error="ASCII animation resource unavailable";return false;}glyph=AnmVm{};glyph.environment=&environment;glyph.resource=resource;glyph.visual.flags=7;glyph.visual.render_flags=0x4000;if(!glyph.select_sprite(0)){error="ASCII initial sprite unavailable";return false;}return true;}
bool AsciiText::enqueue(const HudTextDraw& input,i32 lifetime,bool shadow){if(entries.size()>=320)return true;const auto length=input.text.find(char(0));const auto size=length==std::string::npos?input.text.size():length;if(size>=256){error="ASCII text exceeds original queue string capacity";return false;}AsciiTextEntry entry{input,lifetime,shadow};entry.text.text.resize(size);const float resolution=environment.resolution_scale;auto& p=entry.text.position;p={float(p.x*resolution),float(p.y*resolution),float(p.z*resolution)};if(input.style.coordinate_space==1){p.x=float(float(environment.screen_offsets[0])+p.x);p.y=float(float(environment.screen_offsets[1])+p.y);}entries.push_back(std::move(entry));return true;}
void AsciiText::update(){u32 next=0;for(u32 i=0;i<entries.size();i++){entries[i].lifetime=wrapping_add(entries[i].lifetime,-1);if(entries[i].lifetime>=0){if(next!=i)entries[next]=std::move(entries[i]);next++;}}entries.resize(next);}
bool AsciiText::draw_entry(const AsciiTextEntry& entry,AsciiGlyphServices& services){
 const auto& text=entry.text;const auto& style=text.style;auto& v=glyph.visual;auto& p=glyph.variables.position;const float resolution=environment.resolution_scale;v.render_flags&=0xff8fffff;v.flags=(v.flags&0xfebfffff)|0xa00009;p=text.position;v.scale=style.scale;
 float advance=0,height=0;bool linear=false;switch(style.font){case 1:advance=float(style.scale.x*6.f);height=9;break;case 2:advance=float(style.scale.x*7.f);height=10;break;case 3:advance=float(style.scale.x*7.f);height=10;linear=true;break;case 4:advance=float(style.scale.x*12.f);height=16;break;case 5:advance=float(style.scale.x*12.f);height=16;linear=true;break;default:advance=float(float(spacing)*style.scale.x);height=14;linear=style.scale.x!=1;break;}if(linear)v.render_flags|=0x800;else v.render_flags&=~0x800u;
 const auto width=[&](u8 ch){return ((style.font==2||style.font==3)&&ch=='.')||((style.font==4||style.font==5)&&ch==',')?float(style.scale.x*4.f):advance;};
 if(style.alignment==0||style.alignment==2){const bool narrow=style.font>=2&&style.font<=5;const float factor=style.alignment==0?.5f:1.f;if(narrow){for(u8 ch:text.text){float offset=width(ch);if(style.alignment==0)offset=float(offset*.5f);offset=float(offset*resolution);p.x=float(p.x-offset);}}else{float offset=float(float(text.text.size())*advance);if(style.alignment==0)offset=float(offset*.5f);p.x=float(p.x-float(offset*resolution));}}
 if(style.vertical_alignment==0)p.y=float(p.y-float(float(height*.5f)*resolution));else if(style.vertical_alignment==2)p.y=float(p.y-float(resolution*height));
 const auto select=[&](i32 index){if(glyph.select_sprite(index))return true;error="ASCII glyph sprite unavailable: "+std::to_string(index);return false;};
 for(u8 ch:text.text){if(ch==10){p.y=float(float(float(style.scale.y*height)*resolution)+p.y);p.x=text.position.x;continue;}if(ch!=' '){i32 index=v.sprite;if(style.font==0)index=i32(ch)-32;else if(style.font==1)index=i32(ch)+66;else if(style.font==2||style.font==3){advance=float(style.scale.x*7.f);if(ch>='a'&&ch<='z')index=i32(ch)+116;else switch(ch){case '/':index=206;break;case ':':index=207;break;case '-':index=208;break;case '*':index=209;break;case '%':index=210;break;case '$':index=257;break;case '.':index=211;advance=float(style.scale.x*4.f);break;case '+':index=212;break;default:index=i32(ch)+148;break;}}
  else if(style.font==4||style.font==5){advance=float(style.scale.x*12.f);p.y=text.position.y;switch(ch){case '/':index=249;break;case '.':index=250;break;case 's':index=251;break;case '*':index=252;break;case ',':index=253;advance=float(style.scale.x*4.f);p.y=float(float(resolution*3.f)+text.position.y);break;default:index=i32(ch)+191;break;}}
  if(style.font>=0&&style.font<=5&&!select(index))return false;v.flags|=8;
  if(entry.shadow){v.color=(style.color>>25)<<24;const float offset=float(resolution*2.f);p.x=float(offset+p.x);p.y=float(offset+p.y);if(!services.ascii_glyph(glyph)){error="ASCII shadow draw failed";return false;}p.x=float(p.x-offset);p.y=float(p.y-offset);}
  v.color=style.color;if(!services.ascii_glyph(glyph)){error="ASCII glyph draw failed";return false;}
 }p.x=float(float(resolution*advance)+p.x);}
 return true;
}
bool AsciiText::draw(i32 space,AsciiGlyphServices& services){for(const auto& entry:entries)if(entry.text.style.coordinate_space==space&&!draw_entry(entry,services))return false;return true;}
bool AsciiText::draw(i32 space,AnmRenderer& renderer){struct Services final:AsciiGlyphServices{AnmRenderer& renderer;explicit Services(AnmRenderer& r):renderer(r){}bool ascii_glyph(AnmVm& vm)override{return renderer.draw_glyph(vm)!=-2;}}services(renderer);if(!draw(space,services)){if(error.empty())error=renderer.error;return false;}renderer.flush();return true;}
}
