#include "BombReimu.hpp"
#include "AnmVisualState.hpp"
#include <cmath>
namespace th15 {
bool BombReimu::animation(u32& handle,i32 script,const Vec3& p){handle=context.animations.create(context.player_resource,script,-1,0,p);if(!handle){error=context.animations.error;return false;}context.animations.registry.find(handle)->visual.inherited_color=0;return true;}
bool BombReimu::interrupt(u32 handle,i32 label){if(context.animations.interrupt(handle,label))return true;error=context.animations.error;return false;}
bool BombReimu::start(){position=context.motion.position;if(!context.world.sound(49,true)){error="Reimu bomb audio failed";return false;}invalidate_spell();context.enemies.uses=wrapping_add(context.enemies.uses,1);orbs={};orbs_available=true;return animation(aura,24,position);}
bool BombReimu::initialize(ReimuOrb& o,i32 index){o.motion.velocity=context.motion.position;if(!animation(o.animation,16,o.motion.position))return false;o.active=1;o.age.set(0);o.index=index;o.damage_source=damage.circle(o.motion.position,56,0,9999,15);auto* s=damage.find(o.damage_source);if(!s){error=damage.error;return false;}s->flags|=4;s->interval=3;return true;}
bool BombReimu::update_orb(ReimuOrb& o){
    auto& m=o.motion;if(o.age.current!=o.age.previous){const i32 release=wrapping_mul(wrapping_add(o.index,9),10);if(o.age.current<90){m.velocity=context.motion.position;m.radius=float(m.radius+1.5f);m.angle=normalize_angle(float(m.angle+0.10471975803375244f));}
        else if(o.age.current<release){m.velocity=context.motion.position;m.angle=normalize_angle(float(m.angle+0.10471975803375244f));}
        else if(o.age.current==release){m.flags&=~15u;m.set_angle(float(std::atan2(double(o.displacement.y),double(o.displacement.x))));m.speed=float(std::sqrt(double(float(float(o.displacement.x*o.displacement.x)+float(o.displacement.y*o.displacement.y)))));}
        else{if(enemies){float nearest=262144.f;o.target=0;for(auto* e:enemies->enemies)if(!(e->flags&0xc000021u)){const float dx=float(m.position.x-e->motion.position.x),dy=float(m.position.y-e->motion.position.y),distance=float(float(dx*dx)+float(dy*dy));if(distance<nearest){nearest=distance;o.target=e->id;}}}
            if(!o.target){if(m.position.x<-160||m.position.x>160||m.position.y<32||m.position.y>416)m.speed=float(m.speed*.9f);}
            else{auto* target=enemies?enemies->find(o.target):nullptr;if(!target){error="Reimu orb target no longer resolves";return false;}if(!(target->flags&0xc000021u)){const float dx=float(target->motion.position.x-m.position.x),dy=float(target->motion.position.y-m.position.y),bearing=float(std::atan2(double(dy),double(dx)));float delta=float(bearing-m.angle);if(delta>3.1415927410125732f)delta=float(bearing-float(m.angle+6.2831854820251465f));else if(float(m.angle-bearing)>3.1415927410125732f)delta=float(bearing-float(m.angle-6.2831854820251465f));float speed=m.speed;if(std::abs(delta)>=0.7853981852531433f){speed=float(speed-.7f);if(speed<1)speed=1;}else if(std::abs(delta)<0.2617993950843811f){speed=float(speed+.2f);if(speed>8)speed=8;}m.set_angle(normalize_angle(float(m.angle+float(delta*.1f))));m.speed=speed;}}}}
    const Vec3 prior=m.position;m.integrate(frame_rate);m.advance(frame_rate);if(auto* vm=context.animations.registry.find(o.animation))vm->visual.translation=m.position;o.displacement={float(m.position.x-prior.x),float(m.position.y-prior.y),float(m.position.z-prior.z)};o.age.tick(&frame_rate);return true;
}
bool BombReimu::explode(ReimuOrb& o){if(o.archived){if(context.animations.retire(o.animation))return true;error=context.animations.error;return false;}if(o.active){if(!context.world.sound(27,false)||!context.world.cancel_bullets(o.motion.position,128,1)||!context.world.cancel_lasers(o.motion.position,128,1,true)){error="Reimu orb explosion service failed";return false;}const i32 id=damage.circle(o.motion.position,64,8,11,100);auto* source=damage.find(id);if(!source){error=damage.error;return false;}source->flags|=4;}if(!interrupt(o.animation,1))return false;o.active=0;if(auto* s=damage.find(o.damage_source))s->flags&=~1u;o.damage_source=0;return true;}
bool BombReimu::explode_all(){for(auto& o:orbs){if(o.archived){if(!context.animations.retire(o.animation)){error=context.animations.error;return false;}continue;}if(!explode(o))return false;}return true;}
bool BombReimu::stop_active(){if(!explode_all()||!interrupt(aura,1)||!context.world.nudge({8,6,6})){if(error.empty())error="Reimu bomb stop effect failed";return false;}orbs_available=false;context.session.bomb_state=0;return true;}
bool BombReimu::cancel(){const i32 slot=age.current%8;for(u32 i=0;i<8;i++){const auto& o=orbs[i];if(o.active&&slot==i32(i)){const i32 reward=(~context.spell.flags)&1;if(!context.world.cancel_bullets(o.motion.position,64,reward)||!context.world.cancel_lasers(o.motion.position,64,(~context.spell.flags)&1,true)){error="Reimu orb cancellation failed";return false;}}}return true;}
bool BombReimu::frame(bool& finished){context.life.invulnerability.set(40);if(auto* vm=context.animations.registry.find(aura))vm->visual.translation=context.motion.position;
    if(age.current>119){bool any=false;for(auto& o:orbs){if(context.animations.registry.find(o.animation)){any=true;break;}o.animation=0;}if(!any){if(!interrupt(aura,1))return false;orbs_available=false;finished=true;return true;}}
    if(age.current==200){if(!explode_all()||!interrupt(aura,1)||!context.world.nudge({8,6,6})){if(error.empty())error="Reimu bomb ending effect failed";return false;}return true;}
    if(age.current!=age.previous&&age.current==0){float direction=0;for(u32 i=0;i<8;i++){auto& o=orbs[i];if(!initialize(o,i32(i)))return false;o.motion.flags=(o.motion.flags&~13u)|2;o.motion.radius=0;o.motion.angle=normalize_angle(direction);o.motion.angular_velocity=0.04908738657832146f;auto* source=damage.find(o.damage_source);source->damage_limit=300;direction=normalize_angle(float(direction+0.7853981852531433f));}}
    for(auto& o:orbs)if(o.active){if(!update_orb(o))return false;auto* source=damage.find(o.damage_source);if(!source){error="Reimu orb damage source unavailable";return false;}if(source->accumulated<300)source->motion.position=o.motion.position;else{if(!explode(o)||!context.world.sound(27,false)||!context.world.nudge({8,6,6})){if(error.empty())error="Reimu orb burst effect failed";return false;}}}return cancel();
}
}
