#include "DialogueAnmHost.hpp"
namespace th15 {
bool DialogueAnmHost::fail(const char* message){if(error.empty())error=message;return false;}
bool DialogueAnmHost::create(i32 resource,i32 script,u32& handle){handle=animations.create(resource,script,-1,0);return handle!=0||fail("Dialogue animation creation failed");}
bool DialogueAnmHost::interrupt(u32 handle,i32 label,bool immediate){return animations.interrupt(handle,label,immediate)||fail("Dialogue animation interrupt failed");}
bool DialogueAnmHost::retire(u32& handle){return animations.retire(handle)||fail("Dialogue animation retirement failed");}
bool DialogueAnmHost::text_initialize(u32 handle){auto* vm=animations.registry.find(handle);if(!vm)return fail("Dialogue text animation missing");vm->visual.render_flags|=0x1000;return scene.initialize_text(*vm,21,21)||fail("Dialogue text initialization failed");}
bool DialogueAnmHost::text(const DialogueText& request){auto* vm=animations.registry.find(request.handle);if(!vm)return fail("Dialogue text animation missing");if(request.move)vm->visual.translation=request.position;return scene.paint_text(*vm,request)||fail("Dialogue text painting failed");}
bool DialogueAnmHost::position(u32 handle,const Vec3& position){if(auto* vm=animations.registry.find(handle))vm->visual.translation=position;return true;}
bool DialogueAnmHost::depth(u32 handle,float depth){if(auto* vm=animations.registry.find(handle))vm->visual.translation.z=depth;return true;}
bool DialogueAnmHost::create_balloon(i32 resource,i32 script,const Vec3& position,float width,i32 style,u32& handle){handle=animations.create(resource,script,-1,0,position);return handle?balloon_width(handle,style,width):fail("Dialogue balloon animation creation failed");}
bool DialogueAnmHost::balloon_width(u32 handle,i32 style,float width){auto* parent=animations.registry.find(handle);if(!parent)return fail("Dialogue balloon animation missing");const float value=float(width+16.f);for(i32 script:{wrapping_add(style,173),wrapping_add(style,205)}){auto* child=animations.registry.find_child_script(*parent,script,0);if(!child)return fail("Dialogue balloon width child missing");child->variables.floats[0]=value;}return true;}
bool DialogueAnmHost::follow_balloon(DialogueState& state){auto* parent=animations.registry.find(state.handles[11]);if(!parent){state.handles[11]=0;return true;}auto* child=animations.registry.find_child_script(*parent,wrapping_add(state.balloon_style,173),0);if(!child)return true;Vec3 anchor;if(!anm_position(*child,anchor))return fail("Dialogue balloon anchor unavailable");if(environment.resolution_scale==0)return fail("Dialogue balloon resolution is zero");const float factor=float(2.f/environment.resolution_scale);anchor.x=float(anchor.x*factor);anchor.y=float(anchor.y*factor);if(state.speaker>=1){if(child->visual.scale.x<1.f){const float offset=float(float(float(child->visual.scale.x+.125f)*32.f)-6.f);anchor.x=float(anchor.x+offset);}else anchor.x=float(anchor.x+26.f);}else anchor.x=float(anchor.x-36.f);for(u32 slot:{6u,8u,7u,9u})if(auto* vm=animations.registry.find(state.handles[slot]))vm->visual.translation=anchor;return true;}
bool DialogueAnmHost::release(DialogueState& state){bool ok=true;for(auto& handle:state.handles)if(!retire(handle))ok=false;return ok;}
}
