#include "EnemyCheckpoint.hpp"
#include "EclFile.hpp"
#include <algorithm>
namespace th15 {
namespace {
constexpr u32 owner_size=0x574c,state_offset=0x120c,payload_magic=0x31585445;
template<class T>void put(u8* p,u32 at,const T& v){std::memcpy(p+at,&v,sizeof v);}
template<class T>void get(const u8* p,u32 at,T& v){std::memcpy(&v,p+at,sizeof v);}
u32 word(const u8* p,u32 at){u32 v;get(p,at,v);return v;}
template<class S,class Copy>void fields(S& s,Copy copy){
 copy(0,s.previous);copy(0x44,s.motion);copy(0x88,s.absolute);copy(0xcc,s.relative);copy(0x110,s.hitbox);copy(0x118,s.hurtbox);copy(0x120,s.rotation_angle);
 copy(0x124,s.animation_handles);copy(0x164,s.animation_offsets);copy(0x224,s.animation_parents);copy(0x264,s.selected_animation_resource);copy(0x268,s.animation_resource);copy(0x26c,s.animation_script);copy(0x270,s.animation_base);copy(0x274,s.movement_direction);copy(0x278,s.animation_rotation_mode);copy(0x27c,s.animation_layer);copy(0x280,s.last_hit_position);
 copy(0x28c,s.integer_registers);copy(0x29c,s.float_registers);copy(0x2ac,s.temporary_registers);copy(0x2bc,s.age_timer);copy(0x2d0,s.lifetime_timer);copy(0x2e4,s.slowdown);
 copy(0x2f8,s.absolute_position);copy(0x360,s.relative_position);copy(0x3c8,s.absolute_angle);copy(0x3f8,s.absolute_speed);copy(0x428,s.relative_angle);copy(0x458,s.relative_speed);copy(0x488,s.absolute_shape);copy(0x4cc,s.relative_shape);copy(0x510,s.absolute_wave);copy(0x554,s.relative_wave);
 for(u32 i=0;i<16;i++){auto& b=s.shooters.shooters[i];const u32 base=0x598+i*896;copy(base,b.sprite);copy(base+4,b.color);copy(base+8,b.position);copy(base+20,b.angle);copy(base+24,b.angle_step);copy(base+28,b.speed);copy(base+32,b.speed_step);copy(base+36,b.radius);for(u32 j=0;j<18;j++){auto& t=b.transforms[j];const u32 at=base+40+j*44;copy(at,t.floats);copy(at+16,t.integers);copy(at+32,t.type);copy(at+36,t.active);}copy(base+832,b.extra);copy(base+868,b.count);copy(base+870,b.rows);copy(base+872,b.pattern);copy(base+874,b.reserved);copy(base+876,b.flags);copy(base+880,b.shoot_sound);copy(base+884,b.transform_sound);copy(base+888,b.tail);}
 copy(0x3d98,s.shooters.next_transform);copy(0x3dd8,s.shooters.offset);copy(0x3e98,s.shooters.origin);copy(0x3f58,s.sprite_size);copy(0x3f60,s.bound_center);copy(0x3f68,s.bound_size);copy(0x3f70,s.score);copy(0x3f74,s.life);copy(0x3f78,s.initial_life);copy(0x3f7c,s.phase_life);copy(0x3f80,s.life_budget);copy(0x3f84,s.life_threshold);copy(0x3f88,s.cumulative_damage);copy(0x3f8c,s.life_flags);copy(0x3f90,s.primary_drop);copy(0x3f94,s.item_drops);copy(0x3fd4,s.drop_radius);copy(0x3fdc,s.pending_damage);
 copy(0x3fe0,s.death_sound);copy(0x3fe4,s.death_animation);copy(0x3fe8,s.death_animation_resource);copy(0x3fec,s.damage_flash_frames);copy(0x3ff4,s.hit_sound);copy(0x3ff8,s.collision_timer);copy(0x400c,s.invulnerability_timer);copy(0x4020,s.script_control);copy(0x4028,s.damage_limit);copy(0x402c,s.damage_timer);copy(0x4040,s.damage_multiplier);copy(0x4048,s.phase_timer);copy(0x4060,s.flags);copy(0x4064,s.lifecycle_flags);copy(0x4068,s.inactive_animation);copy(0x406c,s.normal_animation);copy(0x4070,s.boss_slot);
 for(u32 i=0;i<8;i++){copy(0x4078+i*136,s.interrupts[i].life);copy(0x407c+i*136,s.interrupts[i].time);}
 copy(0x44c4,s.distortion.target);copy(0x44c8,s.distortion.radius);copy(0x44cc,s.distortion.color);copy(0x44d0,s.distortion.phase_x);copy(0x44d4,s.distortion.phase_y);copy(0x451c,s.callback_state);copy(0x4528,s.chapter);copy(0x452c,s.chapter_contribution);
}
bool put_name(u8* p,const std::string& name){if(name.size()>=64||name.find('\0')!=std::string::npos)return false;std::memset(p,0,64);std::memcpy(p,name.data(),name.size());return true;}
bool get_name(const u8* p,std::string& name){const auto* end=std::find(p,p+64,u8(0));if(end==p+64)return false;name.assign(reinterpret_cast<const char*>(p),end-p);return true;}
constexpr std::array<u32,5> updates{{0,0x4315f0,0x431720,0x431840,0x4318a0}};
constexpr std::array<u32,3> damages{{0,0x431a30,0x431a50}};
}
bool EnemyCheckpoint::write_file(std::vector<u8>& out){
 error.clear();out.clear();if(!available){error="No enemy checkpoint to serialize";return false;}out.resize(0xa8,0);put(out.data(),0,integer_registers);put(out.data(),0x10,float_registers);put(out.data(),0x30,counters);put(out.data(),0x3c,boss_ids);put(out.data(),0x7c,manager_flags);put(out.data(),0x80,control);put(out.data(),0x84,next_id);put(out.data(),0x88,total);put(out.data(),0x8c,timer);put(out.data(),0xa0,shot_damage);put(out.data(),0xa4,other_damage);
 auto tree=[&](u32 handle)->bool{if(!pool.write_tree(handle,animations,out)){error=pool.error;return false;}return true;};EclFile ecl;
 for(u32 index=0;index<entries.size();index++){const auto& entry=entries[index];const auto& s=entry.state;const u32 at=out.size();out.resize(at+owner_size,0);auto* record=out.data()+at;fields(s,[&](u32 offset,const auto& value){put(record+state_offset,offset,value);});put(record,0x5740,s.id);put(record,0x5744,s.parent_id);put(record,0x14f8,index+1<entries.size()?u32(1):u32(0));
  if(u32(s.update_rule)>=updates.size()||u32(s.damage_rule)>=damages.size()){error="Enemy checkpoint callback is unavailable";return false;}put(record+state_offset,0x4518,updates[u32(s.update_rule)]);put(record+state_offset,0x4520,damages[u32(s.damage_rule)]);
  for(u32 i=0;i<8;i++)if(!put_name(record+state_offset+0x4080+i*136,s.interrupts[i].script)||!put_name(record+state_offset+0x40c0+i*136,s.interrupts[i].timeout_script)){error="Enemy checkpoint interrupt name exceeds original field";return false;}
  if(!put_name(record+state_offset+0x44d8,s.death_script)){error="Enemy checkpoint death routine exceeds original field";return false;}
  const auto& mesh=s.distortion_mesh;const u32 columns=mesh.grid.column_count(),rows=mesh.grid.row_count();const bool grid=columns!=0;put(record+state_offset,0x44bc,grid?u32(1):u32(0));
  for(auto handle:s.animation_handles)if(handle&&!tree(handle))return false;
  if(grid){if(columns!=17||rows<2||rows>1024||mesh.grid.vertices.size()!=columns*rows||mesh.grid.sampling.size()!=columns*rows){error="Invalid enemy checkpoint screen grid";return false;}const u32 base=out.size(),fixed=0x1c+(columns-1)*8+columns*rows*40;out.resize(base+fixed,0);auto* data=out.data()+base;put(data,0,columns);put(data,4,rows);for(u32 i=0;i<16;i++)put(data,0x1c+i*4,mesh.strip_handles[i]);const u32 vertices=0x1c+(columns-1)*8;std::memcpy(data+vertices,mesh.grid.vertices.data(),columns*rows*28);std::memcpy(data+vertices+columns*rows*28,mesh.grid.sampling.data(),columns*rows*12);if(!tree(mesh.capture_handle))return false;for(auto handle:mesh.strip_handles)if(!tree(handle))return false;}
  if(!ecl.write_threads(entry.scripts,out,at,out.size())){error=ecl.error;return false;}
 }
 u32 payloads=0;for(const auto& e:entries)for(const auto& s:e.state.shooters.shooters)for(const auto& t:s.transforms)if(!t.payload.empty())payloads++;
 if(payloads){const u32 at=out.size();out.resize(at+8);put(out.data(),at,payload_magic);put(out.data(),at+4,payloads);for(u32 i=0;i<entries.size();i++)for(u32 j=0;j<16;j++)for(u32 k=0;k<18;k++){const auto& p=entries[i].state.shooters.shooters[j].transforms[k].payload;if(p.empty())continue;if(p.size()>65536){error="Enemy checkpoint transform payload exceeds limit";return false;}const u32 at=out.size();out.resize(at+16);put(out.data(),at,i);put(out.data(),at+4,j);put(out.data(),at+8,k);put(out.data(),at+12,u32(p.size()));out.insert(out.end(),p.begin(),p.end());}}
 return true;
}
bool EnemyCheckpoint::read_file(const u8* data,u32 size,u32& consumed){
 error.clear();consumed=0;if(!data||size<0xa8){error="Truncated enemy checkpoint manager";return false;}struct Guard{AnmCheckpoint& pool;AnmCheckpoint::Mark mark;bool committed=false;~Guard(){if(!committed)pool.rollback(mark);}} guard{pool,pool.mark()};std::vector<Entry> next;u32 offset=0xa8;EclFile ecl;
 auto tree=[&](u32& handle)->bool{u32 used=0;handle=pool.read_tree(data+offset,size-offset,used,animations);if(!handle){error=pool.error;return false;}offset+=used;return true;};
 bool more=size>offset&&!(size-offset>=8&&word(data,offset)==payload_magic);
 while(more){if(next.size()>=65536||size-offset<owner_size){error="Truncated enemy checkpoint owner list";return false;}const u32 at=offset;const auto* record=data+at;next.emplace_back();auto& entry=next.back();auto& s=entry.state;fields(s,[&](u32 at,auto& value){get(record+state_offset,at,value);});get(record,0x5740,s.id);get(record,0x5744,s.parent_id);more=word(record,0x14f8)!=0;offset+=owner_size;
  auto update=std::find(updates.begin(),updates.end(),word(record+state_offset,0x4518));auto damage=std::find(damages.begin(),damages.end(),word(record+state_offset,0x4520));if(update==updates.end()||damage==damages.end()){error="Unsupported callback in enemy checkpoint";return false;}s.update_rule=EnemyUpdateRule(update-updates.begin());s.damage_rule=EnemyDamageRule(damage-damages.begin());
  for(u32 i=0;i<8;i++)if(!get_name(record+state_offset+0x4080+i*136,s.interrupts[i].script)||!get_name(record+state_offset+0x40c0+i*136,s.interrupts[i].timeout_script)){error="Unterminated enemy checkpoint interrupt routine";return false;}
  if(!get_name(record+state_offset+0x44d8,s.death_script)){error="Unterminated enemy checkpoint death routine";return false;}
  for(auto& handle:s.animation_handles)if(handle&&!tree(handle))return false;
  if(word(record+state_offset,0x44bc)){if(size-offset<0x1c){error="Truncated enemy checkpoint screen grid";return false;}auto& mesh=s.distortion_mesh;const u32 columns=word(data+offset,0),rows=word(data+offset,4);if(columns!=17||rows<2||rows>1024){error="Invalid enemy checkpoint screen grid dimensions";return false;}const u32 fixed=0x1c+(columns-1)*8+columns*rows*40;if(size-offset<fixed||!mesh.grid.initialize(columns,rows)){error="Truncated enemy checkpoint screen grid vertices";return false;}const u32 vertices=offset+0x1c+(columns-1)*8;std::memcpy(mesh.grid.vertices.data(),data+vertices,columns*rows*28);std::memcpy(mesh.grid.sampling.data(),data+vertices+columns*rows*28,columns*rows*12);offset+=fixed;if(!tree(mesh.capture_handle))return false;for(auto& handle:mesh.strip_handles)if(!tree(handle))return false;s.distortion.active=true;}
  u32 children=0;if(!ecl.read_threads(record,size-at,entry.scripts,manager.program,offset-at,children)){error=ecl.error;return false;}offset+=children;
 }
 if(size-offset>=8&&word(data,offset)==payload_magic){const u32 count=word(data,offset+4);offset+=8;if(count>next.size()*16*18){error="Enemy checkpoint payload count exceeds capacity";return false;}for(u32 i=0;i<count;i++){if(size-offset<16){error="Truncated enemy checkpoint payload header";return false;}const u32 owner=word(data,offset),shooter=word(data,offset+4),transform=word(data,offset+8),length=word(data,offset+12);offset+=16;if(owner>=next.size()||shooter>=16||transform>=18||length>65536||length>size-offset||!next[owner].state.shooters.shooters[shooter].transforms[transform].payload.empty()){error="Invalid enemy checkpoint transform payload";return false;}auto& p=next[owner].state.shooters.shooters[shooter].transforms[transform].payload;p.assign(data+offset,data+offset+length);offset+=length;}}
 for(const auto& e:next)for(const auto& s:e.state.shooters.shooters)for(const auto& t:s.transforms)if(t.type==16777216&&(t.payload.empty()||t.payload.back()!=0)){error="Enemy routine in checkpoint lacks portable string data";return false;}
 get(data,0,integer_registers);get(data,0x10,float_registers);get(data,0x30,counters);get(data,0x3c,boss_ids);get(data,0x7c,manager_flags);get(data,0x80,control);get(data,0x84,next_id);get(data,0x88,total);get(data,0x8c,timer);get(data,0xa0,shot_damage);get(data,0xa4,other_damage);entries=std::move(next);available=true;consumed=offset;guard.committed=true;return true;
}
}
