#include "LaserVisual.hpp"
#include <cmath>
namespace th15 {
bool LaserVisual::tick(AnmVm& vm){if(vm.tick(random,animations.rate)<0){error=vm.error;return false;}return true;}
bool LaserVisual::body_initialize(){const auto* descriptor=bullet_appearance(type);auto* resource=animations.resource(resource_id);if(!descriptor||!resource||color<0||color>=16){error="Laser animation specification unavailable";return false;}
    if(!body.bind(*resource,u32(descriptor->script))){error="Laser body script unavailable";return false;}const auto* source=animations.script_template(resource_id,u32(descriptor->script));body.environment=source?source->environment:nullptr;body.object_host=&animations;body.sprite_source=this;
    if(!tick(body))return false;if((body.visual.render_flags&0xc000)==0x8000)body.visual.render_flags=(body.visual.render_flags&~0x8000u)|0x4000;
    body.pending_interrupt=2;if(!tick(body))return false;body.visual.flags=(body.visual.flags&~0x1c0u)|0x20;body.visual.flags=(body.visual.flags&0xc31fffffu)|0x3000000;body.visual.render_flags=(body.visual.render_flags&~0x80000u)|0x40000;return true;
}
bool LaserVisual::endpoint_initialize(AnmVm& vm,i32 script,bool interrupt,bool blend){if(!animations.bind_template(vm,resource_id,script)){error=animations.error;return false;}vm.visual.translation={};if(!tick(vm))return false;if(interrupt){vm.pending_interrupt=2;if(!tick(vm))return false;}if(blend)vm.visual.flags=(vm.visual.flags&~0x1c0u)|0x20;vm.visual.render_flags=(vm.visual.render_flags&~0x80000u)|0x40000;return true;}
bool LaserVisual::initialize_moving(i32 sprite,i32 colour){type=sprite;color=colour;curve_source=false;if(!body_initialize()||!endpoint_initialize(head,color+56,true,true))return false;head.visual.flags=(head.visual.flags&0xc3ffffffu)|0x2000000;const bool small=type<=17||type==38;return endpoint_initialize(tip,color+(small?91:83),false,small);}
bool LaserVisual::initialize_stationary(i32 sprite,i32 colour){type=sprite;color=colour;curve_source=false;if(!body_initialize()||!endpoint_initialize(head,color+56,true,true))return false;head.visual.flags=(head.visual.flags&0xc3ffffffu)|0x2000000;return true;}
bool LaserVisual::initialize_curved(i32 sprite,i32 colour){
    type=sprite;color=colour;curve_source=true;auto* resource=animations.resource(resource_id);if(!resource||type<0||type>=44||color<0||color>=16){error="Curve animation specification unavailable";return false;}
    const i32 script=type==1?314:wrapping_add(type,134);if(!body.bind(*resource,u32(script))){error="Curve animation script unavailable";return false;}const auto* source=animations.script_template(resource_id,u32(script));body.environment=source?source->environment:nullptr;body.object_host=&animations;body.sprite_source=type==1?nullptr:this;
    if(!tick(body))return false;if((body.visual.render_flags&0xc000)==0x8000)body.visual.render_flags=(body.visual.render_flags&~0x8000u)|0x4000;body.pending_interrupt=2;if(!tick(body))return false;body.visual.flags=(body.visual.flags&~0x1c0u)|0x20;body.visual.flags=(body.visual.flags&0xc31fffffu)|0x3000000;body.visual.render_flags=(body.visual.render_flags&~0x80000u)|0x40000;
    if(!endpoint_initialize(head,color+56,true,true))return false;head.visual.flags=(head.visual.flags&0xc3ffffffu)|0x2000000;return true;
}
bool LaserVisual::update_curved(){return tick(body)&&tick(head);}
bool LaserVisual::draw_curved(const CurveLaserMotion& motion,AnmRenderer& renderer){
    const Vec2 position=body.environment?Vec2{float(body.environment->screen_offsets[0]),float(body.environment->screen_offsets[1])}:Vec2{};if(!curve_strip(motion.points.data(),u32(motion.points.size()),motion.render_width,position,{body.visual.uv[0].y,body.visual.uv[2].y},curve_vertices)){error="Curve drawing point count invalid";return false;}
    if(renderer.draw_screen_strip(body,curve_vertices.data(),u32(curve_vertices.size()))<-1){error=renderer.error;return false;}if(!motion.points.empty()&&i32(motion.points.size())>=motion.path_age.current){head.variables.position=motion.points.back().position;if(renderer.draw(head)<-1){error=renderer.error;return false;}}return true;
}
bool LaserVisual::rebind_body(i32 sprite,i32 colour){const auto* appearance=bullet_appearance(sprite);if(!appearance){error="Laser replacement animation type unavailable";return false;}if(!animations.bind_template(body,resource_id,wrapping_add(appearance->script,colour))){error=animations.error;return false;}return tick(body);}
bool LaserVisual::update(float width,float length,float traveled,bool moving){if(!body.sprite){error="Laser body sprite unavailable";return false;}body.visual.flags|=8;body.visual.scale.x=float(width/body.sprite->width);body.visual.scale.y=float(length/body.sprite->height);if(!tick(body))return false;if(traveled==0&&!tick(head))return false;return !moving||tick(tip);}
bool LaserVisual::draw_moving(const MovingLaserMotion& motion,AnmRenderer& renderer){body.variables.position=motion.position;body.variables.rotation.z=normalize_angle(float(motion.angle+1.5707963705062866f));body.visual.flags|=4;if(renderer.draw(body)<-1){error=renderer.error;return false;}
    tip.variables.position={float(motion.position.x+float(std::cos(double(motion.angle))*double(motion.length))),float(motion.position.y+float(std::sin(double(motion.angle))*double(motion.length))),0};if(renderer.draw(tip)<-1){error=renderer.error;return false;}if(motion.traveled==0){head.variables.position=motion.position;if(renderer.draw(head)<-1){error=renderer.error;return false;}}return true;}
bool LaserVisual::draw_stationary(const StationaryLaserMotion& motion,AnmRenderer& renderer){body.variables.position=motion.position;body.variables.rotation.z=normalize_angle(float(motion.angle+1.5707963705062866f));body.visual.flags|=4;if(renderer.draw(body)<-1){error=renderer.error;return false;}if(motion.traveled==0){head.variables.position=motion.position;if(renderer.draw(head)<-1){error=renderer.error;return false;}}return true;}
}
