// Generated purple section names; locale order zh-CN, en-US, ja-JP.
#pragma once
namespace th15 {
struct PracticeSectionLabel {int id;const char* names[5][3];};
inline constexpr PracticeSectionLabel practice_section_labels[]{
 {1,{{"道中一非","Mid Nonspell 1","道中 通常1"},{"道中一非","Mid Nonspell 1","道中 通常1"},{"道中一非","Mid Nonspell 1","道中 通常1"},{"道中一非","Mid Nonspell 1","道中 通常1"},{"","",""}}},
 {2,{{"道中二非","Mid Nonspell 2","道中 通常2"},{"道中二非","Mid Nonspell 2","道中 通常2"},{"道中二非","Mid Nonspell 2","道中 通常2"},{"道中二非","Mid Nonspell 2","道中 通常2"},{"","",""}}},
 {3,{{"","",""},{"","",""},{"凶弹「高速撞击」","Evil Bullet \"Speed Strike\"","凶弾「スピードストライク」"},{"凶弹「高速撞击」","Evil Bullet \"Speed Strike\"","凶弾「スピードストライク」"},{"","",""}}},
 {4,{{"关底一非","Boss Nonspell 1","ボス 通常1"},{"关底一非","Boss Nonspell 1","ボス 通常1"},{"关底一非","Boss Nonspell 1","ボス 通常1"},{"关底一非","Boss Nonspell 1","ボス 通常1"},{"","",""}}},
 {5,{{"弹符「射鹰」","Bullet Sign \"Eagle Shooting\"","弾符「イーグルシューティング」"},{"弹符「射鹰」","Bullet Sign \"Eagle Shooting\"","弾符「イーグルシューティング」"},{"弹符「射鹰」","Bullet Sign \"Eagle Shooting\"","弾符「イーグルシューティング」"},{"弹符「鹰已击中」","Bullet Sign \"The Eagle Has Shot Its Target\"","弾符「鷹は撃ち抜いた」"},{"","",""}}},
 {6,{{"关底二非","Boss Nonspell 2","ボス 通常2"},{"关底二非","Boss Nonspell 2","ボス 通常2"},{"关底二非","Boss Nonspell 2","ボス 通常2"},{"关底二非","Boss Nonspell 2","ボス 通常2"},{"","",""}}},
 {7,{{"铳符「月狂之枪」","Gun Sign \"Lunatic Gun\"","銃符「ルナティックガン」"},{"铳符「月狂之枪」","Gun Sign \"Lunatic Gun\"","銃符「ルナティックガン」"},{"铳符「月狂之枪」","Gun Sign \"Lunatic Gun\"","銃符「ルナティックガン」"},{"铳符「月狂之枪」","Gun Sign \"Lunatic Gun\"","銃符「ルナティックガン」"},{"","",""}}},
 {8,{{"道中一非","Mid Nonspell 1","道中 通常1"},{"道中一非","Mid Nonspell 1","道中 通常1"},{"道中一非","Mid Nonspell 1","道中 通常1"},{"道中一非","Mid Nonspell 1","道中 通常1"},{"","",""}}},
 {9,{{"关底一非","Boss Nonspell 1","ボス 通常1"},{"关底一非","Boss Nonspell 1","ボス 通常1"},{"关底一非","Boss Nonspell 1","ボス 通常1"},{"关底一非","Boss Nonspell 1","ボス 通常1"},{"","",""}}},
 {10,{{"兔符「草莓团子」","Rabbit Sign \"Strawberry Dango\"","兎符「ストロベリーダンゴ」"},{"兔符「草莓团子」","Rabbit Sign \"Strawberry Dango\"","兎符「ストロベリーダンゴ」"},{"兔符「浆果浆果团子」","Rabbit Sign \"Berry Berry Dango\"","兎符「ベリーベリーダンゴ」"},{"兔符「浆果浆果团子」","Rabbit Sign \"Berry Berry Dango\"","兎符「ベリーベリーダンゴ」"},{"","",""}}},
 {11,{{"关底二非","Boss Nonspell 2","ボス 通常2"},{"关底二非","Boss Nonspell 2","ボス 通常2"},{"关底二非","Boss Nonspell 2","ボス 通常2"},{"关底二非","Boss Nonspell 2","ボス 通常2"},{"","",""}}},
 {12,{{"兔符「团子影响力」","Rabbit Sign \"Dango Influence\"","兎符「ダンゴインフリューエンス」"},{"兔符「团子影响力」","Rabbit Sign \"Dango Influence\"","兎符「ダンゴインフリューエンス」"},{"兔符「团子影响力」","Rabbit Sign \"Dango Influence\"","兎符「ダンゴインフリューエンス」"},{"兔符「团子影响力」","Rabbit Sign \"Dango Influence\"","兎符「ダンゴインフリューエンス」"},{"","",""}}},
 {13,{{"关底三非","Boss Nonspell 3","ボス 通常3"},{"关底三非","Boss Nonspell 3","ボス 通常3"},{"关底三非","Boss Nonspell 3","ボス 通常3"},{"关底三非","Boss Nonspell 3","ボス 通常3"},{"","",""}}},
 {14,{{"月见「九月的满月」","Moon-Viewing \"September Full Moon\"","月見「セプテンバーフルムーン」"},{"月见「九月的满月」","Moon-Viewing \"September Full Moon\"","月見「セプテンバーフルムーン」"},{"月见「九月的满月」","Moon-Viewing \"September Full Moon\"","月見「セプテンバーフルムーン」"},{"月见酒「月狂的九月」","Moon-Viewing Saké \"Lunatic September\"","月見酒「ルナティックセプテンバー」"},{"","",""}}},
 {15,{{"道中一非","Mid Nonspell 1","道中 通常1"},{"道中一非","Mid Nonspell 1","道中 通常1"},{"道中一非","Mid Nonspell 1","道中 通常1"},{"道中一非","Mid Nonspell 1","道中 通常1"},{"","",""}}},
 {16,{{"梦符「绯红色的噩梦」","Dream Sign \"Scarlet Nightmare\"","夢符「緋色の悪夢」"},{"梦符「绯红色的噩梦」","Dream Sign \"Scarlet Nightmare\"","夢符「緋色の悪夢」"},{"梦符「绯红色的压迫噩梦」","Dream Sign \"Scarlet Oppressive Nightmare\"","夢符「緋色の圧迫悪夢」"},{"梦符「绯红色的压迫噩梦」","Dream Sign \"Scarlet Oppressive Nightmare\"","夢符「緋色の圧迫悪夢」"},{"","",""}}},
 {17,{{"关底一非","Boss Nonspell 1","ボス 通常1"},{"关底一非","Boss Nonspell 1","ボス 通常1"},{"关底一非","Boss Nonspell 1","ボス 通常1"},{"关底一非","Boss Nonspell 1","ボス 通常1"},{"","",""}}},
 {18,{{"梦符「蔚蓝色的愁梦」","Dream Sign \"Indigo Dream of Anxiety\"","夢符「藍色の愁夢」"},{"梦符「蔚蓝色的愁梦」","Dream Sign \"Indigo Dream of Anxiety\"","夢符「藍色の愁夢」"},{"梦符「蔚蓝色的愁三重梦」","Dream Sign \"Indigo Three-Layered Dream of Anxiety\"","夢符「藍色の愁三重夢」"},{"梦符「愁永远之梦」","Dream Sign \"Eternally Anxious Dream\"","夢符「愁永遠の夢」"},{"","",""}}},
 {19,{{"关底二非","Boss Nonspell 2","ボス 通常2"},{"关底二非","Boss Nonspell 2","ボス 通常2"},{"关底二非","Boss Nonspell 2","ボス 通常2"},{"关底二非","Boss Nonspell 2","ボス 通常2"},{"","",""}}},
 {20,{{"梦符「刈安色的迷梦」","Dream Sign \"Ochre Confusion\"","夢符「刈安色の迷夢」"},{"梦符「刈安色的迷梦」","Dream Sign \"Ochre Confusion\"","夢符「刈安色の迷夢」"},{"梦符「刈安色的错综迷梦」","Dream Sign \"Ochre Labyrinthine Confusion\"","夢符「刈安色の錯綜迷夢」"},{"梦符「刈安色的错综迷梦」","Dream Sign \"Ochre Labyrinthine Confusion\"","夢符「刈安色の錯綜迷夢」"},{"","",""}}},
 {21,{{"关底三非","Boss Nonspell 3","ボス 通常3"},{"关底三非","Boss Nonspell 3","ボス 通常3"},{"关底三非","Boss Nonspell 3","ボス 通常3"},{"关底三非","Boss Nonspell 3","ボス 通常3"},{"","",""}}},
 {22,{{"梦符「捕梦网」","Dream Sign \"Dream Catcher\"","夢符「ドリームキャッチャー」"},{"梦符「捕梦网」","Dream Sign \"Dream Catcher\"","夢符「ドリームキャッチャー」"},{"梦符「苍蓝色的捕梦网」","Dream Sign \"Azure Dream Catcher\"","夢符「蒼色のドリームキャッチャー」"},{"梦符「梦我梦中」","Dream Sign \"Losing Oneself in a Dream\"","夢符「夢我夢中」"},{"","",""}}},
 {23,{{"月符「绀色的狂梦」","Moon Sign \"Ultramarine Lunatic Dream\"","月符「紺色の狂夢」"},{"月符「绀色的狂梦」","Moon Sign \"Ultramarine Lunatic Dream\"","月符「紺色の狂夢」"},{"月符「绀色的狂梦」","Moon Sign \"Ultramarine Lunatic Dream\"","月符「紺色の狂夢」"},{"月符「绀色的狂梦」","Moon Sign \"Ultramarine Lunatic Dream\"","月符「紺色の狂夢」"},{"","",""}}},
 {24,{{"道中一非","Mid Nonspell 1","道中 通常1"},{"道中一非","Mid Nonspell 1","道中 通常1"},{"道中一非","Mid Nonspell 1","道中 通常1"},{"道中一非","Mid Nonspell 1","道中 通常1"},{"","",""}}},
 {25,{{"关底一非","Boss Nonspell 1","ボス 通常1"},{"关底一非","Boss Nonspell 1","ボス 通常1"},{"关底一非","Boss Nonspell 1","ボス 通常1"},{"关底一非","Boss Nonspell 1","ボス 通常1"},{"","",""}}},
 {26,{{"玉符「乌合之咒」","Orb Sign \"Disorderly Flock's Curse\"","玉符「烏合の呪」"},{"玉符「乌合之咒」","Orb Sign \"Disorderly Flock's Curse\"","玉符「烏合の呪」"},{"玉符「乌合的逆咒」","Orb Sign \"Disorderly Flock's Reverse Curse\"","玉符「烏合の逆呪」"},{"玉符「乌合的二重咒」","Orb Sign \"Disorderly Flock's Duplex Curse\"","玉符「烏合の二重呪」"},{"","",""}}},
 {27,{{"关底二非","Boss Nonspell 2","ボス 通常2"},{"关底二非","Boss Nonspell 2","ボス 通常2"},{"关底二非","Boss Nonspell 2","ボス 通常2"},{"关底二非","Boss Nonspell 2","ボス 通常2"},{"","",""}}},
 {28,{{"玉符「秽身探知型水雷」","Orb Sign \"Impure Body Detection Mines\"","玉符「穢身探知型機雷」"},{"玉符「秽身探知型水雷」","Orb Sign \"Impure Body Detection Mines\"","玉符「穢身探知型機雷」"},{"玉符「秽身探知型水雷　改」","Orb Sign \"Impure Body Detection Mines V2\"","玉符「穢身探知型機雷　改」"},{"玉符「秽身探知型水雷　改」","Orb Sign \"Impure Body Detection Mines V2\"","玉符「穢身探知型機雷　改」"},{"","",""}}},
 {29,{{"关底三非","Boss Nonspell 3","ボス 通常3"},{"关底三非","Boss Nonspell 3","ボス 通常3"},{"关底三非","Boss Nonspell 3","ボス 通常3"},{"关底三非","Boss Nonspell 3","ボス 通常3"},{"","",""}}},
 {30,{{"玉符「众神的弹冠」","Orb Sign \"Shotgun Coronation of the Gods\"","玉符「神々の弾冠」"},{"玉符「众神的弹冠」","Orb Sign \"Shotgun Coronation of the Gods\"","玉符「神々の弾冠」"},{"玉符「众神的光辉弹冠」","Orb Sign \"Shining Shotgun Coronation of the Gods\"","玉符「神々の光り輝く弾冠」"},{"玉符「众神的光辉弹冠」","Orb Sign \"Shining Shotgun Coronation of the Gods\"","玉符「神々の光り輝く弾冠」"},{"","",""}}},
 {31,{{"「孤翼的白鹭」","\"One-Winged White Heron\"","「片翼の白鷺」"},{"「孤翼的白鹭」","\"One-Winged White Heron\"","「片翼の白鷺」"},{"「孤翼的白鹭」","\"One-Winged White Heron\"","「片翼の白鷺」"},{"「孤翼的白鹭」","\"One-Winged White Heron\"","「片翼の白鷺」"},{"","",""}}},
 {32,{{"It's lunatic time！","It's lunatic time！","It's lunatic time！"},{"It's lunatic time！","It's lunatic time！","It's lunatic time！"},{"It's lunatic time！","It's lunatic time！","It's lunatic time！"},{"It's lunatic time！","It's lunatic time！","It's lunatic time！"},{"","",""}}},
 {33,{{"关底一非","Boss Nonspell 1","ボス 通常1"},{"关底一非","Boss Nonspell 1","ボス 通常1"},{"关底一非","Boss Nonspell 1","ボス 通常1"},{"关底一非","Boss Nonspell 1","ボス 通常1"},{"","",""}}},
 {34,{{"狱符「地狱日食」","Hell Sign \"Hell Eclipse\"","獄符「ヘルエクリプス」"},{"狱符「地狱日食」","Hell Sign \"Hell Eclipse\"","獄符「ヘルエクリプス」"},{"狱符「地狱之蚀」","Hell Sign \"Eclipse of Hell\"","獄符「地獄の蝕」"},{"狱符「地狱之蚀」","Hell Sign \"Eclipse of Hell\"","獄符「地獄の蝕」"},{"","",""}}},
 {35,{{"关底二非","Boss Nonspell 2","ボス 通常2"},{"关底二非","Boss Nonspell 2","ボス 通常2"},{"关底二非","Boss Nonspell 2","ボス 通常2"},{"关底二非","Boss Nonspell 2","ボス 通常2"},{"","",""}}},
 {36,{{"狱符「闪光与条纹」","Hell Sign \"Flash and Stripe\"","獄符「フラッシュアンドストライプ」"},{"狱符「闪光与条纹」","Hell Sign \"Flash and Stripe\"","獄符「フラッシュアンドストライプ」"},{"狱符「星与条纹」","Hell Sign \"Star and Stripe\"","獄符「スターアンドストライプ」"},{"狱符「星与条纹」","Hell Sign \"Star and Stripe\"","獄符「スターアンドストライプ」"},{"","",""}}},
 {37,{{"关底三非","Boss Nonspell 3","ボス 通常3"},{"关底三非","Boss Nonspell 3","ボス 通常3"},{"关底三非","Boss Nonspell 3","ボス 通常3"},{"关底三非","Boss Nonspell 3","ボス 通常3"},{"","",""}}},
 {38,{{"狱炎「擦弹地狱火」","Hellfire \"Graze Inferno\"","獄炎「グレイズインフェルノ」"},{"狱炎「擦弹地狱火」","Hellfire \"Graze Inferno\"","獄炎「グレイズインフェルノ」"},{"狱炎「擦弹地狱火」","Hellfire \"Graze Inferno\"","獄炎「グレイズインフェルノ」"},{"狱炎「擦弹的狱意」","Hellfire \"Infernal Essence of Grazing\"","獄炎「かすりの獄意」"},{"","",""}}},
 {39,{{"地狱「条纹状的深渊」","Inferno \"Striped Abyss\"","地獄「ストライプドアビス」"},{"地狱「条纹状的深渊」","Inferno \"Striped Abyss\"","地獄「ストライプドアビス」"},{"地狱「条纹状的深渊」","Inferno \"Striped Abyss\"","地獄「ストライプドアビス」"},{"地狱「条纹状的深渊」","Inferno \"Striped Abyss\"","地獄「ストライプドアビス」"},{"","",""}}},
 {40,{{"「伪阿波罗」","\"Fake Apollo\"","「フェイクアポロ」"},{"「伪阿波罗」","\"Fake Apollo\"","「フェイクアポロ」"},{"「伪阿波罗」","\"Fake Apollo\"","「フェイクアポロ」"},{"「阿波罗捏造说」","\"Apollo Hoax Theory\"","「アポロ捏造説」"},{"","",""}}},
 {41,{{"流星雨","Stars","流星雨"},{"流星雨","Stars","流星雨"},{"流星雨","Stars","流星雨"},{"流星雨","Stars","流星雨"},{"","",""}}},
 {42,{{"关底一非","Boss Nonspell 1","ボス 通常1"},{"关底一非","Boss Nonspell 1","ボス 通常1"},{"关底一非","Boss Nonspell 1","ボス 通常1"},{"关底一非","Boss Nonspell 1","ボス 通常1"},{"","",""}}},
 {43,{{"「掌上的纯光」","\"Pure Light of the Palm\"","「掌の純光」"},{"「掌上的纯光」","\"Pure Light of the Palm\"","「掌の純光」"},{"「掌上的纯光」","\"Pure Light of the Palm\"","「掌の純光」"},{"「掌上的纯光」","\"Pure Light of the Palm\"","「掌の純光」"},{"","",""}}},
 {44,{{"关底二非","Boss Nonspell 2","ボス 通常2"},{"关底二非","Boss Nonspell 2","ボス 通常2"},{"关底二非","Boss Nonspell 2","ボス 通常2"},{"关底二非","Boss Nonspell 2","ボス 通常2"},{"","",""}}},
 {45,{{"「杀意的百合」","\"Murderous Lilies\"","「殺意の百合」"},{"「杀意的百合」","\"Murderous Lilies\"","「殺意の百合」"},{"「杀意的百合」","\"Murderous Lilies\"","「殺意の百合」"},{"「杀意的百合」","\"Murderous Lilies\"","「殺意の百合」"},{"","",""}}},
 {46,{{"关底三非","Boss Nonspell 3","ボス 通常3"},{"关底三非","Boss Nonspell 3","ボス 通常3"},{"关底三非","Boss Nonspell 3","ボス 通常3"},{"关底三非","Boss Nonspell 3","ボス 通常3"},{"","",""}}},
 {47,{{"「原始的神灵界」","\"Primordial Divine Spirit World\"","「原始の神霊界」"},{"「原始的神灵界」","\"Primordial Divine Spirit World\"","「原始の神霊界」"},{"「现代的神灵界」","\"Modern Divine Spirit World\"","「現代の神霊界」"},{"「现代的神灵界」","\"Modern Divine Spirit World\"","「現代の神霊界」"},{"","",""}}},
 {48,{{"关底四非","Boss Nonspell 4","ボス 通常4"},{"关底四非","Boss Nonspell 4","ボス 通常4"},{"关底四非","Boss Nonspell 4","ボス 通常4"},{"关底四非","Boss Nonspell 4","ボス 通常4"},{"","",""}}},
 {49,{{"「战栗的寒冷之星」","\"Trembling, Shivering Star\"","「震え凍える星」"},{"「战栗的寒冷之星」","\"Trembling, Shivering Star\"","「震え凍える星」"},{"「战栗的寒冷之星」","\"Trembling, Shivering Star\"","「震え凍える星」"},{"「战栗的寒冷之星」","\"Trembling, Shivering Star\"","「震え凍える星」"},{"","",""}}},
 {50,{{"「纯粹的狂气」","\"Pristine Lunacy\"","「純粋なる狂気」"},{"「纯粹的狂气」","\"Pristine Lunacy\"","「純粋なる狂気」"},{"「纯粹的狂气」","\"Pristine Lunacy\"","「純粋なる狂気」"},{"「纯粹的狂气」","\"Pristine Lunacy\"","「純粋なる狂気」"},{"","",""}}},
 {51,{{"「溢出的瑕秽」","\"Overflowing Blemishes\"","「溢れ出る瑕穢」"},{"「溢出的瑕秽」","\"Overflowing Blemishes\"","「溢れ出る瑕穢」"},{"「溢出的瑕秽」","\"Overflowing Blemishes\"","「溢れ出る瑕穢」"},{"「地上秽的纯化」","\"Refinement of Earthen Impurity\"","「地上穢の純化」"},{"","",""}}},
 {52,{{"纯符「单纯的子弹地狱」","Pure Sign \"Purely Bullet Hell\"","純符「ピュアリーバレットヘル」"},{"纯符「单纯的子弹地狱」","Pure Sign \"Purely Bullet Hell\"","純符「ピュアリーバレットヘル」"},{"纯符「纯粹的弹幕地狱」","Pure Sign \"A Pristine Danmaku Hell\"","純符「純粋な弾幕地獄」"},{"纯符「纯粹的弹幕地狱」","Pure Sign \"A Pristine Danmaku Hell\"","純符「純粋な弾幕地獄」"},{"","",""}}},
 {53,{{"","",""},{"","",""},{"","",""},{"","",""},{"蝴蝶「取而代之的蝴蝶」","Butterfly \"Butterfly Supplantation\"","胡蝶「バタフライサプランテーション」"}}},
 {54,{{"","",""},{"","",""},{"","",""},{"","",""},{"超特急「梦幻快车」","Super-Express \"Dream Express\"","超特急「ドリームエクスプレス」"}}},
 {55,{{"","",""},{"","",""},{"","",""},{"","",""},{"爬梦「爬行的子弹」","Crawling Dream \"Creeping Bullet\"","這夢「クリーピングバレット」"}}},
 {56,{{"","",""},{"","",""},{"","",""},{"","",""},{"关底一非","Boss Nonspell 1","ボス 通常1"}}},
 {57,{{"","",""},{"","",""},{"","",""},{"","",""},{"异界「逢魔之刻」","Otherworld \"Ōmagatoki\"","異界「逢魔ガ刻」"}}},
 {58,{{"","",""},{"","",""},{"","",""},{"","",""},{"关底二非","Boss Nonspell 2","ボス 通常2"}}},
 {59,{{"","",""},{"","",""},{"","",""},{"","",""},{"地球「邪秽在身」","Earth \"Impurity Within One's Body\"","地球「邪穢在身」"}}},
 {60,{{"","",""},{"","",""},{"","",""},{"","",""},{"关底三非","Boss Nonspell 3","ボス 通常3"}}},
 {61,{{"","",""},{"","",""},{"","",""},{"","",""},{"月「阿波罗反射镜」","Moon \"Apollo Reflection Mirror\"","月「アポロ反射鏡」"}}},
 {62,{{"","",""},{"","",""},{"","",""},{"","",""},{"关底四非","Boss Nonspell 4","ボス 通常4"}}},
 {63,{{"","",""},{"","",""},{"","",""},{"","",""},{"「用于逼死瓮中鼠的单纯弹幕」","\"Simple Danmaku for Cornering a Trapped Rat\"","「袋の鼠を追い詰める為の単純な弾幕」"}}},
 {64,{{"","",""},{"","",""},{"","",""},{"","",""},{"关底五非","Boss Nonspell 5","ボス 通常5"}}},
 {65,{{"","",""},{"","",""},{"","",""},{"","",""},{"异界「地狱的非理想弹幕」","Otherworld \"Hell's Non-Ideal Danmaku\"","異界「地獄のノンイデアル弾幕」"}}},
 {66,{{"","",""},{"","",""},{"","",""},{"","",""},{"关底六非","Boss Nonspell 6","ボス 通常6"}}},
 {67,{{"","",""},{"","",""},{"","",""},{"","",""},{"地球「落向地狱的雨」","Earth \"Rain Falling in Hell\"","地球「地獄に降る雨」"}}},
 {68,{{"","",""},{"","",""},{"","",""},{"","",""},{"关底七非","Boss Nonspell 7","ボス 通常7"}}},
 {69,{{"","",""},{"","",""},{"","",""},{"","",""},{"月「月狂冲击」","Moon \"Lunatic Impact\"","月「ルナティックインパクト」"}}},
 {70,{{"","",""},{"","",""},{"","",""},{"","",""},{"关底八非","Boss Nonspell 8","ボス 通常8"}}},
 {71,{{"","",""},{"","",""},{"","",""},{"","",""},{"「用于杀人的纯粹弹幕」","\"Pristine Danmaku for Killing a Person\"","「人を殺める為の純粋な弾幕」"}}},
 {72,{{"","",""},{"","",""},{"","",""},{"","",""},{"「三位一体论狂想曲」","\"Trinitarian Rhapsody\"","「トリニタリアンラプソディ」"}}},
 {73,{{"","",""},{"","",""},{"","",""},{"","",""},{"「最初与最后的无名弹幕」","\"First and Last Nameless Danmaku\"","「最初で最後の無名の弾幕」"}}},
 {74,{{"底力测试","ab test","ab test"},{"底力测试","ab test","ab test"},{"底力测试","ab test","ab test"},{"底力测试","ab test","ab test"},{"","",""}}},
};
}
