// Development-only observation of the original saved-file boundary.
import{writeFileSync,mkdirSync}from 'node:fs';import{resolve}from 'node:path';import{oracle,root,sha}from '../../tests/cpp/helpers.mjs';
const m=await oracle(),manager=m.allocate(0x33b54),directory=resolve(root,'artifacts/cpp/analysis/score');mkdirSync(directory,{recursive:true});let writes=[];
try{
 m.view(0x503d86,1)[0]=0;m.u32(0x4e9a48,0xabcd1234);m.u32(0x4e9a4c,5432);m.replace(0x490f2b,'working directory boundary',()=>0);m.replace(0x402db0,'no previous score file boundary',()=>0,1);
 m.call(0x45dbd0,{ecx:manager});m.u32(0x4e9bc8,manager);
 const initial=Buffer.from(m.bytes(manager+8,0x33b4c)),rng=Buffer.from(m.bytes(0x4e9a48,8));writeFileSync(resolve(directory,'original-default-state.bin'),initial);
 m.replace(0x403130,'score file creation boundary',()=>{m.u32(0x4e0ef0,777);return 0;});
 const writeAddress=m.u32(0x4be09c),entry=m.importMap.get(writeAddress);m.importMap.set(writeAddress,{...entry,argc:5,handler:()=>{const sp=m.reg('ESP'),size=m.u32(sp+12);if(m.u32(sp+4)!==777)throw Error('Unexpected score file handle');writes.push(Buffer.from(m.bytes(m.u32(sp+8),size)));m.u32(m.u32(sp+16),size);return 1;}});
 const closeAddress=m.u32(0x4be088),close=m.importMap.get(closeAddress);m.importMap.set(closeAddress,{...close,argc:1,handler:()=>1});
 if(m.call(0x45df50,{limit:1000000000})!==0||writes.length!==2)throw Error('Original score write failed');const bytes=Buffer.concat(writes);writeFileSync(resolve(directory,'original-default-scoreth15.dat'),bytes);const saved=Buffer.from(m.bytes(manager+8,0x33b4c));writeFileSync(resolve(directory,'original-saved-state.bin'),saved);
 const restored=m.allocate(0x33b54),source=m.allocate(bytes.length);m.write(restored,Buffer.from(m.bytes(manager,0x33b54)));m.write(source,bytes);m.u32(restored,source);m.u32(restored+4,0);if(m.call(0x45ddd0,{ecx:restored,limit:1000000000})!==0)throw Error('Original score reopen failed');const reopened=Buffer.from(m.bytes(restored+8,0x33b4c));if(!reopened.equals(saved))throw Error('Original saved-file round trip differs');
 const report={originalFunctions:['0x45dbd0','0x45d7a0','0x45db10','0x45df50','0x45ddd0'],initialBytes:initial.length,initialSha256:sha(initial),rng:rng.toString('hex'),fileBytes:bytes.length,fileSha256:sha(bytes),savedSha256:sha(saved),header:bytes.subarray(0,24).toString('hex'),blocks:Array.from({length:5},(_,i)=>({kind:'CR',index:i,magic:saved.readUInt32LE(i*0xa4a0),checksum:saved.readUInt32LE(i*0xa4a0+4),length:saved.readUInt32LE(i*0xa4a0+8),id:saved.readUInt32LE(i*0xa4a0+12)})).concat([{kind:'ST',offset:0x33720,magic:saved.readUInt32LE(0x33720),length:saved.readUInt32LE(0x33728)}]),scope:'Native saved-file boundary and full initialized file/state bytes; file I/O and working directory isolated. Production saved-file codec and runtime record objects remain to implement.'};writeFileSync(resolve(directory,'probe.json'),JSON.stringify(report,null,2)+String.fromCharCode(10));console.log(JSON.stringify(report,null,2));
}finally{m.close();}
