import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,writeFile,readdir} from 'node:fs/promises';
import {resolve} from 'node:path';
import {launchBrowser} from '../../../th10_web/scripts/native/browser-launch.mjs';
import {root,sha,report} from '../cpp/helpers.mjs';
const testPointdevice=process.env.TH15_APPLICATION_POINTDEVICE==='1';
const testRetry=process.env.TH15_APPLICATION_RETRY==='1';
const testTransition=process.env.TH15_APPLICATION_TRANSITION==='1'||testRetry;
const assets=(await readdir(resolve(root,'reference/assets'))).filter(n=>!n.endsWith('.dat'));
const fonts=(await readdir(resolve(root,'assets/sdl-native/fonts'))).filter(n=>n.endsWith('.bin'));
const songs=(await readdir(resolve(root,'assets/music'))).filter(n=>n.endsWith('.ogg'));
test('TH15 real application enters Legacy or Pointdevice gameplay from title and pauses without gameplay overrides',async()=>{
 const files=new Map([['/module.mjs',resolve(root,'artifacts/sdl-application/th15-application.mjs')],['/th15-application.wasm',resolve(root,'artifacts/sdl-application/th15-application.wasm')],...assets.map(n=>['/assets/'+n,resolve(root,'reference/assets',n)]),...fonts.map(n=>['/fonts/'+n,resolve(root,'assets/sdl-native/fonts',n)]),...songs.map(n=>['/music/'+n,resolve(root,'assets/music',n)])]);
 const html='<!doctype html><title>TH15 application integration development</title><canvas id="canvas" width="640" height="480"></canvas><script type="module">import create from "/module.mjs";window.fixture=await create({canvas:document.querySelector("canvas")});</script>';
 const server=createServer(async(req,res)=>{try{const path=new URL(req.url,'http://localhost').pathname;res.setHeader('Cross-Origin-Opener-Policy','same-origin');res.setHeader('Cross-Origin-Embedder-Policy','require-corp');if(path==='/'){res.setHeader('Content-Type','text/html');res.end(html);return;}const file=files.get(path);if(!file){res.writeHead(404).end();return;}res.setHeader('Content-Type',path.endsWith('.mjs')?'text/javascript':path.endsWith('.wasm')?'application/wasm':'application/octet-stream');res.end(await readFile(file));}catch(e){res.writeHead(500).end(String(e));}});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;const errors=[],observations=[];
 try{
  browser=await launchBrowser({args:['--enable-unsafe-swiftshader','--autoplay-policy=no-user-gesture-required']});const page=await browser.newPage();page.on('pageerror',e=>errors.push(String(e)));const url='http://127.0.0.1:'+server.address().port+'/';const prepare=async()=>{await page.goto(url);await page.waitForFunction(()=>window.fixture,{timeout:90000});
  await page.evaluate(async({assets,fonts,songs})=>{const c=fixture;for(const dir of ['assets','fonts','music'])c.FS.mkdir('/'+dir);for(const [dir,names] of [['assets',assets],['fonts',fonts],['music',songs]])for(const name of names){const response=await fetch('/'+dir+'/'+name);if(!response.ok)throw Error('Missing '+name);c.FS.writeFile('/'+dir+'/'+name,new Uint8Array(await response.arrayBuffer()));}c.FS.mkdir('/save');c.FS.mount(c.IDBFS,{},'/save');await new Promise((ok,no)=>c.FS.syncfs(true,e=>e?no(e):ok()));},{assets,fonts,songs});};await prepare();
  const inspect=async kind=>{const value=await page.evaluate(kind=>{const c=fixture;const decode=p=>new TextDecoder().decode(c.HEAPU8.subarray(p,c.HEAPU8.indexOf(0,p)));const p=c._application_pixels();return{kind,state:Array.from(c.HEAP32.subarray(c._application_state()/4,c._application_state()/4+16)),error:decode(c._application_error()),music:decode(c._application_music()),checkpoint:Array.from(c.HEAP32.subarray(c._application_checkpoint_state()/4,c._application_checkpoint_state()/4+9)),transition:Array.from(c.HEAP32.subarray(c._application_transition_state()/4,c._application_transition_state()/4+9)),manual:Array.from(c.HEAP32.subarray(c._application_manual_state()/4,c._application_manual_state()/4+5)),pixels:Array.from(c.HEAPU8.subarray(p,p+640*480*4))};},kind);const pixels=Buffer.from(value.pixels);delete value.pixels;value.sha256=sha(pixels);value.visible=0;for(let p=0;p<pixels.length;p+=4)if(pixels[p]||pixels[p+1]||pixels[p+2])value.visible++;await page.locator('canvas').screenshot({path:resolve(root,'artifacts/cpp/verification/application-'+kind+'.png')});observations.push(value);await writeFile(resolve(root,'artifacts/cpp/verification/application-observed.json'),JSON.stringify(observations,null,2));return value;};
  const boot=()=>{const c=fixture;window.decode=p=>new TextDecoder().decode(c.HEAPU8.subarray(p,c.HEAPU8.indexOf(0,p)));window.state=()=>Array.from(c.HEAP32.subarray(c._application_state()/4,c._application_state()/4+16));window.step=(held=0,pressed=0,repeated=0)=>{if(!c._application_step(held,pressed,repeated,60,0))throw Error(decode(c._application_error())||'Application stopped '+state());return state();};window.waitTitle=(screen,limit=250)=>{for(let n=0;n<limit;n++){const s=step();if(s[0]===0&&s[8]===screen&&s[9]===2)return s;}throw Error('Title timed out '+state());};window.choose=(cursor,screen)=>{c._application_title_select(cursor);step(1,1);return waitTitle(screen);};if(!c._application_initialize(0))throw Error(decode(c._application_error()));waitTitle(1);};await page.evaluate(boot);
  let observed=await inspect('title');assert.equal(observed.music,'th15_01.wav');assert.ok(observed.visible>50000);
  await page.evaluate(pointdevice=>{choose(0,5);choose(pointdevice?0:1,6);choose(1,7);fixture._application_title_select(0);step(1,1);for(let n=0;n<250;n++){const s=step();if(s[0]===1)break;}if(state()[0]!==1)throw Error('Game did not enter '+state());},testPointdevice);
  observed=await inspect('entry');assert.equal(observed.state[12]&0x300,testPointdevice?0x100:0);assert.equal(observed.state[9],2);assert.equal(observed.state[10],3);
  await page.evaluate(pointdevice=>{for(let n=0;n<(pointdevice?200:900);n++)step(1,n===0?1:0);},testPointdevice);observed=await inspect('gameplay');assert.equal(observed.state[0],1);assert.ok(observed.state[5]>=(testPointdevice?100:800));if(testPointdevice){assert.equal(observed.checkpoint[0],1);assert.ok(observed.checkpoint[7]>96);}assert.equal(observed.music,'th15_02.wav');assert.ok(observed.visible>50000);
  await page.evaluate(()=>{step(0x100,0x100);for(let n=0;n<20;n++)step();});observed=await inspect('pause');assert.equal(observed.state[14],1);assert.ok(observed.visible>50000);const pausedFrame=observed.state[5];await page.evaluate(()=>{for(let n=0;n<10;n++)step();});assert.equal((await inspect('pause-still')).state[5],pausedFrame);
  await page.evaluate(pointdevice=>{for(let n=0;n<(pointdevice?2:3);n++)step(0x20,0x20);step(1,1);for(let n=0;n<45;n++)step();},testPointdevice);observed=await inspect('pause-manual');assert.equal(observed.manual[0],1);assert.equal(observed.manual[1],1);assert.equal(observed.manual[4],32);assert.equal(observed.state[5],pausedFrame);
  await page.evaluate(()=>{step(1,1);for(let n=0;n<30;n++)step();});observed=await inspect('pause-manual-page');assert.equal(observed.manual[1],4);assert.equal(observed.state[5],pausedFrame);assert.ok(observed.visible>50000);
  await page.evaluate(()=>{step(2,2);for(let n=0;n<25;n++)step();step(2,2);for(let n=0;n<45;n++)step();});observed=await inspect('pause-manual-closed');assert.equal(observed.manual[0],-1);assert.equal(observed.state[14],1);assert.equal(observed.state[5],pausedFrame);
  await page.evaluate(()=>{step(0x100,0x100);for(let n=0;n<20;n++)step();});observed=await inspect('resumed');assert.equal(observed.state[14],0);assert.ok(observed.state[5]>pausedFrame);
  if(testTransition){
   await page.evaluate(()=>{if(!fixture._application_complete_stage())throw Error(decode(fixture._application_error()));step();});observed=await inspect('stage2-entry');assert.equal(observed.state[2],2);assert.equal(observed.transition[5],1);assert.ok(observed.transition[3]>=0);
   await page.evaluate(()=>{for(let n=0;n<145;n++)step(1);});observed=await inspect('stage2-transition');assert.equal(observed.state[2],2);assert.equal(observed.transition[5],1);assert.ok(observed.transition[4]>0);assert.ok(observed.transition[1]>0);
   await page.evaluate(()=>{for(let n=0;n<100;n++)step(1);});observed=await inspect('stage2-running');assert.equal(observed.state[2],2);assert.equal(observed.transition[5],0);assert.equal(observed.transition[3],-1);assert.equal(observed.state[6]&0x800,0);assert.equal(observed.music,'th15_03.wav');assert.ok(observed.state[5]>30);assert.ok(observed.visible>50000);
  }
  if(testRetry){
   await page.evaluate(()=>{step(2,2);for(let n=0;n<12;n++)step();});observed=await inspect('retry-before');assert.equal(observed.state[2],2);assert.equal(observed.state[10],2,'actual second-stage bomb consumed');
   await page.evaluate(()=>{step(0x100,0x100);for(let n=0;n<32;n++)step();for(let n=0;n<4;n++){step(0x20,0x20);step();}step(1,1);for(let n=0;n<35;n++)step();step(0x10,0x10);step();step(1,1);for(let n=0;n<100;n++)step();});observed=await inspect('retry-entered');assert.equal(observed.state[0],1);assert.equal(observed.state[2],1,'Legacy retry starts the selected run at stage one');assert.equal(observed.state[10],3,'retry resets spent bomb stock');assert.equal(observed.state[11],100,'retry resets stage-one power');assert.equal(observed.state[13],0);assert.equal(observed.music,'th15_02.wav');
  }
  await page.evaluate(()=>{step(0x100,0x100);for(let n=0;n<20;n++)step();step(0x10000,0x10000);waitTitle(1);for(let n=0;n<20;n++)step();});observed=await inspect('returned-title');assert.equal(observed.state[0],0);assert.equal(observed.music,'th15_01.wav');assert.equal(observed.manual[0],-1);assert.ok(observed.visible>50000);
  if(testPointdevice){
   const stored=await page.evaluate(async()=>{const c=fixture;const bytes=c.FS.readFile('/save/autosave/save0_1.dat');await new Promise((ok,no)=>c.FS.syncfs(false,e=>e?no(e):ok()));c._application_close();return Array.from(bytes);});assert.ok(stored.length>96,'actual Pointdevice checkpoint written');await prepare();await page.evaluate(boot);
   await page.evaluate(()=>{choose(0,5);choose(0,6);choose(1,7);choose(0,21);fixture._application_title_select(0);step(1,1);for(let n=0;n<350;n++){const s=step();if(s[0]===1&&s[12]===0x100&&s[5]>0)break;}if(state()[0]!==1)throw Error('Resume did not enter '+state());});observed=await inspect('pointdevice-reloaded');assert.equal(observed.state[0],1);assert.equal(observed.state[12]&0x300,0x100);assert.equal(observed.checkpoint[0],1);assert.equal(observed.checkpoint[2],0);assert.equal(observed.checkpoint[3],1);assert.ok(observed.checkpoint[7]>96);assert.ok(observed.checkpoint[8]>0);await page.evaluate(()=>{for(let n=0;n<300;n++)step(1);});observed=await inspect('pointdevice-continued');assert.equal(observed.state[0],1);assert.ok(observed.visible>50000);
  }
  assert.deepEqual(errors,[]);report(testRetry?'sdl-application-retry':testPointdevice?'sdl-application-pointdevice':testTransition?'sdl-application-transition':'sdl-application',{testRetry,testTransition,testPointdevice,passed:true,completeGame:false,wasmSha256:sha(await readFile(resolve(root,'artifacts/sdl-application/th15-application.wasm'))),observations,scope:(testPointdevice?'Actual IDBFS flush, fresh page/Wasm and title ContinuePrompt reopen a real nine-module checkpoint; resumed battle executes another 300 frames. ':'')+'Real application title to normal Reimu stage 1, original stock/power/collision/scripts, staged OGG, shared SDL3/WebGL2 compositor and actual pause/resume GPU captures. No invulnerability/full-power/automatic boss kill. Optional transition test invokes the actual completion controller directly and verifies retained outgoing/current background owners and stage music; this is controlled scene integration, not a natural full-stage clear or independent native full-run comparison. All-stage natural clears/replays/endings and final launcher remain unverified.'});await page.evaluate(()=>fixture._application_close());
 }finally{await browser?.close();await new Promise(r=>server.close(r));}
});
