import test from 'node:test';import assert from 'node:assert/strict';import{createServer}from'node:http';import{readFile,writeFile,readdir}from'node:fs/promises';import{resolve}from'node:path';import{launchBrowser}from'../../../th10_web/scripts/native/browser-launch.mjs';import{root,report,sha}from'../cpp/helpers.mjs';
test('Application sprite transparency survives initial title, game entry and title return at both physical scales',{timeout:600000},async()=>{
 const label=process.env.TH15_ALPHA_LABEL||'alpha-hotfix';assert.match(label,/^[a-z0-9-]+$/);
 const songs=(await readdir(resolve(root,'assets/music'))).filter(n=>n.endsWith('.ogg'));
 const output=process.env.TH15_ALPHA_MODULE||'artifacts/sdl-application',files=new Map([['/module.mjs',resolve(root,output,'th15-application.mjs')],['/th15-application.wasm',resolve(root,output,'th15-application.wasm')],['/data',resolve(root,'artifacts/alpha-hotfix-candidate/site/packages/th15/th15.data')],['/index',resolve(root,'artifacts/alpha-hotfix-candidate/site/runtime/th15/th15.data.json')],...songs.map(n=>['/music/'+n,resolve(root,'assets/music',n)])]);
 const html='<!doctype html><canvas id="canvas" width="640" height="480"></canvas><script type="module">import create from "/module.mjs";window.fixture=await create({canvas:document.querySelector("canvas")});</script>';
 const server=createServer(async(req,res)=>{try{const path=new URL(req.url,'http://localhost').pathname;res.setHeader('Cross-Origin-Opener-Policy','same-origin');res.setHeader('Cross-Origin-Embedder-Policy','require-corp');if(path==='/'){res.setHeader('Content-Type','text/html');res.end(html);return;}const file=files.get(path);if(!file){res.writeHead(404).end();return;}res.setHeader('Content-Type',path.endsWith('.mjs')?'text/javascript':path.endsWith('.wasm')?'application/wasm':'application/octet-stream');res.end(await readFile(file));}catch(e){res.writeHead(500).end(String(e));}});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;const errors=[],observations=[];
 try{browser=await launchBrowser();for(const scale of [1,2]){const page=await browser.newPage();page.on('pageerror',e=>errors.push(String(e)));await page.goto('http://127.0.0.1:'+server.address().port+'/');await page.waitForFunction(()=>window.fixture,{timeout:90000});
 await page.evaluate(async({scale,songs})=>{const c=fixture,data=new Uint8Array(await(await fetch('/data')).arrayBuffer()),index=await(await fetch('/index')).json();for(const dir of ['/fonts','/music','/save'])c.FS.mkdir(dir);for(const f of index.files)c.FS.writeFile(f.filename,data.subarray(f.start,f.end));for(const name of songs)c.FS.writeFile('/music/'+name,new Uint8Array(await(await fetch('/music/'+name)).arrayBuffer()));c._application_render_scale(scale);window.decode=p=>new TextDecoder().decode(c.HEAPU8.subarray(p,c.HEAPU8.indexOf(0,p)));window.state=()=>Array.from(c.HEAP32.subarray(c._application_state()/4,c._application_state()/4+16));window.step=(held=0,pressed=0)=>{if(!c._application_step(held,pressed,0,60,0))throw Error(decode(c._application_error())||'Application stopped');return state();};window.frames=n=>{for(let i=0;i<n;i++)step();};window.key=k=>{step(k,k);step();};window.waitMenu=screen=>{for(let i=0;i<350;i++){const s=step();if(s[0]===0&&s[8]===screen&&s[9]===2)return;}throw Error('Menu missing '+screen+' '+state());};window.choose=(cursor,screen)=>{c._application_title_select(cursor);key(1);waitMenu(screen);};if(!c._application_initialize(0))throw Error(decode(c._application_error()));waitMenu(1);frames(20);},{scale,songs});
 const probe=async scene=>{const samples=await page.evaluate(()=>{const p=fixture._application_test_alpha_pixels();if(!p)throw Error('Application alpha probe failed');return [26,66,106].map(x=>Array.from(fixture.HEAPU8.subarray(p+(26*640+x)*4,p+(26*640+x)*4+4)));});const expected=[[64,48,32,255],[52,64,76,191],[40,80,120,255]];for(let i=0;i<3;i++)for(let channel=0;channel<4;channel++)assert.ok(Math.abs(samples[i][channel]-expected[i][channel])<=1,scene+' scale '+scale+' alpha sample '+i+' channel '+channel+' actual='+samples[i]+' expected='+expected[i]);observations.push({scene,scale,samples});await page.evaluate(()=>frames(2));};
 await page.locator('canvas').screenshot({path:resolve(root,'artifacts/cpp/verification/'+label+'-title-'+scale+'x.png'),timeout:120000});await probe('initial-title');
 await page.evaluate(()=>{choose(0,5);choose(1,6);choose(1,7);key(1);for(let i=0;i<250&&state()[0]!==1;i++)step();if(state()[0]!==1)throw Error('Game not entered '+state());frames(100);});await probe('gameplay');
 await page.evaluate(()=>{key(0x100);frames(12);key(0x10000);waitMenu(1);frames(20);});await page.locator('canvas').screenshot({path:resolve(root,'artifacts/cpp/verification/'+label+'-returned-title-'+scale+'x.png'),timeout:120000});await probe('returned-title');await page.evaluate(()=>fixture._application_close());await page.close();console.log('Application transparency passed scale',scale);}
 assert.deepEqual(errors,[]);report('sdl-application-alpha',{passed:true,wasmSha256:sha(await readFile(resolve(root,output,'th15-application.wasm'))),observations,scope:'Actual application state after title initialization, actual normal game entry and pause/Q/title at 640x480 and 1280x960. Public AnmRenderer sprite strip uses inherited blend/alpha state without enabling blending in the probe; zero, partial and opaque alpha pixels are checked against independent over-composition arithmetic. Real title/returned-title screenshots captured before the probe.'});
 }finally{await browser?.close();await new Promise(r=>server.close(r));}
});
