import test from 'node:test';import assert from 'node:assert/strict';import{createServer}from'node:http';import{readFile,writeFile,readdir}from'node:fs/promises';import{resolve}from'node:path';import{launchBrowser}from'../../../th10_web/scripts/native/browser-launch.mjs';import{root,report,sha}from'../cpp/helpers.mjs';
test('Application stage transitions and pause captures preserve the whole playfield at both physical scales',{timeout:600000},async()=>{
 const label=process.env.TH15_ALPHA_LABEL||'alpha-hotfix';assert.match(label,/^[a-z0-9-]+$/);
 const songs=(await readdir(resolve(root,'assets/music'))).filter(n=>n.endsWith('.ogg'));
 const output=process.env.TH15_ALPHA_MODULE||'artifacts/sdl-application',files=new Map([['/module.mjs',resolve(root,output,'th15-application.mjs')],['/th15-application.wasm',resolve(root,output,'th15-application.wasm')],['/data',resolve(root,'artifacts/alpha-hotfix-candidate/site/packages/th15/th15.data')],['/index',resolve(root,'artifacts/alpha-hotfix-candidate/site/runtime/th15/th15.data.json')],...songs.map(n=>['/music/'+n,resolve(root,'assets/music',n)])]);
 const html='<!doctype html><canvas id="canvas" width="640" height="480"></canvas><script type="module">import create from "/module.mjs";window.fixture=await create({canvas:document.querySelector("canvas")});</script>';
 const server=createServer(async(req,res)=>{try{const path=new URL(req.url,'http://localhost').pathname;res.setHeader('Cross-Origin-Opener-Policy','same-origin');res.setHeader('Cross-Origin-Embedder-Policy','require-corp');if(path==='/'){res.setHeader('Content-Type','text/html');res.end(html);return;}const file=files.get(path);if(!file){res.writeHead(404).end();return;}res.setHeader('Content-Type',path.endsWith('.mjs')?'text/javascript':path.endsWith('.wasm')?'application/wasm':'application/octet-stream');res.end(await readFile(file));}catch(e){res.writeHead(500).end(String(e));}});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;const errors=[],observations=[];
 try{browser=await launchBrowser();for(const scale of [1,2]){const page=await browser.newPage();page.on('pageerror',e=>errors.push(String(e)));await page.goto('http://127.0.0.1:'+server.address().port+'/');await page.waitForFunction(()=>window.fixture,{timeout:90000});
 await page.evaluate(async({scale,songs})=>{const c=fixture,data=new Uint8Array(await(await fetch('/data')).arrayBuffer()),index=await(await fetch('/index')).json();for(const dir of ['/fonts','/music','/save'])c.FS.mkdir(dir);for(const f of index.files)c.FS.writeFile(f.filename,data.subarray(f.start,f.end));for(const name of songs)c.FS.writeFile('/music/'+name,new Uint8Array(await(await fetch('/music/'+name)).arrayBuffer()));c._application_render_scale(scale);window.decode=p=>new TextDecoder().decode(c.HEAPU8.subarray(p,c.HEAPU8.indexOf(0,p)));window.state=()=>Array.from(c.HEAP32.subarray(c._application_state()/4,c._application_state()/4+16));window.step=(held=0,pressed=0)=>{if(!c._application_step(held,pressed,0,60,0))throw Error(decode(c._application_error())||'Application stopped');return state();};window.frames=n=>{for(let i=0;i<n;i++)step();};window.key=k=>{step(k,k);step();};window.waitMenu=screen=>{for(let i=0;i<350;i++){const s=step();if(s[0]===0&&s[8]===screen&&s[9]===2)return;}throw Error('Menu missing '+screen+' '+state());};window.choose=(cursor,screen)=>{c._application_title_select(cursor);key(1);waitMenu(screen);};if(!c._application_initialize(0))throw Error(decode(c._application_error()));waitMenu(1);frames(20);},{scale,songs});
 const inspect=async scene=>{const result=await page.evaluate(()=>{const c=fixture,p=c._application_pixels(),pixels=c.HEAPU8;const columns=[];for(let x=324;x<414;x++){let lit=0;for(let y=30;y<452;y++){const at=p+(y*640+x)*4;if(pixels[at]+pixels[at+1]+pixels[at+2]>3)lit++;}columns.push(lit);}return {state:state(),columns};});assert.equal(result.state[0],1);assert.ok(result.columns.every(n=>n>20),scene+' scale '+scale+' has blank right-side columns '+result.columns);observations.push({scene,scale,...result});};
 await page.locator('canvas').screenshot({path:resolve(root,'artifacts/cpp/verification/'+label+'-title-'+scale+'x.png'),timeout:120000});
 await page.evaluate(()=>{choose(0,5);choose(1,6);choose(1,7);key(1);for(let i=0;i<250&&state()[0]!==1;i++)step();if(state()[0]!==1)throw Error('Game not entered '+state());frames(100);});await page.locator('canvas').screenshot({path:resolve(root,'artifacts/cpp/verification/strip-fixed-game-'+scale+'.png')});await page.evaluate(()=>{key(0x100);frames(12);});await page.locator('canvas').screenshot({path:resolve(root,'artifacts/cpp/verification/strip-fixed-pause-'+scale+'.png')});await page.evaluate(()=>{frames(30);key(0x100);frames(30);});await page.evaluate(()=>{fixture._application_complete_stage();frames(650);});await inspect('stage-two-gameplay');await page.locator('canvas').screenshot({path:resolve(root,'artifacts/cpp/verification/strip-fixed-stage2-'+scale+'.png')});await page.evaluate(()=>{key(0x100);frames(30);});await inspect('stage-two-pause');await page.locator('canvas').screenshot({path:resolve(root,'artifacts/cpp/verification/strip-fixed-stage2-pause-'+scale+'.png')});await page.evaluate(()=>{key(0x100);frames(30);});await inspect('stage-two-after-resume');
 await page.evaluate(()=>{fixture._application_close();});await page.close();console.log('Full playfield and pause capture passed scale',scale);}
 assert.deepEqual(errors,[]);report('sdl-application-playfield',{passed:true,wasmSha256:sha(await readFile(resolve(root,output,'th15-application.wasm'))),observations,scope:'Actual application: normal game entry, stage-one completion and retained-background transition to stage two, pause capture and resume at both render scales. Ninety columns across the formerly black right-side strip must each contain visible content, with screenshots. The old module fails this assertion and reproduces the user screenshot.'});
 }finally{await browser?.close();await new Promise(r=>server.close(r));}
});
