import test from'node:test';import assert from'node:assert/strict';import{createServer}from'node:http';import{readFile,writeFile}from'node:fs/promises';import{createHash}from'node:crypto';import{launchBrowser}from'../../../th10_web/scripts/native/browser-launch.mjs';
const project=new URL('../../',import.meta.url),output=new URL('artifacts/sdl-audio/',project),defs=JSON.parse(await readFile(new URL('reference/sound-definitions.json',project),'utf8')),manifest=JSON.parse(await readFile(new URL('assets/music/manifest.json',project),'utf8')),samples=[...new Set(defs.samples.map(v=>v.name)),'thbgm.fmt'];
test('TH15 real SDL3/Vorbis mixer plays all original effects/tracks and preserves loops, pan, pause and device queue',async()=>{
 const files=new Map([['/module.mjs',new URL('th15-audio.mjs',output)],['/th15-audio.wasm',new URL('th15-audio.wasm',output)]]);for(const name of samples)files.set('/assets/'+name,new URL('reference/assets/'+name,project));for(const row of manifest.tracks)files.set('/music/'+row.filename.replace(/\.wav$/,'.ogg'),new URL('assets/music/'+row.filename.replace(/\.wav$/,'.ogg'),project));
 const server=createServer(async(req,res)=>{try{const path=new URL(req.url,'http://localhost').pathname;res.setHeader('Cross-Origin-Opener-Policy','same-origin');res.setHeader('Cross-Origin-Embedder-Policy','require-corp');if(path==='/'){res.setHeader('Content-Type','text/html');res.end('<!doctype html><title>TH15 audio fixture</title><button id="audio">Enable audio</button>');return;}const file=files.get(path);if(!file){res.writeHead(404).end();return;}res.setHeader('Content-Type',path.endsWith('.mjs')?'text/javascript':path.endsWith('.wasm')?'application/wasm':'application/octet-stream');res.end(await readFile(file));}catch(e){res.writeHead(500).end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;const errors=[];
 try{browser=await launchBrowser({args:['--enable-unsafe-swiftshader','--autoplay-policy=no-user-gesture-required']});const page=await browser.newPage();page.on('pageerror',e=>errors.push(String(e)));await page.goto('http://127.0.0.1:'+server.address().port+'/');await page.evaluate(async({samples,tracks})=>{const{default:create}=await import('/module.mjs');const c=window.core=await create({});c.FS.mkdir('/assets');c.FS.mkdir('/music');for(const name of samples)c.FS.writeFile('/assets/'+name,new Uint8Array(await fetch('/assets/'+name).then(r=>r.arrayBuffer())));for(const t of tracks){const name=t.filename.replace(/\.wav$/,'.ogg');c.FS.writeFile('/music/'+name,new Uint8Array(await fetch('/music/'+name).then(r=>r.arrayBuffer())));}window.audioError=()=>{const p=c._audio_error();return new TextDecoder().decode(c.HEAPU8.subarray(p,c.HEAPU8.indexOf(0,p)));};document.querySelector('#audio').onclick=()=>{window.initialized=!!c._audio_initialize(1);};},{samples,tracks:manifest.tracks});await page.click('#audio');assert.equal(await page.evaluate(()=>window.initialized),true,await page.evaluate(()=>audioError()));
 const result=await page.evaluate(({tracks})=>{
 const c=core,decode=p=>new TextDecoder().decode(c.HEAPU8.subarray(p,c.HEAPU8.indexOf(0,p))),stats=()=>{const p=c._audio_statistics();return Array.from(c.HEAPU32.subarray(p/4,p/4+11));};function nameCall(fn,value){const bytes=new TextEncoder().encode(value+'\0'),p=c._malloc(bytes.length);c.HEAPU8.set(bytes,p);const result=c[fn](p);c._free(p);if(!result)throw Error(value+': '+audioError());return result;}
 function energy(blocks=16){let l=0,r=0,peak=0;for(let j=0;j<blocks;j++){const p=c._audio_mix(1024);if(!p)throw Error('Audio mix failed');const pcm=new Float32Array(c.HEAPU8.buffer,p,2048);for(let n=0;n<2048;n+=2){if(!Number.isFinite(pcm[n])||!Number.isFinite(pcm[n+1]))throw Error('Invalid audio PCM');l+=pcm[n]*pcm[n];r+=pcm[n+1]*pcm[n+1];peak=Math.max(peak,Math.abs(pcm[n]),Math.abs(pcm[n+1]));}}return{l,r,peak};}
 const effects=[];for(let id=0;id<77;id++){c._audio_effects_stop(-1);c._audio_enqueue(id,0,0);c._audio_update();effects.push({id,...energy(32)});}c._audio_effects_stop(-1);
 c._audio_enqueue(10,-192,1);c._audio_update();const left=energy();c._audio_effects_stop(-1);c._audio_enqueue(10,192,1);c._audio_update();const right=energy();c._audio_effects_stop(-1);
 c._audio_enqueue(20,0,0);c._audio_update();energy(300);const looping=c._audio_playing(20);c._audio_effects_suspend();const stopped=c._audio_playing(20),stopEnergy=energy();c._audio_effects_resume();const resumed=c._audio_playing(20),resumeEnergy=energy();c._audio_effects_stop(-1);
 const songs=[];for(const row of tracks){nameCall('_audio_music_prepare',row.filename);nameCall('_audio_music_file',row.filename);const playing=energy(128),before=c._audio_current_seconds(),current=decode(c._audio_current_music());c._audio_music_pause(1);const silence=energy(8),after=c._audio_current_seconds();c._audio_music_pause(0);const resumed=energy(64);if(!c._audio_music_seek((row.frames-128)/row.rate))throw Error('Music seek failed '+row.filename);const p=c._audio_mix(512);if(!p)throw Error('Loop boundary mix failed');const cursor=c._audio_current_seconds()*row.rate;songs.push({file:row.filename,current,before,after,playing,silence,resumed,cursor,expected:row.loopFrame+384});}
 c._audio_music_fade(60);for(let n=0;n<60;n++)c._audio_update();const faded=energy();nameCall('_audio_music_file','th15_01');const title=decode(c._audio_current_music());nameCall('_audio_music_file','th128_08');const gameOver=decode(c._audio_current_music());nameCall('_audio_music_file','th15_01');const returnedTitle=decode(c._audio_current_music());c._audio_music_pause(1);c._audio_pump();const queued=stats();c._audio_device_suspend(1);c._audio_device_suspend(0);c._audio_music_pause(0);c._audio_update();c._audio_pump();const enqueue=(code,value,text='')=>{const bytes=new TextEncoder().encode(text+'\0'),p=c._malloc(bytes.length);c.HEAPU8.set(bytes,p);const ok=c._audio_queue_music(code,value,p);c._free(p);if(!ok)throw Error(audioError());};c._audio_music_stop();enqueue(1,0,'th15_02.wav');enqueue(2,0);const queueStates=[];for(let n=0;n<9;n++){c._audio_update();const p=c._audio_queue_state();queueStates.push({state:Array.from(c.HEAPU32.subarray(p/4,p/4+3)),wave:decode(c._audio_current_music())});}const queuedSong=energy(128);enqueue(6,0,'Pause');c._audio_update();const queuePaused=stats(),queuePauseEnergy=energy();enqueue(7,0,'UnPause');c._audio_update();const queueResumed=stats(),queueResumeEnergy=energy();enqueue(1,0,'th15_01.wav');enqueue(2,0);if(!c._audio_finish_requests())throw Error(audioError());const queueTitle=decode(c._audio_current_music());return{queueStates,queuedSong,queuePaused,queuePauseEnergy,queueResumed,queueResumeEnergy,queueTitle,effects,left,right,looping,stopped,stopEnergy,resumed,resumeEnergy,songs,faded,title,gameOver,returnedTitle,queued,final:stats(),error:audioError()};
 },{tracks:manifest.tracks});
 await writeFile(new URL('artifacts/cpp/verification/sdl-audio-observed.json',project),JSON.stringify(result,null,2)+'\n');
 assert.deepEqual(errors,[]);assert.equal(result.error,'');for(const effect of result.effects)assert.ok(effect.l+effect.r>1e-10,'Audible original effect '+effect.id);assert.ok(result.left.l>result.left.r*5&&result.right.r>result.right.l*5,'Original stereo pan');assert.equal(result.looping,1);assert.equal(result.stopped,0);assert.equal(result.resumed,1);assert.equal(result.stopEnergy.l+result.stopEnergy.r,0);assert.ok(result.resumeEnergy.l+result.resumeEnergy.r>0);
 for(const song of result.songs){assert.equal(song.current,song.file);assert.ok(song.playing.l+song.playing.r>1e-8,'Audible '+song.file);assert.equal(song.before,song.after,'Paused cursor '+song.file);assert.equal(song.silence.l+song.silence.r,0,'Paused audio '+song.file);assert.ok(song.resumed.l+song.resumed.r>0);assert.ok(Math.abs(song.cursor-song.expected)<=1.1,'Original PCM loop '+song.file+' '+song.cursor+' '+song.expected);}assert.equal(result.faded.l+result.faded.r,0);assert.equal(result.title,'th15_01.wav');assert.equal(result.gameOver,'th128_08.wav');assert.equal(result.returnedTitle,'th15_01.wav');assert.equal(result.queued[3],0);assert.ok(result.queued[2]>=6144);assert.ok(result.queued[4]>0);assert.equal(result.final[3],0);
 assert.deepEqual(result.queueStates.map(v=>v.state),[[2,0,0],[2,0,1],[2,1,2],[2,1,3],[2,1,4],[2,1,5],[2,1,6],[2,1,7],[0,0,0]]);assert.deepEqual(result.queueStates.map(v=>v.wave),['','','','','','th15_02.wav','th15_02.wav','th15_02.wav','th15_02.wav']);assert.ok(result.queuedSong.l+result.queuedSong.r>0);assert.equal(result.queuePaused[8],1);assert.equal(result.queueResumed[8],0);assert.equal(result.queuePauseEnergy.l+result.queuePauseEnergy.r,0);assert.ok(result.queueResumeEnergy.l+result.queueResumeEnergy.r>0);assert.equal(result.queueTitle,'th15_01.wav');
 const wasm=await readFile(new URL('th15-audio.wasm',output));await writeFile(new URL('artifacts/cpp/verification/sdl-audio.json',project),JSON.stringify({passed:true,completeGame:false,wasmSha256:createHash('sha256').update(wasm).digest('hex'),physicalDevice:false,...result,scope:'Actual SDL3/Vorbis/miniaudio compiled browser fixture with original WAVs and all 18 OGG PCM lengths, source-loop wrap, stereo attenuation, stop/resume looping voice, music pause position, fade, title/GameOver track selection and real SDL stream queue; actual original staged commands through preload/play/pause/resume/title restoration and synchronous completion. Headless desktop Chromium WebAudio; full game scene events and mobile hardware are not yet verified.'},null,2)+'\n');
 }finally{await browser?.close();await new Promise(r=>server.close(r));}
});
