import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,writeFile,readdir} from 'node:fs/promises';
import {resolve} from 'node:path';
import {launchBrowser} from '../../../th10_web/scripts/native/browser-launch.mjs';
import {fileURLToPath} from 'node:url';import {createHash} from 'node:crypto';
const root=fileURLToPath(new URL('../../',import.meta.url)),sha=b=>createHash('sha256').update(b).digest('hex'),report=async(name,data)=>writeFile(resolve(root,'artifacts/'+name+'.json'),JSON.stringify(data,null,2));
const assets=[];
const fonts=(await readdir(resolve(root,'assets/sdl-native/fonts'))).filter(n=>/^(font[0-7]|cp932|blend4444)\.bin$/.test(n));
const songs=[];

test('Pointdevice all six stages survive actual persistent checkpoint cold starts',{timeout:1200000},async()=>{
 const files=new Map([['/th15.dat',process.env.TH15_ORIGINAL_DAT],['/module.mjs',resolve(root,'artifacts/sdl-application/th15-application.mjs')],['/th15-application.wasm',resolve(root,'artifacts/sdl-application/th15-application.wasm')],...assets.map(n=>['/assets/'+n,resolve(root,'reference/assets',n)]),...fonts.map(n=>['/fonts/'+n,resolve(root,'assets/sdl-native/fonts',n)]),...songs.map(n=>['/music/'+n,resolve(root,'assets/music',n)])]);
 const html='<!doctype html><title>TH15 application integration development</title><canvas id="canvas" width="640" height="480"></canvas><script type="module">import create from "/module.mjs";window.fixture=await create({canvas:document.querySelector("canvas")});</script>';
 const server=createServer(async(req,res)=>{try{const path=new URL(req.url,'http://localhost').pathname;res.setHeader('Cross-Origin-Opener-Policy','same-origin');res.setHeader('Cross-Origin-Embedder-Policy','require-corp');if(path==='/'){res.setHeader('Content-Type','text/html');res.end(html);return;}const file=files.get(path);if(!file){res.writeHead(404).end();return;}res.setHeader('Content-Type',path.endsWith('.mjs')?'text/javascript':path.endsWith('.wasm')?'application/wasm':'application/octet-stream');res.end(await readFile(file));}catch(e){res.writeHead(500).end(String(e));}});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;const errors=[],observations=[];
 try{
  browser=await launchBrowser({args:['--enable-unsafe-swiftshader','--autoplay-policy=no-user-gesture-required']});const page=await browser.newPage();page.on('pageerror',e=>errors.push(String(e)));const url='http://127.0.0.1:'+server.address().port+'/';const prepare=async()=>{await page.goto(url);await page.waitForFunction(()=>window.fixture,{timeout:90000});
  await page.evaluate(async({assets,fonts,songs})=>{const c=fixture;c.FS.writeFile('/th15.dat',new Uint8Array(await(await fetch('/th15.dat')).arrayBuffer()));for(const dir of ['assets','fonts','music'])c.FS.mkdir('/'+dir);for(const [dir,names] of [['assets',assets],['fonts',fonts],['music',songs]])for(const name of names){const response=await fetch('/'+dir+'/'+name);if(!response.ok)throw Error('Missing '+name);c.FS.writeFile('/'+dir+'/'+name,new Uint8Array(await response.arrayBuffer()));}c.FS.mkdir('/save');c.FS.mount(c.IDBFS,{},'/save');await new Promise((ok,no)=>c.FS.syncfs(true,e=>e?no(e):ok()));},{assets,fonts,songs});};


  const setupControls=()=>{const c=fixture;window.decode=p=>new TextDecoder().decode(c.HEAPU8.subarray(p,c.HEAPU8.indexOf(0,p)));window.state=()=>Array.from(c.HEAP32.subarray(c._application_state()/4,c._application_state()/4+16));window.checkpoint=()=>Array.from(c.HEAP32.subarray(c._application_checkpoint_state()/4,c._application_checkpoint_state()/4+9));window.step=(held=0,pressed=0)=>{if(!c._application_step(held,pressed,0,60,0))throw Error(decode(c._application_error())+' state='+state());return state();};window.frames=n=>{for(let i=0;i<n;i++)step();};window.key=k=>{step(k,k);step();};window.waitMenu=(screen,limit=350)=>{for(let n=0;n<limit;n++){const s=step();if(s[0]===0&&s[8]===screen&&s[9]===2)return s;}throw Error('Menu timed out '+screen+' '+state());};window.choose=(cursor,screen)=>{c._application_title_select(cursor);key(1);return waitMenu(screen);};c._application_test_music_enabled(0);if(!c._application_initialize(0))throw Error(decode(c._application_error()));waitMenu(1);};
  await prepare();await page.evaluate(setupControls);await page.evaluate(()=>{choose(0,5);choose(0,6);choose(1,7);key(1);for(let n=0;n<250&&state()[0]!==1;n++)step();frames(200);});
  for(let stage=1;stage<=6;stage++){
   const before=await page.evaluate(async stage=>{if(state()[0]!==1||state()[2]!==stage||!checkpoint()[0])throw Error('Checkpoint not ready '+state()+' '+checkpoint());await new Promise((ok,no)=>fixture.FS.syncfs(false,e=>e?no(e):ok()));const bytes=Array.from(fixture.FS.readFile('/save/autosave/save0_1.dat')),value={state:state(),checkpoint:checkpoint(),bytes};fixture._application_close();return value;},stage);
   assert.equal(before.checkpoint[1],stage);assert.ok(before.bytes.length>96);await prepare();const durable=await page.evaluate(()=>Array.from(fixture.FS.readFile('/save/autosave/save0_1.dat')));assert.deepEqual(durable,before.bytes,'IDBFS cold load preserves every saved byte before resume');await page.evaluate(setupControls);
   const resumed=await page.evaluate(()=>{choose(0,5);choose(0,6);choose(1,7);choose(0,21);key(1);for(let n=0;n<350;n++){const s=step();if(s[0]===1&&s[12]===0x100&&s[5]>0)break;}return {state:state(),checkpoint:checkpoint(),music:decode(fixture._application_music()),bytes:Array.from(fixture.FS.readFile('/save/autosave/save0_1.dat'))};});
   assert.equal(resumed.state[0],1);assert.equal(resumed.state[2],stage);assert.equal(resumed.state[12]&0x300,0x100);assert.equal(resumed.checkpoint[0],1);assert.equal(resumed.checkpoint[1],stage);const expected=Buffer.from(before.bytes),actual=Buffer.from(resumed.bytes);actual.copy(expected,8,8,16);if(!(stage===1&&expected.readInt32LE(0x1c)===0))for(const index of[0,stage+1,9])expected.writeInt32LE((expected.readInt32LE(0x20+index*4)+1)|0,0x20+index*4);assert.deepEqual(actual,expected,'original retry counters and timestamp change; all nine checkpoint modules stay intact');delete before.bytes;delete resumed.bytes;
   const after=await page.evaluate(()=>{fixture._application_test_protection(600);frames(300);return {state:state(),checkpoint:checkpoint(),music:decode(fixture._application_music())};});assert.equal(after.state[0],1);assert.equal(after.state[2],stage);assert.equal(after.state[14],0);assert.equal(after.checkpoint[0],1);assert.ok(after.state[5]>resumed.state[5]);observations.push({stage,before,resumed,after});console.log('persistent stage cold start passed',stage);await writeFile(resolve(root,'artifacts/cpp/verification/all-stage-checkpoint-progress.json'),JSON.stringify(observations,null,2));
   if(stage<6)await page.evaluate(()=>{if(!fixture._application_complete_stage())throw Error(decode(fixture._application_error()));step();frames(500);});
  }
  const final=await page.evaluate(()=>{if(!fixture._application_test_capture())throw Error(decode(fixture._application_error()));if(!fixture._application_complete_stage())throw Error(decode(fixture._application_error()));frames(3);return {pending:Array.from(new Float32Array(fixture.HEAPU8.buffer,fixture._application_test_lifecycle(),6))[5],files:fixture.FS.readdir('/save/autosave')};});assert.equal(final.pending,0);assert.ok(!final.files.includes('save0_1.dat'),'A completed run must not recreate its deleted checkpoint');
  assert.deepEqual(errors,[]);report('sdl-application-all-stage-checkpoints',{passed:true,wasmSha256:sha(await readFile(resolve(root,'artifacts/sdl-application/th15-application.wasm'))),observations,scope:'Actual C++ Pointdevice selection, real original stage resources, nine-module checkpoint file, IDBFS flush, new page and new Wasm, native ContinuePrompt and another 300 gameplay frames for each normal stage. Cross-stage completion is controlled through the real completion entry; Test-only protection is applied after exact saved-module checks so unattended player deaths cannot open a game-over menu during controlled transitions; no full power or automatic boss kill. This isolates persistent resume rather than proving natural full-run equivalence.'});await page.evaluate(()=>fixture._application_close());
 }finally{await browser?.close();await new Promise(r=>server.close(r));}
});
