import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,writeFile,readdir} from 'node:fs/promises';
import {resolve} from 'node:path';
import {launchBrowser} from '../../../th10_web/scripts/native/browser-launch.mjs';
import {root,report,sha} from '../cpp/helpers.mjs';
const defs=JSON.parse(await readFile(resolve(root,'reference/sound-definitions.json'),'utf8'));
const samples=[...new Set(defs.samples.map(v=>v.name))];
const assets=[...samples,'thbgm.fmt','text.anm','ascii.anm','effect.anm',];
assets.push(...["e01.anm","e01.msg","e02.anm","e02.msg","e03.anm","e03.msg","e04.anm","e04.msg","e05.anm","e05.msg","e06.anm","e06.msg","e07.anm","e07.msg","e08.anm","e08.msg","staff.anm","staff1.msg","staff2.msg","staff3.msg","staff4.msg","staff5.msg","staff6.msg"]);
const fonts=(await readdir(resolve(root,'assets/sdl-native/fonts'))).filter(v=>v.endsWith('.bin'));
const songs=['th15_14.ogg','th15_15.ogg'];
test('TH15 real SDL3 ending and staff combine original scripts, ANM layers, measured fonts and actual music',async()=>{
 const files=new Map([['/module.mjs',resolve(root,'artifacts/sdl-ending/th15-ending.mjs')],['/th15-ending.wasm',resolve(root,'artifacts/sdl-ending/th15-ending.wasm')],...assets.map(n=>['/assets/'+n,resolve(root,'reference/assets',n)]),...fonts.map(n=>['/fonts/'+n,resolve(root,'assets/sdl-native/fonts',n)]),...songs.map(n=>['/music/'+n,resolve(root,'assets/music',n)])]);
 const html='<!doctype html><title>TH15 SDL ending integration fixture</title><canvas id="canvas" width="640" height="480"></canvas><script type="module">import create from "/module.mjs";window.fixture=await create({canvas:document.querySelector("canvas")});</script>';
 const server=createServer(async(req,res)=>{try{const path=new URL(req.url,'http://localhost').pathname;res.setHeader('Cross-Origin-Opener-Policy','same-origin');res.setHeader('Cross-Origin-Embedder-Policy','require-corp');if(path==='/'){res.setHeader('Content-Type','text/html');res.end(html);return;}const file=files.get(path);if(!file){res.writeHead(404).end();return;}res.setHeader('Content-Type',path.endsWith('.mjs')?'text/javascript':path.endsWith('.wasm')?'application/wasm':'application/octet-stream');res.end(await readFile(file));}catch(e){res.writeHead(500).end(String(e));}});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;const errors=[],observations=[];
 try{browser=await launchBrowser({args:['--enable-unsafe-swiftshader','--autoplay-policy=no-user-gesture-required']});const page=await browser.newPage();page.on('pageerror',e=>errors.push(String(e)));await page.goto('http://127.0.0.1:'+server.address().port+'/');await page.waitForFunction(()=>window.fixture,{timeout:90000});
 await page.evaluate(async({assets,fonts,songs})=>{const c=window.fixture;for(const dir of ['assets','fonts','music'])c.FS.mkdir('/'+dir);for(const[dir,names]of[['assets',assets],['fonts',fonts],['music',songs]])for(const name of names){const r=await fetch('/'+dir+'/'+name);if(!r.ok)throw Error('Missing '+name);c.FS.writeFile('/'+dir+'/'+name,new Uint8Array(await r.arrayBuffer()));}},{assets,fonts,songs});

 const result=[];
 await page.evaluate(()=>{const c=fixture;window.decode=p=>new TextDecoder().decode(c.HEAPU8.subarray(p,c.HEAPU8.indexOf(0,p)));window.state=()=>Array.from(c.HEAP32.subarray(c._ending_state()/4,c._ending_state()/4+12));});
 const capture=async(name)=>{const v=await page.evaluate(()=>{const c=fixture,p=c._ending_pixels();if(!p)throw Error('Ending pixels unavailable');return{state:state(),music:decode(c._ending_music()),error:decode(c._ending_error()),pixels:Array.from(c.HEAPU8.subarray(p,p+640*480*4))};}),bytes=Buffer.from(v.pixels);delete v.pixels;v.sha256=sha(bytes);v.visiblePixels=0;for(let i=0;i<bytes.length;i+=4)if(bytes[i]||bytes[i+1]||bytes[i+2])v.visiblePixels++;await page.locator('canvas').screenshot({path:resolve(root,'artifacts/cpp/verification/sdl-ending-'+name+'.png')});return v;};
 for(const [character,continues,mode,seen]of[[0,0,0,0],[3,1,0,1],[1,0,0x100,1],[2,1,0,0]]){await page.evaluate(({character,continues,mode,seen})=>{if(!fixture._ending_initialize(character,2,continues,mode,seen))throw Error(decode(fixture._ending_error()));},{character,continues,mode,seen});let endingImage=null,staffImage=null,finished=false,energy=0,frames=0;const tracks=new Set;
 for(;frames<16000;frames+=30){const step=await page.evaluate(base=>{const c=fixture;for(let i=0;i<30;i++){const f=base+i;if(!c._ending_step(f%37<29?0x200:1,f%47===0?1:0,f%40)){if(state()[8]>=0)break;throw Error(decode(c._ending_error())||'Ending step failure');}if(state()[8]>=0)break;}return{state:state(),music:decode(c._ending_music())};},frames);tracks.add(step.music);if(!endingImage&&step.state[6]>5&&step.state[7]>0&&!(step.state[4]&2)){endingImage=await capture(character+'-'+mode+'-text');energy=await page.evaluate(()=>{const c=fixture,p=c._ending_audio_mix(44100);if(!p)throw Error('Ending mix unavailable');let result=0;for(const v of new Float32Array(c.HEAPU8.buffer,p,88200)){if(!Number.isFinite(v))throw Error('Invalid ending PCM');result+=v*v;}return result;});}if(!staffImage&&(step.state[4]&2)&&step.state[7]>1){staffImage=await capture(character+'-'+mode+'-staff');}if(step.state[8]>=0){assert.equal(step.state[8],16);finished=true;break;}}assert.ok(finished,'Actual ending reaches results destination');assert.ok(endingImage,'Ending text draw observed');assert.equal(endingImage.error,'');assert.ok(endingImage.visiblePixels>10000);assert.ok(staffImage,'Staff resource drawn');assert.equal(staffImage.error,'');assert.ok(staffImage.visiblePixels>10000);assert.notEqual(endingImage.sha256,staffImage.sha256);assert.ok(energy>1e-8,'Real ending OGG mixed');assert.ok(tracks.has('th15_14.wav'));assert.ok(tracks.has('th15_15.wav'));result.push({character,continues,mode,seen,frames:frames+30,tracks:[...tracks],endingImage,staffImage,energy});await writeFile(resolve(root,'artifacts/cpp/verification/sdl-ending-observed.json'),JSON.stringify({result},null,2));await page.evaluate(()=>fixture._ending_close());}
 assert.deepEqual(errors,[]);report('sdl-ending',{passed:true,completeGame:false,wasmSha256:sha(await readFile(resolve(root,'artifacts/sdl-ending/th15-ending.wasm'))),routes:result,scope:'Actual SDL3/WebGL2 Chromium ending/staff composition, production interpreter and callback restart rules, measured font uploads, original resource changes and actual OGG mixing through result destination. Shake callbacks are recorded at the fixture boundary; full application and mobile hardware remain outside this fixture.'});
 }finally{await browser?.close();await new Promise(r=>server.close(r));}
});
