import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,writeFile,readdir} from 'node:fs/promises';
import {resolve} from 'node:path';
import {launchBrowser} from '../../../th10_web/scripts/native/browser-launch.mjs';
import {root,sha,report} from '../cpp/helpers.mjs';
const assets=(await readdir(resolve(root,'reference/assets'))).filter(n=>!n.endsWith('.dat'));
const fonts=(await readdir(resolve(root,'assets/sdl-native/fonts'))).filter(n=>n.endsWith('.bin'));
const songs=(await readdir(resolve(root,'assets/music'))).filter(n=>n.endsWith('.ogg'));

test('Actual Extra scene can retry after game over, return to title, reopen and replay in one page session at both render scales',{timeout:1200000},async()=>{
 const files=new Map([['/module.mjs',resolve(root,'artifacts/sdl-application/th15-application.mjs')],['/th15-application.wasm',resolve(root,'artifacts/sdl-application/th15-application.wasm')],...assets.map(n=>['/assets/'+n,resolve(root,'reference/assets',n)]),...fonts.map(n=>['/fonts/'+n,resolve(root,'assets/sdl-native/fonts',n)]),...songs.map(n=>['/music/'+n,resolve(root,'assets/music',n)])]);
 const html='<!doctype html><title>TH15 application integration development</title><canvas id="canvas" width="640" height="480"></canvas><script type="module">import create from "/module.mjs";window.fixture=await create({canvas:document.querySelector("canvas")});</script>';
 const server=createServer(async(req,res)=>{try{const path=new URL(req.url,'http://localhost').pathname;res.setHeader('Cross-Origin-Opener-Policy','same-origin');res.setHeader('Cross-Origin-Embedder-Policy','require-corp');if(path==='/'){res.setHeader('Content-Type','text/html');res.end(html);return;}const file=files.get(path);if(!file){res.writeHead(404).end();return;}res.setHeader('Content-Type',path.endsWith('.mjs')?'text/javascript':path.endsWith('.wasm')?'application/wasm':'application/octet-stream');res.end(await readFile(file));}catch(e){res.writeHead(500).end(String(e));}});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;const errors=[],observations=[];
 try{
  browser=await launchBrowser({args:['--enable-unsafe-swiftshader','--autoplay-policy=no-user-gesture-required']});const page=await browser.newPage();page.on('pageerror',e=>errors.push(String(e)));const url='http://127.0.0.1:'+server.address().port+'/';const prepare=async()=>{await page.goto(url);await page.waitForFunction(()=>window.fixture,{timeout:90000});
  await page.evaluate(async({assets,fonts,songs})=>{const c=fixture;for(const dir of ['assets','fonts','music'])c.FS.mkdir('/'+dir);for(const [dir,names] of [['assets',assets],['fonts',fonts],['music',songs]])for(const name of names){const response=await fetch('/'+dir+'/'+name);if(!response.ok)throw Error('Missing '+name);c.FS.writeFile('/'+dir+'/'+name,new Uint8Array(await response.arrayBuffer()));}c.FS.mkdir('/save');c.FS.mount(c.IDBFS,{},'/save');await new Promise((ok,no)=>c.FS.syncfs(true,e=>e?no(e):ok()));},{assets,fonts,songs});};


  for(const scale of [1,2]){
   await prepare();await page.evaluate(scale=>{const c=fixture;window.decode=p=>new TextDecoder().decode(c.HEAPU8.subarray(p,c.HEAPU8.indexOf(0,p)));window.state=()=>Array.from(c.HEAP32.subarray(c._application_state()/4,c._application_state()/4+16));window.pause=()=>Array.from(c.HEAP32.subarray(c._application_pause_state()/4,c._application_pause_state()/4+6));window.step=(held=0,pressed=0)=>{if(!c._application_step(held,pressed,0,60,0))throw Error((decode(c._application_error())||'Application stopped')+' state='+state());return state();};window.frames=n=>{for(let i=0;i<n;i++)step();};window.key=k=>{step(k,k);step();};window.waitMenu=(screen,phase=2,limit=400)=>{for(let n=0;n<limit;n++){const s=step();if(s[0]===0&&s[8]===screen&&s[9]===phase)return s;}throw Error('Menu timed out '+screen+' '+state());};window.choose=(cursor,screen)=>{c._application_title_select(cursor);key(1);return waitMenu(screen);};window.enterExtra=()=>{choose(1,6);key(1);waitMenu(7);key(1);for(let n=0;n<300&&state()[0]!==1;n++)step();if(state()[0]!==1)throw Error('Game entry failed '+state());c._application_test_protection(100000);frames(100);};window.pixelStats=()=>{const p=c._application_pixels(),b=c.HEAPU8.subarray(p,p+640*480*4);let left=0,right=0;for(let y=20;y<460;y++)for(let x=20;x<620;x++){const at=(y*640+x)*4;if(b[at]+b[at+1]+b[at+2]>24){if(x<320)left++;else right++;}}return {left,right,width:document.querySelector('canvas').width,height:document.querySelector('canvas').height};};c._application_render_scale(scale);if(!c._application_initialize(0))throw Error(decode(c._application_error()));waitMenu(1);choose(4,11);for(let i=0;i<3;i++)key(32);for(let i=0;i<3;i++)key(128);for(const k of 'HEARTLAND'){c._application_keyboard_key(k.charCodeAt(0),1);frames(2);c._application_keyboard_key(k.charCodeAt(0),0);frames(2);}key(2);waitMenu(1);enterExtra();},scale);
   console.log('Extra scene ready scale',scale);const observations=await page.evaluate(()=>{let checks=[];for(let cycle=0;cycle<3;cycle++){
     if(!fixture._application_test_game_over())throw Error('Game-over entry failed');for(let n=0;n<180;n++){step();if(pause()[1]===15){fixture._application_test_finish_name();key(1);}if(pause()[1]===6)break;}if(pause()[1]!==6)throw Error('Game-over menu not ready '+pause());for(let n=0;n<5&&pause()[2]!==4;n++)key(32);if(pause()[2]!==4)throw Error('Retry unavailable '+pause());key(1);frames(150);fixture._application_test_protection(100000);frames(100);if(state()[0]!==1||state()[2]!==7)throw Error('Retry left Extra '+state());checks.push({cycle,retry:state(),pixels:pixelStats()});
     key(0x100);const pauseVoice=pause()[5];frames(12);key(0x10000);frames(100);waitMenu(1);const titleMusic=decode(fixture._application_music());enterExtra();checks.push({cycle,reentry:state(),pixels:pixelStats(),pauseVoice,titleMusic});
    }return checks;});for(const item of observations){assert.ok(item.pixels.left>10000&&item.pixels.right>10000,'Both halves have scene contents');assert.equal(item.pixels.width,640*scale);assert.equal(item.pixels.height,480*scale);if(item.reentry){assert.equal(item.titleMusic,'th15_01.wav');assert.equal(item.pauseVoice,1,'Pause sound survives the music suspension');}}
   await page.locator('canvas').screenshot({path:resolve(root,'artifacts/cpp/verification/extra-reentry-'+scale+'x.png')});
   console.log('Extra retries verified scale',scale,observations);const saved=await page.evaluate(()=>{if(!fixture._application_complete_stage())throw Error(decode(fixture._application_error()));for(let n=0;n<1000&&state()[0]===1;n++)step();waitMenu(15);key(1);key(16);key(64);key(1);waitMenu(16);key(1);waitMenu(16,3);key(1);waitMenu(16);const bytes=Array.from(fixture.FS.readFile('/save/replay/th15_01.rpy'));if(fixture.FS.analyzePath('/save/replay/th15_00.rpy').exists)throw Error('New replay still starts from 00');key(2);waitMenu(1);choose(3,12);key(1);waitMenu(12,4);frames(18);key(1);for(let n=0;n<300&&state()[0]!==1;n++)step();frames(150);if(state()[2]!==7||state()[0]!==1)throw Error('Extra replay failed '+state());return {bytes,state:state(),pixels:pixelStats()};});assert.ok(saved.bytes.length>200);assert.equal(saved.state[2],7);await writeFile(resolve(root,'artifacts/cpp/verification/extra-reentry-'+scale+'x.rpy'),Buffer.from(saved.bytes));delete saved.bytes;observations.push({replay:saved});observations.push({scale});await page.evaluate(()=>fixture._application_close());report('sdl-extra-reentry-'+scale+'x',{passed:true,observations,wasmSha256:sha(await readFile(resolve(root,'artifacts/sdl-application/th15-application.wasm'))),scope:'Actual Extra application/menu lifecycle with controlled game over and stage completion. Three retries, three title returns/reentries, completed replay write/read on same page; real GPU pixel contents at 640x480 and 1280x960. Not a natural Extra gameplay parity proof.'});
  }assert.deepEqual(errors,[]);
 }finally{await browser?.close();await new Promise(r=>server.close(r));}
});
