import test from 'node:test';import assert from 'node:assert/strict';import{createServer}from'node:http';import{readFile,writeFile}from'node:fs/promises';import{createHash}from'node:crypto';import{launchBrowser}from'../../../th10_web/scripts/native/browser-launch.mjs';
const project=new URL('../../',import.meta.url),output=new URL('artifacts/sdl-graphics/',project);const html='<!doctype html><meta charset="utf-8"><canvas id="canvas" width="640" height="480"></canvas><script type="module">import factory from "/module.mjs";window.fixture=await factory({canvas:document.querySelector("canvas")});</script>';
test('TH15 actual SDL3/WebGL2 texture sampling, blends, GPU capture and shared streaming',async()=>{
 const files=new Map([['/',()=>Buffer.from(html)],['/module.mjs',()=>readFile(new URL('th15-graphics.mjs',output))],['/th15-graphics.wasm',()=>readFile(new URL('th15-graphics.wasm',output))],['/text.anm',()=>readFile(new URL('reference/assets/text.anm',project))]]);const server=createServer(async(req,res)=>{try{const file=files.get(new URL(req.url,'http://localhost').pathname);if(!file){res.writeHead(404).end();return;}const data=await file();res.writeHead(200,{'Content-Type':req.url.endsWith('.mjs')?'text/javascript':req.url.endsWith('.wasm')?'application/wasm':'text/html','Cross-Origin-Opener-Policy':'same-origin','Cross-Origin-Embedder-Policy':'require-corp'});res.end(data);}catch(e){res.writeHead(500).end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;const errors=[];
 try{browser=await launchBrowser();const page=await browser.newPage();page.on('pageerror',e=>errors.push(String(e)));await page.goto('http://127.0.0.1:'+server.address().port+'/');await page.waitForFunction(()=>window.fixture,{timeout:90000});const data=await page.evaluate(async()=>{
 const c=window.fixture;const string=p=>{let end=p;while(c.HEAPU8[end])++end;return new TextDecoder().decode(c.HEAPU8.subarray(p,end));};if(!c._graphics_initialize())throw Error(string(c._graphics_error()));
 const formats=[1,2,3,4,5,6,7],bytes=[0,4,2,2,3,2,2,1],textures=[],samples=[];let checks=0;
 const packed=(format,n)=>{const a=n*17,r=(n*37)&255,g=(n*71)&255,b=(n*109)&255;return format===6?[(a<<8)|(Math.round(r*7/255)<<5)|(Math.round(g*7/255)<<2)|Math.round(b*3/255)]:format===1?[b,g,r,a]:format===2?[(b>>3)|((g>>3)<<5)|((r>>3)<<10)|(a>=128?0x8000:0)]:format===3?[(b>>3)|((g>>2)<<5)|((r>>3)<<11)]:format===4?[b,g,r]:format===5?[(b>>4)|((g>>4)<<4)|((r>>4)<<8)|((a>>4)<<12)]:[a];};
 const expand=(format,n)=>{const p=packed(format,n);if(format===1)return p;if(format===4)return [...p,255];if(format===7)return[255,255,255,p[0]];if(format===6){const v=p[0];return[(v&3)*85,Math.round((v>>>2&7)*255/7),Math.round((v>>>5&7)*255/7),v>>>8];}const v=p[0];return format===2?[Math.round((v&31)*255/31),Math.round((v>>5&31)*255/31),Math.round((v>>10&31)*255/31),v&0x8000?255:0]:format===3?[Math.round((v&31)*255/31),Math.round((v>>5&63)*255/63),Math.round((v>>11&31)*255/31),255]:[(v&15)*17,(v>>4&15)*17,(v>>8&15)*17,(v>>12&15)*17];};
 const make=(format,w,h,values)=>{const p=c._malloc(values.length);c.HEAPU8.set(values,p);const texture=c._graphics_texture(format,w,h,p,values.length);c._free(p);if(!texture)throw Error(string(c._graphics_error()));return texture;};
 c._graphics_clear(0xff203040);
 for(let f=0;f<formats.length;++f){const format=formats[f],raw=new Uint8Array(16*bytes[format]);for(let i=0;i<16;++i){const p=packed(format,i);if(bytes[format]===2){raw[i*2]=p[0]&255;raw[i*2+1]=p[0]>>>8;}else raw.set(p,i*bytes[format]);}const texture=make(format,4,4,raw);textures.push(texture);const x=(f%3)*160,y=Math.floor(f/3)*160;c._graphics_quad(texture,x,y,128,128,0xffffffff,4,5);for(let i=0;i<16;++i)samples.push({x:x+(i%4)*32+16,y:y+Math.floor(i/4)*32+16,source:expand(format,i)});}
 const ptr=c._graphics_pixels(),pixels=Array.from(c.HEAPU8.subarray(ptr,ptr+640*480*4)),expected=[];for(const sample of samples){const at=(sample.y*640+sample.x)*4,source=sample.source,a=source[3]/255,bg=[64,48,32,255],want=source.map((v,k)=>Math.round(v*a+bg[k]*(1-a)));expected.push({actual:pixels.slice(at,at+4),expected:want});++checks;}
 const capture=make(1,128,128,new Uint8Array(128*128*4));if(!c._graphics_capture(capture,160,0,128,128))throw Error(string(c._graphics_error()));c._graphics_quad(capture,0,320,128,128,0xffffffff,1,0);const pixels2=c._graphics_pixels();for(let i=0;i<16;++i){const x=(i%4)*32+16,y=Math.floor(i/4)*32+16,sourceAt=(y*640+x+160)*4,destAt=((y+320)*640+x)*4;expected.push({actual:Array.from(c.HEAPU8.subarray(pixels2+destAt,pixels2+destAt+4)),expected:pixels.slice(sourceAt,sourceAt+4)});++checks;}
 const packed332=new Uint8Array([0xa5,0x95]),source332=make(6,1,1,packed332),target332=make(6,1,1,new Uint8Array(2));if(!c._graphics_resize(source332,target332,1,1,1,1))throw Error(string(c._graphics_error()));const target332Ptr=c._graphics_read_texture(target332),packed332Result=new DataView(c.HEAPU8.buffer).getUint16(target332Ptr,true);if(packed332Result!==0x95a5)throw Error("RGB332 GPU copy differs: "+packed332Result.toString(16));checks++;
 const all332=new Uint8Array(65536*2);for(let n=0;n<65536;n++){all332[n*2]=n&255;all332[n*2+1]=n>>>8;}const all332Source=make(6,256,256,all332),all332Target=make(6,256,256,new Uint8Array(all332.length));if(!c._graphics_resize(all332Source,all332Target,256,256,256,256))throw Error(string(c._graphics_error()));const all332Read=c._graphics_read_texture(all332Target);for(let n=0;n<all332.length;n++){if(c.HEAPU8[all332Read+n]!==all332[n])throw Error("RGB332 exhaustive GPU copy differs at byte "+n);}checks+=65536;
 const alphaTexture=make(1,1,1,new Uint8Array([40,80,120,128]));const alphaCases=[[1,1,0,0],[1,4,1,0],[0,1,0,0],[1,1,1,4],[0,0,0,2],[1,1,0,0]];for(const [separate,src,dst,equation] of alphaCases){c._graphics_clear(0x60203040);c._graphics_alpha(separate,src,dst,equation);c._graphics_quad(alphaTexture,0,0,32,32,0xffffffff,4,5);const p=c._graphics_pixels(),at=(16*640+16)*4,a=128/255,bg=[64,48,32,96],source=[40,80,120,128];const want=source.map((v,k)=>Math.round(v*a+bg[k]*(1-a)));if(separate)want[3]=equation===4?128:Math.min(255,Math.round(128*(src===1?1:src===4?a:0)+96*(dst===1?1:0)));expected.push({actual:Array.from(c.HEAPU8.subarray(p+at,p+at+4)),expected:want});checks++;}c._graphics_alpha(0,1,0,0);
 c._graphics_clear(0xff203040);c._graphics_depth_quad(0,0,96,64,.2,0xffff0000);c._graphics_depth_quad(0,0,96,64,.8,0xff0000ff);
 const readPixel=(x,y)=>{const p=c._graphics_pixels(),at=(y*640+x)*4;return Array.from(c.HEAPU8.subarray(p+at,p+at+4));};expected.push({actual:readPixel(16,16),expected:[0,0,255,255]});checks++;
 if(!c._graphics_clear_depth(0,0,32,64))throw Error(string(c._graphics_error()));expected.push({actual:readPixel(16,16),expected:[0,0,255,255]});checks++;c._graphics_depth_quad(0,0,96,64,.8,0xff0000ff);expected.push({actual:readPixel(16,16),expected:[255,0,0,255]},{actual:readPixel(48,16),expected:[0,0,255,255]});checks+=2;
 if(!c._graphics_clear_depth(0,0,0,0))throw Error(string(c._graphics_error()));expected.push({actual:readPixel(48,16),expected:[0,0,255,255]});checks++;c._graphics_depth_quad(0,0,96,64,.9,0xff00ff00);expected.push({actual:readPixel(16,16),expected:[0,255,0,255]},{actual:readPixel(48,16),expected:[0,255,0,255]});checks+=2;
 const screenData=new Uint8Array(await(await fetch('/text.anm')).arrayBuffer()),screenPtr=c._malloc(screenData.length);c.HEAPU8.set(screenData,screenPtr);if(!c._graphics_screen_initialize(screenPtr,screenData.length))throw Error(string(c._graphics_screen_error()));c._free(screenPtr);
 const screenSamples=[];for(let frame=0;frame<3;frame++){for(let pass=0;pass<10;pass++){if(!c._graphics_screen_pass(pass))throw Error(string(c._graphics_screen_error()));if(pass===0)c._graphics_screen_paint((0xff112233+frame*0x10101)>>>0);if(pass===3)c._graphics_screen_paint((0xff445566+frame*0x10101)>>>0);if(pass===5)c._graphics_screen_paint(0xff778899);}screenSamples.push({frame,pixels:[[224,240],[136,24],[500,240],[320,400]].map(([x,y])=>({x,y,pixel:readPixel(x,y)}))});}if(!c._graphics_screen_pass(1))throw Error(string(c._graphics_screen_error()));c._graphics_screen_paint(0xff7a4b2c);if(!c._graphics_screen_capture(0))throw Error(string(c._graphics_screen_error()));let snapshot=c._graphics_screen_capture_texture(),screenshot=c._graphics_read_texture(snapshot);if(c._graphics_texture_format(snapshot)!==3)throw Error('Original screenshot must use RGB565');const snapshotPixel=(x,y)=>{const at=screenshot+(y*512+x)*2,n=c.HEAPU8[at]|(c.HEAPU8[at+1]<<8);return [Math.round((n&31)*255/31),Math.round((n>>5&63)*255/63),Math.round((n>>11&31)*255/31),255];};for(const [x,y] of [[0,0],[127,31],[31,127],[255,255]]){const at=(y*256+x)*4;expected.push({actual:snapshotPixel(x,y),expected:[41,77,123,255]});checks++;}
 if(!c._graphics_screen_pass(7))throw Error(string(c._graphics_screen_error()));c._graphics_screen_paint(0xff21496b);if(!c._graphics_screen_capture(1))throw Error(string(c._graphics_screen_error()));if(c._graphics_screen_capture_pending()!==1)throw Error('Result capture must wait for the final frame');screenshot=c._graphics_read_texture(c._graphics_screen_capture_texture());expected.push({actual:snapshotPixel(0,0),expected:[41,77,123,255]});checks++;if(!c._graphics_screen_capture_finish())throw Error(string(c._graphics_screen_error()));if(c._graphics_screen_capture_pending()!==0)throw Error('Result capture queue not drained');screenshot=c._graphics_read_texture(c._graphics_screen_capture_texture());for(const [x,y] of [[0,0],[127,31],[31,127],[255,255]]){const at=(y*256+x)*4;expected.push({actual:snapshotPixel(x,y),expected:[107,73,33,255]});checks++;}expected.push({actual:snapshotPixel(300,300),expected:[0,0,0,255]});checks++;c._graphics_screen_close();
 for(let frame=0;frame<120;++frame){c._graphics_quad(textures[0],480,320,128,128,0xffffffff,4,5);c._graphics_frame();}const stats=Array.from(c.HEAPU32.subarray(c._graphics_stats()>>>2,(c._graphics_stats()>>>2)+18));return {expected,checks,stats,screenSamples,error:string(c._graphics_error())};});
 assert.equal(data.error,'');for(const frame of data.screenSamples)for(const sample of frame.pixels){const expected=sample.x===500?[0,0,0,255]:[51+frame.frame,34+frame.frame,17+frame.frame,255];assert.deepEqual(sample.pixel,expected,'original text.anm composite frame '+frame.frame+' at '+sample.x+','+sample.y);} assert.deepEqual(errors,[]);for(let i=0;i<data.expected.length;++i)for(let channel=0;channel<4;++channel)assert.ok(Math.abs(data.expected[i].actual[channel]-data.expected[i].expected[channel])<=1,'sample '+i+' channel '+channel+' actual '+data.expected[i].actual+' expected '+data.expected[i].expected);assert.equal(data.stats[7],0,'No bufferSubData streaming');assert.ok(data.stats[6]>0);assert.ok(data.stats[9]>0,'Direct game vertices');assert.equal(data.stats[10],0,'No duplicate game batch copies');assert.ok(data.stats[11]<=2,'Fixed vertex layout cached');const wasm=await readFile(new URL('th15-graphics.wasm',output));await writeFile(new URL('artifacts/cpp/verification/sdl-webgl-pixels.json',project),JSON.stringify({passed:true,completeGame:false,wasmSha256:createHash('sha256').update(wasm).digest('hex'),checks:data.checks*4+data.screenSamples.length*16,compositedFrames:data.screenSamples.length,frames:120,stats:data.stats,scope:'Actual SDL3/WebGL2 fixture: seven texture formats, including exact A8/RGB332 storage/readback and shader sampling, A8 shader sampling, source alpha blending and independent alpha factors/equations with cache transitions, GPU surface capture including actual text.anm pause screenshots and deferred result screenshots with frame-end color verification, color-preserving regional/full depth clears with occlusion outside the clear rectangle, all ten compositor phases with original text.anm target/capture scripts across three distinct scene colors, and glBufferData streaming. Desktop Chromium software GPU; complete scenes and mobile hardware are not yet verified.'},null,2)+'\n');
 }finally{await browser?.close();await new Promise(r=>server.close(r));}
});
