import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,readdir,mkdir,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import {analyzeNormalizedWindow} from '../../../third_party/eagler-common/testkit/presentation-lab/analyzer.mjs';
import {launchBrowser} from '../../../th10_web/scripts/native/browser-launch.mjs';
const root=fileURLToPath(new URL('../../',import.meta.url));
test('60/120/144/165/240 Hz RAF retains fixed logical ticks and interpolated presentation submissions', {timeout:600000}, async()=>{
 assert.ok(process.env.TH15_ORIGINAL_DAT,'Set TH15_ORIGINAL_DAT to the private original th15.dat');
 const musicDirectory=process.env.TH15_HIGH_REFRESH_MUSIC;const music=musicDirectory?['th15_01.ogg','th15_02.ogg','th15_04.ogg']:[];
 const fonts=(await readdir(resolve(root,'assets/sdl-native/fonts'))).filter(n=>n.endsWith('.bin'));
 const files=new Map([['/module.mjs',resolve(root,'artifacts/sdl-application/th15-application.mjs')],['/th15-application.wasm',resolve(root,'artifacts/sdl-application/th15-application.wasm')],['/th15.dat',process.env.TH15_ORIGINAL_DAT],...music.map(n=>['/music/'+n,resolve(musicDirectory,n)]),...fonts.map(n=>['/fonts/'+n,resolve(root,'assets/sdl-native/fonts',n)])]);
 const server=createServer(async(req,res)=>{try{const path=new URL(req.url,'http://localhost').pathname;res.setHeader('Cross-Origin-Opener-Policy','same-origin');res.setHeader('Cross-Origin-Embedder-Policy','require-corp');if(path==='/'){res.setHeader('Content-Type','text/html');res.end('<canvas id="canvas" width="1280" height="960"></canvas><script type="module">import create from "/module.mjs";window.rafQueue=[];window.requestAnimationFrame=callback=>(rafQueue.push(callback),rafQueue.length);window.driveRaf=time=>{const callbacks=rafQueue.splice(0);for(const callback of callbacks)callback(time);};window.fixture=await create({canvas:document.querySelector("canvas"),onGameFrame:(ok,ms,ticks)=>{window.events.push({ok,ticks,ms});}});window.events=[];</script>');return;}const file=files.get(path);if(!file){res.writeHead(404).end();return;}res.setHeader('Content-Type',path.endsWith('.mjs')?'text/javascript':path.endsWith('.wasm')?'application/wasm':'application/octet-stream');res.end(await readFile(file));}catch(e){res.writeHead(500).end(String(e));}});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;const errors=[];const output=resolve(root,'artifacts/cpp/verification');await mkdir(output,{recursive:true});
 try{
 const observations=[];
 for(const rate of [60,120,144,165,240]){
 browser=await launchBrowser({args:['--autoplay-policy=no-user-gesture-required']});const page=await browser.newPage();page.on('pageerror',e=>{errors.push(String(e));console.error('Browser error:',String(e));});await page.goto('http://127.0.0.1:'+server.address().port+'/');await page.waitForFunction(()=>window.fixture,null,{timeout:90000});
 await page.evaluate(async ({fonts,music})=>{const c=fixture;c.FS.mkdir('/fonts');c.FS.mkdir('/save');for(const name of fonts)c.FS.writeFile('/fonts/'+name,new Uint8Array(await(await fetch('/fonts/'+name)).arrayBuffer()));c.FS.writeFile('/th15.dat',new Uint8Array(await(await fetch('/th15.dat')).arrayBuffer()));c.FS.mkdir('/music');for(const name of music)c.FS.writeFile('/music/'+name,new Uint8Array(await(await fetch('/music/'+name)).arrayBuffer()));c._th15_music_enabled(+(music.length>0));c._th15_render_scale(2);if(!c._th15_initialize())throw Error('Initialize failed');window.state=()=>Array.from(c.HEAP32.subarray(c._th15_probe_state()/4,c._th15_probe_state()/4+16));window.world=()=>Array.from(c.HEAPU32.subarray(c._th15_probe_world_state()/4,c._th15_probe_world_state()/4+16));window.stats=()=>Array.from(c.HEAPU32.subarray(c._th15_probe_graphics_statistics()/4,c._th15_probe_graphics_statistics()/4+17));window.tick=()=>{if(!c._th15_probe_tick()){const pointer=c._th15_error();throw Error('Tick failed: '+new TextDecoder().decode(c.HEAPU8.subarray(pointer,c.HEAPU8.indexOf(0,pointer))));}};window.frames=n=>{for(let i=0;i<n;i++)tick();};window.key=scan=>{c._th15_key(scan,1);tick();c._th15_key(scan,0);tick();};window.waitMenu=screen=>{for(let n=0;n<350;n++){tick();if(state()[8]===screen&&state()[9]===2)return;}throw Error('Menu timed out '+state());};waitMenu(1);key(28);waitMenu(5);key(28);waitMenu(6);key(28);waitMenu(7);key(28);for(let n=0;n<250&&c._th15_phase()!==1;n++)tick();if(c._th15_phase()!==1)throw Error('Game entry failed');frames(245);c._th15_probe_protection(100000);c._th15_probe_presentation_enable(1);c._th15_key(205,1);tick();tick();c._th15_key(205,0);window.reference=()=>Array.from(new Float32Array(c.HEAPU8.buffer,c._th15_probe_presentation_reference(),5));window.sample=()=>Array.from(new Float32Array(c.HEAPU8.buffer,c._th15_probe_presentation_sample(),3));},{fonts,music});
 const interpolation=await page.evaluate(()=>{const c=fixture,before=world(),ref=reference(),samples=[];const digests=()=>Array.from(c.HEAPU32.subarray(c._th15_probe_checkpoint_digest()/4,c._th15_probe_checkpoint_digest()/4+9));const audio=()=>Array.from(c.HEAPU32.subarray(c._th15_audio_statistics()/4,c._th15_audio_statistics()/4+11)).filter((_,i)=>i!==4);const audioBefore=audio();const bytesBefore=digests();const pixels=()=>{const pointer=c._th15_probe_pixels();let hash=2166136261;for(const byte of c.HEAPU8.subarray(pointer,pointer+640*480*4))hash=Math.imul(hash^byte,16777619);return hash>>>0;};const authoredPixels=pixels();if(!ref[4]||Math.abs(ref[1]-ref[0])<1)throw Error('No moving Player reference '+ref);for(const alpha of [0,.25,.5,.75,1,.5,.5]){if(!c._th15_probe_presentation_draw(alpha))throw Error('Presentation draw failed');const r=reference();if(JSON.stringify(world())!==JSON.stringify(before))throw Error('Draw-only changed world');if(JSON.stringify(audio())!==JSON.stringify(audioBefore))throw Error("Presentation changed audio");const expected=ref[0]+(ref[1]-ref[0])*alpha;if(Math.abs(r[2]-expected)>.001)throw Error('Interpolation mismatch '+JSON.stringify({alpha,r,expected}));samples.push({alpha,x:r[2],state:{checkpoint:digests(),world:world()}});}if(JSON.stringify(digests())!==JSON.stringify(bytesBefore))throw Error('Draw-only changed checkpoint modules');const fault=[];c._th15_probe_presentation_fault(1);for(const alpha of [0,.25,.5,.75,1,.5,.5]){if(!c._th15_probe_presentation_draw(alpha))throw Error('Fault draw failed');fault.push({alpha,x:reference()[2],state:{checkpoint:digests(),world:world()}});}c._th15_probe_presentation_fault(0);if(!c._th15_probe_presentation_draw(1)||pixels()!==authoredPixels)throw Error("Packet alpha=1 differs from original Draw pixels");c._th15_probe_presentation_draw(.5);const halfPixels=pixels();c._th15_probe_presentation_draw(.5);if(pixels()!==halfPixels)throw Error("Repeated alpha is not pixel-idempotent");return {ref,samples,fault,authoredPixels,halfPixels,audioBefore,bytesBefore,world:before,tick:c._th15_frame()};});
 const shake=await page.evaluate(()=>{const c=fixture;c._th15_key(205,1);tick();c._th15_probe_presentation_offset(10,0);tick();c._th15_key(205,0);const ref=reference();if(!ref[4])throw Error("Missing shake reference");const samples=[];for(const alpha of [0,.5,1]){c._th15_probe_presentation_draw(alpha);const actual=reference()[2],expected=ref[0]+(ref[1]-10-ref[0])*alpha+10;if(Math.abs(actual-expected)>.001)throw Error("Shake was interpolated "+JSON.stringify({alpha,ref,actual,expected}));samples.push({alpha,actual});}c._th15_probe_presentation_offset(0,0);tick();return {ref,samples};});
 if(music.length)assert.ok(interpolation.audioBefore[4]<18,"OGG track is active");
 assert.ok(interpolation.samples[1].x!==interpolation.samples[0].x);
 const normalized=(x,tick,alpha)=>({sessionEpoch:1,simulationTick:tick,referenceDrawSerial:tick,alpha,completeness:'incomplete',dropped:0,limitations:['Player submission only; other owner coverage remains unknown'],records:[{ownerId:'player',objectId:'root',generation:interpolation.ref[3],identityConfidence:'proven',coordinateSpace:'screen',lifecycle:{continuous:true},fields:[{id:'vertex.x',value:x,tolerance:.001,interpolationPolicy:'continuous'}]}]});
 const stateEvidence={coverageVersion:'th15/checkpoint-world/1',groups:[{id:'checkpoint-nine-modules',digest:JSON.stringify(interpolation.bytesBefore)},{id:'world-probe',digest:JSON.stringify(interpolation.world)}],missingGroups:['complete-Replay-cursor','title-pause-caption-owners','complete-authoritative-and-rollback-visible-state']};
 const analyze=samples=>analyzeNormalizedWindow({previous:normalized(interpolation.ref[0],interpolation.tick-1),current:normalized(interpolation.ref[1],interpolation.tick),samples:samples.map(row=>normalized(row.x,interpolation.tick,row.alpha)),stateBefore:stateEvidence,statesAfter:samples.map(row=>({...stateEvidence,groups:[{id:'checkpoint-nine-modules',digest:JSON.stringify(row.state.checkpoint)},{id:'world-probe',digest:JSON.stringify(row.state.world)}]})),build:{game:'th15',eaglerCommon:'8316c4f861dedb67e1e0e7be75ddcf0b90f63448'}});
 const normalReport=analyze(interpolation.samples),faultReport=analyze(interpolation.fault);
 assert.equal(normalReport.objects[0].status,'interpolated');assert.equal(normalReport.purityStatus,'unknown');assert.notEqual(faultReport.objects[0].status,'interpolated');
 const value=await page.evaluate(rate=>{const c=fixture;const before=c._th15_frame(),startStats=stats(),samples=[];c._th15_loop_start();driveRaf(0);let unchanged=0;for(let n=1;n<=rate*2;n++){const frame=c._th15_frame(),w=world(),previous=stats();driveRaf(n*1000/rate);const after=stats();if(c._th15_frame()===frame){if(JSON.stringify(world())!==JSON.stringify(w))throw Error('Presentation-only RAF mutated gameplay');if(n>15&&rate>60&&after[5]===previous[5])throw Error('High-refresh RAF did not present');unchanged++;}samples.push(c._th15_frame());}const costs=events.map(e=>e.ms).sort((a,b)=>a-b);const result={cpuSubmission:{median:costs[Math.floor(costs.length*.5)],p95:costs[Math.floor(costs.length*.95)],max:costs.at(-1)},rate,ticks:c._th15_frame()-before,presentations:stats()[5]-startStats[5],unchanged,eventTicks:events.reduce((n,e)=>n+e.ticks,0),events:events.length};c._th15_limit_presentation(1);const lockedFrame=c._th15_frame(),lockedStats=stats()[5];for(let n=1;n<=rate;n++)driveRaf(2000+n*1000/rate);result.lockedTicks=c._th15_frame()-lockedFrame;result.lockedPresentations=stats()[5]-lockedStats;c._th15_loop_pause(1);const paused=c._th15_frame(),pausedStats=stats();for(let n=0;n<10;n++)driveRaf(3000+(n+1)*1000/rate);if(c._th15_frame()!==paused||stats()[5]!==pausedStats[5])throw Error('Suspended loop presented or advanced');c._th15_loop_stop();return result;},rate);
 assert.equal(value.ticks,120);assert.equal(value.eventTicks,120);assert.equal(value.lockedTicks,60);assert.equal(value.lockedPresentations,60);if(rate===60)assert.equal(value.presentations,120);else assert.ok(value.presentations>=rate*2-10);observations.push({...value,interpolation,shake,normalReport,faultReport});console.log(JSON.stringify(value));await page.close();await browser.close();browser=null;
 }
 assert.deepEqual(errors,[]);
 await writeFile(resolve(output,music.length?'high-refresh-cadence-music.json':'high-refresh-cadence.json'),JSON.stringify({passed:true,music:music.length>0,observations,scope:'Actual SDL browser RAF loop, original archive, full Stage 1 state and GPU calls. Presentation-only RAF submits recorded Draw commands without input/simulation. Cadence check only; complete state coverage is a separate gate.'},null,2));
 }finally{await browser?.close();await new Promise(r=>server.close(r));}
});
