import test from 'node:test';import assert from 'node:assert/strict';import{createServer}from'node:http';import{createReadStream}from'node:fs';import{stat,writeFile,readFile}from'node:fs/promises';import{resolve,sep}from'node:path';import{launchBrowser}from'../../../th10_web/scripts/native/browser-launch.mjs';import{root,sha,report}from'../cpp/helpers.mjs';
const site=resolve(root,'artifacts/architecture-preview/site'),evidence=resolve(root,'artifacts/cpp/verification');
test('TH15 final shared launcher uses original archive, real RAF keyboard/touch, native pause replay save and local player files',{timeout:480000},async()=>{
 const server=createServer(async(req,res)=>{try{let name=decodeURIComponent(new URL(req.url,'http://localhost').pathname);if(name==='/')name='/index.html';const file=resolve(site,'.'+name);if(!file.startsWith(site+sep)){res.writeHead(403).end();return;}const s=await stat(file);if(!s.isFile()){res.writeHead(404).end();return;}const ext=name.slice(name.lastIndexOf('.'));res.writeHead(200,{'Content-Type':ext==='.html'?'text/html; charset=utf-8':ext==='.mjs'||ext==='.js'?'text/javascript':ext==='.json'?'application/json':ext==='.css'?'text/css':ext==='.wasm'?'application/wasm':ext==='.png'?'image/png':'application/octet-stream','Content-Length':s.size,'Cross-Origin-Opener-Policy':'same-origin','Cross-Origin-Embedder-Policy':'require-corp'});createReadStream(file).pipe(res);}catch(e){res.writeHead(404).end(String(e));}});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser,page,runtime;const errors=[],observations=[];
 try{
  browser=await launchBrowser({args:['--enable-unsafe-swiftshader','--autoplay-policy=no-user-gesture-required']});page=await browser.newPage();page.on('pageerror',e=>{errors.push(String(e));console.error('browser error:',String(e));});page.on('console',m=>{if(m.type()==='error')console.error('browser console:',m.text());});page.on('requestfailed',r=>console.error('request failed:',r.url(),r.failure()?.errorText));await page.setViewportSize({width:1100,height:800});await page.addInitScript(()=>{localStorage.setItem('eagler-touhou-game-options-v1-th15',JSON.stringify({music:'midi',musicPreferenceExplicit:true,options:{touchEnabled:true,touchMovementMode:'touch',touchSensitivity:100,touchFocusMode:'hold-button',doubleTapBombEnabled:false}}));});await page.goto('http://127.0.0.1:'+server.address().port+'/');await page.locator('#changelogConfirm').click();await page.locator('button[data-game="th15"]').click();await page.locator('#launch').click();await page.waitForFunction(()=>{const frame=document.querySelector('#gameFrame');return !!frame?.contentWindow?.Module?._th15_probe_state?.();},null,{timeout:150000});runtime=page.frames().find(f=>f.url().includes('/runtime/th15/th15.html'));assert.ok(runtime);
  await page.evaluate(()=>{window.testRpc=(command,args={})=>new Promise((ok,no)=>{const frame=document.querySelector('#gameFrame'),request='test-'+crypto.randomUUID();const timer=setTimeout(()=>{window.removeEventListener('message',listen);no(Error('Runtime RPC timed out '+command));},30000);const listen=e=>{if(e.source!==frame.contentWindow||e.origin!==location.origin||e.data?.request!==request)return;clearTimeout(timer);window.removeEventListener('message',listen);e.data.ok?ok(e.data):no(Error(e.data.error));};window.addEventListener('message',listen);frame.contentWindow.postMessage({protocol:'eagler-touhou/1',game:'th15',command,request,...args},location.origin);});});
  const rpc=(command,args={})=>page.evaluate(({command,args})=>window.testRpc(command,args),{command,args});
  const waitTitle=(screen,substate=2)=>runtime.waitForFunction(([screen,substate])=>{const c=Module,p=c._th15_probe_state();if(!p)return false;const s=c.HEAP32.subarray(p/4,p/4+16);return s[0]===0&&s[8]===screen&&s[9]===substate;},[screen,substate],{timeout:45000});
  const waitTicks=async n=>{const before=await runtime.evaluate(()=>Module._th15_frame());await runtime.waitForFunction(frame=>Module._th15_frame()>=frame,before+n,{timeout:30000});};
  // Keep press duration inside the browser so slow host IPC cannot turn a tap into native key repeat.
  const key=async code=>page.evaluate(async code=>{const c=document.querySelector('#gameFrame').contentWindow.Module;const ticks=n=>new Promise((resolve,reject)=>{const target=c._th15_frame()+n,started=performance.now();const check=()=>{if(c._th15_frame()>=target)return resolve();if(performance.now()-started>30000)return reject(Error('Keyboard frame timeout'));setTimeout(check,0);};check();});await window.testRpc('keyboard',{code,down:true});try{await ticks(3);}finally{await window.testRpc('keyboard',{code,down:false});}await ticks(3);},code);
  const state=()=>runtime.evaluate(()=>Array.from(Module.HEAP32.subarray(Module._th15_probe_state()/4,Module._th15_probe_state()/4+16)));
  const pause=()=>runtime.evaluate(()=>Array.from(Module.HEAP32.subarray(Module._th15_probe_pause_state()/4,Module._th15_probe_pause_state()/4+7)));
  const waitPause=(phase,cursor=-1)=>runtime.waitForFunction(([phase,cursor])=>{const c=Module,p=c._th15_probe_pause_state(),s=c.HEAP32.subarray(p/4,p/4+7);return s[1]===phase&&(cursor<0||s[2]===cursor)&&s[6]>=12;},[phase,cursor],{timeout:30000});
  const snapshot=async kind=>{const data=await runtime.evaluate(kind=>{const c=Module,decode=p=>new TextDecoder().decode(c.HEAPU8.subarray(p,c.HEAPU8.indexOf(0,p)));const a=c._th15_probe_state(),b=c._th15_probe_player_state(),d=c._th15_probe_pause_state(),audio=c._th15_audio_statistics();return {kind,state:Array.from(c.HEAP32.subarray(a/4,a/4+16)),player:Array.from(new Float32Array(c.HEAPU8.buffer).subarray(b/4,b/4+10)),pause:Array.from(c.HEAP32.subarray(d/4,d/4+7)),audio:Array.from(c.HEAPU32.subarray(audio/4,audio/4+11)),heapBytes:c.HEAPU8.length,archiveBytes:c.FS.stat('/th15.dat').size,extractedAssets:c.FS.analyzePath('/assets').exists,error:decode(c._th15_error())};},kind);observations.push(data);await writeFile(resolve(evidence,'launcher-observed.json'),JSON.stringify(observations,null,2));assert.equal(data.error,'');return data;};
  await waitTitle(1);await page.screenshot({path:resolve(evidence,'launcher-title.png')});let seen=await snapshot('title');assert.equal(seen.archiveBytes,77453661);assert.equal(seen.extractedAssets,false);assert.equal(seen.audio[5],0);
  await runtime.evaluate(()=>{window.livePositions={};const before=Module.onGameFrame;Module.onGameFrame=(...args)=>{before(...args);const c=Module,p=c._th15_probe_state(),s=c.HEAP32.subarray(p/4,p/4+16);if(s[0]===1&&s[14]===0){const q=c._th15_probe_player_state();window.livePositions[s[5]]=Array.from(new Float32Array(c.HEAPU8.buffer).subarray(q/4,q/4+2));}};});
  await key('KeyZ');await waitTitle(5);await key('ArrowDown');await key('KeyZ');await waitTitle(6);while((await state())[10]!==1)await key('ArrowDown');await key('KeyZ');await waitTitle(7);await key('KeyZ');await runtime.waitForFunction(()=>{const c=Module,p=c._th15_probe_player_state();return p&&c._th15_phase()===1&&new Float32Array(c.HEAPU8.buffer)[p/4+2]===1&&new Float32Array(c.HEAPU8.buffer)[p/4+3]>40;},null,{timeout:45000});
  seen=await snapshot('entered');assert.equal(seen.state[12]&0x300,0);assert.equal(seen.audio[5],1);await page.locator('#touchHelpClose').click().catch(()=>{});await page.locator('#touchFire').click();
  const beforeTouch=await runtime.evaluate(()=>{const p=Module._th15_probe_player_state();return Array.from(new Float32Array(Module.HEAPU8.buffer).subarray(p/4,p/4+2));});await rpc('direct-touch',{type:'down',id:41,x:.5,y:.75});await rpc('direct-touch',{type:'move',id:41,x:.56,y:.69});await waitTicks(25);await rpc('direct-touch',{type:'up',id:41,x:.56,y:.69});seen=await snapshot('continuous-touch');assert.ok(seen.player[0]>beforeTouch[0]+5);assert.ok(seen.player[1]<beforeTouch[1]-5);assert.equal(seen.player[2],1);
  const beforeBomb=seen.state[10];await rpc('touch-controls',{controls:{fireEnabled:false,focusEnabled:false,bombSerial:1,escapeSerial:0}});await waitTicks(8);seen=await snapshot('touch-bomb');assert.equal(seen.state[10],beforeBomb-1);await rpc('touch-controls',{controls:{fireEnabled:false,focusEnabled:false,bombSerial:1,escapeSerial:1}});await waitPause(6,0);seen=await snapshot('paused');assert.equal(seen.state[14],1);assert.equal(seen.audio[8],1);
  await key('ArrowDown');await key('ArrowDown');assert.equal((await pause())[2],2);await key('KeyZ');await waitPause(9,1);await waitTicks(20);await key('ArrowUp');await key('KeyZ');await waitPause(11,0);await key('KeyZ');await waitPause(12);await key('ArrowUp');await key('ArrowLeft');assert.equal((await pause())[4],90);await key('KeyZ');await waitPause(11);await key('KeyX');await waitTitle(1);await waitTicks(20);seen=await snapshot('saved-returned-title');assert.equal(seen.audio[5],0);assert.equal(seen.audio[8],0);
  await rpc('sync');const listing=(await rpc('list')).files;assert.ok(listing.some(f=>f.path==='scoreth15.dat'));assert.ok(listing.some(f=>f.path==='th15.cfg'));assert.ok(listing.some(f=>f.path==='replay/th15_00.rpyx'));const recording=(await rpc('read',{path:'replay/th15_00.rpyx'})).bytes;assert.ok(recording.length>0);await writeFile(resolve(evidence,'launcher-touch.rpyx'),new Uint8Array(recording));
  const livePositions=await runtime.evaluate(()=>window.livePositions);const compared=await runtime.evaluate(live=>{window.replayMatches=[];window.replayErrors=[];Module.onGameFrame=((before)=>(...args)=>{before(...args);const c=Module,p=c._th15_probe_state(),s=c.HEAP32.subarray(p/4,p/4+16);if(s[0]===1&&s[14]===0&&live[s[5]]){const q=c._th15_probe_player_state(),actual=Array.from(new Float32Array(c.HEAPU8.buffer).subarray(q/4,q/4+2)),expected=live[s[5]];if(actual[0]!==expected[0]||actual[1]!==expected[1])window.replayErrors.push({frame:s[5],actual,expected});else window.replayMatches.push(s[5]);}})(Module.onGameFrame);return Object.keys(live).length;},livePositions);assert.ok(compared>50);
  while((await state())[10]!==3)await key('ArrowDown');await key('KeyZ');await waitTitle(12);await key('KeyZ');await waitTitle(12,4);await waitTicks(20);await key('KeyZ');await runtime.waitForFunction(()=>Module._th15_phase()===1,null,{timeout:45000});await runtime.waitForFunction(()=>Module._th15_phase()===2,null,{timeout:45000});await waitPause(6,1);await key("KeyZ");await waitTitle(12);const replayCheck=await runtime.evaluate(()=>({matched:window.replayMatches.length,errors:window.replayErrors}));assert.ok(replayCheck.matched>30);assert.deepEqual(replayCheck.errors,[]);observations.push({kind:'actual-application-touch-replay',...replayCheck});
  await waitTitle(12);await key('KeyX');await waitTitle(1);while((await state())[10]!==8)await key('ArrowUp');assert.equal((await state())[10],8);await key('KeyZ');await page.waitForFunction(()=>!document.body.classList.contains('player-active'),null,{timeout:30000});assert.deepEqual(errors,[]);await page.screenshot({path:resolve(evidence,'launcher-exited.png')});
  const manifest=JSON.parse(await readFile(resolve(site,'manifest.json'),'utf8'));report('sdl-final-launcher',{passed:true,completeGame:false,manifestVersion:manifest.version,wasmSha256:manifest.execution.sha256,observations,replayBytes:recording.length,scope:'Local development package: actual final launcher, original compressed TH15 archive, compiled C++/SDL3 RAF, protocol keyboard and continuous touch/B/escape, native pause/name/slot replay save, title music and browser-local player files. Exact player coordinates compared on overlapping real callback frames during saved touch replay. Desktop Chromium software GPU; whole-world native parity, all-stage natural clears, phone hardware and public deployment remain unverified.'});
 }catch(e){if(page){await writeFile(resolve(evidence,'launcher-failure.json'),JSON.stringify({error:String(e),errors,observations,text:await page.evaluate(()=>document.body.innerText.slice(0,12000)).catch(()=>''),frames:await Promise.all(page.frames().map(async f=>({url:f.url(),text:await f.evaluate(()=>document.body.innerText.slice(0,4000)).catch(()=>''),probe:await f.evaluate(()=>({module:!!window.Module,probe:typeof window.Module?._th15_probe_state,phase:window.Module?._th15_phase?.(),state:window.Module?._th15_probe_state?Array.from(window.Module.HEAP32.subarray(window.Module._th15_probe_state()/4,window.Module._th15_probe_state()/4+16)):null,pause:window.Module?._th15_probe_pause_state?Array.from(window.Module.HEAP32.subarray(window.Module._th15_probe_pause_state()/4,window.Module._th15_probe_pause_state()/4+7)):null})).catch(()=>null)}))),runtimeError:runtime?await runtime.evaluate(()=>{const c=Module,p=c._th15_error();return new TextDecoder().decode(c.HEAPU8.subarray(p,c.HEAPU8.indexOf(0,p)));}).catch(()=>null):null},null,2));await page.screenshot({path:resolve(evidence,'launcher-failure.png')}).catch(()=>{});}throw e;}finally{await browser?.close();await new Promise(r=>server.close(r));}
});
