import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {launchBrowser} from '../../../th10_web/scripts/native/browser-launch.mjs';
import {root,report,sha} from '../cpp/helpers.mjs';
import {launcherServer,startLauncherPage,runtimeFrame,rpc} from './launcher-fixture.mjs';
test('Original data and measured font files retain one immutable package buffer across real launcher restarts',{timeout:300000},async()=>{
 const server=await launcherServer(),index=JSON.parse(await readFile(resolve(server.site,'runtime/th15/th15.data.json'),'utf8'));let browser,page,runtime;const errors=[],observations=[];
 try{
  assert.equal(index.files.length,11);assert.equal(index.remote_package_size,129629300);assert.deepEqual(index.files.filter(f=>f.filename.startsWith('/fonts/')).map(f=>f.filename).sort(),[...Array.from({length:8},(_,i)=>'/fonts/font'+i+'.bin'),'/fonts/cp932.bin','/fonts/blend4444.bin'].sort());
  browser=await launchBrowser({args:['--enable-unsafe-swiftshader','--autoplay-policy=no-user-gesture-required']});page=await startLauncherPage(browser,{viewport:{width:1000,height:800}});page.on('pageerror',e=>errors.push(String(e)));await page.goto(server.url);await page.locator('#changelogConfirm').click();await page.locator('button[data-game="th15"]').click();
  for(let cycle=0;cycle<2;cycle++){
   if(cycle)await page.locator('button[data-game="th15"]').click();
   await page.locator('#launch').click();await page.waitForFunction(()=>!!document.querySelector('#gameFrame')?.contentWindow?.Module?._th15_probe_state?.(),null,{timeout:150000});runtime=runtimeFrame(page);await runtime.waitForFunction(()=>{const c=Module,p=c._th15_probe_state();return c.HEAP32[p/4]===0&&c.HEAP32[p/4+8]===1&&c.HEAP32[p/4+9]===2;},null,{timeout:30000});
   const seen=await runtime.evaluate(files=>{const c=Module,buffer=c.FS.lookupPath('/th15.dat').node.contents.buffer;return {heapBytes:c.HEAPU8.length,backingBytes:buffer.byteLength,files:files.map(f=>{const node=c.FS.lookupPath(f.filename).node;return {name:f.filename,size:node.usedBytes,byteOffset:node.contents.byteOffset,shared:node.contents.buffer===buffer};}),unusedFallback:c.FS.analyzePath('/fonts/font8.bin').exists,phase:c._th15_phase()};},index.files);observations.push({cycle,...seen});assert.equal(seen.phase,0);assert.equal(seen.unusedFallback,false);assert.equal(seen.backingBytes,index.remote_package_size);for(let i=0;i<index.files.length;i++){assert.equal(seen.files[i].size,index.files[i].end-index.files[i].start);assert.equal(seen.files[i].byteOffset,index.files[i].start);assert.equal(seen.files[i].shared,true,'MEMFS range must retain the original package view');}
   await runtime.evaluate(()=>{Module._th15_loop_stop();Module._th15_keys_clear();});const step=n=>runtime.evaluate(n=>{const c=Module;for(let i=0;i<n;i++)if(!c._th15_probe_tick())throw Error('Application stopped');const p=c._th15_probe_state();return Array.from(c.HEAP32.subarray(p/4,p/4+16));},n);const key=async code=>{await rpc(page,'keyboard',{code,down:true});await step(3);await rpc(page,'keyboard',{code,down:false});return step(3);};let state=await step(0);for(let taps=0;state[10]!==8;taps++){assert.ok(taps<12);state=await key('ArrowUp');}await runtime.evaluate(()=>Module._th15_loop_start());await rpc(page,'keyboard',{code:'KeyZ',down:true});await page.waitForFunction(()=>!document.body.classList.contains('player-active'),null,{timeout:30000});
  }
  assert.deepEqual(errors,[]);report('sdl-package-data-memory',{passed:true,completeGame:false,packageBytes:index.remote_package_size,unusedAlternateFontBytes:65099049,avoidedMemfsCopyBytes:index.remote_package_size,observations,wasmSha256:sha(await readFile(resolve(server.site,'runtime/th15/th15.wasm'))),scope:'Actual common launcher, compressed original archive, every normal original measured font and two real launch/exit cycles. All eleven MEMFS files retain the same immutable package backing buffer with exact byte ranges and original parser validation. The five alternate GDI faces remain in complete developer assets for fallback oracle tests; mobile hardware performance remains separate.'});
 }catch(e){await writeFile(resolve(root,'artifacts/cpp/verification/sdl-package-data-memory-failure.json'),JSON.stringify({error:String(e),errors,observations},null,2));throw e;}finally{await browser?.close();await server.close();}
});
