import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,writeFile,readdir} from 'node:fs/promises';
import {resolve} from 'node:path';
import {launchBrowser} from '../../../th10_web/scripts/native/browser-launch.mjs';
import {root,sha,report} from '../cpp/helpers.mjs';
const testPointdevice=process.env.TH15_APPLICATION_POINTDEVICE==='1';
const testRetry=process.env.TH15_APPLICATION_RETRY==='1';
const testTransition=process.env.TH15_APPLICATION_TRANSITION==='1'||testRetry;
const applicationOutput=resolve(root,process.env.TH15_RESTART_BUILD||'artifacts/sdl-application');
const renderScale=process.env.TH15_RESTART_SCALE==='2'?2:1;
const assets=(await readdir(resolve(root,'reference/assets'))).filter(n=>!n.endsWith('.dat'));
const fonts=(await readdir(resolve(root,'assets/sdl-native/fonts'))).filter(n=>n.endsWith('.bin'));
const songs=(await readdir(resolve(root,'assets/music'))).filter(n=>n.endsWith('.ogg'));
test('Pointdevice Restart retains its original background throughout the retry overlay',{timeout:300000},async()=>{
 const files=new Map([['/module.mjs',resolve(applicationOutput,'th15-application.mjs')],['/th15-application.wasm',resolve(applicationOutput,'th15-application.wasm')],...assets.map(n=>['/assets/'+n,resolve(root,'reference/assets',n)]),...fonts.map(n=>['/fonts/'+n,resolve(root,'assets/sdl-native/fonts',n)]),...songs.map(n=>['/music/'+n,resolve(root,'assets/music',n)])]);
 const html='<!doctype html><title>TH15 application integration development</title><canvas id="canvas" width="640" height="480"></canvas><script type="module">import create from "/module.mjs";window.fixture=await create({canvas:document.querySelector("canvas")});</script>';
 const server=createServer(async(req,res)=>{try{const path=new URL(req.url,'http://localhost').pathname;res.setHeader('Cross-Origin-Opener-Policy','same-origin');res.setHeader('Cross-Origin-Embedder-Policy','require-corp');if(path==='/'){res.setHeader('Content-Type','text/html');res.end(html);return;}const file=files.get(path);if(!file){res.writeHead(404).end();return;}res.setHeader('Content-Type',path.endsWith('.mjs')?'text/javascript':path.endsWith('.wasm')?'application/wasm':'application/octet-stream');res.end(await readFile(file));}catch(e){res.writeHead(500).end(String(e));}});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;const errors=[],observations=[];
 try{
  browser=await launchBrowser({args:['--enable-unsafe-swiftshader','--autoplay-policy=no-user-gesture-required']});const page=await browser.newPage();page.on('pageerror',e=>errors.push(String(e)));const url='http://127.0.0.1:'+server.address().port+'/';const prepare=async()=>{await page.goto(url);await page.waitForFunction(()=>window.fixture,{timeout:90000});
  await page.evaluate(async({assets,fonts,songs})=>{const c=fixture;for(const dir of ['assets','fonts','music'])c.FS.mkdir('/'+dir);for(const [dir,names] of [['assets',assets],['fonts',fonts],['music',songs]])for(const name of names){const response=await fetch('/'+dir+'/'+name);if(!response.ok)throw Error('Missing '+name);c.FS.writeFile('/'+dir+'/'+name,new Uint8Array(await response.arrayBuffer()));}c.FS.mkdir('/save');c.FS.mount(c.IDBFS,{},'/save');await new Promise((ok,no)=>c.FS.syncfs(true,e=>e?no(e):ok()));},{assets,fonts,songs});};await prepare();

  await page.evaluate(renderScale=>{const c=fixture;c._application_render_scale(renderScale);window.decode=p=>new TextDecoder().decode(c.HEAPU8.subarray(p,c.HEAPU8.indexOf(0,p)));window.state=()=>Array.from(c.HEAP32.subarray(c._application_state()/4,c._application_state()/4+16));window.pause=()=>Array.from(c.HEAP32.subarray(c._application_pause_state()/4,c._application_pause_state()/4+6));window.step=(held=0,pressed=0)=>{if(!c._application_step(held,pressed,0,60,0))throw Error(decode(c._application_error())+' '+state());return state();};window.frames=n=>{for(let n0=0;n0<n;n0++)step();};window.key=k=>{step(k,k);step();};window.waitTitle=(screen)=>{for(let n=0;n<250;n++){const s=step();if(s[0]===0&&s[8]===screen&&s[9]===2)return;}throw Error('Title '+screen+' '+state());};window.choose=(cursor,screen)=>{c._application_title_select(cursor);key(1);waitTitle(screen);};if(!c._application_initialize(0))throw Error(decode(c._application_error()));waitTitle(1);choose(0,5);choose(0,6);choose(0,7);c._application_title_select(0);key(1);for(let n=0;n<250&&state()[0]!==1;n++)step();frames(150);},renderScale);
  const inspect=async label=>{const value=await page.evaluate(()=>{const c=fixture,p=c._application_pixels(),bytes=c.HEAPU8.subarray(p,p+640*480*4);let black=0,purple=0,green=0,pixels=0;for(let y=60;y<460;y++)for(let x=34;x<414;x++){const i=(y*640+x)*4,a=bytes[i],g=bytes[i+1],b=bytes[i+2];pixels++;if(a+g+b<24)black++;if(a>g*1.15&&b>g*1.15&&a+b>60)purple++;if(g>a*1.3&&g>b*1.3&&g>30)green++;}return{state:state(),pause:pause(),transition:Array.from(c.HEAP32.subarray(c._application_transition_state()/4,c._application_transition_state()/4+9)),pixels,black,purple,green};});const screenshot=(process.env.TH15_RESTART_CONTROL==='1'?'restart-old-control-':'restart-')+label+'-'+renderScale+'x.png';await page.locator('canvas').screenshot({path:resolve(root,'artifacts/cpp/verification',screenshot)});observations.push({label,screenshot,...value});console.log('Restart sample',label,JSON.stringify(value));return value;};
  await inspect('before-death');
  await page.evaluate(()=>{if(!fixture._application_test_death())throw Error('Death failed');for(let n=0;n<100;n++){step();if(pause()[1]===6)break;}if(pause()[1]!==6||pause()[2]!==0)throw Error('Retry menu '+pause());key(1);for(let n=0;n<100;n++){if(state()[6]&0x10000)break;step();}if(!(state()[6]&0x10000))throw Error('Restart not entered '+state());});
  for(const [label,n]of [['retry-first',0],['retry-15',15],['retry-30',15],['retry-50',20]]){await page.evaluate(frames=>window.frames(frames),n);const value=await inspect(label);assert.equal(value.state[6]&0x10000,0x10000);if(process.env.TH15_RESTART_CONTROL!=='1'){if(label==='retry-15')assert.ok(value.purple>value.pixels*.3,'Original purple Restart backdrop missing '+JSON.stringify(value));assert.ok(value.purple+value.green>value.pixels*.5,'Restart backdrop became a flat fill at '+label+' '+JSON.stringify(value));if(label==='retry-50')assert.ok(value.green>value.pixels*.3,'Restart transition did not animate back to stage '+JSON.stringify(value));}}
  await page.evaluate(()=>frames(60));const resumed=await inspect('resumed');assert.equal(resumed.state[6]&0x10000,0);assert.ok(resumed.state[5]>20);assert.deepEqual(errors,[]);
  report((process.env.TH15_RESTART_CONTROL==='1'?'sdl-restart-background-old-control':'sdl-restart-background')+(renderScale===2?'-2x':''),{passed:true,wasmSha256:sha(await readFile(resolve(applicationOutput,'th15-application.wasm'))),renderScale,observations,scope:'Actual original assets in SDL3/WebGL2 application. Pointdevice Reimu Easy, controlled death through original lifecycle and actual GameOver Continue; screenshot/pixel checks sample Restart backdrop at first/15/30/50 frames and verify game resumes. Native full pixel matching and every later checkpoint are separate.'});await page.evaluate(()=>fixture._application_close());
 }finally{await browser?.close();await new Promise(r=>server.close(r));}
});
