import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {launchBrowser} from '../../../th10_web/scripts/native/browser-launch.mjs';
import {core,memory,string,root,report,sha} from '../cpp/helpers.mjs';
import {launcherServer,startLauncherPage,runtimeFrame,rpc} from './launcher-fixture.mjs';
test('Actual SDL presentation samples a real original-ECL spell and imports its replay timing',{timeout:600000},async()=>{
 const bytes=await readFile(resolve(root,'artifacts/cpp/verification/controlled-spell-clock.rpy')),c=await core(),r=c.replay_create(),p=c.allocate(bytes.length);let expected;
 try{memory(c,p,bytes.length).set(bytes);assert.equal(c.replay_open(r,p,bytes.length),1,string(c,c.replay_error(r)));const d=c.replay_data(r),dv=new DataView(c.memory.buffer);assert.equal(dv.getInt32(d+0xa0,true),1);assert.equal(dv.getInt32(d+0xa4+0x14+0x50,true),400);assert.equal(dv.getInt32(d+0xa4+0x14+0x60,true),7);expected=dv.getInt32(d+0xa4+0x1e4,true);assert.equal(c.spell_clock_valid(expected),1);}finally{c.release(p);c.replay_delete(r);}
 const server=await launcherServer();let browser,page,runtime;const errors=[],observations=[];
 try{
  browser=await launchBrowser({args:['--enable-unsafe-swiftshader','--autoplay-policy=no-user-gesture-required']});page=await startLauncherPage(browser,{viewport:{width:1000,height:800}});page.on('pageerror',e=>errors.push(String(e)));await page.goto(server.url);await page.locator('#changelogConfirm').click();await page.locator('button[data-game="th15"]').click();await page.locator('[data-action="manage-replay"]:visible').first().click();await page.locator('#replayDialog').waitFor({state:'visible'});
  const choosing=page.waitForEvent('filechooser');await page.locator('[data-action="import-replay"]').click();await(await choosing).setFiles({name:'th15_00.rpy',mimeType:'application/octet-stream',buffer:bytes});await page.waitForFunction(()=>document.querySelectorAll('#replayList .replay-row').length===1,null,{timeout:90000});await page.locator('[data-replay-close]').first().click();await page.locator('#launch').click();await page.waitForFunction(()=>!!document.querySelector('#gameFrame')?.contentWindow?.Module?._th15_probe_state?.(),null,{timeout:150000});runtime=runtimeFrame(page);
  await runtime.waitForFunction(()=>{const c=Module,p=c._th15_probe_state();return c.HEAP32[p/4]===0&&c.HEAP32[p/4+8]===1&&c.HEAP32[p/4+9]===2;},null,{timeout:30000});await runtime.evaluate(()=>{Module._th15_loop_stop();Module._th15_keys_clear();});
  const advance=n=>runtime.evaluate(n=>{const c=Module;for(let i=0;i<n;i++)if(!c._th15_probe_tick()){const p=c._th15_error();throw Error(new TextDecoder().decode(c.HEAPU8.subarray(p,c.HEAPU8.indexOf(0,p))));}const p=c._th15_probe_state();return Array.from(c.HEAP32.subarray(p/4,p/4+16));},n);
  const key=async code=>{await rpc(page,'keyboard',{code,down:true});await advance(3);await rpc(page,'keyboard',{code,down:false});return advance(3);};
  const menu=async(screen,phase=2)=>{for(let n=0;n<240;n++){const s=await advance(0);if(s[0]===0&&s[8]===screen&&s[9]===phase)return s;await advance(1);}throw Error('Menu unavailable '+screen+'/'+phase+' '+JSON.stringify(await advance(0)));};
  let state=await menu(1);while(state[10]!==3)state=await key('ArrowDown');await key('KeyZ');await menu(12);await key('KeyZ');for(let i=0;i<120;i++){state=await advance(1);if(state[0]===1)break;}assert.equal(state[0],1);
  let activeSamples=0,completed=null,lastFlags=-1;
  for(let ticks=0;ticks<2400;ticks+=5){state=await advance(5);assert.equal(state[0],1,'spell replay remains in its actual scene');const clock=await runtime.evaluate(()=>{const c=Module,p=c._th15_probe_spell_state();return Array.from(c.HEAP32.subarray(p/4,p/4+6));});if(clock[0]!==lastFlags){observations.push({stageFrame:state[5],clock});lastFlags=clock[0];}if(clock[0]&1){assert.ok(clock[0]&0x40,'after-draw sample records the spell start');activeSamples++;}if(clock[5]){completed={stageFrame:state[5],clock};break;}}
  assert.ok(activeSamples>20,'real spell runs for multiple rendered frames');assert.ok(completed,'real unmodified ECL finishes the spell');assert.equal(completed.clock[5],1);assert.ok(completed.clock[3]>100);assert.equal(completed.clock[4],expected,'after-draw completion reads the selected replay snapshot');assert.equal(completed.clock[0]&0x41,0,'finish clears both active and sampled bits');
  await advance(30);const score=await runtime.evaluate(()=>{const c=Module,p=c._th15_probe_hud_score();return Array.from(c.HEAP32.subarray(p/4,p/4+6));});observations.push({hudScore:score});assert.ok(score[0]>0,"actual original ECL and chapter rewards earn score");assert.ok(score[1]>0,"real HUD displays the earned score");assert.ok(score[1]<=score[0]);assert.ok(score[3]>=score[1]);assert.deepEqual(errors,[]);await runtime.locator('canvas').screenshot({path:resolve(root,'artifacts/cpp/verification/sdl-spell-clock-completed.png')});report('sdl-spell-clock',{passed:true,completeGame:false,controlledFixture:true,replaySha256:sha(bytes),wasmSha256:sha(await readFile(resolve(root,'artifacts/sdl-application/th15-application.wasm'))),activeSamples,completed,score,observations,scope:'Actual shared launcher, imported original-format controlled stage-3 spell-entry replay, unchanged original ECL/ANM resources, SDL3/WebGL2 draws and after-draw clock start/finish. Full power, seven reserve lives and held fire/focus are controlled replay setup; this is integration evidence, not an independently recorded original gameplay replay.'});
 }catch(e){await writeFile(resolve(root,'artifacts/cpp/verification/sdl-spell-clock-failure.json'),JSON.stringify({error:String(e),errors,observations},null,2));throw e;}finally{await browser?.close();await server.close();}
});
