import test from 'node:test';import assert from 'node:assert/strict';import {createServer} from 'node:http';import {readFile,writeFile} from 'node:fs/promises';import {createHash} from 'node:crypto';import {launchBrowser} from '../../../th10_web/scripts/native/browser-launch.mjs';
const project=new URL('../../',import.meta.url),output=new URL('artifacts/sdl-store/',project),sha=b=>createHash('sha256').update(b).digest('hex');
test('TH15 production SDL store preserves player score/config/replay through an actual browser IDBFS reload',async()=>{
 const files=new Map([['/module.mjs',new URL('th15-store.mjs',output)],['/th15-store.wasm',new URL('th15-store.wasm',output)],['/demo.rpy',new URL('reference/assets/demo0.rpy',project)]]),errors=[];
 const html='<!doctype html><title>TH15 save persistence verification</title><script type="module">import create from "/module.mjs";window.core=await create({});</script>';
 const server=createServer(async(req,res)=>{try{const path=new URL(req.url,'http://localhost').pathname;res.setHeader('Cross-Origin-Opener-Policy','same-origin');res.setHeader('Cross-Origin-Embedder-Policy','require-corp');if(path==='/'){res.setHeader('Content-Type','text/html');res.end(html);return;}const file=files.get(path);if(!file){res.writeHead(404).end();return;}res.setHeader('Content-Type',path.endsWith('.mjs')?'text/javascript':path.endsWith('.wasm')?'application/wasm':'application/octet-stream');res.end(await readFile(file));}catch(e){res.writeHead(500).end(String(e));}});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;
 try{browser=await launchBrowser();const page=await browser.newPage();page.on('pageerror',e=>errors.push(String(e)));const url='http://127.0.0.1:'+server.address().port+'/';
 const initialize=async()=>{await page.goto(url);await page.waitForFunction(()=>window.core,{timeout:90000});await page.evaluate(async()=>{const c=core;window.decode=p=>new TextDecoder().decode(c.HEAPU8.subarray(p,c.HEAPU8.indexOf(0,p)));window.nameCall=(fn,value,...args)=>{const bytes=new TextEncoder().encode(value+'\0'),p=c._malloc(bytes.length);c.HEAPU8.set(bytes,p);const result=c[fn](...args,p);c._free(p);if(!result)throw Error(decode(c._store_error()));return result;};window.sync=populate=>new Promise((ok,no)=>c.FS.syncfs(populate,e=>e?no(e):ok()));c.FS.mkdir('/save');c.FS.mount(c.IDBFS,{},'/save');await sync(true);nameCall('_store_initialize','/save');});};
 await initialize();const first=await page.evaluate(async()=>{const c=core,state=()=>Array.from(c.HEAP32.subarray(c._store_state()/4,c._store_state()/4+8));const before=state();if(!c._store_mutate()||!c._store_save())throw Error(decode(c._store_error()));const data=new Uint8Array(await fetch('/demo.rpy').then(r=>r.arrayBuffer()));c.FS.writeFile('/save/replay/th15_02.rpy',data);c.FS.writeFile('/save/replay/invalid.rpy',new Uint8Array([1,2,3]));c.FS.writeFile('/save/replay/th15_ud0190.rpy',new Uint8Array([1,2,3]));for(const name of ['th15_00.rpy','th15_26.rpy','other.rpy','th15_ud0186.rpy','th15_ud0200.rpy','th15_ud0200.rpyx'])c.FS.writeFile('/save/replay/'+name,data);c.FS.writeFile('/save/autosave/save2_3.dat',new Uint8Array([4,5,6]));if(!c._store_remove_checkpoint(2,3)||c.FS.analyzePath('/save/autosave/save2_3.dat').exists)throw Error('Checkpoint not removed');nameCall('_store_save_recording','TESTGRP',1,3);if(!c._store_catalog())throw Error(decode(c._store_error()));const after=state(),p=c._store_record_blocks(),blocks=Array.from(c.HEAPU8.subarray(p,p+c._store_record_size())),score=Array.from(c.FS.readFile('/save/scoreth15.dat')),config=Array.from(c.FS.readFile('/save/th15.cfg')),replay=Array.from(c.FS.readFile('/save/replay/th15_04.rpy')),names=Array.from({length:100},(_,i)=>decode(c._store_replay_name(i)));await sync(false);c._store_close();return {before,after,blocks,score,config,replay,names};});
 assert.equal(first.before[0],0);assert.deepEqual(first.before.slice(2,4),[100,80]);assert.equal(first.after[0],1);assert.deepEqual(first.after.slice(2,4),[42,37]);assert.equal(first.after[4],4);assert.deepEqual(first.names.slice(0,5),['','th15_02.rpy','','th15_04.rpy','']);assert.deepEqual(first.names.slice(25,29),['th15_ud0186.rpy','','th15_ud0200.rpyx','']);assert.equal(first.names.filter(Boolean).length,4);assert.ok(first.replay.length>36);assert.equal(Buffer.from(first.replay).readUInt32LE(),0x72353174);
 await initialize();const second=await page.evaluate(()=>{const c=core;if(!c._store_catalog())throw Error(decode(c._store_error()));const state=Array.from(c.HEAP32.subarray(c._store_state()/4,c._store_state()/4+8)),p=c._store_record_blocks();return {state,blocks:Array.from(c.HEAPU8.subarray(p,p+c._store_record_size())),score:Array.from(c.FS.readFile('/save/scoreth15.dat')),config:Array.from(c.FS.readFile('/save/th15.cfg')),replay:Array.from(c.FS.readFile('/save/replay/th15_04.rpy')),names:Array.from({length:100},(_,i)=>decode(c._store_replay_name(i))),removed:!c.FS.analyzePath('/save/autosave/save2_3.dat').exists,error:decode(c._store_error())};});assert.deepEqual(second.state,first.after);assert.deepEqual(second.names,first.names);for(const key of ['blocks','score','config','replay'])assert.deepEqual(second[key],first[key],key+' survives browser reload');assert.equal(second.removed,true);assert.equal(second.error,'');assert.deepEqual(errors,[]);await page.evaluate(()=>core._store_close());
 await writeFile(new URL('artifacts/cpp/verification/sdl-store.json',project),JSON.stringify({passed:true,completeGame:false,wasmSha256:sha(await readFile(new URL('th15-store.wasm',output))),scoreSha256:sha(Buffer.from(first.score)),configSha256:sha(Buffer.from(first.config)),savedReplaySha256:sha(Buffer.from(first.replay)),state:first.after,replayNames:first.names,scope:'Production SDL FileStore plus native RecordStore/GameConfig/Replay codecs, atomic MEMFS writes, actual IndexedDB-backed IDBFS flush and fresh Wasm/page reload. Original demo import, new native recording export/reopen through catalog, malformed replay exclusion and original autosave deletion. Full game scene integration and chapter checkpoint serialization are separate pending work.'},null,2)+'\n');
 }finally{await browser?.close();await new Promise(r=>server.close(r));}
});
