import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,writeFile,readdir} from 'node:fs/promises';
import {resolve} from 'node:path';
import {launchBrowser} from '../../../th10_web/scripts/native/browser-launch.mjs';
import {root,report,sha} from '../cpp/helpers.mjs';
const defs=JSON.parse(await readFile(resolve(root,'reference/sound-definitions.json'),'utf8'));
const samples=[...new Set(defs.samples.map(v=>v.name))];
const assets=[...samples,'thbgm.fmt','text.anm','ascii.anm','effect.anm','title.anm','title_v.anm','help.anm','musiccmt.txt','demo0.rpy','demo1.rpy','demo2.rpy',...Array.from({length:9},(_,i)=>'help_'+String(i+1).padStart(2,'0')+'.png')];
const fonts=(await readdir(resolve(root,'assets/sdl-native/fonts'))).filter(v=>v.endsWith('.bin'));
const songs=['th15_01.ogg','th15_02.ogg'];
test('TH15 real SDL3 title combines native menus, ANM layers, fonts, help images and staged music',async()=>{
 const files=new Map([['/module.mjs',resolve(root,'artifacts/sdl-title/th15-title.mjs')],['/th15-title.wasm',resolve(root,'artifacts/sdl-title/th15-title.wasm')],...assets.map(n=>['/assets/'+n,resolve(root,'reference/assets',n)]),...fonts.map(n=>['/fonts/'+n,resolve(root,'assets/sdl-native/fonts',n)]),...songs.map(n=>['/music/'+n,resolve(root,'assets/music',n)])]);
 const html='<!doctype html><title>TH15 SDL title integration fixture</title><canvas id="canvas" width="640" height="480"></canvas><script type="module">import create from "/module.mjs";window.fixture=await create({canvas:document.querySelector("canvas")});</script>';
 const server=createServer(async(req,res)=>{try{const path=new URL(req.url,'http://localhost').pathname;res.setHeader('Cross-Origin-Opener-Policy','same-origin');res.setHeader('Cross-Origin-Embedder-Policy','require-corp');if(path==='/'){res.setHeader('Content-Type','text/html');res.end(html);return;}const file=files.get(path);if(!file){res.writeHead(404).end();return;}res.setHeader('Content-Type',path.endsWith('.mjs')?'text/javascript':path.endsWith('.wasm')?'application/wasm':'application/octet-stream');res.end(await readFile(file));}catch(e){res.writeHead(500).end(String(e));}});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;const errors=[],observations=[];
 try{browser=await launchBrowser({args:['--enable-unsafe-swiftshader','--autoplay-policy=no-user-gesture-required']});const page=await browser.newPage();page.on('pageerror',e=>errors.push(String(e)));await page.goto('http://127.0.0.1:'+server.address().port+'/');await page.waitForFunction(()=>window.fixture,{timeout:90000});
 await page.evaluate(async({assets,fonts,songs})=>{const c=window.fixture;for(const dir of ['assets','fonts','music'])c.FS.mkdir('/'+dir);for(const[dir,names]of[['assets',assets],['fonts',fonts],['music',songs]])for(const name of names){const r=await fetch('/'+dir+'/'+name);if(!r.ok)throw Error('Missing '+name);c.FS.writeFile('/'+dir+'/'+name,new Uint8Array(await r.arrayBuffer()));}},{assets,fonts,songs});
 const inspect=async(kind)=>{const v=await page.evaluate(kind=>{const c=fixture,decode=p=>new TextDecoder().decode(c.HEAPU8.subarray(p,c.HEAPU8.indexOf(0,p))),p=c._title_pixels();return{kind,state:Array.from(c.HEAP32.subarray(c._title_state()/4,c._title_state()/4+12)),music:decode(c._title_music()),error:decode(c._title_error()),fontWrites:c._title_font_writes(),pixels:Array.from(c.HEAPU8.subarray(p,p+640*480*4))};},kind);const bytes=Buffer.from(v.pixels);delete v.pixels;v.pixelSha256=sha(bytes);v.visiblePixels=0;for(let i=0;i<bytes.length;i+=4)if(bytes[i]||bytes[i+1]||bytes[i+2])v.visiblePixels++;await page.locator('canvas').screenshot({path:resolve(root,'artifacts/cpp/verification/sdl-title-'+kind+'.png')});observations.push(v);await writeFile(resolve(root,'artifacts/cpp/verification/sdl-title-observed.json'),JSON.stringify({observations},null,2));return v;};
 await page.evaluate(()=>{const c=fixture,decode=p=>new TextDecoder().decode(c.HEAPU8.subarray(p,c.HEAPU8.indexOf(0,p)));window.state=()=>Array.from(c.HEAP32.subarray(c._title_state()/4,c._title_state()/4+12));window.step=(pressed=0,repeated=0)=>{if(!c._title_step(pressed|repeated,pressed,repeated))throw Error(decode(c._title_error())||'Title step stopped '+state());return state();};window.waitTitle=(screen,limit=250)=>{for(let n=0;n<limit;n++){const s=step();if(s[0]===screen&&s[1]===2)return s;}throw Error('Title state timed out '+state());};window.choose=(cursor,screen)=>{c._title_select(cursor);step(1);return waitTitle(screen);};if(!c._title_initialize(0))throw Error(decode(c._title_error()));waitTitle(1);});
 let v=await inspect('main');assert.equal(v.error,'');assert.equal(v.music,'th15_01.wav');assert.ok(v.visiblePixels>50000);
 await page.evaluate(()=>{if(!fixture._title_unlock())throw Error('Title unlock failed');choose(5,14);for(let n=0;n<25;n++)step();});v=await inspect('music-room');assert.ok(v.fontWrites>=25);assert.ok(v.visiblePixels>50000);
 await page.evaluate(()=>{fixture._title_select(1);step(1);for(let n=0;n<30;n++)step();step(1);for(let n=0;n<30;n++)step();});v=await inspect('music-playing');assert.equal(v.music,'th15_02.wav');
 const energy=await page.evaluate(()=>{const c=fixture,p=c._title_audio_mix(44100);if(!p)throw Error('Title mixer failed');let result=0;for(const v of new Float32Array(c.HEAPU8.buffer,p,88200)){if(!Number.isFinite(v))throw Error('Invalid title PCM');result+=v*v;}return result;});assert.ok(energy>1e-8);
 await page.evaluate(()=>{step(0x102);waitTitle(1);for(let n=0;n<20;n++)step();});v=await inspect('music-return');assert.equal(v.music,'th15_01.wav');
 for(const[index,screen,kind]of[[4,11,'player-data'],[3,12,'replay'],[6,3,'options']]){await page.evaluate(({index,screen})=>{choose(index,screen);for(let n=0;n<15;n++)step();},{index,screen});v=await inspect(kind);assert.equal(v.error,'');assert.ok(v.visiblePixels>50000);await page.evaluate(screen=>{step(0x102);if(screen===3)step(0x102);waitTitle(1);},screen);}
 await page.evaluate(()=>{fixture._title_select(7);step(1);for(let n=0;n<40;n++)step();});v=await inspect('help-page-1');assert.equal(v.state[0],17);assert.ok(v.visiblePixels>50000);
 await page.evaluate(()=>{step(1);for(let n=0;n<30;n++)step();});v=await inspect('help-page-2');assert.equal(v.state[0],17);assert.notEqual(v.pixelSha256,observations.find(v=>v.kind==='help-page-1').pixelSha256);
 await page.evaluate(()=>{step(0x102);for(let n=0;n<30;n++)step();step(0x102);waitTitle(1);});v=await inspect('help-return');assert.equal(v.music,'th15_01.wav');
 await page.evaluate(()=>{choose(0,5);choose(0,6);choose(1,7);fixture._title_select(2);step(1);for(let n=0;n<250;n++){if(state()[10]>=0)break;step();}if(state()[10]!==13)throw Error('Game launch destination missing');});v=await inspect('new-game');assert.equal(v.state[6],2);assert.equal(v.state[7],1);assert.equal(v.state[8],1);assert.equal(v.state[10],13);
 assert.deepEqual(errors,[]);await writeFile(resolve(root,'artifacts/cpp/verification/sdl-title-observed.json'),JSON.stringify({observations,energy},null,2)+'\n');report('sdl-title',{passed:true,completeGame:false,wasmSha256:sha(await readFile(resolve(root,'artifacts/sdl-title/th15-title.wasm'))),observations,energy,scope:'Actual SDL3/WebGL2 desktop Chromium title composition with original ANM resources, measured font atlases, 9-page manual upload path, native callback priorities and real Vorbis/effects mixer. Main/menu returns, music title restoration, manual next/previous and game destination request. Run factory, original final-frame GPU parity, saved catalog and mobile drivers remain outside this fixture.'});await page.evaluate(()=>fixture._title_close());
 }finally{await browser?.close();await new Promise(r=>server.close(r));}
});
